from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=28,
        y=111,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=2,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R358_VOLCANO_AREA_11,
        show_message = False,
        dst_x = 12,
        dst_y = 121,
        dst_z = 1,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=19,
        y=124,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R366_VOLCANO_AREA_13_WSAVE_POINT,
        show_message = False,
        dst_x = 11,
        dst_y = 69,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=18,
        y=109,
        z=4,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R366_VOLCANO_AREA_13_WSAVE_POINT,
        show_message = False,
        dst_x = 15,
        dst_y = 69,
        dst_z = 5,
        dst_z_half = False,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=25,
        y=108,
        z=4,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R364_VOLCANO_AREA_14,
        show_message = False,
        dst_x = 6,
        dst_y = 121,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
]
