from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=21,
        y=21,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R284_MOLEVILLE_MINES_AREA_18_MINECART_ROOM,
        show_message = False,
        dst_x = 4,
        dst_y = 55,
        dst_z = 2,
        dst_z_half = False,
    dst_f = SOUTH,
        x_bit_7 = False,
    ),
    RoomExit(
        x=21,
        y=22,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R284_MOLEVILLE_MINES_AREA_18_MINECART_ROOM,
        show_message = False,
        dst_x = 4,
        dst_y = 55,
        dst_z = 2,
        dst_z_half = False,
    dst_f = SOUTH,
        x_bit_7 = False,
    ),
]
