"""164 - MachineMadeBowyer"""

from randomizer.scripts.monster.script_imports import *

script = MonsterScript(
    [
        IfVarBitsClear(0x7EE004, [0]),
        SetVarBits(0x7EE004, [0]),
        DoMonsterBehaviour(0),
        Wait1TurnandRestartScript(),
        ClearVar(DESIGNATED_RANDOM_NUM_VAR),
        Set7EE005ToRandomNumber(upper_bound=7),
        IfVarLessThan(0x7EE000, 1),
        IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 4),
        CastSpell(StaticE, LightningOrb, Bolt),
        IncreaseVarBy1(0x7EE000),
        Wait1TurnandRestartScript(),
        IfVarLessThan(0x7EE000, 1),
        Attack(PhysicalAttack105, PhysicalAttack105, Gnight),
        IncreaseVarBy1(0x7EE000),
        Wait1TurnandRestartScript(),
        ClearVar(DESIGNATED_RANDOM_NUM_VAR),
        Set7EE005ToRandomNumber(upper_bound=7),
        IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 2),
        ClearVar(0x7EE001),
        ClearVar(ATTACK_PHASE_COUNTER),
        EnableCommand([COMMAND_ATTACK, COMMAND_SPECIAL, COMMAND_ITEM]),
        DisableCommand([COMMAND_ATTACK]),
        SetVarBits(0x7EE001, [0]),
        Attack(PhysicalAttack102),
        ClearVar(0x7EE000),
        Wait1TurnandRestartScript(),
        ClearVar(DESIGNATED_RANDOM_NUM_VAR),
        Set7EE005ToRandomNumber(upper_bound=7),
        IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 2),
        ClearVar(0x7EE001),
        ClearVar(ATTACK_PHASE_COUNTER),
        EnableCommand([COMMAND_ATTACK, COMMAND_SPECIAL, COMMAND_ITEM]),
        DisableCommand([COMMAND_SPECIAL]),
        SetVarBits(0x7EE001, [1]),
        Attack(PhysicalAttack103),
        ClearVar(0x7EE000),
        Wait1TurnandRestartScript(),
        ClearVar(0x7EE001),
        ClearVar(ATTACK_PHASE_COUNTER),
        EnableCommand([COMMAND_ATTACK, COMMAND_SPECIAL, COMMAND_ITEM]),
        DisableCommand([COMMAND_ITEM]),
        SetVarBits(0x7EE001, [2]),
        Attack(PhysicalAttack104),
        ClearVar(0x7EE000),
        StartCounterCommands(),
        IfHPBelow(0),
        DoMonsterBehaviour(3),
        RemoveTarget(SELF),
        Wait1TurnandRestartScript(),
        IfTargetedByItem([CarboCookie]),
        ClearVar(0x7EE000),
        ClearVar(0x7EE001),
        ClearVar(ATTACK_PHASE_COUNTER),
        EnableCommand([COMMAND_ATTACK, COMMAND_SPECIAL, COMMAND_ITEM]),
        Wait1TurnandRestartScript(),
    ]
)
