# 197 - CountDown

from randomizer.scripts.monster.script_imports import *

script = MonsterScript([
	IfVarBitsSet(0x7EE004, [0]),
	Wait1TurnandRestartScript(),
	IfVarLessThan(0x7EE000, 1),
	DoMonsterBehaviour(18),
	IncreaseVarBy1(0x7EE000),
	RunBattleDialog(53),
	CastSpell(Crystal, Crystal, IceRock),
	Wait1TurnandRestartScript(),
	IfVarLessThan(0x7EE000, 2),
	DoMonsterBehaviour(19),
	IncreaseVarBy1(0x7EE000),
	RunBattleDialog(54),
	SetTarget(RANDOM_ALLY_OR_SELF),
	CastSpell(Recover),
	SetTarget(RANDOM_OPPONENT),
	Wait1TurnandRestartScript(),
	IfVarLessThan(0x7EE000, 3),
	DoMonsterBehaviour(20),
	IncreaseVarBy1(0x7EE000),
	RunBattleDialog(55),
	CastSpell(AuroraFlash),
	Wait1TurnandRestartScript(),
	IfVarLessThan(0x7EE000, 4),
	DoMonsterBehaviour(21),
	IncreaseVarBy1(0x7EE000),
	RunBattleDialog(56),
	SetTarget(RANDOM_ALLY_OR_SELF),
	CastSpell(MegaRecover),
	SetTarget(RANDOM_OPPONENT),
	Wait1TurnandRestartScript(),
	IfVarLessThan(0x7EE000, 5),
	DoMonsterBehaviour(22),
	IncreaseVarBy1(0x7EE000),
	RunBattleDialog(57),
	CastSpell(WaterBlast),
	Wait1TurnandRestartScript(),
	IfVarLessThan(0x7EE000, 6),
	DoMonsterBehaviour(23),
	IncreaseVarBy1(0x7EE000),
	RunBattleDialog(58),
	Wait1TurnandRestartScript(),
	IfVarLessThan(0x7EE000, 7),
	DoMonsterBehaviour(24),
	IncreaseVarBy1(0x7EE000),
	RunBattleDialog(59),
	CastSpell(PetalBlast),
	Wait1TurnandRestartScript(),
	DoMonsterBehaviour(25),
	ClearVar(0x7EE000),
	RunBattleDialog(60),
	CastSpell(Corona),
	StartCounterCommands(),
	IfHPBelow(0),
	IfLastMonsterStanding(),
	DoMonsterBehaviour(3),
	RemoveTarget(SELF),
	Wait1TurnandRestartScript(),
	IfHPBelow(0),
	IfVarBitsClear(0x7EE004, [1]),
	SetVarBits(0x7EE004, [1]),
	SetVarBits(0x7EE004, [0]),
	SetUntargetable(SELF),
	RunBattleDialog(221),
	DoMonsterBehaviour(26),
	Wait1TurnandRestartScript()
])
