"""224 - Mack"""

from randomizer.scripts.monster.script_imports import *

script = MonsterScript(
    [
        IfVarBitsSet(0x7EE001, [0]),
        IfVarBitsClear(0x7EE001, [7]),
        SetVarBits(0x7EE001, [7]),
        RunBattleDialog(132),
        Wait1TurnandRestartScript(),
        IfTurnCounterEquals(3),
        IfVarBitsClear(0x7EE003, [7]),
        IfVarLessThan(0x7EE000, 3),
        SetVarBits(0x7EE003, [7]),
        ClearVar(ATTACK_PHASE_COUNTER),
        SetUntargetable(MONSTER_1_SET),
        RunBattleEvent(BE0004_MACK_JUMPS_OUT_OF_BATTLE_OFF_SCREEN),
        Wait1TurnandRestartScript(),
        IfTurnCounterEquals(5),
        IfVarBitsClear(0x7EE003, [7]),
        IfVarBitsClear(0x7EE003, [0]),
        IfLastMonsterStanding(),
        CallTarget(MONSTER_2_CALL),
        CallTarget(MONSTER_3_CALL),
        CallTarget(MONSTER_4_CALL),
        CallTarget(MONSTER_5_CALL),
        SetVarBits(0x7EE003, [0]),
        ClearVar(0x7EE000),
        Wait1TurnandRestartScript(),
        IfVarBitsClear(0x7EE003, [7]),
        IfLastMonsterStanding(),
        CastSpell(FlameWall, FlameWall, Flame),
        Wait1TurnandRestartScript(),
        IfVarBitsClear(0x7EE003, [7]),
        Set7EE005ToRandomNumber(upper_bound=7),
        IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 4),
        Attack(PhysicalAttack13),
        ClearVar(DESIGNATED_RANDOM_NUM_VAR),
        Wait1TurnandRestartScript(),
        IfVarBitsClear(0x7EE003, [7]),
        CastSpell(FlameWall, Flame, Flame),
        Wait1TurnandRestartScript(),
        StartCounterCommands(),
        IfHPBelow(0),
        DoMonsterBehaviour(3),
        RemoveTarget(SELF),
        Wait1TurnandRestartScript(),
        IfTargetedBySpell([Thunderbolt]),
        SetVarBits(0x7EE001, [0]),
        Wait1TurnandRestartScript(),
    ]
)
