# 206 - Eggbert

from randomizer.scripts.monster.script_imports import *

script = MonsterScript([
	IfCurrentlyInFormationID(304),
	Wait1TurnandRestartScript(),
	Attack(PhysicalAttack118),
	RemoveTarget(SELF),
	Wait1TurnandRestartScript(),
	StartCounterCommands(),
	IfCurrentlyInFormationID(304),
	IfTargetedByRegularAttack(),
	IfVarBitsSet(0x7EE004, [0]),
	ClearVarBits(0x7EE007, [0]),
	SetTarget(MONSTER_1_SET),
	Attack(PhysicalAttack118),
	RemoveTarget(SELF),
	Wait1TurnandRestartScript(),
	IfCurrentlyInFormationID(304),
	IfTargetedByRegularAttack(),
	IfVarBitsSet(0x7EE004, [1]),
	ClearVarBits(0x7EE007, [1]),
	SetTarget(MONSTER_1_SET),
	Attack(PhysicalAttack118),
	RemoveTarget(SELF),
	Wait1TurnandRestartScript(),
	IfCurrentlyInFormationID(304),
	IfTargetedByRegularAttack(),
	IfVarBitsSet(0x7EE004, [2]),
	ClearVarBits(0x7EE007, [2]),
	SetTarget(MONSTER_1_SET),
	Attack(PhysicalAttack118),
	RemoveTarget(SELF),
	Wait1TurnandRestartScript(),
	IfCurrentlyInFormationID(304),
	IfTargetedByRegularAttack(),
	IfVarBitsSet(0x7EE004, [3]),
	ClearVarBits(0x7EE007, [3]),
	SetTarget(MONSTER_1_SET),
	Attack(PhysicalAttack118),
	RemoveTarget(SELF),
	Wait1TurnandRestartScript(),
	IfCurrentlyInFormationID(304),
	Wait1TurnandRestartScript(),
	IfTargetedByRegularAttack(),
	Attack(PhysicalAttack118),
	RemoveTarget(SELF),
	Wait1TurnandRestartScript()
])
