# 52 - Boomer

from randomizer.scripts.monster.script_imports import *

script = MonsterScript([
	IfVarEqualOrGreaterThan(0x7EE003, 2),
	IfVarBitsSet(0x7EE002, [1]),
	ClearVarBits(0x7EE002, [1]),
	SetVarBits(0x7EE002, [0]),
	ClearVar(0x7EE003),
	SetTarget(SELF),
	DoMonsterBehaviour(8),
	Wait1TurnandRestartScript(),
	IfVarEqualOrGreaterThan(0x7EE003, 2),
	IfVarBitsSet(0x7EE002, [0]),
	ClearVarBits(0x7EE002, [0]),
	SetVarBits(0x7EE002, [1]),
	ClearVar(0x7EE003),
	SetTarget(SELF),
	DoMonsterBehaviour(9),
	Wait1TurnandRestartScript(),
	ClearVar(DESIGNATED_RANDOM_NUM_VAR),
	Set7EE005ToRandomNumber(upper_bound=7),
	IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 4),
	Attack(PhysicalAttack1, PhysicalAttack1, Skewer),
	IncreaseVarBy1(0x7EE003),
	Wait1TurnandRestartScript(),
	CastSpell(Blizzard, Blast, Storm),
	IncreaseVarBy1(0x7EE003),
	StartCounterCommands(),
	IfHPBelow(0),
	DoMonsterBehaviour(3),
	RemoveTarget(SELF),
	Wait1TurnandRestartScript(),
	IfVarBitsSet(0x7EE002, [0]),
	IfTargetedByCommand([COMMAND_SPECIAL]),
	Attack(Shaker, AttackDoNothing, AttackDoNothing),
	Wait1TurnandRestartScript(),
	IfVarBitsSet(0x7EE002, [1]),
	IfTargetedByCommand([COMMAND_ATTACK]),
	Attack(Shaker, AttackDoNothing, AttackDoNothing),
	Wait1TurnandRestartScript()
])
