"""198 - DingALing"""

from randomizer.scripts.monster.script_imports import *

script = MonsterScript(
    [
        Set7EE005ToRandomNumber(upper_bound=9),
        IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 3),
        Attack(PhysicalAttack0),
        ClearVar(DESIGNATED_RANDOM_NUM_VAR),
        Wait1TurnandRestartScript(),
        IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 4),
        DoMonsterBehaviour(14),
        RunBattleDialog(220),
        IncreaseVarBy1(0x7EE000),
        ClearVar(DESIGNATED_RANDOM_NUM_VAR),
        Wait1TurnandRestartScript(),
        IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 6),
        DoMonsterBehaviour(16),
        SetVarBits(0x7EE00F, [1]),
        Attack(ScrowBell, DoomReverb, SporeChimes),
        ClearVarBits(0x7EE00F, [1]),
        ClearVar(DESIGNATED_RANDOM_NUM_VAR),
        Wait1TurnandRestartScript(),
        IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 8),
        DoMonsterBehaviour(17),
        CastSpell(DarkStar),
        ClearVar(DESIGNATED_RANDOM_NUM_VAR),
        Wait1TurnandRestartScript(),
        ClearVar(DESIGNATED_RANDOM_NUM_VAR),
        Set7EE005ToRandomNumber(upper_bound=7),
        IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 4),
        IfVarBitsSet(PARTY_SIZE, [0, 1]),
        IfTargetAlive(SLOT_1),
        DoMonsterBehaviour(15),
        SetTarget(SLOT_1),
        Attack(FearRoulette),
        Wait1TurnandRestartScript(),
        ClearVar(DESIGNATED_RANDOM_NUM_VAR),
        Set7EE005ToRandomNumber(upper_bound=7),
        IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 4),
        IfVarBitsSet(PARTY_SIZE, [0, 1]),
        IfTargetAlive(SLOT_2),
        DoMonsterBehaviour(15),
        SetTarget(SLOT_2),
        SetVarBits(0x7EE00E, [0]),
        Attack(FearRoulette),
        ClearVarBits(0x7EE00E, [0]),
        Wait1TurnandRestartScript(),
        IfVarBitsSet(PARTY_SIZE, [0, 1]),
        IfTargetAlive(SLOT_3),
        DoMonsterBehaviour(15),
        SetTarget(SLOT_3),
        SetVarBits(0x7EE00E, [1]),
        Attack(FearRoulette),
        ClearVarBits(0x7EE00E, [1]),
        Wait1TurnandRestartScript(),
        CastSpell(DarkStar),
        StartCounterCommands(),
    ]
)
