# 194 - Bundt

from randomizer.scripts.monster.script_imports import *

script = MonsterScript(
    [
        IfVarBitsClear(0x7EE000, [0]),
        Wait1TurnandRestartScript(),
        Set7EE005ToRandomNumber(upper_bound=7),
        IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 4),
        SetVarBits(0x7EE00F, [0]),
        Attack(PhysicalAttack0, PhysicalAttack31, LullaBye),
        ClearVarBits(0x7EE00F, [0]),
        ClearVar(DESIGNATED_RANDOM_NUM_VAR),
        IfVarEqualOrGreaterThan(0x7EE007, 1),
        IfVarBitsClear(0x7EE000, [7]),
        DecreaseVarBy1(0x7EE007),
        Wait1TurnandRestartScript(),
        IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 4),
        IfVarEqualOrGreaterThan(0x7EE007, 1),
        ClearVarBits(0x7EE000, [7]),
        Wait1TurnandRestartScript(),
        CastSpell(DiamondSaw, Blizzard, Blizzard),
        IfVarEqualOrGreaterThan(0x7EE007, 1),
        IfVarBitsClear(0x7EE000, [7]),
        DecreaseVarBy1(0x7EE007),
        Wait1TurnandRestartScript(),
        IfVarEqualOrGreaterThan(0x7EE007, 1),
        ClearVarBits(0x7EE000, [7]),
        Wait1TurnandRestartScript(),
        StartCounterCommands(),
        IfHPBelow(0),
        IfVarBitsClear(0x7EE000, [0]),
        IfVarBitsSet(0x7EE000, [1]),
        SetVarBits(0x7EE000, [0]),
        RunBattleEvent(BE0032_BUNDT_MOVES_AGAIN_BOTH_COOKS_RUN_AWAY),
        RemoveTarget(MONSTER_3_SET),
        RemoveTarget(MONSTER_4_SET),
        RunBattleEvent(BE0033_CANDLES_APPEAR_ON_BUNDT),
        SetUntargetable(MONSTER_3_SET),
        RunBattleEvent(BE0034_BLOW_THOSE_CANDLES_OUT),
        Wait1TurnandRestartScript(),
        IfVarEqualOrGreaterThan(0x7EE007, 5),
        SetTargetable(MONSTER_3_SET),
        RemoveTarget(MONSTER_3_SET),
        DoMonsterBehaviour(6),
        SetTargetable(MONSTER_2_SET),
        RemoveTarget(SELF),
        Wait1TurnandRestartScript(),
        IfTargetedByCommand([COMMAND_ATTACK]),
        IfVarBitsSet(0x7EE000, [0]),
        IncreaseVarBy1(0x7EE007),
        IfVarBitsClear(PARTY_SIZE, [0, 1]),
        SetVarBits(0x7EE000, [7]),
        Wait1TurnandRestartScript(),
    ]
)
