# 199 - Belome1

from randomizer.scripts.monster.script_imports import *

script = MonsterScript(
    [
        IfVarBitsClear(0x7EE004, [0]),
        SetVarBits(0x7EE004, [0]),
        SetTarget(RANDOM_OPPONENT),
        Attack(PhysicalAttack1),
        SetTarget(RANDOM_OPPONENT),
        Wait1TurnandRestartScript(),
        IfHPBelow(300, identifier="belome_hp"),
        IfVarBitsClear(0x7EE004, [1]),
        SetVarBits(0x7EE004, [1]),
        SetTarget(RANDOM_OPPONENT),
        Attack(ScrowFunk),
        SetTarget(RANDOM_OPPONENT),
        Wait1TurnandRestartScript(),
        IfTurnCounterEquals(3),
        IfVarBitsClear(0x7EE000, [0]),
        IfTargetAlive(SLOT_1),
        IfTargetAlive(SLOT_2),
        IfTargetAlive(SLOT_3),
        SetTarget(SLOT_1),
        RunBattleEvent(BE0002_BELOME_SWALLOWS_MALLOW),
        SetTarget(RANDOM_OPPONENT),
        Wait1TurnandRestartScript(),
        IfVarBitsSet(0x7EE000, [0]),
        SetTarget(RANDOM_OPPONENT),
        Attack(PhysicalAttack1),
        SetTarget(RANDOM_OPPONENT),
        Wait1TurnandRestartScript(),
        IfVarBitsSet(0x7EE004, [1]),
        Attack(PhysicalAttack1, ScrowFunk, SleepSauce),
        Wait1TurnandRestartScript(),
        Attack(PhysicalAttack1, PhysicalAttack1, SleepSauce),
        StartCounterCommands(),
        IfHPBelow(0),
        IfVarBitsSet(0x7EE000, [0]),
        RunBattleEvent(BE0006_BELOME_SPITS_OUT_MALLOW),
        DoMonsterBehaviour(3),
        RemoveTarget(SELF),
        Wait1TurnandRestartScript(),
        IfHPBelow(0),
        DoMonsterBehaviour(3),
        RemoveTarget(SELF),
        Wait1TurnandRestartScript(),
        IfTargetedByRegularAttack(),
        IfVarBitsSet(0x7EE000, [0]),
        IfVarEqualOrGreaterThan(0x7EE001, 2),
        ClearVarBits(0x7EE000, [0]),
        ClearVar(ATTACK_PHASE_COUNTER),
        RunBattleEvent(BE0006_BELOME_SPITS_OUT_MALLOW),
        Wait1TurnandRestartScript(),
        IfTargetedByCommand([COMMAND_SPECIAL]),
        IncreaseVarBy1(0x7EE001),
        IncreaseVarBy1(0x7EE001),
        Wait1TurnandRestartScript(),
        IfTargetedByRegularAttack(),
        IncreaseVarBy1(0x7EE001),
        Wait1TurnandRestartScript(),
    ]
)
