# 208 - Punchinello

from randomizer.scripts.monster.script_imports import *

script = MonsterScript(
    [
        IfVarBitsClear(0x7EE000, [0]),
        IfLastMonsterStanding(),
        DoMonsterBehaviour(0),
        CallTarget(MONSTER_2_CALL),
        DoMonsterBehaviour(0),
        CallTarget(MONSTER_3_CALL),
        DoMonsterBehaviour(0),
        CallTarget(MONSTER_4_CALL),
        DoMonsterBehaviour(0),
        CallTarget(MONSTER_5_CALL),
        Wait1TurnandRestartScript(),
        IfVarBitsSet(0x7EE000, [1]),
        IfLastMonsterStanding(),
        CallTarget(MONSTER_2_CALL),
        CallTarget(MONSTER_3_CALL),
        CallTarget(MONSTER_4_CALL),
        CallTarget(MONSTER_5_CALL),
        Wait1TurnandRestartScript(),
        IfVarBitsSet(0x7EE000, [2]),
        IfLastMonsterStanding(),
        ClearVar(0x7EE002),
        CallTarget(MONSTER_2_CALL),
        CallTarget(MONSTER_3_CALL),
        CallTarget(MONSTER_4_CALL),
        Wait1TurnandRestartScript(),
        Set7EE005ToRandomNumber(upper_bound=7),
        IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 1),
        CastSpell(SandStorm),
        ClearVar(DESIGNATED_RANDOM_NUM_VAR),
        Wait1TurnandRestartScript(),
        Attack(PhysicalAttack1),
        StartCounterCommands(),
        IfHPBelow(800, identifier="punch_hp_1"),
        IfLastMonsterStanding(),
        IfVarBitsClear(0x7EE004, [1]),
        SetVarBits(0x7EE004, [1]),
        SetVarBits(0x7EE000, [0, 1]),
        RunBattleEvent(BE0009_PUNCHINELLO_INTERLUDES_AND_PREPARES_TO_SUMMON_BOB_OMBS),
        Wait1TurnandRestartScript(),
        IfHPBelow(800, identifier="punch_hp_2"),
        IfVarBitsClear(0x7EE004, [1]),
        RunBattleEvent(BE0094_PUNCHINELLO_S_BOMBS_EXPLODE_IF_STILL_ALIVE),
        RemoveTarget(ALL_ALLIES_EXCLUDING_SELF),
        SetVarBits(0x7EE004, [1]),
        SetVarBits(0x7EE000, [0, 1]),
        RunBattleEvent(BE0009_PUNCHINELLO_INTERLUDES_AND_PREPARES_TO_SUMMON_BOB_OMBS),
        Wait1TurnandRestartScript(),
        IfHPBelow(400, identifier="punch_hp_3"),
        IfLastMonsterStanding(),
        IfVarBitsClear(0x7EE004, [0]),
        SetVarBits(0x7EE004, [0]),
        SetVarBits(0x7EE000, [2]),
        ClearVarBits(0x7EE000, [1]),
        RunBattleEvent(
            BE0010_PUNCHINELLO_INTERLUDES_AND_PREPARES_TO_SUMMON_MEZZO_BOMBS
        ),
        Wait1TurnandRestartScript(),
        IfHPBelow(400, identifier="punch_hp_4"),
        IfVarBitsClear(0x7EE004, [0]),
        RunBattleEvent(BE0094_PUNCHINELLO_S_BOMBS_EXPLODE_IF_STILL_ALIVE),
        RemoveTarget(ALL_ALLIES_EXCLUDING_SELF),
        SetVarBits(0x7EE004, [0]),
        SetVarBits(0x7EE000, [2]),
        ClearVarBits(0x7EE000, [1]),
        RunBattleEvent(
            BE0010_PUNCHINELLO_INTERLUDES_AND_PREPARES_TO_SUMMON_MEZZO_BOMBS
        ),
        Wait1TurnandRestartScript(),
        IfHPBelow(0),
        IfLastMonsterStanding(),
        DoMonsterBehaviour(3),
        RemoveTarget(SELF),
        Wait1TurnandRestartScript(),
        IfHPBelow(0),
        RunBattleEvent(BE0094_PUNCHINELLO_S_BOMBS_EXPLODE_IF_STILL_ALIVE),
        RemoveTarget(ALL_ALLIES_EXCLUDING_SELF),
        DoMonsterBehaviour(3),
        RemoveTarget(SELF),
        Wait1TurnandRestartScript(),
    ]
)
