"""251 - Valentina"""

from randomizer.scripts.monster.script_imports import *

script = MonsterScript(
    [
        IfVarBitsClear(0x7EE003, [0]),
        IfTargetAlive(SLOT_2),
        SetVarBits(0x7EE003, [0, 6]),
        SetUntargetable(SELF),
        RunBattleEvent(BE0048_VALENTINA_SUMMONS_DODO_DODO_CARRIES_OFF_MIDDLE_CHARACTER),
        Wait1TurnandRestartScript(),
        IfVarBitsClear(0x7EE003, [0]),
        SetVarBits(0x7EE003, [0, 1, 2, 5]),
        SetTargetable(MONSTER_2_SET),
        Wait1TurnandRestartScript(),
        IfVarEqualOrGreaterThan(0x7EE00D, 5),
        ClearVar(0x7EE00D),
        CastSpell(PetalBlast, AuroraFlash, LightBeam),
        Wait1TurnandRestartScript(),
        ClearVar(DESIGNATED_RANDOM_NUM_VAR),
        Set7EE005ToRandomNumber(upper_bound=7),
        IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 4),
        IfVarBitsSet(0x7EE003, [2]),
        CastSpell(Solidify, DrainBeam, DiamondSaw),
        IncreaseVarBy1(0x7EE00D),
        Wait1TurnandRestartScript(),
        IfVarBitsSet(0x7EE003, [2]),
        Attack(PhysicalAttack0),
        IncreaseVarBy1(0x7EE00D),
        Wait1TurnandRestartScript(),
        IfVarLessThan(DESIGNATED_RANDOM_NUM_VAR, 4),
        IfVarBitsSet(0x7EE003, [1]),
        CastSpell(WaterBlast, Blizzard, Crystal),
        IncreaseVarBy1(0x7EE00D),
        Wait1TurnandRestartScript(),
        IfVarBitsSet(0x7EE003, [1]),
        Attack(PhysicalAttack0),
        IncreaseVarBy1(0x7EE00D),
        Wait1TurnandRestartScript(),
        StartCounterCommands(),
        IfHPBelow(1200, identifier="return_dodo"),
        IfVarBitsSet(0x7EE003, [6]),
        IfVarBitsClear(0x7EE003, [2]),
        IfVarBitsSet(0x7EE003, [1]),
        SetVarBits(0x7EE003, [2]),
        ClearVarBits(0x7EE003, [3]),
        SetTargetable(MONSTER_2_SET),
        RunBattleEvent(BE0050_DODO_RETURNS_TO_VALENTINA_S_FORMATION),
        Wait1TurnandRestartScript(),
        IfHPBelow(0),
        DoMonsterBehaviour(3),
        RemoveTarget(ALL_ALLIES_AND_SELF),
        Wait1TurnandRestartScript(),
    ]
)
