# 192 - KnifeGuy

from randomizer.scripts.monster.script_imports import *

script = MonsterScript(
    [
        IfVarEqualOrGreaterThan(0x7EE002, 3),
        IfVarBitsClear(0x7EE000, [0]),
        IfTargetAlive(ALL_ALLIES_EXCLUDING_SELF),
        ClearVar(0x7EE001),
        SetVarBits(0x7EE000, [0]),
        RunBattleEvent(BE0018_KNIFE_GUY_GRATE_GUY_PAIR_UP_PIGGY_BACK),
        Wait1TurnandRestartScript(),
        IfVarBitsSet(0x7EE000, [0]),
        CastSpell(Blizzard, Crystal, Crystal),
        IncreaseVarBy1(0x7EE002),
        Wait1TurnandRestartScript(),
        Attack(PhysicalAttack1, PhysicalAttack1, PhysicalAttack20),
        IncreaseVarBy1(0x7EE002),
        StartCounterCommands(),
        IfHPBelow(0),
        IfLastMonsterStanding(),
        DoMonsterBehaviour(3),
        RemoveTarget(SELF),
        Wait1TurnandRestartScript(),
        IfHPBelow(0),
        IfVarBitsSet(0x7EE000, [0]),
        ClearVarBits(0x7EE000, [0]),
        RunBattleEvent(BE0019_KNIFE_GUY_GRATE_GUY_SEPARATE_YIKES_THEY_RE_PRETTY_TOUGH),
        DoMonsterBehaviour(3),
        RemoveTarget(SELF),
        Wait1TurnandRestartScript(),
        IfHPBelow(0),
        DoMonsterBehaviour(3),
        RemoveTarget(SELF),
        Wait1TurnandRestartScript(),
        IfTargetedByRegularAttack(),
        IncreaseVarBy1(0x7EE001),
        IfVarBitsSet(0x7EE000, [0]),
        IfVarEqualOrGreaterThan(0x7EE001, 5),
        ClearVarBits(0x7EE000, [0]),
        ClearVar(0x7EE002),
        RunBattleEvent(BE0019_KNIFE_GUY_GRATE_GUY_SEPARATE_YIKES_THEY_RE_PRETTY_TOUGH),
        Wait1TurnandRestartScript(),
    ]
)
