from .able_juice_prize import *
from .amulet_prize import *
from .antidote_pin_prize import *
from .attack_scarf_prize import *
from .bad_mushroom_prize import *
from .beetle_box_prize import *
from .bracer_prize import *
from .btub_ring_prize import *
from .chomp_prize import *
from .chomp_shell_prize import *
from .coin_trick_prize import *
from .courage_shell_prize import *
from .crystalline_prize import *
from .cymbals_prize import *
from .double_punch_prize import *
from .drill_claw_prize import *
from .earlier_times_prize import *
from .elixir_prize import *
from .enduring_brooch_prize import *
from .energizer_prize import *
from .exp_booster_prize import *
from .fearless_pin_prize import *
from .feather_prize import *
from .finger_shot_prize import *
from .fire_bomb_prize import *
from .fire_cape_prize import *
from .fire_dress_prize import *
from .fire_pants_prize import *
from .fire_shell_prize import *
from .fire_shirt_prize import *
from .flower_box_prize import *
from .flower_jar_prize import *
from .flower_tab_prize import *
from .freshen_up_prize import *
from .fright_bomb_prize import *
from .froggie_drink_prize import *
from .froggiestick_prize import *
from .frying_pan_prize import *
from .fuzzy_cape_prize import *
from .fuzzy_dress_prize import *
from .fuzzy_pants_prize import *
from .fuzzy_shirt_prize import *
from .ghost_medal_prize import *
from .goodie_bag_prize import *
from .hammer_prize import *
from .hand_cannon_prize import *
from .hand_gun_prize import *
from .happy_cape_prize import *
from .happy_pants_prize import *
from .happy_shell_prize import *
from .happy_shirt_prize import *
from .heal_shell_prize import *
from .hero_shirt_prize import *
from .honey_syrup_prize import *
from .hurly_gloves_prize import *
from .ice_bomb_prize import *
from .jinx_belt_prize import *
from .jump_shoes_prize import *
from .kerokero_cola_prize import *
from .lazy_shell_armor_prize import *
from .lazy_shell_weapon_prize import *
from .lucky_hammer_prize import *
from .lucky_jewel_prize import *
from .maple_syrup_prize import *
from .masher_prize import *
from .max_mushroom_prize import *
from .mega_cape_prize import *
from .mega_glove_prize import *
from .mega_pants_prize import *
from .mega_shirt_prize import *
from .megalixir_prize import *
from .mid_mushroom_prize import *
from .moldy_mush_prize import *
from .muku_cookie_prize import *
from .mushroom_prize import *
from .nautica_dress_prize import *
from .nok_nok_shell_prize import *
from .pants_prize import *
from .parasol_prize import *
from .pick_me_up_prize import *
from .poison_mushroom_prize import *
from .polka_dress_prize import *
from .power_blast_prize import *
from .prince_pants_prize import *
from .progressive_egg_prize import *
from .punch_glove_prize import *
from .pure_water_prize import *
from .quartz_charm_prize import *
from .rare_scarf_prize import *
from .red_essence_prize import *
from .regular_fireworks_prize import *
from .ribbit_stick_prize import *
from .rock_candy_prize import *
from .rotten_mush_prize import *
from .royal_dress_prize import *
from .royal_syrup_prize import *
from .safety_badge_prize import *
from .safety_ring_prize import *
from .sage_stick_prize import *
from .sailor_cape_prize import *
from .sailor_pants_prize import *
from .sailor_shirt_prize import *
from .scrooge_ring_prize import *
from .see_ya_prize import *
from .shirt_prize import *
from .signal_ring_prize import *
from .slap_glove_prize import *
from .sleepy_bomb_prize import *
from .sonic_cymbal_prize import *
from .spiked_link_prize import *
from .star_cape_prize import *
from .star_egg_prize import *
from .star_gun_prize import *
from .stella_023_prize import *
from .sticky_glove_prize import *
from .super_hammer_prize import *
from .super_slap_prize import *
from .super_suit_prize import *
from .teamwork_band_prize import *
from .thick_pants_prize import *
from .thick_shirt_prize import *
from .troopa_pin_prize import *
from .troopa_shell_prize import *
from .trueform_pin_prize import *
from .ultra_hammer_prize import *
from .wake_up_pin_prize import *
from .war_fan_prize import *
from .whomp_glove_prize import *
from .wilt_shroom_prize import *
from .wonder_chomp_prize import *
from .work_pants_prize import *
from .yoshi_ade_prize import *
from .yoshi_candy_prize import *
from .yoshi_cookie_prize import *
from .zoom_shoes_prize import *
