from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=1,
        y=78,
        z=10,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R350_SMITHY_FACTORY_AREA_01,
        show_message = False,
        dst_x = 7,
        dst_y = 20,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=16,
        y=53,
        z=10,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R222_SMITHY_FACTORY_AREA_03_GLUM_REAPERS,
        show_message = False,
        dst_x = 1,
        dst_y = 125,
        dst_z = 10,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=16,
        y=55,
        z=10,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R222_SMITHY_FACTORY_AREA_03_GLUM_REAPERS,
        show_message = False,
        dst_x = 1,
        dst_y = 125,
        dst_z = 10,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
