# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.helpers.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.helpers.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": 'EVENT_1644_set_0',
        "command": 'set',
        "args": [0x70df, 24]
    },
    {
        "identifier": 'EVENT_1644_fade_out_music_to_volume_1',
        "command": 'fade_out_music_to_volume',
        "args": [1, 127]
    },
    {
        "identifier": 'EVENT_1644_jmp_if_bit_set_2',
        "command": 'jmp_if_bit_set',
        "args": [0x7057, 4, 'EVENT_1644_enter_area_18']
    },
    {
        "identifier": 'EVENT_1644_jmp_if_bit_set_13',
        "command": 'jmp_if_bit_set',
        "args": [0x707a, 4, 'EVENT_1644_fade_in_from_black_async_16']
    },
    {
        "identifier": 'EVENT_1644_action_queue_async_14',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_1],
        "subscript": [
            {
                "identifier": 'EVENT_1644_action_queue_async_14_SUBSCRIPT_transfer_to_xyzf_0',
                "command": 'transfer_to_xyzf',
                "args": [20, 45, 24, RadialDirections.EAST]
            },
            {
                "identifier": 'EVENT_1644_action_queue_async_14_SUBSCRIPT_face_northeast_1',
                "command": 'face_northeast'
            }
        ]
    },
    {
        "identifier": 'EVENT_1644_set_action_script_sync_15',
        "command": 'set_action_script_sync',
        "args": [AreaObjects.NPC_1, 160]
    },
    {
        "identifier": 'EVENT_1644_fade_in_from_black_async_16',
        "command": 'jmp',
        "args": ['EVENT_1644_fade_in_from_black_async_21']
    },
    {
        "identifier": 'EVENT_1644_enter_area_18',
        "command": 'enter_area',
        "args": [Rooms._108_MOLEVILLE_OUTSIDE, RadialDirections.SOUTHWEST, 17, 44, 4, []]
    },
    {
        "identifier": 'EVENT_1644_jmp_if_bit_clear_19',
        "command": 'jmp_if_bit_clear',
        "args": [0x7042, 1, 'EVENT_1644_fade_in_from_black_async_21']
    },
    {
        "identifier": 'EVENT_1644_apply_tile_mod_20',
        "command": 'apply_tile_mod',
        "args": [Rooms._108_MOLEVILLE_OUTSIDE, 0, [_0x6AFlags.USE_ALTERNATE]]
    },
    {
        "identifier": 'EVENT_1644_fade_in_from_black_async_21',
        "command": 'fade_in_from_black_async'
    },
    {
        "identifier": 'EVENT_1644_jmp_if_bit_clear_7',
        "command": 'jmp_if_bit_clear',
        "args": [0x7087, 0, 'EVENT_1644_ret_26']
    },
    {
        "identifier": 'EVENT_1644_run_event_as_subroutine_25_',
        "command": 'run_event_as_subroutine',
        "args": [3588]
    },
    {
        "identifier": 'EVENT_1644_jmp_if_bit_clear_7_',
        "command": 'jmp_if_bit_clear',
        "args": [0x7099, 7, 'EVENT_1644_ret_26']
    },
    {
        "identifier": 'EVENT_1644_run_event_as_subroutine_25__',
        "command": 'run_event_as_subroutine',
        "args": [3897]
    },
    {
        "identifier": 'EVENT_1644_ret_26',
        "command": 'ret'
    }
]
