# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.data.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.data.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": "EVENT_3400_check_room",
        "command": "set_7000_to_current_level"
    },
    {
        "identifier": "EVENT_3400_room_7_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [7, "EVENT_3400_play_marrymore_music_indoors"]
    },
    {
        "identifier": "EVENT_3400_room_9_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [9, "EVENT_3400_play_marrymore_music_indoors"]
    },
    {
        "identifier": "EVENT_3400_room_17_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [17, "EVENT_3400_play_mushroom_kingdom_music"]
    },
    {
        "identifier": "EVENT_3400_room_20_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [20, "EVENT_3400_play_mushroom_kingdom_music"]
    },
    {
        "identifier": "EVENT_3400_room_24_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [24, "EVENT_3400_play_sunken_ship_music"]
    },
    {
        "identifier": "EVENT_3400_room_27_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [27, "EVENT_3400_play_sunken_ship_music"]
    },
    {
        "identifier": "EVENT_3400_room_28_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [28, "EVENT_3400_play_sunken_ship_music"]
    },
    {
        "identifier": "EVENT_3400_room_31_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [31, "EVENT_3400_play_mushroom_kingdom_music"]
    },
    {
        "identifier": "EVENT_3400_room_33_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [33, "EVENT_3400_play_yoster_isle_music"]
    },
    {
        "identifier": "EVENT_3400_room_34_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [34, "EVENT_3400_play_yoster_isle_music"]
    },
    {
        "identifier": "EVENT_3400_room_35_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [35, "EVENT_3400_play_booster_tower_music"]
    },
    {
        "identifier": "EVENT_3400_room_36_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [36, "EVENT_3400_play_booster_tower_music"]
    },
    {
        "identifier": "EVENT_3400_room_39_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [39, "EVENT_3400_play_booster_tower_music"]
    },
    {
        "identifier": "EVENT_3400_room_41_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [41, "EVENT_3400_play_booster_tower_music"]
    },
    {
        "identifier": "EVENT_3400_room_48_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [48, "EVENT_3400_play_booster_tower_music"]
    },
    {
        "identifier": "EVENT_3400_room_59_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [59, "EVENT_3400_play_dungeon_music"]
    },
    {
        "identifier": "EVENT_3400_room_60_jump",
        "command": 'jmp_if_7000_equals_short',
        "args": [60, "EVENT_3400_play_dungeon_music"]
    },
    {
        "identifier": "EVENT_3400_ret",
        "command": 'ret'
    },
    {
        "identifier": "EVENT_3400_play_marrymore_music_indoors",
        "command": 'fade_out_music_to_volume',
        "args": [1, 96]
    },
    {
        "identifier": "EVENT_3400_play_marrymore_music",
        "command": 'play_music_current_volume',
        "args": [Music._39_MARRYMORE]
    },
    {
        "identifier": "EVENT_3400_play_marrymore_music_ret",
        "command": 'ret'
    },
    {
        "identifier": "EVENT_3400_play_mushroom_kingdom_music",
        "command": 'play_music_current_volume',
        "args": [Music._02_MUSHROOM_KINGDOM]
    },
    {
        "identifier": "EVENT_3400_play_mushroom_kingdom_music_ret",
        "command": 'ret'
    },
    {
        "identifier": "EVENT_3400_play_sunken_ship_music",
        "command": 'play_music_current_volume',
        "args": [Music._41_SUNKEN_SHIP]
    },
    {
        "identifier": "EVENT_3400_play_sunken_ship_music_ret",
        "command": 'ret'
    },
    {
        "identifier": "EVENT_3400_play_yoster_isle_music",
        "command": 'play_music_current_volume',
        "args": [Music._04_YOSTER_ISLAND]
    },
    {
        "identifier": "EVENT_3400_play_yoster_isle_music_ret",
        "command": 'ret'
    },
    {
        "identifier": "EVENT_3400_play_booster_tower_music",
        "command": 'play_music_current_volume',
        "args": [Music._32_AND_MY_NAMES_BOOSTER]
    },
    {
        "identifier": "EVENT_3400_play_booster_tower_music_ret",
        "command": 'ret'
    },
    {
        "identifier": "EVENT_3400_play_dungeon_music",
        "command": 'play_music_current_volume',
        "args": [Music._27_DUNGEON_IS_FULL_OF_MONSTERS]
    },
    {
        "identifier": "EVENT_3400_play_dungeon_music_ret",
        "command": 'ret'
    }
]
