# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.data.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.data.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": "EVENT_3947_current_lvl",
        "command": 'set_7000_to_current_level'
    },
    {
        'identifier': 'EVENT_3947_room_5_jump', 
        'command': 'jmp_if_7000_equals_short', 
        'args': [470, 'EVENT_3947_ret']
    }, 
    {
        "identifier": 'EVENT_3947_set_7010_to_object_xyz_82',
        "command": 'set_7016_to_object_xyz',
        "args": [AreaObjects.MARIO]
    },
    {
        "identifier": 'EVENT_3947_set_7010_to_object_xyz_82)',
        "command": 'set_7010_to_object_xyz',
        "args": [AreaObjects.MARIO]
    },
    {
        "identifier": 'EVENT_3947_fade',
        "command": 'fade_out_to_black_async'
    },
    {
        "identifier": 'EVENT_3947_enter_area_36',
        "command": 'enter_area',
        "args": [470, RadialDirections.SOUTH, 7, 82, 0, []]
    },
    {
        "identifier": 'EVENT_3947_action_queue_sync_0',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_0],
        "subscript": [
            {
                "identifier": 'EVENT_2601_action_queue_sync_0_SUBSCRIPT_set_vram_priority_0',
                "command": 'visibility_off'
            }
        ]
    },
    {
        "identifier": 'EVENT_3947_action_queue_sync_1',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_1],
        "subscript": [
            {
                "identifier": 'EVENT_2601_action_queue_sync_0_SUBSCRIPT_set_vram_priority_0',
                "command": 'visibility_off'
            }
        ]
    },
    {
        "identifier": 'EVENT_3947_action_queue_sync_2',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_2],
        "subscript": [
            {
                "identifier": 'EVENT_2601_action_queue_sync_0_SUBSCRIPT_set_vram_priority_0',
                "command": 'visibility_off'
            }
        ]
    },
    {
        "identifier": 'EVENT_3947_action_queue_sync_3',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_3],
        "subscript": [
            {
                "identifier": 'EVENT_2601_action_queue_sync_0_SUBSCRIPT_set_vram_priority_0',
                "command": 'visibility_off'
            }
        ]
    },
    {
        "identifier": 'EVENT_3947_action_queue_sync_4',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_4],
        "subscript": [
            {
                "identifier": 'EVENT_2601_action_queue_sync_0_SUBSCRIPT_set_vram_priority_0',
                "command": 'visibility_off'
            }
        ]
    },
    {
        "identifier": 'EVENT_3947_action_queue_sync_5',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_5],
        "subscript": [
            {
                "identifier": 'EVENT_2601_action_queue_sync_0_SUBSCRIPT_set_vram_priority_0',
                "command": 'visibility_off'
            }
        ]
    },
    {
        "identifier": 'EVENT_3947_action_queue_sync_6',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_6],
        "subscript": [
            {
                "identifier": 'EVENT_2601_action_queue_sync_0_SUBSCRIPT_set_vram_priority_0',
                "command": 'visibility_off'
            }
        ]
    },
    {
        "identifier": 'EVENT_3947_action_queue_sync_12',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_12],
        "subscript": [
            {
                "identifier": 'EVENT_2601_action_queue_sync_0_SUBSCRIPT_set_vram_priority_0',
                "command": 'visibility_off'
            }
        ]
    },
    {
        "identifier": 'EVENT_3947_action_queue_sync_14',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_14],
        "subscript": [
            {
                "identifier": 'EVENT_2601_action_queue_sync_0_SUBSCRIPT_set_vram_priority_0',
                "command": 'visibility_off'
            }
        ]
    },
    {
        "identifier": 'EVENT_3947_remove_from_current_level_50',
        "command": 'remove_from_current_level',
        "args": [AreaObjects.MARIO]
    },
    {
        "identifier": 'EVENT_3947_circle_mask_static_51',
        "command": 'circle_mask_static',
        "args": [AreaObjects.MARIO, 96, 8]
    },
    {
        "identifier": 'EVENT_3947_fade_in_from_black_async_7_',
        "command": 'pause',
        "args": [180]
    },
    {
        "identifier": 'EVENT_3947_action_queue_async_3',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_14],
        "subscript": [
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_start_loop_n_times_0',
                "command": 'start_loop_n_times',
                "args": [3]
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_visibility_on_1',
                "command": 'visibility_on'
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_pause_2',
                "command": 'pause',
                "args": [8]
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_visibility_off_3',
                "command": 'visibility_off'
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_pause_4',
                "command": 'pause',
                "args": [8]
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_end_loop_5',
                "command": 'end_loop'
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_start_loop_n_times_6',
                "command": 'start_loop_n_times',
                "args": [3]
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_visibility_on_7',
                "command": 'visibility_on'
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_pause_8',
                "command": 'pause',
                "args": [4]
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_visibility_off_9',
                "command": 'visibility_off'
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_pause_10',
                "command": 'pause',
                "args": [4]
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_end_loop_11',
                "command": 'end_loop'
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_start_loop_n_times_12',
                "command": 'start_loop_n_times',
                "args": [3]
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_visibility_on_13',
                "command": 'visibility_on'
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_pause_14',
                "command": 'pause',
                "args": [2]
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_visibility_off_15',
                "command": 'visibility_off'
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_pause_16',
                "command": 'pause',
                "args": [2]
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_end_loop_17',
                "command": 'end_loop'
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_visibility_on_18',
                "command": 'visibility_on'
            },
            {
                "identifier": 'EVENT_3229_action_queue_async_3_SUBSCRIPT_pause_20',
                "command": 'pause',
                "args": [180]
            }
        ]
    },
    {
        "identifier": 'EVENT_3947_circle_mask_static_56',
        "command": 'circle_mask_static',
        "args": [AreaObjects.MARIO, 0, 8]
    },
    {
        "identifier": 'EVENT_3947_reload_level',
        "command": 'jmp_to_event',
        "args": [3948]
    },
    {
        "identifier": 'EVENT_3947_ret',
        "command": 'jmp_to_event',
        "args": [3400]
    }
]
