# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.data.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.data.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": 'EVENT_1116_set_0',
        "command": 'set',
        "args": [0x70a7, 150]
    },
    {
        "identifier": 'EVENT_1116_store_7000_item_quantity_to_70A7_1',
        "command": 'store_7000_item_quantity_to_70A7'
    },
    {
        "identifier": 'EVENT_1116_jmp_if_7000_equals_short_2',
        "command": 'jmp_if_7000_equals_short',
        "args": [1, 'EVENT_1116_open_shop_12']
    },
    {
        "identifier": 'EVENT_1116_set_3',
        "command": 'set',
        "args": [0x70a7, 152]
    },
    {
        "identifier": 'EVENT_1116_store_7000_item_quantity_to_70A7_4',
        "command": 'store_7000_item_quantity_to_70A7'
    },
    {
        "identifier": 'EVENT_1116_jmp_if_7000_equals_short_5',
        "command": 'jmp_if_7000_equals_short',
        "args": [1, 'EVENT_1116_open_shop_15']
    },
    {
        "identifier": 'EVENT_1116_set_6',
        "command": 'set',
        "args": [0x70a7, 151]
    },
    {
        "identifier": 'EVENT_1116_store_7000_item_quantity_to_70A7_7',
        "command": 'store_7000_item_quantity_to_70A7'
    },
    {
        "identifier": 'EVENT_1116_jmp_if_7000_equals_short_8',
        "command": 'jmp_if_7000_equals_short',
        "args": [1, 'EVENT_1116_open_shop_18']
    },
    {
        "identifier": 'EVENT_1116_open_shop_9',
        "command": 'jmp_to_event',
        "args": [1179]
    },
    {
        "identifier": 'EVENT_1116_open_shop_12',
        "command": 'jmp_to_event',
        "args": [1182]
    },
    {
        "identifier": 'EVENT_1116_open_shop_15',
        "command": 'jmp_to_event',
        "args": [1181]
    },
    {
        "identifier": 'EVENT_1116_open_shop_18',
        "command": 'jmp_to_event',
        "args": [1180]
    }
]
