# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.helpers.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.helpers.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": 'EVENT_869_____action_queue_async_181',
        "command": 'action_queue_async',
        "args": [AreaObjects.MEM_70A8],
        "subscript": [
            {
                "identifier": 'EVENT_869_reset_2',
                "command": 'set_sprite_sequence',
                "args": [0, 0, [_0x08Flags.READ_AS_MOLD, _0x08Flags.MIRROR_SPRITE]]
            },
            {
                "identifier": 'EVENT_869_pause_1',
                "command": 'pause',
                "args": [60]
            },
            {
                "identifier": 'ACTION_869_set_animation_speed_1',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_869_animate_fast',
                "command": 'set_sprite_sequence',
                "args": [10, 0, [_0x08Flags.READ_AS_SEQUENCE, _0x08Flags.LOOPING_OFF]]
            },
            {
                "identifier": 'EVENT_869_pause_1',
                "command": 'pause',
                "args": [120]
            },
            {
                "identifier": 'EVENT_869_reset',
                "command": 'set_sprite_sequence',
                "args": [0, 0, [_0x08Flags.READ_AS_MOLD, _0x08Flags.MIRROR_SPRITE]]
            },
            {
                "identifier": 'EVENT_869_pause_1',
                "command": 'pause',
                "args": [60]
            },
            {
                "identifier": 'ACTION_869_set_animation_speed_1',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_869_animate_fast',
                "command": 'set_sprite_sequence',
                "args": [10, 0, [_0x08Flags.READ_AS_SEQUENCE, _0x08Flags.LOOPING_OFF]]
            },
            {
                "identifier": 'EVENT_869_pause_1',
                "command": 'pause',
                "args": [120]
            },
            {
                "identifier": 'EVENT_869_reset_2',
                "command": 'set_sprite_sequence',
                "args": [0, 0, [_0x08Flags.READ_AS_MOLD, _0x08Flags.MIRROR_SPRITE]]
            },
            {
                "identifier": 'EVENT_869_pause_1',
                "command": 'pause',
                "args": [60]
            },
            {
                "identifier": 'ACTION_869_set_animation_speed_1',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FASTER, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_869_animate_fast',
                "command": 'set_sprite_sequence',
                "args": [10, 0, [_0x08Flags.READ_AS_SEQUENCE, _0x08Flags.LOOPING_OFF]]
            },
            {
                "identifier": 'EVENT_869_pause_1',
                "command": 'pause',
                "args": [120]
            },
            {
                "identifier": 'EVENT_869_reset_2',
                "command": 'set_sprite_sequence',
                "args": [0, 0, [_0x08Flags.READ_AS_MOLD, _0x08Flags.MIRROR_SPRITE]]
            },
            {
                "identifier": 'EVENT_869_pause_1',
                "command": 'pause',
                "args": [60]
            },
            {
                "identifier": 'ACTION_869_set_animation_speed_1',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.VERY_FAST, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_869_animate_fast',
                "command": 'set_sprite_sequence',
                "args": [10, 0, [_0x08Flags.READ_AS_SEQUENCE, _0x08Flags.LOOPING_OFF]]
            },
            {
                "identifier": 'EVENT_869_pause_1',
                "command": 'pause',
                "args": [120]
            },
            {
                "identifier": 'EVENT_869_reset_2',
                "command": 'set_sprite_sequence',
                "args": [0, 0, [_0x08Flags.READ_AS_MOLD, _0x08Flags.MIRROR_SPRITE]]
            },
            {
                "identifier": 'EVENT_869_pause_1',
                "command": 'pause',
                "args": [60]
            },
            {
                "identifier": 'ACTION_869_set_animation_speed_1',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FASTEST, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_869_animate_fast',
                "command": 'set_sprite_sequence',
                "args": [10, 0, [_0x08Flags.READ_AS_SEQUENCE, _0x08Flags.LOOPING_OFF]]
            },
            {
                "identifier": 'EVENT_869_pause_1',
                "command": 'pause',
                "args": [120]
            },
            {
                "identifier": 'EVENT_869_reset_2',
                "command": 'set_sprite_sequence',
                "args": [0, 0, [_0x08Flags.READ_AS_MOLD, _0x08Flags.MIRROR_SPRITE]]
            },
            {
                "identifier": 'EVENT_869_pause_1',
                "command": 'pause',
                "args": [60]
            },
            {
                "identifier": 'ACTION_869_set_animation_speed_1',
                "command": 'maximize_sequence_speed'
            },
            {
                "identifier": 'EVENT_869_animate_fast',
                "command": 'set_sprite_sequence',
                "args": [10, 0, [_0x08Flags.READ_AS_SEQUENCE, _0x08Flags.LOOPING_OFF]]
            },
            {
                "identifier": 'EVENT_869_pause_1',
                "command": 'pause',
                "args": [120]
            },
            {
                "identifier": 'EVENT_869_reset_2',
                "command": 'set_sprite_sequence',
                "args": [0, 0, [_0x08Flags.READ_AS_MOLD, _0x08Flags.MIRROR_SPRITE]]
            },
            {
                "identifier": 'EVENT_869_pause_1',
                "command": 'pause',
                "args": [60]
            },
            {
                "identifier": 'ACTION_869_set_animation_speed_1',
                "command": 'maximize_sequence_speed_86'
            },
            {
                "identifier": 'EVENT_869_animate_fast',
                "command": 'set_sprite_sequence',
                "args": [10, 0, [_0x08Flags.READ_AS_SEQUENCE, _0x08Flags.LOOPING_OFF]]
            },
            {
                "identifier": 'EVENT_869_pause_1',
                "command": 'pause',
                "args": [120]
            },
            {
                "identifier": 'EVENT_869_reset_2',
                "command": 'set_sprite_sequence',
                "args": [0, 0, [_0x08Flags.READ_AS_MOLD, _0x08Flags.MIRROR_SPRITE]]
            },
        ]
    },
    {
        "identifier": 'EVENT_869_ret',
        "command": 'ret'
    }
]
