# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.data.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.data.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": 'EVENT_1714_action_queue_sync_0',
        "command": 'action_queue_sync',
        "args": [AreaObjects.NPC_0],
        "subscript": [
            {
                "identifier": 'EVENT_1714_action_queue_sync_0_SUBSCRIPT_shift_west_pixels_0',
                "command": 'shift_west_pixels',
                "args": [4]
            }
        ]
    },
    {
        "identifier": 'EVENT_1714_sequence_setter',
        "command": 'run_event_as_subroutine',
        "args": [757]
    },
    {
        "identifier": 'EVENT_1714_jmp_if_bit_clear_1',
        "command": 'jmp_if_bit_clear',
        "args": [0x7077, 0, 'EVENT_1714_set_bit_3']
    },
    {
        "identifier": 'EVENT_1714_jmp_to_event_2',
        "command": 'run_event_as_subroutine',
        "args": [14]
    },
    {
        "identifier": 'EVENT_1714_ret_26',
        "command": 'jmp',
        "args": ['EVENT_1714_jmp_if_bit_clear_7']
    },
    {
        "identifier": 'EVENT_1714_set_bit_3',
        "command": 'set_bit',
        "args": [0x7077, 0]
    },
    {
        "identifier": 'EVENT_1714_fade_in_from_black_sync_4',
        "command": 'fade_in_from_black_sync'
    },
    {
        "identifier": 'EVENT_1714_action_queue_async_5',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_5],
        "subscript": [
            {
                "identifier": 'EVENT_1714_action_queue_async_5_SUBSCRIPT_visibility_on_0',
                "command": 'visibility_on'
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_5_SUBSCRIPT_set_sprite_sequence_1',
                "command": 'set_sprite_sequence',
                "args": [5, 0, [_0x08Flags.READ_AS_SEQUENCE, _0x08Flags.MIRROR_SPRITE]]
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_5_SUBSCRIPT_pause_2',
                "command": 'pause',
                "args": [135]
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_5_SUBSCRIPT_reset_properties_3',
                "command": 'reset_properties'
            }
        ]
    },
    {
        "identifier": 'EVENT_1714_action_queue_async_10',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_5],
        "subscript": [
            {
                "identifier": 'EVENT_1714_action_queue_async_10_SUBSCRIPT_play_sound_0',
                "command": 'play_sound',
                "args": [Sounds._033_JUMPING_BOUNCING_FISH, 4]
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_10_SUBSCRIPT_jump_to_height_1',
                "command": 'jump_to_height',
                "args": [96]
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_10_SUBSCRIPT_pause_2',
                "command": 'pause',
                "args": [8]
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_10_SUBSCRIPT_face_southwest_3',
                "command": 'face_southwest'
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_10_SUBSCRIPT_pause_4',
                "command": 'pause',
                "args": [8]
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_10_SUBSCRIPT_face_northwest_5',
                "command": 'face_northwest'
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_10_SUBSCRIPT_sequence_looping_on_6',
                "command": 'sequence_looping_on'
            }
        ]
    },
    {
        "identifier": 'EVENT_1714__pause_4',
        "command": 'pause',
        "args": [10]
    },
    {
        "identifier": 'EVENT_1714_action_queue_sync_13',
        "command": 'action_queue_sync',
        "args": [AreaObjects.NPC_5],
        "subscript": [
            {
                "identifier": 'EVENT_1714_action_queue_sync_13_SUBSCRIPT_set_priority_0',
                "command": 'set_priority',
                "args": [3]
            },
            {
                "identifier": 'EVENT_1714_action_queue_sync_13_SUBSCRIPT_set_animation_speed_1',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.WALKING, _0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_1714_action_queue_sync_13_SUBSCRIPT_walk_1_step_southwest_2',
                "command": 'walk_1_step_southwest'
            },
            {
                "identifier": 'EVENT_1714_action_queue_sync_13_SUBSCRIPT_play_sound_3',
                "command": 'play_sound',
                "args": [Sounds._033_JUMPING_BOUNCING_FISH, 4]
            },
            {
                "identifier": 'EVENT_1714_action_queue_sync_13_SUBSCRIPT_jump_to_height_4',
                "command": 'jump_to_height',
                "args": [96]
            },
            {
                "identifier": 'EVENT_1714_action_queue_sync_13_SUBSCRIPT_shift_south_steps_5',
                "command": 'shift_south_steps',
                "args": [4]
            },
            {
                "identifier": 'EVENT_1714_action_queue_sync_13_SUBSCRIPT_play_sound_6',
                "command": 'play_sound',
                "args": [Sounds._033_JUMPING_BOUNCING_FISH, 4]
            },
            {
                "identifier": 'EVENT_1714_action_queue_sync_13_SUBSCRIPT_jump_to_height_7',
                "command": 'jump_to_height',
                "args": [108]
            },
            {
                "identifier": 'EVENT_1714_action_queue_sync_13_SUBSCRIPT_shift_southeast_steps_8',
                "command": 'shift_southeast_steps',
                "args": [6]
            },
            {
                "identifier": 'EVENT_1714_action_queue_sync_13_SUBSCRIPT_object_memory_modify_bits_9',
                "command": 'object_memory_modify_bits',
                "args": [0x09, [5], [4, 6]]
            },
            {
                "identifier": 'EVENT_1714_action_queue_sync_13_SUBSCRIPT_set_animation_speed_10',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FASTER, [_0x10Flags.WALKING, _0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_1714_action_queue_sync_13_SUBSCRIPT_shift_east_steps_11',
                "command": 'shift_east_steps',
                "args": [6]
            },
            {
                "identifier": 'EVENT_1714_action_queue_sync_13_SUBSCRIPT_visibility_off_12',
                "command": 'visibility_off'
            }
        ]
    },
    {
        "identifier": 'EVENT_1714_action_queue_async_14',
        "command": 'action_queue_async',
        "args": [AreaObjects.SCREEN_FOCUS],
        "subscript": [
            {
                "identifier": 'EVENT_1714_action_queue_async_14_SUBSCRIPT_set_animation_speed_0',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_14_SUBSCRIPT_shift_south_steps_1',
                "command": 'shift_south_steps',
                "args": [4]
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_14_SUBSCRIPT_set_animation_speed_2',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FASTER, [_0x10Flags.WALKING, _0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_14_SUBSCRIPT_shift_southeast_steps_3',
                "command": 'shift_southeast_steps',
                "args": [6]
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_14_SUBSCRIPT_pause_4',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_14_SUBSCRIPT_shift_northwest_steps_5',
                "command": 'shift_northwest_steps',
                "args": [6]
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_14_SUBSCRIPT_set_animation_speed_6',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_14_SUBSCRIPT_shift_north_steps_7',
                "command": 'shift_north_steps',
                "args": [4]
            },
            {
                "identifier": 'EVENT_1714_action_queue_async_14_SUBSCRIPT_set_animation_speed_8',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.WALKING]]
            }
        ]
    },
    {
        "identifier": 'EVENT_1714_jmp_if_bit_clear_7',
        "command": 'jmp_if_bit_clear',
        "args": [0x7087, 0, 'EVENT_1714_ret_17']
    },
    {
        "identifier": 'EVENT_1714_run_event_as_subroutine_25_',
        "command": 'run_event_as_subroutine',
        "args": [3588]
    },
    {
        "identifier": 'EVENT_1714_jmp_if_bit_clear_7_',
        "command": 'jmp_if_bit_clear',
        "args": [0x7099, 7, 'EVENT_1714_ret_17']
    },
    {
        "identifier": 'EVENT_1714_run_event_as_subroutine_25__',
        "command": 'run_event_as_subroutine',
        "args": [3890]
    },
    {
        "identifier": 'EVENT_1714_ret_17',
        "command": 'ret'
    }
]
