# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.helpers.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.helpers.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": 'EVENT_1584_set_bit_0_',
        "command": 'jmp_if_bit_clear',
        "args": [0x7067, 7, 'EVENT_1584_set_bit_0']
    },
    {
        "identifier": "EVENT_1584_remove_block-",
        "command": "remove_from_current_level",
        "args": [AreaObjects.NPC_3],
    },
    {
        "identifier": "EVENT_1584_remove_note-",
        "command": "remove_from_current_level",
        "args": [AreaObjects.NPC_4],
    },
    {
        "identifier": "EVENT_1584_remove_block",
        "command": "remove_from_level",
        "args": [AreaObjects.NPC_3, Rooms._427_BELOME_TEMPLE_AREA_10_PIPE_TO_MONSTRO_TOWN],
    },
    {
        "identifier": "EVENT_1584_remove_note",
        "command": "remove_from_level",
        "args": [AreaObjects.NPC_4, Rooms._427_BELOME_TEMPLE_AREA_10_PIPE_TO_MONSTRO_TOWN],
    },

    {
        "identifier": 'EVENT_1584_set_bit_0',
        "command": 'jmp_if_bit_set',
        "args": [0x708A, 0, 'EVENT_1584_summon_to_level_248']
    },
    {
        "identifier": 'EVENT_1584_action_queue_async_4_',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_1],
        "subscript": [
            {
                "identifier": 'EVENT_1584_action_queue_async_4_SUBSCRIPT_shift_east_pixels_0',
                "command": 'shift_west_pixels',
                "args": [8]
            },
            {
                "identifier": 'EVENT_1584_action_queue_async_4_SUBSCRIPT_shift_north_pixels_1',
                "command": 'shift_south_pixels',
                "args": [8]
            }
        ]
    },
    {
        "identifier": 'EVENT_1584_action_queue_async_4__',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_2],
        "subscript": [
            {
                "identifier": 'EVENT_1584_action_queue_async_4_SUBSCRIPT_shift_east_pixels_0',
                "command": 'shift_west_pixels',
                "args": [8]
            },
            {
                "identifier": 'EVENT_1584_action_queue_async_4_SUBSCRIPT_shift_north_pixels_1',
                "command": 'shift_south_pixels',
                "args": [8]
            }
        ]
    },
    {
        "identifier": 'EVENT_1584_jmp_0',
        "command": 'jmp',
        "args": ['EVENT_1584_set_0']
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_248',
        "command": 'remove_from_level',
        "args": [AreaObjects.NPC_1, Rooms._427_BELOME_TEMPLE_AREA_10_PIPE_TO_MONSTRO_TOWN]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_248__',
        "command": 'remove_from_current_level',
        "args": [AreaObjects.NPC_1]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_248_',
        "command": 'remove_from_level',
        "args": [AreaObjects.NPC_2, Rooms._427_BELOME_TEMPLE_AREA_10_PIPE_TO_MONSTRO_TOWN]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_248___',
        "command": 'remove_from_current_level',
        "args": [AreaObjects.NPC_2]
    },
    {
        "identifier": 'EVENT_1584_set_0',
        "command": 'set',
        "args": [0x70df, 37]
    },
    {
        "identifier": 'EVENT_1584_jmp_if_bit_clear_1',
        "command": 'jmp_if_bit_clear',
        "args": [0x708c, 4, 'EVENT_1584_jmp_if_bit_clear_3']
    },
    {
        "identifier": 'EVENT_1584_set_2',
        "command": 'set',
        "args": [0x70df, 43]
    },
    {
        "identifier": 'EVENT_1584_jmp_if_bit_clear_3',
        "command": 'jmp_if_bit_clear',
        "args": [0x7050, 3, 'EVENT_1584_jmp_if_bit_set_5']
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_4',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_16, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_jmp_if_bit_set_5',
        "command": 'jmp_if_bit_set',
        "args": [0x7044, 6, 'EVENT_1584_set_bit_8']
    },
    {
        "identifier": 'EVENT_1584_fade_in_from_black_sync_44___',
        "command": 'fade_in_from_black_async'
    },
    {
        "identifier": 'EVENT_1584_jmp_0_',
        "command": 'jmp',
        "args": ['EVENT_1584_jmp_if_bit_clear_7']
    },
    {
        "identifier": 'EVENT_1584_set_bit_8',
        "command": 'set_bit',
        "args": [0x704f, 2]
    },
    {
        "identifier": 'EVENT_1584_clear_bit_9',
        "command": 'clear_bit',
        "args": [0x7050, 6]
    },
    {
        "identifier": 'EVENT_1584_clear_bit_10',
        "command": 'clear_bit',
        "args": [0x7094, 0]
    },
    {
        "identifier": 'EVENT_1584_clear_bit_11',
        "command": 'clear_bit',
        "args": [0x7050, 7]
    },
    {
        "identifier": 'EVENT_1584_set_12',
        "command": 'set',
        "args": [0x70ac, 0]
    },
    {
        "identifier": 'EVENT_1584_clear_bit_13',
        "command": 'clear_bit',
        "args": [0x7094, 2]
    },
    {
        "identifier": 'EVENT_1584_clear_bit_15',
        "command": 'clear_bit',
        "args": [0x7094, 1]
    },
    {
        "identifier": 'EVENT_1584_set_16',
        "command": 'set',
        "args": [0x70ad, 0]
    },
    {
        "identifier": 'EVENT_1584_remove_from_current_level_17',
        "command": 'remove_from_current_level',
        "args": [AreaObjects.NPC_0]
    },
    {
        "identifier": 'EVENT_1584_set_bit_18',
        "command": 'set_bit',
        "args": [0x704f, 0]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_19',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_0, Rooms._263_LANDS_END_UNDERGROUND_AREA_01]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_20',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_1, Rooms._263_LANDS_END_UNDERGROUND_AREA_01]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_21',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_2, Rooms._263_LANDS_END_UNDERGROUND_AREA_01]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_22',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_0, Rooms._264_LANDS_END_UNDERGROUND_AREA_02]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_23',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_1, Rooms._264_LANDS_END_UNDERGROUND_AREA_02]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_24',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_2, Rooms._264_LANDS_END_UNDERGROUND_AREA_02]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_25',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_0, Rooms._265_LANDS_END_UNDERGROUND_AREA_03]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_26',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_1, Rooms._265_LANDS_END_UNDERGROUND_AREA_03]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_27',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_2, Rooms._265_LANDS_END_UNDERGROUND_AREA_03]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_28',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_0, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_29',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_1, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_30',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_2, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_31',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_3, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_32',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_4, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_33',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_5, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_34',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_6, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_35',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_7, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_36',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_8, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_37',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_9, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_38',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_10, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_39',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_11, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_40',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_12, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_41',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_13, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_42',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_14, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_summon_to_level_43',
        "command": 'summon_to_level',
        "args": [AreaObjects.NPC_15, Rooms._262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS]
    },
    {
        "identifier": 'EVENT_1584_fade_in_from_black_sync_44',
        "command": 'fade_in_from_black_sync'
    },
    {
        "identifier": 'EVENT_1584_set_action_script_async_45',
        "command": 'set_action_script_async',
        "args": [AreaObjects.MARIO, 10]
    },
    {
        "identifier": 'EVENT_1584_jmp_if_bit_clear_7',
        "command": 'jmp_if_bit_clear',
        "args": [0x7087, 0, 'EVENT_1584_ret_26']
    },
    {
        "identifier": 'EVENT_1584_run_event_as_subroutine_25_',
        "command": 'run_event_as_subroutine',
        "args": [3588]
    },
    {
        "identifier": 'EVENT_1584_jmp_if_bit_clear_7_',
        "command": 'jmp_if_bit_clear',
        "args": [0x7099, 7, 'EVENT_1584_ret_26']
    },
    {
        "identifier": 'EVENT_1584_run_event_as_subroutine_25__',
        "command": 'run_event_as_subroutine',
        "args": [3908]
    },
    {
        "identifier": 'EVENT_1584_ret_26',
        "command": 'ret'
    }
]
