# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.data.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.data.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": 'EVENT_2652_stop_sound_0_',
        "command": 'jmp_if_bit_set',
        "args": [0x7086, 0, 'EVENT_2652_enter_area_43']
    },
    {
        "identifier": 'EVENT_2652_enter_area_43_',
        "command": 'enter_area',
        "args": [Rooms._315_SEASIDE_TOWN_DURING_YARIDOVICH_BEACH, RadialDirections.NORTHWEST, 12, 38, 0, [_0x68Flags.RUN_ENTRANCE_EVENT]]
    },
    {
        "identifier": "EVENT_2652_ret",
        "command": 'ret'
    },
    {
        "identifier": 'EVENT_2652_enter_area_43',
        "command": 'enter_area',
        "args": [Rooms._316_SEASIDE_TOWN_BEACH, RadialDirections.NORTHWEST, 12, 38, 0, [_0x68Flags.RUN_ENTRANCE_EVENT]]
    },
    {
        "identifier": "EVENT_2652_ret_",
        "command": 'ret'
    },
]
