# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.helpers.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.helpers.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": 'EVENT_754_jmp_if_bit_clear_0',
        "command": 'jmp_if_bit_clear',
        "args": [0x7081, 7, 'EVENT_754_enter_area_6']
    },
    {
        "identifier": 'EVENT_754_jmp_if_bit_clear_1',
        "command": 'jmp_if_bit_clear',
        "args": [0x7082, 0, 'EVENT_754_enter_area_8']
    },
    {
        "identifier": 'EVENT_754_enter_area_6',
        "command": 'enter_area',
        "args": [Rooms._491_MUSHROOM_KINGDOM_ITEM_SHOP_TOP_FLOOR, RadialDirections.NORTHWEST, 20, 23, 1, [_0x68Flags.RUN_ENTRANCE_EVENT, _0x68Flags.Z_HALF]]
    },
    {
        "identifier": 'EVENT_754_ret_7',
        "command": 'ret'
    },
    {
        "identifier": 'EVENT_754_enter_area_8',
        "command": 'enter_area',
        "args": [Rooms._483_MUSHROOM_KINGDOM_DURING_MACK_ITEM_SHOP_TOP_FLOOR, RadialDirections.NORTHWEST, 20, 23, 1, [_0x68Flags.RUN_ENTRANCE_EVENT, _0x68Flags.Z_HALF]]
    },
    {
        "identifier": 'EVENT_754_ret_11',
        "command": 'ret'
    }
]
