# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.helpers.eventtables import (
    ControllerDirections,
    RadialDirections,
    Rooms,
    Sounds,
    AreaObjects,
    NPCPackets,
    Locations,
    Shops,
    EventSequences,
    MenuTutorials,
    OverworldSequences,
    PlayableCharacters,
    EquipSlots,
    DialogDurations,
    IntroTitles,
    Colours,
    PaletteSetTypes,
    Music,
    MusicDirections,
    MusicPitch,
    Coords,
    CoordUnits,
    Tutorials,
    _0x40Flags,
    _0x60Flags,
    _0x62Flags,
    _0x63Flags,
    _0x68Flags,
    _0x6AFlags,
    _0x6BFlags,
    _0x81Flags,
    _0x84Flags,
)
from randomizer.helpers.objectsequencetables import (
    SequenceSpeeds,
    VramPriority,
    _0x08Flags,
    _0x0AFlags,
    _0x10Flags,
)
from randomizer.data import items

script = [
    {
        "identifier": "EVENT_3214_jmp_if_bit_set_182",
        "command": "jmp_if_bit_set",
        "args": [0x7058, 6, "EVENT_3214_fade_out_to_black_async_200"],
    },
    {
        "identifier": "EVENT_3214_start_battle_183",
        "command": "run_event_as_subroutine",
        "args": [354],
    },
    {"identifier": "EVENT_3214_set_bit_184", "command": "set_bit", "args": [0x707C, 5]},
    {
        "identifier": "EVENT_3214_clear_bit_185",
        "command": "clear_bit",
        "args": [0x707C, 6],
    },
    {
        "identifier": "EVENT_3214_clear_bit_186",
        "command": "clear_bit",
        "args": [0x707C, 7],
    },
    {
        "identifier": "EVENT_3214_run_event_as_subroutine_187",
        "command": "run_event_as_subroutine",
        "args": [24],
    },
    {"identifier": "EVENT_3214_restore_all_hp_188", "command": "restore_all_hp"},
    {"identifier": "EVENT_3214_restore_all_fp_189", "command": "restore_all_fp"},
    {"identifier": "EVENT_3214_set_bit_190", "command": "set_bit", "args": [0x7058, 6]},
    {
        "identifier": "EVENT_3214_enter_area_191",
        "command": "enter_area",
        "args": [
            Rooms._173_SUNKEN_SHIP_POSTKC_AREA_01_SMALL_ROOM_WTRAMPOLINE,
            RadialDirections.NORTHEAST,
            3,
            89,
            8,
            [_0x68Flags.RUN_ENTRANCE_EVENT],
        ],
    },
    {
        "identifier": "EVENT_3214_clear_bit_192",
        "command": "clear_bit",
        "args": [0x7049, 0],
    },
    {
        "identifier": "EVENT_3214_action_queue_sync_193",
        "command": "action_queue",
        "args": [AreaObjects.MARIO, True],
        "subscript": [
            {
                "identifier": "EVENT_3214_action_queue_sync_193_SUBSCRIPT_jump_to_height_silent_0",
                "command": "jump_to_height_silent",
                "args": [0],
            }
        ],
    },
    {"identifier": "EVENT_3214_pause_194", "command": "pause", "args": [20]},
    {
        "identifier": "EVENT_3214_set_short_195",
        "command": "jmp_to_event",
        "args": [168],
    },
    {"identifier": "EVENT_3214_ret_199", "command": "ret"},
    {
        "identifier": "EVENT_3214_fade_out_to_black_async_200",
        "command": "fade_out_to_black_async",
    },
    {"identifier": "EVENT_3214_set_bit_205", "command": "set_bit", "args": [0x7049, 0]},
    {
        "identifier": "EVENT_3214_enable_controls_206",
        "command": "enable_controls",
        "args": [[]],
    },
    {
        "identifier": "EVENT_3214_enter_area_207",
        "command": "enter_area",
        "args": [
            Rooms._173_SUNKEN_SHIP_POSTKC_AREA_01_SMALL_ROOM_WTRAMPOLINE,
            RadialDirections.SOUTH,
            2,
            92,
            8,
            [_0x68Flags.RUN_ENTRANCE_EVENT],
        ],
    },
    {
        "identifier": "EVENT_3214_action_queue_sync_208",
        "command": "action_queue",
        "args": [AreaObjects.MARIO, True],
        "subscript": [
            {
                "identifier": "EVENT_3214_action_queue_sync_208_SUBSCRIPT_jump_to_height_silent_0",
                "command": "jump_to_height_silent",
                "args": [0],
            }
        ],
    },
    {"identifier": "EVENT_3214_ret_209", "command": "ret"},
]
