# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.helpers.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.helpers.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": 'EVENT_2407_jmp_if_var_equals_byte_27',
        "command": 'jmp_if_var_equals_byte',
        "args": [0x70ae, 6, 'EVENT_2407_freeze_camera_29']
    },
    {
        "identifier": 'EVENT_2407_ret_28',
        "command": 'ret'
    },
    {
        "identifier": 'EVENT_2407_freeze_camera_29',
        "command": 'freeze_camera'
    },
    {
        "identifier": 'EVENT_2407_action_queue_async_30',
        "command": 'action_queue_async',
        "args": [AreaObjects.MARIO],
        "subscript": [
            {
                "identifier": 'EVENT_2407_action_queue_async_30_SUBSCRIPT_walk_1_step_northeast_0',
                "command": 'walk_1_step_northeast'
            },
            {
                "identifier": 'EVENT_2407_action_queue_async_30_SUBSCRIPT_visibility_off_1',
                "command": 'visibility_off'
            }
        ]
    },
    {
        "identifier": 'EVENT_2407_pause_31',
        "command": 'pause',
        "args": [32]
    },
    {
        "identifier": 'EVENT_2407_db_32',
        "command": 'db',
        "args": [0xfd, 0x8d]
    },
    {
        "identifier": 'EVENT_2407_apply_tile_mod_33',
        "command": 'apply_tile_mod',
        "args": [Rooms._159_STAR_HILL_AREA_04, 13, [_0x6AFlags.USE_ALTERNATE]]
    },
    {
        "identifier": 'EVENT_2407_play_sound_34',
        "command": 'play_sound',
        "args": [Sounds._126_EMERGE_DEEP_WATER, 6]
    },
    {
        "identifier": 'EVENT_2407_unfreeze_camera_35',
        "command": 'unfreeze_camera'
    },
    {
        "identifier": 'EVENT_2407_pause_36',
        "command": 'pause',
        "args": [32]
    },
    {
        "identifier": 'EVENT_2407_fade_out_to_black_async_duration_37',
        "command": 'fade_out_to_black_async_duration',
        "args": [16]
    },
    {
        "identifier": 'EVENT_2407_play_sound_38',
        "command": 'play_sound',
        "args": [Sounds._125_ENTER_DEEP_WATER, 6]
    },
    {
        "identifier": 'EVENT_2407_open_location_41',
        "command": 'open_location',
        "args": [Locations._031_STAR_HILL, [6, 7]]
    }
]
