from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=10,
        y=99,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=1,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R327_MUSHROOM_KINGDOM_CASTLE_DURING_MACK_STAIRWELL_TO_TOADSTOOLS_ROOM,
        show_message = False,
        dst_x = 26,
        dst_y = 20,
        dst_z = 2,
        dst_z_half = True,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=13,
        y=93,
        z=2,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R328_MUSHROOM_KINGDOM_CASTLE_DURING_MACK_TOADSTOOLS_ROOM,
        show_message = True,
        dst_x = 3,
        dst_y = 66,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=20,
        y=96,
        z=4,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=1,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R329_MUSHROOM_KINGDOM_CASTLE_DURING_MACK_BRANCH_ROOM_TO_VAULTGUEST_ROOM,
        show_message = False,
        dst_x = 16,
        dst_y = 69,
        dst_z = 1,
        dst_z_half = True,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
]
