# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.data.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.data.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": 'EVENT_2074_enter_area_0',
        "command": 'enter_area',
        "args": [Rooms._351_CULEXS_ROOM, RadialDirections.NORTH, 29, 45, 0, []]
    },
    {
        "identifier": 'EVENT_2074_action_queue_sync_1',
        "command": 'action_queue_sync',
        "args": [AreaObjects.SCREEN_FOCUS],
        "subscript": [
            {
                "identifier": 'EVENT_2074_action_queue_sync_1_SUBSCRIPT_shift_east_pixels_0',
                "command": 'shift_east_pixels',
                "args": [12]
            }
        ]
    },
    {
        "identifier": 'EVENT_2074_action_queue_async_2',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_0],
        "subscript": [
            {
                "identifier": 'EVENT_2074_action_queue_async_2_SUBSCRIPT_sequence_looping_on_0',
                "command": 'sequence_looping_on'
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_2_SUBSCRIPT_set_sprite_sequence_1',
                "command": 'set_sprite_sequence',
                "args": [8, 0, [_0x08Flags.READ_AS_SEQUENCE]]
            }
        ]
    },
    {
        "identifier": 'EVENT_2074_set_action_script_sync_3',
        "command": 'set_action_script_sync',
        "args": [AreaObjects.LAYER_1, 575]
    },
    {
        "identifier": 'EVENT_2074_fade_in_from_black_async_duration_4',
        "command": 'fade_in_from_black_async_duration',
        "args": [70]
    },
    {
        "identifier": 'EVENT_2074_pause_5',
        "command": 'pause',
        "args": [60]
    },
    {
        "identifier": 'EVENT_2074_action_queue_async_6',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_0],
        "subscript": [
            {
                "identifier": 'EVENT_2074_action_queue_async_6_SUBSCRIPT_set_animation_speed_0',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_6_SUBSCRIPT_shift_south_steps_1',
                "command": 'shift_south_steps',
                "args": [1]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_6_SUBSCRIPT_pause_2',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_6_SUBSCRIPT_shift_south_steps_3',
                "command": 'shift_south_steps',
                "args": [1]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_6_SUBSCRIPT_pause_4',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_6_SUBSCRIPT_shift_south_steps_5',
                "command": 'shift_south_steps',
                "args": [1]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_6_SUBSCRIPT_pause_6',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_6_SUBSCRIPT_shift_south_steps_7',
                "command": 'shift_south_steps',
                "args": [1]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_6_SUBSCRIPT_pause_8',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_6_SUBSCRIPT_shift_south_steps_9',
                "command": 'shift_south_steps',
                "args": [1]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_6_SUBSCRIPT_pause_10',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_6_SUBSCRIPT_shift_south_steps_11',
                "command": 'shift_south_steps',
                "args": [1]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_6_SUBSCRIPT_pause_12',
                "command": 'pause',
                "args": [30]
            }
        ]
    },
    {
        "identifier": 'EVENT_2074_jmp_if_bit_set_7',
        "command": 'jmp_if_bit_set',
        "args": [0x708a, 6, 'EVENT_2074_run_dialog_16']
    },
    {
        "identifier": 'EVENT_2074_run_dialog_8',
        "command": 'run_dialog',
        "args": [3056, AreaObjects.NPC_14, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE]]
    },
    {
        "identifier": 'EVENT_2074_run_dialog_9',
        "command": 'run_dialog',
        "args": [3057, AreaObjects.NPC_14, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE]]
    },
    {
        "identifier": 'EVENT_2074_set_bit_10',
        "command": 'set_bit',
        "args": [0x708a, 6]
    },
    {
        "identifier": 'EVENT_2074_jmp_if_dialog_option_b_11',
        "command": 'jmp_if_dialog_option_b',
        "args": ['EVENT_2074_run_dialog_19']
    },
    {
        "identifier": 'EVENT_2074_run_dialog_12',
        "command": 'run_dialog',
        "args": [3061, AreaObjects.NPC_14, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE]]
    },
    {
        "identifier": 'EVENT_2074_start_battle_13',
        "command": 'start_battle',
        "args": [0x00d8, 47]
    },
    {
        "identifier": 'EVENT_2074_jmp_if_bit_clear_14',
        "command": 'jmp_if_bit_clear',
        "args": [0x7040, 0, 'EVENT_2074_fade_in_from_black_async_29']
    },
    {
        "identifier": 'EVENT_2074_reset_and_choose_game_15',
        "command": 'reset_and_choose_game'
    },
    {
        "identifier": 'EVENT_2074_run_dialog_16',
        "command": 'run_dialog',
        "args": [3059, AreaObjects.NPC_14, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE]]
    },
    {
        "identifier": 'EVENT_2074_jmp_if_dialog_option_b_17',
        "command": 'jmp_if_dialog_option_b',
        "args": ['EVENT_2074_run_dialog_19']
    },
    {
        "identifier": 'EVENT_2074_jmp_18',
        "command": 'jmp',
        "args": ['EVENT_2074_run_dialog_12']
    },
    {
        "identifier": 'EVENT_2074_run_dialog_19',
        "command": 'run_dialog',
        "args": [3058, AreaObjects.NPC_14, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE]]
    },
    {
        "identifier": 'EVENT_2074_jmp_20',
        "command": 'jmp',
        "args": ['EVENT_2074_action_queue_async_21']
    },
    {
        "identifier": 'EVENT_2074_action_queue_async_21',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_0],
        "subscript": [
            {
                "identifier": 'EVENT_2074_action_queue_async_21_SUBSCRIPT_set_animation_speed_0',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_21_SUBSCRIPT_shift_north_steps_1',
                "command": 'shift_north_steps',
                "args": [1]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_21_SUBSCRIPT_pause_2',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_21_SUBSCRIPT_shift_north_steps_3',
                "command": 'shift_north_steps',
                "args": [1]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_21_SUBSCRIPT_pause_4',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_21_SUBSCRIPT_shift_north_steps_5',
                "command": 'shift_north_steps',
                "args": [1]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_21_SUBSCRIPT_pause_6',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_21_SUBSCRIPT_shift_north_steps_7',
                "command": 'shift_north_steps',
                "args": [1]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_21_SUBSCRIPT_pause_8',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_21_SUBSCRIPT_shift_north_steps_9',
                "command": 'shift_north_steps',
                "args": [1]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_21_SUBSCRIPT_pause_10',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_21_SUBSCRIPT_shift_north_steps_11',
                "command": 'shift_north_steps',
                "args": [1]
            },
            {
                "identifier": 'EVENT_2074_action_queue_async_21_SUBSCRIPT_pause_12',
                "command": 'pause',
                "args": [30]
            }
        ]
    },
    {
        "identifier": 'EVENT_2074_jmp_if_bit_set_22',
        "command": 'jmp_if_bit_set',
        "args": [0x7093, 4, 'EVENT_2074_apply_solidity_mod_25']
    },
    {
        "identifier": 'EVENT_2074_enter_area_23',
        "command": 'enter_area',
        "args": [Rooms._324_MONSTRO_TOWN_OUTSIDE, RadialDirections.SOUTHWEST, 11, 63, 4, []]
    },
    {
        "identifier": 'EVENT_2074_jmp_24',
        "command": 'jmp',
        "args": ['EVENT_2048_set_bit_0']
    },
    {
        "identifier": 'EVENT_2074_apply_solidity_mod_25',
        "command": 'apply_solidity_mod',
        "args": [Rooms._324_MONSTRO_TOWN_OUTSIDE, 0, []]
    },
    {
        "identifier": 'EVENT_2074_apply_tile_mod_26',
        "command": 'apply_tile_mod',
        "args": [Rooms._324_MONSTRO_TOWN_OUTSIDE, 33, [_0x6AFlags.USE_ALTERNATE]]
    },
    {
        "identifier": 'EVENT_2074_enter_area_27',
        "command": 'enter_area',
        "args": [Rooms._324_MONSTRO_TOWN_OUTSIDE, RadialDirections.SOUTHWEST, 11, 63, 4, []]
    },
    {
        "identifier": 'EVENT_2074_jmp_28',
        "command": 'jmp',
        "args": ['EVENT_2048_set_bit_0']
    },
    {
        "identifier": 'EVENT_2074_fade_in_from_black_async_29',
        "command": 'fade_in_from_black_async'
    },
    {
        "identifier": 'EVENT_2074_pause_30',
        "command": 'pause',
        "args": [5]
    },
    {
        "identifier": 'EVENT_2074_play_music_default_volume_31',
        "command": 'play_music_default_volume',
        "args": [Music._58_CONVERSATION_WITH_CULEX]
    },
    {
        "identifier": 'EVENT_2074_pause_32',
        "command": 'pause',
        "args": [60]
    },
    {
        "identifier": 'EVENT_2074_run_dialog_33',
        "command": 'run_dialog',
        "args": [3060, AreaObjects.NPC_14, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE]]
    },
    {
        "identifier": 'EVENT_2074_pause_34',
        "command": 'pause',
        "args": [15]
    },
    {
        "identifier": 'EVENT_2074_set_35',
        "command": 'set',
        "args": [0x70a7, 94]
    },
    {
        "identifier": 'EVENT_2074_set_36',
        "command": 'set',
        "args": [0x7000, 3355]
    },
    {
        "identifier": 'EVENT_2074_run_event_as_subroutine_37',
        "command": 'run_event_as_subroutine',
        "args": [3829]
    },
    {
        "identifier": 'EVENT_2074_pause_38',
        "command": 'pause',
        "args": [15]
    },
    {
        "identifier": 'EVENT_2074_run_dialog_39',
        "command": 'run_dialog',
        "args": [3354, AreaObjects.NPC_14, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE]]
    },
    {
        "identifier": 'EVENT_2074_set_bit_40',
        "command": 'set_bit',
        "args": [0x7093, 4]
    },
    {
        "identifier": 'EVENT_2074_restore_all_hp_41',
        "command": 'restore_all_hp'
    },
    {
        "identifier": 'EVENT_2074_restore_all_fp_42',
        "command": 'restore_all_fp'
    },
    {
        "identifier": 'EVENT_2074_jmp_43',
        "command": 'jmp',
        "args": ['EVENT_2074_action_queue_async_21']
    }
]
