from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=14,
        y=53,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=1,
        nw_se_edge_active = True,
        ne_sw_edge_active = True,
        byte_2_bit_2 = False,
        destination = R007_MARRYMORE_INN_1F,
        show_message = False,
        dst_x = 7,
        dst_y = 60,
        dst_z = 0,
        dst_z_half = True,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=16,
        y=43,
        z=2,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R009_MARRYMORE_INN_REGULAR_ROOM,
        show_message = False,
        dst_x = 14,
        dst_y = 20,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=13,
        y=41,
        z=3,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=1,
        nw_se_edge_active = True,
        ne_sw_edge_active = True,
        byte_2_bit_2 = False,
        destination = R011_MARRYMORE_INN_3F,
        show_message = False,
        dst_x = 12,
        dst_y = 73,
        dst_z = 1,
        dst_z_half = True,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
