from randomizer.types.bosses.enums import BossLocations
from randomizer.types.world.flags.enums import (
    AvailableMusic,
    BanditsWayGating,
    BarrelVolcanoGating,
    BelomeTempleGating,
    BoosterTowerGating,
    BossScaleOptions,
    BowsersKeepGating,
    EXPChallengeOptions,
    EXPMultiplierOptions,
    EquipmentCharactersOptions,
    EquipmentPropertiesOptions,
    FactoryGating,
    FireworksOptions,
    ForestMazeGating,
    ItemQualities,
    LearnableSpells,
    MarrymoreGating,
    Moleville1Gating,
    MonstroTownGating,
    PipeVaultGating,
    PlayableCharacters,
    SeaGating,
    ShopQualities,
    ShuffleLocationSelector,
    WinConditions,
    YaridovichGating,
)


REGULAR_CHECKS = [  # excludes key item checks. can't turn those off
    ShuffleLocationSelector.MariosPadStarter1,
    ShuffleLocationSelector.MariosPadStarter2,
    ShuffleLocationSelector.MariosPadStarter3,
    ShuffleLocationSelector.MariosPadStarter4,
    ShuffleLocationSelector.MariosPadBed,
    ShuffleLocationSelector.MushroomWay1,
    ShuffleLocationSelector.MushroomWay2,
    ShuffleLocationSelector.MushroomWay3,
    ShuffleLocationSelector.MushroomWay4,
    ShuffleLocationSelector.HammerBrosReward,
    ShuffleLocationSelector.MushroomKingdomHallway,
    ShuffleLocationSelector.PeachSurprise,
    ShuffleLocationSelector.MushroomKingdomVault1,
    ShuffleLocationSelector.MushroomKingdomVault2,
    ShuffleLocationSelector.MushroomKingdomVault3,
    ShuffleLocationSelector.MushroomKingdomStore,
    ShuffleLocationSelector.MushroomKingdomStoreBasement1,
    ShuffleLocationSelector.MushroomKingdomStoreBasement2,
    ShuffleLocationSelector.BanditsWay1,
    ShuffleLocationSelector.BanditsWay2,
    ShuffleLocationSelector.BanditsWayStarChest,
    ShuffleLocationSelector.BanditsWayDogJump,
    ShuffleLocationSelector.BanditsWayCroco,
    ShuffleLocationSelector.Croco1Reward,
    ShuffleLocationSelector.Croco1Reward2,
    # ShuffleLocationSelector.BanditsWayCoin1,
    # ShuffleLocationSelector.BanditsWayCoin2,
    # ShuffleLocationSelector.BanditsWayCoin3,
    ShuffleLocationSelector.MushroomKingdomStoreExchange,
    ShuffleLocationSelector.MushroomKingdomInn,
    ShuffleLocationSelector.PandoriteChest,
    ShuffleLocationSelector.PandoriteReward1,
    ShuffleLocationSelector.PandoriteReward2,
    ShuffleLocationSelector.KeroSewersPandoriteRoom,
    ShuffleLocationSelector.KeroSewersStarChest,
    ShuffleLocationSelector.KeroSewersBeforeBelomeLower,
    ShuffleLocationSelector.MidasRiverFirstTime,
    ShuffleLocationSelector.MidasRiverBottomLeftCave,
    ShuffleLocationSelector.MidasRiverBottomRightCave,
    ShuffleLocationSelector.CricketJamReward,
    ShuffleLocationSelector.CricketPieReward,
    ShuffleLocationSelector.MelodyBay1,
    ShuffleLocationSelector.MelodyBay2,
    ShuffleLocationSelector.MelodyBay3,
    ShuffleLocationSelector.RoseWayPlatform,
    ShuffleLocationSelector.RoseWayMushroom,
    ShuffleLocationSelector.RoseWayFlower,
    ShuffleLocationSelector.RoseWayFiveChests1,
    ShuffleLocationSelector.RoseWayFiveChests2,
    ShuffleLocationSelector.RoseWayFiveChests3,
    ShuffleLocationSelector.RoseWayFiveChests4,
    ShuffleLocationSelector.RoseWayFiveChests5,
    ShuffleLocationSelector.RoseTownFlag,
    ShuffleLocationSelector.RoseTownStore1,
    ShuffleLocationSelector.RoseTownStore2,
    ShuffleLocationSelector.RoseTownTreasureHouse1,
    ShuffleLocationSelector.RoseTownTreasureHouse2,
    ShuffleLocationSelector.RoseTownTreasureHouse3,
    ShuffleLocationSelector.RoseTownToad,
    ShuffleLocationSelector.Gaz,
    ShuffleLocationSelector.RoseTownTreasureHouseMazeReward,
    ShuffleLocationSelector.GardenerCloud1,
    ShuffleLocationSelector.GardenerCloud2,
    # ShuffleLocationSelector.RoseWayCoin1,
    # ShuffleLocationSelector.RoseWayCoin2,
    # ShuffleLocationSelector.RoseWayCoin3,
    # ShuffleLocationSelector.RoseWayCoin4,
    # ShuffleLocationSelector.RoseWayCoin5,
    ShuffleLocationSelector.ForestMaze1,
    ShuffleLocationSelector.ForestMaze2,
    ShuffleLocationSelector.ForestMazeUnderground1,
    ShuffleLocationSelector.ForestMazeUnderground2,
    ShuffleLocationSelector.ForestMazeUnderground3,
    ShuffleLocationSelector.ForestMazeRedEssence,
    ShuffleLocationSelector.ForestMazeSecret1,
    ShuffleLocationSelector.ForestMazeSecret2,
    ShuffleLocationSelector.ForestMazeSecret3,
    ShuffleLocationSelector.ForestMazeSecret4,
    ShuffleLocationSelector.ForestMazeSecret5,
    ShuffleLocationSelector.PipeVaultSlide1,
    ShuffleLocationSelector.PipeVaultSlide2,
    ShuffleLocationSelector.PipeVaultSlide3,
    ShuffleLocationSelector.PipeVaultSlideFrogCoin,
    ShuffleLocationSelector.GoombaThumping1,
    ShuffleLocationSelector.GoombaThumping2,
    ShuffleLocationSelector.PipeVaultNippers1,
    ShuffleLocationSelector.PipeVaultNippers2,
    # ShuffleLocationSelector.PipeVaultSlideCoin1,
    # ShuffleLocationSelector.PipeVaultSlideCoin2,
    # ShuffleLocationSelector.PipeVaultSlideCoin3,
    # ShuffleLocationSelector.PipeVaultSlideCoin4,
    # ShuffleLocationSelector.PipeVaultSlideCoin5,
    ShuffleLocationSelector.YosterIsleEntrance,
    ShuffleLocationSelector.YosterIsleFlag,
    ShuffleLocationSelector.YosterIsleRaceReward1,
    ShuffleLocationSelector.YosterIsleRaceReward2,
    ShuffleLocationSelector.YosterIsleRaceReward3,
    ShuffleLocationSelector.Croco2Item,
    ShuffleLocationSelector.MolevilleMinesShyGuy,
    ShuffleLocationSelector.MolevilleMinesStarChest,
    ShuffleLocationSelector.MolevilleMinesCoins,
    ShuffleLocationSelector.MolevilleMinesPunchinello1,
    ShuffleLocationSelector.MolevilleMinesPunchinello2,
    ShuffleLocationSelector.TreasureSeller1,
    ShuffleLocationSelector.TreasureSeller2,
    ShuffleLocationSelector.TreasureSeller3,
    ShuffleLocationSelector.FireworksShop,
    ShuffleLocationSelector.BucketGirl,
    ShuffleLocationSelector.BoosterPassBush,
    ShuffleLocationSelector.BoosterPass1,
    ShuffleLocationSelector.BoosterPass2,
    ShuffleLocationSelector.BoosterPassSecret1,
    ShuffleLocationSelector.BoosterPassSecret2,
    ShuffleLocationSelector.BoosterPassSecret3,
    ShuffleLocationSelector.BoosterPassFlower,
    ShuffleLocationSelector.BoosterTowerSpookum,
    ShuffleLocationSelector.BoosterTowerRailway,
    ShuffleLocationSelector.BoosterTowerMasher,
    ShuffleLocationSelector.BoosterTowerPortraits,
    ShuffleLocationSelector.BoosterTowerThwomp,
    ShuffleLocationSelector.BoosterTowerParachute,
    ShuffleLocationSelector.BoosterTowerParachuteCrevice,
    ShuffleLocationSelector.BoosterTowerFrogCoin1,
    ShuffleLocationSelector.BoosterTowerFrogCoin2,
    ShuffleLocationSelector.BoosterTowerFrogCoin3,
    ShuffleLocationSelector.BoosterTowerFrogCoin4,
    ShuffleLocationSelector.BoosterTowerRoomKey,
    ShuffleLocationSelector.BoosterTowerZoomShoes,
    ShuffleLocationSelector.BoosterTowerTop1,
    ShuffleLocationSelector.BoosterTowerTop2,
    ShuffleLocationSelector.BoosterTowerTop3,
    ShuffleLocationSelector.BoosterTowerKnifeGuy,
    # ShuffleLocationSelector.BoosterTowerCoin1,
    # ShuffleLocationSelector.BoosterTowerCoin2,
    # ShuffleLocationSelector.BoosterTowerCoin3,
    # ShuffleLocationSelector.BoosterTowerCoin4,
    # ShuffleLocationSelector.BoosterTowerCoin5,
    # ShuffleLocationSelector.BoosterTowerCoin6,
    # ShuffleLocationSelector.BoosterTowerCoin7,
    # ShuffleLocationSelector.BoosterTowerCoin8,
    # ShuffleLocationSelector.BoosterTowerCoin9,
    ShuffleLocationSelector.MarrymoreInn,
    ShuffleLocationSelector.MarrymorePrize1,
    ShuffleLocationSelector.MarrymorePrize2,
    ShuffleLocationSelector.MarrymorePrize3,
    ShuffleLocationSelector.MarrymorePrize4,
    ShuffleLocationSelector.MarrymorePrize5,
    ShuffleLocationSelector.MarrymorePrize6,
    ShuffleLocationSelector.MarrymoreSnifit1,
    ShuffleLocationSelector.MarrymoreSnifit2,
    ShuffleLocationSelector.MarrymoreSnifit3,
    ShuffleLocationSelector.MarrymoreAltar,
    ShuffleLocationSelector.FrogDisciple1,
    ShuffleLocationSelector.FrogDisciple2,
    ShuffleLocationSelector.FrogDisciple3,
    ShuffleLocationSelector.FrogDisciple4,
    ShuffleLocationSelector.FrogDisciple5,
    ShuffleLocationSelector.SeasideTownBossPrize,
    ShuffleLocationSelector.SeasideTownRescue,
    ShuffleLocationSelector.SeaStarChest,
    ShuffleLocationSelector.SeaSaveRoom1,
    ShuffleLocationSelector.SeaSaveRoom2,
    ShuffleLocationSelector.SeaSaveRoom3,
    ShuffleLocationSelector.SeaWhirlpoolChest,
    ShuffleLocationSelector.SunkenShipRatStairsFlower,
    ShuffleLocationSelector.SunkenShipRatStairs,
    ShuffleLocationSelector.SunkenShipTroopaPuzzle,
    ShuffleLocationSelector.SunkenShipTrampolinePuzzle,
    ShuffleLocationSelector.SunkenShip3DMaze,
    ShuffleLocationSelector.SunkenShipCannonballPuzzle,
    ShuffleLocationSelector.SunkenShipBarrelPuzzle,
    ShuffleLocationSelector.SunkenShipShop,
    ShuffleLocationSelector.SunkenShipCoins1,
    ShuffleLocationSelector.SunkenShipCoins2,
    ShuffleLocationSelector.SunkenShipCloneRoom,
    ShuffleLocationSelector.SunkenShipFrogCoinRoom,
    ShuffleLocationSelector.SunkenShipHidonMushroom,
    ShuffleLocationSelector.HidonChest,
    ShuffleLocationSelector.HidonReward1,
    ShuffleLocationSelector.HidonReward2,
    ShuffleLocationSelector.SunkenShipUnderwaterFrogCoin1,
    ShuffleLocationSelector.SunkenShipUnderwaterFrogCoin2,
    ShuffleLocationSelector.SunkenShipUnderwaterFrogCoin3,
    ShuffleLocationSelector.SunkenShipUnderwaterFrogCoin4,
    ShuffleLocationSelector.SunkenShipBlooberRoom,
    ShuffleLocationSelector.SunkenShipSafetyRing,
    ShuffleLocationSelector.SunkenShipBandanaReds,
    # ShuffleLocationSelector.SunkenShipCoinSnake,
    ShuffleLocationSelector.LandsEndRedEssence,
    ShuffleLocationSelector.LandsEndChowPit1,
    ShuffleLocationSelector.LandsEndChowPit2,
    ShuffleLocationSelector.LandsEndBeeRoom,
    ShuffleLocationSelector.LandsEndSecret1,
    ShuffleLocationSelector.LandsEndSecret2,
    ShuffleLocationSelector.LandsEndShyAway,
    ShuffleLocationSelector.KeroSewersBeforeBelomeUpper2,
    ShuffleLocationSelector.LandsEndStarChest1,
    ShuffleLocationSelector.LandsEndStarChest2,
    ShuffleLocationSelector.LandsEndStarChest3,
    ShuffleLocationSelector.TroopaClimb,
    ShuffleLocationSelector.BelomeTempleFortuneTeller,
    ShuffleLocationSelector.BelomeTempleFortune1,
    ShuffleLocationSelector.BelomeTempleFortune2,
    ShuffleLocationSelector.BelomeTempleFortune3,
    ShuffleLocationSelector.BelomeTempleFortune4,
    ShuffleLocationSelector.BelomeTempleAfterFortune1,
    ShuffleLocationSelector.BelomeTempleAfterFortune2,
    ShuffleLocationSelector.BelomeTempleAfterFortune3,
    ShuffleLocationSelector.BelomeTempleAfterFortune4,
    ShuffleLocationSelector.BelomeTempleTreasure1,
    ShuffleLocationSelector.BelomeTempleTreasure2,
    ShuffleLocationSelector.BelomeTempleTreasure3,
    ShuffleLocationSelector.BelomeTempleTreasureFlower1,
    ShuffleLocationSelector.BelomeTempleTreasureFlower2,
    ShuffleLocationSelector.BelomeTempleTreasureFlower3,
    ShuffleLocationSelector.BelomeTempleTreasureFlower4,
    ShuffleLocationSelector.BelomeTempleTreasureFrogCoin1,
    ShuffleLocationSelector.BelomeTempleTreasureFrogCoin2,
    ShuffleLocationSelector.BelomeTempleTreasureFrogCoin3,
    ShuffleLocationSelector.BelomeTempleTreasureFrogCoin4,
    ShuffleLocationSelector.BelomeTempleTreasureFrogCoin5,
    ShuffleLocationSelector.BelomeTempleTreasureFrogCoin6,
    ShuffleLocationSelector.BelomeTempleTreasureFrogCoin7,
    ShuffleLocationSelector.BelomeTempleTreasureFrogCoin8,
    ShuffleLocationSelector.MonstroTownEntrance,
    ShuffleLocationSelector.MonstroTownThwomp,
    ShuffleLocationSelector.JinxDojoReward,
    ShuffleLocationSelector.CulexReward,
    ShuffleLocationSelector.SuperJumps100,
    ShuffleLocationSelector.SuperJumps30,
    ShuffleLocationSelector.ThreeMustyFears,
    ShuffleLocationSelector.BeanValley1,
    ShuffleLocationSelector.BeanValley2,
    ShuffleLocationSelector.BeanValleyLeftPiranhaPipe,
    ShuffleLocationSelector.BeanValleyBottomLeftPiranhaPipe,
    ShuffleLocationSelector.BeanValleyBottomRightPiranhaPipeLower,
    ShuffleLocationSelector.BeanValleyBottomRightPiranhaPipeUpper,
    ShuffleLocationSelector.BeanValleyBoxBoyRoom1,
    ShuffleLocationSelector.BeanValleyBoxBoyRoom2,
    ShuffleLocationSelector.BeanValleyBoxBoyRoomHidden,
    ShuffleLocationSelector.BeanValleyPiranhaPlants,
    ShuffleLocationSelector.BeanValleyMegasmilaxRoom,
    ShuffleLocationSelector.BeanValleyFirstVineRoomFrogCoin,
    ShuffleLocationSelector.BeanValleyBeanstalk,
    ShuffleLocationSelector.BeanValleyBeanstalkFrogCoin,
    ShuffleLocationSelector.BeanValleyWestBeanstalkFrogCoin,
    ShuffleLocationSelector.BeanValleyCloud1,
    ShuffleLocationSelector.BeanValleyCloud2,
    ShuffleLocationSelector.BeanValleyFall1,
    ShuffleLocationSelector.BeanValleyFall2,
    # ShuffleLocationSelector.BeanValleyFirstVineRoomLowerCoin,
    # ShuffleLocationSelector.BeanValleyFirstVineRoomMiddleCoin,
    # ShuffleLocationSelector.BeanValleyFirstVineRoomUpperCoin,
    # ShuffleLocationSelector.BeanValleyBeanstalkCoin1,
    # ShuffleLocationSelector.BeanValleyBeanstalkCoin2,
    # ShuffleLocationSelector.BeanValleyBeanstalkCoin3,
    # ShuffleLocationSelector.BeanValleyEastBeanstalkCoin1,
    # ShuffleLocationSelector.BeanValleyEastBeanstalkCoin2,
    # ShuffleLocationSelector.BeanValleyEastBeanstalkCoin3,
    # ShuffleLocationSelector.BeanValleyEastBeanstalkCoin4,
    # ShuffleLocationSelector.BeanValleyEastBeanstalkCoin5,
    # ShuffleLocationSelector.BeanValleyWestBeanstalkCoin1,
    # ShuffleLocationSelector.BeanValleyWestBeanstalkCoin2,
    # ShuffleLocationSelector.BeanValleyWestBeanstalkCoin3,
    ShuffleLocationSelector.CasinoGrateGuyPrize,
    ShuffleLocationSelector.NimbusLandInn,
    ShuffleLocationSelector.NimbusLandInn2,
    ShuffleLocationSelector.NimbusLandShop,
    ShuffleLocationSelector.NimbusCastleBeforeBirdetta2,
    ShuffleLocationSelector.NimbusCastleOutOfBounds1,
    ShuffleLocationSelector.NimbusCastleOutOfBounds2,
    ShuffleLocationSelector.NimbusLandPrisoners,
    ShuffleLocationSelector.NimbusLandPrisoners2,
    ShuffleLocationSelector.NimbusCastleSingleGoldBird,
    ShuffleLocationSelector.NimbusCastleBirdetta,
    ShuffleLocationSelector.NimbusCastleAfterEgg1,
    ShuffleLocationSelector.NimbusCastleAfterEgg2,
    ShuffleLocationSelector.NimbusCastleCornerChestAfterValentina,
    ShuffleLocationSelector.NimbusCastleStarAfterValentina,
    ShuffleLocationSelector.NimbusLandCellar,
    ShuffleLocationSelector.NimbusLandSignalRing,
    ShuffleLocationSelector.NimbusLandRightSide,
    ShuffleLocationSelector.BarrelVolcanoSecret1,
    ShuffleLocationSelector.BarrelVolcanoSecret2,
    ShuffleLocationSelector.BarrelVolcanoBeforeStar1,
    ShuffleLocationSelector.BarrelVolcanoBeforeStar2,
    ShuffleLocationSelector.BarrelVolcanoStarRoom,
    ShuffleLocationSelector.BarrelVolcanoLavaPool,
    ShuffleLocationSelector.BarrelVolcanoSaveRoom1,
    ShuffleLocationSelector.BarrelVolcanoSaveRoom2,
    ShuffleLocationSelector.BarrelVolcanoReverse,
    ShuffleLocationSelector.BarrelVolcanoDonut1,
    ShuffleLocationSelector.BarrelVolcanoDonut2,
    ShuffleLocationSelector.BarrelVolcanoHinopio,
    ShuffleLocationSelector.BowsersKeepDarkRoom,
    ShuffleLocationSelector.BowsersKeepCrocoShop1,
    ShuffleLocationSelector.BowsersKeepCrocoShop2,
    ShuffleLocationSelector.BowsersKeepInvisibleBridge1,
    ShuffleLocationSelector.BowsersKeepInvisibleBridge2,
    ShuffleLocationSelector.BowsersKeepInvisibleBridge3,
    ShuffleLocationSelector.BowsersKeepInvisibleBridge4,
    ShuffleLocationSelector.BowsersKeepMovingPlatforms1,
    ShuffleLocationSelector.BowsersKeepMovingPlatforms2,
    ShuffleLocationSelector.BowsersKeepMovingPlatforms3,
    ShuffleLocationSelector.BowsersKeepMovingPlatforms4,
    ShuffleLocationSelector.BowsersKeepElevatorPlatforms,
    ShuffleLocationSelector.BowsersKeepCannonballRoom1,
    ShuffleLocationSelector.BowsersKeepCannonballRoom2,
    ShuffleLocationSelector.BowsersKeepCannonballRoom3,
    ShuffleLocationSelector.BowsersKeepCannonballRoom4,
    ShuffleLocationSelector.BowsersKeepCannonballRoom5,
    ShuffleLocationSelector.BowsersKeepRotatingPlatforms1,
    ShuffleLocationSelector.BowsersKeepRotatingPlatforms2,
    ShuffleLocationSelector.BowsersKeepRotatingPlatforms3,
    ShuffleLocationSelector.BowsersKeepRotatingPlatforms4,
    ShuffleLocationSelector.BowsersKeepRotatingPlatforms5,
    ShuffleLocationSelector.BowsersKeepRotatingPlatforms6,
    ShuffleLocationSelector.BowsersKeepDoorReward1,
    ShuffleLocationSelector.BowsersKeepDoorReward2,
    ShuffleLocationSelector.BowsersKeepDoorReward3,
    ShuffleLocationSelector.BowsersKeepDoorReward4,
    ShuffleLocationSelector.BowsersKeepDoorReward5,
    ShuffleLocationSelector.BowsersKeepDoorReward6,
    ShuffleLocationSelector.BowsersKeepMagikoopa,
    # ShuffleLocationSelector.BowsersKeepInvisibleBridgeCoin1,
    # ShuffleLocationSelector.BowsersKeepInvisibleBridgeCoin2,
    # ShuffleLocationSelector.BowsersKeepInvisibleBridgeCoin3,
    # ShuffleLocationSelector.BowsersKeepInvisibleBridgeCoin4,
    # ShuffleLocationSelector.BowsersKeepCannonballRoomCoin1,
    # ShuffleLocationSelector.BowsersKeepCannonballRoomCoin2,
    # ShuffleLocationSelector.BowsersKeepCannonballRoomCoin3,
    # ShuffleLocationSelector.BowsersKeepCannonballRoomCoin4,
    # ShuffleLocationSelector.BowsersKeepCannonballRoomCoin5,
    # ShuffleLocationSelector.BowsersKeepCannonballRoomCoin6,
    # ShuffleLocationSelector.BowsersKeepCannonballRoomCoin7,
    # ShuffleLocationSelector.BowsersKeepCannonballRoomCoin8,
    ShuffleLocationSelector.FactorySaveRoom,
    ShuffleLocationSelector.FactoryBoltPlatforms,
    ShuffleLocationSelector.FactoryFallingAxems,
    ShuffleLocationSelector.FactoryTreasurePit1,
    ShuffleLocationSelector.FactoryTreasurePit2,
    ShuffleLocationSelector.FactoryConveyorPlatforms1,
    ShuffleLocationSelector.FactoryConveyorPlatforms2,
    ShuffleLocationSelector.FactoryBehindSnakes1,
    ShuffleLocationSelector.FactoryBehindSnakes2,
    ShuffleLocationSelector.FactoryToadGift,
]


BOSS_STAR_PIECE_LOCATIONS = [
    ShuffleLocationSelector.MushroomWayStarPiece,
    ShuffleLocationSelector.BanditsWayStarPiece,
    ShuffleLocationSelector.InvasionStarPiece,
    ShuffleLocationSelector.PandoriteBoss,
    ShuffleLocationSelector.KeroSewersBoss,
    ShuffleLocationSelector.ForestMazeBoss,
    ShuffleLocationSelector.MolevilleMinesBoss1,
    ShuffleLocationSelector.MolevilleMinesBoss2,
    ShuffleLocationSelector.BoosterTowerStarPiece1,
    ShuffleLocationSelector.BoosterTowerStarPiece2,
    ShuffleLocationSelector.MarrymoreStarPiece,
    ShuffleLocationSelector.StarHillStarPiece1,
    ShuffleLocationSelector.SunkenShipMidboss,
    ShuffleLocationSelector.HidonBoss,
    ShuffleLocationSelector.SunkenShipBoss,
    ShuffleLocationSelector.SeasideTownBoss,
    ShuffleLocationSelector.LandsEndStarPiece1,
    ShuffleLocationSelector.BelomeTempleBoss,
    ShuffleLocationSelector.DojoBoss1,
    ShuffleLocationSelector.DojoBoss2,
    ShuffleLocationSelector.DojoBoss3,
    ShuffleLocationSelector.DojoBoss4,
    ShuffleLocationSelector.CulexBoss,
    ShuffleLocationSelector.BoxBoyBoss,
    ShuffleLocationSelector.BeanValleyBoss,
    ShuffleLocationSelector.NimbusLandStarPiece1,
    ShuffleLocationSelector.NimbusCastleStarPiece2,
    ShuffleLocationSelector.NimbusCastleStarPiece3,
    ShuffleLocationSelector.BarrelVolcanoBoss1,
    ShuffleLocationSelector.BarrelVolcanoBoss2,
    ShuffleLocationSelector.BowsersKeepBossChester,
    ShuffleLocationSelector.BowsersKeepBoss1,
    ShuffleLocationSelector.BowsersKeepBoss2,
    ShuffleLocationSelector.BowsersKeepBoss3,
    ShuffleLocationSelector.FactoryBoss1,
    ShuffleLocationSelector.FactoryBoss2,
    ShuffleLocationSelector.InnerFactoryBoss1,
    ShuffleLocationSelector.InnerFactoryBoss2,
    ShuffleLocationSelector.InnerFactoryBoss3,
    ShuffleLocationSelector.InnerFactoryBoss4,
    ShuffleLocationSelector.InnerFactoryBossFinal,
]

STARTER_CHARACTER_LIST = [o for o in PlayableCharacters]
EQUIPMENT_CHARACTERS_LIST = [o for o in EquipmentCharactersOptions]
EQUIPMENT_PROPERTIES_LIST = [o for o in EquipmentPropertiesOptions]
EXP_MULTIPLIER_OPTIONS = [o for o in EXPMultiplierOptions]
LEARNABLE_SPELL_LIST = [o for o in LearnableSpells]
PLAYABLE_CHARACTER_LIST = [
    o for o in STARTER_CHARACTER_LIST if o != PlayableCharacters.Random
]
ITEM_QUALITY_LIST = [o for o in ItemQualities]
FIREWORKS_OPTION_LIST = [o for o in FireworksOptions]
EXP_CHALLENGE_OPTIONS_LIST = [o for o in EXPChallengeOptions]
BANDITS_WAY_GATING_LIST = [o for o in BanditsWayGating]
FOREST_GATING_LIST = [o for o in ForestMazeGating]
VAULT_GATING_LIST = [o for o in PipeVaultGating]
MOLEVILLE_GATING = [o for o in Moleville1Gating]
TOWER_GATING = [o for o in BoosterTowerGating]
MARRYMORE_GATING = [o for o in MarrymoreGating]
SEA_GATING = [o for o in SeaGating]
TEMPLE_GATING = [o for o in BelomeTempleGating]
MONSTRO_GATING = [o for o in MonstroTownGating]
VOLCANO_GATING = [o for o in BarrelVolcanoGating]
KEEP_GATING = [o for o in BowsersKeepGating]
FACTORY_GATING = [o for o in FactoryGating]
SEASIDE_BOSS_GATING = [o for o in YaridovichGating]
WIN_CONDITION_LIST = [o for o in WinConditions]
SHOP_QUALITY_LIST = [o for o in ShopQualities]
BOSS_SCALE_LIST = [o for o in BossScaleOptions]
SHUFFLED_BOSS_LIST = [o for o in BossLocations]
BOSS_MUSIC_LIST = [o for o in AvailableMusic]
