"""Constants used to populate setting values."""

from randomizer.types.bosses.enums import BossLocations
from randomizer.types.world.flags.enums import (
    AvailableMusic,
    BanditsWayGating,
    BarrelVolcanoGating,
    BelomeTempleGating,
    BoosterTowerGating,
    BossScaleOptions,
    BowsersKeepGating,
    EXPChallengeOptions,
    EXPMultiplierOptions,
    EquipmentCharactersOptions,
    EquipmentPropertiesOptions,
    FactoryGating,
    FireworksOptions,
    ForestMazeGating,
    ItemQualities,
    LearnableSpells,
    MarrymoreGating,
    Moleville1Gating,
    MonstroTownGating,
    PipeVaultGating,
    PlayableCharacters,
    SeaGating,
    ShopQualities,
    ShuffleLocationSelector,
    WinConditions,
    YaridovichGating,
)


REGULAR_CHECKS = [  # excludes key item checks. can't turn those off
    ShuffleLocationSelector.MARIOS_PAD_STARTER_1,
    ShuffleLocationSelector.MARIOS_PAD_STARTER_2,
    ShuffleLocationSelector.MARIOS_PAD_STARTER_3,
    ShuffleLocationSelector.MARIOS_PAD_STARTER_4,
    ShuffleLocationSelector.MARIOS_PAD_BED,
    ShuffleLocationSelector.MUSHROOM_WAY_1,
    ShuffleLocationSelector.MUSHROOM_WAY_2,
    ShuffleLocationSelector.MUSHROOM_WAY_3,
    ShuffleLocationSelector.MUSHROOM_WAY_4,
    ShuffleLocationSelector.HAMMER_BROS_REWARD,
    ShuffleLocationSelector.MUSHROOM_KINGDOM_HALLWAY,
    ShuffleLocationSelector.PEACH_SURPRISE,
    ShuffleLocationSelector.MUSHROOM_KINGDOM_VAULT_1,
    ShuffleLocationSelector.MUSHROOM_KINGDOM_VAULT_2,
    ShuffleLocationSelector.MUSHROOM_KINGDOM_VAULT_3,
    ShuffleLocationSelector.MUSHROOM_KINGDOM_STORE,
    ShuffleLocationSelector.MUSHROOM_KINGDOM_STORE_BASEMENT_1,
    ShuffleLocationSelector.MUSHROOM_KINGDOM_STORE_BASEMENT_2,
    ShuffleLocationSelector.BANDITS_WAY_1,
    ShuffleLocationSelector.BANDITS_WAY_2,
    ShuffleLocationSelector.BANDITS_WAY_STAR_CHEST,
    ShuffleLocationSelector.BANDITS_WAY_DOG_JUMP,
    ShuffleLocationSelector.BANDITS_WAY_CROCO,
    ShuffleLocationSelector.CROCO_1_REWARD,
    ShuffleLocationSelector.CROCO_1_REWARD_2,
    # ShuffleLocationSelector.BanditsWayCoin1,
    # ShuffleLocationSelector.BanditsWayCoin2,
    # ShuffleLocationSelector.BanditsWayCoin3,
    ShuffleLocationSelector.MUSHROOM_KINGDOM_STORE_EXCHANGE,
    ShuffleLocationSelector.MUSHROOM_KINGDOM_INN,
    ShuffleLocationSelector.PANDORITE_CHEST,
    ShuffleLocationSelector.PANDORITE_REWARD_1,
    ShuffleLocationSelector.PANDORITE_REWARD_2,
    ShuffleLocationSelector.KERO_SEWERS_PANDORITE_ROOM,
    ShuffleLocationSelector.KERO_SEWERS_STAR_CHEST,
    ShuffleLocationSelector.KERO_SEWERS_BEFORE_BELOME_LOWER,
    ShuffleLocationSelector.MIDAS_RIVER_FIRST_TIME,
    ShuffleLocationSelector.MIDAS_RIVER_BOTTOM_LEFT_CAVE,
    ShuffleLocationSelector.MIDAS_RIVER_BOTTOM_RIGHT_CAVE,
    ShuffleLocationSelector.CRICKET_JAM_REWARD,
    ShuffleLocationSelector.CRICKET_PIE_REWARD,
    ShuffleLocationSelector.MELODY_BAY_1,
    ShuffleLocationSelector.MELODY_BAY_2,
    ShuffleLocationSelector.MELODY_BAY_3,
    ShuffleLocationSelector.ROSE_WAY_PLATFORM,
    ShuffleLocationSelector.ROSE_WAY_MUSHROOM,
    ShuffleLocationSelector.ROSE_WAY_FLOWER,
    ShuffleLocationSelector.ROSE_WAY_FIVE_CHESTS_1,
    ShuffleLocationSelector.ROSE_WAY_FIVE_CHESTS_2,
    ShuffleLocationSelector.ROSE_WAY_FIVE_CHESTS_3,
    ShuffleLocationSelector.ROSE_WAY_FIVE_CHESTS_4,
    ShuffleLocationSelector.ROSE_WAY_FIVE_CHESTS_5,
    ShuffleLocationSelector.ROSE_TOWN_FLAG,
    ShuffleLocationSelector.ROSE_TOWN_STORE_1,
    ShuffleLocationSelector.ROSE_TOWN_STORE_2,
    ShuffleLocationSelector.ROSE_TOWN_TREASURE_HOUSE_1,
    ShuffleLocationSelector.ROSE_TOWN_TREASURE_HOUSE_2,
    ShuffleLocationSelector.ROSE_TOWN_TREASURE_HOUSE_3,
    ShuffleLocationSelector.ROSE_TOWN_TOAD,
    ShuffleLocationSelector.GAZ,
    ShuffleLocationSelector.ROSE_TOWN_TREASURE_HOUSE_MAZE_REWARD,
    ShuffleLocationSelector.GARDENER_CLOUD_1,
    ShuffleLocationSelector.GARDENER_CLOUD_2,
    # ShuffleLocationSelector.RoseWayCoin1,
    # ShuffleLocationSelector.RoseWayCoin2,
    # ShuffleLocationSelector.RoseWayCoin3,
    # ShuffleLocationSelector.RoseWayCoin4,
    # ShuffleLocationSelector.RoseWayCoin5,
    ShuffleLocationSelector.FOREST_MAZE_1,
    ShuffleLocationSelector.FOREST_MAZE_2,
    ShuffleLocationSelector.FOREST_MAZE_UNDERGROUND_1,
    ShuffleLocationSelector.FOREST_MAZE_UNDERGROUND_2,
    ShuffleLocationSelector.FOREST_MAZE_UNDERGROUND_3,
    ShuffleLocationSelector.FOREST_MAZE_RED_ESSENCE,
    ShuffleLocationSelector.FOREST_MAZE_SECRET_1,
    ShuffleLocationSelector.FOREST_MAZE_SECRET_2,
    ShuffleLocationSelector.FOREST_MAZE_SECRET_3,
    ShuffleLocationSelector.FOREST_MAZE_SECRET_4,
    ShuffleLocationSelector.FOREST_MAZE_SECRET_5,
    ShuffleLocationSelector.PIPE_VAULT_SLIDE_1,
    ShuffleLocationSelector.PIPE_VAULT_SLIDE_2,
    ShuffleLocationSelector.PIPE_VAULT_SLIDE_3,
    ShuffleLocationSelector.PIPE_VAULT_SLIDE_FROG_COIN,
    ShuffleLocationSelector.GOOMBA_THUMPING_1,
    ShuffleLocationSelector.GOOMBA_THUMPING_2,
    ShuffleLocationSelector.PIPE_VAULT_NIPPERS_1,
    ShuffleLocationSelector.PIPE_VAULT_NIPPERS_2,
    # ShuffleLocationSelector.PipeVaultSlideCoin1,
    # ShuffleLocationSelector.PipeVaultSlideCoin2,
    # ShuffleLocationSelector.PipeVaultSlideCoin3,
    # ShuffleLocationSelector.PipeVaultSlideCoin4,
    # ShuffleLocationSelector.PipeVaultSlideCoin5,
    ShuffleLocationSelector.YOSTER_ISLE_ENTRANCE,
    ShuffleLocationSelector.YOSTER_ISLE_FLAG,
    ShuffleLocationSelector.YOSTER_ISLE_RACE_REWARD_1,
    ShuffleLocationSelector.YOSTER_ISLE_RACE_REWARD_2,
    ShuffleLocationSelector.YOSTER_ISLE_RACE_REWARD_3,
    ShuffleLocationSelector.CROCO_2_ITEM,
    ShuffleLocationSelector.MOLEVILLE_MINES_SHY_GUY,
    ShuffleLocationSelector.MOLEVILLE_MINES_STAR_CHEST,
    ShuffleLocationSelector.MOLEVILLE_MINES_COINS,
    ShuffleLocationSelector.MOLEVILLE_MINES_PUNCHINELLO_1,
    ShuffleLocationSelector.MOLEVILLE_MINES_PUNCHINELLO_2,
    ShuffleLocationSelector.TREASURE_SELLER_1,
    ShuffleLocationSelector.TREASURE_SELLER_2,
    ShuffleLocationSelector.TREASURE_SELLER_3,
    ShuffleLocationSelector.FIREWORKS_SHOP,
    ShuffleLocationSelector.BUCKET_GIRL,
    ShuffleLocationSelector.BOOSTER_PASS_BUSH,
    ShuffleLocationSelector.BOOSTER_PASS_1,
    ShuffleLocationSelector.BOOSTER_PASS_2,
    ShuffleLocationSelector.BOOSTER_PASS_SECRET_1,
    ShuffleLocationSelector.BOOSTER_PASS_SECRET_2,
    ShuffleLocationSelector.BOOSTER_PASS_SECRET_3,
    ShuffleLocationSelector.BOOSTER_PASS_FLOWER,
    ShuffleLocationSelector.BOOSTER_TOWER_SPOOKUM,
    ShuffleLocationSelector.BOOSTER_TOWER_RAILWAY,
    ShuffleLocationSelector.BOOSTER_TOWER_MASHER,
    ShuffleLocationSelector.BOOSTER_TOWER_PORTRAITS,
    ShuffleLocationSelector.BOOSTER_TOWER_THWOMP,
    ShuffleLocationSelector.BOOSTER_TOWER_PARACHUTE,
    ShuffleLocationSelector.BOOSTER_TOWER_PARACHUTE_CREVICE,
    ShuffleLocationSelector.BOOSTER_TOWER_FROG_COIN_1,
    ShuffleLocationSelector.BOOSTER_TOWER_FROG_COIN_2,
    ShuffleLocationSelector.BOOSTER_TOWER_FROG_COIN_3,
    ShuffleLocationSelector.BOOSTER_TOWER_FROG_COIN_4,
    ShuffleLocationSelector.BOOSTER_TOWER_ROOM_KEY,
    ShuffleLocationSelector.BOOSTER_TOWER_ZOOM_SHOES,
    ShuffleLocationSelector.BOOSTER_TOWER_TOP_1,
    ShuffleLocationSelector.BOOSTER_TOWER_TOP_2,
    ShuffleLocationSelector.BOOSTER_TOWER_TOP_3,
    ShuffleLocationSelector.BOOSTER_TOWER_KNIFE_GUY,
    # ShuffleLocationSelector.BoosterTowerCoin1,
    # ShuffleLocationSelector.BoosterTowerCoin2,
    # ShuffleLocationSelector.BoosterTowerCoin3,
    # ShuffleLocationSelector.BoosterTowerCoin4,
    # ShuffleLocationSelector.BoosterTowerCoin5,
    # ShuffleLocationSelector.BoosterTowerCoin6,
    # ShuffleLocationSelector.BoosterTowerCoin7,
    # ShuffleLocationSelector.BoosterTowerCoin8,
    # ShuffleLocationSelector.BoosterTowerCoin9,
    ShuffleLocationSelector.MARRYMORE_INN,
    ShuffleLocationSelector.MARRYMORE_PRIZE_1,
    ShuffleLocationSelector.MARRYMORE_PRIZE_2,
    ShuffleLocationSelector.MARRYMORE_PRIZE_3,
    ShuffleLocationSelector.MARRYMORE_PRIZE_4,
    ShuffleLocationSelector.MARRYMORE_PRIZE_5,
    ShuffleLocationSelector.MARRYMORE_PRIZE_6,
    ShuffleLocationSelector.MARRYMORE_SNIFIT_1,
    ShuffleLocationSelector.MARRYMORE_SNIFIT_2,
    ShuffleLocationSelector.MARRYMORE_SNIFIT_3,
    ShuffleLocationSelector.MARRYMORE_ALTAR,
    ShuffleLocationSelector.FROG_DISCIPLE_1,
    ShuffleLocationSelector.FROG_DISCIPLE_2,
    ShuffleLocationSelector.FROG_DISCIPLE_3,
    ShuffleLocationSelector.FROG_DISCIPLE_4,
    ShuffleLocationSelector.FROG_DISCIPLE_5,
    ShuffleLocationSelector.SEASIDE_TOWN_BOSS_PRIZE,
    ShuffleLocationSelector.SEASIDE_TOWN_RESCUE,
    ShuffleLocationSelector.SEA_STAR_CHEST,
    ShuffleLocationSelector.SEA_SAVE_ROOM_1,
    ShuffleLocationSelector.SEA_SAVE_ROOM_2,
    ShuffleLocationSelector.SEA_SAVE_ROOM_3,
    ShuffleLocationSelector.SEA_WHIRLPOOL_CHEST,
    ShuffleLocationSelector.SUNKEN_SHIP_RAT_STAIRS_FLOWER,
    ShuffleLocationSelector.SUNKEN_SHIP_RAT_STAIRS,
    ShuffleLocationSelector.SUNKEN_SHIP_TROOPA_PUZZLE,
    ShuffleLocationSelector.SUNKEN_SHIP_TRAMPOLINE_PUZZLE,
    ShuffleLocationSelector.SUNKEN_SHIP_3D_MAZE,
    ShuffleLocationSelector.SUNKEN_SHIP_CANNONBALL_PUZZLE,
    ShuffleLocationSelector.SUNKEN_SHIP_BARREL_PUZZLE,
    ShuffleLocationSelector.SUNKEN_SHIP_SHOP,
    ShuffleLocationSelector.SUNKEN_SHIP_COINS_1,
    ShuffleLocationSelector.SUNKEN_SHIP_COINS_2,
    ShuffleLocationSelector.SUNKEN_SHIP_CLONE_ROOM,
    ShuffleLocationSelector.SUNKEN_SHIP_FROG_COIN_ROOM,
    ShuffleLocationSelector.SUNKEN_SHIP_HIDON_MUSHROOM,
    ShuffleLocationSelector.HIDON_CHEST,
    ShuffleLocationSelector.HIDON_REWARD_1,
    ShuffleLocationSelector.HIDON_REWARD_2,
    ShuffleLocationSelector.SUNKEN_SHIP_UNDERWATER_FROG_COIN_1,
    ShuffleLocationSelector.SUNKEN_SHIP_UNDERWATER_FROG_COIN_2,
    ShuffleLocationSelector.SUNKEN_SHIP_UNDERWATER_FROG_COIN_3,
    ShuffleLocationSelector.SUNKEN_SHIP_UNDERWATER_FROG_COIN_4,
    ShuffleLocationSelector.SUNKEN_SHIP_BLOOBER_ROOM,
    ShuffleLocationSelector.SUNKEN_SHIP_SAFETY_RING,
    ShuffleLocationSelector.SUNKEN_SHIP_BANDANA_REDS,
    # ShuffleLocationSelector.SunkenShipCoinSnake,
    ShuffleLocationSelector.LANDS_END_RED_ESSENCE,
    ShuffleLocationSelector.LANDS_END_CHOW_PIT_1,
    ShuffleLocationSelector.LANDS_END_CHOW_PIT_2,
    ShuffleLocationSelector.LNDS_END_BEE_ROOM,
    ShuffleLocationSelector.LANDS_END_SECRET_1,
    ShuffleLocationSelector.LANDS_END_SECRET_2,
    ShuffleLocationSelector.LANDS_END_SHY_AWAY,
    ShuffleLocationSelector.KERO_SEWERS_BEFORE_BELOME_UPPER_2,
    ShuffleLocationSelector.LANDS_END_STAR_CHEST_1,
    ShuffleLocationSelector.LANDS_END_STAR_CHEST_2,
    ShuffleLocationSelector.LANDS_END_STAR_CHEST_3,
    ShuffleLocationSelector.TROOPA_CLIMB,
    ShuffleLocationSelector.BELOME_TEMPLE_FORTUNE_TELLER,
    ShuffleLocationSelector.BELOME_TEMPLE_FORTUNE_1,
    ShuffleLocationSelector.BELOME_TEMPLE_FORTUNE_2,
    ShuffleLocationSelector.BELOME_TEMPLE_FORTUNE_3,
    ShuffleLocationSelector.BELOME_TEMPLE_FORTUNE_4,
    ShuffleLocationSelector.BELOME_TEMPLE_AFTER_FORTUNE_1,
    ShuffleLocationSelector.BELOME_TEMPLE_AFTER_FORTUNE_2,
    ShuffleLocationSelector.BELOME_TEMPLE_AFTER_FORTUNE_3,
    ShuffleLocationSelector.BELOME_TEMPLE_AFTER_FORTUNE_4,
    ShuffleLocationSelector.BELOME_TEMPLE_TREASURE_1,
    ShuffleLocationSelector.BELOME_TEMPLE_TREASURE_2,
    ShuffleLocationSelector.BELOME_TEMPLE_TREASURE_3,
    ShuffleLocationSelector.BELOME_TEMPLE_TREASURE_FLOWER_1,
    ShuffleLocationSelector.BELOME_TEMPLE_TREASURE_FLOWER_2,
    ShuffleLocationSelector.BELOME_TEMPLE_TREASURE_FLOWER_3,
    ShuffleLocationSelector.BELOME_TEMPLE_TREASURE_FLOWER_4,
    ShuffleLocationSelector.BELOME_TEMPLE_TREASURE_FROG_COIN_1,
    ShuffleLocationSelector.BELOME_TEMPLE_TREASURE_FROG_COIN_2,
    ShuffleLocationSelector.BELOME_TEMPLE_TREASURE_FROG_COIN_3,
    ShuffleLocationSelector.BELOME_TEMPLE_TREASURE_FROG_COIN_4,
    ShuffleLocationSelector.BELOME_TEMPLE_TREASURE_FROG_COIN_5,
    ShuffleLocationSelector.BELOME_TEMPLE_TREASURE_FROG_COIN_6,
    ShuffleLocationSelector.BELOME_TEMPLE_TREASURE_FROG_COIN_7,
    ShuffleLocationSelector.BELOME_TEMPLE_TREASURE_FROG_COIN_8,
    ShuffleLocationSelector.MONSTRO_TOWN_ENTRANCE,
    ShuffleLocationSelector.MONSTRO_TOWN_THWOMP,
    ShuffleLocationSelector.JINX_DOJO_REWARD,
    ShuffleLocationSelector.CULEX_REWARD,
    ShuffleLocationSelector.SUPER_JUMPS_100,
    ShuffleLocationSelector.SUPER_JUMPS_30,
    ShuffleLocationSelector.THREE_MUSTY_FEARS,
    ShuffleLocationSelector.BEAN_VALLEY_1,
    ShuffleLocationSelector.BEAN_VALLEY_2,
    ShuffleLocationSelector.BEAN_VALLEY_LEFT_PIRANHA_PIPE,
    ShuffleLocationSelector.BEAN_VALLEY_BOTTOM_LEFT_PIRANHA_PIPE,
    ShuffleLocationSelector.BEAN_VALLEY_BOTTOM_RIGHT_PIRANHA_PIPE_LOWER,
    ShuffleLocationSelector.BEAN_VALLEY_BOTTOM_RIGHT_PIRANHA_PIPE_UPPER,
    ShuffleLocationSelector.BEAN_VALLEY_BOX_BOY_ROOM_1,
    ShuffleLocationSelector.BEAN_VALLEY_BOX_BOY_ROOM_2,
    ShuffleLocationSelector.BEAN_VALLEY_BOX_BOY_ROOM_HIDDEN,
    ShuffleLocationSelector.BEAN_VALLEY_PIRANHA_PLANTS,
    ShuffleLocationSelector.BEAN_VALLEY_MEGASMILAX_ROOM,
    ShuffleLocationSelector.BEAN_VALLEY_FIRST_VINE_ROOM_FROG_COIN,
    ShuffleLocationSelector.BEAN_VALLEY_BEANSTALK,
    ShuffleLocationSelector.BEAN_VALLEY_BEANSTALK_FROG_COIN,
    ShuffleLocationSelector.BEAN_VALLEY_WEST_BEANSTALK_FROG_COIN,
    ShuffleLocationSelector.BEAN_VALLEY_CLOUD_1,
    ShuffleLocationSelector.BEAN_VALLEY_CLOUD_2,
    ShuffleLocationSelector.BEAN_VALLEY_FALL_1,
    ShuffleLocationSelector.BEAN_VALLEY_FALL_2,
    # ShuffleLocationSelector.BeanValleyFirstVineRoomLowerCoin,
    # ShuffleLocationSelector.BeanValleyFirstVineRoomMiddleCoin,
    # ShuffleLocationSelector.BeanValleyFirstVineRoomUpperCoin,
    # ShuffleLocationSelector.BeanValleyBeanstalkCoin1,
    # ShuffleLocationSelector.BeanValleyBeanstalkCoin2,
    # ShuffleLocationSelector.BeanValleyBeanstalkCoin3,
    # ShuffleLocationSelector.BeanValleyEastBeanstalkCoin1,
    # ShuffleLocationSelector.BeanValleyEastBeanstalkCoin2,
    # ShuffleLocationSelector.BeanValleyEastBeanstalkCoin3,
    # ShuffleLocationSelector.BeanValleyEastBeanstalkCoin4,
    # ShuffleLocationSelector.BeanValleyEastBeanstalkCoin5,
    # ShuffleLocationSelector.BeanValleyWestBeanstalkCoin1,
    # ShuffleLocationSelector.BeanValleyWestBeanstalkCoin2,
    # ShuffleLocationSelector.BeanValleyWestBeanstalkCoin3,
    ShuffleLocationSelector.CASINO_GRATE_GUY_PRIZE,
    ShuffleLocationSelector.NIMBUS_LAND_INN,
    ShuffleLocationSelector.NIMBUS_LAND_INN_2,
    ShuffleLocationSelector.NIMBUS_LAND_SHOP,
    ShuffleLocationSelector.NIMBUS_LAND_BEFORE_BIRDETTA_1,
    ShuffleLocationSelector.NIMBUS_LAND_BEFORE_BIRDETTA_2,
    ShuffleLocationSelector.NIMBUS_CASTLE_OUT_OF_BOUNDS_1,
    ShuffleLocationSelector.NIMBUS_CASTLE_OUT_OF_BOUNDS_2,
    ShuffleLocationSelector.NIMBUS_LAND_PRISONERS,
    ShuffleLocationSelector.NIMBUS_LAND_PRISONERS_2,
    ShuffleLocationSelector.NIMBUS_CASTLE_SINGLE_GOLD_BIRD,
    ShuffleLocationSelector.NIMBUS_CASTLE_BIRDETTA,
    ShuffleLocationSelector.NIMBUS_CASTLE_AFTER_EGG_1,
    ShuffleLocationSelector.NIMBUS_CASTLE_AFTER_EGG_2,
    ShuffleLocationSelector.NIMBUS_CASTLE_CORNER_CHEST_AFTER_VALENTINA,
    ShuffleLocationSelector.NIMBUS_CASTLE_STAR_AFTER_VALENTINA,
    ShuffleLocationSelector.NIMBUS_LAND_CELLAR,
    ShuffleLocationSelector.NIMBUS_LAND_SIGNAL_RING,
    ShuffleLocationSelector.NIMBUS_LAND_RIGHT_SIDE,
    ShuffleLocationSelector.BARREL_VOLCANO_SECRET_1,
    ShuffleLocationSelector.BARREL_VOLCANO_SECRET_2,
    ShuffleLocationSelector.BARREL_VOLCANO_BEFORE_STAR_1,
    ShuffleLocationSelector.BARREL_VOLCANO_BEFORE_STAR_2,
    ShuffleLocationSelector.BARREL_VOLCANO_STAR_ROOM,
    ShuffleLocationSelector.BARREL_VOLCANO_LAVA_POOL,
    ShuffleLocationSelector.BARREL_VOLCANO_SAVE_ROOM_1,
    ShuffleLocationSelector.BARREL_VOLCANO_SAVE_ROOM_2,
    ShuffleLocationSelector.BARREL_VOLCANO_REVERSE,
    ShuffleLocationSelector.BARREL_VOLCANO_DONUT_1,
    ShuffleLocationSelector.BARREL_VOLCANO_DONUT_2,
    ShuffleLocationSelector.BARREL_VOLCANO_HINOPIO,
    ShuffleLocationSelector.BOWSERS_KEEP_DARK_ROOM,
    ShuffleLocationSelector.BOWSERS_KEEP_CROCO_SHOP_1,
    ShuffleLocationSelector.BOWSERS_KEEP_CROCO_SHOP_2,
    ShuffleLocationSelector.BOWSERS_KEEP_INVISIBLE_BRIDGE_1,
    ShuffleLocationSelector.BOWSERS_KEEP_INVISIBLE_BRIDGE_2,
    ShuffleLocationSelector.BOWSERS_KEEP_INVISIBLE_BRIDGE_3,
    ShuffleLocationSelector.BOWSERS_KEEP_INVISIBLE_BRIDGE_4,
    ShuffleLocationSelector.BOWSERS_KEEP_MOVING_PLATFORMS_1,
    ShuffleLocationSelector.BOWSERS_KEEP_MOVING_PLATFORMS_2,
    ShuffleLocationSelector.BOWSERS_KEEP_MOVING_PLATFORMS_3,
    ShuffleLocationSelector.BOWSERS_KEEP_MOVING_PLATFORMS_4,
    ShuffleLocationSelector.BOWSERS_KEEP_ELEVATOR_PLATFORMS,
    ShuffleLocationSelector.BOWSERS_KEEP_CANNONBALL_ROOM_1,
    ShuffleLocationSelector.BOWSERS_KEEP_CANNONBALL_ROOM_2,
    ShuffleLocationSelector.BOWSERS_KEEP_CANNONBALL_ROOM_3,
    ShuffleLocationSelector.BOWSERS_KEEP_CANNONBALL_ROOM_4,
    ShuffleLocationSelector.BOWSERS_KEEP_CANNONBALL_ROOM_5,
    ShuffleLocationSelector.BOWSERS_KEEP_ROTATING_PLATFORMS_1,
    ShuffleLocationSelector.BOWSERS_KEEP_ROTATING_PLATFORMS_2,
    ShuffleLocationSelector.BOWSERS_KEEP_ROTATING_PLATFORMS_3,
    ShuffleLocationSelector.BOWSERS_KEEP_ROTATING_PLATFORMS_4,
    ShuffleLocationSelector.BOWSERS_KEEP_ROTATING_PLATFORMS_5,
    ShuffleLocationSelector.BOWSERS_KEEP_ROTATING_PLATFORMS_6,
    ShuffleLocationSelector.BOWSERS_KEEP_DOOR_REWARD_1,
    ShuffleLocationSelector.BOWSERS_KEEP_DOOR_REWARD_2,
    ShuffleLocationSelector.BOWSERS_KEEP_DOOR_REWARD_3,
    ShuffleLocationSelector.BOWSERS_KEEP_DOOR_REWARD_4,
    ShuffleLocationSelector.BOWSERS_KEEP_DOOR_REWARD_5,
    ShuffleLocationSelector.BOWSERS_KEEP_DOOR_REWARD_6,
    ShuffleLocationSelector.BOWSERS_KEEP_MAGIKOOPA,
    # ShuffleLocationSelector.BowsersKeepInvisibleBridgeCoin1,
    # ShuffleLocationSelector.BowsersKeepInvisibleBridgeCoin2,
    # ShuffleLocationSelector.BowsersKeepInvisibleBridgeCoin3,
    # ShuffleLocationSelector.BowsersKeepInvisibleBridgeCoin4,
    # ShuffleLocationSelector.BOWSERS_KEEP_CANNONBALL_ROOM_COIN_1,
    # ShuffleLocationSelector.BOWSERS_KEEP_CANNONBALL_ROOM_COIN_2,
    # ShuffleLocationSelector.BOWSERS_KEEP_CANNONBALL_ROOM_COIN_3,
    # ShuffleLocationSelector.BOWSERS_KEEP_CANNONBALL_ROOM_COIN_4,
    # ShuffleLocationSelector.BOWSERS_KEEP_CANNONBALL_ROOM_COIN_5,
    # ShuffleLocationSelector.BOWSERS_KEEP_CANNONBALL_ROOM_COIN_6,
    # ShuffleLocationSelector.BOWSERS_KEEP_CANNONBALL_ROOM_COIN_7,
    # ShuffleLocationSelector.BOWSERS_KEEP_CANNONBALL_ROOM_COIN_8,
    ShuffleLocationSelector.FACTORY_SAVE_ROOM,
    ShuffleLocationSelector.FACTORY_BOLT_PLATFORMS,
    ShuffleLocationSelector.FACTORY_FALLING_AXEMS,
    ShuffleLocationSelector.FACTORY_TREASURE_PIT_1,
    ShuffleLocationSelector.FACTORY_TREASURE_PIT_2,
    ShuffleLocationSelector.FACTORY_CONVEYOR_PLATFORMS_1,
    ShuffleLocationSelector.FACTORY_CONVEYOR_PLATFORMS_2,
    ShuffleLocationSelector.FACTORY_BEHIND_SNAKES_1,
    ShuffleLocationSelector.FACTORY_BEHIND_SNAKES_2,
    ShuffleLocationSelector.FACTORY_TOAD_GIFT,
]


BOSS_STAR_PIECE_LOCATIONS = [
    ShuffleLocationSelector.MUSHROOM_WAY_STAR_PIECE,
    ShuffleLocationSelector.BANDITS_WAY_STAR_PIECE,
    ShuffleLocationSelector.INVASION_STAR_PIECE,
    ShuffleLocationSelector.PANDORITE_BOSS,
    ShuffleLocationSelector.KERO_SEWERS_BOSS,
    ShuffleLocationSelector.FOREST_MAZE_BOSS,
    ShuffleLocationSelector.MOLEVILLE_MINES_BOSS_1,
    ShuffleLocationSelector.MOLEVILLE_MINES_BOSS_2,
    ShuffleLocationSelector.BOOSTER_TOWER_STAR_PIECE_1,
    ShuffleLocationSelector.BOOSTER_TOWER_STAR_PIECE_2,
    ShuffleLocationSelector.MARRYMORE_STAR_PIECE,
    ShuffleLocationSelector.STAR_HILL_STAR_PIECE_1,
    ShuffleLocationSelector.SUNKEN_SHIP_MIDBOSS,
    ShuffleLocationSelector.HIDON_BOSS,
    ShuffleLocationSelector.SUNKEN_SHIP_BOSS,
    ShuffleLocationSelector.SEASIDE_TOWN_BOSS,
    ShuffleLocationSelector.LANDS_END_STAR_PIECE_1,
    ShuffleLocationSelector.BELOME_TEMPLE_BOSS,
    ShuffleLocationSelector.DOJO_BOSS_1,
    ShuffleLocationSelector.DOJO_BOSS_2,
    ShuffleLocationSelector.DOJO_BOSS_3,
    ShuffleLocationSelector.DOJO_BOSS_4,
    ShuffleLocationSelector.CULEX_BOSS,
    ShuffleLocationSelector.BOX_BOY_BOSS,
    ShuffleLocationSelector.BEAN_VALLEY_BOSS,
    ShuffleLocationSelector.NIMBUS_LAND_STAR_PIECE_1,
    ShuffleLocationSelector.NIMBUS_CASTLE_STAR_PIECE_2,
    ShuffleLocationSelector.NIMBUS_CASTLE_STAR_PIECE_3,
    ShuffleLocationSelector.BARREL_VOLCANO_BOSS_1,
    ShuffleLocationSelector.BARREL_VOLCANO_BOSS_2,
    ShuffleLocationSelector.BOWSERS_KEEP_BOSS_CHESTER,
    ShuffleLocationSelector.BOWSERS_KEEP_BOSS_1,
    ShuffleLocationSelector.BOWSERS_KEEP_BOSS_2,
    ShuffleLocationSelector.BOWSERS_KEEP_BOSS_3,
    ShuffleLocationSelector.FACTORY_BOSS_1,
    ShuffleLocationSelector.FACTORY_BOSS_2,
    ShuffleLocationSelector.INNER_FACTORY_BOSS_1,
    ShuffleLocationSelector.INNER_FACTORY_BOSS_2,
    ShuffleLocationSelector.INNER_FACTORY_BOSS_3,
    ShuffleLocationSelector.INNER_FACTORY_BOSS_4,
    ShuffleLocationSelector.INNER_FACTORY_BOSS_FINAL,
]

STARTER_CHARACTER_LIST = list(PlayableCharacters)
EQUIPMENT_CHARACTERS_LIST = list(EquipmentCharactersOptions)
EQUIPMENT_PROPERTIES_LIST = list(EquipmentPropertiesOptions)
EXP_MULTIPLIER_OPTIONS = list(EXPMultiplierOptions)
LEARNABLE_SPELL_LIST = list(LearnableSpells)
PLAYABLE_CHARACTER_LIST = [
    o for o in STARTER_CHARACTER_LIST if o != PlayableCharacters.RANDOM
]
ITEM_QUALITY_LIST = list(ItemQualities)
FIREWORKS_OPTION_LIST = list(FireworksOptions)
EXP_CHALLENGE_OPTIONS_LIST = list(EXPChallengeOptions)
BANDITS_WAY_GATING_LIST = list(BanditsWayGating)
FOREST_GATING_LIST = list(ForestMazeGating)
VAULT_GATING_LIST = list(PipeVaultGating)
MOLEVILLE_GATING = list(Moleville1Gating)
TOWER_GATING = list(BoosterTowerGating)
MARRYMORE_GATING = list(MarrymoreGating)
SEA_GATING = list(SeaGating)
TEMPLE_GATING = list(BelomeTempleGating)
MONSTRO_GATING = list(MonstroTownGating)
VOLCANO_GATING = list(BarrelVolcanoGating)
KEEP_GATING = list(BowsersKeepGating)
FACTORY_GATING = list(FactoryGating)
SEASIDE_BOSS_GATING = list(YaridovichGating)
WIN_CONDITION_LIST = list(WinConditions)
SHOP_QUALITY_LIST = list(ShopQualities)
BOSS_SCALE_LIST = list(BossScaleOptions)
SHUFFLED_BOSS_LIST = list(BossLocations)
BOSS_MUSIC_LIST = list(AvailableMusic)
