from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=25,
        y=123,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R378_BEAN_VALLEY_BEANSTALKS_AREA_01,
        show_message = False,
        dst_x = 2,
        dst_y = 59,
        dst_z = 2,
        dst_z_half = False,
    dst_f = SOUTH,
        x_bit_7 = False,
    ),
    RoomExit(
        x=25,
        y=124,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R378_BEAN_VALLEY_BEANSTALKS_AREA_01,
        show_message = False,
        dst_x = 2,
        dst_y = 59,
        dst_z = 2,
        dst_z_half = False,
    dst_f = SOUTH,
        x_bit_7 = False,
    ),
]
