
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
room = {
  "partition": {
    "ally_sprite_buffer_size": 1,
    "allow_extra_sprite_buffer": False,
    "extra_sprite_buffer_size": 0,
    "buffer_a": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_b": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_c": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "full_palette_buffer": True,
  },
  "music": Music._13_ROAD_IS_FULL_OF_DANGERS,
  "entrance_event": 3919,
  "event_tiles": [
    {
      "event": 2318,
      "x": 6,
      "y": 115,
      "z": 4,
      "f": Edge.SOUTHEAST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2319,
      "x": 6,
      "y": 117,
      "z": 4,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2320,
      "x": 8,
      "y": 118,
      "z": 4,
      "f": Edge.SOUTHEAST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2321,
      "x": 8,
      "y": 114,
      "z": 4,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2322,
      "x": 7,
      "y": 107,
      "z": 4,
      "f": Edge.SOUTHEAST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2323,
      "x": 7,
      "y": 109,
      "z": 4,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2324,
      "x": 9,
      "y": 110,
      "z": 4,
      "f": Edge.SOUTHEAST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2325,
      "x": 9,
      "y": 106,
      "z": 4,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2326,
      "x": 11,
      "y": 107,
      "z": 4,
      "f": Edge.SOUTHEAST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2327,
      "x": 11,
      "y": 109,
      "z": 4,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2328,
      "x": 13,
      "y": 110,
      "z": 4,
      "f": Edge.SOUTHEAST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2329,
      "x": 13,
      "y": 106,
      "z": 4,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2330,
      "x": 10,
      "y": 95,
      "z": 6,
      "f": Edge.SOUTHEAST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2331,
      "x": 10,
      "y": 97,
      "z": 6,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2332,
      "x": 12,
      "y": 98,
      "z": 6,
      "f": Edge.SOUTHEAST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2333,
      "x": 12,
      "y": 94,
      "z": 6,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    }
  ],
  "exit_fields": [
    {
      "x": 14,
      "y": 91,
      "z": 6,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.MAP_LOCATION,
      "byte_2_bit_2": True,
      "destination": Locations._025_BOOSTER_PASS,
      "show_message": False,
      "destination_props": {
        "byte_2_bit_0": True,
        "byte_2_bit_1": False,
      }
    },
    {
      "x": 1,
      "y": 122,
      "z": 0,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._100_BOOSTER_PASS_AREA_01,
      "show_message": True,
      "destination_props": {
        "x": 19,
        "y": 26,
        "z": 8,
        "z_half": False,
        "f": RadialDirection.SOUTHWEST,
        "x_bit_7": False
      }
    }
  ],
  "objects": [
    {
      "id": 0,
      "type": ObjectType.BATTLE,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 321,
      "battle_pack": 45,
      "after_battle": 8,
      "action_script": 400,
      "speed": 0,
      "action_offset": 0,
      "pack_offset": 0,
      "visible": True,
      "x": 7,
      "y": 115,
      "z": 2,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": True,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": True,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": True,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 1,
          "action_offset": 0,
          "pack_offset": 0,
          "visible": True,
          "x": 8,
          "y": 107,
          "z": 2,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 2,
          "action_offset": 0,
          "pack_offset": 0,
          "visible": True,
          "x": 12,
          "y": 107,
          "z": 2,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 3,
          "action_offset": 0,
          "pack_offset": 0,
          "visible": True,
          "x": 11,
          "y": 95,
          "z": 4,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        }
      ]
    },
    {
      "id": 4,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 192,
      "event_script": 2304,
      "action_script": 15,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": False,
      "x": 15,
      "y": 115,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": True,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 5,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.JUMP_ON,
      "model": 109,
      "event_script": 2312,
      "action_script": 15,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 10,
      "y": 111,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": False,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 6,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 198,
      "event_script": 241,
      "action_script": 15,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 15,
      "y": 109,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": []
    }
  ]
}
