
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
room = {
  "partition": {
    "ally_sprite_buffer_size": 1,
    "allow_extra_sprite_buffer": False,
    "extra_sprite_buffer_size": 0,
    "buffer_a": {
      "type": PartitionBufferTypes._3_SPRITES_PER_ROW,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_b": {
      "type": PartitionBufferTypes._4_SPRITES_PER_ROW,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_c": {
      "type": PartitionBufferTypes._4_SPRITES_PER_ROW,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "full_palette_buffer": True,
  },
  "music": Music._71_ENDING_PART_2,
  "entrance_event": 15,
  "event_tiles": [],
  "exit_fields": [],
  "objects": [
    {
      "id": 0,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 206,
      "event_script": 2304,
      "action_script": 970,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 6,
      "y": 19,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.NORTHEAST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 1,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 7,
          "y": 21,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.NORTHEAST
        },
        {
          "id": 2,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 8,
          "y": 23,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.NORTHEAST
        }
      ]
    },
    {
      "id": 3,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 262,
      "event_script": 2304,
      "action_script": 973,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 4,
      "y": 25,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.NORTHEAST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 4,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 1,
          "visible": True,
          "x": 6,
          "y": 27,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHEAST
        },
        {
          "id": 5,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 2,
          "visible": True,
          "x": 5,
          "y": 21,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHEAST
        }
      ]
    },
    {
      "id": 6,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 57,
      "event_script": 2304,
      "action_script": 972,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 1,
      "y": 26,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 7,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 2,
      "event_script": 2304,
      "action_script": 969,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 5,
      "y": 18,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.NORTHEAST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 8,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": False,
          "x": 5,
          "y": 18,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.NORTHEAST
        }
      ]
    },
    {
      "id": 9,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 184,
      "event_script": 2304,
      "action_script": 971,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 1,
      "y": 20,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    }
  ]
}
