
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
room = {
  "partition": {
    "ally_sprite_buffer_size": 1,
    "allow_extra_sprite_buffer": False,
    "extra_sprite_buffer_size": 0,
    "buffer_a": {
      "type": PartitionBufferTypes._4_SPRITES_PER_ROW,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_b": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_c": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "full_palette_buffer": True,
  },
  "music": Music._31_BOOSTERS_TOWER,
  "entrance_event": 1339,
  "event_tiles": [],
  "exit_fields": [
    {
      "x": 19,
      "y": 34,
      "z": 0,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._036_BOOSTER_TOWER_6F_AREA_04_3LEVEL_WTHWOMP_ON_TEETERTOTTER,
      "show_message": False,
      "destination_props": {
        "x": 4,
        "y": 119,
        "z": 0,
        "z_half": False,
        "f": RadialDirection.SOUTHWEST,
        "x_bit_7": False
      }
    },
    {
      "x": 13,
      "y": 13,
      "z": 0,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._200_BOOSTER_TOWER_6F_AREA_03_ELDERS_ROOM_WCHOMP,
      "show_message": False,
      "destination_props": {
        "x": 23,
        "y": 123,
        "z": 0,
        "z_half": False,
        "f": RadialDirection.NORTHEAST,
        "x_bit_7": False
      }
    },
    {
      "x": 10,
      "y": 12,
      "z": 0,
      "f": Edge.SOUTHEAST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._201_BOOSTER_TOWER_6F_AREA_01_SMALL_ROOM_WSAVE_POINT,
      "show_message": False,
      "destination_props": {
        "x": 30,
        "y": 123,
        "z": 0,
        "z_half": False,
        "f": RadialDirection.NORTHWEST,
        "x_bit_7": False
      }
    }
  ],
  "objects": [
    {
      "id": 0,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 282,
      "event_script": 1323,
      "action_script": 0,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 5,
      "action_offset": 0,
      "visible": True,
      "x": 15,
      "y": 19,
      "z": 0,
      "z_half": True,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": True,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": True,
      "cant_walk_under": True,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 1,
          "npc_id_offset": 0,
          "event_offset": 5,
          "action_offset": 0,
          "visible": True,
          "x": 16,
          "y": 21,
          "z": 0,
          "z_half": True,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 2,
          "npc_id_offset": 0,
          "event_offset": 5,
          "action_offset": 0,
          "visible": True,
          "x": 17,
          "y": 23,
          "z": 0,
          "z_half": True,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 3,
          "npc_id_offset": 0,
          "event_offset": 5,
          "action_offset": 0,
          "visible": True,
          "x": 18,
          "y": 25,
          "z": 0,
          "z_half": True,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 4,
          "npc_id_offset": 0,
          "event_offset": 5,
          "action_offset": 0,
          "visible": True,
          "x": 19,
          "y": 27,
          "z": 0,
          "z_half": True,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 5,
          "npc_id_offset": 0,
          "event_offset": 5,
          "action_offset": 0,
          "visible": True,
          "x": 20,
          "y": 29,
          "z": 0,
          "z_half": True,
          "direction": RadialDirection.SOUTHWEST
        }
      ]
    },
    {
      "id": 6,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 50,
      "event_script": 1394,
      "action_script": 0,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": False,
      "x": 0,
      "y": 0,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHEAST,
      "face_on_trigger": True,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 7,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 196,
      "event_script": 1394,
      "action_script": 830,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": False,
      "x": 18,
      "y": 25,
      "z": 1,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": True,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 8,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.PRESS_A_FROM_FRONT,
      "model": 255,
      "event_script": 1332,
      "action_script": 13,
      "speed": 3,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 15,
      "y": 19,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": True,
      "cant_walk_up_stairs": True,
      "cant_walk_under": True,
      "cant_pass_walls": False,
      "cant_jump_through": True,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 9,
          "npc_id_offset": 0,
          "event_offset": 1,
          "action_offset": 0,
          "visible": True,
          "x": 16,
          "y": 21,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 10,
          "npc_id_offset": 0,
          "event_offset": 2,
          "action_offset": 0,
          "visible": True,
          "x": 17,
          "y": 23,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 11,
          "npc_id_offset": 0,
          "event_offset": 3,
          "action_offset": 0,
          "visible": True,
          "x": 18,
          "y": 25,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 12,
          "npc_id_offset": 0,
          "event_offset": 4,
          "action_offset": 0,
          "visible": True,
          "x": 19,
          "y": 27,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 13,
          "npc_id_offset": 0,
          "event_offset": 5,
          "action_offset": 0,
          "visible": True,
          "x": 20,
          "y": 29,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        }
      ]
    },
    {
      "id": 14,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.PRESS_A_FROM_ANY_SIDE,
      "model": 255,
      "event_script": 1340,
      "action_script": 13,
      "speed": 3,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 13,
      "y": 15,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": True,
      "cant_walk_up_stairs": True,
      "cant_walk_under": True,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 15,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.PRESS_A_FROM_ANY_SIDE,
      "model": 220,
      "event_script": 1343,
      "action_script": 0,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 14,
      "y": 16,
      "z": 0,
      "z_half": True,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": True,
      "cant_walk_under": True,
      "cant_pass_walls": False,
      "cant_jump_through": True,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    }
  ]
}
