
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
room = {
  "partition": {
    "ally_sprite_buffer_size": 1,
    "allow_extra_sprite_buffer": True,
    "extra_sprite_buffer_size": 0,
    "buffer_a": {
      "type": PartitionBufferTypes._4_SPRITES_PER_ROW,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_b": {
      "type": PartitionBufferTypes._3_SPRITES_PER_ROW,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_c": {
      "type": PartitionBufferTypes._4_SPRITES_PER_ROW,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "full_palette_buffer": True,
  },
  "music": Music._00_CURRENT,
  "entrance_event": 3701,
  "event_tiles": [
    {
      "event": 3663,
      "x": 1,
      "y": 24,
      "z": 0,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    }
  ],
  "exit_fields": [
    {
      "x": 7,
      "y": 11,
      "z": 0,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._410_NIMBUS_CASTLE_AREA_07_STRAIGHT_FROM_AREA_06_WLONG_STAIRCASE,
      "show_message": False,
      "destination_props": {
        "x": 14,
        "y": 93,
        "z": 4,
        "z_half": False,
        "f": RadialDirection.NORTHEAST,
        "x_bit_7": False
      }
    }
  ],
  "objects": [
    {
      "id": 0,
      "type": ObjectType.BATTLE,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 260,
      "battle_pack": 98,
      "after_battle": 0,
      "action_script": 881,
      "speed": 0,
      "action_offset": 0,
      "pack_offset": 0,
      "visible": True,
      "x": 5,
      "y": 14,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": True,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": True,
      "cant_walk_through": True,
      "byte3_bit7": True,
      "slidable_along_walls": True,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 1,
          "action_offset": 1,
          "pack_offset": 1,
          "visible": True,
          "x": 6,
          "y": 17,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.NORTHWEST
        }
      ]
    },
    {
      "id": 2,
      "type": ObjectType.BATTLE,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 183,
      "battle_pack": 92,
      "after_battle": 0,
      "action_script": 803,
      "speed": 0,
      "action_offset": 0,
      "pack_offset": 0,
      "visible": True,
      "x": 3,
      "y": 23,
      "z": 1,
      "z_half": False,
      "direction": RadialDirection.NORTHWEST,
      "face_on_trigger": True,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": True,
      "cant_walk_through": True,
      "byte3_bit7": True,
      "slidable_along_walls": True,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 3,
      "type": ObjectType.BATTLE,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 183,
      "battle_pack": 92,
      "after_battle": 0,
      "action_script": 883,
      "speed": 0,
      "action_offset": 0,
      "pack_offset": 0,
      "visible": True,
      "x": 2,
      "y": 20,
      "z": 1,
      "z_half": False,
      "direction": RadialDirection.SOUTHEAST,
      "face_on_trigger": True,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": True,
      "cant_walk_through": True,
      "byte3_bit7": True,
      "slidable_along_walls": True,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 4,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.PRESS_A_FROM_ANY_SIDE,
      "model": 79,
      "event_script": 3759,
      "action_script": 810,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": False,
      "x": 6,
      "y": 17,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.NORTHWEST,
      "face_on_trigger": True,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": True,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 5,
      "type": ObjectType.BATTLE,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 279,
      "battle_pack": 92,
      "after_battle": 0,
      "action_script": 15,
      "speed": 0,
      "action_offset": 0,
      "pack_offset": 0,
      "visible": False,
      "x": 21,
      "y": 110,
      "z": 1,
      "z_half": False,
      "direction": RadialDirection.NORTHWEST,
      "face_on_trigger": True,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": True,
      "cant_walk_through": True,
      "byte3_bit7": True,
      "slidable_along_walls": False,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 6,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 63,
      "event_script": 470,
      "action_script": 15,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": False,
      "x": 2,
      "y": 20,
      "z": 1,
      "z_half": False,
      "direction": RadialDirection.SOUTHEAST,
      "face_on_trigger": True,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": False,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 7,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 63,
      "event_script": 470,
      "action_script": 15,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": False,
      "x": 3,
      "y": 23,
      "z": 1,
      "z_half": False,
      "direction": RadialDirection.NORTHWEST,
      "face_on_trigger": True,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": False,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": []
    }
  ]
}
