
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
room = {
  "partition": {
    "ally_sprite_buffer_size": 1,
    "allow_extra_sprite_buffer": True,
    "extra_sprite_buffer_size": 0,
    "buffer_a": {
      "type": PartitionBufferTypes._4_SPRITES_PER_ROW,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_b": {
      "type": PartitionBufferTypes._3_SPRITES_PER_ROW,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_c": {
      "type": PartitionBufferTypes._3_SPRITES_PER_ROW,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "full_palette_buffer": True,
  },
  "music": Music._00_CURRENT,
  "entrance_event": 2145,
  "event_tiles": [],
  "exit_fields": [
    {
      "x": 3,
      "y": 67,
      "z": 5,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._477_BOWSERS_KEEP_2ND_TIME_AREA_02,
      "show_message": False,
      "destination_props": {
        "x": 16,
        "y": 69,
        "z": 0,
        "z_half": False,
        "f": RadialDirection.SOUTHWEST,
        "x_bit_7": False
      }
    },
    {
      "x": 17,
      "y": 40,
      "z": 5,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._479_BOWSERS_KEEP_2ND_TIME_AREA_04_THRONE_ROOM,
      "show_message": False,
      "destination_props": {
        "x": 2,
        "y": 66,
        "z": 0,
        "z_half": False,
        "f": RadialDirection.NORTHEAST,
        "x_bit_7": False
      }
    }
  ],
  "objects": [
    {
      "id": 0,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 255,
      "event_script": 1395,
      "action_script": 15,
      "speed": 3,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 11,
      "y": 51,
      "z": 5,
      "z_half": False,
      "direction": RadialDirection.NORTHEAST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": False,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 1,
      "type": ObjectType.BATTLE,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 326,
      "battle_pack": 114,
      "after_battle": 0,
      "action_script": 993,
      "speed": 0,
      "action_offset": 0,
      "pack_offset": 0,
      "visible": True,
      "x": 5,
      "y": 63,
      "z": 5,
      "z_half": False,
      "direction": RadialDirection.NORTHEAST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 2,
          "action_offset": 1,
          "pack_offset": 0,
          "visible": True,
          "x": 8,
          "y": 57,
          "z": 5,
          "z_half": False,
          "direction": RadialDirection.NORTHEAST
        },
        {
          "id": 3,
          "action_offset": 2,
          "pack_offset": 0,
          "visible": True,
          "x": 11,
          "y": 53,
          "z": 5,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 4,
          "action_offset": 3,
          "pack_offset": 0,
          "visible": True,
          "x": 8,
          "y": 59,
          "z": 5,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        }
      ]
    },
    {
      "id": 5,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.JUMP_ON,
      "model": 502,
      "event_script": 2146,
      "action_script": 15,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 13,
      "y": 48,
      "z": 4,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 6,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 14,
          "y": 46,
          "z": 4,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 7,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 15,
          "y": 44,
          "z": 4,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        }
      ]
    },
    {
      "id": 8,
      "type": ObjectType.BATTLE,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 322,
      "battle_pack": 112,
      "after_battle": 2,
      "action_script": 539,
      "speed": 0,
      "action_offset": 0,
      "pack_offset": 0,
      "visible": False,
      "x": 13,
      "y": 54,
      "z": 5,
      "z_half": True,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 9,
          "action_offset": 0,
          "pack_offset": 0,
          "visible": False,
          "x": 10,
          "y": 46,
          "z": 5,
          "z_half": True,
          "direction": RadialDirection.SOUTHWEST
        }
      ]
    }
  ]
}
