
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
room = {
  "partition": {
    "ally_sprite_buffer_size": 1,
    "allow_extra_sprite_buffer": False,
    "extra_sprite_buffer_size": 0,
    "buffer_a": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_b": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_c": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "full_palette_buffer": True,
  },
  "music": Music._14_MARIOS_PAD,
  "entrance_event": 1408,
  "event_tiles": [
    {
      "event": 1406,
      "x": 12,
      "y": 34,
      "z": 1,
      "f": Edge.SOUTHEAST,
      "length": 1,
      "height": 6,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 1407,
      "x": 11,
      "y": 34,
      "z": 1,
      "f": Edge.SOUTHWEST,
      "length": 3,
      "height": 6,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 1407,
      "x": 11,
      "y": 33,
      "z": 1,
      "f": Edge.SOUTHEAST,
      "length": 1,
      "height": 6,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 1407,
      "x": 12,
      "y": 35,
      "z": 1,
      "f": Edge.SOUTHEAST,
      "length": 1,
      "height": 6,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    }
  ],
  "exit_fields": [
    {
      "x": 13,
      "y": 32,
      "z": 1,
      "f": Edge.SOUTHEAST,
      "length": 1,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._189_MARIOS_PIPEHOUSE,
      "show_message": False,
      "destination_props": {
        "x": 2,
        "y": 16,
        "z": 0,
        "z_half": False,
        "f": RadialDirection.NORTHEAST,
        "x_bit_7": False
      }
    },
    {
      "x": 10,
      "y": 51,
      "z": 0,
      "f": Edge.SOUTHEAST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.MAP_LOCATION,
      "byte_2_bit_2": True,
      "destination": Locations._008_MARIOS_PAD,
      "show_message": False,
      "destination_props": {
        "byte_2_bit_0": True,
        "byte_2_bit_1": False,
      }
    }
  ],
  "objects": [
    {
      "id": 0,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.JUMP_ON,
      "model": 102,
      "event_script": 80,
      "action_script": 120,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 5,
      "y": 34,
      "z": 0,
      "z_half": True,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": False,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": []
    }
  ]
}
