
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
room = {
  "partition": {
    "ally_sprite_buffer_size": 1,
    "allow_extra_sprite_buffer": False,
    "extra_sprite_buffer_size": 0,
    "buffer_a": {
      "type": PartitionBufferTypes.TREASURE_CHEST,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_b": {
      "type": PartitionBufferTypes._4_SPRITES_PER_ROW,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_c": {
      "type": PartitionBufferTypes.COINS,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "full_palette_buffer": True,
  },
  "music": Music._31_BOOSTERS_TOWER,
  "entrance_event": 2340,
  "event_tiles": [
    {
      "event": 2341,
      "x": 18,
      "y": 121,
      "z": 0,
      "f": Edge.SOUTHEAST,
      "length": 1,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": True,
      "byte_8_bit_4": False,
    }
  ],
  "exit_fields": [
    {
      "x": 16,
      "y": 124,
      "z": 0,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._043_BOOSTER_TOWER_1F_AREA_01_MAIN_ROOM,
      "show_message": False,
      "destination_props": {
        "x": 26,
        "y": 109,
        "z": 0,
        "z_half": False,
        "f": RadialDirection.SOUTHWEST,
        "x_bit_7": False
      }
    },
    {
      "x": 16,
      "y": 116,
      "z": 11,
      "f": Edge.SOUTHEAST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._193_BOOSTER_TOWER_2F_AREA_03_STEPS_WCIRCLING_BOBOMBS,
      "show_message": False,
      "destination_props": {
        "x": 5,
        "y": 71,
        "z": 9,
        "z_half": False,
        "f": RadialDirection.NORTHWEST,
        "x_bit_7": False
      }
    }
  ],
  "objects": [
    {
      "id": 0,
      "type": ObjectType.CHEST,
      "initiator": Initiator.HIT_FROM_BELOW,
      "model": 94,
      "event_script": 34,
      "action_script": 14,
      "speed": 0,
      "star_offset": 5,
      "item_offset": 8,
      "visible": True,
      "x": 18,
      "y": 125,
      "z": 18,
      "z_half": True,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": False,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 1,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 281,
      "event_script": 2389,
      "action_script": 15,
      "speed": 5,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 19,
      "y": 120,
      "z": 1,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": False,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 2,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 0,
      "event_script": 2304,
      "action_script": 15,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": False,
      "x": 0,
      "y": 0,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": False,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 3,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 153,
      "event_script": 2304,
      "action_script": 15,
      "speed": 4,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": False,
      "x": 18,
      "y": 126,
      "z": 19,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 4,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.JUMP_ON,
      "model": 101,
      "event_script": 2304,
      "action_script": 15,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 18,
      "y": 121,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHEAST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": False,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    }
  ]
}
