
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
room = {
  "partition": {
    "ally_sprite_buffer_size": 1,
    "allow_extra_sprite_buffer": True,
    "extra_sprite_buffer_size": 1,
    "buffer_a": {
      "type": PartitionBufferTypes.TREASURE_CHEST,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_b": {
      "type": PartitionBufferTypes._3_SPRITES_PER_ROW,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_c": {
      "type": PartitionBufferTypes.COINS,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "full_palette_buffer": True,
  },
  "music": Music._66_BOWSERS_CASTLE_2ND_TIME,
  "entrance_event": 1827,
  "event_tiles": [
    {
      "event": 1947,
      "x": 21,
      "y": 86,
      "z": 2,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 1879,
      "x": 7,
      "y": 118,
      "z": 2,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    }
  ],
  "exit_fields": [],
  "objects": [
    {
      "id": 0,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 255,
      "event_script": 1551,
      "action_script": 161,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 4,
      "y": 113,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHEAST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": False,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 1,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.JUMP_ON,
      "model": 427,
      "event_script": 1840,
      "action_script": 161,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 9,
      "y": 116,
      "z": 2,
      "z_half": False,
      "direction": RadialDirection.NORTHEAST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": False,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": False,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 2,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 7,
          "y": 109,
          "z": 2,
          "z_half": False,
          "direction": RadialDirection.NORTHEAST
        },
        {
          "id": 3,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 15,
          "y": 109,
          "z": 2,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 4,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 17,
          "y": 106,
          "z": 2,
          "z_half": False,
          "direction": RadialDirection.NORTHEAST
        },
        {
          "id": 5,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 16,
          "y": 100,
          "z": 2,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 6,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 15,
          "y": 99,
          "z": 2,
          "z_half": False,
          "direction": RadialDirection.NORTHEAST
        },
        {
          "id": 7,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 20,
          "y": 97,
          "z": 2,
          "z_half": False,
          "direction": RadialDirection.NORTHWEST
        },
        {
          "id": 8,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 22,
          "y": 95,
          "z": 2,
          "z_half": False,
          "direction": RadialDirection.NORTHWEST
        },
        {
          "id": 9,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 13,
          "y": 98,
          "z": 2,
          "z_half": False,
          "direction": RadialDirection.SOUTHEAST
        }
      ]
    },
    {
      "id": 10,
      "type": ObjectType.CHEST,
      "initiator": Initiator.HIT_FROM_BELOW,
      "model": 503,
      "event_script": 1936,
      "action_script": 14,
      "speed": 0,
      "star_offset": 0,
      "item_offset": 2,
      "visible": True,
      "x": 17,
      "y": 90,
      "z": 6,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": False,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 11,
      "type": ObjectType.CHEST,
      "initiator": Initiator.HIT_FROM_BELOW,
      "model": 503,
      "event_script": 1937,
      "action_script": 14,
      "speed": 0,
      "star_offset": 11,
      "item_offset": 6,
      "visible": True,
      "x": 9,
      "y": 106,
      "z": 6,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": False,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 12,
      "type": ObjectType.CHEST,
      "initiator": Initiator.HIT_FROM_BELOW,
      "model": 503,
      "event_script": 1938,
      "action_script": 14,
      "speed": 0,
      "star_offset": 2,
      "item_offset": 6,
      "visible": True,
      "x": 11,
      "y": 117,
      "z": 6,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": False,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 13,
      "type": ObjectType.CHEST,
      "initiator": Initiator.HIT_FROM_BELOW,
      "model": 503,
      "event_script": 1939,
      "action_script": 14,
      "speed": 0,
      "star_offset": 1,
      "item_offset": 7,
      "visible": True,
      "x": 22,
      "y": 94,
      "z": 6,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": False,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    }
  ]
}
