# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectdisassembler --rom ROM
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
room = {
  "partition": {
    "ally_sprite_buffer_size": 1,
    "allow_extra_sprite_buffer": False,
    "extra_sprite_buffer_size": 0,
    "buffer_a": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_b": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_c": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "full_palette_buffer": True,
  },
  "music": Music._00_CURRENT,
  "entrance_event": 2144,
  "event_tiles": [],
  "exit_fields": [
    {
      "x": 3,
      "y": 96,
      "z": 0,
      "f": Edge.SOUTHWEST,
      "length": 3,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._476_BOWSERS_KEEP_2ND_TIME_AREA_01,
      "show_message": False,
      "destination_props": {
        "x": 10,
        "y": 23,
        "z": 0,
        "z_half": False,
        "f": RadialDirection.SOUTHWEST,
        "x_bit_7": False
      }
    },
    {
      "x": 17,
      "y": 67,
      "z": 0,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._478_BOWSERS_KEEP_2ND_TIME_AREA_03_LAVA_ROOM_WBRIDGE,
      "show_message": False,
      "destination_props": {
        "x": 4,
        "y": 66,
        "z": 5,
        "z_half": False,
        "f": RadialDirection.NORTHEAST,
        "x_bit_7": False
      }
    }
  ],
  "objects": [
    {
      "id": 0,
      "type": ObjectType.BATTLE,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 320,
      "battle_pack": 110,
      "after_battle": 0,
      "action_script": 547,
      "speed": 0,
      "action_offset": 0,
      "pack_offset": 0,
      "visible": True,
      "x": 7,
      "y": 85,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHEAST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 1,
          "action_offset": 1,
          "pack_offset": 0,
          "visible": True,
          "x": 10,
          "y": 87,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.NORTHWEST
        },
        {
          "id": 2,
          "action_offset": 0,
          "pack_offset": 0,
          "visible": True,
          "x": 9,
          "y": 81,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHEAST
        },
        {
          "id": 3,
          "action_offset": 1,
          "pack_offset": 0,
          "visible": True,
          "x": 12,
          "y": 83,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.NORTHWEST
        },
        {
          "id": 4,
          "action_offset": 0,
          "pack_offset": 0,
          "visible": True,
          "x": 11,
          "y": 77,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHEAST
        },
        {
          "id": 5,
          "action_offset": 1,
          "pack_offset": 0,
          "visible": True,
          "x": 14,
          "y": 79,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.NORTHWEST
        }
      ]
    }
  ]
}
