
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
room = {
  "partition": {
    "ally_sprite_buffer_size": 1,
    "allow_extra_sprite_buffer": True,
    "extra_sprite_buffer_size": 0,
    "buffer_a": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_b": {
      "type": PartitionBufferTypes._4_SPRITES_PER_ROW,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_c": {
      "type": PartitionBufferTypes.COINS,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "full_palette_buffer": False,
  },
  "music": Music._41_SUNKEN_SHIP,
  "entrance_event": 15,
  "event_tiles": [
    {
      "event": 3272,
      "x": 7,
      "y": 20,
      "z": 5,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 4,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 3273,
      "x": 13,
      "y": 24,
      "z": 0,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 4,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 3118,
      "x": 5,
      "y": 28,
      "z": 5,
      "f": Edge.SOUTHEAST,
      "length": 5,
      "height": 2,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    }
  ],
  "exit_fields": [
    {
      "x": 0,
      "y": 33,
      "z": 5,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._184_SUNKEN_SHIP_POSTKC_AREA_09_HIDONS_ROOM_WSAVE_POINT,
      "show_message": False,
      "destination_props": {
        "x": 30,
        "y": 113,
        "z": 0,
        "z_half": False,
        "f": RadialDirection.SOUTHWEST,
        "x_bit_7": False
      }
    },
    {
      "x": 7,
      "y": 19,
      "z": 5,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._188_SUNKEN_SHIP_POSTKC_AREA_11_WATER_ROOM_WITH_WHIRLPOOL,
      "show_message": False,
      "destination_props": {
        "x": 1,
        "y": 82,
        "z": 5,
        "z_half": False,
        "f": RadialDirection.NORTHEAST,
        "x_bit_7": False
      }
    },
    {
      "x": 13,
      "y": 23,
      "z": 0,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._188_SUNKEN_SHIP_POSTKC_AREA_11_WATER_ROOM_WITH_WHIRLPOOL,
      "show_message": False,
      "destination_props": {
        "x": 7,
        "y": 86,
        "z": 0,
        "z_half": False,
        "f": RadialDirection.NORTHEAST,
        "x_bit_7": False
      }
    }
  ],
  "objects": [
    {
      "id": 0,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 195,
      "event_script": 241,
      "action_script": 925,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 6,
      "y": 40,
      "z": 1,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": False,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": True,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 1,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 195,
      "event_script": 240,
      "action_script": 925,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 10,
      "y": 32,
      "z": 1,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": False,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": True,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 2,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 195,
      "event_script": 239,
      "action_script": 925,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 6,
      "y": 32,
      "z": 1,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": False,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": True,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 3,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 195,
      "event_script": 238,
      "action_script": 925,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 8,
      "y": 36,
      "z": 1,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": False,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": True,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 4,
      "type": ObjectType.BATTLE,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 329,
      "battle_pack": 67,
      "after_battle": 0,
      "action_script": 345,
      "speed": 0,
      "action_offset": 0,
      "pack_offset": 0,
      "visible": True,
      "x": 6,
      "y": 37,
      "z": 1,
      "z_half": True,
      "direction": RadialDirection.NORTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": True,
      "cant_walk_under": False,
      "cant_pass_walls": True,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 5,
          "action_offset": 0,
          "pack_offset": 0,
          "visible": True,
          "x": 6,
          "y": 30,
          "z": 2,
          "z_half": True,
          "direction": RadialDirection.SOUTHEAST
        }
      ]
    },
    {
      "id": 6,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.PRESS_A_FROM_FRONT,
      "model": 253,
      "event_script": 256,
      "action_script": 15,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 3,
      "y": 35,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHEAST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": False,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    }
  ]
}
