
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
room = {
  "partition": {
    "ally_sprite_buffer_size": 1,
    "allow_extra_sprite_buffer": True,
    "extra_sprite_buffer_size": 0,
    "buffer_a": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_b": {
      "type": PartitionBufferTypes._4_SPRITES_PER_ROW,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_c": {
      "type": PartitionBufferTypes.COINS,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "full_palette_buffer": True,
  },
  "music": Music._22_MIDAS_RIVER,
  "entrance_event": 3480,
  "event_tiles": [],
  "exit_fields": [],
  "objects": [
    {
      "id": 0,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 64,
      "event_script": 1551,
      "action_script": 160,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": False,
      "x": 0,
      "y": 0,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 1,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 96,
      "event_script": 1551,
      "action_script": 160,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": False,
      "x": 0,
      "y": 0,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 2,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 202,
      "event_script": 3487,
      "action_script": 163,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": False,
      "x": 0,
      "y": 0,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": True,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 3,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 194,
      "event_script": 3488,
      "action_script": 163,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": False,
      "x": 0,
      "y": 0,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": True,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 4,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": False,
          "x": 0,
          "y": 0,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 5,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": False,
          "x": 0,
          "y": 0,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 6,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": False,
          "x": 0,
          "y": 0,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 7,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": False,
          "x": 0,
          "y": 0,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 8,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": False,
          "x": 0,
          "y": 0,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 9,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": False,
          "x": 0,
          "y": 0,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 10,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": False,
          "x": 0,
          "y": 0,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 11,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": False,
          "x": 0,
          "y": 0,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        }
      ]
    },
    {
      "id": 12,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 80,
      "event_script": 1551,
      "action_script": 46,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 8,
      "y": 4,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 13,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 9,
          "y": 4,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 14,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 10,
          "y": 4,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 15,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 9,
          "y": 4,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 16,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 10,
          "y": 4,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        }
      ]
    }
  ]
}
