
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
room = {
  "partition": {
    "ally_sprite_buffer_size": 1,
    "allow_extra_sprite_buffer": False,
    "extra_sprite_buffer_size": 0,
    "buffer_a": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_b": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "buffer_c": {
      "type": PartitionBufferTypes.EMPTY_3,
      "main_buffer_space": PartitionMainSpace._0_BYTES,
      "index_in_main_buffer": True,
    },
    "full_palette_buffer": True,
  },
  "music": Music._32_AND_MY_NAMES_BOOSTER,
  "entrance_event": 2576,
  "event_tiles": [
    {
      "event": 2401,
      "x": 22,
      "y": 61,
      "z": 4,
      "f": Edge.SOUTHEAST,
      "length": 1,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2401,
      "x": 22,
      "y": 63,
      "z": 4,
      "f": Edge.SOUTHEAST,
      "length": 1,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2403,
      "x": 26,
      "y": 66,
      "z": 4,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2404,
      "x": 19,
      "y": 65,
      "z": 0,
      "f": Edge.SOUTHEAST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    }
  ],
  "exit_fields": [
    {
      "x": 26,
      "y": 65,
      "z": 4,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._037_BOOSTER_TOWER_4F_3LEVEL_ROOM_WJUMPING_SPOOKUMS,
      "show_message": False,
      "destination_props": {
        "x": 11,
        "y": 49,
        "z": 0,
        "z_half": False,
        "f": RadialDirection.NORTHEAST,
        "x_bit_7": False
      }
    },
    {
      "x": 19,
      "y": 64,
      "z": 0,
      "f": Edge.SOUTHEAST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._259_BOOSTER_TOWER_3F_AREA_01_GREEN_SWITCH_FOR_BP_SECRET,
      "show_message": False,
      "destination_props": {
        "x": 30,
        "y": 123,
        "z": 0,
        "z_half": False,
        "f": RadialDirection.NORTHWEST,
        "x_bit_7": False
      }
    }
  ],
  "objects": [
    {
      "id": 0,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 12,
      "event_script": 2304,
      "action_script": 15,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 22,
      "y": 61,
      "z": 4,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    },
    {
      "id": 1,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 255,
      "event_script": 2575,
      "action_script": 15,
      "speed": 4,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": False,
      "x": 24,
      "y": 66,
      "z": 4,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": False,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 2,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": False,
          "x": 24,
          "y": 65,
          "z": 4,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 3,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": False,
          "x": 21,
          "y": 66,
          "z": 4,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 4,
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": False,
          "x": 20,
          "y": 65,
          "z": 4,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        }
      ]
    }
  ]
}
