from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=26,
        y=115,
        z=3,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=1,
        nw_se_edge_active = True,
        ne_sw_edge_active = True,
        byte_2_bit_2 = False,
        destination = R182_SUNKEN_SHIP_POSTKC_AREA_07_THREE_DRY_BONES,
        show_message = False,
        dst_x = 23,
        dst_y = 97,
        dst_z = 1,
        dst_z_half = True,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=31,
        y=111,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R187_SUNKEN_SHIP_POSTKC_AREA_10_WATER_ROOM_WITH_FROG_COINS,
        show_message = False,
        dst_x = 1,
        dst_y = 32,
        dst_z = 5,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
