from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=3,
        y=83,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R161_SUNKEN_SHIP_AREA_03_GREAPERS,
        show_message = False,
        dst_x = 9,
        dst_y = 43,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=10,
        y=69,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R167_SUNKEN_SHIP_AREA_05_LONG_STAIRWELL_WITH_RUNNING_ALLEY_RATS,
        show_message = False,
        dst_x = 17,
        dst_y = 26,
        dst_z = 6,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
