from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=3,
        y=118,
        z=4,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R138_LANDS_END_AREA_02,
        show_message = False,
        dst_x = 30,
        dst_y = 20,
        dst_z = 4,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=18,
        y=87,
        z=6,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R141_LANDS_END_AREA_04_ROTATING_FLOWERS,
        show_message = False,
        dst_x = 1,
        dst_y = 45,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
