from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=1,
        y=64,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R122_NIMBUS_CASTLE_AREA_12_ENTRANCE_TO_THRONE_ROOM,
        show_message = False,
        dst_x = 3,
        dst_y = 121,
        dst_z = 3,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=7,
        y=46,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R411_NIMBUS_CASTLE_PATH_AFTER_THRONE_ROOM_1ST,
        show_message = False,
        dst_x = 12,
        dst_y = 123,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
]
