from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=7,
        y=105,
        z=3,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R499_NIMBUS_CASTLE_AREA_05_LONG_5EXIT_ROOM_AFTER_VALENTINA,
        show_message = False,
        dst_x = 19,
        dst_y = 109,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=1,
        y=122,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R116_NIMBUS_CASTLE_AREA_02_LEFT_OF_AREA_01,
        show_message = False,
        dst_x = 30,
        dst_y = 43,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=3,
        y=122,
        z=3,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R501_NIMBUS_CASTLE_AREA_03_4WAY_PATH_AFTER_VALENTINA,
        show_message = False,
        dst_x = 26,
        dst_y = 11,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHEAST,
        x_bit_7 = False,
    ),
]
