from randomizer.entities.rooms.exit_imports import *

exits = [
    MapExit(
        x=1,
        y=121,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = True,
        destination = OW26_BOOSTER_TOWER,
        show_message = False,
        byte_2_bit_1 = False,
        byte_2_bit_0 = False,
    ),
    RoomExit(
        x=8,
        y=108,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = False,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R043_BOOSTER_TOWER_1F_AREA_01_MAIN_ROOM,
        show_message = False,
        dst_x = 22,
        dst_y = 117,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=7,
        y=109,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = False,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R043_BOOSTER_TOWER_1F_AREA_01_MAIN_ROOM,
        show_message = False,
        dst_x = 22,
        dst_y = 117,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
