# pylint: disable=C0301,C0103

"""referenced by monster_spells Blizzard, monster_spells IceRock, monster_spells Crystal, monster_spells DiamondSaw"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=548,
    script=[
        ResetTargetMappingMemory(identifier="queuestart_0x35459e"),
        SetAMEM60ToCurrentTarget(),
        EnableSpritesOnSubscreen(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=0,
            z=-96,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ClearAMEM8Bit(0x64),
        SetAMEM16BitToConst(0x60, 9),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        SetAMEM16BitToConst(0x60, 9),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        SetAMEM16BitToConst(0x60, 9),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        Pause1Frame(identifier="command_0x3545cf"),
        JmpIfAMEM8BitNotEqualsConst(0x64, 3, ["command_0x3545cf"]),
        DisableSpritesOnSubscreen(),
        Jmp(["command_0x35252f"]),
        RunSubroutine(["command_0x353437"], identifier="queuestart_0x3545da"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=160,
            y=128,
            z=-48,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 9),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        SetAMEM16BitToConst(0x60, 5),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35624B),
        RunSubroutine(["command_0x352552"]),
        RunSubroutine(["command_0x353400"]),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x354604",
        ),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        NewEffectObject(effect=EF0057_SNOW_CONFETTI__SLATE_GREEN, playback_off=True),
        PlaySound(sound=S0104_BLIZZARD),
        Db(bytearray(b"\x9c\x00D\x10\x00\x08\x00 \x00")),
        FadeInEffect(duration=1),
        Layer3On(prop=OVERLAP_ALL, bpp4=True),
        Db(bytearray(b"\xdd\x04\x0e\x05\x02\x00")),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=140),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        Db(bytearray(b"\x9d\x02")),
        Layer3Off(prop=OVERLAP_ALL, bpp4=True),
        Db(bytearray(b"\xde")),
        RunSubroutine(["command_0x353399"]),
        Pause2Frames(),
        ClearEffectIndex(),
        ReturnObjectQueue(),
        ResetTargetMappingMemory(identifier="queuestart_0x354642"),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=128,
            y=-64,
            z=-80,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        EnableSpritesOnSubscreen(),
        NewSpriteAtCoords(
            sprite_id=SPR0791_ICE_ROCK,
            sequence=0,
            priority=0,
            vram_address=0x6200,
            palette_row=8,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        FadeInSprite(duration=2),
        VisibilityOn(),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=0,
            apply_to_x=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=0,
            apply_to_y=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=17,
            start_position=-257,
            end_position=256,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        MoveObject(
            speed=17,
            start_position=256,
            end_position=-257,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        MoveObject(
            speed=17,
            start_position=-257,
            end_position=256,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        MoveObject(
            speed=17,
            start_position=256,
            end_position=-257,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=33,
            start_position=0,
            end_position=1280,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=28),
        PlaySound(sound=S0103_CRYSTAL_HITS),
        ShakeScreen(amount=5, speed=8),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        StopShakingObject(),
        MoveObject(
            speed=41,
            start_position=-513,
            end_position=1280,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        ResetObjectMappingMemory(),
        SpriteSequence(sequence=1),
        PauseScriptUntilSpriteSequenceDone(),
        DisableSpritesOnSubscreen(),
        Jmp(["command_0x35252f"]),
        ResetTargetMappingMemory(identifier="queuestart_0x3546cd"),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-8,
            y=0,
            z=-96,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0791_ICE_ROCK,
            sequence=2,
            priority=0,
            vram_address=0x6200,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        MoveObject(
            speed=33,
            start_position=0,
            end_position=1280,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        MoveObject(
            speed=41,
            start_position=-513,
            end_position=1280,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        PlaySound(sound=S0103_CRYSTAL_HITS),
        SpriteSequence(sequence=3),
        PauseScriptUntilSpriteSequenceDone(),
        ClearAMEM8Bit(0x64),
        SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
        IncAMEM8Bit(0x64),
        SetOMEMMainToAMEM8Bit(omem=0x64, amem=0x64),
        RemoveObject(),
        ReturnObjectQueue(),
        ResetTargetMappingMemory(identifier="queuestart_0x35470b"),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=8,
            y=0,
            z=-96,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0791_ICE_ROCK,
            sequence=2,
            priority=0,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        MoveObject(
            speed=33,
            start_position=0,
            end_position=1280,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        MoveObject(
            speed=41,
            start_position=-513,
            end_position=1280,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        PlaySound(sound=S0103_CRYSTAL_HITS),
        SpriteSequence(sequence=3),
        PauseScriptUntilSpriteSequenceDone(),
        ClearAMEM8Bit(0x64),
        SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
        IncAMEM8Bit(0x64),
        SetOMEMMainToAMEM8Bit(omem=0x64, amem=0x64),
        RemoveObject(),
        ReturnObjectQueue(),
        ResetTargetMappingMemory(identifier="queuestart_0x354749"),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=0,
            z=-96,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0791_ICE_ROCK,
            sequence=2,
            priority=0,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        MoveObject(
            speed=33,
            start_position=0,
            end_position=1280,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        MoveObject(
            speed=41,
            start_position=-513,
            end_position=1280,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        PlaySound(sound=S0103_CRYSTAL_HITS),
        SpriteSequence(sequence=3),
        PauseScriptUntilSpriteSequenceDone(),
        ClearAMEM8Bit(0x64),
        SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
        IncAMEM8Bit(0x64),
        SetOMEMMainToAMEM8Bit(omem=0x64, amem=0x64),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x354787",
        ),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        NewEffectObject(effect=EF0057_SNOW_CONFETTI__SLATE_GREEN, playback_off=True),
        Db(bytearray(b"\x9c\x00D\x10\x00\x08\x00 \x00")),
        FadeInEffect(duration=1),
        Layer3On(prop=OVERLAP_ALL, bpp4=True),
        Db(bytearray(b"\xdd\x04\x0e\x05\x02\x00")),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=140),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        Db(bytearray(b"\x9d\x02")),
        Layer3Off(prop=OVERLAP_ALL, bpp4=True),
        Db(bytearray(b"\xde")),
        Pause2Frames(),
        ClearEffectIndex(),
        Jmp(["command_0x35252f"]),
    ],
)
