# referenced by monster_spells StaticE, monster_spells Bolt, monster_spells Electroshock

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=159,
    script=[
        ResetTargetMappingMemory(identifier="queuestart_0x354e72"),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=7,
            y=-84,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewEffectObject(effect=EF0006_BOLT, looping_off=True),
        FadeInEffect(duration=1),
        Layer3On(property=OVERLAP_ALL, bpp4=True),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        FadeOutObject(duration=4),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        Layer3Off(property=OVERLAP_ALL, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=8,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x354e93",
        ),
        NewEffectObject(effect=EF0061_STATIC_E___ELECTRIC_BLAST_, looping_off=True),
        Layer3On(property=OVERLAP_ALL, bpp4=True),
        PauseScriptUntil(condition=SEQ_4BPP_COMPLETE),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(property=OVERLAP_ALL, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        Jmp(["command_0x35252f"]),
        ResetTargetMappingMemory(identifier="queuestart_0x354eaf"),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-2,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ClearAMEM8Bit(0x68),
        ClearAMEM8Bit(0x60),
        SetAMEM16BitToConst(0x60, 0),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35624B),
        RunSubroutine(["command_0x352552"]),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=8,
            y=-1,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewEffectObject(effect=EF0068_ELECTROSHOCK, looping_off=True),
        Db(bytearray(b"y\x00\x11\x18\x02")),
        FadeInEffect(duration=1),
        Layer3On(property=OVERLAP_ALL, bpp4=True),
        PlaySound(sound=S0022_CORONA_DESCENDS),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ClearAMEM8Bit(0x68),
        ClearAMEM8Bit(0x60),
        SetAMEM16BitToConst(0x60, 0),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35624B),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        RunSubroutine(["command_0x352552"]),
        FadeOutObject(duration=3),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(property=OVERLAP_ALL, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        Db(bytearray(b"y\x00\x11\x18\x00")),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        Jmp(["command_0x35253b"]),
    ],
)
