# referenced by ally_spells Come Back, ally_spells Shocker, ally_spells Psychopath, ally_spells Super Flame, ally_spells Crusher, ally_spells Geno Whirl, ally_spells Geno Boost, ally_spells Poison Gas, ally_spells HP Rain, ally_spells Snowy, ally_spells Thunderbolt, ally_spells Psych Bomb, ally_spells Geno Flash, ally_spells Sleepy Time, ally_spells Terrorize, ally_spells Therapy, ally_spells Ultra Flame, ally_spells Geno Blast, ally_spells Mute, ally_spells Star Rain, ally_spells Geno Beam

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=127,
    script=[
        SpriteSequence(sequence=0, looping_off=True, identifier="command_0x3580b4"),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=112,
            y=155,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1792, arch_height=96),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        ReturnSubroutine(),
        SpriteSequence(sequence=0, looping_off=True, identifier="command_0x3580cb"),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=96,
            y=163,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1792, arch_height=96),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        ReturnSubroutine(),
        SpriteSequence(sequence=0, looping_off=True, identifier="command_0x3580e2"),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"Dh")),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1792, arch_height=96),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        ReturnSubroutine(),
        SpriteSequence(sequence=0, looping_off=True, identifier="command_0x3580f5"),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-52,
            y=26,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1792, arch_height=96),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        ReturnSubroutine(),
        SpriteSequence(sequence=0, looping_off=True, identifier="command_0x35810e"),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=44,
            y=199,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1792, arch_height=96),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        ReturnSubroutine(),
        SpriteSequence(sequence=4, identifier="command_0x358127"),
        PauseScriptUntilSpriteSequenceDone(),
        ReturnSubroutine(),
        SetAMEMToRandom(amem=0x60, upper_bound=8),
        ObjectQueueAtOffsetAndIndexAtAMEM60(target_address=0x358133),
        ReturnSubroutine(),
    ],
)
