# referenced by behaviour_24_0x350A9C, behaviour_8_0x3507A2, monster_attacks Backfire, monster_spells Escape, behaviour_32_0x350C14, behaviour_23_0x350A55, behaviour_9_0x3507E9, monster_spells LightBeam, behaviour_35_0x350CDC, behaviour_17_0x35096F, monster_attacks DarkClaw, behaviour_33_0x350C5B, behaviour_16_0x350928, behaviour_25_0x350ABD, monster_spells LightningOrb, behaviour_10_0x350830, monster_attacks Endobubble, monster_attacks LullaBye, behaviour_44_0x350E4A

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=217,
    script=[
        SpriteSequence(sequence=4, identifier="command_0x3531f8"),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        Jmp(["command_0x350d31"]),
        SpriteSequence(sequence=2, identifier="command_0x3531ff"),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        Jmp(["command_0x3505d5"]),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        Jmp(["command_0x3508b5"]),
        RunSubroutine(["command_0x35322b"], identifier="command_0x353219"),
        Jmp(["command_0x3505d5"]),
        RunSubroutine(["command_0x353274"]),
        Jmp(["command_0x3508b5"]),
        RunSubroutine(["command_0x353274"], identifier="command_0x353225"),
        Jmp(["command_0x3509ae"]),
        SpriteSequence(sequence=0, mirror=True, identifier="command_0x35322b"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        PlaySound(sound=S0062_MONSTER_RUN_AWAY),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=22,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=512, arch_height=128),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=72,
            y=-36,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=768, arch_height=192),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=192,
            y=-96,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=256),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        Db(bytearray(b"\xd6")),
        ReturnSubroutine(),
        SpriteSequence(sequence=0, mirror=True, identifier="command_0x353274"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        PlaySound(sound=S0062_MONSTER_RUN_AWAY),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=100,
            y=-100,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X04, speed=1280, arch_height=208),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        Db(bytearray(b"\xd6")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6D),
        SetAMEM8BitToConst(0x6D, 1),
        Pause1Frame(identifier="command_0x35329d"),
        SetAMEMToAMEM8Bit(dest_amem=0xA8, amem=0x6A),
        SetAMEMToAMEM8Bit(dest_amem=0xA7, amem=0x6D),
        IncAMEM8BitByAMEM(amem=0x6A, source_amem=0xCC),
        JmpIfAMEM8BitGreaterOrEqualThanAMEM(
            amem=0x6A, source_amem=0xCB, destinations=["command_0x3532b3"]
        ),
        Jmp(["command_0x35329d"]),
        ReturnSubroutine(identifier="command_0x3532b3"),
        ClearAMEM8Bit(0x6D),
        SetAMEM8BitToConst(0x6D, 1),
        Pause1Frame(identifier="command_0x3532ba"),
        SetAMEMToAMEM8Bit(dest_amem=0xA8, amem=0x6A),
        SetAMEMToAMEM8Bit(dest_amem=0xA7, amem=0x6D),
        DecAMEM8BitByAMEM(amem=0x6A, source_amem=0xCC),
        JmpIfAMEM8BitLessThanAMEM(
            amem=0x6A, source_amem=0xCB, destinations=["command_0x3532d0"]
        ),
        Jmp(["command_0x3532ba"]),
        ReturnSubroutine(identifier="command_0x3532d0"),
    ],
)
