# referenced by monster_spells WaterBlast

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=221,
    script=[
        RunSubroutine(["command_0x353437"], identifier="queuestart_0x3559fc"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 30),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x353706),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x353706),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        ObjectQueueAtOffsetAndIndex(
            index=6, target_address=0x353706, identifier="command_0x355a2d"
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        IncAMEM8Bit(0x68),
        JmpIfAMEM8BitNotEqualsConst(0x68, 5, ["command_0x355a2d"]),
        RunSubroutine(["command_0x35337d"]),
        RunSubroutine(["command_0x3533f5"]),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=16,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x355a56",
        ),
        NewEffectObject(effect=EF0053_LIGHT_BLUE_BLAST, looping_off=True),
        RunSubroutine(["command_0x353399"]),
        RunSubroutine(["command_0x3533ea"]),
        Layer3On(property=OVERLAP_ALL, bpp4=True),
        PlaySound(sound=S0110_HUGE_EXPLOSION),
        RunSubroutine(["command_0x3533a7"]),
        PauseScriptUntil(condition=SEQ_4BPP_COMPLETE),
        FadeOutObject(duration=3),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        RunSubroutine(["command_0x35338b"]),
        Layer3Off(property=OVERLAP_ALL, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x355a7e",
        ),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-1537,
            end_position=-1537,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        NewEffectObject(effect=EF0057_SNOW_CONFETTI__SLATE_GREEN, playback_off=True),
        RunSubroutine(["command_0x353400"]),
        FadeInEffect(duration=1),
        Layer3On(property=OVERLAP_ALL, bpp4=True),
        RunSubroutine(["command_0x35340b"]),
        Layer3Off(property=OVERLAP_ALL, bpp4=True),
        RunSubroutine(["command_0x3533f5"]),
        ResetObjectMappingMemory(),
        Pause2Frames(),
        ClearEffectIndex(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x352ae6"], identifier="queuestart_0x355aa6"),
        PlaySound(sound=S0178_POISON_GAS_2),
        NewSpriteAtCoords(
            sprite_id=SPR0803_WATER_BLAST_WATER_SPOUTS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x352ae6"], identifier="queuestart_0x355ab7"),
        PlaySound(sound=S0178_POISON_GAS_2),
        NewSpriteAtCoords(
            sprite_id=SPR0803_WATER_BLAST_WATER_SPOUTS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x352ae6"], identifier="queuestart_0x355ac8"),
        PlaySound(sound=S0178_POISON_GAS_2),
        NewSpriteAtCoords(
            sprite_id=SPR0803_WATER_BLAST_WATER_SPOUTS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
    ],
)
