# pylint: disable=C0301,C0103

"""referenced by monster_attacks PhysicalAttack56, monster_attacks GunkBall, monster_attacks PhysicalAttack40, behaviour_46_0x350E98, behaviour_53_0x350F7A, monster_attacks TripleKick, monster_attacks PhysicalAttack10, monster_spells PetalBlast, behaviour_28_0x350BB7, behaviour_37_0x350D36, monster_attacks PhysicalAttack32, monster_attacks Poison, monster_spells DiamondSaw, monster_attacks GetTough, behaviour_44_0x350E4A, monster_spells Boulder, monster_spells WillyWisp"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=147,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x356a82"),
        NewSpriteAtCoords(
            sprite_id=SPR0797_SLEEPY_TIME_SHEEP_RAM,
            sequence=5,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        ClearAMEM8Bit(0x68),
        ClearAMEM8Bit(0x69),
        SetAMEM16BitToConst(0x60, 9),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=55),
        SpriteSequence(sequence=4),
        Pause1Frame(identifier="command_0x356ab1"),
        JmpIfAMEM8BitNotEqualsConst(0x69, 4, ["command_0x356ab1"]),
        Jmp(["command_0x356b01"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x356abb"),
        NewSpriteAtCoords(
            sprite_id=SPR0797_SLEEPY_TIME_SHEEP_RAM,
            sequence=5,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        ClearAMEM8Bit(0x67),
        ClearAMEM8Bit(0x69),
        SetAMEM16BitToConst(0x60, 9),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=55),
        SpriteSequence(sequence=4),
        Pause1Frame(identifier="command_0x356aea"),
        JmpIfAMEM8BitNotEqualsConst(0x69, 4, ["command_0x356aea"]),
        Jmp(["command_0x356b0b"]),
        SetAMEM8BitToOMEMMain(amem=0x69, omem=0x69),
        IncAMEM8Bit(0x69),
        SetOMEMMainToAMEM8Bit(omem=0x69, amem=0x69),
        RemoveObject(),
        ResetObjectMappingMemory(),
        ReturnObjectQueue(),
        IncAMEM8BitByConst(0x68, 1, identifier="command_0x356b01"),
        SetOMEMMainToAMEM8Bit(omem=0x68, amem=0x68),
        RemoveObject(),
        ReturnObjectQueue(),
        IncAMEM8BitByConst(0x67, 1, identifier="command_0x356b0b"),
        SetOMEMMainToAMEM8Bit(omem=0x67, amem=0x67),
        RemoveObject(),
        ReturnObjectQueue(),
    ])
