# pylint: disable=C0301,C0103

"""referenced by ally_spells Geno Flash"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=162,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35be0e",
        ),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6D),
        Db(bytearray(b" \x80\x10\x00")),
        JmpIfAMEM8BitGreaterOrEqualThanConst(0x60, 31, ["command_0x35be28"]),
        DisplayMessage(BATTLE_MESSAGE, 13),
        PauseScriptUntilDialogClosed(),
        ClearAMEM16Bit(0x60, identifier="command_0x35be28"),
        ClearAMEM16Bit(0x6D),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6E),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35B43D),
        Db(bytearray(b"\x84\x03\x00")),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35BE04),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35BE04),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        Db(bytearray(b"\x84\x03\x00")),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        RemoveObject(),
        ReturnObjectQueue(),
        ScreenEffect(SEF0000_GENO_FLASH, identifier="queuestart_0x35be52"),
        Db(bytearray(b"\xa8\x02\x00")),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35be60",
        ),
        Db(bytearray(b"\x8b\x11\x00\x00\x11")),
        DoMaskEffect(CYLINDER_MASK),
        SetMaskCoords((1, 18), (-113, 13), (33, 56), (42, 0)),
        SetAMEM16BitTo7E1x(0x60, 0x7E0750),
        Db(bytearray(b"\x9b\x02\x00\x02\x03")),
        Pause1Frame(identifier="command_0x35be82"),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 1, ["command_0x35be82"]),
        Db(bytearray(b"\x9b\x03\x00\x08\x03")),
        SetAMEMToAMEM16Bit(dest_amem=0x8A, amem=0x68),
        Db(bytearray(b"\x90")),
        DisableSpritesOnSubscreen(),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=103, identifier="queuestart_0x35bea3"
        ),
        SetAMEM8BitToConst(0x6F, 1),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6F),
        ReturnObjectQueue(),
    ],
)
