# pylint: disable=C0301,C0103

"""referenced by behaviour_33_0x350C5B, behaviour_24_0x350A9C, behaviour_8_0x3507A2, behaviour_16_0x350928, behaviour_32_0x350C14, behaviour_23_0x350A55, behaviour_9_0x3507E9, monster_spells DarkStar"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=312,
    script=[
        ClearAMEM16Bit(0x60, identifier="queuestart_0x35c4c6"),
        ClearAMEM8Bit(0x6F),
        Db(bytearray(b"\xe5\x01")),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35C4BE),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        Db(bytearray(b"\xe5\x00")),
        ReturnObjectQueue(),
        PlaySound(sound=S0086_LONG_FALL, identifier="queuestart_0x35c4da"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=224,
            y=-112,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        NewEffectObject(effect=EF0027_DARK_STAR, looping_off=True),
        DoMaskEffect(POLYGON_MASK),
        SetMaskCoords((8, -16), (112, 120), (112, 120), (-128, -16)),
        ScreenFlash(BLUE, 8),
        Layer3On(prop=TRANSPARENCY_OFF, bit_0=True, bpp4=True),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=32,
            y=80,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        PlaySound(sound=S0087_BIG_BOUNCE),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6D),
        ShakeScreen(amount=3, speed=256),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35C4BE),
        ScreenFlashWithDuration(WHITE, 1, 16),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        StopShakingObject(),
        ClearAMEM8Bit(0x6C),
        PlaySound(sound=S0172_WEAPON_TIMING, channel=4, identifier="command_0x35c523"),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35C363),
        MoveObject(
            speed=209,
            start_position=-4609,
            end_position=4608,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        Pause1Frame(),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True),
        PauseScriptUntil(condition=0x01),
        PlaySound(sound=S0087_BIG_BOUNCE),
        ResetObjectMappingMemory(),
        ShakeScreen(amount=3, speed=256),
        ClearAMEM8Bit(0x6D),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35C4BE),
        ScreenFlashWithDuration(WHITE, 1, 16),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        StopShakingObject(),
        IncAMEM8Bit(0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 2, ["command_0x35c523"]),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35C363),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=-128,
            y=80,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1280, arch_height=256),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        PlaySound(sound=S0087_BIG_BOUNCE),
        PauseScriptUntil(condition=SEQ_4BPP_COMPLETE),
        Layer3Off(prop=TRANSPARENCY_OFF, bpp4=True),
        Db(bytearray(b"\x90")),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        Pause2Frames(),
        ClearEffectIndex(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        Db(bytearray(b"\xba\x05\x01\x00"), identifier="queuestart_0x35c58a"),
        NewSpriteAtCoords(
            sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT,
            sequence=0,
            priority=0,
            vram_address=0xA300,
            palette_row=0,
            looping=True,
            param_2_and_0x10=True,
            mirror_sprite=True,
            invert_sprite=True),
        ResetTargetMappingMemory(),
        Db(bytearray(b"\xa8\x02\x00")),
        Pause1Frame(),
        Db(bytearray(b"\xba\x05\x01\x00")),
        NewSpriteAtCoords(
            sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT,
            sequence=0,
            priority=0,
            vram_address=0xA300,
            palette_row=0,
            looping=True,
            overwrite_palette=True,
            mirror_sprite=True,
            invert_sprite=True),
        ResetTargetMappingMemory(),
        Db(bytearray(b"\xa8\x02\x00")),
        Pause1Frame(),
        Db(bytearray(b"\xba\x05\x01\x00")),
        NewSpriteAtCoords(
            sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT,
            sequence=0,
            priority=0,
            vram_address=0xA300,
            palette_row=0,
            looping=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            mirror_sprite=True,
            invert_sprite=True),
        ResetTargetMappingMemory(),
        Db(bytearray(b"\xa8\x02\x00")),
        Pause1Frame(),
        Db(bytearray(b"\xba\x05\x01\x00")),
        NewSpriteAtCoords(
            sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT,
            sequence=0,
            priority=0,
            vram_address=0xA300,
            palette_row=0,
            looping=True,
            mirror_sprite=True,
            invert_sprite=True),
        ResetTargetMappingMemory(),
        Db(bytearray(b"\xa8\x02\x00")),
        Pause1Frame(),
        Db(bytearray(b"\xba\x05\x01\x00")),
        NewSpriteAtCoords(
            sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT,
            sequence=0,
            priority=0,
            vram_address=0xA300,
            palette_row=0,
            looping=True,
            param_2_and_0x10=True,
            mirror_sprite=True,
            invert_sprite=True),
        ResetTargetMappingMemory(),
        Db(bytearray(b"\xa8\x02\x00")),
        Pause1Frame(),
        Db(bytearray(b"\xba\x05\x01\x00")),
        NewSpriteAtCoords(
            sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT,
            sequence=0,
            priority=0,
            vram_address=0xA300,
            palette_row=0,
            looping=True,
            overwrite_palette=True,
            mirror_sprite=True,
            invert_sprite=True),
        ResetTargetMappingMemory(),
        Db(bytearray(b"\xa8\x02\x00")),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
    ])
