# pylint: disable=C0301,C0103

"""referenced by items WiltShroom"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=227,
    script=[
        ClearAMEM16Bit(0x60, identifier="queuestart_0x35ea16"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6E),
        ClearAMEM8Bit(0x6E),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=48,
            y=154,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35EA0C),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=64,
            y=162,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35EA0C),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=80,
            y=170,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35EA0C),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=96,
            y=178,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35EA0C),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=112,
            y=186,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35EA0C),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=128,
            y=194,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35EA0C),
        Pause1Frame(identifier="command_0x35ea7a"),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 6, ["command_0x35ea7a"]),
        JmpIfAMEM8BitEqualsConst(0x6D, 1, ["command_0x35ea8d"]),
        DisplayMessage(BATTLE_MESSAGE, 44),
        Jmp(["command_0x35ea90"]),
        DisplayMessage(BATTLE_MESSAGE, 45, identifier="command_0x35ea8d"),
        PlaySound(sound=S0006_BONUS_FLOWER_STATUS_UP, identifier="command_0x35ea90"),
        PauseScriptUntilDialogClosed(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35ea9c"),
        NewSpriteAtCoords(
            sprite_id=SPR0530_STAT_BOOST_ARROWS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        RunSubroutine(["command_0x35eadb"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35eab1"),
        NewSpriteAtCoords(
            sprite_id=SPR0530_STAT_BOOST_ARROWS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        RunSubroutine(["command_0x35eadb"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35eac6"),
        NewSpriteAtCoords(
            sprite_id=SPR0530_STAT_BOOST_ARROWS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        RunSubroutine(["command_0x35eadb"]),
        ReturnObjectQueue(),
        SetAMEM8BitToOMEMMain(amem=0x6A, omem=0x6D, identifier="command_0x35eadb"),
        JmpIfAMEM8BitEqualsConst(0x6A, 1, ["command_0x35eaea"]),
        PlaySound(sound=S0076_STAT_BOOST_SINGLE),
        Jmp(["command_0x35eaec"]),
        PlaySound(sound=S0077_STAT_BOOST_MULTI, identifier="command_0x35eaea"),
        PauseScriptUntilSpriteSequenceDone(identifier="command_0x35eaec"),
        RemoveObject(),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        IncAMEM8Bit(0x6E),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnSubroutine(),
    ])
