# referenced by ally_spells Come Back

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(expected_size = 208, script = [
	ClearAMEM8Bit(0x6C, identifier="queuestart_0x35a6a1"),
	SetAMEM60ToCurrentTarget(identifier="command_0x35a6a3"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=6, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	ClearAMEM16Bit(0x60),
	ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35A4E7),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-10, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	ClearAMEM16Bit(0x60),
	ObjectQueueAtOffsetAndIndex(index=10, target_address=0x35A4E7),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-2, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	ClearAMEM16Bit(0x60),
	ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35A4E7),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=14, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	ClearAMEM16Bit(0x60),
	ObjectQueueAtOffsetAndIndex(index=10, target_address=0x35A4E7),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
	IncAMEM8Bit(0x6C),
	JmpIfAMEM8BitNotEqualsConst(0x6C, 2, ["command_0x35a6a3"]),
	SetAMEM8BitToConst(0x6E, 1),
	SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="queuestart_0x35a700"),
	NewSpriteAtCoords(sprite_id=SPR0561_BLUE_CURE_STARS, sequence=0, priority=3, vram_address=0x6400, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	ShineEffect(colour_count=6, starting_colour_index=1, glow_duration=1, east=True),
	PauseScriptUntilSpriteSequenceDone(),
	RemoveObject(),
	Db(bytearray(b'\x81')),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="queuestart_0x35a719"),
	NewSpriteAtCoords(sprite_id=SPR0561_BLUE_CURE_STARS, sequence=0, priority=3, vram_address=0x6600, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	ShineEffect(colour_count=6, starting_colour_index=1, glow_duration=1, east=True),
	PauseScriptUntilSpriteSequenceDone(),
	RemoveObject(),
	Db(bytearray(b'\x81')),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=2, y=-5, z=0, set_x=True, set_y=True, set_z=True, identifier="queuestart_0x35a732"),
	Db(bytearray(b'\xa6')),
	NewSpriteAtCoords(sprite_id=SPR0575_SPARKLES, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	RemoveObject(),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-7, y=-2, z=0, set_x=True, set_y=True, set_z=True, identifier="queuestart_0x35a747"),
	Db(bytearray(b'\xa6')),
	NewSpriteAtCoords(sprite_id=SPR0575_SPARKLES, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	RemoveObject(),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=8, y=-2, z=0, set_x=True, set_y=True, set_z=True, identifier="queuestart_0x35a75c"),
	Db(bytearray(b'\xa6')),
	NewSpriteAtCoords(sprite_id=SPR0575_SPARKLES, sequence=1, priority=3, vram_address=0x6400, palette_row=8, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	RemoveObject(),
	ReturnObjectQueue()
])
