# referenced by weapons SpikedLink

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=156,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35f548",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0034_CHOMP,
            sequence=3,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PlaySound(sound=S0121_BIG_SWING),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        PlaySound(sound=S0121_BIG_SWING),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        PlaySound(sound=S0121_BIG_SWING),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        PlaySound(sound=S0121_BIG_SWING),
        PauseScriptUntilSpriteSequenceDone(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=48,
            y=-32,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SpriteSequence(sequence=4),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
        PauseScriptUntil(condition=0x07),
        SetAMEM8BitToConst(0x67, 1),
        SetOMEMMainToAMEM8Bit(omem=0x67, amem=0x67),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        RemoveObject(),
        ReturnObjectQueue(),
        PlaySound(sound=S0137_BOWSER_CRUSH_STOMP, identifier="queuestart_0x35f59a"),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0034_CHOMP,
            sequence=5,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        Db(bytearray(b"\xe5\x01")),
        ScreenFlashWithDuration(WHITE, 1, 16),
        PlaySound(sound=S0042_BLADE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        SpriteSequence(sequence=4, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=5, looping_off=True),
        ScreenFlashWithDuration(WHITE, 1, 16),
        PlaySound(sound=S0042_BLADE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        SpriteSequence(sequence=4, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=5, looping_off=True),
        ScreenFlashWithDuration(WHITE, 1, 16),
        PlaySound(sound=S0042_BLADE),
        RemoveObject(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        Db(bytearray(b"\xe5\x00")),
        ReturnObjectQueue(),
    ],
)
