# referenced by items FrightBomb

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=377,
    script=[
        ClearAMEM16Bit(0x60, identifier="queuestart_0x35e5e0"),
        ClearAMEM8Bit(0x6C),
        ClearAMEM8Bit(0x6D),
        ClearAMEM8Bit(0x6E),
        Db(bytearray(b" \x8a\x01\x00")),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35E5D8),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35E5D8),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        ClearAMEM16Bit(0x62),
        ResetTargetMappingMemory(),
        MuteTimingJmp(["command_0x35e615"]),
        SpriteQueue(
            field_object=0, destinations=["queuestart_0x35daac"], current_target=True
        ),
        PauseScriptUntilAMEMBitsSet(0x6C, [0, 1, 2, 3, 4, 5, 6, 7]),
        JmpIfAMEM8BitEqualsConst(0x6C, 2, ["command_0x35e615"]),
        ClearAMEM8Bit(0x6C),
        SpriteQueue(
            field_object=0, destinations=["queuestart_0x35e6fd"], current_target=True
        ),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        SetAMEM8BitToConst(0x6D, 255, identifier="command_0x35e615"),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35e625"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-16,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        PlaySound(sound=S0115_TRANSFORM),
        NewSpriteAtCoords(
            sprite_id=SPR0195_FLOWER,
            sequence=6,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-16,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0797_SLEEPY_TIME_SHEEP_RAM,
            sequence=3,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=5),
        PauseScriptUntilSpriteSequenceDone(),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        SpriteSequence(sequence=4, looping_on=True),
        Pause1Frame(identifier="command_0x35e656"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitEqualsConst(0x6D, 255, ["command_0x35e6ab"]),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 0, ["command_0x35e656"]),
        SpriteSequence(sequence=3, looping_on=True),
        SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=-32, z=0, set_y=True),
        PlaySound(sound=S0181_LAMB_S_LURE_SINGLE),
        MoveObject(
            speed=49,
            start_position=0,
            end_position=-769,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=33,
            start_position=512,
            end_position=-513,
            apply_to_x=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        DisplayMessage(BATTLE_MESSAGE, 16),
        PauseScriptUntilDialogClosed(),
        PauseScriptUntil(condition=0x02),
        ResetObjectMappingMemory(),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE012),
        IncAMEM8Bit(0x6E),
        JmpIfAMEM8BitLessThanConst(0x6E, 48, ["command_0x35e6a4"]),
        RemoveItemFromStandardInventory(LambsLure),
        AddItemToStandardInventory(SheepAttack),
        DisplayMessage(BATTLE_MESSAGE, 14),
        PauseScriptUntilDialogClosed(),
        ClearAMEM8Bit(0x6E),
        Set7E1xToAMEM8Bit(0x7EE012, 0x6E, identifier="command_0x35e6a4"),
        Jmp(["command_0x35e6bc"]),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-16,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x35e6ab",
        ),
        PlaySound(sound=S0115_TRANSFORM),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0195_FLOWER, sequence=6, store_to_vram=True, store_palette=True
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(identifier="command_0x35e6bc"),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=87, identifier="queuestart_0x35e6c6"
        ),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-16,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0793_BIG_PINK_HEART,
            sequence=2,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=4, y=0, z=0, set_z=True),
        MoveObject(
            speed=17,
            start_position=-305,
            end_position=304,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=136,
            end_position=136,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PlaySound(sound=S0072_PSYCHOPATH_CLOUD_APPEARS),
        PauseScriptUntil(condition=0x04),
        ResetObjectMappingMemory(),
        RemoveObject(),
        ReturnObjectQueue(),
        ResetObjectMappingMemory(identifier="queuestart_0x35e6fd"),
        ClearAMEM8Bit(0x6F),
        SetAMEMToAMEM8Bit(dest_amem=0xA7, amem=0x6F),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_INITIAL_POSITION, x=0, y=-9, z=0, set_y=True
        ),
        PlaySound(sound=S0115_TRANSFORM),
        NewSpriteAtCoords(
            sprite_id=SPR0195_FLOWER,
            sequence=6,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_INITIAL_POSITION, x=0, y=-1, z=0, set_y=True
        ),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0797_SLEEPY_TIME_SHEEP_RAM,
            sequence=5,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        ResetTargetMappingMemory(),
        SpriteSequence(sequence=3, looping_on=True),
        SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=-32, z=0, set_y=True),
        MoveObject(
            speed=49,
            start_position=0,
            end_position=-769,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=33,
            start_position=-513,
            end_position=512,
            apply_to_x=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        ClearAMEM8Bit(0x6D),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        PauseScriptUntil(condition=0x02),
        ResetObjectMappingMemory(),
        RemoveObject(),
        Db(bytearray(b"\xd6")),
        SetAMEM8BitToConst(0x6C, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnObjectQueue(),
    ],
)
