# referenced by ally_spells Psychopath

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=357,
    script=[
        StartTrackingAllyButtonInputs(identifier="queuestart_0x35c12e"),
        SetAMEM16BitToConst(0x60, 0),
        ClearAMEM8Bit(0x6B),
        ClearAMEM8Bit(0x6C),
        ClearAMEM8Bit(0x6D),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        PlaySound(sound=S0071_PSYCHOPATH_DRUM_ROLL),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35C124),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35C124),
        PauseScriptUntilAMEMBitsSet(0x6B, [0]),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6B),
        Pause1Frame(identifier="command_0x35c14e"),
        SetAMEM8BitToOMEMMain(amem=0x6B, omem=0x6E),
        JmpIfAMEM8BitNotEqualsConst(0x6B, 0, ["command_0x35c14e"]),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35C124),
        TimingForOneBinaryButtonPress(
            end_accepting_input=30,
            start_accepting_input=0,
            timed_hit_ends=30,
            destinations=["command_0x35c169"],
        ),
        PlaySound(sound=S0172_WEAPON_TIMING, channel=4),
        SetAMEM8BitToConst(0x6F, 1),
        EndTrackingAllyButtonInputs(identifier="command_0x35c169"),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 1, ["command_0x35c17f"]),
        DisplayMessage(PSYCHOPATH_MESSAGE, 0),
        PlaySound(sound=S0073_PSYCHOPATH_MESSAGE),
        PauseScriptUntilDialogClosed(),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6E, identifier="command_0x35c17f"),
        ReturnObjectQueue(),
        Db(bytearray(b"\x1f\x80"), identifier="queuestart_0x35c184"),
        Db(bytearray(b"\x1e@")),
        Db(bytearray(b"\xdc")),
        Db(bytearray(b">")),
        PlaySound(sound=S0013_COIN),
        Db(bytearray(b"W")),
        SetAMEM8BitToConst(0x6A, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6A, amem=0x6A),
        Db(bytearray(b"\x1f@")),
        Db(bytearray(b"\x1e\x80")),
        ReturnSpriteQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35c19a"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-32,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        PlaySound(sound=S0072_PSYCHOPATH_CLOUD_APPEARS),
        NewSpriteAtCoords(
            sprite_id=SPR0557_PSYCHOPATH_QUESTION_MARK_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ClearAMEM8Bit(0x6A),
        SetAMEM60ToCurrentTarget(),
        SpriteQueue(
            field_object=0, destinations=["queuestart_0x35c184"], current_target=True
        ),
        PauseScriptUntilAMEMBitsSet(0x6A, [0]),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=16,
            y=101,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35c1c4",
        ),
        DoMaskEffect(CIRCLE_MASK),
        SetMaskCoords((1, 16), (-117, 17), (1, 2), (1, -113)),
        MoveObject(
            speed=81,
            start_position=1904,
            end_position=-1905,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=1184,
            end_position=1184,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=46),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=81,
            start_position=-1745,
            end_position=1744,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-545,
            end_position=-545,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=26),
        ResetObjectMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1280, arch_height=0),
        PauseScriptUntil(condition=0x07),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=1),
        SetAMEM8BitToConst(0x6B, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6B, amem=0x6B),
        SetMaskCoords((1, 32), (4, 16), (60, 0), (113, -112)),
        Db(bytearray(b"\xc5")),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6B),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=240,
            y=116,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35c231",
        ),
        DoMaskEffect(CIRCLE_MASK, 128),
        SetMaskCoords((1, 16), (-117, 17), (1, 2), (1, -113)),
        MoveObject(
            speed=81,
            start_position=-1905,
            end_position=1904,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-1185,
            end_position=-1185,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=46),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=81,
            start_position=1744,
            end_position=-1745,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=544,
            end_position=544,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=26),
        ResetObjectMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1280, arch_height=0),
        PauseScriptUntil(condition=0x07),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=1),
        DisableSpritesOnSubscreen(),
        Db(bytearray(b"\x90")),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        SetAMEM8BitToConst(0x6C, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnObjectQueue(),
    ],
)
