# pylint: disable=C0301,C0103

"""referenced by weapons Cymbals, behaviour_34_0x350C9E, behaviour_33_0x350C5B, behaviour_24_0x350A9C, behaviour_8_0x3507A2, behaviour_41_0x350DAF, behaviour_51_0x350F56, behaviour_16_0x350928, behaviour_32_0x350C14, behaviour_52_0x350F6B, weapons SonicCymbal, behaviour_23_0x350A55, behaviour_9_0x3507E9, behaviour_42_0x350DED, behaviour_43_0x350E38"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=140,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35f78b"),
        NewSpriteAtCoords(
            sprite_id=SPR0033_CYMBALS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        PlaySound(sound=S0049_CYMBAL_CRASH),
        PauseScriptUntilSpriteSequenceDone(),
        Pause1Frame(identifier="command_0x35f7a3"),
        SetAMEM8BitToOMEMMain(amem=0x63, omem=0x63),
        JmpIfAMEM8BitNotEqualsConst(0x63, 1, ["command_0x35f7a3"]),
        RemoveObject(),
        SetOMEMMainToAMEM8Bit(omem=0x64, amem=0x63),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35f7b4"),
        Pause1Frame(identifier="command_0x35f7bc"),
        SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
        JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35f7bc"]),
        NewSpriteAtCoords(
            sprite_id=SPR0033_CYMBALS,
            sequence=1,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        PlaySound(sound=S0060_CYMBAL_RESONANCE),
        PauseScriptUntilSpriteSequenceDone(),
        Pause1Frame(identifier="command_0x35f7d3"),
        SetAMEM8BitToOMEMMain(amem=0x65, omem=0x65),
        JmpIfAMEM8BitNotEqualsConst(0x65, 1, ["command_0x35f7d3"]),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35f7e0"),
        Pause1Frame(identifier="command_0x35f7e8"),
        SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
        JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35f7e8"]),
        NewSpriteAtCoords(
            sprite_id=SPR0033_CYMBALS,
            sequence=1,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        PlaySound(sound=S0060_CYMBAL_RESONANCE),
        Db(bytearray(b"\x9c\x00A\x10\x00\x08\x00\xf0\x00")),
        PauseScriptUntilSpriteSequenceDone(),
        Pause1Frame(identifier="command_0x35f808"),
        SetAMEM8BitToOMEMMain(amem=0x65, omem=0x65),
        JmpIfAMEM8BitNotEqualsConst(0x65, 1, ["command_0x35f808"]),
        Db(bytearray(b"\x9d\x02")),
        RemoveObject(),
        ReturnObjectQueue(),
    ])
