# referenced by

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=215,
    script=[
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=104,
            y=160,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ClearAMEM8Bit(0x60),
        SetAMEM16BitToConst(0x60, 10),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x3A8AC0),
        RunSubroutine(["command_0x3a771e"]),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x3A8AC0),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x3A8AC0),
        RunSubroutine(["command_0x3a7734"]),
        RunSubroutine(["command_0x3a773f"]),
        RunSubroutine(["command_0x3a774a"]),
        RunSubroutine(["command_0x3a75ce"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a9fbd",
        ),
        NewEffectObject(effect=EF0025_PSYCH_BOMB__BG_, playback_off=True),
        RunSubroutine(["command_0x3a75b2"]),
        RunSubroutine(["command_0x3a776b"]),
        ScreenFlash(NO_COLOUR, 8),
        RunSubroutine(["command_0x3a756c"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Layer3On(property=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        RunSubroutine(["command_0x3a7755"]),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(property=OVERLAP_ALL_EXCEPT_ALLIES, bpp4=True),
        Db(bytearray(b"\x90")),
        RunSubroutine(["command_0x3a757a"]),
        Pause2Frames(),
        ResetObjectMappingMemory(),
        ClearEffectIndex(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a9ff0",
        ),
        NewEffectObject(effect=EF0057_SNOW_CONFETTI__SLATE_GREEN, playback_off=True),
        RunSubroutine(["command_0x3a75c0"]),
        RunSubroutine(["command_0x3a7760"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=768,
            end_position=768,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Layer3On(property=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        RunSubroutine(["command_0x3a7755"]),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        Layer3Off(property=OVERLAP_ALL_EXCEPT_ALLIES, bpp4=True),
        Pause2Frames(),
        ResetObjectMappingMemory(),
        ClearEffectIndex(),
        RunSubroutine(["command_0x3a7588"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3aa01d",
        ),
        DoMaskEffect(POLYGON_MASK),
        RunSubroutine(["command_0x3a755e"]),
        RunSubroutine(["command_0x3a7729"]),
        PlaySound(sound=S0045_HP_RAIN_CLOUD),
        SetAMEM8BitToConst(0x65, 16),
        SetAMEM8BitToConst(0x66, 0),
        SetAMEM8BitToConst(0x67, 1),
        SetAMEM8BitToConst(0x68, 96),
        SetAMEM8BitToConst(0x69, 0),
        SetAMEM8BitToConst(0x6A, 65409),
        SetAMEM8BitToConst(0x6B, 0),
        SetAMEM8BitToConst(0x6C, 96),
        SetAMEM8BitToConst(0x6D, 0),
        SetAMEM8BitToConst(0x6E, 65409),
        SetAMEM8BitToConst(0x6F, 0),
        RunSubroutine(["command_0x3a8757"]),
        RunSubroutine(["command_0x3a75dc"]),
        RunSubroutine(["command_0x3a7734"]),
        RunSubroutine(["command_0x3a7596"]),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        ReturnObjectQueue(),
    ],
)
