# pylint: disable=C0301,C0103

"""referenced by ally_spells Therapy, items Mushroom, items PickMeUp"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=594,
    script=[
        ClearAMEM16Bit(0x60, identifier="queuestart_0x35cf35"),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6C),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6E),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35CF29),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35CF29),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35CF29),
        JmpIfAMEM8BitEqualsConst(0x6D, 6, ["command_0x35cf61"]),
        JmpIfAMEM8BitGreaterOrEqualThanConst(0x6D, 3, ["command_0x35cf5c"]),
        PlaySound(sound=S0066_RECOVER_HP),
        Jmp(["command_0x35cf63"]),
        PlaySound(sound=S0067_RECOVER_FP, identifier="command_0x35cf5c"),
        Jmp(["command_0x35cf63"]),
        PlaySound(sound=S0068_RECOVER_DRINK, identifier="command_0x35cf61"),
        SetAMEM60ToCurrentTarget(identifier="command_0x35cf63"),
        Db(bytearray(b" \x8a\x01\x00")),
        Db(bytearray(b" \xbb\x01\x00")),
        Pause1Frame(identifier="command_0x35cf6c"),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 3, ["command_0x35cf6c"]),
        JmpIfAMEM8BitEqualsAMEM(
            amem=0x6A, source_amem=0xCB, destinations=["command_0x35cf82"]
        ),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35CF29),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        SetAMEM8BitToConst(0x6F, 1, identifier="command_0x35cf82"),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35cf8b"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-8,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitEqualsConst(0x6D, 2, ["command_0x35cfc6"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6D, 3, ["command_0x35cfd2"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6D, 4, ["command_0x35cfd2"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6D, 5, ["command_0x35cfde"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6D, 6, ["command_0x35cfea"]),
        NewSpriteAtCoords(
            sprite_id=SPR0779_WHITE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        Jmp(["command_0x35cff3"]),
        NewSpriteAtCoords(
            sprite_id=SPR0561_BLUE_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35cfc6",
        ),
        Jmp(["command_0x35cff3"]),
        NewSpriteAtCoords(
            sprite_id=SPR0796_LIGHT_ORANGE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35cfd2",
        ),
        Jmp(["command_0x35cff3"]),
        NewSpriteAtCoords(
            sprite_id=SPR0560_RED_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35cfde",
        ),
        Jmp(["command_0x35cff3"]),
        NewSpriteAtCoords(
            sprite_id=SPR0559_GREEN_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35cfea",
        ),
        RunSubroutine(["command_0x35d0cf"], identifier="command_0x35cff3"),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35cff7"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=8,
            y=-10,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitEqualsConst(0x6D, 2, ["command_0x35d032"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6D, 3, ["command_0x35d03e"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6D, 4, ["command_0x35d03e"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6D, 5, ["command_0x35d04a"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6D, 6, ["command_0x35d056"]),
        NewSpriteAtCoords(
            sprite_id=SPR0779_WHITE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True,
        ),
        Jmp(["command_0x35d05f"]),
        NewSpriteAtCoords(
            sprite_id=SPR0561_BLUE_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True,
            identifier="command_0x35d032",
        ),
        Jmp(["command_0x35d05f"]),
        NewSpriteAtCoords(
            sprite_id=SPR0796_LIGHT_ORANGE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True,
            identifier="command_0x35d03e",
        ),
        Jmp(["command_0x35d05f"]),
        NewSpriteAtCoords(
            sprite_id=SPR0560_RED_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True,
            identifier="command_0x35d04a",
        ),
        Jmp(["command_0x35d05f"]),
        NewSpriteAtCoords(
            sprite_id=SPR0559_GREEN_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True,
            identifier="command_0x35d056",
        ),
        RunSubroutine(["command_0x35d0cf"], identifier="command_0x35d05f"),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35d063"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-24,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitEqualsConst(0x6D, 2, ["command_0x35d09e"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6D, 3, ["command_0x35d0aa"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6D, 4, ["command_0x35d0b6"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6D, 5, ["command_0x35d0b6"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6D, 6, ["command_0x35d0c2"]),
        NewSpriteAtCoords(
            sprite_id=SPR0779_WHITE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        Jmp(["command_0x35d0cb"]),
        NewSpriteAtCoords(
            sprite_id=SPR0561_BLUE_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d09e",
        ),
        Jmp(["command_0x35d0cb"]),
        NewSpriteAtCoords(
            sprite_id=SPR0796_LIGHT_ORANGE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d0aa",
        ),
        Jmp(["command_0x35d0cb"]),
        NewSpriteAtCoords(
            sprite_id=SPR0560_RED_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d0b6",
        ),
        Jmp(["command_0x35d0cb"]),
        NewSpriteAtCoords(
            sprite_id=SPR0795_LIGHT_GREEN_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d0c2",
        ),
        RunSubroutine(["command_0x35d0cf"], identifier="command_0x35d0cb"),
        ReturnObjectQueue(),
        ShineEffect(
            colour_count=6,
            starting_colour_index=1,
            glow_duration=1,
            east=True,
            identifier="command_0x35d0cf",
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        Db(bytearray(b"\x81")),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        IncAMEM8Bit(0x6E),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnSubroutine(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35d0e1"),
        ClearAMEM8Bit(0x6C),
        SpriteQueue(
            field_object=0, destinations=["queuestart_0x35d170"], current_target=True
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=6),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-32,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Db(bytearray(b" \xbf\x01\x00")),
        PlaySound(sound=S0006_BONUS_FLOWER_STATUS_UP),
        JmpIfAMEM8BitEqualsConst(0x6F, 0, ["command_0x35d11a"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6F, 1, ["command_0x35d126"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6F, 2, ["command_0x35d132"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6F, 3, ["command_0x35d13e"]),
        Jmp(["command_0x35d14a"]),
        NewSpriteAtCoords(
            sprite_id=SPR0552_THANK_YOU_RED_DIALOGUE_BUBBLE,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d11a",
        ),
        Jmp(["command_0x35d153"]),
        NewSpriteAtCoords(
            sprite_id=SPR0553_THANK_YOU_PURPLE_DIALOGUE_BUBBLE,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d126",
        ),
        Jmp(["command_0x35d153"]),
        NewSpriteAtCoords(
            sprite_id=SPR0555_THANK_YOU_GREEN_DIALOGUE_BUBBLE,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d132",
        ),
        Jmp(["command_0x35d153"]),
        NewSpriteAtCoords(
            sprite_id=SPR0554_THANK_YOU_BLUE_DIALOGUE_BUBBLE,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d13e",
        ),
        Jmp(["command_0x35d153"]),
        NewSpriteAtCoords(
            sprite_id=SPR0556_THANK_YOU_YELLOW_DIALOGUE_BUBBLE,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d14a",
        ),
        ShineEffect(
            colour_count=14,
            starting_colour_index=10,
            glow_duration=3,
            east=True,
            identifier="command_0x35d153",
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=40),
        RemoveObject(),
        Db(bytearray(b"\x81")),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        SetAMEM60ToCurrentTarget(),
        ClearAMEM8Bit(0x6D),
        SpriteQueue(
            field_object=0, destinations=["queuestart_0x35d17c"], current_target=True
        ),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6D),
        ReturnObjectQueue(),
        SpriteSequence(sequence=10, identifier="queuestart_0x35d170"),
        PauseScriptUntilSpriteSequenceDone(),
        SetAMEM8BitToConst(0x6C, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnSpriteQueue(),
        SpriteSequence(sequence=0, looping_off=True, identifier="queuestart_0x35d17c"),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnSpriteQueue(),
    ],
)
