# pylint: disable=C0301,C0103

"""referenced by monster_attacks PhysicalAttack10, monster_spells Boulder, monster_spells WillyWisp"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=95,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-8,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x356eb6",
        ),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=65,
            start_position=-513,
            end_position=768,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=17,
            start_position=0,
            end_position=-257,
            apply_to_x=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        Jmp(["command_0x356af4"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=8,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x356ed7",
        ),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=65,
            start_position=-513,
            end_position=768,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=17,
            start_position=0,
            end_position=256,
            apply_to_x=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        Jmp(["command_0x356af4"]),
        RunSubroutine(["command_0x352ae6"], identifier="queuestart_0x356ef8"),
        Db(bytearray(b"\x83\x83")),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=120),
        Jmp(["command_0x356af4"]),
    ],
)
