# pylint: disable=C0301,C0103

"""referenced by monster_spells Blast"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=151,
    script=[
        ResetTargetMappingMemory(identifier="queuestart_0x355959"),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=248,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 29),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x353706),
        Pause1Frame(identifier="command_0x3559ad"),
        JmpIfAMEM8BitNotEqualsConst(0x68, 9, ["command_0x3559ad"]),
        Jmp(["command_0x35252f"]),
        RunSubroutine(["command_0x35259b"], identifier="queuestart_0x3559b7"),
        NewSpriteAtCoords(
            sprite_id=SPR0776_BLAST_ORANGE_GAS_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3559e4"]),
        RunSubroutine(["command_0x35259b"], identifier="queuestart_0x3559c7"),
        NewSpriteAtCoords(
            sprite_id=SPR0776_BLAST_ORANGE_GAS_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3559e4"]),
        RunSubroutine(["command_0x35259b"], identifier="queuestart_0x3559d7"),
        NewSpriteAtCoords(
            sprite_id=SPR0776_BLAST_ORANGE_GAS_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        SetAMEM8BitToOMEMMain(amem=0x68, omem=0x68, identifier="command_0x3559e4"),
        IncAMEM8Bit(0x68),
        SetOMEMMainToAMEM8Bit(omem=0x68, amem=0x68),
        RemoveObject(),
        ReturnObjectQueue(),
    ],
)
