# referenced by items BeetleBox

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=343,
    script=[
        ClearAMEM8Bit(0x6F, identifier="queuestart_0x35e86c"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=8,
            y=-34,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0462_EGGBERT,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        MoveObject(
            speed=25,
            start_position=-545,
            end_position=0,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PlaySound(sound=S0061_ITEM_USE),
        RunSubroutine(["command_0x35e980"]),
        Db(bytearray(b"\x12\x81")),
        ResetObjectMappingMemory(),
        JmpIfAMEM8BitEqualsConst(0x6F, 2, ["command_0x35e8e4"]),
        MoveObject(
            speed=33,
            start_position=0,
            end_position=512,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=17),
        ResetObjectMappingMemory(),
        ClearAMEM16Bit(0x60),
        JmpIfAMEM8BitEqualsConst(0x6F, 1, ["command_0x35e8c8"]),
        SetAMEM8BitToConst(0x6D, 1),
        ClearAMEM8Bit(0x6E),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35E866),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        RemoveObject(),
        PlaySound(sound=S0007_ERROR_INCORRECT_ANSWER),
        NewSpriteAtCoords(
            sprite_id=SPR0518_SMALL_WHITE_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        Jmp(["command_0x35e916"]),
        ClearAMEM8Bit(0x6D, identifier="command_0x35e8c8"),
        ClearAMEM8Bit(0x6E),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35E866),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        RemoveObject(),
        PlaySound(sound=S0064_EGG_HATCH),
        NewSpriteAtCoords(
            sprite_id=SPR0518_SMALL_WHITE_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        Jmp(["command_0x35e916"]),
        RemoveObject(identifier="command_0x35e8e4"),
        PlaySound(sound=S0115_TRANSFORM),
        NewSpriteAtCoords(
            sprite_id=SPR0195_FLOWER,
            sequence=6,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0797_SLEEPY_TIME_SHEEP_RAM,
            sequence=5,
            store_to_vram=True,
            store_palette=True,
        ),
        DisplayMessage(BATTLE_MESSAGE, 15),
        PauseScriptUntilDialogClosed(),
        PauseScriptUntilSpriteSequenceDone(),
        SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=-32, z=0, set_y=True),
        PlaySound(sound=S0181_LAMB_S_LURE_SINGLE),
        SpriteSequence(sequence=3, looping_on=True),
        MoveObject(
            speed=49,
            start_position=0,
            end_position=-769,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=0x02),
        ResetObjectMappingMemory(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6F, 1, identifier="command_0x35e916"),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=1,
            y=-26,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35e91f",
        ),
        PlaySound(sound=S0072_PSYCHOPATH_CLOUD_APPEARS),
        NewSpriteAtCoords(
            sprite_id=SPR0793_BIG_PINK_HEART,
            sequence=2,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        MoveObject(
            speed=97,
            start_position=-513,
            end_position=512,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitEqualsConst(0x6D, 1, ["command_0x35e973"]),
        ClearAMEM8Bit(0x6C),
        MoveObject(
            speed=1,
            start_position=240,
            end_position=240,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
            identifier="command_0x35e94b",
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        MoveObject(
            speed=1,
            start_position=-241,
            end_position=-241,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        IncAMEM8Bit(0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 6, ["command_0x35e94b"]),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        Jmp(["command_0x35e976"]),
        SpriteSequence(sequence=4, identifier="command_0x35e973"),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(identifier="command_0x35e976"),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        Db(bytearray(b" \x8a\x01\x00"), identifier="command_0x35e980"),
        SetAMEM8BitTo7E1x(0x6B, 0x7EE012),
        JmpIfAMEM8BitEqualsConst(0x6A, 1, ["command_0x35e99a"]),
        Pause1Frame(),
        JmpIfAMEM8BitLessThanConst(0x6B, 1, ["command_0x35e9c2"]),
        DecAMEM8Bit(0x6B),
        Jmp(["command_0x35e9be"]),
        Db(bytearray(b" \x8a\x1e\x00"), identifier="command_0x35e99a"),
        JmpIfAMEM8BitNotEqualsConst(0x6A, 83, ["command_0x35e9c2"]),
        Pause1Frame(),
        SetAMEM8BitToConst(0x6F, 1),
        IncAMEM8Bit(0x6B),
        JmpIfAMEM8BitLessThanConst(0x6B, 10, ["command_0x35e9be"]),
        Pause1Frame(),
        SetAMEM8BitToConst(0x6F, 2),
        RemoveItemFromStandardInventory(MysteryEgg),
        AddItemToStandardInventory(LambsLure),
        ClearAMEM8Bit(0x6B),
        Set7E1xToAMEM8Bit(0x7EE012, 0x6B, identifier="command_0x35e9be"),
        ReturnSubroutine(identifier="command_0x35e9c2"),
    ],
)
