# referenced by ally_spells Terrorize

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=229,
    script=[
        Db(bytearray(b" \x80\x10\x00"), identifier="queuestart_0x35ac65"),
        JmpIfAMEM8BitGreaterOrEqualThanConst(0x60, 31, ["command_0x35ac73"]),
        DisplayMessage(BATTLE_MESSAGE, 12),
        PauseScriptUntilDialogueClosed(),
        ClearAMEM16Bit(0x60, identifier="command_0x35ac73"),
        ClearAMEM8Bit(0x6C),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35AC59),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35AC59),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        PlaySound(sound=S0173_TERRORIZE),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35AC59),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        ScreenEffect(SEF0002_TERRORIZE, identifier="queuestart_0x35ac9f"),
        Db(bytearray(b"\xa8\x02\x00")),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        StartTrackingAllyButtonInputs(identifier="queuestart_0x35acad"),
        TimingForRotationCount(
            end_accepting_input=70, start_accepting_input=0, max_presses=16
        ),
        EndTrackingAllyButtonInputs(),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        ClearAMEM16Bit(0x62, identifier="queuestart_0x35acbc"),
        ClearAMEM8Bit(0x6C),
        SetAMEM8BitToConst(0x66, 4),
        ResetTargetMappingMemory(identifier="command_0x35acc4"),
        MuteTimingJmp(["command_0x35ace7"]),
        UnknownJmp26(182, ["command_0x35acdf"]),
        SetAMEMToAMEM16Bit(dest_amem=0xC4, amem=0x60),
        ClearAMEM16Bit(0x60),
        IncAMEM8Bit(0x6C),
        ClearAMEM8Bit(0x6D),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35AC59),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        IncAMEM16Bit(0x62, identifier="command_0x35acdf"),
        JmpIfAMEM16BitNotEqualsConst(0x62, 6, ["command_0x35acc4"]),
        JmpIfAMEM8BitEqualsConst(
            0x6C, 0, ["command_0x35ad10"], identifier="command_0x35ace7"
        ),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=304,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0571_FEAR_EXCLAMATION_POINT,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        SetAMEM8BitToConst(0x6D, 255),
        PauseScriptUntilSpriteSequenceDone(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=6),
        SetAMEM8BitToConst(0x6D, 35),
        RemoveObject(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=6),
        SetAMEM8BitToConst(0x6C, 1, identifier="command_0x35ad10"),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnObjectQueue(),
        ResetTargetMappingMemory(identifier="queuestart_0x35ad19"),
        SetAMEM16BitToOMEMMain(amem=0x60, omem=0x64),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-32,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Pause1Frame(identifier="command_0x35ad2e"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 255, ["command_0x35ad2e"]),
        Db(bytearray(b"\x83\x83")),
        PlaySound(sound=S0107_BUBBLE_POP),
        Pause1Frame(identifier="command_0x35ad3d"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 35, ["command_0x35ad3d"]),
        RemoveObject(),
        ReturnObjectQueue(),
    ],
)
