# pylint: disable=C0301,C0103

"""referenced by ally_spells Geno Whirl"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=300,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35ba9b",
        ),
        Db(bytearray(b" \x8d@\x00")),
        JmpIfAMEM8BitEqualsConst(0x6D, 64, ["command_0x35bab9"]),
        NewSpriteAtCoords(
            sprite_id=SPR0029_GENO_FINGER_SHOT,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            invert_sprite=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        Jmp(["command_0x35bac2"]),
        NewSpriteAtCoords(
            sprite_id=SPR0039_RED_SCARECROW,
            sequence=5,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            param_2_and_0x10=True,
            invert_sprite=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
            identifier="command_0x35bab9",
        ),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=9, identifier="command_0x35bac2"
        ),
        StartTrackingAllyButtonInputs(),
        ClearAMEM16Bit(0x6E),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6E),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35BA91),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35BA91),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6E),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35BA91),
        TimingForOneBinaryButtonPress(
            end_accepting_input=15,
            start_accepting_input=0,
            timed_hit_ends=15,
            destinations=["command_0x35baec"],
        ),
        ScreenFlashWithDuration(BLUE, 1, 16),
        PlaySound(sound=S0078_TIMED_STAT_BOOST, channel=4),
        EndTrackingAllyButtonInputs(identifier="command_0x35baec"),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        PlaySound(sound=S0000_SILENCE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35bb00"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-12,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        PlaySound(sound=S0042_BLADE, channel=4),
        NewSpriteAtCoords(
            sprite_id=SPR0517_BOMB_EXPLOSION,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        SetAMEM8BitToConst(0x6F, 1, identifier="queuestart_0x35bb1f"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION, x=0, y=112, z=0, set_x=True, set_y=True
        ),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION, x=80, y=0, z=0, set_z=True
        ),
        DoMaskEffect(POLYGON_MASK),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6F),
        Pause1Frame(identifier="command_0x35bb39"),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 2, ["command_0x35bb39"]),
        IncAMEM8Bit(0x6E),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6E),
        SetMaskCoords((8, -76), (-112, -76), (112, 112), (-112, 112)),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ScreenFlash(NO_COLOUR, 8),
        SetAMEM16BitToAMEM(amem=0x68, source_amem=0x8A),
        Db(bytearray(b"\xc5")),
        Pause1Frame(identifier="command_0x35bb5f"),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 1, ["command_0x35bb5f"]),
        SetAMEMToAMEM16Bit(dest_amem=0x8A, amem=0x68),
        Db(bytearray(b"\x90")),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35bb76"),
        Db(bytearray(b"!\x9e:\x00")),
        JmpIfAMEM16BitEqualsConst(0x6E, 0, ["command_0x35bb8c"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-20,
            y=-150,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Jmp(["command_0x35bb94"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-20,
            y=-124,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x35bb8c",
        ),
        Pause1Frame(identifier="command_0x35bb94"),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 1, ["command_0x35bb94"]),
        NewEffectObject(effect=EF0032_GENO_WHIRL, looping_off=True),
        IncAMEM8Bit(0x6E),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6E),
        Pause1Frame(identifier="command_0x35bba8"),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 3, ["command_0x35bba8"]),
        Layer3On(prop=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        PlaySound(sound=S0063_GENO_BLAST_IGNITION),
        PauseScriptUntil(condition=SEQ_4BPP_COMPLETE),
        Layer3Off(prop=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
    ],
)
