# pylint: disable=C0301,C0103

"""referenced by monster_spells Shredder"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=130,
    script=[
        ClearAMEM16Bit(0x60, identifier="queuestart_0x35c604"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=54,
            y=160,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35C5FE),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0172_WEAPON_TIMING, channel=4),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=86,
            y=176,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35C5FE),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0172_WEAPON_TIMING, channel=4),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=118,
            y=192,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35C5FE),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35c646",
        ),
        Db(bytearray(b"\x84\x03\x00")),
        Db(bytearray(b"\x8b\x11\x00\x00\x11")),
        DoMaskEffect(CYLINDER_MASK),
        SetMaskCoords((1, 21), (-113, 13), (33, 56), (42, 0)),
        PlaySound(sound=S0063_GENO_BLAST_IGNITION),
        SetAMEM16BitToAMEM(amem=0x60, source_amem=0x96),
        Db(bytearray(b"\x9b\x02\x00\x06\x04")),
        Db(bytearray(b"\x9b\x03\x00\n\x04")),
        SetAMEMToAMEM16Bit(dest_amem=0x8A, amem=0x68),
        Db(bytearray(b"\x90")),
        DisableSpritesOnSubscreen(),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        Db(bytearray(b"\x84\x03\x00")),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
    ],
)
