# pylint: disable=C0301,C0103

"""referenced by monster_attacks 122, monster_spells BreakerBeam"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=161,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-8,
            y=-4,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3558b0",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0546_BOMBS_AWAY_ELECTRIC_BALL,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        RunSubroutine(["command_0x357f5e"]),
        PlaySound(sound=S0095_BOWSERS_CRUSHER),
        Jmp(["command_0x35252f"]),
        RunSubroutine(["command_0x353437"], identifier="queuestart_0x3558c9"),
        Db(bytearray(b"\x84\x03\x00")),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SetAMEM16BitToConst(0x60, 28),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x353706),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x353706),
        RunSubroutine(["command_0x3533f5"]),
        Db(bytearray(b"\x84\x03\x00")),
        Jmp(["command_0x35253b"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3558ec",
        ),
        RunSubroutine(["command_0x3533df"]),
        NewEffectObject(effect=EF0101_SAND_STORM_FG__4BPP_, playback_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-1025,
            end_position=-1025,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=512,
            end_position=512,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        FadeInEffect(duration=2),
        ScreenFlash(RED, 8),
        Layer3On(prop=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        RunSubroutine(["command_0x35337d"]),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=90),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(prop=OVERLAP_ALL_EXCEPT_ALLIES, bpp4=True),
        Db(bytearray(b"\x90")),
        RunSubroutine(["command_0x35338b"]),
        Pause2Frames(),
        ResetObjectMappingMemory(),
        ClearEffectIndex(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=64,
            y=120,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35592f",
        ),
        DoMaskEffect(POLYGON_MASK),
        RunSubroutine(["command_0x35336f"]),
        RunSubroutine(["command_0x3533ea"]),
        PlaySound(sound=S0026_FLAME_WALL),
        SetMaskCoords((8, 127), (-40, -64), (112, -64), (16, 64)),
        RunSubroutine(["command_0x3533f5"]),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        ReturnObjectQueue(),
    ],
)
