# referenced by monster_attacks Thornet

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=141,
    script=[
        ResetTargetMappingMemory(identifier="command_0x357ae5"),
        ResetObjectMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"D@")),
        PlaySound(sound=S0134_BOO_DISAPPEARS),
        ClearAMEM8Bit(0x6F),
        SetAMEM16BitToConst(0x60, 12),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x355F1D),
        VisibilityOff(),
        Db(bytearray(b"Z")),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X00, speed=512, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ClearAMEM8Bit(0x6F),
        SetAMEM16BitToConst(0x60, 12),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x355F1D),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0135_BOO_APPEARS),
        VisibilityOn(),
        Db(bytearray(b"Y")),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        PlaySound(sound=S0136_BOO_APPROACHES),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=0,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-65,
            end_position=0,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        MoveObject(
            speed=1,
            start_position=-193,
            end_position=0,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=192,
            end_position=0,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=0,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-65,
            end_position=0,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        MoveObject(
            speed=1,
            start_position=-193,
            end_position=0,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=192,
            end_position=0,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
    ],
)
