# referenced by weapons RibbitStick

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(expected_size = 263, script = [
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="queuestart_0x35f825"),
	NewSpriteAtCoords(sprite_id=SPR0032_FROGGIE_STICK, sequence=0, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=1),
	ClearAMEM16Bit(0x60),
	ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35F817),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=1),
	ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35F817),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=18),
	PlaySound(sound=S0112_SWING),
	PauseScriptUntilSpriteSequenceDone(),
	Pause1Frame(identifier="command_0x35f84f"),
	SetAMEM8BitToOMEMMain(amem=0x63, omem=0x63),
	JmpIfAMEM8BitNotEqualsConst(0x63, 1, ["command_0x35f84f"]),
	Set7E1xToAMEM8Bit(0x7EE020, 0x63),
	RemoveObject(),
	SetOMEMMainToAMEM8Bit(omem=0x64, amem=0x63),
	ReturnObjectQueue(),
	PlaySound(sound=S0018_SUPER_JUMP_HIT_1, identifier="queuestart_0x35f864"),
	ClearAMEM16Bit(0x60),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	Pause1Frame(identifier="command_0x35f870"),
	SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
	JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35f870"]),
	NewSpriteAtCoords(sprite_id=SPR0032_FROGGIE_STICK, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=1),
	ClearAMEM8Bit(0x6E),
	ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35F817),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=1),
	ClearAMEM8Bit(0x6F),
	ObjectQueueAtOffsetAndIndex(index=10, target_address=0x35F817),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	PlaySound(sound=S0112_SWING),
	PauseScriptUntilSpriteSequenceDone(),
	PlaySound(sound=S0058_SUPER_JUMP_HIT_2),
	PauseScriptUntilAMEMBitsSet(0x6E, [0]),
	PauseScriptUntilAMEMBitsSet(0x6F, [0]),
	SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
	Pause1Frame(identifier="command_0x35f8ab"),
	SetAMEM8BitToOMEMMain(amem=0x65, omem=0x65),
	JmpIfAMEM8BitNotEqualsConst(0x65, 1, ["command_0x35f8ab"]),
	RemoveObject(),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="queuestart_0x35f8b8"),
	NewSpriteAtCoords(sprite_id=SPR0032_FROGGIE_STICK, sequence=0, priority=3, vram_address=0x6200, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	Pause1Frame(identifier="command_0x35f8c9"),
	SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
	JmpIfAMEM8BitNotEqualsConst(0x6E, 1, ["command_0x35f8c9"]),
	RemoveObject(),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="queuestart_0x35f8d6"),
	NewSpriteAtCoords(sprite_id=SPR0032_FROGGIE_STICK, sequence=0, priority=3, vram_address=0x6400, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	Pause1Frame(identifier="command_0x35f8e7"),
	SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
	JmpIfAMEM8BitNotEqualsConst(0x6E, 1, ["command_0x35f8e7"]),
	RemoveObject(),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="queuestart_0x35f8f4"),
	NewSpriteAtCoords(sprite_id=SPR0032_FROGGIE_STICK, sequence=1, priority=3, vram_address=0x6400, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	RemoveObject(),
	SetAMEM8BitToConst(0x6E, 1),
	SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True, identifier="queuestart_0x35f910"),
	NewSpriteAtCoords(sprite_id=SPR0032_FROGGIE_STICK, sequence=1, priority=3, vram_address=0x6200, palette_row=8, overwrite_vram=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	PauseScriptUntilSpriteSequenceDone(),
	RemoveObject(),
	SetAMEM8BitToConst(0x6F, 1),
	SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
	ReturnObjectQueue()
])
