# pylint: disable=C0301,C0103

"""referenced by battle_events BE0045_ZOMBONE_DIES, battle_events BE0055_SHY_AWAY_WATERS_SMILAX_PART_1, battle_events BE0056_SHY_AWAY_WATERS_SMILAX_PART_2, battle_events BE0044_CZAR_DRAGON_DIES, battle_events BE0057_SHY_AWAY_WATERS_SMILAX_PART_3, battle_events BE0058_THRAX_IS_THERE"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=316,
    script=[
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=176,
            y=120,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a9d7b"),
        ClearAMEM8Bit(0x60),
        ClearAMEM8Bit(0x69),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 2),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x3A87CA),
        RunSubroutine(["command_0x3a8674"]),
        RunSubroutine(["command_0x3a7729"]),
        ReturnObjectQueue(),
        DisplayMessage(BATTLE_DIALOGUE, 162, identifier="queuestart_0x3a9d98"),
        PauseScriptUntilDialogClosed(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=240,
            y=120,
            z=-48,
            set_x=True,
            set_y=True,
            set_z=True),
        NewSpriteAtCoords(
            sprite_id=SPR0399_SHY_AWAY,
            sequence=6,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        Db(bytearray(b"X")),
        Db(bytearray(b"Y")),
        SetAMEM8BitTo7E1x(0x68, 0x7EE00D),
        JmpIfAMEM8BitEqualsConst(0x68, 0, ["command_0x3a9dc5"]),
        JmpIfAMEM8BitEqualsConst(0x68, 1, ["command_0x3a9de2"]),
        JmpIfAMEM8BitEqualsConst(0x68, 3, ["command_0x3a9dff"]),
        DisplayMessage(BATTLE_DIALOGUE, 165, identifier="command_0x3a9dc5"),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-193,
            end_position=-193,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=96,
            end_position=96,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=40),
        ResetObjectMappingMemory(),
        PauseScriptUntilDialogClosed(),
        Jmp(["command_0x3a9e19"]),
        DisplayMessage(BATTLE_DIALOGUE, 166, identifier="command_0x3a9de2"),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-193,
            end_position=-193,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=96,
            end_position=96,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=40),
        ResetObjectMappingMemory(),
        PauseScriptUntilDialogClosed(),
        Jmp(["command_0x3a9e19"]),
        DisplayMessage(BATTLE_DIALOGUE, 167, identifier="command_0x3a9dff"),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-193,
            end_position=-193,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=96,
            end_position=96,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        PauseScriptUntilDialogClosed(),
        DisplayMessage(BATTLE_DIALOGUE, 164, identifier="command_0x3a9e19"),
        SpriteSequence(sequence=5, looping_on=True),
        RunSubroutine(["command_0x3a7596"]),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a7734"]),
        SpriteSequence(sequence=6, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        SpriteSequence(sequence=6, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        DisplayMessage(BATTLE_DIALOGUE, 163),
        MoveObject(
            speed=1,
            start_position=192,
            end_position=192,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=-97,
            end_position=-97,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        ClearAMEM8Bit(0x60),
        SetAMEMToAMEM8Bit(dest_amem=0xA7, amem=0x60),
        RemoveObject(),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a7588"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=191,
            y=128,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a9e5b"),
        NewSpriteAtCoords(
            sprite_id=SPR0459_THRAX,
            sequence=0,
            priority=2,
            vram_address=0x7800,
            palette_row=14,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        RunSubroutine(["command_0x3a755e"]),
        Jmp(["thrax_skip_1"], identifier="command_0x3a9e6f"),
        Pause1Frame(),
        SetAMEM8BitTo7E1x(0x67, 0x7EE00D, identifier="thrax_skip_1"),
        JmpIfAMEMBitsClear(0x67, [0], ["command_0x3a9e6f"]),
        SpriteSequence(sequence=3),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=1, looping_off=True),
        RunSubroutine(["command_0x3a757a"]),
        Jmp(["thrax_skip_2"], identifier="command_0x3a9e84"),
        Pause1Frame(),
        SetAMEM8BitTo7E1x(0x67, 0x7EE00D, identifier="thrax_skip_2"),
        JmpIfAMEMBitsClear(0x67, [1], ["command_0x3a9e84"]),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2, looping_off=True),
        RunSubroutine(["command_0x3a757a"]),
        Jmp(["thrax_skip_3"], identifier="command_0x3a9e99"),
        Pause1Frame(),
        SetAMEM8BitTo7E1x(0x67, 0x7EE00E, identifier="thrax_skip_3"),
        JmpIfAMEM8BitNotEqualsConst(0x67, 9, ["command_0x3a9e99"]),
        EnableSpritesOnSubscreen(),
        Db(bytearray(b"\x84\x00\x08")),
        Db(bytearray(b"\x9e\x00\x00")),
        FadeOutSprite(duration=2),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        DisableSpritesOnSubscreen(),
        RemoveObject(),
        ReturnObjectQueue(),
    ])
