# pylint: disable=C0301,C0103

"""referenced by monster_attacks LullaBye, monster_attacks PhysicalAttack105, monster_spells LightBeam"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=518,
    script=[
        RunSubroutine(["command_0x353437"], identifier="queuestart_0x35375e"),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"\x84\x01\x08")),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-8,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ClearAMEM8Bit(0x65),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 0),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x353706),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x353706),
        RunSubroutine(["command_0x352552"]),
        RunSubroutine(["command_0x352582"]),
        Db(bytearray(b"\x9d\x02")),
        Layer3Off(prop=OVERLAP_ALL_EXCEPT_ALLIES, bpp4=True),
        Db(bytearray(b"\x90")),
        RunSubroutine(["command_0x352594"]),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"\x84\x81\x00")),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-16,
            y=0,
            z=-8,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x353792",
        ),
        EnableSpritesOnSubscreen(),
        NewSpriteAtCoords(
            sprite_id=SPR0793_BIG_PINK_HEART,
            sequence=0,
            priority=0,
            vram_address=0x6200,
            palette_row=8,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=0,
            apply_to_x=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=0,
            apply_to_y=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=17,
            start_position=-129,
            end_position=128,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        MoveObject(
            speed=17,
            start_position=128,
            end_position=-129,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        MoveObject(
            speed=17,
            start_position=-129,
            end_position=128,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        MoveObject(
            speed=17,
            start_position=-129,
            end_position=128,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        ResetObjectMappingMemory(),
        SpriteSequence(sequence=1),
        PauseScriptUntilSpriteSequenceDone(),
        DisableSpritesOnSubscreen(),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3537ec",
        ),
        RunSubroutine(["command_0x3533df"]),
        NewEffectObject(effect=EF0092_LIGHT_BEAM, playback_off=True),
        Db(bytearray(b"\x9c\x00B\x10\x00\x08\x00 \x00")),
        ScreenFlash(RED, 8),
        Layer3On(prop=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        RunSubroutine(["command_0x353399"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        RunSubroutine(["command_0x352546"]),
        ResetObjectMappingMemory(),
        Pause2Frames(),
        ClearEffectIndex(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x353822",
        ),
        DoMaskEffect(CIRCLE_MASK),
        RunSubroutine(["command_0x35336f"]),
        RunSubroutine(["command_0x353400"]),
        SetAMEM8BitToConst(0x6A, 0),
        SetAMEM8BitToConst(0x6B, 20),
        SetAMEM8BitToConst(0x6C, 4),
        RunSubroutine(["command_0x353297"]),
        RunSubroutine(["command_0x357ff8"]),
        PlaySound(sound=S0107_BUBBLE_POP),
        SetAMEM8BitToConst(0x6A, 20),
        SetAMEM8BitToConst(0x6B, 25),
        SetAMEM8BitToConst(0x6C, 4),
        RunSubroutine(["command_0x353297"]),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 0),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x353706),
        RunSubroutine(["command_0x352552"]),
        RunSubroutine(["command_0x352589"]),
        RunSubroutine(["command_0x352576"]),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35386b",
        ),
        DoMaskEffect(CIRCLE_MASK, 128),
        SetAMEM8BitToConst(0x6A, 0),
        SetAMEM8BitToConst(0x6B, 25),
        SetAMEM8BitToConst(0x6C, 4),
        RunSubroutine(["command_0x353297"]),
        RunSubroutine(["command_0x352589"]),
        RunSubroutine(["command_0x352576"]),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x353437"], identifier="queuestart_0x35388d"),
        Db(bytearray(b"\x84\x03\x00")),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=128,
            y=256,
            z=-128,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ClearAMEM8Bit(0x65),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 0),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x353706),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x353706),
        RunSubroutine(["command_0x352552"]),
        RunSubroutine(["command_0x352582"]),
        Db(bytearray(b"\x9d\x02")),
        Layer3Off(prop=OVERLAP_ALL_EXCEPT_ALLIES, bpp4=True),
        Db(bytearray(b"\x90")),
        RunSubroutine(["command_0x352594"]),
        Db(bytearray(b"\x84\x03\x00")),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3538bf",
        ),
        NewEffectObject(effect=EF0092_LIGHT_BEAM, playback_off=True),
        RunSubroutine(["command_0x35336f"]),
        ScreenFlash(RED, 8),
        Layer3On(prop=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        RunSubroutine(["command_0x353399"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        RunSubroutine(["command_0x352546"]),
        ResetObjectMappingMemory(),
        Pause2Frames(),
        ClearEffectIndex(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3538ec",
        ),
        RunSubroutine(["command_0x3533df"]),
        SetMaskCoords((7, 0), (32, 0), (2, 0), (0, 1)),
        Db(bytearray(b"F")),
        RunSubroutine(["command_0x353400"]),
        SetAMEM8BitToConst(0x6A, 0),
        SetAMEM8BitToConst(0x6B, 60),
        SetAMEM8BitToConst(0x6C, 1),
        RunSubroutine(["command_0x353297"]),
        RunSubroutine(["command_0x35803b"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SetAMEM8BitToConst(0x6A, 60),
        SetAMEM8BitToConst(0x6B, 80),
        SetAMEM8BitToConst(0x6C, 1),
        RunSubroutine(["command_0x353297"]),
        PlaySound(sound=S0107_BUBBLE_POP),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 0),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x353706),
        RunSubroutine(["command_0x352552"]),
        RunSubroutine(["command_0x352589"]),
        RunSubroutine(["command_0x352576"]),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x353942",
        ),
        DoMaskEffect(CIRCLE_MASK, 128),
        SetAMEM8BitToConst(0x6A, 0),
        SetAMEM8BitToConst(0x6B, 80),
        SetAMEM8BitToConst(0x6C, 8),
        RunSubroutine(["command_0x353297"]),
        RunSubroutine(["command_0x352589"]),
        RunSubroutine(["command_0x352576"]),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        ReturnObjectQueue(),
    ],
)
