# referenced by monster_attacks GunkBall, monster_spells Electroshock, monster_attacks PhysicalAttack91, monster_attacks Blazer

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=309,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x356271",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0532_BLUE_SPARK,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ClearAMEM8Bit(0x69),
        ClearAMEM8Bit(0x64),
        SetAMEM16BitToConst(0x60, 0),
        ObjectQueueAtOffsetAndIndex(
            index=0, target_address=0x356B15, identifier="command_0x35628a"
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        IncAMEM8Bit(0x64),
        JmpIfAMEM8BitNotEqualsConst(0x64, 6, ["command_0x35628a"]),
        Pause1Frame(identifier="command_0x35629a"),
        JmpIfAMEM8BitNotEqualsConst(0x69, 6, ["command_0x35629a"]),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=248,
            z=8,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3562a3",
        ),
        EnableSpritesOnSubscreen(),
        NewSpriteAtCoords(
            sprite_id=SPR0533_YELLOW_SPARK,
            sequence=0,
            priority=0,
            vram_address=0x6200,
            palette_row=8,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        FadeInSprite(duration=2),
        VisibilityOn(),
        ClearAMEM8Bit(0x68),
        ClearAMEM8Bit(0x69),
        ClearAMEM8Bit(0x64),
        SetAMEM16BitToConst(0x60, 0),
        ObjectQueueAtOffsetAndIndex(
            index=20, target_address=0x356B15, identifier="command_0x3562c4"
        ),
        ObjectQueueAtOffsetAndIndex(index=22, target_address=0x356B15),
        Pause1Frame(),
        IncAMEM8Bit(0x64),
        JmpIfAMEM8BitNotEqualsConst(0x64, 10, ["command_0x3562c4"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=55),
        FadeOutSprite(duration=2),
        VisibilityOff(),
        Pause1Frame(identifier="command_0x3562de"),
        JmpIfAMEM8BitNotEqualsConst(0x69, 20, ["command_0x3562de"]),
        DisableSpritesOnSubscreen(),
        Jmp(["command_0x356b01"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-6,
            y=254,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3562e9",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0532_BLUE_SPARK,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ClearAMEM8Bit(0x68),
        ClearAMEM8Bit(0x64),
        ClearAMEM8Bit(0x69),
        SetAMEM16BitToConst(0x60, 0),
        ObjectQueueAtOffsetAndIndex(
            index=2, target_address=0x356B15, identifier="command_0x356304"
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        IncAMEM8Bit(0x64),
        JmpIfAMEM8BitNotEqualsConst(0x64, 24, ["command_0x356304"]),
        Pause1Frame(identifier="command_0x356314"),
        JmpIfAMEM8BitNotEqualsConst(0x69, 24, ["command_0x356314"]),
        Jmp(["command_0x356b01"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=4,
            y=160,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35631e",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0532_BLUE_SPARK,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ClearAMEM8Bit(0x68),
        ClearAMEM8Bit(0x69),
        ClearAMEM8Bit(0x64),
        SetAMEM16BitToConst(0x60, 0),
        ObjectQueueAtOffsetAndIndex(
            index=14, target_address=0x356B15, identifier="command_0x356339"
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        IncAMEM8Bit(0x64),
        JmpIfAMEM8BitNotEqualsConst(0x64, 6, ["command_0x356339"]),
        Pause1Frame(identifier="command_0x356349"),
        JmpIfAMEM8BitNotEqualsConst(0x69, 6, ["command_0x356349"]),
        Jmp(["command_0x356b01"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=253,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x356353",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0527_YELLOW_MIST_STEAM_FORMS_INTO_SMALL_STAR,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ClearAMEM8Bit(0x69),
        SetAMEM16BitToConst(0x60, 11),
        PlaySound(sound=S0148_SMITHY_BULLET_FINGERS),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=7),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=7),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x356B15),
        PlaySound(sound=S0148_SMITHY_BULLET_FINGERS),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=7),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=7),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=7),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x356B15),
        Pause1Frame(identifier="command_0x35639a"),
        JmpIfAMEM8BitNotEqualsConst(0x69, 6, ["command_0x35639a"]),
        RunSubroutine(["command_0x35337d"]),
        RemoveObject(),
        ReturnObjectQueue(),
    ],
)
