# referenced by items MukuCookie

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=711,
    script=[
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=120,
            y=132,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35dd01",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0433_MUKUMUKU,
            sequence=8,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=36),
        PlaySound(sound=S0206_MONSTER_SWING),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        PlaySound(sound=S0206_MONSTER_SWING),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=28),
        PlaySound(sound=S0206_MONSTER_SWING),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        PlaySound(sound=S0206_MONSTER_SWING),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        PlaySound(sound=S0206_MONSTER_SWING),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        PlaySound(sound=S0206_MONSTER_SWING),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=3),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        PlaySound(sound=S0150_ENEMY_TAUNTS_THEN_HITS),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SpriteSequence(sequence=10),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=10),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=3),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        PlaySound(sound=S0150_ENEMY_TAUNTS_THEN_HITS),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SpriteSequence(sequence=10),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        SpriteSequence(sequence=4),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=65),
        ClearAMEM16Bit(0x60),
        ClearAMEM16Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35DCD5),
        PlaySound(sound=S0112_SWING),
        PauseScriptUntilSpriteSequenceDone(),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=12),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x35DCD5),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=12),
        PauseScriptUntilSpriteSequenceDone(),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        DisplayMessage(BATTLE_MESSAGE, 42),
        SpriteSequence(sequence=13),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35DCD5),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=13),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=13),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=13),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=13),
        PauseScriptUntilSpriteSequenceDone(),
        PauseScriptUntilDialogClosed(),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SpriteSequence(sequence=6),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        ClearAMEM8Bit(0x6C, identifier="queuestart_0x35ddb5"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=16,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0777_STAR_EGG_LITTLE_BROWN_BIRD,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        SpriteSequence(sequence=0, looping_on=True, identifier="command_0x35ddc8"),
        PlaySound(sound=S0005_BIRDIE_TWEET),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=8,
            y=-20,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        PlaySound(sound=S0005_BIRDIE_TWEET),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-24,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        PlaySound(sound=S0005_BIRDIE_TWEET),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-8,
            y=-20,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        PlaySound(sound=S0005_BIRDIE_TWEET),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-16,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        SpriteSequence(sequence=1, looping_on=True),
        PlaySound(sound=S0005_BIRDIE_TWEET),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-8,
            y=-12,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        PlaySound(sound=S0005_BIRDIE_TWEET),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        PlaySound(sound=S0005_BIRDIE_TWEET),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=8,
            y=-12,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        PlaySound(sound=S0005_BIRDIE_TWEET),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=16,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        IncAMEM8Bit(0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 2, ["command_0x35ddc8"]),
        RemoveObject(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-3,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35de86",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0785_SPRITZ_BOMB,
            sequence=1,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        MoveObject(
            speed=65,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0517_BOMB_EXPLOSION,
            sequence=0,
            store_to_vram=True,
            store_palette=True,
        ),
        PlaySound(sound=S0012_BOMB_EXPLOSION),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35deb8",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0528_VERY_SMALL_BLACK_DOT,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ShineEffect(
            colour_count=6, starting_colour_index=1, glow_duration=1, east=True
        ),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35DCD5),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x35DCD5),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35DCD5),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35DCD5),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=13),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35DCD5),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35DCD5),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=13),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35DCD5),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35DCD5),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=13),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35DCD5),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35DCD5),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        RemoveObject(),
        Db(bytearray(b"\x81")),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-262,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35df28",
        ),
        Db(bytearray(b"\x83\xc3")),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-244,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=1,
            start_position=96,
            end_position=96,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-262,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35df4a",
        ),
        Db(bytearray(b"\x83\xc3")),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=54),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-244,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=1,
            start_position=96,
            end_position=96,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-9,
            y=-263,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35df78",
        ),
        Db(bytearray(b"\x83\xc3")),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-9,
            y=-245,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=1,
            start_position=96,
            end_position=96,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-9,
            y=-263,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35df9a",
        ),
        Db(bytearray(b"\x83\xc3")),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=54),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-9,
            y=-245,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=1,
            start_position=96,
            end_position=96,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
    ],
)
