# referenced by monster_attacks PhysicalAttack51, monster_attacks ScrowDust

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=208,
    script=[
        RunSubroutine(["command_0x353437"], identifier="queuestart_0x354a24"),
        Db(bytearray(b"\x84\x03\x00")),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-16,
            y=-6,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 12),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x353706),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x353706),
        PlaySound(sound=S0101_STENCH),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=150),
        RunSubroutine(["command_0x35338b"]),
        RunSubroutine(["command_0x353400"]),
        Db(bytearray(b"\x84\x03\x00")),
        Jmp(["command_0x35252f"]),
        RunSubroutine(["command_0x353437"], identifier="queuestart_0x354a52"),
        Db(bytearray(b"\x84\x03\x00")),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-16,
            y=-6,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 12),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x353706),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x353706),
        PlaySound(sound=S0101_STENCH),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=150),
        RunSubroutine(["command_0x35338b"]),
        RunSubroutine(["command_0x353400"]),
        Db(bytearray(b"\x84\x03\x00")),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x354a80",
        ),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-513,
            end_position=-513,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        RunSubroutine(["command_0x3533df"]),
        NewEffectObject(effect=EF0052_SNOW_CONFETTI__GREEN, playback_off=True),
        RunSubroutine(["command_0x35337d"]),
        ScreenFlash(RED, 8),
        Layer3On(property=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        RunSubroutine(["command_0x35340b"]),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        Layer3Off(property=OVERLAP_ALL_EXCEPT_ALLIES, bpp4=True),
        RunSubroutine(["command_0x3533b5"]),
        ResetObjectMappingMemory(),
        Pause2Frames(),
        ClearEffectIndex(),
        RunSubroutine(["command_0x353399"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x354aba",
        ),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-513,
            end_position=-513,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        RunSubroutine(["command_0x3533df"]),
        NewEffectObject(effect=EF0047_METEOR_SHOWER__SNOW_CONFETTI_, playback_off=True),
        RunSubroutine(["command_0x35337d"]),
        ScreenFlash(RED, 8),
        Layer3On(property=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        RunSubroutine(["command_0x35340b"]),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        Layer3Off(property=OVERLAP_ALL_EXCEPT_ALLIES, bpp4=True),
        RunSubroutine(["command_0x3533b5"]),
        ResetObjectMappingMemory(),
        Pause2Frames(),
        ClearEffectIndex(),
        RunSubroutine(["command_0x353399"]),
        ReturnObjectQueue(),
    ],
)
