# pylint: disable=C0301,C0103

"""referenced by battle_events BE0054_CLOAKER_TEAMS_UP_WITH_EARTHLINK, battle_events BE0027_BEAT_TENTACLES_MOVE_ON_TO_NEXT, battle_events BE0053_DOMINO_TEAMS_UP_WITH_MAD_ADDER"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=138,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=0,
            y=-136,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a97d2"),
        SetAMEM16BitToConst(0x60, 33023),
        SetAMEMToAMEM16Bit(dest_amem=0x8C, amem=0x60),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=72,
            end_position=72,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=150),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a756c"]),
        Pause1Frame(identifier="command_0x3a97fb"),
        Pause1Frame(),
        Pause1Frame(),
        Pause1Frame(),
        SetAMEM8BitTo7E1x(0x68, 0x7EE007),
        JmpIfAMEM8BitEqualsConst(0x68, 0, ["command_0x3a97fb"]),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=72,
            end_position=72,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=350),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a756c"]),
        ClearEffectIndex(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=0,
            y=-136,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a9823"),
        SetAMEM16BitToConst(0x60, 33023),
        SetAMEMToAMEM16Bit(dest_amem=0x8C, amem=0x60),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=68,
            end_position=68,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=150),
        RunSubroutine(["command_0x3a7596"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50),
        RunSubroutine(["command_0x3a7588"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=250),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a756c"]),
        ClearEffectIndex(),
        ReturnObjectQueue(),
    ])
