# pylint: disable=C0301,C0103

"""referenced by monster_spells MegaRecover, monster_spells Recover, monster_spells WeirdMushroom"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=92,
    script=[
        RunSubroutine(["command_0x3526b6"], identifier="queuestart_0x35555a"),
        NewSpriteAtCoords(
            sprite_id=SPR0779_WHITE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x3526b6"], identifier="queuestart_0x355569"),
        NewSpriteAtCoords(
            sprite_id=SPR0779_WHITE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x3526b6"], identifier="queuestart_0x355578"),
        NewSpriteAtCoords(
            sprite_id=SPR0779_WHITE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x35252f"]),
        RunSubroutine(["command_0x3526b6"], identifier="queuestart_0x355588"),
        NewSpriteAtCoords(
            sprite_id=SPR0523_YELLOW_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x3526b6"], identifier="queuestart_0x355597"),
        NewSpriteAtCoords(
            sprite_id=SPR0523_YELLOW_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x3526b6"], identifier="queuestart_0x3555a6"),
        NewSpriteAtCoords(
            sprite_id=SPR0523_YELLOW_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x35252f"]),
    ])
