# pylint: disable=C0301,C0103

"""referenced by monster_attacks PhysicalAttack40, monster_attacks IronMaiden"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=232,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=248,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x356831"),
        NewSpriteAtCoords(
            sprite_id=SPR0809_BLUE_MUSIC_NOTE,
            sequence=0,
            priority=0,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        ShineEffect(
            colour_count=8, starting_colour_index=1, glow_duration=1, east=True
        ),
        ClearAMEM8Bit(0x68),
        ClearAMEM8Bit(0x69),
        SetAMEM16BitToConst(0x60, 6),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x356B15),
        SpriteSequence(sequence=1),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        SpriteSequence(sequence=2),
        Pause1Frame(identifier="command_0x35688e"),
        JmpIfAMEM8BitNotEqualsConst(0x69, 12, ["command_0x35688e"]),
        Db(bytearray(b"\x81")),
        Jmp(["command_0x356b01"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=248,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x356899"),
        EnableSpritesOnSubscreen(),
        NewSpriteAtCoords(
            sprite_id=SPR0809_BLUE_MUSIC_NOTE,
            sequence=0,
            priority=0,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        ShineEffect(
            colour_count=8, starting_colour_index=1, glow_duration=1, east=True
        ),
        ClearAMEM8Bit(0x68),
        ClearAMEM8Bit(0x69),
        SetAMEM16BitToConst(0x60, 6),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=18, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=20, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=22, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        ObjectQueueAtOffsetAndIndex(index=24, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=26, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=28, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=30, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=18, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=20, target_address=0x356B15),
        ObjectQueueAtOffsetAndIndex(index=22, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        SpriteSequence(sequence=1),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        SpriteSequence(sequence=2),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        SpriteSequence(sequence=0),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        SpriteSequence(sequence=1),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        SpriteSequence(sequence=2),
        Pause1Frame(identifier="command_0x35690d"),
        JmpIfAMEM8BitNotEqualsConst(0x69, 12, ["command_0x35690d"]),
        DisableSpritesOnSubscreen(),
        Db(bytearray(b"\x81")),
        Jmp(["command_0x356b01"]),
    ])
