# pylint: disable=C0301,C0103

"""referenced by behaviour_33_0x350C5B, behaviour_34_0x350C9E, behaviour_51_0x350F56, behaviour_24_0x350A9C, behaviour_8_0x3507A2, behaviour_41_0x350DAF, behaviour_16_0x350928, behaviour_32_0x350C14, behaviour_52_0x350F6B, weapons FingerShot, behaviour_23_0x350A55, behaviour_9_0x3507E9, behaviour_42_0x350DED, behaviour_43_0x350E38"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=225,
    script=[
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=30, identifier="queuestart_0x35f9b4"
        ),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=20,
            y=236,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        NewSpriteAtCoords(
            sprite_id=SPR0527_YELLOW_MIST_STEAM_FORMS_INTO_SMALL_STAR,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        PlaySound(sound=S0052_FINGER_SHOT_BULLETS),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35F9A2),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=22,
            y=237,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35F9A2),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=24,
            y=238,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35F9A2),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=26,
            y=239,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35F9A2),
        Pause1Frame(identifier="command_0x35fa05"),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 4, ["command_0x35fa05"]),
        RemoveObject(),
        SetAMEM8BitToConst(0x66, 1),
        SetOMEMMainToAMEM8Bit(omem=0x66, amem=0x66),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35fa16"),
        Db(bytearray(b"\x83\x83")),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
        PauseScriptUntil(condition=0x07),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"!\x9c:\x00")),
        JmpIfAMEM16BitNotEqualsConst(0x6C, 0, ["command_0x35fa51"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-18,
            y=-5,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=48),
        Jmp(["command_0x35fa5f"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-18,
            y=24,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x35fa51"),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=160, arch_height=24),
        PauseScriptUntil(
            condition=SPRITE_SHIFT_COMPLETE, identifier="command_0x35fa5f"
        ),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        JmpIfAMEM16BitNotEqualsConst(0x6C, 0, ["command_0x35fa77"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-24,
            y=-6,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        Jmp(["command_0x35fa7f"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-24,
            y=25,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x35fa77"),
        MoveSpriteToCoords(
            shift_type=SHIFT_TYPE_TRANSFER,
            speed=128,
            arch_height=128,
            identifier="command_0x35fa7f"),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6F),
        IncAMEM8Bit(0x6F),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
    ])
