# referenced by ally_spells Geno Boost

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=223,
    script=[
        StartTrackingAllyButtonInputs(identifier="queuestart_0x35b9b2"),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6C),
        ClearAMEM8Bit(0x6D),
        ClearAMEM8Bit(0x6E),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35B9A8),
        PlaySound(sound=S0077_STAT_BOOST_MULTI),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35B9A8),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35B9A8),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        TimingForOneBinaryButtonPress(
            end_accepting_input=30,
            start_accepting_input=0,
            timed_hit_ends=30,
            destinations=["command_0x35ba15"],
        ),
        PlaySound(sound=S0078_TIMED_STAT_BOOST),
        ScreenFlashWithDuration(WHITE, 1, 16),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=4,
            y=-38,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        InitializeBonusMessageSequence(),
        PlaySound(sound=S0006_BONUS_FLOWER_STATUS_UP, channel=4),
        DisplayBonusMessage(message=BM_ATTACK, x=0, y=-2),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        DisplayBonusMessage(message=BM_ATTACK, x=2, y=0),
        PauseScriptUntilBonusMessageComplete(),
        InitializeBonusMessageSequence(),
        PlaySound(sound=S0006_BONUS_FLOWER_STATUS_UP),
        DisplayBonusMessage(message=BM_ATTACK, x=1, y=0),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        DisplayBonusMessage(message=BM_ATTACK, x=2, y=0),
        PauseScriptUntilBonusMessageComplete(),
        Jmp(["command_0x35ba30"]),
        SetAMEM60ToCurrentTarget(identifier="command_0x35ba15"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=4,
            y=-38,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        InitializeBonusMessageSequence(),
        PlaySound(sound=S0006_BONUS_FLOWER_STATUS_UP),
        DisplayBonusMessage(message=BM_ATTACK, x=0, y=-2),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        DisplayBonusMessage(message=BM_ATTACK, x=2, y=0),
        PauseScriptUntilBonusMessageComplete(),
        EndTrackingAllyButtonInputs(identifier="command_0x35ba30"),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35ba3a"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-8,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0530_STAT_BOOST_ARROWS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6C, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35ba57"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=8,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0530_STAT_BOOST_ARROWS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35ba74"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-24,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0530_STAT_BOOST_ARROWS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
    ],
)
