# pylint: disable=C0301,C0103

"""referenced by battle_events BE0093_BEAM_OF_LIGHT_FORMS_AROUND_SMITHY_HEAD_BEFORE_BODY_APPEARS, battle_events BE0086_SMELTER_POURS_MOLTEN_LIQUID_SMITHY_WELDS"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=200,
    script=[
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3aa17b"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=144,
            y=144,
            z=-64,
            set_x=True,
            set_y=True,
            set_z=True),
        NewEffectObject(effect=EF0112_SMELTER__S_MOLTEN_METAL, looping_off=True),
        Layer3On(prop=OVERLAP_ALL, bpp4=True),
        RunSubroutine(["command_0x3a757a"]),
        RunSubroutine(["command_0x3a773f"]),
        RunSubroutine(["command_0x3a7760"]),
        Layer3Off(prop=OVERLAP_ALL, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        FadeInScreen(duration=1),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x3a773f"], identifier="queuestart_0x3aa19f"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=148,
            y=157,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        NewSpriteAtCoords(
            sprite_id=SPR0775_WHITE_GAS_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        PauseScriptUntilSpriteSequenceDone(),
        VisibilityOff(),
        RunSubroutine(["command_0x3a774a"]),
        VisibilityOn(),
        SpriteSequence(sequence=0),
        PauseScriptUntilSpriteSequenceDone(),
        VisibilityOff(),
        RunSubroutine(["command_0x3a7755"]),
        VisibilityOn(),
        SpriteSequence(sequence=0),
        PauseScriptUntilSpriteSequenceDone(),
        RunSubroutine(["command_0x3a75b2"]),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=201,
            y=136,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3aa1cd"),
        SetAMEM16BitToConst(0x60, 12),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x3A8AC0),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x3A8AC0),
        RunSubroutine(["command_0x3a7826"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3aa1e5"),
        DoMaskEffect(CYLINDER_MASK),
        RunSubroutine(["command_0x3a76ca"]),
        RunSubroutine(["command_0x3a7847"]),
        PlaySound(sound=S0209_SMITHY_FORM_1_TRANSFORM),
        SetAMEM8BitToConst(0x6A, 0),
        SetAMEM8BitToConst(0x6B, 60),
        SetAMEM8BitToConst(0x6C, 1),
        RunSubroutine(["command_0x3a879f"]),
        RunSubroutine(["command_0x3a7852"]),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        RunSubroutine(["command_0x3a76ae"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-64,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3aa20f"),
        NewEffectObject(
            effect=EF0111_SMITHY_TRANSFORMS__BEAM_EFFECT_, looping_off=True
        ),
        RunSubroutine(["command_0x3a783c"]),
        FadeInEffect(duration=2),
        ScreenFlash(RED, 8),
        Layer3On(prop=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        RunSubroutine(["command_0x3a76d8"]),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        RunSubroutine(["command_0x3a76bc"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        Layer3Off(prop=OVERLAP_ALL_EXCEPT_ALLIES, bpp4=True),
        Db(bytearray(b"\x90")),
        RunSubroutine(["command_0x3a76e6"]),
        Pause2Frames(),
        ClearEffectIndex(),
        ReturnObjectQueue(),
    ])
