# pylint: disable=C0301,C0103

"""referenced by ally_spells Super Flame, ally_spells Fire Orb"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=542,
    script=[
        Db(bytearray(b" \x80\x10\x00"), identifier="queuestart_0x3593a3"),
        JmpIfAMEM8BitGreaterOrEqualThanConst(0x60, 31, ["command_0x3593b1"]),
        DisplayMessage(BATTLE_MESSAGE, 10),
        PauseScriptUntilDialogClosed(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x3593b1",
        ),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6D),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6F),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x359397),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x359397),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0030_FIRE_THROW),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=10,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0547_FIRE_ORB_FIREBALL,
            sequence=1,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        ShineEffect(
            colour_count=8, starting_colour_index=1, glow_duration=2, east=True
        ),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=26,
            y=-12,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=768, arch_height=320),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        Db(bytearray(b"\x81")),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=26,
            y=-12,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0547_FIRE_ORB_FIREBALL,
            sequence=1,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ShineEffect(
            colour_count=8, starting_colour_index=1, glow_duration=2, east=True
        ),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-6,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Db(bytearray(b"!\x98:\x00")),
        JmpIfAMEM16BitNotEqualsConst(0x68, 0, ["command_0x35942d"]),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=768, arch_height=320),
        Jmp(["command_0x359433"]),
        MoveSpriteToCoords(
            shift_type=SHIFT_TYPE_SHIFT,
            speed=1024,
            arch_height=0,
            identifier="command_0x35942d",
        ),
        PauseScriptUntil(
            condition=SPRITE_SHIFT_COMPLETE, identifier="command_0x359433"
        ),
        Pause1Frame(identifier="command_0x359437"),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 0, ["command_0x359437"]),
        PlaySound(sound=S0032_FIRE_BURN),
        Db(bytearray(b"\x81")),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0770_FIRE_ORB_HIT_EXPLOSION,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        SetAMEM8BitToConst(0x6E, 1),
        PauseScriptUntilSpriteSequenceDone(),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        RemoveObject(),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        StartTrackingAllyButtonInputs(identifier="queuestart_0x359465"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0547_FIRE_ORB_FIREBALL,
            sequence=1,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        ShineEffect(
            colour_count=8, starting_colour_index=1, glow_duration=2, east=True
        ),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6C),
        ClearAMEM8Bit(0x6D),
        ClearAMEM8Bit(0x6E),
        TimingForMultipleButtonPresses(
            start_accepting_input=7,
            destinations=["command_0x35948d"],
            identifier="command_0x359483",
        ),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x359397),
        IncAMEM8Bit(0x6C),
        IncAMEM8Bit(0x6D, identifier="command_0x35948d"),
        JmpIfAMEM8BitLessThanConst(0x6D, 18, ["command_0x359483"]),
        EndTrackingAllyButtonInputs(),
        Pause1Frame(identifier="command_0x359496"),
        JmpIfAMEM8BitNotEqualsAMEM(
            amem=0x6E, source_amem=0xCC, destinations=["command_0x359496"]
        ),
        Db(bytearray(b"\x81")),
        RemoveObject(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        PlaySound(sound=S0030_FIRE_THROW, channel=4, identifier="queuestart_0x3594a8"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=10,
            y=-269,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Db(bytearray(b"\x83\xc3")),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=26,
            y=-268,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=768, arch_height=320),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=26,
            y=-268,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Db(bytearray(b"\x83\x83")),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEMToRandom(amem=0x6A, upper_bound=3),
        JmpIfAMEM8BitEqualsConst(0x6A, 1, ["command_0x3594ee"]),
        JmpIfAMEM8BitEqualsConst(0x6A, 2, ["command_0x3594f9"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Jmp(["command_0x359501"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=4,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x3594ee",
        ),
        Jmp(["command_0x359501"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=2,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x3594f9",
        ),
        Db(bytearray(b"!\x9b:\x00"), identifier="command_0x359501"),
        JmpIfAMEM16BitNotEqualsConst(0x6B, 0, ["command_0x359514"]),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=768, arch_height=320),
        Jmp(["command_0x35951a"]),
        MoveSpriteToCoords(
            shift_type=SHIFT_TYPE_SHIFT,
            speed=1024,
            arch_height=0,
            identifier="command_0x359514",
        ),
        PauseScriptUntil(
            condition=SPRITE_SHIFT_COMPLETE, identifier="command_0x35951a"
        ),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6D),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x359397),
        RemoveObject(),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        IncAMEM8Bit(0x6E),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        PlaySound(sound=S0032_FIRE_BURN, identifier="queuestart_0x359535"),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM8BitToOMEMMain(amem=0x6A, omem=0x6A),
        JmpIfAMEM8BitEqualsConst(0x6A, 1, ["command_0x359555"]),
        JmpIfAMEM8BitEqualsConst(0x6A, 2, ["command_0x359560"]),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Jmp(["command_0x35956b"]),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=4,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x359555",
        ),
        Jmp(["command_0x35956b"]),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=2,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x359560",
        ),
        Jmp(["command_0x35956b"]),
        Pause1Frame(identifier="command_0x35956b"),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 0, ["command_0x35956b"]),
        SetAMEM8BitToConst(0x6D, 1),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6D),
        NewSpriteAtCoords(
            sprite_id=SPR0770_FIRE_ORB_HIT_EXPLOSION,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6E),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x359592",
        ),
        NewEffectObject(effect=EF0043_BLANK_RED_FLASH__4BPP_, looping_off=True),
        Db(bytearray(b"\x8a\x08")),
        Layer3On(prop=OVERLAP_ALL, bpp4=True),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Pause1Frame(identifier="command_0x3595a4"),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 1, ["command_0x3595a4"]),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(prop=OVERLAP_ALL, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
    ],
)
