# pylint: disable=C0301,C0103

"""referenced by battle_events BE0044_CZAR_DRAGON_DIES"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=361,
    script=[
        RunSubroutine(["command_0x3a787e"], identifier="queuestart_0x3a88ff"),
        Db(bytearray(b"\x83\x83")),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        RunSubroutine(["command_0x3a88d2"]),
        RunSubroutine(["command_0x3a787e"]),
        Db(bytearray(b"\x83\x83")),
        RunSubroutine(["command_0x3a7de5"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        RunSubroutine(["command_0x3a88d2"]),
        RunSubroutine(["command_0x3a787e"]),
        Db(bytearray(b"\x83\x83")),
        RunSubroutine(["command_0x3a7e1d"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        RunSubroutine(["command_0x3a88d2"]),
        RunSubroutine(["command_0x3a787e"]),
        Db(bytearray(b"\x83\x83")),
        RunSubroutine(["command_0x3a7f4c"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        RunSubroutine(["command_0x3a88d2"]),
        RunSubroutine(["command_0x3a787e"]),
        Db(bytearray(b"\x83\x83")),
        RunSubroutine(["command_0x3a7e9f"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        RunSubroutine(["command_0x3a88d2"]),
        RunSubroutine(["command_0x3a787e"]),
        Db(bytearray(b"\x83\x83")),
        RunSubroutine(["command_0x3a7de5"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        MoveObject(
            speed=65,
            start_position=0,
            end_position=-1025,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        RunSubroutine(["command_0x3a88d2"]),
        RunSubroutine(["command_0x3a787e"]),
        Db(bytearray(b"\x83\x83")),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=768, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RunSubroutine(["command_0x3a88d2"]),
        RunSubroutine(["command_0x3a787e"]),
        Db(bytearray(b"\x83\x83")),
        RunSubroutine(["command_0x3a7e1d"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        RunSubroutine(["command_0x3a88d2"]),
        RunSubroutine(["command_0x3a787e"]),
        Db(bytearray(b"\x83\x83")),
        RunSubroutine(["command_0x3a7de5"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=17,
            start_position=0,
            end_position=-513,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        MoveObject(
            speed=17,
            start_position=0,
            end_position=512,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        MoveObject(
            speed=17,
            start_position=0,
            end_position=-513,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        MoveObject(
            speed=17,
            start_position=0,
            end_position=512,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        MoveObject(
            speed=17,
            start_position=0,
            end_position=-513,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        MoveObject(
            speed=17,
            start_position=0,
            end_position=512,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=2048, arch_height=128),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RunSubroutine(["command_0x3a88d2"]),
        RunSubroutine(["command_0x3a7a0d"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION, x=0, y=0, z=-256, set_x=True
        ),
        Db(bytearray(b"\x83\x83")),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=1,
            start_position=1024,
            end_position=0,
            apply_to_z=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-193,
            end_position=0,
            apply_to_x=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        SetAMEM8BitToOMEMMain(amem=0x6A, omem=0x6A),
        DecAMEM8Bit(0x6A),
        SetOMEMMainToAMEM8Bit(omem=0x6A, amem=0x6A),
        RunSubroutine(["command_0x3a88d2"]),
        RunSubroutine(["command_0x3a787e"]),
        Db(bytearray(b"\x83\x83")),
        RunSubroutine(["command_0x3a7fa4"]),
        RunSubroutine(["command_0x3a7e55"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        RunSubroutine(["command_0x3a88d2"]),
        RunSubroutine(["command_0x3a787e"]),
        Db(bytearray(b"\x83\x83")),
        RunSubroutine(["command_0x3a7ef7"]),
        RunSubroutine(["command_0x3a7e55"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        RunSubroutine(["command_0x3a88d2"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-240,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Db(bytearray(b"\x83\x83")),
        RunSubroutine(["command_0x3a7fee"]),
        RunSubroutine(["command_0x3a8043"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        RunSubroutine(["command_0x3a88d2"]),
    ],
)
