# referenced by monster_spells MegaDrain, monster_spells Corona

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=71,
    script=[
        ScreenEffect(SEF0018_MEGA_DRAIN, identifier="queuestart_0x355dba"),
        Db(bytearray(b"\xa8\x02\x00")),
        Jmp(["command_0x35253b"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=128,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x355dc2",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0769_YELLOW_LIGHTNING_BALL,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PlaySound(sound=S0022_CORONA_DESCENDS),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=65,
            start_position=2048,
            end_position=-1025,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=40),
        ResetObjectMappingMemory(),
        StopCurrentSoundEffect(),
        ScreenEffect(SEF0017_CORONA),
        Db(bytearray(b"\xa8\x02\x00")),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=70),
        PlaySound(sound=S0022_CORONA_DESCENDS),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=65,
            start_position=1024,
            end_position=-2049,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        StopCurrentSoundEffect(),
        Jmp(["command_0x35252f"]),
    ],
)
