# referenced by ally_spells Ultra Flame

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=504,
    script=[
        Db(bytearray(b" \x80\x10\x00"), identifier="queuestart_0x359c13"),
        JmpIfAMEM8BitGreaterOrEqualThanConst(0x60, 31, ["command_0x359c21"]),
        DisplayMessage(BATTLE_MESSAGE, 10),
        PauseScriptUntilDialogClosed(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x359c21",
        ),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6D),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6F),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x359397),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x359C09),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0051_FIRE_THROW_BIG),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=10,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0577_ULTRA_FLAME_FIREBALL,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        ShineEffect(
            colour_count=8, starting_colour_index=1, glow_duration=2, east=True
        ),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=26,
            y=-12,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=768, arch_height=320),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        Db(bytearray(b"\x81")),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=26,
            y=-12,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0577_ULTRA_FLAME_FIREBALL,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ShineEffect(
            colour_count=8, starting_colour_index=1, glow_duration=2, east=True
        ),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-6,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Db(bytearray(b"!\x98:\x00")),
        JmpIfAMEM16BitNotEqualsConst(0x68, 0, ["command_0x359c9d"]),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=160),
        Jmp(["command_0x359ca3"]),
        MoveSpriteToCoords(
            shift_type=SHIFT_TYPE_SHIFT,
            speed=1280,
            arch_height=0,
            identifier="command_0x359c9d",
        ),
        PauseScriptUntil(
            condition=SPRITE_SHIFT_COMPLETE, identifier="command_0x359ca3"
        ),
        Pause1Frame(identifier="command_0x359ca7"),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 0, ["command_0x359ca7"]),
        PlaySound(sound=S0012_BOMB_EXPLOSION),
        Db(bytearray(b"\x81")),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0579_ULTRA_FLAME_EXPLOSION,
            sequence=1,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        SetAMEM8BitToConst(0x6E, 1),
        PauseScriptUntilSpriteSequenceDone(),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        RemoveObject(),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        StartTrackingAllyButtonInputs(identifier="queuestart_0x359cd5"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0577_ULTRA_FLAME_FIREBALL,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        ShineEffect(
            colour_count=8, starting_colour_index=1, glow_duration=2, east=True
        ),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6C),
        ClearAMEM8Bit(0x6D),
        ClearAMEM8Bit(0x6E),
        TimingForMultipleButtonPresses(
            end_accepting_input=7,
            destinations=["command_0x359cfd"],
            identifier="command_0x359cf3",
        ),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x359C09),
        IncAMEM8Bit(0x6C),
        IncAMEM8Bit(0x6D, identifier="command_0x359cfd"),
        JmpIfAMEM8BitLessThanConst(0x6D, 18, ["command_0x359cf3"]),
        Pause1Frame(identifier="command_0x359d05"),
        JmpIfAMEM8BitNotEqualsAMEM(
            amem=0x6E, source_amem=0xCC, destinations=["command_0x359d05"]
        ),
        EndTrackingAllyButtonInputs(),
        Db(bytearray(b"\x81")),
        RemoveObject(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        ResetTargetMappingMemory(identifier="queuestart_0x359d18"),
        SetAMEM16BitTo7E1x(0x62, 0x7E078E),
        PlaySound(sound=S0051_FIRE_THROW_BIG),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=14,
            y=-269,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Db(bytearray(b"\x83\xc3")),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=28,
            y=-268,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=768, arch_height=320),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=28,
            y=-268,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Db(bytearray(b"\x83\x83")),
        ResetTargetMappingMemory(),
        Set7E1xToAMEM16Bit(0x7E0730, 0x62),
        SetAMEM60ToCurrentTarget(),
        SetAMEMToRandom(amem=0x6A, upper_bound=3),
        JmpIfAMEM8BitEqualsConst(0x6A, 1, ["command_0x359d67"]),
        JmpIfAMEM8BitEqualsConst(0x6A, 2, ["command_0x359d72"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-20,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Jmp(["command_0x359d7a"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=4,
            y=-10,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x359d67",
        ),
        Jmp(["command_0x359d7a"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=2,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x359d72",
        ),
        Db(bytearray(b"!\x9b:\x00"), identifier="command_0x359d7a"),
        JmpIfAMEM16BitNotEqualsConst(0x6B, 0, ["command_0x359d8d"]),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=160),
        Jmp(["command_0x359d93"]),
        MoveSpriteToCoords(
            shift_type=SHIFT_TYPE_SHIFT,
            speed=1152,
            arch_height=0,
            identifier="command_0x359d8d",
        ),
        PauseScriptUntil(
            condition=SPRITE_SHIFT_COMPLETE, identifier="command_0x359d93"
        ),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6D),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x359C09),
        RemoveObject(),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        IncAMEM8Bit(0x6E),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        PlaySound(sound=S0012_BOMB_EXPLOSION, identifier="queuestart_0x359dae"),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM8BitToOMEMMain(amem=0x6A, omem=0x6A),
        JmpIfAMEM8BitEqualsConst(0x6A, 1, ["command_0x359dce"]),
        JmpIfAMEM8BitEqualsConst(0x6A, 2, ["command_0x359dd9"]),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-24,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Jmp(["command_0x359de4"]),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=4,
            y=-12,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x359dce",
        ),
        Jmp(["command_0x359de4"]),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=2,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x359dd9",
        ),
        Jmp(["command_0x359de4"]),
        Pause1Frame(identifier="command_0x359de4"),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 0, ["command_0x359de4"]),
        SetAMEM8BitToConst(0x6D, 1),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6D),
        NewSpriteAtCoords(
            sprite_id=SPR0579_ULTRA_FLAME_EXPLOSION,
            sequence=1,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6E),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
    ],
)
