# pylint: disable=C0301,C0103

"""referenced by items PureWater"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=110,
    script=[
        ClearAMEM16Bit(0x60, identifier="queuestart_0x35dae3"),
        ClearAMEM8Bit(0x6F),
        PlaySound(sound=S0127_LIQUID_DROPLET),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35DAD9),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=9),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35DAD9),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=9),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35DAD9),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35db0a"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-6,
            y=-3,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        NewSpriteAtCoords(
            sprite_id=SPR0514_BLUE_EXPLOSION,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35db1f"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=6,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        NewSpriteAtCoords(
            sprite_id=SPR0514_BLUE_EXPLOSION,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35db34"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-13,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        NewSpriteAtCoords(
            sprite_id=SPR0514_BLUE_EXPLOSION,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        PauseScriptUntilSpriteSequenceDone(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        RemoveObject(),
        ReturnObjectQueue(),
    ])
