# referenced by ally_spells Poison Gas

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=702,
    script=[
        Db(bytearray(b" \x80\x10\x00"), identifier="queuestart_0x35ad5c"),
        JmpIfAMEM8BitGreaterOrEqualThanConst(0x60, 31, ["command_0x35ad6a"]),
        DisplayMessage(BATTLE_MESSAGE, 12),
        PauseScriptUntilDialogClosed(),
        ClearAMEM16Bit(0x60, identifier="command_0x35ad6a"),
        ClearAMEM16Bit(0x6C),
        ClearAMEM16Bit(0x6E),
        Set7E1xToAMEM16Bit(0x7EE020, 0x6E),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35AD4A),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35AD4A),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35AD4A),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35AD4A),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x35AD4A),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6C),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35AD4A),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        ClearAMEM16Bit(0x62, identifier="queuestart_0x35ada9"),
        ClearAMEM8Bit(0x6C),
        SetAMEM8BitToConst(0x66, 4),
        ResetTargetMappingMemory(identifier="command_0x35adb1"),
        MuteTimingJmp(["command_0x35add4"]),
        UnknownJmp26(182, ["command_0x35adcc"]),
        SetAMEMToAMEM16Bit(dest_amem=0xC4, amem=0x60),
        ClearAMEM16Bit(0x60),
        IncAMEM8Bit(0x6C),
        ClearAMEM8Bit(0x6D),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35AD4A),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        IncAMEM16Bit(0x62, identifier="command_0x35adcc"),
        JmpIfAMEM16BitNotEqualsConst(0x62, 6, ["command_0x35adb1"]),
        JmpIfAMEM8BitEqualsConst(
            0x6C, 0, ["command_0x35ae00"], identifier="command_0x35add4"
        ),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=304,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0778_POISON_GAS_GREEN_GAS_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        SetAMEM8BitToConst(0x6D, 255),
        PlaySound(sound=S0178_POISON_GAS_2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0),
        PlaySound(sound=S0178_POISON_GAS_2),
        PauseScriptUntilSpriteSequenceDone(),
        SetAMEM8BitToConst(0x6D, 35),
        RemoveObject(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=6),
        SetAMEM8BitToConst(0x6C, 1, identifier="command_0x35ae00"),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnObjectQueue(),
        ResetTargetMappingMemory(identifier="queuestart_0x35ae09"),
        SetAMEM16BitToOMEMMain(amem=0x60, omem=0x64),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-24,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Pause1Frame(identifier="command_0x35ae1e"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 255, ["command_0x35ae1e"]),
        Db(bytearray(b"\x83\x83")),
        Pause1Frame(identifier="command_0x35ae2b"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 35, ["command_0x35ae2b"]),
        RemoveObject(),
        ReturnObjectQueue(),
        StartTrackingAllyButtonInputs(identifier="queuestart_0x35ae38"),
        TimingForRotationCount(
            end_accepting_input=70, start_accepting_input=0, max_presses=16
        ),
        EndTrackingAllyButtonInputs(),
        SetAMEM8BitToConst(0x6C, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35ae47",
        ),
        NewEffectObject(effect=EF0110_POISON_GAS_BG, playback_off=True),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        IncAMEM8Bit(0x6E),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6E),
        Pause1Frame(identifier="command_0x35ae5c"),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 2, ["command_0x35ae5c"]),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Layer3On(property=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        Pause1Frame(identifier="command_0x35ae71"),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 3, ["command_0x35ae71"]),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(property=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        SetAMEM8BitToConst(0x6E, 4),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6E),
        Pause2Frames(),
        ClearEffectIndex(),
        ResetObjectMappingMemory(),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35ae97",
        ),
        NewEffectObject(effect=EF0109_POISON_GAS_FG_2, looping_on=True),
        SetAMEM8BitTo7E1x(0x6F, 0x7EE020),
        IncAMEM8Bit(0x6F),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6F),
        Pause1Frame(identifier="command_0x35aeac"),
        SetAMEM8BitTo7E1x(0x6F, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 2, ["command_0x35aeac"]),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Layer3On(property=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        Pause1Frame(identifier="command_0x35aec1"),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 3, ["command_0x35aec1"]),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(property=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        ResetObjectMappingMemory(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=176,
            y=88,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35aedf",
        ),
        Pause1Frame(identifier="command_0x35aee7"),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 2, ["command_0x35aee7"]),
        DoMaskEffect(CIRCLE_MASK),
        SetMaskCoords((1, 0), (-113, 8), (32, 10), (1, 0)),
        Pause1Frame(),
        SetAMEMToAMEM8Bit(dest_amem=0xA7, amem=0x6A),
        SetAMEM8BitToAMEM(amem=0x6B, source_amem=0xA8),
        IncAMEM8BitByConst(0x6B, 1),
        SetAMEMToAMEM8Bit(dest_amem=0xA8, amem=0x6B),
        JmpIfAMEM8BitNotEqualsConst(0x6B, 70, ["174"]),
        SetAMEM8BitToConst(0x6E, 3),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6E),
        Pause1Frame(identifier="command_0x35af1d"),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 4, ["command_0x35af1d"]),
        Db(bytearray(b"\x90")),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=128,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35af2c",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0573_MOKURA,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=132,
            y=28,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
        PlaySound(sound=S0021_SCARECROW_BIRDIES),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=140,
            y=52,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1664, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=148,
            y=64,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1536, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=164,
            y=80,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1408, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=180,
            y=88,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1280, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=184,
            y=94,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1152, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=184,
            y=94,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        PlaySound(sound=S0177_POISON_GAS_1),
        MoveObject(
            speed=1,
            start_position=-113,
            end_position=-113,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
            identifier="command_0x35afba",
        ),
        MoveObject(
            speed=1,
            start_position=-100,
            end_position=-100,
            apply_to_z=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        MoveObject(
            speed=1,
            start_position=112,
            end_position=112,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 3, ["command_0x35afba"]),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=256, y=0, z=0, set_z=True),
        MoveObject(
            speed=321,
            start_position=0,
            end_position=4096,
            apply_to_x=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=161,
            start_position=0,
            end_position=2048,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PlaySound(sound=S0011_SWOOSH_RUN_AWAY),
        PauseScriptUntil(condition=0x04),
        ResetObjectMappingMemory(),
        RemoveObject(),
        Pause1Frame(identifier="command_0x35b006"),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 4, ["command_0x35b006"]),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
    ],
)
