# referenced by battle_events BE0024_MACHINE_MADE_YARIDOVICH_MULTIPLIER, battle_events BE0022_YARIDOVICH_MIRAGE_ATTACK, battle_events BE0023_YARIDOVICH_MIRAGE_IS_DESTROYED_RETURN_TO_SINGLE_FORM, battle_events BE0021_JOHNNY_CHALLENGES_MARIO_TO_A_ONE_ON_ONE, battle_events BE0026_INTRO_SCENE_TENTACLES_RISE_FROM_HOLES, battle_events BE0028_BEAT_TENTACLES_MOVE_ON_TO_KING_CALAMARI, battle_events BE0027_BEAT_TENTACLES_MOVE_ON_TO_NEXT, battle_events BE0025_DRILL_BIT

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=1415,
    script=[
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3ac1f1"),
        SpriteSequence(sequence=0, looping_on=True),
        RunSubroutine(["command_0x3a7203"]),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0001_MARIO_JUMP_FRONT,
            sequence=4,
            store_to_vram=True,
            store_palette=True,
        ),
        RunSubroutine(["command_0x3a733e"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT,
            sequence=1,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        SpriteSequence(sequence=7, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=7, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0002_MARIO_WALKING_UP_RIGHT,
            sequence=0,
            store_to_vram=True,
            store_palette=True,
        ),
        RunSubroutine(["command_0x3a757a"]),
        RunSubroutine(["command_0x3a773f"]),
        RunSubroutine(["command_0x3a71da"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a773f"], identifier="queuestart_0x3ac234"),
        ClearAMEM8Bit(0x60),
        SetAMEM8BitToConst(0x60, 128),
        Set7E1xToAMEM8Bit(0x7EFB00, 0x60),
        SpriteSequence(sequence=0, looping_on=True),
        RunSubroutine(["command_0x3a8124"]),
        RunSubroutine(["command_0x3a72e6"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        ClearAMEM8Bit(0x68),
        SetAMEM8BitTo7E5x(0x60, 0x7E0001),
        JmpIfAMEM8BitEqualsConst(0x60, 2, ["command_0x3ac25a"]),
        Jmp(["command_0x3ac2e3"]),
        Db(bytearray(b"\x16"), identifier="command_0x3ac25a"),
        Pause1Frame(),
        SetAMEM8BitTo7E1x(0x67, 0x7EE003),
        JmpIfAMEMBitsSet(0x67, [0], ["command_0x3ac2a9"]),
        Pause1Frame(),
        SetAMEMToRandom(amem=0x68, upper_bound=100),
        JmpIfAMEM8BitEqualsConst(0x68, 0, ["command_0x3ac286"]),
        JmpIfAMEM8BitEqualsConst(0x68, 1, ["command_0x3ac290"]),
        JmpIfAMEM8BitEqualsConst(0x68, 2, ["command_0x3ac29a"]),
        JmpIfAMEM8BitEqualsConst(0x68, 3, ["command_0x3ac2a0"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        Jmp(["command_0x3ac25a"]),
        SpriteSequence(
            sequence=3, looping_off=True, mirror=True, identifier="command_0x3ac286"
        ),
        RunSubroutine(["command_0x3a7374"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        Jmp(["command_0x3ac25a"]),
        SpriteSequence(
            sequence=3, looping_off=True, mirror=True, identifier="command_0x3ac290"
        ),
        RunSubroutine(["command_0x3a7374"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        Jmp(["command_0x3ac25a"]),
        SpriteSequence(sequence=5, mirror=True, identifier="command_0x3ac29a"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3ac25a"]),
        SpriteSequence(sequence=12, mirror=True, identifier="command_0x3ac2a0"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        Jmp(["command_0x3ac25a"]),
        SetAMEM8BitTo7E1x(0x60, 0x7EFA80, identifier="command_0x3ac2a9"),
        ClearAMEMBits(0x60, [7]),
        Set7E1xToAMEM8Bit(0x7EFA80, 0x60),
        SetAMEM8BitTo7E1x(0x60, 0x7EFB00),
        ClearAMEMBits(0x60, [7]),
        Set7E1xToAMEM8Bit(0x7EFB00, 0x60),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a773f"], identifier="queuestart_0x3ac2c0"),
        ClearAMEM8Bit(0x60),
        SetAMEM8BitToConst(0x60, 128),
        Set7E1xToAMEM8Bit(0x7EFA80, 0x60),
        SpriteSequence(sequence=0, looping_on=True),
        RunSubroutine(["command_0x3a81c4"]),
        RunSubroutine(["command_0x3a72e6"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        ClearAMEM8Bit(0x68),
        SetAMEM8BitTo7E5x(0x60, 0x7E0001),
        JmpIfAMEM8BitEqualsConst(0x60, 2, ["command_0x3ac25a"]),
        Db(bytearray(b"\x16"), identifier="command_0x3ac2e3"),
        Pause1Frame(),
        SetAMEM8BitTo7E1x(0x67, 0x7EE003),
        JmpIfAMEMBitsSet(0x67, [0], ["command_0x3ac32e"]),
        Pause1Frame(),
        SetAMEMToRandom(amem=0x68, upper_bound=100),
        JmpIfAMEM8BitEqualsConst(0x68, 0, ["command_0x3ac30f"]),
        JmpIfAMEM8BitEqualsConst(0x68, 1, ["command_0x3ac319"]),
        JmpIfAMEM8BitEqualsConst(0x68, 2, ["command_0x3ac31f"]),
        JmpIfAMEM8BitEqualsConst(0x68, 3, ["command_0x3ac325"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        Jmp(["command_0x3ac2e3"]),
        SpriteSequence(
            sequence=3, looping_off=True, mirror=True, identifier="command_0x3ac30f"
        ),
        RunSubroutine(["command_0x3a7374"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        Jmp(["command_0x3ac2e3"]),
        SpriteSequence(sequence=4, mirror=True, identifier="command_0x3ac319"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3ac2e3"]),
        SpriteSequence(sequence=5, mirror=True, identifier="command_0x3ac31f"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3ac2e3"]),
        SpriteSequence(sequence=12, mirror=True, identifier="command_0x3ac325"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        Jmp(["command_0x3ac2e3"]),
        SetAMEM8BitTo7E1x(0x60, 0x7EFA80, identifier="command_0x3ac32e"),
        ClearAMEMBits(0x60, [7]),
        Set7E1xToAMEM8Bit(0x7EFA80, 0x60),
        SetAMEM8BitTo7E1x(0x60, 0x7EFB00),
        ClearAMEMBits(0x60, [7]),
        Set7E1xToAMEM8Bit(0x7EFB00, 0x60),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a8322"], identifier="queuestart_0x3ac345"),
        RunSubroutine(["command_0x3a727a"]),
        SetAMEM8BitToConst(0x60, 152),
        SetAMEM8BitToConst(0x61, 104),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a82b4"], identifier="queuestart_0x3ac35f"),
        RunSubroutine(["command_0x3a727a"]),
        SetAMEM8BitToConst(0x60, 200),
        SetAMEM8BitToConst(0x61, 160),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        ResetTargetMappingMemory(identifier="queuestart_0x3ac37d"),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=183,
            y=127,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a727a"]),
        SetAMEM8BitToConst(0x60, 183),
        SetAMEM8BitToConst(0x61, 127),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        ClearAMEM8Bit(0x60, identifier="queuestart_0x3ac39d"),
        SetAMEM16BitToConst(0x60, 5),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x3A8AC0),
        VisibilityOff(),
        PlaySound(sound=S0107_BUBBLE_POP),
        RunSubroutine(["command_0x3a756c"]),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=183,
            y=127,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3ac3b2",
        ),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0482_YARIDOVICH,
            sequence=0,
            priority=2,
            vram_address=0x7800,
            palette_row=12,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=YaridovichMirage, position=1, bit_7=True),
        RunSubroutine(["command_0x3a7544"]),
        RunSubroutine(["command_0x3a756c"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3ac3cf"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=183,
            y=127,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0402_MACHINE_MADE_DRILL_BIT,
            sequence=0,
            priority=2,
            vram_address=0x7800,
            palette_row=12,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=MachineMadeDrillBit, position=1, bit_7=True),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=167,
            y=103,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7307"]),
        SetAMEM8BitToConst(0x60, 167),
        SetAMEM8BitToConst(0x61, 103),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        RunSubroutine(["command_0x3a771e"]),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3ac40b"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=183,
            y=127,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0402_MACHINE_MADE_DRILL_BIT,
            sequence=0,
            priority=2,
            vram_address=0x7A00,
            palette_row=12,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=MachineMadeDrillBit, position=1, bit_7=True),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=135,
            y=119,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7307"]),
        SetAMEM8BitToConst(0x60, 135),
        SetAMEM8BitToConst(0x61, 119),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        RunSubroutine(["command_0x3a771e"]),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3ac447"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=183,
            y=127,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0402_MACHINE_MADE_DRILL_BIT,
            sequence=0,
            priority=2,
            vram_address=0x7C00,
            palette_row=12,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=MachineMadeDrillBit, position=1, bit_7=True),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=231,
            y=135,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7307"]),
        SetAMEM8BitToConst(0x60, 231),
        SetAMEM8BitToConst(0x61, 135),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        RunSubroutine(["command_0x3a771e"]),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3ac483"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=183,
            y=127,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0402_MACHINE_MADE_DRILL_BIT,
            sequence=0,
            priority=2,
            vram_address=0x7E00,
            palette_row=12,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=MachineMadeDrillBit, position=1, bit_7=True),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=199,
            y=151,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7307"]),
        SetAMEM8BitToConst(0x60, 199),
        SetAMEM8BitToConst(0x61, 151),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        RunSubroutine(["command_0x3a755e"]),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3ac4c3"),
        ClearAMEM8Bit(0x60),
        SetAMEM16BitToConst(0x60, 5),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x3A8AC0),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        VisibilityOn(),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        ResetTargetMappingMemory(identifier="queuestart_0x3ac4da"),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=183,
            y=127,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7307"]),
        VisibilityOff(),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        ResetTargetMappingMemory(identifier="queuestart_0x3ac4ec"),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=183,
            y=127,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7307"]),
        VisibilityOff(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        RunSubroutine(["command_0x3a756c"]),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        RemoveObject(identifier="queuestart_0x3ac505"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=106,
            y=92,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0473_TENTACLES_LEFT,
            sequence=5,
            priority=2,
            vram_address=0x7000,
            palette_row=10,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=TentaclesLeft, position=1, bit_7=True),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        RemoveObject(identifier="queuestart_0x3ac51f"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=219,
            y=114,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0465_TENTACLES_RIGHT,
            sequence=5,
            priority=2,
            vram_address=0x7200,
            palette_row=12,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=TentaclesRight, position=1, bit_7=True),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        RemoveObject(identifier="queuestart_0x3ac539"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=216,
            y=168,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0465_TENTACLES_RIGHT,
            sequence=5,
            priority=2,
            vram_address=0x7400,
            palette_row=12,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=TentaclesRight, position=1, bit_7=True),
        RunSubroutine(["command_0x3a755e"]),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3ac556"),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=110,
            y=80,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0473_TENTACLES_LEFT,
            sequence=5,
            priority=2,
            vram_address=0x7000,
            palette_row=10,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=TentaclesLeft, position=1, bit_7=True),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3ac573"),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=196,
            y=80,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0473_TENTACLES_LEFT,
            sequence=5,
            priority=2,
            vram_address=0x7200,
            palette_row=10,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=TentaclesLeft, position=1, bit_7=True),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3ac590"),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=220,
            y=155,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0465_TENTACLES_RIGHT,
            sequence=5,
            priority=2,
            vram_address=0x7400,
            palette_row=12,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=TentaclesRight, position=1, bit_7=True),
        RunSubroutine(["command_0x3a755e"]),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        SpriteSequence(sequence=0, looping_on=True, identifier="queuestart_0x3ac5b0"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=100),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=72,
            end_position=72,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=97,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a81ce"]),
        RunSubroutine(["command_0x3a727a"]),
        SetAMEM8BitToConst(0x60, 168),
        SetAMEM8BitToConst(0x61, 192),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        RunSubroutine(["command_0x3a7729"]),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a7544"]),
        Db(bytearray(b"m")),
        ReturnSpriteQueue(),
        SpriteSequence(sequence=0, looping_on=True, identifier="queuestart_0x3ac5f8"),
        RunSubroutine(["command_0x3a7729"]),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a7544"]),
        Db(bytearray(b"m")),
        ReturnSpriteQueue(),
        SpriteSequence(sequence=0, looping_on=True, identifier="queuestart_0x3ac604"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=100),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-137,
            end_position=-137,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=97,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a81e2"]),
        RunSubroutine(["command_0x3a727a"]),
        SetAMEM8BitToConst(0x60, 88),
        SetAMEM8BitToConst(0x61, 136),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        RunSubroutine(["command_0x3a7729"]),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a7544"]),
        Db(bytearray(b"m")),
        ReturnSpriteQueue(),
        SpriteSequence(sequence=0, looping_on=True, identifier="queuestart_0x3ac64c"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=80),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=144,
            end_position=144,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-81,
            end_position=-81,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=97,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=120,
            y=192,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a727a"]),
        SetAMEM8BitToConst(0x60, 120),
        SetAMEM8BitToConst(0x61, 192),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        RunSubroutine(["command_0x3a7729"]),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a7544"]),
        Db(bytearray(b"m")),
        ReturnSpriteQueue(),
        SpriteSequence(sequence=0, looping_on=True, identifier="queuestart_0x3ac69e"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-65,
            end_position=-65,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=97,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=80),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=72,
            end_position=72,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-65,
            end_position=-65,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=97,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=88,
            y=176,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a727a"]),
        RunSubroutine(["command_0x3a7729"]),
        SetAMEM8BitToConst(0x60, 88),
        SetAMEM8BitToConst(0x61, 176),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        SpriteSequence(sequence=0, looping_off=True),
        Db(bytearray(b"m")),
        ReturnSpriteQueue(),
        SpriteSequence(sequence=0, looping_on=True, identifier="queuestart_0x3ac729"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=144,
            end_position=144,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-145,
            end_position=-145,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=97,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=150),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=56,
            y=160,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a727a"]),
        SetAMEM8BitToConst(0x60, 56),
        SetAMEM8BitToConst(0x61, 160),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        RunSubroutine(["command_0x3a7729"]),
        SpriteSequence(sequence=0, looping_off=True),
        Db(bytearray(b"m")),
        ReturnSpriteQueue(),
    ],
)
