# pylint: disable=C0301,C0103

"""referenced by ally_spells Geno Beam"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=741,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=10,
            y=-258,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35b660",
        ),
        RunSubroutine(["command_0x35b925"]),
        ReturnObjectQueue(),
        Db(bytearray(b"\xa6"), identifier="queuestart_0x35b66c"),
        ClearAMEM16Bit(0x60),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=112,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0798_GENO_BEAM_BLAST_FLASH_RED_POWER_UP_STAR,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ShineEffect(
            colour_count=7, starting_colour_index=1, glow_duration=2, east=True
        ),
        ClearAMEM16Bit(0x6C),
        ClearAMEM16Bit(0x6E),
        ObjectQueueAtOffsetAndIndex(index=30, target_address=0x35B43D),
        ObjectQueueAtOffsetAndIndex(index=32, target_address=0x35B43D),
        ObjectQueueAtOffsetAndIndex(index=34, target_address=0x35B43D),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=29),
        SetAMEM8BitToConst(0x6C, 1),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=24),
        SetAMEM8BitToConst(0x6C, 2),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=24),
        SetAMEM8BitToConst(0x6C, 3),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=24),
        SetAMEM8BitToConst(0x6C, 4),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        Db(bytearray(b"\x81")),
        RemoveObject(),
        SetAMEM8BitToConst(0x6E, 1),
        Db(bytearray(b"\xa5")),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=168,
            y=208,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35b6c9",
        ),
        Db(bytearray(b"\x83\x83")),
        Pause1Frame(identifier="command_0x35b6d3"),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 1, ["command_0x35b6d3"]),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=184,
            y=208,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=1,
            start_position=1024,
            end_position=1024,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=0x04),
        ResetObjectMappingMemory(),
        Pause1Frame(identifier="command_0x35b6f4"),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 4, ["command_0x35b6f4"]),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=168,
            y=208,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=1,
            start_position=-1281,
            end_position=-1281,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=0x04),
        ResetObjectMappingMemory(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=168,
            y=208,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35b71f",
        ),
        Db(bytearray(b"\x83\x83")),
        Pause1Frame(identifier="command_0x35b729"),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 1, ["command_0x35b729"]),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=184,
            y=208,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=1,
            start_position=1024,
            end_position=1024,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=0x04),
        ResetObjectMappingMemory(),
        Pause1Frame(identifier="command_0x35b74a"),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 2, ["command_0x35b74a"]),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=204,
            y=208,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=1,
            start_position=1024,
            end_position=1024,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=0x04),
        ResetObjectMappingMemory(),
        Pause1Frame(identifier="command_0x35b76b"),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 4, ["command_0x35b76b"]),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=168,
            y=208,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=1,
            start_position=-1793,
            end_position=-1793,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=0x04),
        ResetObjectMappingMemory(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=168,
            y=208,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35b796",
        ),
        Db(bytearray(b"\x83\x83")),
        Pause1Frame(identifier="command_0x35b7a0"),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 1, ["command_0x35b7a0"]),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=184,
            y=208,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=1,
            start_position=1024,
            end_position=1024,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=0x04),
        ResetObjectMappingMemory(),
        Pause1Frame(identifier="command_0x35b7c1"),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 2, ["command_0x35b7c1"]),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=204,
            y=208,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=1,
            start_position=1024,
            end_position=1024,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=0x04),
        ResetObjectMappingMemory(),
        Pause1Frame(identifier="command_0x35b7e2"),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 3, ["command_0x35b7e2"]),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=224,
            y=208,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=1,
            start_position=1024,
            end_position=1024,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=0x04),
        ResetObjectMappingMemory(),
        Pause1Frame(identifier="command_0x35b803"),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 4, ["command_0x35b803"]),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=168,
            y=208,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=1,
            start_position=-2305,
            end_position=-2305,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=0x04),
        ResetObjectMappingMemory(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=18, identifier="queuestart_0x35b82e"
        ),
        SetAMEM8BitToOMEMMain(amem=0x6A, omem=0x6A),
        JmpIfAMEM8BitEqualsConst(0x6A, 64, ["command_0x35b847"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=15,
            y=241,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Jmp(["command_0x35b84f"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=10,
            y=244,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x35b847",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0528_VERY_SMALL_BLACK_DOT,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=8,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
            identifier="command_0x35b84f",
        ),
        ShineEffect(
            colour_count=6, starting_colour_index=1, glow_duration=1, east=True
        ),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6E),
        ObjectQueueAtOffsetAndIndex(index=38, target_address=0x35B43D),
        ObjectQueueAtOffsetAndIndex(index=40, target_address=0x35B43D),
        ObjectQueueAtOffsetAndIndex(index=42, target_address=0x35B43D),
        ObjectQueueAtOffsetAndIndex(index=44, target_address=0x35B43D),
        ObjectQueueAtOffsetAndIndex(index=46, target_address=0x35B43D),
        Pause1Frame(identifier="command_0x35b874"),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 5, ["command_0x35b874"]),
        Db(bytearray(b"\x81")),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35b87e",
        ),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=17,
            start_position=512,
            end_position=0,
            apply_to_x=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=9,
            start_position=-1153,
            end_position=0,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        RunSubroutine(["command_0x35b914"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35b89c",
        ),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=17,
            start_position=512,
            end_position=0,
            apply_to_x=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=9,
            start_position=512,
            end_position=0,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        RunSubroutine(["command_0x35b914"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35b8ba",
        ),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=17,
            start_position=640,
            end_position=0,
            apply_to_x=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=9,
            start_position=-689,
            end_position=0,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        RunSubroutine(["command_0x35b914"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35b8d8",
        ),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=17,
            start_position=640,
            end_position=0,
            apply_to_x=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=3,
            start_position=128,
            end_position=0,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        RunSubroutine(["command_0x35b914"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35b8f6",
        ),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=17,
            start_position=768,
            end_position=0,
            apply_to_x=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=9,
            start_position=-257,
            end_position=0,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        RunSubroutine(["command_0x35b914"]),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=5, identifier="command_0x35b914"
        ),
        ResetObjectMappingMemory(),
        RemoveObject(),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        IncAMEM8Bit(0x6E),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnSubroutine(),
        Db(bytearray(b"\x83\xc3"), identifier="command_0x35b925"),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X00, speed=160, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        IncAMEM8Bit(0x6C),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        RemoveObject(),
        ReturnSubroutine(),
    ],
)
