# pylint: disable=C0301,C0103

"""referenced by behaviour_11_0x35086A, behaviour_10_0x350830, behaviour_3_0x350669, behaviour_2_0x350635, behaviour_4_0x3506A7"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=226,
    script=[
        PlaySound(sound=S0013_COIN, identifier="queuestart_0x35061e"),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0192_COIN, sequence=2, store_to_vram=True, store_palette=True
        ),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=25,
            start_position=-769,
            end_position=0,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Db(bytearray(b"\x12\x81")),
        PauseScriptUntilSpriteSequenceDone(),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        Db(bytearray(b"T")),
        Db(bytearray(b">")),
        SpriteSequence(sequence=13, looping_off=True),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=0,
            apply_to_x=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=0,
            apply_to_y=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=0,
            apply_to_x=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=0,
            apply_to_y=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetObjectMappingMemory(),
        ResetSpriteSequence(),
        Jmp(["command_0x3506e2"]),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        Db(bytearray(b"T")),
        Db(bytearray(b">")),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0015_BOWSER_SURPRISE,
            sequence=0,
            store_to_vram=True,
            store_palette=True,
        ),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=0,
            apply_to_x=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=0,
            apply_to_y=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=0,
            apply_to_x=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=0,
            apply_to_y=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetObjectMappingMemory(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0013_BOWSER_WALKING_DOWN_LEFT,
            sequence=0,
            store_to_vram=True,
            store_palette=True,
        ),
        ResetSpriteSequence(),
        Jmp(["command_0x3506e2"]),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        Db(bytearray(b"T")),
        Db(bytearray(b">")),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0003_MARIO_SURPRISE_LEFT,
            sequence=0,
            store_to_vram=True,
            store_palette=True,
        ),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=0,
            apply_to_x=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=0,
            apply_to_y=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=0,
            apply_to_x=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=0,
            apply_to_y=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetObjectMappingMemory(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT,
            sequence=0,
            store_to_vram=True,
            store_palette=True,
        ),
        ResetSpriteSequence(),
        Db(bytearray(b"W"), identifier="command_0x3506e2"),
        Db(bytearray(b";")),
        Db(bytearray(b"U")),
        Db(bytearray(b";")),
        Db(bytearray(b"V")),
        JmpIfTargetEnabled(["command_0x3506fc"]),
        PlaySound(sound=S0089_COMMON_MONSTER_EXPLOSION),
        Db(bytearray(b"\xa4")),
        SetAMEM8BitTo7E5x(0x60, 0x7E002C),
        ClearAMEM8Bit(0x61),
        ObjectQueueAtOffsetAndIndexAtAMEM60(target_address=0x3505FE),
        RemoveObject(),
        SetAMEMToAMEM16Bit(dest_amem=0x6E, amem=0x62),
        Db(bytearray(b"\x98")),
        Db(bytearray(b"F"), identifier="command_0x3506fc"),
        Jmp(["command_0x3505d5"]),
    ],
)
