# pylint: disable=C0301,C0103

"""referenced by behaviour_33_0x350C5B, behaviour_34_0x350C9E, behaviour_51_0x350F56, behaviour_24_0x350A9C, behaviour_8_0x3507A2, weapons ChompShell, behaviour_41_0x350DAF, behaviour_16_0x350928, behaviour_32_0x350C14, weapons Chomp, behaviour_52_0x350F6B, behaviour_23_0x350A55, behaviour_9_0x3507E9, behaviour_42_0x350DED, behaviour_43_0x350E38"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=147,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35f4af"),
        NewSpriteAtCoords(
            sprite_id=SPR0034_CHOMP,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        PlaySound(sound=S0121_BIG_SWING),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        PlaySound(sound=S0121_BIG_SWING),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        PlaySound(sound=S0121_BIG_SWING),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        PlaySound(sound=S0121_BIG_SWING),
        PauseScriptUntilSpriteSequenceDone(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=48,
            y=-32,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        SpriteSequence(sequence=1),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
        PauseScriptUntil(condition=0x07),
        SetAMEM8BitToConst(0x67, 1),
        SetOMEMMainToAMEM8Bit(omem=0x67, amem=0x67),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        RemoveObject(),
        ReturnObjectQueue(),
        PlaySound(sound=S0122_POISONED, identifier="queuestart_0x35f501"),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        NewSpriteAtCoords(
            sprite_id=SPR0034_CHOMP,
            sequence=2,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=6),
        PlaySound(sound=S0123_CHOMP_BITE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        PlaySound(sound=S0123_CHOMP_BITE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        PlaySound(sound=S0123_CHOMP_BITE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        PlaySound(sound=S0123_CHOMP_BITE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        PlaySound(sound=S0042_BLADE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        RemoveObject(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
    ])
