# referenced by monster_spells ChestScrow, monster_spells ChestFear, monster_spells ChestPoison, monster_spells ChestMute

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(expected_size = 136, script = [
	SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E, identifier="queuestart_0x35c68a"),
	ClearAMEM8Bit(0x6F),
	SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True),
	JmpIfAMEM8BitEqualsConst(0x6E, 1, ["command_0x35c6b0"]),
	JmpIfAMEM8BitEqualsConst(0x6E, 2, ["command_0x35c6b6"]),
	JmpIfAMEM8BitEqualsConst(0x6E, 3, ["command_0x35c6bc"]),
	NewEffectObject(effect=EF0072_SMITHY_TREASURE_HEAD_SPELL__YELLOW, playback_off=True),
	Jmp(["command_0x35c6bf"]),
	NewEffectObject(effect=EF0069_SMITHY_TREASURE_HEAD_SPELL__RED, playback_off=True, identifier="command_0x35c6b0"),
	Jmp(["command_0x35c6bf"]),
	NewEffectObject(effect=EF0071_SMITHY_TREASURE_HEAD_SPELL__BLUE, playback_off=True, identifier="command_0x35c6b6"),
	Jmp(["command_0x35c6bf"]),
	NewEffectObject(effect=EF0070_SMITHY_TREASURE_HEAD_SPELL__GREEN, playback_off=True, identifier="command_0x35c6bc"),
	Db(bytearray(b'y\x00\x11\x1e\x02'), identifier="command_0x35c6bf"),
	Layer3On(property=OVERLAP_ALL, bpp4=True),
	Db(bytearray(b'\x9c\x80B \x00\x04\x00`\x00')),
	PlaySound(sound=S0017_STAR_GUN_SHOOT),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=9),
	PlaySound(sound=S0017_STAR_GUN_SHOOT, channel=4),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=9),
	PlaySound(sound=S0017_STAR_GUN_SHOOT),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=9),
	PlaySound(sound=S0017_STAR_GUN_SHOOT, channel=4),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=9),
	PlaySound(sound=S0017_STAR_GUN_SHOOT),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=9),
	PlaySound(sound=S0017_STAR_GUN_SHOOT, channel=4),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=9),
	PlaySound(sound=S0017_STAR_GUN_SHOOT),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50),
	FadeOutObject(duration=1),
	PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
	Db(bytearray(b'y\x00\x11\x1e\x00')),
	Layer3Off(property=OVERLAP_ALL, bpp4=True),
	Db(bytearray(b'\x9d\x82')),
	Pause2Frames(),
	ClearEffectIndex(),
	SetAMEM8BitToConst(0x6F, 1),
	SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
	ReturnObjectQueue()
])
