# pylint: disable=C0301,C0103

"""referenced by battle_events BE0098_SMITHY_IS_DEFEATED"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=152,
    script=[
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3aa5be",
        ),
        NewEffectObject(effect=EF0051_DARK_BLUE_BLAST, looping_on=True),
        Layer3On(prop=OVERLAP_ALL, bpp4=True),
        RunSubroutine(["command_0x3a7734"]),
        FadeOutObject(duration=2),
        Layer3Off(prop=OVERLAP_ALL, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        RunSubroutine(["command_0x3a7588"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3aa5d8",
        ),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 12),
        ObjectQueueAtOffsetAndIndex(
            index=48, target_address=0x3A8AC0, identifier="command_0x3aa5e6"
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        ObjectQueueAtOffsetAndIndex(index=50, target_address=0x3A8AC0),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        ObjectQueueAtOffsetAndIndex(index=52, target_address=0x3A8AC0),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        IncAMEM8Bit(0x68),
        JmpIfAMEM8BitNotEqualsConst(0x68, 10, ["command_0x3aa5e6"]),
        RunSubroutine(["command_0x3a757a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x3a7cca"], identifier="queuestart_0x3aa60a"),
        PlaySound(sound=S0111_SLEDGE),
        NewSpriteAtCoords(
            sprite_id=SPR0516_ENEMY_DEFEATED_EXPLOSION_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x3a7cca"], identifier="queuestart_0x3aa61b"),
        PlaySound(sound=S0111_SLEDGE),
        NewSpriteAtCoords(
            sprite_id=SPR0516_ENEMY_DEFEATED_EXPLOSION_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x3a7cca"], identifier="queuestart_0x3aa62c"),
        PlaySound(sound=S0111_SLEDGE),
        NewSpriteAtCoords(
            sprite_id=SPR0516_ENEMY_DEFEATED_EXPLOSION_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3aa63d",
        ),
        NewEffectObject(effect=EF0053_LIGHT_BLUE_BLAST, looping_off=True),
        Layer3On(prop=OVERLAP_ALL, bpp4=True),
        PlaySound(sound=S0110_HUGE_EXPLOSION),
        PauseScriptUntil(condition=SEQ_4BPP_COMPLETE),
        Db(bytearray(b"[\x07\x00")),
        RunSubroutine(["command_0x3a755e"]),
        ReturnObjectQueue(),
    ],
)
