# pylint: disable=C0301,C0103

"""referenced by weapons HurlyGloves"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=318,
    script=[
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=13, identifier="queuestart_0x35f5ec"
        ),
        SetAMEM16BitToConst(0x60, 64384),
        Set7E1xToAMEM16Bit(0x7EE022, 0x60),
        SetAMEM8BitToConst(0x6F, 1),
        IncAMEM8BitByConst(0x6F, 0),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 0, ["command_0x35f615"]),
        SpriteQueue(
            field_object=0,
            destinations=["queuestart_0x35f728"],
            character_slot=True,
            bit_5=True),
        ClearAMEM16Bit(0x60),
        Set7E1xToAMEM8Bit(0x7EE025, 0x60),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35F5E4),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6F, identifier="command_0x35f615"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-6,
            y=-21,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 0, ["command_0x35f633"]),
        NewSpriteAtCoords(
            sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT,
            sequence=4,
            priority=3,
            vram_address=0x6600,
            palette_row=6,
            overwrite_vram=True,
            looping=True,
            mirror_sprite=True,
            overlap_all_sprites=True),
        Jmp(["command_0x35f63c"]),
        NewSpriteAtCoords(
            sprite_id=SPR0096_MARIO_DOLL_SURPRISED,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35f633"),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=9, identifier="command_0x35f63c"
        ),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-4,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 0, ["command_0x35f65c"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0002_MARIO_WALKING_UP_RIGHT, sequence=8, store_to_vram=True
        ),
        PlaySound(sound=S0092_SPEAR_RAIN_SINGLE, identifier="command_0x35f65c"),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        SetAMEM8BitToConst(0x67, 1),
        SetOMEMMainToAMEM8Bit(omem=0x67, amem=0x67),
        RemoveObject(),
        ReturnObjectQueue(),
        PlaySound(sound=S0159_BIG_DEEP_HIT, identifier="queuestart_0x35f66c"),
        SetAMEM16BitToConst(0x60, 64384),
        SetAMEM8BitToConst(0x6F, 1),
        IncAMEM8BitByConst(0x6F, 0),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-4,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 0, ["command_0x35f695"]),
        NewSpriteAtCoords(
            sprite_id=SPR0003_MARIO_SURPRISE_LEFT,
            sequence=6,
            priority=3,
            vram_address=0x6600,
            palette_row=6,
            overwrite_vram=True,
            overlap_all_sprites=True),
        Jmp(["command_0x35f69e"]),
        NewSpriteAtCoords(
            sprite_id=SPR0580_SMALL_MARIO_HURLY_GLOVES,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35f695"),
        ResetTargetMappingMemory(identifier="command_0x35f69e"),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-6,
            y=-21,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=768, arch_height=256),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=18),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 0, ["command_0x35f6c9"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT,
            sequence=4,
            store_to_vram=True,
            looping=True),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=9, identifier="command_0x35f6c9"
        ),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-4,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 0, ["command_0x35f6e9"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0002_MARIO_WALKING_UP_RIGHT, sequence=8, store_to_vram=True
        ),
        PlaySound(sound=S0092_SPEAR_RAIN_SINGLE, identifier="command_0x35f6e9"),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        PlaySound(sound=S0159_BIG_DEEP_HIT),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
        PlaySound(sound=S0159_BIG_DEEP_HIT),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        RemoveObject(),
        ReturnObjectQueue(),
        Db(bytearray(b"\xa6"), identifier="queuestart_0x35f705"),
        SetAMEM16BitTo7E1x(0x60, 0x7EE022),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        NewSpriteAtCoords(
            sprite_id=SPR0096_MARIO_DOLL_SURPRISED,
            sequence=2,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        Pause1Frame(identifier="command_0x35f71b"),
        SetAMEM8BitTo7E1x(0x6F, 0x7EE025),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 1, ["command_0x35f71b"]),
        RemoveObject(),
        ReturnObjectQueue(),
        Db(bytearray(b"\x89"), identifier="queuestart_0x35f728"),
        ReturnSpriteQueue(),
    ])
