# pylint: disable=C0301,C0103

"""referenced by battle_events BE0069_AXEM_RANGERS_ARE_DEFEATED, battle_events BE0018_KNIFE_GUY_GRATE_GUY_PAIR_UP_PIGGY_BACK, battle_events BE0021_JOHNNY_CHALLENGES_MARIO_TO_A_ONE_ON_ONE, battle_events BE0019_KNIFE_GUY_GRATE_GUY_SEPARATE_YIKES_THEY_RE_PRETTY_TOUGH"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=1409,
    script=[
        RunSubroutine(["command_0x3a7760"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0001_MARIO_JUMP_FRONT,
            sequence=9,
            store_to_vram=True,
            store_palette=True,
        ),
        SpriteSequence(sequence=9, mirror=True),
        RunSubroutine(["command_0x3a7218"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT,
            sequence=1,
            store_to_vram=True,
            store_palette=True,
        ),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=7, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        SpriteSequence(sequence=7, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        RunSubroutine(["command_0x3a75c0"]),
        RunSubroutine(["command_0x3a7776"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0002_MARIO_WALKING_UP_RIGHT,
            sequence=3,
            store_to_vram=True,
            store_palette=True,
        ),
        RunSubroutine(["command_0x3a7242"]),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a7781"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0001_MARIO_JUMP_FRONT,
            sequence=9,
            store_to_vram=True,
            store_palette=True,
        ),
        RunSubroutine(["command_0x3a8142"]),
        RunSubroutine(["command_0x3a72e6"]),
        RunSubroutine(["command_0x3a819c"]),
        RunSubroutine(["command_0x3a72e6"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT,
            sequence=1,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        RunSubroutine(["command_0x3a81f6"]),
        RunSubroutine(["command_0x3a727a"]),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        SpriteSequence(sequence=7, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=7, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0003_MARIO_SURPRISE_LEFT,
            sequence=4,
            store_to_vram=True,
            looping=True,
            store_palette=True,
        ),
        RunSubroutine(["command_0x3a7797"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT,
            sequence=1,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        SpriteSequence(sequence=6, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=6, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a7606"]),
        RunSubroutine(["command_0x3a77ad"]),
        SpriteSequence(sequence=10, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0002_MARIO_WALKING_UP_RIGHT,
            sequence=3,
            store_to_vram=True,
            store_palette=True,
        ),
        RunSubroutine(["command_0x3a7257"]),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a773f"]),
        SpriteSequence(sequence=0, looping_on=True),
        RunSubroutine(["command_0x3a7203"]),
        DisplayMessage(BATTLE_DIALOGUE, 82),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0019_MALLOW_WALKING_DOWN_LEFT,
            sequence=9,
            store_to_vram=True,
            store_palette=True,
        ),
        SpriteSequence(sequence=9, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=9, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a7596"]),
        RunSubroutine(["command_0x3a7776"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0020_MALLOW_WALKING_UP_RIGHT,
            sequence=3,
            store_to_vram=True,
            store_palette=True,
        ),
        RunSubroutine(["command_0x3a7242"]),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a7734"]),
        SpriteSequence(sequence=0, looping_on=True),
        RunSubroutine(["command_0x3a81b0"]),
        RunSubroutine(["command_0x3a727a"]),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0019_MALLOW_WALKING_DOWN_LEFT,
            sequence=1,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        DisplayMessage(BATTLE_DIALOGUE, 85),
        SpriteSequence(sequence=4, looping_on=True),
        RunSubroutine(["command_0x3a733e"]),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a75dc"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SpriteSequence(sequence=1, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_on=True),
        RunSubroutine(["command_0x3a8192"]),
        RunSubroutine(["command_0x3a727a"]),
        SpriteSequence(sequence=1, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=10, looping_off=True),
        RunSubroutine(["command_0x3a778c"]),
        DisplayMessage(BATTLE_DIALOGUE, 87),
        SpriteSequence(sequence=4, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=4, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        RunSubroutine(["command_0x3a75f8"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=6, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=6, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        RunSubroutine(["command_0x3a77ad"]),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0020_MALLOW_WALKING_UP_RIGHT,
            sequence=3,
            store_to_vram=True,
            store_palette=True,
        ),
        RunSubroutine(["command_0x3a7257"]),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a77ce"]),
        DisplayMessage(BATTLE_DIALOGUE, 90),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a7630"]),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7755"]),
        SpriteSequence(sequence=0, looping_on=True),
        RunSubroutine(["command_0x3a7203"]),
        DisplayMessage(BATTLE_DIALOGUE, 83),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a75b2"]),
        RunSubroutine(["command_0x3a7776"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0026_GENO_WALKING_UP_RIGHT,
            sequence=3,
            store_to_vram=True,
            store_palette=True,
        ),
        RunSubroutine(["command_0x3a7242"]),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a7781"]),
        SpriteSequence(sequence=0, looping_on=True),
        RunSubroutine(["command_0x3a8174"]),
        RunSubroutine(["command_0x3a727a"]),
        SpriteSequence(sequence=0, looping_off=True),
        DisplayMessage(BATTLE_DIALOGUE, 86),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0025_GENO_WALKING_DOWN_LEFT,
            sequence=9,
            store_to_vram=True,
            store_palette=True,
        ),
        SpriteSequence(sequence=9, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=9, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a75ea"]),
        RunSubroutine(["command_0x3a7797"]),
        SpriteSequence(sequence=1, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=7, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=7, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_off=True),
        RunSubroutine(["command_0x3a77ad"]),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        DisplayMessage(BATTLE_DIALOGUE, 88),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0026_GENO_WALKING_UP_RIGHT,
            sequence=3,
            store_to_vram=True,
            store_palette=True,
        ),
        RunSubroutine(["command_0x3a7257"]),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogClosed(),
        DisplayMessage(BATTLE_DIALOGUE, 89),
        SpriteSequence(sequence=5, looping_off=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a763e"]),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=-32,
            y=16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetObjectMappingMemory(),
        DisplayMessage(BATTLE_DIALOGUE, 71),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a756c"]),
        RunSubroutine(["command_0x3a7734"]),
        DisplayMessage(BATTLE_DIALOGUE, 72),
        SpriteSequence(sequence=5),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=5),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a7588"]),
        RunSubroutine(["command_0x3a71da"]),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"]),
        DisplayMessage(BATTLE_DIALOGUE, 81),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0019_MALLOW_WALKING_DOWN_LEFT,
            sequence=9,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=9, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0020_MALLOW_WALKING_UP_RIGHT,
            sequence=0,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a757a"]),
        RunSubroutine(["command_0x3a773f"]),
        RunSubroutine(["command_0x3a71da"]),
        ReturnSpriteQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_INITIAL_POSITION, x=0, y=0, z=-256, set_x=True
        ),
        RunSubroutine(["command_0x3a7729"]),
        DisplayMessage(BATTLE_DIALOGUE, 63),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=129,
            start_position=1024,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a757a"]),
        MoveObject(
            speed=129,
            start_position=-1025,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=184,
            y=128,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SpriteSequence(sequence=1, looping_on=True),
        RunSubroutine(["command_0x3a8584"]),
        RunSubroutine(["command_0x3a7286"]),
        RunSubroutine(["command_0x3a71ee"]),
        SpriteSequence(sequence=1, looping_off=True),
        RunSubroutine(["command_0x3a7734"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=184,
            y=128,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SpriteSequence(sequence=1, looping_on=True),
        RunSubroutine(["command_0x3a8570"]),
        RunSubroutine(["command_0x3a7286"]),
        RunSubroutine(["command_0x3a71ee"]),
        SpriteSequence(sequence=1, looping_off=True),
        RunSubroutine(["command_0x3a7734"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=184,
            y=128,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SpriteSequence(sequence=1, looping_on=True),
        RunSubroutine(["command_0x3a855c"]),
        RunSubroutine(["command_0x3a7286"]),
        RunSubroutine(["command_0x3a71ee"]),
        SpriteSequence(sequence=1, looping_off=True),
        RunSubroutine(["command_0x3a756c"]),
        RunSubroutine(["command_0x3a7734"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        DisplayMessage(BATTLE_DIALOGUE, 64, identifier="queuestart_0x3abf13"),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a756c"]),
        RunSubroutine(["command_0x3a7734"]),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=170,
            y=129,
            z=-48,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7292"]),
        ClearAMEM8Bit(0x60),
        ClearAMEM8Bit(0x61),
        ClearAMEM8Bit(0x62),
        SetAMEM8BitToConst(0x60, 170),
        SetAMEM8BitToConst(0x61, 129),
        SetAMEM8BitToConst(0x62, 48),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        Set7E5xToAMEM8Bit(0x7E003D, 0x62),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3abf52"),
        DisplayMessage(BATTLE_DIALOGUE, 66),
        SpriteSequence(sequence=3),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        RunSubroutine(["command_0x3a757a"]),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=168,
            y=128,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7292"]),
        ClearAMEM8Bit(0x60),
        ClearAMEM8Bit(0x61),
        ClearAMEM8Bit(0x62),
        SetAMEM8BitToConst(0x60, 168),
        SetAMEM8BitToConst(0x61, 128),
        SetAMEM8BitToConst(0x62, 0),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        Set7E5xToAMEM8Bit(0x7E003D, 0x62),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        DisplayMessage(BATTLE_DIALOGUE, 65, identifier="queuestart_0x3abf91"),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a756c"]),
        ClearAMEM8Bit(0x60),
        ClearAMEM8Bit(0x61),
        ClearAMEM8Bit(0x62),
        SetAMEM8BitToConst(0x60, 151),
        SetAMEM8BitToConst(0x61, 119),
        SetAMEM8BitToConst(0x62, 0),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        Set7E5xToAMEM8Bit(0x7E003D, 0x62),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=151,
            y=119,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7292"]),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3abfca"),
        ClearAMEM8Bit(0x60),
        ClearAMEM8Bit(0x61),
        ClearAMEM8Bit(0x62),
        SetAMEM8BitToConst(0x60, 199),
        SetAMEM8BitToConst(0x61, 143),
        SetAMEM8BitToConst(0x62, 0),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        Set7E5xToAMEM8Bit(0x7E003D, 0x62),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=199,
            y=143,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7292"]),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3ac00a"], identifier="queuestart_0x3abffb"),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3ac00a"], identifier="queuestart_0x3abfff"),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3ac00a"], identifier="queuestart_0x3ac003"),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        SpriteSequence(sequence=0, looping_on=True, identifier="command_0x3ac00a"),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        SpriteSequence(sequence=1, looping_on=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-1025,
            end_position=-1025,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=512,
            end_position=512,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=17,
            start_position=-1025,
            end_position=0,
            apply_to_x=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=65,
            start_position=-1025,
            end_position=1024,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
        DisplayMessage(BATTLE_DIALOGUE, 91, identifier="queuestart_0x3ac063"),
        RunSubroutine(["command_0x3a722d"]),
        PauseScriptUntilDialogClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        DisplayMessage(BATTLE_DIALOGUE, 92),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a756c"]),
        RunSubroutine(["command_0x3a7734"]),
        DisplayMessage(BATTLE_DIALOGUE, 93),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=3),
        PlaySound(sound=S0004_JUMP),
        RunSubroutine(["command_0x3a7374"]),
        ResetSpriteSequence(),
        PauseScriptUntilDialogClosed(),
        DisplayMessage(BATTLE_DIALOGUE, 94),
        RunSubroutine(["command_0x3a733e"]),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a7588"]),
        RunSubroutine(["command_0x3a71da"]),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a773f"], identifier="queuestart_0x3ac09f"),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=204,
            y=62,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0331_BANDANA_BLUE,
            sequence=0,
            priority=2,
            vram_address=0x7800,
            palette_row=12,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=FactoryChief, position=1, bit_7=True),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=184,
            y=52,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=96),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=154,
            y=67,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=128),
        PauseScriptUntil(condition=0x01),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=104,
            y=112,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=352),
        PauseScriptUntil(condition=0x01),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        RunSubroutine(["command_0x3a7374"]),
        Db(bytearray(b"\x16"), identifier="command_0x3ac0f9"),
        Pause1Frame(),
        SetAMEM8BitTo7E1x(0x67, 0x7EE003),
        JmpIfAMEMBitsSet(0x67, [0], ["command_0x3ac141"]),
        Pause1Frame(),
        SetAMEMToRandom(amem=0x68, upper_bound=100),
        JmpIfAMEM8BitEqualsConst(0x68, 0, ["command_0x3ac125"]),
        JmpIfAMEM8BitEqualsConst(0x68, 1, ["command_0x3ac12f"]),
        JmpIfAMEM8BitEqualsConst(0x68, 2, ["command_0x3ac135"]),
        JmpIfAMEM8BitEqualsConst(0x68, 3, ["command_0x3ac13b"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        Jmp(["command_0x3ac0f9"]),
        SpriteSequence(
            sequence=0, looping_on=True, mirror=True, identifier="command_0x3ac125"
        ),
        RunSubroutine(["command_0x3a7390"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        Jmp(["command_0x3ac0f9"]),
        SpriteSequence(sequence=2, mirror=True, identifier="command_0x3ac12f"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3ac0f9"]),
        SpriteSequence(sequence=3, mirror=True, identifier="command_0x3ac135"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3ac0f9"]),
        SpriteSequence(sequence=4, mirror=True, identifier="command_0x3ac13b"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3ac0f9"]),
        Pause1Frame(identifier="command_0x3ac141"),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        Jmp(["command_0x3ac141"]),
    ],
)
