# pylint: disable=C0301,C0103

"""referenced by monster_attacks PhysicalAttack56"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=130,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=8,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x356c06"),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=0,
            apply_to_y=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        ResetObjectMappingMemory(),
        Jmp(["command_0x356af4"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=10,
            y=-264,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x356c20"),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=0,
            apply_to_y=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        ResetObjectMappingMemory(),
        Jmp(["command_0x356af4"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-4,
            y=-240,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x356c3a"),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=0,
            apply_to_y=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        ResetObjectMappingMemory(),
        Jmp(["command_0x356af4"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x356c54"),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=0,
            apply_to_y=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        ResetObjectMappingMemory(),
        Jmp(["command_0x356af4"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-8,
            y=-263,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x356c6e"),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=0,
            apply_to_y=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        ResetObjectMappingMemory(),
        Jmp(["command_0x356af4"]),
    ])
