# pylint: disable=C0301,C0103

"""referenced by battle_events BE0021_JOHNNY_CHALLENGES_MARIO_TO_A_ONE_ON_ONE"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=168,
    script=[
        RunSubroutine(["command_0x3a773f"], identifier="queuestart_0x3ac148"),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=236,
            y=46,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        NewSpriteAtCoords(
            sprite_id=SPR0331_BANDANA_BLUE,
            sequence=0,
            priority=2,
            vram_address=0x7A00,
            palette_row=12,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        SummonMonster(monster=FactoryChief, position=1, bit_7=True),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=216,
            y=56,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=96),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=186,
            y=71,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=128),
        PauseScriptUntil(condition=0x01),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=136,
            y=96,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=352),
        PauseScriptUntil(condition=0x01),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        RunSubroutine(["command_0x3a7374"]),
        Db(bytearray(b"\x16"), identifier="command_0x3ac1a2"),
        Pause1Frame(),
        SetAMEM8BitTo7E1x(0x67, 0x7EE003),
        JmpIfAMEMBitsSet(0x67, [0], ["command_0x3ac1ea"]),
        Pause1Frame(),
        SetAMEMToRandom(amem=0x68, upper_bound=100),
        JmpIfAMEM8BitEqualsConst(0x68, 0, ["command_0x3ac1ce"]),
        JmpIfAMEM8BitEqualsConst(0x68, 1, ["command_0x3ac1d8"]),
        JmpIfAMEM8BitEqualsConst(0x68, 2, ["command_0x3ac1de"]),
        JmpIfAMEM8BitEqualsConst(0x68, 3, ["command_0x3ac1e4"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        Jmp(["command_0x3ac1a2"]),
        SpriteSequence(
            sequence=0, looping_on=True, mirror=True, identifier="command_0x3ac1ce"
        ),
        RunSubroutine(["command_0x3a7390"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        Jmp(["command_0x3ac1a2"]),
        SpriteSequence(sequence=2, mirror=True, identifier="command_0x3ac1d8"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3ac1a2"]),
        SpriteSequence(sequence=3, mirror=True, identifier="command_0x3ac1de"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3ac1a2"]),
        SpriteSequence(sequence=4, mirror=True, identifier="command_0x3ac1e4"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3ac1a2"]),
        Pause1Frame(identifier="command_0x3ac1ea"),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        Jmp(["command_0x3ac1ea"]),
    ])
