# pylint: disable=C0301,C0103

"""referenced by ally_spells Jump"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=325,
    script=[
        StartTrackingAllyButtonInputs(identifier="queuestart_0x359252"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        SetAMEM8BitToOMEMMain(amem=0x69, omem=0x6D),
        JmpIfAMEM8BitEqualsConst(0x69, 64, ["command_0x359271"]),
        NewSpriteAtCoords(
            sprite_id=SPR0581_MARIO_JUMP_ATTACKS,
            sequence=4,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            mirror_sprite=True,
            invert_sprite=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        Jmp(["command_0x35927a"]),
        NewSpriteAtCoords(
            sprite_id=SPR0039_RED_SCARECROW,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            invert_sprite=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
            identifier="command_0x359271"),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=112,
            y=160,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x35927a"),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=128),
        PauseScriptUntil(condition=0x07),
        PlaySound(sound=S0004_JUMP),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=128,
            y=-64,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=2304, arch_height=0),
        PauseScriptUntil(condition=0x07),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        JmpIfAMEM8BitEqualsConst(0x69, 64, ["command_0x3592cc"]),
        NewSpriteAtCoords(
            sprite_id=SPR0582_MARIO_CROUCH,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            invert_sprite=True,
            overlap_all_sprites=True),
        Db(bytearray(b" \x89\x1e\x00")),
        JmpIfAMEM8BitNotEqualsConst(0x69, 76, ["command_0x3592d5"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0581_MARIO_JUMP_ATTACKS,
            sequence=15,
            store_to_vram=True,
            looping=True),
        Jmp(["command_0x3592d5"]),
        NewSpriteAtCoords(
            sprite_id=SPR0039_RED_SCARECROW,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            invert_sprite=True,
            overlap_all_sprites=True,
            identifier="command_0x3592cc"),
        ClearAMEM16Bit(0x60, identifier="command_0x3592d5"),
        ClearAMEM8Bit(0x6A),
        ClearAMEM16Bit(0x6C),
        ClearAMEM8Bit(0x6F),
        PlaySound(sound=S0086_LONG_FALL),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35924C),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35924C),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35924C),
        RunSubroutine(["command_0x35c71f"]),
        Pause1Frame(identifier="command_0x3592f6"),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 3, ["command_0x3592f6"]),
        PlaySound(sound=S0056_SUPER_JUMP_HIT_1_UP),
        Db(bytearray(b"\x8d")),
        SetAMEMToAMEM8Bit(dest_amem=0x61, amem=0x6D),
        TimingForOneTieredButtonPress(
            end_accepting_input=45,
            start_accepting_input=0,
            partial_start=39,
            perfect_start=44,
            perfect_end=45,
            destinations=["147"]),
        NewEffectObject(effect=EF0036_BLANK_WHITE_FLASH__2BPP_, playback_off=True),
        Layer3On(prop=TRANSPARENCY_OFF),
        Db(bytearray(b"\xba\x03\xe8\x00")),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=1, y=1443, z=2592),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=8332, y=268, z=8704),
        Db(bytearray(b"l")),
        Db(bytearray(b"n")),
        NewSpriteAtCoords(
            sprite_id=SPR0384_APPRENTICE,
            sequence=0,
            priority=0,
            vram_address=0x4584,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-4,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        JmpIfAMEM8BitEqualsConst(0x69, 64, ["command_0x359344"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0581_MARIO_JUMP_ATTACKS, sequence=4, store_to_vram=True
        ),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x359344"),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X08, speed=1280, arch_height=176),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        PauseScriptUntilAMEMBitsSet(0x6F, [0, 1, 2, 3, 4, 5, 6, 7]),
        JmpIfAMEM8BitNotEqualsConst(0x6A, 1, ["command_0x359367"]),
        Db(bytearray(b"\xa8\x02\x00")),
        Layer3Off(prop=TRANSPARENCY_OFF),
        Pause2Frames(),
        ClearEffectIndex(),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6C, identifier="command_0x359367"),
        Pause1Frame(),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35936e"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-192,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        Db(bytearray(b"\x83\x83")),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-4,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=2048, arch_height=0),
        PauseScriptUntil(condition=0x07),
        RemoveObject(),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        IncAMEM8Bit(0x6C),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnObjectQueue(),
    ])
