# referenced by ally_spells Ultra Jump

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=543,
    script=[
        StartTrackingAllyButtonInputs(identifier="queuestart_0x3599ea"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SetAMEM8BitToOMEMMain(amem=0x69, omem=0x6D),
        JmpIfAMEM8BitEqualsConst(0x69, 64, ["command_0x359a09"]),
        NewSpriteAtCoords(
            sprite_id=SPR0581_MARIO_JUMP_ATTACKS,
            sequence=4,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            mirror_sprite=True,
            invert_sprite=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        Jmp(["command_0x359a12"]),
        NewSpriteAtCoords(
            sprite_id=SPR0039_RED_SCARECROW,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            invert_sprite=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
            identifier="command_0x359a09",
        ),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=112,
            y=160,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x359a12",
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=128),
        PauseScriptUntil(condition=0x07),
        PlaySound(sound=S0004_JUMP),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=128,
            y=-64,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=2304, arch_height=0),
        PauseScriptUntil(condition=0x07),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        JmpIfAMEM8BitEqualsConst(0x69, 64, ["command_0x359a64"]),
        NewSpriteAtCoords(
            sprite_id=SPR0582_MARIO_CROUCH,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            invert_sprite=True,
            overlap_all_sprites=True,
        ),
        Db(bytearray(b" \x88\x1e\x00")),
        JmpIfAMEM8BitNotEqualsConst(0x68, 76, ["command_0x359a6d"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0581_MARIO_JUMP_ATTACKS,
            sequence=15,
            store_to_vram=True,
            looping=True,
        ),
        Jmp(["command_0x359a6d"]),
        NewSpriteAtCoords(
            sprite_id=SPR0039_RED_SCARECROW,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            invert_sprite=True,
            overlap_all_sprites=True,
            identifier="command_0x359a64",
        ),
        ClearAMEM16Bit(0x60, identifier="command_0x359a6d"),
        ClearAMEM8Bit(0x6A),
        ClearAMEM8Bit(0x6B),
        ClearAMEM8Bit(0x6C),
        PlaySound(sound=S0086_LONG_FALL),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35924C),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35924C),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35924C),
        Pause1Frame(identifier="command_0x359a8b"),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 3, ["command_0x359a8b"]),
        PlaySound(sound=S0018_SUPER_JUMP_HIT_1),
        JmpIfAMEM8BitEqualsConst(0x69, 64, ["command_0x359a9b"]),
        Db(bytearray(b"\x89")),
        ResetTargetMappingMemory(identifier="command_0x359a9b"),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-4,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        TimingForOneBinaryButtonPress(
            end_accepting_input=60,
            start_accepting_input=0,
            timed_hit_ends=60,
            destinations=["command_0x359b8e"],
        ),
        ClearAMEM8Bit(0x6F),
        Db(bytearray(b"?\x80\x15\x00\x00\x84")),
        SetAMEM8BitToConst(0x6A, 1),
        IncAMEM8Bit(0x6B),
        JmpIfAMEM8BitEqualsConst(0x69, 64, ["command_0x359ad1"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0581_MARIO_JUMP_ATTACKS, sequence=4, store_to_vram=True
        ),
        JmpIfAMEM8BitNotEqualsConst(0x68, 76, ["command_0x359ad1"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0581_MARIO_JUMP_ATTACKS,
            sequence=15,
            store_to_vram=True,
            looping=True,
        ),
        RunSubroutine(["command_0x359bd5"], identifier="command_0x359ad1"),
        PlaySound(sound=S0058_SUPER_JUMP_HIT_2),
        TimingForOneBinaryButtonPress(
            end_accepting_input=50,
            start_accepting_input=0,
            timed_hit_ends=50,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        PlaySound(sound=S0059_SUPER_JUMP_HIT_3),
        TimingForOneBinaryButtonPress(
            end_accepting_input=40,
            start_accepting_input=0,
            timed_hit_ends=40,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        PlaySound(sound=S0041_SUPER_JUMP_HIT_4),
        TimingForOneBinaryButtonPress(
            end_accepting_input=30,
            start_accepting_input=0,
            timed_hit_ends=30,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        PlaySound(sound=S0050_SUPER_JUMP_HIT_5),
        TimingForOneBinaryButtonPress(
            end_accepting_input=26,
            start_accepting_input=0,
            timed_hit_ends=26,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        PlaySound(sound=S0056_SUPER_JUMP_HIT_1_UP),
        TimingForOneBinaryButtonPress(
            end_accepting_input=22,
            start_accepting_input=0,
            timed_hit_ends=22,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        PlaySound(sound=S0056_SUPER_JUMP_HIT_1_UP),
        TimingForOneBinaryButtonPress(
            end_accepting_input=18,
            start_accepting_input=0,
            timed_hit_ends=18,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        PlaySound(sound=S0056_SUPER_JUMP_HIT_1_UP),
        TimingForOneBinaryButtonPress(
            end_accepting_input=14,
            start_accepting_input=0,
            timed_hit_ends=14,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        PlaySound(sound=S0056_SUPER_JUMP_HIT_1_UP),
        TimingForOneBinaryButtonPress(
            end_accepting_input=10,
            start_accepting_input=0,
            timed_hit_ends=10,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        PlaySound(sound=S0056_SUPER_JUMP_HIT_1_UP),
        TimingForOneBinaryButtonPress(
            end_accepting_input=9,
            start_accepting_input=0,
            timed_hit_ends=9,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        PlaySound(sound=S0056_SUPER_JUMP_HIT_1_UP),
        TimingForOneBinaryButtonPress(
            end_accepting_input=8,
            start_accepting_input=0,
            timed_hit_ends=8,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        PlaySound(sound=S0056_SUPER_JUMP_HIT_1_UP),
        TimingForOneBinaryButtonPress(
            end_accepting_input=7,
            start_accepting_input=0,
            timed_hit_ends=7,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        PlaySound(sound=S0056_SUPER_JUMP_HIT_1_UP),
        TimingForOneBinaryButtonPress(
            end_accepting_input=6,
            start_accepting_input=0,
            timed_hit_ends=6,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        PlaySound(sound=S0056_SUPER_JUMP_HIT_1_UP),
        TimingForOneBinaryButtonPress(
            end_accepting_input=5,
            start_accepting_input=0,
            timed_hit_ends=5,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        PlaySound(sound=S0056_SUPER_JUMP_HIT_1_UP),
        TimingForOneBinaryButtonPress(
            end_accepting_input=4,
            start_accepting_input=0,
            timed_hit_ends=4,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        PlaySound(sound=S0056_SUPER_JUMP_HIT_1_UP),
        TimingForOneBinaryButtonPress(
            end_accepting_input=3,
            start_accepting_input=0,
            timed_hit_ends=3,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        PlaySound(sound=S0056_SUPER_JUMP_HIT_1_UP, identifier="command_0x359b79"),
        Pause1Frame(),
        JmpIfAMEM8BitGreaterOrEqualThanConst(0x6B, 100, ["command_0x359b8e"]),
        TimingForOneBinaryButtonPress(
            end_accepting_input=2,
            start_accepting_input=0,
            timed_hit_ends=2,
            destinations=["command_0x359b8e"],
        ),
        RunSubroutine(["command_0x359bc7"]),
        Jmp(["command_0x359b79"]),
        JmpIfAMEM8BitEqualsConst(
            0x69, 64, ["command_0x359b9a"], identifier="command_0x359b8e"
        ),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0581_MARIO_JUMP_ATTACKS, sequence=4, store_to_vram=True
        ),
        ClearAMEM8Bit(0x6F, identifier="command_0x359b9a"),
        Db(bytearray(b"?\x80\x15\x00\x00\x84")),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X08, speed=1280, arch_height=176),
        PauseScriptUntilAMEMBitsSet(0x6F, [0, 1, 2, 3, 4, 5, 6, 7]),
        EndTrackingAllyButtonInputs(),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6C),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6C),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=1),
        RemoveObject(),
        ReturnObjectQueue(),
        IncAMEM8Bit(0x6B, identifier="command_0x359bc7"),
        ClearAMEM8Bit(0x6F),
        Db(bytearray(b"?\x80\x15\x00\x00\x84")),
        RunSubroutine(["command_0x359bd5"]),
        ReturnSubroutine(),
        MoveObject(
            speed=193,
            start_position=-4865,
            end_position=0,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
            identifier="command_0x359bd5",
        ),
        Pause1Frame(),
        Db(bytearray(b"\x12\x81")),
        ResetTargetMappingMemory(),
        SetAMEM16BitTo7E1x(0x62, 0x7E078E),
        Set7E1xToAMEM16Bit(0x7E0730, 0x62),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=0,
            z=-208,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=193,
            start_position=0,
            end_position=4608,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Pause1Frame(),
        SetAMEM40ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=0, z=0, set_x=True),
        PauseScriptUntil(condition=0x01),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
    ],
)
