# pylint: disable=C0301,C0103

"""referenced by battle_events BE0069_AXEM_RANGERS_ARE_DEFEATED, battle_events BE0021_JOHNNY_CHALLENGES_MARIO_TO_A_ONE_ON_ONE, battle_events BE0032_BUNDT_MOVES_AGAIN_BOTH_COOKS_RUN_AWAY, battle_events BE0016_CROCO_RETURNS_ITEMS_ENOUGH_HERE_S_YOUR_JUNK, battle_events BE0007_COUNTDOWN_RUNS_SCHEDULE_1_00_3_00_5_00_6_00_7_00, battle_events BE0082_SMITHY_1ST_FORM_IS_BEATEN_GROUND_SHAKES_ETC"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=488,
    script=[
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=768, arch_height=384),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ReturnSubroutine(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-769,
            end_position=-769,
            apply_to_z=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=1,
            start_position=768,
            end_position=768,
            apply_to_z=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-769,
            end_position=-769,
            apply_to_z=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=1,
            start_position=768,
            end_position=768,
            apply_to_z=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
        ResetTargetMappingMemory(identifier="command_0x3a7374"),
        MoveObject(
            speed=81,
            start_position=-1281,
            end_position=0,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=81,
            start_position=0,
            end_position=1280,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=129,
            start_position=-2049,
            end_position=0,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=129,
            start_position=0,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
        ResetTargetMappingMemory(identifier="command_0x3a73ac"),
        MoveObject(
            speed=1,
            start_position=-1025,
            end_position=-1025,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=1,
            start_position=1024,
            end_position=1024,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        ResetObjectMappingMemory(),
        SetAMEM8BitTo7E1x(0x68, 0x7EE01F),
        JmpIfAMEMBitsClear(0x68, [0], ["command_0x3a73ac"]),
        ReturnSubroutine(),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=1, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        RunSubroutine(["command_0x3a7374"]),
        SpriteSequence(sequence=1, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        RunSubroutine(["command_0x3a7374"]),
        ReturnSubroutine(),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=1, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        RunSubroutine(["command_0x3a7374"]),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=1, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        RunSubroutine(["command_0x3a7374"]),
        ReturnSubroutine(),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=1, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        RunSubroutine(["command_0x3a7374"]),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=1, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        RunSubroutine(["command_0x3a7374"]),
        ReturnSubroutine(),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        RunSubroutine(["command_0x3a7374"]),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        RunSubroutine(["command_0x3a7374"]),
        ReturnSubroutine(),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        RunSubroutine(["command_0x3a7374"]),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        RunSubroutine(["command_0x3a7374"]),
        ReturnSubroutine(),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        RunSubroutine(["command_0x3a7374"]),
        SpriteSequence(sequence=1, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        RunSubroutine(["command_0x3a7374"]),
        ReturnSubroutine(),
    ],
)
