# pylint: disable=C0301,C0103

"""referenced by ally_spells Sleepy Time"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=110,
    script=[
        StartTrackingAllyButtonInputs(identifier="queuestart_0x35a421"),
        TimingForRotationCount(
            end_accepting_input=120, start_accepting_input=0, max_presses=28
        ),
        SetOMEMMainToAMEM8Bit(omem=0x62, amem=0x62),
        EndTrackingAllyButtonInputs(),
        ReturnObjectQueue(),
        ResetTargetMappingMemory(identifier="queuestart_0x35a42c"),
        SetAMEM16BitToOMEMMain(amem=0x60, omem=0x64),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=2,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Pause1Frame(identifier="command_0x35a441"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 255, ["command_0x35a441"]),
        Db(bytearray(b"\x83\x83")),
        Pause1Frame(identifier="command_0x35a44e"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 35, ["command_0x35a44e"]),
        RemoveObject(),
        ReturnObjectQueue(),
        MoveObject(
            speed=81,
            start_position=0,
            end_position=1536,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
            identifier="command_0x35a45b",
        ),
        PauseScriptUntil(condition=0x07),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=129,
            start_position=-1025,
            end_position=1024,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=65,
            start_position=-257,
            end_position=256,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        IncAMEM8Bit(0x6C),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnSubroutine(),
    ],
)
