# pylint: disable=C0301,C0103

"""referenced by ally_spells Psych Bomb, ally_spells Bowser Crush"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=543,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35a98e",
        ),
        Db(bytearray(b" \x8d@\x00")),
        JmpIfAMEM8BitEqualsConst(0x6D, 64, ["command_0x35a9ac"]),
        NewSpriteAtCoords(
            sprite_id=SPR0012_TOADSTOOL_FALLEN_CRYING,
            sequence=2,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            param_2_and_0x10=True,
            invert_sprite=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        Jmp(["command_0x35a9b5"]),
        NewSpriteAtCoords(
            sprite_id=SPR0039_RED_SCARECROW,
            sequence=4,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            param_2_and_0x10=True,
            invert_sprite=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
            identifier="command_0x35a9ac",
        ),
        Db(bytearray(b" \x80\x10\x00"), identifier="command_0x35a9b5"),
        JmpIfAMEM8BitGreaterOrEqualThanConst(0x60, 31, ["command_0x35a9c3"]),
        DisplayMessage(BATTLE_MESSAGE, 41),
        PauseScriptUntilDialogClosed(),
        Db(bytearray(b" \x8d@\x00"), identifier="command_0x35a9c3"),
        JmpIfAMEM8BitEqualsConst(0x6D, 64, ["command_0x35a9d2"]),
        SpriteSequence(sequence=2),
        Jmp(["command_0x35a9d4"]),
        SpriteSequence(sequence=4, identifier="command_0x35a9d2"),
        PlaySound(sound=S0088_TICKING_BOMB, identifier="command_0x35a9d4"),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6F),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6F),
        Set7E1xToAMEM8Bit(0x7EE021, 0x6F),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35A97C),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35A97C),
        ClearAMEM8Bit(0x6E),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35A97C),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35A97C),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        JmpIfAMEM8BitEqualsConst(0x6D, 64, ["command_0x35aa03"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0008_TOADSTOOL_WALKING_UP_RIGHT, sequence=0, store_to_vram=True
        ),
        SetAMEM8BitToConst(0x6F, 1, identifier="command_0x35aa03"),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        Pause1Frame(),
        RemoveObject(),
        ReturnObjectQueue(),
        StartTrackingAllyButtonInputs(identifier="queuestart_0x35aa0e"),
        TimingForButtonMashUnknown(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        TimingForButtonMashCount(max_presses=16),
        EndTrackingAllyButtonInputs(),
        ReturnObjectQueue(),
        Pause1Frame(identifier="queuestart_0x35aa18"),
        SetAMEM8BitTo7E1x(0x6D, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 1, ["queuestart_0x35aa18"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=176,
            y=124,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        DoMaskEffect(DOME_MASK),
        SetMaskCoords((1, 0), (-113, 8), (32, 13), (2, 0)),
        Db(bytearray(b"\x1d")),
        Db(bytearray(b" \xe0 \n")),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=2570, y=14882, z=71),
        SetAMEM8BitToAMEM(amem=0x6B, source_amem=0xA8),
        IncAMEM8Bit(0x6B),
        SetAMEMToAMEM8Bit(dest_amem=0xA8, amem=0x6B),
        JmpIfAMEM8BitNotEqualsConst(0x6B, 70, ["170"]),
        SetAMEM16BitToAMEM(amem=0x68, source_amem=0x8A),
        Db(bytearray(b"\xc5")),
        Pause1Frame(identifier="command_0x35aa59"),
        SetAMEM8BitTo7E1x(0x6C, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 10, ["command_0x35aa59"]),
        SetAMEM8BitToConst(0x6C, 20),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6C),
        Pause1Frame(identifier="command_0x35aa6c"),
        SetAMEM8BitTo7E1x(0x6D, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 30, ["command_0x35aa6c"]),
        SetAMEMToAMEM16Bit(dest_amem=0x8A, amem=0x68),
        Db(bytearray(b"\x90")),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35aa87",
        ),
        NewEffectObject(effect=EF0025_PSYCH_BOMB__BG_, playback_off=True),
        Pause1Frame(identifier="command_0x35aa92"),
        SetAMEM8BitTo7E1x(0x6E, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 2, ["command_0x35aa92"]),
        Layer3On(prop=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        MoveObject(
            speed=1,
            start_position=768,
            end_position=768,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-769,
            end_position=-769,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Pause1Frame(identifier="command_0x35aaaf"),
        SetAMEM8BitTo7E1x(0x6C, 0x7EE020),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 20, ["command_0x35aaaf"]),
        ResetObjectMappingMemory(),
        Layer3Off(prop=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        ClearEffectIndex(),
        SetAMEM8BitToConst(0x6D, 30),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6D),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=56, identifier="queuestart_0x35aac7"
        ),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=5,
            y=-20,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0785_SPRITZ_BOMB,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=160,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1536, arch_height=256),
        PlaySound(sound=S0112_SWING),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6C),
        ClearAMEM8Bit(0x6D),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35A97C),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=9),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35A97C),
        SetAMEM8BitToConst(0x6F, 1),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6F),
        ClearAMEM8Bit(0x6E),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x35A97C),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=9, identifier="command_0x35ab18"
        ),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35A97C),
        IncAMEM8Bit(0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 20, ["command_0x35ab18"]),
        Pause1Frame(identifier="command_0x35ab28"),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 22, ["command_0x35ab28"]),
        SetAMEM8BitToConst(0x6F, 1),
        Set7E1xToAMEM8Bit(0x7EE021, 0x6F),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        SetAMEM8BitToConst(0x6E, 10),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6E),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        RemoveObject(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35aba5"], identifier="queuestart_0x35ab48"),
        MoveObject(
            speed=1,
            start_position=1792,
            end_position=1792,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        PlaySound(sound=S0012_BOMB_EXPLOSION),
        ResetObjectMappingMemory(),
        RemoveObject(),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        IncAMEM8Bit(0x6D),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=18, identifier="queuestart_0x35ab66"
        ),
        RunSubroutine(["command_0x35abec"], identifier="command_0x35ab6a"),
        ClearAMEM8Bit(0x6E),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35A97C),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        SetAMEM8BitTo7E1x(0x6C, 0x7EE021),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 1, ["command_0x35ab6a"]),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35ab89",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0517_BOMB_EXPLOSION,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        SetAMEMToRandom(amem=0x60, upper_bound=3, identifier="command_0x35aba5"),
        ObjectQueueAtOffsetAndIndexAtAMEM60(target_address=0x35ABAD),
        ReturnSubroutine(),
    ],
)
