# referenced by behaviour_33_0x350C5B, behaviour_34_0x350C9E, behaviour_51_0x350F56, behaviour_24_0x350A9C, behaviour_8_0x3507A2, weapons HandGun, behaviour_41_0x350DAF, behaviour_16_0x350928, behaviour_32_0x350C14, behaviour_52_0x350F6B, behaviour_23_0x350A55, behaviour_9_0x3507E9, behaviour_42_0x350DED, behaviour_43_0x350E38

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(expected_size = 185, script = [
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30, identifier="queuestart_0x35fc8f"),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=20, y=239, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0527_YELLOW_MIST_STEAM_FORMS_INTO_SMALL_STAR, sequence=1, priority=3, vram_address=0x6600, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, behind_all_sprites=True, overlap_all_sprites=True),
	ClearAMEM16Bit(0x60),
	ClearAMEM8Bit(0x6E),
	ClearAMEM8Bit(0x6F),
	PlaySound(sound=S0148_SMITHY_BULLET_FINGERS),
	ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35FC89),
	ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35F9A2),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35F9A2),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35F9A2),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35F9A2),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35F9A2),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35F9A2),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=6),
	PlaySound(sound=S0000_SILENCE),
	Pause1Frame(identifier="command_0x35fce2"),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 6, ["command_0x35fce2"]),
	PauseScriptUntilAMEMBitsSet(0x6E, [0]),
	RemoveObject(),
	SetAMEM8BitToConst(0x66, 1),
	SetOMEMMainToAMEM8Bit(omem=0x66, amem=0x66),
	ReturnObjectQueue(),
	SetAMEM32ToXYZCoords(origin=CASTER_CURRENT_POSITION, x=-4, y=3, z=0, set_x=True, set_y=True, set_z=True, identifier="queuestart_0x35fcf6"),
	NewSpriteAtCoords(sprite_id=SPR0527_YELLOW_MIST_STEAM_FORMS_INTO_SMALL_STAR, sequence=4, priority=3, vram_address=0x6400, palette_row=8, overwrite_vram=True, looping=True, overwrite_palette=True, overlap_all_sprites=True),
	ClearAMEM16Bit(0x60),
	ClearAMEM8Bit(0x6F),
	ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35F9A2),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35F9A2),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	ObjectQueueAtOffsetAndIndex(index=10, target_address=0x35F9A2),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35F9A2),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35F9A2),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
	ObjectQueueAtOffsetAndIndex(index=10, target_address=0x35F9A2),
	Pause1Frame(identifier="command_0x35fd37"),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 6, ["command_0x35fd37"]),
	RemoveObject(),
	SetAMEM8BitToConst(0x6E, 1),
	SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
	ReturnObjectQueue()
])
