# pylint: disable=C0301,C0103

"""referenced by monster_attacks Quicksilver, monster_attacks PhysicalAttack21, monster_attacks ScrowFangs, monster_spells Drain, monster_attacks PhysicalAttack90, monster_attacks 126, monster_attacks Shaker, monster_attacks Funguspike, monster_attacks BombsAway, monster_attacks Terrapunch, monster_attacks PhysicalAttack18, monster_attacks 121, monster_attacks 117, monster_attacks 114, monster_spells LightningOrb, monster_attacks PhysicalAttack113, monster_attacks 122, monster_attacks PhysicalAttack89, monster_attacks PhysicalAttack27, monster_attacks 125, monster_attacks PhysicalAttack108"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=617,
    script=[
        ResetTargetMappingMemory(identifier="command_0x357d0b"),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"D8")),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=768, arch_height=96),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        SpriteSequence(sequence=3),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=6),
        SpriteSequence(sequence=6),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-24,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=768, arch_height=192),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        SpriteSequence(sequence=5),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        ReturnSubroutine(),
        ResetTargetMappingMemory(identifier="command_0x357d3e"),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"D8")),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X00, speed=1280, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0189_CROCO_STILL,
            sequence=3,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=5, looping_on=True),
        PlaySound(sound=S0011_SWOOSH_RUN_AWAY),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=16,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X00, speed=1280, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        SpriteSequence(sequence=5, looping_off=True),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=0,
            apply_to_x=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=0,
            apply_to_y=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        ResetObjectMappingMemory(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0496_CROCO_1,
            sequence=0,
            store_to_vram=True,
            looping=True,
            store_palette=True,
        ),
        ResetSpriteSequence(),
        ReturnSubroutine(),
        ResetTargetMappingMemory(identifier="command_0x357d8c"),
        ResetObjectMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"D@")),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=80),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"Dp")),
        SpriteSequence(sequence=3),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=5),
        PlaySound(sound=S0087_BIG_BOUNCE),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-193,
            end_position=-193,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=129,
            start_position=-1537,
            end_position=1536,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        PlaySound(sound=S0087_BIG_BOUNCE),
        MoveObject(
            speed=129,
            start_position=-1537,
            end_position=1536,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0087_BIG_BOUNCE),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=64,
            end_position=64,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=65,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0195_EXPLOSIVE_HIT),
        ResetSpriteSequence(),
        ReturnSubroutine(),
        SpriteSequence(sequence=6, identifier="command_0x357e04"),
        PauseScriptUntilSpriteSequenceDone(),
        VisibilityOff(),
        RunSubroutine(["command_0x357f5e"]),
        SpriteSequence(sequence=5, looping_off=True),
        VisibilityOn(),
        SpriteSequence(sequence=5),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        PlaySound(sound=S0150_ENEMY_TAUNTS_THEN_HITS),
        PauseScriptUntilSpriteSequenceDone(),
        ReturnSubroutine(),
        SpriteSequence(sequence=6, identifier="command_0x357e1a"),
        PauseScriptUntilSpriteSequenceDone(),
        VisibilityOff(),
        RunSubroutine(["command_0x357f1e"]),
        SpriteSequence(sequence=5, looping_off=True),
        VisibilityOn(),
        SpriteSequence(sequence=5),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        ReturnSubroutine(),
        SpriteSequence(sequence=6, identifier="command_0x357e2b"),
        PauseScriptUntilSpriteSequenceDone(),
        VisibilityOff(),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x35272a"]),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1536, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        SpriteSequence(sequence=7, looping_off=True),
        VisibilityOn(),
        PlaySound(sound=S0206_MONSTER_SWING),
        SpriteSequence(sequence=7),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50),
        PlaySound(sound=S0206_MONSTER_SWING),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        PlaySound(sound=S0206_MONSTER_SWING),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        PlaySound(sound=S0206_MONSTER_SWING),
        PauseScriptUntilSpriteSequenceDone(),
        VisibilityOff(),
        SetOMEM60To072C(),
        DisplayMessageAtOMEM60As(BATTLE_DIALOGUE),
        RunSubroutine(["command_0x357f1e"]),
        SpriteSequence(sequence=5, looping_off=True),
        VisibilityOn(),
        SpriteSequence(sequence=5),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        ReturnSubroutine(),
        SpriteSequence(sequence=6, identifier="command_0x357e6c"),
        PauseScriptUntilSpriteSequenceDone(),
        VisibilityOff(),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"D8")),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=64),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        SpriteSequence(sequence=5, looping_off=True),
        VisibilityOn(),
        SpriteSequence(sequence=5),
        PauseScriptUntilSpriteSequenceDone(),
        ReturnSubroutine(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0502_BOOSTER,
            sequence=0,
            store_to_vram=True,
            store_palette=True,
            identifier="command_0x357e88",
        ),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=8,
            y=8,
            z=-16,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=512, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        SpriteSequence(sequence=2, looping_off=True),
        RunSubroutine(["command_0x35337d"]),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=32,
            y=-16,
            z=-8,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=768, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetSpriteSequence(),
        ReturnSubroutine(),
        ResetTargetMappingMemory(identifier="command_0x357ebe"),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-8,
            y=4,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1536, arch_height=0),
        SetAMEM16BitToConst(0x60, 10),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x355F1D),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        VisibilityOff(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x355F1D),
        VisibilityOn(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
        ResetTargetMappingMemory(identifier="command_0x357ef0"),
        MoveObject(
            speed=65,
            start_position=-769,
            end_position=-1537,
            apply_to_x=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=33,
            start_position=384,
            end_position=768,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=14),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
        ReturnSubroutine(identifier="command_0x357f07"),
        ResetTargetMappingMemory(identifier="command_0x357f08"),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=96,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=64),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
        ResetTargetMappingMemory(identifier="command_0x357f1e"),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1536, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ReturnSubroutine(),
        ResetTargetMappingMemory(identifier="command_0x357f32"),
        ResetObjectMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=8,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=512, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ReturnSubroutine(),
        ResetTargetMappingMemory(identifier="command_0x357f48"),
        ResetObjectMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=8,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1024, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ReturnSubroutine(),
        ResetTargetMappingMemory(identifier="command_0x357f5e"),
        ResetObjectMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=8,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1536, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ReturnSubroutine(),
    ],
)
