# pylint: disable=C0301,C0103

"""referenced by monster_spells Flame"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=113,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=4,
            y=256,
            z=8,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3563e5",
        ),
        EnableSpritesOnSubscreen(),
        NewSpriteAtCoords(
            sprite_id=SPR0794_DARK_RED_YELLOW_FIREBALL,
            sequence=1,
            priority=0,
            vram_address=0x6600,
            palette_row=8,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        FadeInSprite(duration=2),
        VisibilityOn(),
        ClearAMEM8Bit(0x69),
        SetAMEM16BitToConst(0x60, 0),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        FadeOutEffect(duration=1),
        SpriteSequence(sequence=2, looping_on=True),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x356B15),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        FadeOutSprite(duration=2),
        VisibilityOff(),
        Pause1Frame(identifier="command_0x35644c"),
        JmpIfAMEM8BitNotEqualsConst(0x69, 8, ["command_0x35644c"]),
        DisableSpritesOnSubscreen(),
        RemoveObject(),
        ReturnObjectQueue(),
    ],
)
