# pylint: disable=C0301,C0103

"""referenced by battle_events BE0092_SHELLY_BREAKS"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=166,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SetAMEM16BitToConst(0x6F, 65535),
        SetAMEMToAMEM16Bit(dest_amem=0x6C, amem=0x6F),
        EnableSpritesOnSubscreen(),
        NewSpriteAtCoords(
            sprite_id=SPR0026_GENO_WALKING_UP_RIGHT,
            sequence=0,
            priority=0,
            vram_address=0x6200,
            palette_row=8,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=6),
        RemoveObject(),
        DisableSpritesOnSubscreen(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=172,
            y=119,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a8c05",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0160_SHELLY_BOTTOM_SECTION,
            sequence=0,
            priority=2,
            vram_address=0x7600,
            palette_row=12,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        RunSubroutine(["command_0x3a755e"], identifier="after_shelly_egg"),
        RunSubroutine(["command_0x3a7873"]),
        Db(bytearray(b"\x02")),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=186,
            y=74,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Db(bytearray(b"\xba\x01\x04\x00")),
        ScreenEffect(SEF0015_UNKNOWN),
        RunSubroutine(["command_0x3a774a"]),
        PlaySound(sound=S0086_LONG_FALL),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=65,
            start_position=512,
            end_position=2048,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a771e"]),
        Db(bytearray(b"\x02")),
        SetAMEM32ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=256,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SetAMEM16BitToConst(0x60, 33021),
        SetAMEMToAMEM16Bit(dest_amem=0x8C, amem=0x60),
        RunSubroutine(["command_0x3a7760"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=96,
            end_position=96,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-49,
            end_position=-49,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=120),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a7781"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=9,
            start_position=0,
            end_position=768,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        RunSubroutine(["command_0x3a7797"]),
        MoveObject(
            speed=9,
            start_position=768,
            end_position=1792,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        RunSubroutine(["command_0x3a77c3"]),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a771e"]),
        Db(bytearray(b"\x02")),
    ],
)
