# pylint: disable=C0301,C0103

"""referenced by items Bomb, items BambinoBomb, items RottenMush, items Fireworks, items AbleJuice, items RockCandy, items 80, items 79, items FreshenUp, items MysteryEgg, items YoshiCandy, items DebugBomb, items Energizer, items Bracer, items GoodieBag, items DUMMY_53SopranoCard, items Elixir, items BadMushroom, items StarEgg, items SheepAttack, items MaxMushroom, items CastleKey2, items SleepBomb, items Mushroom2, items EarlierTimes, items Mushroom, items FearBomb, items RedEssence, items Megalixir, items YoshiAde, items IceBomb, items FroggieDrink, items MukuCookie, items YoshiCookie, items MuteBomb, items DoomBomb, items RoyalSyrup, items BaneBomb, items MidMushroom, items MapleSyrup, items KerokeroCola, items BeetleBox, items WiltShroom, items FrightBomb, items HoneySyrup, items SleepyBomb, items SeeYa, items BrightCard, items FireBomb, items PureWater, items PickMeUp"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=1149,
    script=[
        ClearAMEM8Bit(0x6F, identifier="command_0x35caac"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35CF29),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0013_COIN),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cacb"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitToConst(0x6E, 1),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35CF29),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0013_COIN),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35caec"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitToConst(0x6E, 2),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35CF29),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0013_COIN),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cb0d"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitToConst(0x6E, 3),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35CF29),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0013_COIN),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cb2e"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitToConst(0x6E, 4),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35CF29),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0013_COIN),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cb4f"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitToConst(0x6E, 5),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35CF29),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0013_COIN),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cb70"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35D187),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0013_COIN),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cb8d"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        SetAMEM8BitToConst(0x6E, 6),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35CF29),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cbac"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35D1FE),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cbc9"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=18, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitToConst(0x6E, 1),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35D1FE),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cbe8"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=20, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitToConst(0x6E, 2),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35D1FE),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6E, identifier="command_0x35cc07"),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=22, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35D2D5),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cc24"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=24, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitToConst(0x6E, 3),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35D45D),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0013_COIN),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cc45"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35D74B),
        PauseScriptUntilAMEMBitsSet(0x6F, [0, 1, 2, 3, 4, 5, 6, 7]),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cc51"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=34, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35DAD9),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cc6c"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=36, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35DB51),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cc87"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35DC6C),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cca2"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=44, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35DC8F),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35ccbd"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=46, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35DCB2),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35ccd8"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=28, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        SetAMEM8BitToConst(0x6E, 1),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35CF29),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35ccf7"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=26, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35D45D),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0013_COIN),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cd16"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=32, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35DCD5),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0013_COIN),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cd33"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=40, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitToConst(0x6E, 1),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35D45D),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0013_COIN),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cd54"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=42, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitToConst(0x6E, 2),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35D45D),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PlaySound(sound=S0013_COIN),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cd75"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=38, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitTo7E5x(0x60, 0x7E0001),
        JmpIfAMEM8BitEqualsConst(0x60, 0, ["command_0x35cd9f"]),
        JmpIfAMEM8BitEqualsConst(0x60, 1, ["command_0x35cda8"]),
        JmpIfAMEM8BitEqualsConst(0x60, 2, ["command_0x35cdb1"]),
        JmpIfAMEM8BitEqualsConst(0x60, 3, ["command_0x35cdba"]),
        Jmp(["command_0x35cdc3"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0002_MARIO_WALKING_UP_RIGHT,
            sequence=1,
            store_to_vram=True,
            store_palette=True,
            identifier="command_0x35cd9f",
        ),
        Jmp(["command_0x35cdc9"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0008_TOADSTOOL_WALKING_UP_RIGHT,
            sequence=1,
            store_to_vram=True,
            store_palette=True,
            identifier="command_0x35cda8",
        ),
        Jmp(["command_0x35cdc9"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0014_BOWSER_WALKING_UP_RIGHT,
            sequence=1,
            store_to_vram=True,
            store_palette=True,
            identifier="command_0x35cdb1",
        ),
        Jmp(["command_0x35cdc9"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0026_GENO_WALKING_UP_RIGHT,
            sequence=1,
            store_to_vram=True,
            store_palette=True,
            identifier="command_0x35cdba",
        ),
        Jmp(["command_0x35cdc9"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0020_MALLOW_WALKING_UP_RIGHT,
            sequence=1,
            store_to_vram=True,
            store_palette=True,
            identifier="command_0x35cdc3",
        ),
        PlaySound(sound=S0062_MONSTER_RUN_AWAY, identifier="command_0x35cdc9"),
        DisplayCantRunDialog(),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cdcd"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35DFC8),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cdd9"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=38, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        FadeOutScreen(duration=5),
        Db(bytearray(b"\x9c\x00A\x18\x00\x08\x00\x80\x00")),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=90),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Db(bytearray(b"\x9d\x02")),
        Db(bytearray(b"[\x01\x00")),
        SetAMEM16BitToConst(0x6E, 1),
        Set7E1xToAMEM16Bit(0x7E0B82, 0x6E),
        SetAMEM8BitTo7E1x(0x6E, 0x7E004C),
        Set7E1xToAMEM8Bit(0x7E004B, 0x6E),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35ce0d"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitToConst(0x6E, 4),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35D45D),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35ce2c"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=50, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35E045),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35ce47"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=30, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35E07C),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35ce5e"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=38, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35E5D8),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35ce75"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=48, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35E759),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35ce90"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35E866),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35ce9c"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=50, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35E9C3),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35ceb3"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35EA0C),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35ced0"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=18, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitToConst(0x6E, 1),
        ClearAMEM8Bit(0x6F),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35EA0C),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        SetAMEM8BitToConst(0x6F, 1, identifier="command_0x35ceef"),
        Db(bytearray(b'"\xcfN0')),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35cefc"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=50, target_address=0x358685),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        Db(bytearray(b"\x8d")),
        ClearAMEM8Bit(0x6F),
        SetAMEMToAMEM8Bit(dest_amem=0x61, amem=0x6F),
        FadeOutScreen(duration=1),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35EAF9),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        Db(bytearray(b"\x8c")),
        AttackTimerBegins(),
        Db(bytearray(b"<\x00\x08")),
        FadeInScreen(duration=1),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        ReturnSubroutine(),
    ],
)
