# pylint: disable=C0301,C0103

"""referenced by ally_spells Thunderbolt"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=170,
    script=[
        StartTrackingAllyButtonInputs(identifier="queuestart_0x35beb8"),
        SetAMEM16BitToConst(0x60, 0),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35BEB0),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35BEB0),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        TimingForOneBinaryButtonPress(
            end_accepting_input=30,
            start_accepting_input=0,
            timed_hit_ends=30,
            destinations=["command_0x35bee4"],
        ),
        ScreenFlashWithDuration(WHITE, 1, 16),
        PlaySound(sound=S0078_TIMED_STAT_BOOST),
        EndTrackingAllyButtonInputs(identifier="command_0x35bee4"),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35beee",
        ),
        NewEffectObject(effect=EF0046_BLANK_DARK_BLUE_FLASH__4BPP_, looping_off=True),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        Pause1Frame(identifier="command_0x35bf01"),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 0, ["command_0x35bf01"]),
        Layer3On(prop=OVERLAP_ALL, bpp4=True),
        ScreenFlashWithDuration(WHITE, 3, 32),
        PlaySound(sound=S0078_TIMED_STAT_BOOST),
        PauseScriptUntil(condition=SEQ_4BPP_COMPLETE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        FadeOutObject(duration=1),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(prop=OVERLAP_ALL, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        PlaySound(sound=S0044_BOLT, identifier="queuestart_0x35bf2c"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True
        ),
        NewEffectObject(effect=EF0091_THUNDERBOLT, looping_off=True),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        Pause1Frame(identifier="command_0x35bf41"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6F),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 0, ["command_0x35bf41"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=24),
        Layer3On(prop=OVERLAP_ALL, bpp4=True),
        PauseScriptUntil(condition=SEQ_2BPP_COMPLETE),
        Layer3Off(prop=OVERLAP_ALL, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
    ],
)
