# pylint: disable=C0301,C0103

"""referenced by battle_events BE0079_MAGIKOOPA_SUMMONS_MONSTER"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=202,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=-192,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a9ec1"),
        NewSpriteAtCoords(
            sprite_id=SPR0820_MAGIKOOPA_S_TRIANGLE_CIRCLE_X_CAST_MAGIC,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=17,
            start_position=1280,
            end_position=256,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        RunSubroutine(["command_0x3a7596"]),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a9eed"),
        ClearAMEM8Bit(0x60),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 9),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x3A8AC0),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x3A8AC0),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x3A8AC0),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x3A8AC0),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x3A8AC0),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x3A8AC0),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x3A8AC0),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x3A8AC0),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x3A8AC0),
        Pause1Frame(identifier="command_0x3a9f41"),
        JmpIfAMEM8BitNotEqualsConst(0x68, 9, ["command_0x3a9f41"]),
        RunSubroutine(["command_0x3a75a4"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x3a787e"], identifier="queuestart_0x3a9f4c"),
        NewSpriteAtCoords(
            sprite_id=SPR0775_WHITE_GAS_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        PlaySound(sound=S0178_POISON_GAS_2),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3a9f7f"]),
        RunSubroutine(["command_0x3a787e"], identifier="queuestart_0x3a9f5e"),
        NewSpriteAtCoords(
            sprite_id=SPR0775_WHITE_GAS_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        PlaySound(sound=S0178_POISON_GAS_2),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3a9f7f"]),
        RunSubroutine(["command_0x3a787e"], identifier="queuestart_0x3a9f70"),
        NewSpriteAtCoords(
            sprite_id=SPR0775_WHITE_GAS_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        PlaySound(sound=S0178_POISON_GAS_2),
        PauseScriptUntilSpriteSequenceDone(),
        SetAMEM8BitToOMEMMain(amem=0x68, omem=0x68, identifier="command_0x3a9f7f"),
        IncAMEM8Bit(0x68),
        SetOMEMMainToAMEM8Bit(omem=0x68, amem=0x68),
        RemoveObject(),
        ReturnObjectQueue(),
    ])
