# referenced by

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=66,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-8,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a8a7e",
        ),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=65,
            start_position=-513,
            end_position=768,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=17,
            start_position=0,
            end_position=-257,
            apply_to_x=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        RunSubroutine(["command_0x3a88d2"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=8,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a8a9f",
        ),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=65,
            start_position=-513,
            end_position=768,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=17,
            start_position=0,
            end_position=256,
            apply_to_x=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        RunSubroutine(["command_0x3a88d2"]),
    ],
)
