# pylint: disable=C0301,C0103

"""referenced by ally_spells Bowser Crush"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=216,
    script=[
        Db(bytearray(b" \x8d\x10\x00"), identifier="queuestart_0x35b365"),
        JmpIfAMEM8BitGreaterOrEqualThanConst(0x6D, 31, ["command_0x35b373"]),
        DisplayMessage(BATTLE_MESSAGE, 41),
        PauseScriptUntilDialogClosed(),
        ClearAMEM16Bit(0x60, identifier="command_0x35b373"),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35A97C),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35B35D),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35b38b"),
        NewEffectObject(effect=EF0011_BOWSER_CRUSH, playback_off=True),
        DoMaskEffect(POLYGON_MASK),
        SetMaskCoords((8, -80), (-80, 64), (-80, 64), (48, -80)),
        ScreenFlash(YELLOW, 8),
        Layer3On(prop=TRANSPARENCY_OFF, bit_0=True, bpp4=True),
        Db(bytearray(b"\xdd\xff\x0e\x05\x02\x01")),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35B35D),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        ClearAMEM8Bit(0x6E),
        ShakeScreen(amount=2, speed=160),
        PlaySound(sound=S0137_BOWSER_CRUSH_STOMP),
        RunSubroutine(["command_0x35b41b"]),
        RunSubroutine(["command_0x35b41b"]),
        RunSubroutine(["command_0x35b41b"]),
        RunSubroutine(["command_0x35b41b"]),
        RunSubroutine(["command_0x35b41b"]),
        RunSubroutine(["command_0x35b41b"]),
        RunSubroutine(["command_0x35b41b"]),
        RunSubroutine(["command_0x35b41b"]),
        StopShakingObject(),
        Layer3Off(prop=TRANSPARENCY_OFF, bpp4=True),
        Db(bytearray(b"\xde")),
        Db(bytearray(b"\x90")),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        Pause2Frames(),
        ClearEffectIndex(),
        SetAMEM8BitToConst(0x6F, 1),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=-9,
            y=-5,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35b3f1"),
        NewSpriteAtCoords(
            sprite_id=SPR0788_MECHA_KOOPA_BOWSER_CRUSH_EYES,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        Pause1Frame(identifier="command_0x35b40a"),
        SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6F),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 1, ["command_0x35b40a"]),
        RemoveObject(),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6F),
        ReturnObjectQueue(),
        ResetTargetMappingMemory(identifier="command_0x35b41b"),
        MoveObject(
            speed=1,
            start_position=384,
            end_position=384,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=768,
            end_position=768,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=209,
            start_position=-1537,
            end_position=1536,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        PlaySound(sound=S0137_BOWSER_CRUSH_STOMP),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
    ])
