# pylint: disable=C0301,C0103

"""referenced by ally_spells Geno Blast"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=535,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bbed",
        ),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitEqualsConst(0x6D, 64, ["command_0x35bc0b"]),
        NewSpriteAtCoords(
            sprite_id=SPR0026_GENO_WALKING_UP_RIGHT,
            sequence=4,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            invert_sprite=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        Jmp(["command_0x35bc14"]),
        NewSpriteAtCoords(
            sprite_id=SPR0039_RED_SCARECROW,
            sequence=4,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            invert_sprite=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
            identifier="command_0x35bc0b",
        ),
        Db(bytearray(b" \x80\x10\x00"), identifier="command_0x35bc14"),
        JmpIfAMEM8BitGreaterOrEqualThanConst(0x60, 31, ["command_0x35bc22"]),
        DisplayMessage(BATTLE_MESSAGE, 13),
        PauseScriptUntilDialogClosed(),
        ClearAMEM16Bit(0x60, identifier="command_0x35bc22"),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35BBC7),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35B43D),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=24, target_address=0x35BBC7),
        ObjectQueueAtOffsetAndIndex(index=26, target_address=0x35BBC7),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=66),
        JmpIfAMEM8BitEqualsConst(0x6D, 64, ["command_0x35bc50"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0030_GENO_MORPH_INTO_CANNON, sequence=0, store_to_vram=True
        ),
        PauseScriptUntilAMEMBitsSet(0x6F, [0], identifier="command_0x35bc50"),
        JmpIfAMEM8BitEqualsConst(0x6D, 64, ["command_0x35bc62"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0026_GENO_WALKING_UP_RIGHT, sequence=0, store_to_vram=True
        ),
        Jmp(["command_0x35bc68"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0039_RED_SCARECROW,
            sequence=0,
            store_to_vram=True,
            identifier="command_0x35bc62",
        ),
        SetAMEM8BitToConst(0x6F, 1, identifier="command_0x35bc68"),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        Pause1Frame(),
        RemoveObject(),
        ReturnObjectQueue(),
        PlaySound(sound=S0063_GENO_BLAST_IGNITION, identifier="queuestart_0x35bc73"),
        ScreenEffect(SEF0010_GENO_BLAST),
        Db(bytearray(b"\xa8\x02\x00")),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        ClearAMEM8Bit(0x6C, identifier="queuestart_0x35bc83"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=94),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=6, identifier="command_0x35bc89"
        ),
        PlaySound(sound=S0118_GENO_BLAST_END),
        IncAMEM8Bit(0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 15, ["command_0x35bc89"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=4,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bc98",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0528_VERY_SMALL_BLACK_DOT,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=8,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ShineEffect(
            colour_count=6, starting_colour_index=1, glow_duration=1, east=True
        ),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6E),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x35BBC7),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=22, target_address=0x35BBC7),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35BBC7),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=32, target_address=0x35BBC7),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=20, target_address=0x35BBC7),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35BBC7),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=18, target_address=0x35BBC7),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35BBC7),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35BBC7),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=34, target_address=0x35BBC7),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=30, target_address=0x35BBC7),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35BBC7),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=28, target_address=0x35BBC7),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x35BBC7),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=86),
        Db(bytearray(b"\x81")),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0532_BLUE_SPARK,
            sequence=0,
            store_to_vram=True,
            looping=True,
            store_palette=True,
        ),
        Pause1Frame(identifier="command_0x35bd01"),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 14, ["command_0x35bd01"]),
        RemoveObject(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-24,
            y=-272,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bd16",
        ),
        RunSubroutine(["command_0x35bdbe"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-21,
            y=-274,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bd22",
        ),
        RunSubroutine(["command_0x35bdbe"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-18,
            y=-272,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bd2e",
        ),
        RunSubroutine(["command_0x35bdbe"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-15,
            y=-274,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bd3a",
        ),
        RunSubroutine(["command_0x35bdbe"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-12,
            y=-272,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bd46",
        ),
        RunSubroutine(["command_0x35bdbe"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-9,
            y=-274,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bd52",
        ),
        RunSubroutine(["command_0x35bdbe"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-6,
            y=-272,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bd5e",
        ),
        RunSubroutine(["command_0x35bdbe"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-3,
            y=-274,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bd6a",
        ),
        RunSubroutine(["command_0x35bdbe"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-272,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bd76",
        ),
        RunSubroutine(["command_0x35bdbe"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=3,
            y=-274,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bd82",
        ),
        RunSubroutine(["command_0x35bdbe"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=6,
            y=-272,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bd8e",
        ),
        RunSubroutine(["command_0x35bdbe"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=9,
            y=-274,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bd9a",
        ),
        RunSubroutine(["command_0x35bdbe"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=12,
            y=-272,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bda6",
        ),
        RunSubroutine(["command_0x35bdbe"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=15,
            y=-274,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35bdb2",
        ),
        RunSubroutine(["command_0x35bdbe"]),
        ReturnObjectQueue(),
        Db(bytearray(b"\x83\x83"), identifier="command_0x35bdbe"),
        MoveObject(
            speed=3,
            start_position=0,
            end_position=-81,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        MoveObject(
            speed=2,
            start_position=-81,
            end_position=-257,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        MoveObject(
            speed=2,
            start_position=-257,
            end_position=0,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-3,
            y=-285,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=896, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        IncAMEM8Bit(0x6E),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        RemoveObject(),
        ReturnSubroutine(),
    ],
)
