# pylint: disable=C0301,C0103

"""referenced by battle_events BE0034_BLOW_THOSE_CANDLES_OUT, battle_events BE0036_TENTACLES_THROW_CHARACTER_OFF_SCREEN, battle_events BE0028_BEAT_TENTACLES_MOVE_ON_TO_KING_CALAMARI, battle_events BE0032_BUNDT_MOVES_AGAIN_BOTH_COOKS_RUN_AWAY, battle_events BE0033_CANDLES_APPEAR_ON_BUNDT"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=1249,
    script=[
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3ac7cf"),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=179,
            y=162,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        NewSpriteAtCoords(
            sprite_id=SPR0465_TENTACLES_RIGHT,
            sequence=5,
            priority=2,
            vram_address=0x7600,
            palette_row=12,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        SummonMonster(monster=TentaclesRight, position=1, bit_7=True),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3ac7ec"),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=212,
            y=96,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        NewSpriteAtCoords(
            sprite_id=SPR0472_KING_CALAMARI,
            sequence=0,
            priority=2,
            vram_address=0x7800,
            palette_row=14,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        SummonMonster(monster=KingCalamari, position=1, bit_7=True),
        RunSubroutine(["command_0x3a755e"]),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=-32,
            y=248,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        SpriteSequence(sequence=0, looping_on=True),
        RunSubroutine(["command_0x3a81b0"]),
        RunSubroutine(["command_0x3a727a"]),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0001_MARIO_JUMP_FRONT,
            sequence=9,
            store_to_vram=True,
            store_palette=True),
        SpriteSequence(sequence=9, mirror=True),
        PlaySound(sound=S0004_JUMP),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=-65,
            end_position=-65,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=129,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0004_JUMP),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=81,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        VisibilityOff(),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x3a7729"]),
        VisibilityOff(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=168,
            y=144,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0001_MARIO_JUMP_FRONT,
            sequence=3,
            store_to_vram=True,
            store_palette=True),
        VisibilityOn(),
        PlaySound(sound=S0004_JUMP),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=81,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0004_JUMP),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=64,
            end_position=64,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=129,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT,
            sequence=0,
            store_to_vram=True,
            store_palette=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        SetSequenceSpeed(3),
        SpriteSequence(sequence=8),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=8),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        SetSequenceSpeed(1),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        SpriteSequence(sequence=0, looping_on=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=110),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        SetAMEM8BitTo7E5x(0x60, 0x7E0000, identifier="queuestart_0x3ac917"),
        SetAMEMBits(0x60, [7]),
        Set7E5xToAMEM8Bit(0x7E0000, 0x60),
        RunSubroutine(["command_0x3a755e"]),
        RunSubroutine(["command_0x3a7729"]),
        RunSubroutine(["command_0x3a86a7"]),
        PlaySound(sound=S0092_SPEAR_RAIN_SINGLE),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=65,
            start_position=-1025,
            end_position=-4097,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        ClearAMEM8Bit(0x60),
        Set7E1xToAMEM8Bit(0x7EE00D, 0x60),
        SetAMEM8BitTo7E1x(0x60, 0x7EFA00),
        IncAMEM8Bit(0x60),
        SetAMEM8BitToConst(0x61, 1),
        Db(bytearray(b"\x16"), identifier="command_0x3ac94b"),
        Pause1Frame(),
        JmpIfAMEM8BitEquals7E1x(0x61, 0x7EE00D, ["command_0x3ac959"]),
        JmpIfAMEM8BitNotEquals7E1x(0x60, 0x7EFA00, ["command_0x3ac94b"]),
        ResetTargetMappingMemory(identifier="command_0x3ac959"),
        MoveObject(
            speed=65,
            start_position=1024,
            end_position=4096,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a71da"]),
        RunSubroutine(["command_0x3a7544"]),
        SetAMEM8BitToConst(0x60, 8),
        Set7E5xToAMEM8Bit(0x7E0040, 0x60),
        SetAMEM16BitToConst(0x60, 3),
        Set7E5xToAMEM16Bit(0x7E0043, 0x60),
        Db(bytearray(b"m")),
        SetAMEM8BitTo7E5x(0x60, 0x7E0000),
        ClearAMEMBits(0x60, [7]),
        Set7E5xToAMEM8Bit(0x7E0000, 0x60),
        ClearAMEM8Bit(0x60),
        Set7E1xToAMEM8Bit(0x7EE008, 0x60),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a756c"], identifier="queuestart_0x3ac990"),
        SpriteSequence(sequence=3),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a756c"]),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a773f"]),
        DisplayMessage(BATTLE_DIALOGUE, 96),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        SpriteSequence(sequence=1, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        DisplayMessage(BATTLE_DIALOGUE, 97),
        RunSubroutine(["command_0x3a733e"]),
        SpriteSequence(sequence=1, looping_off=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a7596"]),
        RunSubroutine(["command_0x3a7755"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SpriteSequence(sequence=1, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        DisplayMessage(BATTLE_DIALOGUE, 99),
        PlaySound(sound=S0004_JUMP),
        RunSubroutine(["command_0x3a7374"]),
        PauseScriptUntilDialogClosed(),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a75b2"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        ResetSpriteSequence(),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        RunSubroutine(["command_0x3a733e"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=176,
            y=136,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x3a727a"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        DisplayMessage(BATTLE_DIALOGUE, 95),
        SpriteSequence(sequence=3, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a7588"]),
        RunSubroutine(["command_0x3a774a"]),
        DisplayMessage(BATTLE_DIALOGUE, 98),
        SpriteSequence(sequence=3, looping_on=True, mirror=True),
        PlaySound(sound=S0004_JUMP),
        RunSubroutine(["command_0x3a7374"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a75a4"]),
        RunSubroutine(["command_0x3a7760"]),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_on=True),
        DisplayMessage(BATTLE_DIALOGUE, 100),
        RunSubroutine(["command_0x3a71ee"]),
        ResetSpriteSequence(),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        SpriteSequence(sequence=3, looping_on=True, identifier="queuestart_0x3aca69"),
        RunSubroutine(["command_0x3a771e"]),
        ResetSpriteSequence(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=10, identifier="queuestart_0x3aca7e"
        ),
        RunSubroutine(["command_0x3a75dc"]),
        ResetTargetMappingMemory(),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        PlaySound(sound=S0004_JUMP),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=4608,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=129,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        PlaySound(sound=S0004_JUMP),
        RunSubroutine(["command_0x3a7390"]),
        SpriteSequence(sequence=1, looping_on=True),
        RunSubroutine(["command_0x3a81d8"]),
        RunSubroutine(["command_0x3a7292"]),
        SpriteSequence(sequence=0, looping_on=True),
        RunSubroutine(["command_0x3a75ea"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-769,
            end_position=-769,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=384,
            end_position=384,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        SpriteSequence(
            sequence=1, looping_on=True, mirror=True, identifier="queuestart_0x3acb45"
        ),
        RunSubroutine(["command_0x3a7781"]),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=256,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=129,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a778c"]),
        SpriteSequence(sequence=1, looping_on=True),
        RunSubroutine(["command_0x3a81d8"]),
        RunSubroutine(["command_0x3a7292"]),
        SpriteSequence(sequence=0, looping_on=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-769,
            end_position=-769,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=384,
            end_position=384,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        ReturnSpriteQueue(),
        PauseScriptUntilBitsClear(17246),
        Db(bytearray(b"\x13")),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=100),
        ResetSpriteSequence(),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        SpriteSequence(sequence=3, looping_on=True, identifier="queuestart_0x3acc12"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=100),
        ResetSpriteSequence(),
        RunSubroutine(["command_0x3a756c"]),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3acc20"),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=199,
            y=80,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        NewSpriteAtCoords(
            sprite_id=SPR0510_CANDLE,
            sequence=1,
            priority=2,
            vram_address=0x7E00,
            palette_row=14,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        SummonMonster(monster=Candle, position=1, bit_7=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SpriteSequence(sequence=2, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SpriteSequence(sequence=3, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SpriteSequence(sequence=4, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SpriteSequence(sequence=5, looping_on=True),
        DisplayMessage(BATTLE_DIALOGUE, 137),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        ClearAMEM8Bit(0x69, identifier="queuestart_0x3acc59"),
        Db(bytearray(b"\x16"), identifier="command_0x3acc5b"),
        Pause1Frame(),
        SetAMEM8BitTo7E1x(0x68, 0x7EE007),
        JmpIfAMEM8BitEqualsAMEM(
            amem=0x68, source_amem=0xC9, destinations=["command_0x3acc5b"]
        ),
        SetAMEM8BitToAMEM(amem=0x69, source_amem=0xC8),
        JmpIfAMEM8BitEqualsConst(0x68, 0, ["command_0x3acc92"]),
        JmpIfAMEM8BitEqualsConst(0x68, 1, ["command_0x3acc97"]),
        JmpIfAMEM8BitEqualsConst(0x68, 2, ["command_0x3acc9c"]),
        JmpIfAMEM8BitEqualsConst(0x68, 3, ["command_0x3acca1"]),
        JmpIfAMEM8BitEqualsConst(0x68, 4, ["command_0x3acca6"]),
        JmpIfAMEM8BitEqualsConst(0x68, 5, ["command_0x3accab"]),
        Jmp(["command_0x3acc5b"]),
        SpriteSequence(sequence=5, looping_on=True, identifier="command_0x3acc92"),
        Jmp(["command_0x3acc5b"]),
        SpriteSequence(sequence=4, looping_on=True, identifier="command_0x3acc97"),
        Jmp(["command_0x3acc5b"]),
        SpriteSequence(sequence=3, looping_on=True, identifier="command_0x3acc9c"),
        Jmp(["command_0x3acc5b"]),
        SpriteSequence(sequence=2, looping_on=True, identifier="command_0x3acca1"),
        Jmp(["command_0x3acc5b"]),
        SpriteSequence(sequence=1, looping_on=True, identifier="command_0x3acca6"),
        Jmp(["command_0x3acc5b"]),
        SpriteSequence(sequence=6, looping_on=True, identifier="command_0x3accab"),
        Jmp(["command_0x3acc5b"]),
    ])
