# referenced by monster_attacks PhysicalAttack10, monster_attacks PhysicalAttack9

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=80,
    script=[
        ReturnSubroutine(identifier="command_0x357951"),
        ResetTargetMappingMemory(identifier="command_0x357952"),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=257,
            start_position=1024,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0170_SUBMERGED_UNDER),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 11),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x355F1D),
        Db(bytearray(b"Z")),
        VisibilityOff(),
        RunSubroutine(["command_0x352552"]),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"D`")),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=768, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        SetAMEM60ToCurrentTarget(),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 11),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x355F1D),
        VisibilityOn(),
        PlaySound(sound=S0170_SUBMERGED_UNDER),
        MoveObject(
            speed=257,
            start_position=-1025,
            end_position=-2049,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        Db(bytearray(b"Y")),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x352552"]),
        ReturnSubroutine(),
    ],
)
