# pylint: disable=C0301,C0103

"""referenced by behaviour_53_0x350F7A, monster_attacks PhysicalAttack117, monster_attacks PhysicalAttack116, monster_attacks PhysicalAttack118"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=456,
    script=[
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=176,
            y=160,
            z=-256,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3552d1"),
        NewSpriteAtCoords(
            sprite_id=SPR0487_AERO,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=33,
            start_position=1024,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=39),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0093_BOWYER_ARROW_LOCK_BUTTON),
        SpriteSequence(sequence=0),
        PauseScriptUntilSpriteSequenceDone(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0563_ABXY_BUTTONS_FROM_BOWYER_S_BUTTON_LOCK,
            sequence=4,
            store_to_vram=True,
            store_palette=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ClearAMEM8Bit(0x61),
        SetAMEM8BitToConst(0x61, 1),
        Set7E1xToAMEM8Bit(0x7EE003, 0x61),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ClearAMEM8Bit(0x61),
        SetAMEM8BitToConst(0x61, 0),
        Set7E1xToAMEM8Bit(0x7EE003, 0x61),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=112,
            y=144,
            z=-272,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x355322"),
        NewSpriteAtCoords(
            sprite_id=SPR0487_AERO,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=33,
            start_position=1024,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=39),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0093_BOWYER_ARROW_LOCK_BUTTON),
        SpriteSequence(sequence=0),
        PauseScriptUntilSpriteSequenceDone(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0563_ABXY_BUTTONS_FROM_BOWYER_S_BUTTON_LOCK,
            sequence=4,
            store_to_vram=True,
            store_palette=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ClearAMEM8Bit(0x61),
        SetAMEM8BitToConst(0x61, 1),
        Set7E1xToAMEM8Bit(0x7EE003, 0x61),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ClearAMEM8Bit(0x61),
        SetAMEM8BitToConst(0x61, 0),
        Set7E1xToAMEM8Bit(0x7EE003, 0x61),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=160,
            y=-122,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x355373"),
        NewSpriteAtCoords(
            sprite_id=SPR0487_AERO,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=33,
            start_position=1024,
            end_position=2048,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=39),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0093_BOWYER_ARROW_LOCK_BUTTON),
        SpriteSequence(sequence=0),
        PauseScriptUntilSpriteSequenceDone(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0563_ABXY_BUTTONS_FROM_BOWYER_S_BUTTON_LOCK,
            sequence=4,
            store_to_vram=True,
            store_palette=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ClearAMEM8Bit(0x61),
        SetAMEM8BitToConst(0x61, 1),
        Set7E1xToAMEM8Bit(0x7EE003, 0x61),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ClearAMEM8Bit(0x61),
        SetAMEM8BitToConst(0x61, 0),
        Set7E1xToAMEM8Bit(0x7EE003, 0x61),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=176,
            y=-96,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3553c4"),
        NewSpriteAtCoords(
            sprite_id=SPR0563_ABXY_BUTTONS_FROM_BOWYER_S_BUTTON_LOCK,
            sequence=0,
            priority=2,
            vram_address=0x7800,
            palette_row=12,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        ClearAMEM8Bit(0x60),
        ClearAMEM8Bit(0x61),
        SetAMEM8BitToConst(0x60, 1),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION, x=176, y=160, z=0, set_y=True, set_z=True
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X00, speed=3072, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        Pause1Frame(identifier="command_0x3553f1"),
        JmpIfAMEM8BitEquals7E1x(0x61, 0x7EE003, ["command_0x3553f1"]),
        Pause1Frame(),
        JmpIfAMEM8BitEquals7E1x(0x60, 0x7EE001, ["command_0x355404"]),
        SpriteSequence(sequence=0),
        Jmp(["command_0x3553f1"]),
        PlaySound(sound=S0098_CLICK, identifier="command_0x355404"),
        SpriteSequence(sequence=3),
        Jmp(["command_0x3553f1"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=160,
            y=-120,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35540b"),
        NewSpriteAtCoords(
            sprite_id=SPR0563_ABXY_BUTTONS_FROM_BOWYER_S_BUTTON_LOCK,
            sequence=1,
            priority=2,
            vram_address=0x7A00,
            palette_row=12,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        ClearAMEM8Bit(0x60),
        ClearAMEM8Bit(0x61),
        SetAMEM8BitToConst(0x60, 4),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION, x=160, y=136, z=0, set_y=True, set_z=True
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X00, speed=3072, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        Pause1Frame(identifier="command_0x355438"),
        JmpIfAMEM8BitEquals7E1x(0x61, 0x7EE003, ["command_0x355438"]),
        Pause1Frame(),
        JmpIfAMEM8BitEquals7E1x(0x60, 0x7EE001, ["command_0x35544b"]),
        SpriteSequence(sequence=1),
        Jmp(["command_0x355438"]),
        PlaySound(sound=S0098_CLICK, identifier="command_0x35544b"),
        SpriteSequence(sequence=3),
        Jmp(["command_0x355438"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=112,
            y=-128,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x355452"),
        NewSpriteAtCoords(
            sprite_id=SPR0563_ABXY_BUTTONS_FROM_BOWYER_S_BUTTON_LOCK,
            sequence=2,
            priority=2,
            vram_address=0x7C00,
            palette_row=12,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        ClearAMEM8Bit(0x60),
        ClearAMEM8Bit(0x61),
        SetAMEM8BitToConst(0x60, 2),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION, x=112, y=128, z=0, set_y=True, set_z=True
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X00, speed=3072, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        Pause1Frame(identifier="command_0x35547f"),
        JmpIfAMEM8BitEquals7E1x(0x61, 0x7EE003, ["command_0x35547f"]),
        Pause1Frame(),
        JmpIfAMEM8BitEquals7E1x(0x60, 0x7EE001, ["command_0x355492"]),
        SpriteSequence(sequence=2),
        Jmp(["command_0x35547f"]),
        PlaySound(sound=S0098_CLICK, identifier="command_0x355492"),
        SpriteSequence(sequence=3),
        Jmp(["command_0x35547f"]),
    ])
