# referenced by monster_spells PetalBlast, monster_spells Solidify

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=217,
    script=[
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=48,
            y=80,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3556ed",
        ),
        NewEffectObject(effect=EF0022_SOLIDIFY, looping_off=True),
        RunSubroutine(["command_0x35337d"]),
        RunSubroutine(["command_0x3533f5"]),
        FadeInEffect(duration=1),
        Layer3On(property=OVERLAP_ALL, bpp4=True),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        Layer3Off(property=OVERLAP_ALL, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        Jmp(["command_0x35252f"]),
        RunSubroutine(["command_0x353437"], identifier="queuestart_0x355716"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True
        ),
        NewEffectObject(
            effect=EF0060_ICE_BOMB_SOLIDIFY_BG__BLUE_FREEZE_, looping_off=True
        ),
        RunSubroutine(["command_0x3533ea"]),
        FadeInEffect(duration=2),
        Layer3On(property=OVERLAP_ALL, bpp4=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        RunSubroutine(["command_0x35338b"]),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(property=OVERLAP_ALL, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x353437"], identifier="queuestart_0x355740"),
        SetAMEM16BitToConst(0x60, 5),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35624B),
        RunSubroutine(["command_0x352552"]),
        RunSubroutine(["command_0x353400"]),
        RunSubroutine(["command_0x35340b"]),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x355755",
        ),
        NewEffectObject(effect=EF0077_PETAL_BLAST_1, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-769,
            end_position=-769,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=384,
            end_position=384,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        FadeInEffect(duration=2),
        Layer3On(property=OVERLAP_ALL, bpp4=True),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=90),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(property=OVERLAP_ALL, bpp4=True),
        Pause2Frames(),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x353399"]),
        ClearEffectIndex(),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x355791",
        ),
        NewEffectObject(effect=EF0078_PETAL_BLAST_2, looping_on=True),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        FadeInEffect(duration=2),
        Layer3On(property=OVERLAP_ALL, bpp4=True),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=90),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        Layer3Off(property=OVERLAP_ALL, bpp4=True),
        Pause2Frames(),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3533a7"]),
        ClearEffectIndex(),
        ReturnObjectQueue(),
    ],
)
