# pylint: disable=C0301,C0103

"""referenced by monster_attacks PhysicalAttack11, monster_attacks PhysicalAttack15, monster_attacks PhysicalAttack12"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=322,
    script=[
        ResetTargetMappingMemory(identifier="command_0x3579a2"),
        ResetObjectMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"D@")),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=80),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"D\x80")),
        SpriteSequence(sequence=3),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=5),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X00, speed=2048, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=-101,
            start_position=0,
            end_position=-513,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=103,
            start_position=-513,
            end_position=0,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=5),
        ResetObjectMappingMemory(),
        ResetSpriteSequence(),
        ReturnSubroutine(),
        ResetTargetMappingMemory(identifier="command_0x357a03"),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1280, arch_height=96),
        PauseScriptUntil(condition=0x07),
        ResetObjectMappingMemory(),
        ResetSpriteSequence(),
        ReturnSubroutine(),
        ResetTargetMappingMemory(identifier="command_0x357a19"),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=17,
            start_position=256,
            end_position=0,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        MoveObject(
            speed=25,
            start_position=-769,
            end_position=0,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=32,
            y=-16,
            z=-32,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1536, arch_height=0),
        PauseScriptUntil(condition=0x04),
        ReturnSubroutine(),
        ResetTargetMappingMemory(identifier="command_0x357a4c"),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=0,
            y=0,
            z=-16,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1536, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetSpriteSequence(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=512, arch_height=128),
        PauseScriptUntil(condition=0x07),
        ReturnSubroutine(),
        ResetTargetMappingMemory(identifier="command_0x357a77"),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION, x=-16, y=8, z=0, set_y=True, set_z=True
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=256, arch_height=64),
        PauseScriptUntil(condition=0x04),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        Db(bytearray(b"Z")),
        MoveObject(
            speed=1,
            start_position=-513,
            end_position=-513,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=129,
            start_position=-4097,
            end_position=0,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Db(bytearray(b"\x12\x81")),
        ResetObjectMappingMemory(),
        SpriteSequence(sequence=5),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION, x=48, y=-24, z=0, set_y=True, set_z=True
        ),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION, x=32, y=-16, z=0, set_y=True, set_z=True
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_0X00, speed=256, arch_height=0),
        MoveObject(
            speed=257,
            start_position=4096,
            end_position=8192,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        Db(bytearray(b"Y")),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_z=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
    ],
)
