# pylint: disable=C0301,C0103

"""referenced by ally_spells Super Flame"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=454,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3584bf"),
        NewSpriteAtCoords(
            sprite_id=SPR0528_VERY_SMALL_BLACK_DOT,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        ShineEffect(
            colour_count=6, starting_colour_index=1, glow_duration=1, east=True
        ),
        SetAMEM16BitToConst(0x60, 0),
        ClearAMEM8Bit(0x6E),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x358499),
        RunSubroutine(["command_0x35862c"]),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        RemoveObject(),
        Db(bytearray(b"\x81")),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=5, identifier="queuestart_0x3584ef"
        ),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=8,
            y=-266,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        NewEffectObject(effect=EF0012_SPELL_CAST_SPADE, looping_on=True),
        PlaySound(sound=S0035_SPELL_POWER_UP),
        Db(bytearray(b"\x8a\x01")),
        Layer3On(prop=OVERLAP_ALL, bpp4=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=24),
        FadeOutObject(duration=1),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(prop=OVERLAP_ALL, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x35851a"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-290,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x358529"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=9,
            y=-287,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x358538"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=16,
            y=-282,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x358547"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=21,
            y=-275,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x358556"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=24,
            y=-266,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x358565"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=21,
            y=-257,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x358574"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=16,
            y=-250,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x358583"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=9,
            y=-245,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x358592"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-242,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x3585a1"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-9,
            y=-245,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x3585b0"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-16,
            y=-250,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x3585bf"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-21,
            y=-257,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x3585ce"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-24,
            y=-266,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x3585dd"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-21,
            y=-275,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x3585ec"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-16,
            y=-282,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x35812b"], identifier="queuestart_0x3585fb"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-9,
            y=-287,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        RunSubroutine(["command_0x35860a"]),
        ReturnObjectQueue(),
        Db(bytearray(b"\x83\x83"), identifier="command_0x35860a"),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-266,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        IncAMEM8Bit(0x6D),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6D, identifier="command_0x35862c"),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x358499),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x358499),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x358499),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x358499),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x358499),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x358499),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x358499),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=18, target_address=0x358499),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=20, target_address=0x358499),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=22, target_address=0x358499),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=24, target_address=0x358499),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=26, target_address=0x358499),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=28, target_address=0x358499),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=30, target_address=0x358499),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=32, target_address=0x358499),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=34, target_address=0x358499),
        Pause1Frame(identifier="command_0x35867d"),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 16, ["command_0x35867d"]),
        ReturnSubroutine(),
    ])
