# pylint: disable=C0301,C0103

"""referenced by monster_attacks PhysicalAttack47, monster_spells Electroshock, monster_spells PetalBlast, monster_attacks Poison"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=108,
    script=[
        RunSubroutine(["command_0x35259b"], identifier="queuestart_0x356b86"),
        Db(bytearray(b"\x83\x83")),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=768, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        Jmp(["command_0x356af4"]),
        RunSubroutine(["command_0x35259b"], identifier="queuestart_0x356ba2"),
        Db(bytearray(b"\x83\x83")),
        RunSubroutine(["command_0x352c39"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        Jmp(["command_0x356af4"]),
        RunSubroutine(["command_0x35259b"], identifier="queuestart_0x356bb1"),
        Db(bytearray(b"\x83\x83")),
        RunSubroutine(["command_0x352dc0"]),
        RunSubroutine(["command_0x352c71"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        Jmp(["command_0x356af4"]),
        RunSubroutine(["command_0x35259b"], identifier="queuestart_0x356bc3"),
        Db(bytearray(b"\x83\x83")),
        RunSubroutine(["command_0x352d13"]),
        RunSubroutine(["command_0x352c71"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        Jmp(["command_0x356af4"]),
        RunSubroutine(["command_0x352ae6"], identifier="queuestart_0x356bd5"),
        Db(bytearray(b"\x83\x83")),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-1025,
            end_position=-1025,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=512,
            end_position=512,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        Jmp(["command_0x356af4"]),
    ],
)
