# pylint: disable=C0301,C0103

"""referenced by items SheepAttack, items YoshiCookie"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=890,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35d75f",
        ),
        SetAMEM16BitToConst(0x60, 0),
        ClearAMEM8Bit(0x6D),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35D74B),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35D74B),
        PlaySound(sound=S0075_YOSHI_TALK),
        PauseScriptUntilAMEMBitsSet(0x6F, [0, 1, 2, 3, 4, 5, 6, 7]),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=272,
            y=224,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35d781",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0051_GREEN_YOSHI_WALK,
            sequence=1,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=204,
            y=174,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=768, arch_height=128),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0049_GREEN_YOSHI,
            sequence=12,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=3),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0051_GREEN_YOSHI_WALK,
            sequence=0,
            store_to_vram=True,
            looping=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0052_GREEN_YOSHI_LAYING_EGG,
            sequence=1,
            store_to_vram=True,
            looping=True,
            store_palette=True,
        ),
        Pause1Frame(identifier="command_0x35d7bf"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 1, ["command_0x35d7bf"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0052_GREEN_YOSHI_LAYING_EGG,
            sequence=2,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        PlaySound(sound=S0065_YOSHI_CANT_MAKE_COOKIE),
        PauseScriptUntilSpriteSequenceDone(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=6),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0049_GREEN_YOSHI,
            sequence=12,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=3),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0051_GREEN_YOSHI_WALK,
            sequence=1,
            store_to_vram=True,
            looping=True,
            store_palette=True,
        ),
        Db(bytearray(b"DZ")),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=768, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0049_GREEN_YOSHI,
            sequence=11,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=3),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0051_GREEN_YOSHI_WALK,
            sequence=10,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        ClearAMEM8Bit(0x6C),
        SetAMEM60ToCurrentTarget(),
        SpriteQueue(
            field_object=0, destinations=["queuestart_0x35daac"], current_target=True
        ),
        PauseScriptUntilAMEMBitsSet(0x6C, [0, 1, 2, 3, 4, 5, 6, 7]),
        JmpIfAMEM8BitEqualsConst(0x6C, 2, ["command_0x35d8b9"]),
        ClearAMEM8Bit(0x6C),
        SetAMEM60ToCurrentTarget(),
        SpriteQueue(
            field_object=0, destinations=["queuestart_0x35dac8"], current_target=True
        ),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        ClearAMEM8Bit(0x6C),
        ClearAMEM8Bit(0x6D),
        SetAMEM16BitToConst(0x60, 0),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35D74B),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35D74B),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        ClearAMEM8Bit(0x6D),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x35D74B),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        ClearAMEM8Bit(0x6C),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35D74B),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=1),
        SpriteSequence(sequence=11, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=19),
        PlaySound(sound=S0065_YOSHI_CANT_MAKE_COOKIE),
        PauseScriptUntilSpriteSequenceDone(),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        SpriteSequence(sequence=1, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0049_GREEN_YOSHI,
            sequence=11,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0051_GREEN_YOSHI_WALK,
            sequence=1,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0049_GREEN_YOSHI,
            sequence=12,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0051_GREEN_YOSHI_WALK,
            sequence=0,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6D),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35D74B),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0052_GREEN_YOSHI_LAYING_EGG,
            sequence=0,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=54),
        PlaySound(sound=S0064_EGG_HATCH),
        PauseScriptUntilSpriteSequenceDone(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0051_GREEN_YOSHI_WALK,
            sequence=0,
            store_to_vram=True,
            store_palette=True,
        ),
        ResetObjectMappingMemory(),
        DisplayMessage(BATTLE_MESSAGE, 5),
        PauseScriptUntilDialogClosed(),
        SetAMEM8BitToConst(0x6D, 1),
        SetAMEM8BitToConst(0x6E, 255),
        Jmp(["command_0x35d924"]),
        PlaySound(sound=S0010_MALLOW_PUNCH_1, identifier="command_0x35d8b9"),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0051_GREEN_YOSHI_WALK,
            sequence=9,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        PlaySound(sound=S0008_GET_DIZZY),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0049_GREEN_YOSHI,
            sequence=11,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        SpriteSequence(sequence=1, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        SpriteSequence(sequence=12, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x35D74B),
        ClearAMEM8Bit(0x6E),
        SpriteSequence(sequence=0, looping_off=True, identifier="command_0x35d8e2"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        SpriteSequence(sequence=10, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        SpriteSequence(sequence=12, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        SpriteSequence(sequence=11, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        SpriteSequence(sequence=1, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        SpriteSequence(sequence=12, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        IncAMEM8Bit(0x6E),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 3, ["command_0x35d8e2"]),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        SetAMEM8BitToConst(0x6E, 1),
        ResetTargetMappingMemory(identifier="command_0x35d924"),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0049_GREEN_YOSHI,
            sequence=10,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0051_GREEN_YOSHI_WALK,
            sequence=0,
            store_to_vram=True,
            looping=True,
            store_palette=True,
        ),
        SetAMEM40ToXYZCoords(origin=ABSOLUTE_POSITION, x=272, y=0, z=0, set_z=True),
        MoveObject(
            speed=1,
            start_position=640,
            end_position=640,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=1280,
            end_position=1280,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=0x04),
        ResetObjectMappingMemory(),
        RemoveObject(),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6E),
        ReturnObjectQueue(),
        SetAMEM8BitToConst(0x6D, 1, identifier="queuestart_0x35d958"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=16,
            y=-12,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0562_YELLOW_REUSABLE_ITEM_SPRITE_WITH_LETTER_I,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=183,
            y=52,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=592, arch_height=80),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0518_SMALL_WHITE_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0051_GREEN_YOSHI_WALK,
            sequence=12,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=1488,
            end_position=1488,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=19),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0051_GREEN_YOSHI_WALK,
            sequence=12,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        MoveObject(
            speed=1,
            start_position=-513,
            end_position=-513,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=1024,
            end_position=1024,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        RemoveObject(),
        ResetObjectMappingMemory(),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35d9c8"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0518_SMALL_WHITE_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35d9e5"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-3,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0518_SMALL_WHITE_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6C, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35da02"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=3,
            y=4,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0518_SMALL_WHITE_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=68, identifier="queuestart_0x35da1f"
        ),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=20,
            y=-10,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0518_SMALL_WHITE_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0562_YELLOW_REUSABLE_ITEM_SPRITE_WITH_LETTER_I,
            sequence=0,
            store_to_vram=True,
            looping=True,
            store_palette=True,
        ),
        MoveObject(
            speed=1,
            start_position=-97,
            end_position=-97,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Pause1Frame(identifier="command_0x35da43"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 1, ["command_0x35da43"]),
        RemoveObject(),
        ResetObjectMappingMemory(),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35da51"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=38,
            y=-31,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0518_SMALL_WHITE_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        MoveObject(
            speed=1,
            start_position=512,
            end_position=512,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-1025,
            end_position=-1025,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=3),
        RemoveObject(),
        ResetObjectMappingMemory(),
        SetAMEM8BitToConst(0x6C, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-18,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35da82",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0566_GREEN_ITEM_COLLECTION,
            sequence=9,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-40,
            y=-24,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=512, arch_height=256),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=31),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM8BitTo7E5x(0x6F, 0x7E0041, identifier="queuestart_0x35daac"),
        JmpIfAMEM8BitEqualsConst(0x6F, 128, ["command_0x35dabf"]),
        SetAMEM8BitToConst(0x6F, 2),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6F),
        ReturnSpriteQueue(),
        SetAMEM8BitToConst(0x6F, 1, identifier="command_0x35dabf"),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6F),
        ReturnSpriteQueue(),
        ClearAMEM8Bit(0x6F, identifier="queuestart_0x35dac8"),
        SetAMEMToAMEM8Bit(dest_amem=0xA7, amem=0x6F),
        RemoveObject(),
        Db(bytearray(b"\xd6")),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6F),
        ReturnObjectQueue(),
    ],
)
