# pylint: disable=C0301,C0103

"""referenced by ally_spells Group Hug"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=377,
    script=[
        StartTrackingAllyButtonInputs(identifier="queuestart_0x359f2c"),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6D),
        ClearAMEM8Bit(0x6E),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x359F1A),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        PlaySound(sound=S0066_RECOVER_HP),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x359F1A),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        TimingForOneTieredButtonPress(
            end_accepting_input=30,
            start_accepting_input=0,
            partial_start=25,
            perfect_start=29,
            perfect_end=30,
            destinations=["command_0x359f4e"],
        ),
        PlaySound(sound=S0172_WEAPON_TIMING, channel=4),
        EndTrackingAllyButtonInputs(identifier="command_0x359f4e"),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        ClearAMEM8Bit(0x6E, identifier="queuestart_0x359f5b"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True, set_y=True, set_z=True
        ),
        MoveObject(
            speed=1,
            start_position=-65,
            end_position=-65,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Db(bytearray(b"\x84\x03\x00")),
        DoMaskEffect(INCLINE_1),
        NewEffectObject(effect=EF0063_BLUE_STAR_BUNCHES, playback_off=True),
        Db(bytearray(b"\x8a\x02")),
        ScreenFlash(RED),
        SetAMEM16BitToAMEM(amem=0x68, source_amem=0x8A),
        Db(bytearray(b"\xc5")),
        Layer3On(prop=OVERLAP_NONE, bit_0=True, bpp4=True),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Db(bytearray(b"y\x00\x11\x17\x02")),
        Pause1Frame(identifier="command_0x359f88"),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 1, ["command_0x359f88"]),
        Db(bytearray(b"y\x00\x11\x17\x00")),
        Layer3Off(prop=OVERLAP_NONE, bit_0=True, bpp4=True),
        SetAMEMToAMEM16Bit(dest_amem=0x8A, amem=0x68),
        Db(bytearray(b"\x90")),
        Db(bytearray(b"\xc4")),
        Pause2Frames(),
        Db(bytearray(b"\xc5")),
        ClearEffectIndex(),
        ResetObjectMappingMemory(),
        Db(bytearray(b"\x84\x03\x00")),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        ClearAMEM8Bit(0x6D, identifier="queuestart_0x359fb0"),
        ClearAMEM8Bit(0x6E),
        ClearAMEM16Bit(0x62),
        MuteTimingJmp(["command_0x359fea"], identifier="command_0x359fb6"),
        Db(bytearray(b" \xbb\x01\x00")),
        JmpIfAMEM8BitEqualsConst(0x6B, 1, ["command_0x359fe2"]),
        IncAMEM8Bit(0x6D),
        JmpIfAMEM8BitEqualsConst(0x6D, 2, ["command_0x359fd8"]),
        SetAMEMToAMEM16Bit(dest_amem=0xC4, amem=0x60),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x359F1A),
        Jmp(["command_0x359fe2"]),
        SetAMEMToAMEM16Bit(dest_amem=0xC6, amem=0x60, identifier="command_0x359fd8"),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x359F1A),
        IncAMEM16Bit(0x62, identifier="command_0x359fe2"),
        JmpIfAMEM16BitNotEqualsConst(0x62, 1, ["command_0x359fb6"]),
        Pause1Frame(identifier="command_0x359fea"),
        JmpIfAMEM8BitNotEqualsAMEM(
            amem=0x6E, source_amem=0xCD, destinations=["command_0x359fea"]
        ),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
        ClearAMEM8Bit(0x6D, identifier="queuestart_0x359ffa"),
        SetAMEM16BitToOMEMMain(amem=0x64, omem=0x64),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0561_BLUE_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x359F1A),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x359F1A),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x359F1A),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6D, 1),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        IncAMEM8Bit(0x6E),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        ClearAMEM8Bit(0x6D, identifier="queuestart_0x35a030"),
        SetAMEM16BitToOMEMMain(amem=0x64, omem=0x66),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=32,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0561_BLUE_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x359F1A),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x359F1A),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x359F1A),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6D, 1),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        IncAMEM8Bit(0x6E),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        SetAMEM16BitToOMEMMain(amem=0x60, omem=0x64, identifier="queuestart_0x35a066"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x35a096"]),
        ReturnObjectQueue(),
        SetAMEM16BitToOMEMMain(amem=0x60, omem=0x64, identifier="queuestart_0x35a076"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-10,
            y=-3,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x35a096"]),
        ReturnObjectQueue(),
        SetAMEM16BitToOMEMMain(amem=0x60, omem=0x64, identifier="queuestart_0x35a086"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=10,
            y=-3,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x35a096"]),
        ReturnObjectQueue(),
        Db(bytearray(b"\x83\x83"), identifier="command_0x35a096"),
        Pause1Frame(identifier="command_0x35a098"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 1, ["command_0x35a098"]),
        RemoveObject(),
        ReturnSubroutine(),
    ],
)
