# pylint: disable=C0301,C0103

"""referenced by monster_attacks 115, monster_attacks Endobubble"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=303,
    script=[
        RunSubroutine(["command_0x353437"], identifier="queuestart_0x353f81"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Db(bytearray(b"\x84\x03\x00")),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 5),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x353706),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=150),
        RunSubroutine(["command_0x3533b5"]),
        RunSubroutine(["command_0x35340b"]),
        Db(bytearray(b"\x84\x03\x00")),
        Jmp(["command_0x35252f"]),
        ResetTargetMappingMemory(identifier="queuestart_0x353fad"),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-24,
            y=-36,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3533ea"]),
        Db(bytearray(b"y\x00\x05\x07\x02")),
        NewEffectObject(effect=EF0107_ECHOFINDER, playback_off=True),
        FadeInEffect(duration=1),
        ScreenFlash(RED, 8),
        Layer3On(prop=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        RunSubroutine(["command_0x35336f"]),
        RunSubroutine(["command_0x3533f5"]),
        FadeOutObject(duration=1),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        Layer3Off(prop=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        RunSubroutine(["command_0x353399"]),
        Pause2Frames(),
        Db(bytearray(b"y\x00\x05\x07\x00")),
        ClearEffectIndex(),
        RunSubroutine(["command_0x3533a7"]),
        ReturnObjectQueue(),
        ResetTargetMappingMemory(identifier="queuestart_0x353fe4"),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-10,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        DoMaskEffect(CIRCLE_MASK),
        RunSubroutine(["command_0x35337d"]),
        RunSubroutine(["command_0x3533df"]),
        PlaySound(sound=S0144_LIGHTNING_ORB),
        SetAMEM8BitToConst(0x6A, 0),
        SetAMEM8BitToConst(0x6B, 40),
        SetAMEM8BitToConst(0x6C, 1),
        RunSubroutine(["command_0x353297"]),
        RunSubroutine(["command_0x353416"]),
        RunSubroutine(["command_0x35338b"]),
        RunSubroutine(["command_0x353400"]),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-20,
            y=-20,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x354013",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0771_EGG,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=8,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1280, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        PlaySound(sound=S0084_WALLOP_4),
        NewSpriteAtCoords(
            sprite_id=SPR0519_DRAIN_EXPLOSION,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-20,
            y=-20,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x354047",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0771_EGG,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-8,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1280, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        PlaySound(sound=S0084_WALLOP_4),
        NewSpriteAtCoords(
            sprite_id=SPR0519_DRAIN_EXPLOSION,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-20,
            y=-20,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35407b",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0771_EGG,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=16,
            y=-24,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1280, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        PlaySound(sound=S0084_WALLOP_4),
        NewSpriteAtCoords(
            sprite_id=SPR0519_DRAIN_EXPLOSION,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x35252f"]),
    ],
)
