# referenced by

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=1291,
    script=[
        RunSubroutine(["command_0x3a773f"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=128,
            y=128,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0503_BOOSTER,
            sequence=1,
            priority=2,
            vram_address=0x7000,
            palette_row=10,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=352,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a72aa"]),
        VisibilityOn(),
        RunSubroutine(["command_0x3a8354"]),
        RunSubroutine(["command_0x3a7292"]),
        RunSubroutine(["command_0x3a7596"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=200,
            y=96,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a72fc"]),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        DisplayMessage(BATTLE_DIALOGUE, 112),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0050_BOOSTER,
            sequence=4,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a75a4"]),
        RunSubroutine(["command_0x3a7760"]),
        DisplayMessage(BATTLE_DIALOGUE, 114),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        SpriteSequence(sequence=1, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        RunSubroutine(["command_0x3a8322"]),
        RunSubroutine(["command_0x3a72fc"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        DisplayMessage(BATTLE_DIALOGUE, 115),
        SpriteSequence(sequence=4, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=4, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a75c0"]),
        RunSubroutine(["command_0x3a7776"]),
        DisplayMessage(BATTLE_DIALOGUE, 117),
        SpriteSequence(sequence=2, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a75dc"]),
        RunSubroutine(["command_0x3a778c"]),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-65,
            end_position=-65,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-33,
            end_position=-33,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        DisplayMessage(BATTLE_DIALOGUE, 119),
        SpriteSequence(sequence=4, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=4, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a75f8"]),
        RunSubroutine(["command_0x3a77ad"]),
        DisplayMessage(BATTLE_DIALOGUE, 121),
        SpriteSequence(sequence=2, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        DisplayMessage(BATTLE_DIALOGUE, 67),
        SpriteSequence(sequence=4, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=4, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a7622"]),
        RunSubroutine(["command_0x3a77c3"]),
        DisplayMessage(BATTLE_DIALOGUE, 123),
        SpriteSequence(sequence=2, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a763e"]),
        RunSubroutine(["command_0x3a77d9"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0050_BOOSTER,
            sequence=2,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RunSubroutine(["command_0x3a77e4"]),
        PlaySound(sound=S0156_CHOMP_BITE),
        SpriteSequence(sequence=2, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=120),
        DisplayMessage(BATTLE_DIALOGUE, 124),
        SpriteSequence(sequence=13, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=200),
        PauseScriptUntilDialogClosed(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        RunSubroutine(["command_0x3a7668"]),
        RunSubroutine(["command_0x3a77fa"]),
        DisplayMessage(BATTLE_DIALOGUE, 126),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0502_BOOSTER,
            sequence=3,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        SpriteSequence(sequence=3, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        SpriteSequence(sequence=3, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        SpriteSequence(sequence=2, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        DisplayMessage(BATTLE_DIALOGUE, 127),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        RunSubroutine(["command_0x3a7684"]),
        Db(bytearray(b"\xe4")),
        SpriteSequence(sequence=0, looping_on=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=250),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a7729"]),
        RunSubroutine(["command_0x3a771e"]),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=128,
            y=128,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0504_SNIFIT,
            sequence=1,
            priority=2,
            vram_address=0x7A00,
            palette_row=14,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=320,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a72aa"]),
        VisibilityOn(),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=136,
            y=128,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7292"]),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        DisplayMessage(BATTLE_DIALOGUE, 109),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a756c"]),
        RunSubroutine(["command_0x3a773f"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        RunSubroutine(["command_0x3a774a"]),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        RunSubroutine(["command_0x3a7755"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0224_RED_BOMB,
            sequence=1,
            store_to_vram=True,
            looping=True,
            store_palette=True,
        ),
        RunSubroutine(["command_0x3a733e"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        DisplayMessage(BATTLE_DIALOGUE, 113),
        SpriteSequence(sequence=2, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a75b2"]),
        RunSubroutine(["command_0x3a7781"]),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=168,
            y=136,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7292"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        RunSubroutine(["command_0x3a77b8"]),
        DisplayMessage(BATTLE_DIALOGUE, 122),
        SpriteSequence(sequence=2, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a7630"]),
        RunSubroutine(["command_0x3a77ce"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=64,
            end_position=64,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-33,
            end_position=-33,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        RunSubroutine(["command_0x3a764c"]),
        SpriteSequence(sequence=2, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a77ef"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SpriteSequence(sequence=1, looping_on=True),
        RunSubroutine(["command_0x3a7374"]),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a7805"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0504_SNIFIT, sequence=0, store_to_vram=True, store_palette=True
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        SpriteSequence(sequence=0, looping_on=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=70),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=129,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=100),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a771e"]),
        RemoveObject(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x3a7729"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=128,
            y=128,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0504_SNIFIT,
            sequence=1,
            priority=2,
            vram_address=0x7C00,
            palette_row=14,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=320,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a72aa"]),
        VisibilityOn(),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=168,
            y=144,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7292"]),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        DisplayMessage(BATTLE_DIALOGUE, 110),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a757a"]),
        RunSubroutine(["command_0x3a773f"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        RunSubroutine(["command_0x3a774a"]),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        RunSubroutine(["command_0x3a776b"]),
        DisplayMessage(BATTLE_DIALOGUE, 116),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0224_RED_BOMB,
            sequence=2,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a75ce"]),
        RunSubroutine(["command_0x3a7781"]),
        SpriteSequence(sequence=0, looping_on=True, mirror=True),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=232,
            y=136,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7292"]),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a7797"]),
        DisplayMessage(BATTLE_DIALOGUE, 120),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a7606"]),
        RunSubroutine(["command_0x3a77ce"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-33,
            end_position=-33,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-33,
            end_position=-33,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a77ef"]),
        DisplayMessage(BATTLE_DIALOGUE, 125),
        SpriteSequence(sequence=1, looping_on=True),
        RunSubroutine(["command_0x3a7374"]),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a7676"]),
        RunSubroutine(["command_0x3a7805"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=90),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0504_SNIFIT, sequence=0, store_to_vram=True, store_palette=True
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        SpriteSequence(sequence=0, looping_on=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=95),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=129,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=100),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a771e"]),
        RemoveObject(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x3a7734"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=128,
            y=128,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0504_SNIFIT,
            sequence=1,
            priority=2,
            vram_address=0x7E00,
            palette_row=14,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=320,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a72aa"]),
        VisibilityOn(),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=200,
            y=160,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7292"]),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        DisplayMessage(BATTLE_DIALOGUE, 111),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        RunSubroutine(["command_0x3a7588"]),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        RunSubroutine(["command_0x3a774a"]),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        RunSubroutine(["command_0x3a7781"]),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        RunSubroutine(["command_0x3a8354"]),
        RunSubroutine(["command_0x3a7292"]),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=232,
            y=96,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a72fc"]),
        SpriteSequence(sequence=1, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0504_SNIFIT, sequence=0, store_to_vram=True, store_palette=True
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=32),
        DisplayMessage(BATTLE_DIALOGUE, 118),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a75ea"]),
        RunSubroutine(["command_0x3a77ce"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-65,
            end_position=-65,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=32,
            end_position=32,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SpriteSequence(sequence=1, looping_off=True),
        RunSubroutine(["command_0x3a77ef"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SpriteSequence(sequence=1, looping_on=True),
        RunSubroutine(["command_0x3a7374"]),
        SpriteSequence(sequence=1, looping_off=True),
        RunSubroutine(["command_0x3a7805"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=150),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        SpriteSequence(sequence=0, looping_on=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=125),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=129,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=100),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a755e"]),
        RemoveObject(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x3a7999"]),
        NewSpriteAtCoords(
            sprite_id=SPR0795_LIGHT_GREEN_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x3a7999"]),
        NewSpriteAtCoords(
            sprite_id=SPR0795_LIGHT_GREEN_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x3a7999"]),
        NewSpriteAtCoords(
            sprite_id=SPR0795_LIGHT_GREEN_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        ReturnObjectQueue(),
    ],
)
