# pylint: disable=C0301,C0103

"""referenced by battle_events BE0007_COUNTDOWN_RUNS_SCHEDULE_1_00_3_00_5_00_6_00_7_00, battle_events BE0008_COUNTDOWN_RUNS_SCHEDULE_6_00_9_00_10_00_12_00"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=391,
    script=[
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=224,
            y=98,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a9532"),
        NewSpriteAtCoords(
            sprite_id=SPR0226_TINY_STAR,
            sequence=0,
            priority=3,
            vram_address=0x7000,
            palette_row=10,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        RunSubroutine(["command_0x3a771e"]),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=136,
            y=152,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a9548"),
        DisplayMessage(BATTLE_DIALOGUE, 53),
        NewSpriteAtCoords(
            sprite_id=SPR0012_TOADSTOOL_FALLEN_CRYING,
            sequence=0,
            priority=3,
            vram_address=0x7400,
            palette_row=14,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        SpriteSequence(sequence=0, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50),
        SpriteSequence(sequence=0, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50),
        SpriteSequence(sequence=0, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50),
        SpriteSequence(sequence=0, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50),
        SpriteSequence(sequence=0, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=50),
        SpriteSequence(sequence=0, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0007_TOADSTOOL_WALKING_DOWN_LEFT,
            sequence=6,
            store_to_vram=True,
            store_palette=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        DisplayMessage(BATTLE_DIALOGUE, 54),
        SpriteSequence(sequence=8, looping_on=True),
        PauseScriptUntilDialogClosed(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        DisplayMessage(BATTLE_DIALOGUE, 55),
        SpriteSequence(sequence=0, looping_on=True),
        RunSubroutine(["command_0x3a8106"]),
        RunSubroutine(["command_0x3a72da"]),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SpriteSequence(sequence=6, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0009_TOADSTOOL_SURPRISE,
            sequence=0,
            store_to_vram=True,
            store_palette=True),
        DisplayMessage(BATTLE_DIALOGUE, 56),
        RunSubroutine(["command_0x3a7374"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0007_TOADSTOOL_WALKING_DOWN_LEFT,
            sequence=0,
            store_to_vram=True,
            store_palette=True),
        PauseScriptUntilDialogClosed(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0012_TOADSTOOL_FALLEN_CRYING,
            sequence=1,
            store_to_vram=True,
            looping=True,
            store_palette=True),
        DisplayMessage(BATTLE_DIALOGUE, 57),
        PauseScriptUntilDialogClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        RunSubroutine(["command_0x3a7588"]),
        RunSubroutine(["command_0x3a771e"]),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=224,
            y=98,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a95da"),
        NewSpriteAtCoords(
            sprite_id=SPR0226_TINY_STAR,
            sequence=0,
            priority=3,
            vram_address=0x7000,
            palette_row=10,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        RunSubroutine(["command_0x3a771e"]),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=235,
            y=115,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a95f0"),
        NewSpriteAtCoords(
            sprite_id=SPR0000_MARIO_WALKING_DOWN_LEFT,
            sequence=0,
            priority=3,
            vram_address=0x7200,
            palette_row=12,
            param_2_and_0x10=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        RunSubroutine(["command_0x3a7734"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=-65,
            end_position=-65,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        VisibilityOn(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a771e"]),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=136,
            y=146,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3a9625"),
        NewSpriteAtCoords(
            sprite_id=SPR0008_TOADSTOOL_WALKING_UP_RIGHT,
            sequence=0,
            priority=3,
            vram_address=0x7400,
            palette_row=14,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        RunSubroutine(["command_0x3a757a"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        DisplayMessage(BATTLE_DIALOGUE, 56),
        SpriteSequence(sequence=3),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        DisplayMessage(BATTLE_DIALOGUE, 58),
        PauseScriptUntilDialogClosed(),
        SpriteSequence(sequence=0, looping_on=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=9,
            start_position=576,
            end_position=0,
            apply_to_x=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=5,
            start_position=-257,
            end_position=0,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SpriteSequence(sequence=0, looping_off=True),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        DisplayMessage(BATTLE_DIALOGUE, 59),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=80,
            end_position=80,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=-33,
            end_position=-33,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetObjectMappingMemory(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0007_TOADSTOOL_WALKING_DOWN_LEFT,
            sequence=1,
            store_to_vram=True,
            store_palette=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=7, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=7, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntilDialogClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        DisplayMessage(BATTLE_DIALOGUE, 60),
        SpriteSequence(sequence=9, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=9, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        PauseScriptUntilDialogClosed(),
        RunSubroutine(["command_0x3a7588"]),
        RunSubroutine(["command_0x3a771e"]),
        RemoveObject(),
        ReturnObjectQueue(),
    ])
