# referenced by items Bracer

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(expected_size = 205, script = [
	ClearAMEM16Bit(0x60, identifier="queuestart_0x35d208"),
	ClearAMEM8Bit(0x6F),
	SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
	JmpIfAMEM8BitGreaterOrEqualThanConst(0x6E, 1, ["command_0x35d21b"]),
	PlaySound(sound=S0076_STAT_BOOST_SINGLE),
	Jmp(["command_0x35d21d"]),
	PlaySound(sound=S0077_STAT_BOOST_MULTI, identifier="command_0x35d21b"),
	ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35D1FE, identifier="command_0x35d21d"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35D1FE),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35D1FE),
	Pause1Frame(identifier="command_0x35d231"),
	JmpIfAMEM8BitNotEqualsConst(0x6F, 3, ["command_0x35d231"]),
	SetAMEM60ToCurrentTarget(),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=4, y=-38, z=0, set_x=True, set_y=True, set_z=True),
	SetAMEM8BitToAMEM(amem=0x67, source_amem=0xCE),
	InitializeBonusMessageSequence(),
	PlaySound(sound=S0006_BONUS_FLOWER_STATUS_UP),
	JmpIfAMEM8BitGreaterOrEqualThanConst(0x67, 1, ["command_0x35d256"]),
	DisplayBonusMessage(message=BM_ATTACK, x=1, y=0),
	Jmp(["command_0x35d25b"]),
	DisplayBonusMessage(message=BM_ATTACK, x=0, y=-2, identifier="command_0x35d256"),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12, identifier="command_0x35d25b"),
	DisplayBonusMessage(message=BM_ATTACK, x=2, y=0),
	PauseScriptUntilBonusMessageComplete(),
	JmpIfAMEM8BitLessThanConst(0x67, 2, ["command_0x35d27d"]),
	InitializeBonusMessageSequence(),
	PlaySound(sound=S0006_BONUS_FLOWER_STATUS_UP),
	DisplayBonusMessage(message=BM_ATTACK, x=1, y=0),
	PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
	DisplayBonusMessage(message=BM_ATTACK, x=2, y=0),
	PauseScriptUntilBonusMessageComplete(),
	SetAMEM8BitToConst(0x6F, 1, identifier="command_0x35d27d"),
	SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
	ReturnObjectQueue(),
	SetAMEM60ToCurrentTarget(identifier="queuestart_0x35d286"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=-8, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0530_STAT_BOOST_ARROWS, sequence=0, priority=3, vram_address=0x6200, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	RunSubroutine(["command_0x35d2c8"]),
	ReturnObjectQueue(),
	SetAMEM60ToCurrentTarget(identifier="queuestart_0x35d29c"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=8, y=-8, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0530_STAT_BOOST_ARROWS, sequence=0, priority=3, vram_address=0x6400, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	RunSubroutine(["command_0x35d2c8"]),
	ReturnObjectQueue(),
	SetAMEM60ToCurrentTarget(identifier="queuestart_0x35d2b2"),
	SetAMEM32ToXYZCoords(origin=TARGET_CURRENT_POSITION, x=0, y=-24, z=0, set_x=True, set_y=True, set_z=True),
	NewSpriteAtCoords(sprite_id=SPR0530_STAT_BOOST_ARROWS, sequence=0, priority=3, vram_address=0x6600, palette_row=0, overwrite_vram=True, overwrite_palette=True, overlap_all_sprites=True),
	RunSubroutine(["command_0x35d2c8"]),
	ReturnObjectQueue(),
	PauseScriptUntilSpriteSequenceDone(identifier="command_0x35d2c8"),
	RemoveObject(),
	SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6F),
	IncAMEM8Bit(0x6F),
	SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
	ReturnSubroutine()
])
