# pylint: disable=C0301,C0103

"""referenced by ally_spells Come Back"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=421,
    script=[
        StartTrackingAllyButtonInputs(identifier="queuestart_0x35a4fb"),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35A4E7),
        PlaySound(sound=S0190_COME_BACK),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=96,
            y=-192,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        NewSpriteAtCoords(
            sprite_id=SPR0522_COME_BACK_RAINBOW_STAR,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        ShineEffect(
            colour_count=7, starting_colour_index=1, glow_duration=2, east=True
        ),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=88,
            y=-176,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=384, arch_height=0),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35A4E7),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35A4E7),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=80,
            y=-160,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=384, arch_height=0),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x35A4E7),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35A4E7),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=72,
            y=-144,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=384, arch_height=0),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35A4E7),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x35A4E7),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=64,
            y=-128,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=384, arch_height=0),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35A4E7),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x35A4E7),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=56,
            y=-112,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=384, arch_height=0),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35A4E7),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35A4E7),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=48,
            y=-96,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=384, arch_height=0),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35A4E7),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x35A4E7),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=40,
            y=-80,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=384, arch_height=0),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35A4E7),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35A4E7),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=32,
            y=-64,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=384, arch_height=0),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x35A4E7),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35A4E7),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=24,
            y=-48,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=384, arch_height=0),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x35A4E7),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35A4E7),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=16,
            y=-32,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=384, arch_height=0),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35A4E7),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35A4E7),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=8,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=384, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        TimingForOneBinaryButtonPress(
            end_accepting_input=30,
            start_accepting_input=0,
            timed_hit_ends=30,
            destinations=["command_0x35a66a"]),
        PlaySound(sound=S0172_WEAPON_TIMING, channel=4),
        EndTrackingAllyButtonInputs(identifier="command_0x35a66a"),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0522_COME_BACK_RAINBOW_STAR,
            sequence=1,
            store_to_vram=True,
            store_palette=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=18),
        ClearAMEM16Bit(0x60),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35A4E7),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        Db(bytearray(b"\x81")),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6C),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35CF29),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        ScreenEffect(SEF0008_COME_BACK, identifier="queuestart_0x35a692"),
        Db(bytearray(b"\xa8\x02\x00")),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
    ])
