# pylint: disable=C0301,C0103

"""referenced by behaviour_33_0x350C5B, behaviour_34_0x350C9E, behaviour_51_0x350F56, behaviour_24_0x350A9C, behaviour_8_0x3507A2, behaviour_41_0x350DAF, behaviour_16_0x350928, behaviour_32_0x350C14, behaviour_52_0x350F6B, weapons LuckyHammer, weapons Masher, behaviour_23_0x350A55, weapons Hammer, behaviour_9_0x3507E9, behaviour_42_0x350DED, behaviour_43_0x350E38"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=127,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35f13f"),
        NewSpriteAtCoords(
            sprite_id=SPR0031_HAMMER,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        PauseScriptUntilSpriteSequenceDone(),
        Pause1Frame(identifier="command_0x35f151"),
        SetAMEM8BitToOMEMMain(amem=0x63, omem=0x63),
        JmpIfAMEM8BitNotEqualsConst(0x63, 1, ["command_0x35f151"]),
        RemoveObject(),
        SetOMEMMainToAMEM8Bit(omem=0x64, amem=0x63),
        ReturnObjectQueue(),
        PlaySound(sound=S0054_HAMMER_HIT_1, identifier="queuestart_0x35f162"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        Pause1Frame(identifier="command_0x35f16c"),
        SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
        JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35f16c"]),
        NewSpriteAtCoords(
            sprite_id=SPR0031_HAMMER,
            sequence=1,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        PauseScriptUntilSpriteSequenceDone(),
        PlaySound(sound=S0055_HAMMER_HIT_2),
        Pause1Frame(identifier="command_0x35f183"),
        SetAMEM8BitToOMEMMain(amem=0x65, omem=0x65),
        JmpIfAMEM8BitNotEqualsConst(0x65, 1, ["command_0x35f183"]),
        RemoveObject(),
        ReturnObjectQueue(),
        PlaySound(sound=S0054_HAMMER_HIT_1, identifier="queuestart_0x35f190"),
        Pause1Frame(identifier="command_0x35f192"),
        SetAMEM8BitToOMEMMain(amem=0x64, omem=0x64),
        JmpIfAMEM8BitNotEqualsConst(0x64, 1, ["command_0x35f192"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=4,
            y=-38,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        InitializeBonusMessageSequence(),
        PlaySound(sound=S0006_BONUS_FLOWER_STATUS_UP),
        DisplayBonusMessage(message=BM_ATTACK, x=6, y=0),
        PauseScriptUntilBonusMessageComplete(),
        SetAMEM8BitTo7E1x(0x6F, 0x7EFA1F),
        SetAMEMBits(0x6F, [0]),
        Set7E1xToAMEM8Bit(0x7EFA1F, 0x6F),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
    ])
