# pylint: disable=C0301,C0103

"""referenced by monster_attacks Vigorup, monster_attacks PhysicalAttack51, monster_attacks SporeChimes, monster_attacks Toxicyst, monster_attacks Elegy, monster_attacks IronMaiden, monster_attacks InkBlast, monster_attacks DoomReverb, monster_attacks Fangs, monster_attacks Quicksilver, monster_attacks Backfire, monster_attacks VenomDrool, monster_attacks MushFunk, monster_attacks PhysicalAttack21, monster_attacks PhysicalAttack46, monster_attacks FunRun, monster_attacks ViroPlasm, monster_attacks Echofinder, monster_attacks ScrowDust, monster_attacks PhysicalAttack50, monster_attacks PollenNap, monster_attacks PhysicalAttack28, monster_attacks CarniKiss, monster_attacks Poison, monster_attacks FearRoulette, monster_attacks 126, monster_attacks PhysicalAttack105, monster_attacks PhysicalAttack57, monster_attacks PhysicalAttack40, monster_attacks DarkClaw, monster_attacks PhysicalAttack29, monster_attacks PhysicalAttack115, monster_attacks BodySlam, monster_attacks RoyalFlush, monster_attacks FullHouse, monster_attacks PhysicalAttack85, monster_attacks PhysicalAttack47, monster_attacks PhysicalAttack56, monster_attacks GunkBall, monster_attacks Howl, monster_attacks Scream, monster_attacks SpritzBomb, monster_attacks Stench, monster_attacks PsychoPlasm, monster_attacks Sporocyst, monster_attacks VaVaVoom, monster_attacks PhysicalAttack31, monster_attacks GetTough, monster_attacks WildCard, monster_attacks 122, monster_attacks PhysicalAttack86, monster_attacks Migraine, monster_attacks PhysicalAttack94, monster_attacks PhysicalAttack91, monster_attacks PhysicalAttack27, monster_attacks Blazer, monster_attacks PhysicalAttack93, monster_attacks Scythe, monster_attacks Sickle, monster_attacks Endobubble, monster_attacks LullaBye"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=209,
    script=[
        ResetTargetMappingMemory(identifier="command_0x357b73"),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"D8")),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=1024, arch_height=64),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=-16,
            y=8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x357b83"),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=512, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
        ResetTargetMappingMemory(identifier="command_0x357b97"),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"D8")),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=512, arch_height=128),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        PlaySound(sound=S0111_SLEDGE),
        ResetObjectMappingMemory(),
        SetAMEM16BitToConst(0x60, 10),
        ResetSpriteSequence(),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ReturnSubroutine(),
        SpriteSequence(sequence=0, looping_on=True, identifier="command_0x357bb8"),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=16,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=2048, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        SpriteSequence(sequence=3),
        ResetObjectMappingMemory(),
        MoveObject(
            speed=1,
            start_position=512,
            end_position=0,
            apply_to_x=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=0,
            apply_to_y=True,
            should_set_speed=True),
        MoveObject(
            speed=65,
            start_position=-513,
            end_position=256,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=128,
            y=160,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x357bef"),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=512, arch_height=128),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        PlaySound(sound=S0149_ENEMY_JUMPS_HIGH),
        MoveObject(
            speed=17,
            start_position=-1281,
            end_position=0,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        ResetObjectMappingMemory(),
        ReturnSubroutine(),
        SpriteSequence(sequence=4, identifier="command_0x357c11"),
        ShakeScreen(amount=5, speed=8),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        PlaySound(sound=S0110_HUGE_EXPLOSION),
        ClearAMEM8Bit(0x68),
        ClearAMEM8Bit(0x60),
        SetAMEM16BitToConst(0x60, 1),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35624B),
        StopShakingObject(),
        RunSubroutine(["command_0x352552"]),
        PlaySound(sound=S0110_HUGE_EXPLOSION),
        ClearAMEM8Bit(0x68),
        ClearAMEM8Bit(0x60),
        SetAMEM16BitToConst(0x60, 1),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35624B),
        StopShakingObject(),
        RunSubroutine(["command_0x352552"]),
        ResetSpriteSequence(),
        ReturnSubroutine(),
    ])
