# pylint: disable=C0301,C0103

"""referenced by monster_spells WillyWisp, monster_spells LightningOrb"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=453,
    script=[
        RunSubroutine(["command_0x353437"], identifier="queuestart_0x3543c7"),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=-32,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        EnableSpritesOnSubscreen(),
        NewSpriteAtCoords(
            sprite_id=SPR0772_LIGHTNING_ORB_BLUE_LIGHTNING_BALL,
            sequence=0,
            priority=0,
            vram_address=0x6200,
            palette_row=8,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        FadeInSprite(duration=2),
        VisibilityOn(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=17,
            start_position=-257,
            end_position=0,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        RunSubroutine(["command_0x357f48"]),
        RemoveObject(),
        Db(bytearray(b"\x84\x03\x00")),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 8),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x353706),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=150),
        RunSubroutine(["command_0x3533b5"]),
        RunSubroutine(["command_0x35340b"]),
        Db(bytearray(b"\x84\x03\x00")),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x354418",
        ),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-1025,
            end_position=-1025,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        RunSubroutine(["command_0x3533ea"]),
        NewEffectObject(effect=EF0106_LIGHTNING_ORB__BG_WAVES_, playback_off=True),
        FadeInEffect(duration=1),
        ScreenFlash(RED, 8),
        Layer3On(prop=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        RunSubroutine(["command_0x35336f"]),
        RunSubroutine(["command_0x3533f5"]),
        FadeOutObject(duration=1),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(prop=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        RunSubroutine(["command_0x353399"]),
        Pause2Frames(),
        ClearEffectIndex(),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3533a7"]),
        ReturnObjectQueue(),
        ResetTargetMappingMemory(identifier="queuestart_0x35444d"),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-10,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        DoMaskEffect(DOME_MASK),
        RunSubroutine(["command_0x35337d"]),
        RunSubroutine(["command_0x3533df"]),
        PlaySound(sound=S0144_LIGHTNING_ORB),
        SetAMEM8BitToConst(0x6A, 0),
        SetAMEM8BitToConst(0x6B, 35),
        SetAMEM8BitToConst(0x6C, 1),
        RunSubroutine(["command_0x353297"]),
        RunSubroutine(["command_0x353416"]),
        RunSubroutine(["command_0x35338b"]),
        RunSubroutine(["command_0x353400"]),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x353437"], identifier="queuestart_0x35447c"),
        Db(bytearray(b"\x84\x03\x00")),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SetAMEM16BitToConst(0x60, 8),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x353706),
        RunSubroutine(["command_0x353416"]),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x353706),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x353706),
        RunSubroutine(["command_0x35340b"]),
        RunSubroutine(["command_0x3533c3"]),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 11),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x355F1D),
        RunSubroutine(["command_0x352552"]),
        RunSubroutine(["command_0x3533f5"]),
        Db(bytearray(b"\x84\x03\x00")),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3544ba",
        ),
        DoMaskEffect(CYLINDER_MASK),
        RunSubroutine(["command_0x35336f"]),
        RunSubroutine(["command_0x3533ea"]),
        SetAMEM8BitToConst(0x6A, 0),
        SetAMEM8BitToConst(0x6B, 30),
        SetAMEM8BitToConst(0x6C, 1),
        RunSubroutine(["command_0x353297"]),
        RunSubroutine(["command_0x3533a7"]),
        RunSubroutine(["command_0x3533f5"]),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3544e2",
        ),
        NewEffectObject(effect=EF0028_WILLY_WISP__BLUE_ORB_BALL_BG_, playback_off=True),
        RunSubroutine(["command_0x3533df"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-2049,
            end_position=-2049,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-2049,
            end_position=-2049,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        FadeInEffect(duration=2),
        ScreenFlash(RED, 8),
        Layer3On(prop=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        RunSubroutine(["command_0x35337d"]),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        RunSubroutine(["command_0x353400"]),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(prop=OVERLAP_ALL_EXCEPT_ALLIES, bpp4=True),
        Db(bytearray(b"\x90")),
        RunSubroutine(["command_0x35338b"]),
        Pause2Frames(),
        ResetObjectMappingMemory(),
        ClearEffectIndex(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=128,
            y=128,
            z=-96,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x354520",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0548_WILLY_WISP_PURPLE_ELECTRIC_BALL,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=65,
            start_position=1536,
            end_position=4096,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        VisibilityOff(),
        PlaySound(sound=S0170_SUBMERGED_UNDER),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 11),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x355F1D),
        RunSubroutine(["command_0x352552"]),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1024, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3533b5"]),
        RunSubroutine(["command_0x353421"]),
        RunSubroutine(["command_0x3533d1"]),
        VisibilityOn(),
        PlaySound(sound=S0118_GENO_BLAST_END),
        PlaySound(sound=S0069_GENO_POWER_UP),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=65,
            start_position=-1025,
            end_position=-4097,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x353399"]),
        RemoveObject(),
        ReturnObjectQueue(),
    ],
)
