# referenced by battle_events BE0054_CLOAKER_TEAMS_UP_WITH_EARTHLINK, battle_events BE0048_VALENTINA_SUMMONS_DODO_DODO_CARRIES_OFF_MIDDLE_CHARACTER, battle_events BE0050_DODO_RETURNS_TO_VALENTINA_S_FORMATION, battle_events BE0049_DODO_FLUTTERS_AND_LEAVES_BATTLE, battle_events BE0053_DOMINO_TEAMS_UP_WITH_MAD_ADDER, battle_events BE0097_SMITHY_WAITS_BEFORE_TRANSFORMING_HEAD, battle_events BE0047_UNKNOWN, battle_events BE0096_NOTHING, battle_events BE0091_SMITHY_S_HEAD_FADES_BEFORE_TRANSFORMING_INTO_OTHER_HEAD

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=1964,
    script=[
        RunSubroutine(["command_0x3a771e"], identifier="queuestart_0x3acf48"),
        ReturnSpriteQueue(),
        SetAMEM8BitTo7E5x(0x60, 0x7E0041, identifier="queuestart_0x3acf4c"),
        SetAMEMBits(0x60, [7]),
        Set7E5xToAMEM8Bit(0x7E0041, 0x60),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        Pause1Frame(identifier="queuestart_0x3acf5b"),
        Pause1Frame(),
        Pause1Frame(),
        PauseScriptUntilDialogueClosed(),
        RunSubroutine(["command_0x3a756c"]),
        RunSubroutine(["command_0x3a773f"]),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=-256, z=0, set_y=True),
        RunSubroutine(["command_0x3a7544"]),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        SpriteSequence(sequence=6, looping_on=True, identifier="queuestart_0x3acf74"),
        RunSubroutine(["command_0x3a7729"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SpriteSequence(sequence=5),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        PlaySound(sound=S0021_SCARECROW_BIRDIES),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SpriteSequence(sequence=7, looping_on=True),
        RunSubroutine(["command_0x3aa6f6"]),
        RunSubroutine(["command_0x3a727a"]),
        RunSubroutine(["command_0x3a757a"]),
        PlaySound(sound=S0021_SCARECROW_BIRDIES),
        SpriteSequence(sequence=4),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-769,
            end_position=-769,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=384,
            end_position=384,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=17,
            start_position=-1025,
            end_position=-2049,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=45),
        ResetObjectMappingMemory(),
        Db(bytearray(b"\xc8\x01")),
        RunSubroutine(["command_0x3a7588"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=240,
            y=16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        Db(bytearray(b"\xc7\x01")),
        RunSubroutine(["command_0x3a7596"]),
        PlaySound(sound=S0021_SCARECROW_BIRDIES),
        SpriteSequence(sequence=4),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=17,
            start_position=256,
            end_position=512,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0087_BIG_BOUNCE),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=129,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0087_BIG_BOUNCE),
        MoveObject(
            speed=257,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0087_BIG_BOUNCE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SpriteSequence(sequence=6, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=184,
            y=128,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7307"]),
        ResetSpriteSequence(),
        SetAMEM8BitToConst(0x60, 184),
        SetAMEM8BitToConst(0x61, 128),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        RunSubroutine(["command_0x3a7544"]),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a773f"], identifier="queuestart_0x3ad040"),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=-256, z=0, set_y=True),
        RunSubroutine(["command_0x3a771e"]),
        SetAMEM8BitTo7E1x(0x60, 0x7EFA80),
        SetAMEMBits(0x60, [7]),
        Set7E1xToAMEM8Bit(0x7EFA80, 0x60),
        Db(bytearray(b"\x16"), identifier="command_0x3ad059"),
        Pause1Frame(),
        SetAMEM8BitTo7E1x(0x67, 0x7EE00F),
        JmpIfAMEMBitsClear(0x67, [0], ["command_0x3ad059"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SetAMEM8BitTo7E1x(0x60, 0x7EFA80),
        ClearAMEMBits(0x60, [7]),
        Set7E1xToAMEM8Bit(0x7EFA80, 0x60),
        RunSubroutine(["command_0x3a7544"]),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7734"], identifier="queuestart_0x3ad07e"),
        SpriteSequence(sequence=3, looping_off=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-769,
            end_position=-769,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=384,
            end_position=384,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=17,
            start_position=-1025,
            end_position=-2049,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=45),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a774a"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=224,
            y=24,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=17,
            start_position=256,
            end_position=512,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=129,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=257,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        SpriteSequence(sequence=8),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        RunSubroutine(["command_0x3a71da"]),
        RunSubroutine(["command_0x3a7544"]),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a773f"], identifier="queuestart_0x3ad11c"),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=-256, z=0, set_y=True),
        RunSubroutine(["command_0x3a771e"]),
        SetAMEM8BitTo7E1x(0x60, 0x7EFB80),
        SetAMEMBits(0x60, [7]),
        Set7E1xToAMEM8Bit(0x7EFB80, 0x60),
        Db(bytearray(b"\x16"), identifier="command_0x3ad135"),
        Pause1Frame(),
        SetAMEM8BitTo7E1x(0x67, 0x7EE00F),
        JmpIfAMEMBitsClear(0x67, [0], ["command_0x3ad135"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SetAMEM8BitTo7E1x(0x60, 0x7EFB80),
        ClearAMEMBits(0x60, [7]),
        Set7E1xToAMEM8Bit(0x7EFB80, 0x60),
        RunSubroutine(["command_0x3a7544"]),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        RemoveObject(identifier="queuestart_0x3ad15a"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=199,
            y=151,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0312_DODO_ND_TIME,
            sequence=0,
            priority=2,
            vram_address=0x7800,
            palette_row=12,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=Dodo, position=1, bit_7=True),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        Pause1Frame(identifier="queuestart_0x3ad174"),
        SetAMEM8BitTo7E1x(0x67, 0x7EE00F),
        JmpIfAMEMBitsClear(0x67, [0], ["queuestart_0x3ad174"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Db(bytearray(b"\xc7\x01")),
        RunSubroutine(["command_0x3a7544"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        PlaySound(sound=S0021_SCARECROW_BIRDIES, identifier="queuestart_0x3ad193"),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        SetSequenceSpeed(2),
        SpriteSequence(sequence=1, looping_on=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=1024,
            end_position=1024,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-513,
            end_position=-513,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        RunSubroutine(["command_0x3a756c"]),
        RunSubroutine(["command_0x3a7544"]),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3ad1c0"),
        SetSequenceSpeed(2),
        SpriteSequence(sequence=0, looping_on=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=512,
            end_position=512,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0004_JUMP),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=512,
            end_position=512,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=97,
            start_position=-1537,
            end_position=1536,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0004_JUMP),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=512,
            end_position=512,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=65,
            start_position=-1537,
            end_position=1536,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        SetSequenceSpeed(1),
        Db(bytearray(b"\xc8\x01")),
        SetAMEM8BitTo7E1x(0x60, 0x7EE00F),
        SetAMEMBits(0x60, [0]),
        Set7E1xToAMEM8Bit(0x7EE00F, 0x60),
        SetAMEM8BitTo7E1x(0x60, 0x7EFB00),
        SetAMEMBits(0x60, [7]),
        Set7E1xToAMEM8Bit(0x7EFB00, 0x60),
        Db(bytearray(b"\x16"), identifier="command_0x3ad23f"),
        Pause1Frame(),
        SetAMEM8BitTo7E1x(0x67, 0x7EE00F),
        JmpIfAMEMBitsClear(0x67, [1], ["command_0x3ad23f"]),
        SpriteSequence(sequence=1, looping_on=True, mirror=True),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=16,
            y=64,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=17,
            start_position=256,
            end_position=1024,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0004_JUMP),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=64,
            end_position=64,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=81,
            start_position=-1537,
            end_position=1536,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0004_JUMP),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=64,
            end_position=64,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=113,
            start_position=-1537,
            end_position=1536,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0004_JUMP),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SpriteSequence(sequence=1, looping_on=True),
        RunSubroutine(["command_0x3a71da"]),
        SpriteSequence(sequence=1, looping_off=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=1, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        SpriteSequence(sequence=0, looping_off=True),
        SetAMEM8BitTo7E1x(0x60, 0x7EFB00),
        ClearAMEMBits(0x60, [7]),
        Set7E1xToAMEM8Bit(0x7EFB00, 0x60),
        RunSubroutine(["command_0x3a7544"]),
        Db(bytearray(b"m")),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=32,
            y=16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3ad2e0",
        ),
        PlaySound(sound=S0021_SCARECROW_BIRDIES),
        SpriteSequence(sequence=4, mirror=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=384,
            end_position=384,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=17,
            start_position=512,
            end_position=2048,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0087_BIG_BOUNCE),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=384,
            end_position=384,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=129,
            start_position=-1537,
            end_position=1536,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0087_BIG_BOUNCE),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=384,
            end_position=384,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=193,
            start_position=-1537,
            end_position=1536,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PlaySound(sound=S0087_BIG_BOUNCE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SpriteSequence(sequence=6, looping_on=True, mirror=True),
        Pause1Frame(),
        Pause1Frame(),
        Pause1Frame(),
        PauseScriptUntilDialogueClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        PlaySound(sound=S0021_SCARECROW_BIRDIES),
        SpriteSequence(sequence=4, mirror=True),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=6, looping_on=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        SpriteSequence(sequence=5, looping_off=True, mirror=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SetAMEM8BitTo7E1x(0x60, 0x7EE00F),
        SetAMEMBits(0x60, [1]),
        Set7E1xToAMEM8Bit(0x7EE00F, 0x60),
        SetSequenceSpeed(3),
        SpriteSequence(sequence=1, looping_on=True),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=199,
            y=151,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a7292"]),
        SetSequenceSpeed(1),
        ResetSpriteSequence(),
        SetAMEM8BitToConst(0x60, 199),
        SetAMEM8BitToConst(0x61, 151),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        RunSubroutine(["command_0x3a7544"]),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        DisplayMessage(BATTLE_DIALOGUE, 157),
        SpriteSequence(sequence=3),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntilDialogueClosed(),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        RunSubroutine(["command_0x3a756c"]),
        RunSubroutine(["command_0x3a7734"]),
        DisplayMessage(BATTLE_DIALOGUE, 158),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        PauseScriptUntilDialogueClosed(),
        SpriteSequence(sequence=0, looping_on=True),
        DisplayMessage(BATTLE_DIALOGUE, 160),
        PauseScriptUntilDialogueClosed(),
        RunSubroutine(["command_0x3a7588"]),
        RunSubroutine(["command_0x3a774a"]),
        DisplayMessage(BATTLE_DIALOGUE, 161),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntilDialogueClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        RunSubroutine(["command_0x3a75a4"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=17,
            start_position=-257,
            end_position=-2049,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        Db(bytearray(b"Z")),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"]),
        PlaySound(sound=S0021_SCARECROW_BIRDIES),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=6, looping_on=True),
        RunSubroutine(["command_0x3a757a"]),
        RunSubroutine(["command_0x3a773f"]),
        SpriteSequence(sequence=5),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        SpriteSequence(sequence=7, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=120),
        PlaySound(sound=S0021_SCARECROW_BIRDIES),
        SpriteSequence(sequence=4),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=33,
            start_position=-513,
            end_position=-2049,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetObjectMappingMemory(),
        SpriteSequence(sequence=5, looping_on=True),
        RunSubroutine(["command_0x3a7596"]),
        RunSubroutine(["command_0x3a7755"]),
        PlaySound(sound=S0021_SCARECROW_BIRDIES),
        SpriteSequence(sequence=4, looping_on=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=17,
            start_position=-257,
            end_position=-2049,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a85b6"], identifier="queuestart_0x3ad456"),
        RunSubroutine(["command_0x3a72e6"]),
        DisplayMessage(BATTLE_DIALOGUE, 233),
        SpriteSequence(sequence=3),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogueClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=384,
            end_position=384,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-161,
            end_position=-161,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=97,
            start_position=-1537,
            end_position=1536,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=384,
            end_position=384,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-161,
            end_position=-161,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=65,
            start_position=-1537,
            end_position=1536,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        ClearAMEM8Bit(0x60),
        SetAMEMToAMEM8Bit(dest_amem=0xA7, amem=0x60),
        RemoveObject(),
        RunSubroutine(["command_0x3a757a"]),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a85b6"], identifier="queuestart_0x3ad4bb"),
        RunSubroutine(["command_0x3a72e6"]),
        DisplayMessage(BATTLE_DIALOGUE, 232),
        SpriteSequence(sequence=3),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_off=True),
        PauseScriptUntilDialogueClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=384,
            end_position=384,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-161,
            end_position=-161,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=97,
            start_position=-1537,
            end_position=1536,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=384,
            end_position=384,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-161,
            end_position=-161,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=65,
            start_position=-1537,
            end_position=1536,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        ClearAMEM8Bit(0x60),
        SetAMEMToAMEM8Bit(dest_amem=0xA7, amem=0x60),
        RemoveObject(),
        RunSubroutine(["command_0x3a757a"]),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        SpriteSequence(sequence=0, looping_on=True, identifier="queuestart_0x3ad520"),
        RunSubroutine(["command_0x3a7729"]),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        RemoveObject(identifier="queuestart_0x3ad52b"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=184,
            y=128,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0479_MAD_ADDER,
            sequence=0,
            priority=2,
            vram_address=0x7800,
            palette_row=14,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=MadAdder, position=1, bit_7=True),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=128,
            y=-72,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a72ce"]),
        VisibilityOn(),
        RunSubroutine(["command_0x3a773f"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=68,
            end_position=68,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=250),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a7755"]),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        RunSubroutine(["command_0x3a7544"]),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        RemoveObject(identifier="queuestart_0x3ad576"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=184,
            y=128,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0499_EARTH_LINK,
            sequence=0,
            priority=2,
            vram_address=0x7800,
            palette_row=14,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=Earthlink, position=1, bit_7=True),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=128,
            y=-72,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a72ce"]),
        VisibilityOn(),
        RunSubroutine(["command_0x3a773f"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=68,
            end_position=68,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=250),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a7755"]),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        RunSubroutine(["command_0x3a7544"]),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=152,
            y=160,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3ad5c1",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0478_DOMINO_ND_TIME,
            sequence=0,
            priority=2,
            vram_address=0x7000,
            palette_row=10,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=Domino2, position=1, bit_7=True),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=128,
            y=-64,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a72ce"]),
        RunSubroutine(["command_0x3a774a"]),
        VisibilityOn(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=68,
            end_position=68,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=300),
        ResetObjectMappingMemory(),
        DisplayMessage(BATTLE_DIALOGUE, 235),
        SpriteSequence(sequence=3),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntilDialogueClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=304,
            end_position=304,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-153,
            end_position=-153,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=33,
            start_position=-1281,
            end_position=256,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0509_DOMINO_ND_TIME,
            sequence=0,
            priority=2,
            vram_address=0x7000,
            palette_row=10,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        ResetSpriteSequence(),
        PlaySound(sound=S0078_TIMED_STAT_BOOST),
        RunSubroutine(["command_0x3a8753"]),
        RunSubroutine(["command_0x3a75a4"]),
        SetAMEM8BitToConst(0x60, 184),
        SetAMEM8BitToConst(0x61, 128),
        SetAMEM8BitToConst(0x62, 96),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        Set7E5xToAMEM8Bit(0x7E003D, 0x62),
        RunSubroutine(["command_0x3a7544"]),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        RemoveObject(identifier="queuestart_0x3ad65a"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=152,
            y=160,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0477_CLOAKER_ST_TIME,
            sequence=0,
            priority=2,
            vram_address=0x7000,
            palette_row=10,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=Cloaker2, position=1, bit_7=True),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=128,
            y=-64,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x3a72ce"]),
        RunSubroutine(["command_0x3a774a"]),
        VisibilityOn(),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=68,
            end_position=68,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=300),
        ResetObjectMappingMemory(),
        DisplayMessage(BATTLE_DIALOGUE, 234),
        SpriteSequence(sequence=3),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntilDialogueClosed(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=304,
            end_position=304,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-153,
            end_position=-153,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=33,
            start_position=-1281,
            end_position=256,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        ResetObjectMappingMemory(),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0508_CLOAKER_ND_TIME,
            sequence=0,
            priority=2,
            vram_address=0x7000,
            palette_row=10,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        ResetSpriteSequence(),
        PlaySound(sound=S0078_TIMED_STAT_BOOST),
        RunSubroutine(["command_0x3a8753"]),
        RunSubroutine(["command_0x3a75a4"]),
        SetAMEM8BitToConst(0x60, 184),
        SetAMEM8BitToConst(0x61, 128),
        SetAMEM8BitToConst(0x62, 96),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        Set7E5xToAMEM8Bit(0x7E003D, 0x62),
        RunSubroutine(["command_0x3a7544"]),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
    ],
)
