# pylint: disable=C0301,C0103

"""referenced by monster_attacks DarkClaw"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=127,
    script=[
        RunSubroutine(["command_0x353437"], identifier="queuestart_0x354b35"),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        ClearAMEM8Bit(0x60),
        SetAMEM16BitToConst(0x60, 13),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x353706),
        RunSubroutine(["command_0x3533df"]),
        Db(bytearray(b"\xba\x01\x00\x00")),
        ScreenEffect(SEF0011_HOWL),
        Db(bytearray(b"\x9c\x00B(\x00\x08\x00 \x00")),
        ScreenFlash(GREEN, 8),
        Layer3On(prop=TRANSPARENCY_OFF, bit_0=True, bpp4=True, invisible=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=160),
        RunSubroutine(["command_0x35337d"]),
        RunSubroutine(["command_0x3533f5"]),
        Db(bytearray(b"\x9d\x02")),
        Db(bytearray(b"\xba\x01\x01\x00")),
        ScreenEffect(SEF0011_HOWL),
        Layer3Off(prop=TRANSPARENCY_OFF, bpp4=True, invisible=True),
        Db(bytearray(b"\x90")),
        RunSubroutine(["command_0x353399"]),
        Jmp(["command_0x35253b"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-2,
            y=-7,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x354b7d",
        ),
        DoMaskEffect(CIRCLE_MASK),
        RunSubroutine(["command_0x35336f"]),
        SetAMEM8BitToConst(0x6A, 0),
        SetAMEM8BitToConst(0x6B, 25),
        SetAMEM8BitToConst(0x6C, 1),
        RunSubroutine(["command_0x353297"]),
        RunSubroutine(["command_0x3533ea"]),
        SetAMEM8BitToConst(0x6A, 25),
        SetAMEM8BitToConst(0x6B, 0),
        SetAMEM8BitToConst(0x6C, 1),
        RunSubroutine(["command_0x3532b4"]),
        RunSubroutine(["command_0x35338b"]),
        RunSubroutine(["command_0x353400"]),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        ReturnObjectQueue(),
    ],
)
