# pylint: disable=C0301,C0103

"""referenced by monster_attacks SporeChimes, monster_attacks Backfire, monster_attacks FearRoulette, behaviour_24_0x350A9C, monster_attacks PhysicalAttack21, monster_attacks PhysicalAttack46, monster_attacks PhysicalAttack50, monster_spells PetalBlast, monster_spells LightBeam, monster_spells Blast, monster_attacks EerieJig, monster_attacks PhysicalAttack90, monster_spells MegaRecover, monster_spells BigBang, monster_attacks Shaker, monster_attacks DarkClaw, monster_attacks PhysicalAttack29, monster_spells DiamondSaw, monster_attacks PhysicalAttack85, monster_attacks GunkBall, monster_spells Electroshock, monster_spells Blizzard, monster_attacks 128, monster_attacks PhysicalAttack113, monster_attacks 122, monster_attacks WildCard, monster_attacks PhysicalAttack27, monster_attacks Scythe, monster_attacks PhysicalAttack10, monster_attacks PhysicalAttack32, monster_attacks PhysicalAttack115, monster_attacks PhysicalAttack118, monster_attacks PhysicalAttack51, monster_attacks Elegy, monster_attacks Toxicyst, monster_spells Shredder, behaviour_32_0x350C14, monster_attacks VenomDrool, monster_attacks PhysicalAttack116, monster_attacks ScrowDust, monster_attacks PhysicalAttack57, monster_attacks PhysicalAttack40, monster_attacks 118, monster_spells Sledge, monster_spells SandStorm, monster_attacks PhysicalAttack47, behaviour_33_0x350C5B, behaviour_16_0x350928, monster_attacks ScrowBell, monster_spells LightningOrb, behaviour_10_0x350830, monster_attacks PsychoPlasm, monster_spells Boulder, monster_spells SwordRain, monster_attacks PhysicalAttack86, monster_attacks PhysicalAttack93, monster_attacks Jinxed, monster_attacks Sickle, monster_attacks Endobubble, monster_attacks LullaBye, behaviour_44_0x350E4A, monster_spells KnockOut, monster_attacks Vigorup, monster_spells WaterBlast, monster_attacks Fangs, behaviour_8_0x3507A2, monster_spells MegaDrain, monster_attacks DoomReverb, behaviour_46_0x350E98, monster_attacks MushFunk, monster_attacks FunRun, monster_spells IceRock, monster_attacks PollenNap, monster_attacks PhysicalAttack28, monster_spells Crystal, monster_spells DarkStar, monster_attacks PhysicalAttack105, monster_spells Solidify, monster_spells Flame, monster_attacks RoyalFlush, monster_attacks FullHouse, monster_spells Bolt, monster_spells ChainSaw, monster_attacks Psyche, monster_spells Recover, monster_attacks Howl, monster_attacks PhysicalAttack56, monster_attacks Scream, monster_spells StaticE, monster_attacks Stench, monster_attacks Sporocyst, monster_attacks PhysicalAttack31, monster_spells MeteorBlast, monster_attacks PhysicalAttack94, monster_attacks Thornet, monster_attacks PhysicalAttack91, monster_attacks Blazer, monster_spells AuroraFlash, monster_spells Corona, monster_attacks PhysicalAttack81, monster_spells SpearRain, monster_attacks DahliaDance, monster_attacks IronMaiden, monster_attacks InkBlast, monster_attacks Quicksilver, monster_attacks Echofinder, monster_attacks ViroPlasm, behaviour_23_0x350A55, behaviour_37_0x350D36, monster_attacks Skewer, monster_attacks CarniKiss, behaviour_9_0x3507E9, monster_attacks Poison, monster_spells Storm, monster_spells Drain, monster_spells WeirdMushroom, monster_attacks Pierce, monster_attacks BodySlam, monster_attacks TripleKick, monster_spells ArrowRain, behaviour_28_0x350BB7, monster_attacks Magnum, monster_attacks Deathsickle, monster_attacks 115, monster_spells BreakerBeam, behaviour_53_0x350F7A, monster_attacks SpritzBomb, monster_spells DrainBeam, monster_spells WillyWisp, monster_spells FlameStone, monster_attacks VaVaVoom, monster_attacks GetTough, monster_spells FlameWall, monster_spells MeteorSwarm, monster_attacks PhysicalAttack89, monster_attacks Migraine, monster_attacks PhysicalAttack117, monster_attacks 116"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=245,
    script=[
        ClearAMEM8Bit(0x6F, identifier="command_0x352475"),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x353706),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35247f"),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x353706),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x352489"),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x353706),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x352493"),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x353706),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x35249d"),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x353706),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x3524a7"),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x353706),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x3524b1"),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x353706),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x3524bb"),
        PlaySound(sound=S0125_SPIKE_SHOT),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        PlaySound(sound=S0125_SPIKE_SHOT),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        PlaySound(sound=S0125_SPIKE_SHOT),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=16),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ReturnSubroutine(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=8, identifier="command_0x3524df"
        ),
        SpriteSequence(sequence=3),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x353706),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x353706),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x353706),
        PlaySound(sound=S0175_DEATHSICKLE),
        PauseScriptUntilSpriteSequenceDone(),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ResetSpriteSequence(),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F, identifier="command_0x3524fb"),
        PlaySound(sound=S0051_FIRE_THROW_BIG),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        PlaySound(sound=S0051_FIRE_THROW_BIG),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x353706),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        PlaySound(sound=S0051_FIRE_THROW_BIG),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x353706),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ReturnSubroutine(),
        SetOMEM60To072C(identifier="command_0x35251b"),
        DisplayMessageAtOMEM60As(BATTLE_DIALOGUE),
        SpriteSequence(sequence=3),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        ReturnSubroutine(),
        SetOMEM60To072C(identifier="command_0x352523"),
        DisplayMessageAtOMEM60As(BATTLE_DIALOGUE),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        ReturnSubroutine(),
        SetOMEM60To072C(identifier="command_0x35252b"),
        DisplayMessageAtOMEM60As(PSYCHOPATH_MESSAGE),
        ReturnSubroutine(),
        ClearAMEM8Bit(0x6F),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        RemoveObject(),
        ReturnObjectQueue(),
        ClearAMEM8Bit(0x6F),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        Pause1Frame(identifier="command_0x352546"),
        SetAMEM8BitToOMEMMain(amem=0x68, omem=0x68),
        JmpIfAMEM8BitNotEqualsConst(0x68, 1, ["command_0x352546"]),
        ReturnSubroutine(),
        Pause1Frame(identifier="command_0x352552"),
        SetAMEM8BitToAMEM(amem=0x68, source_amem=0xC8),
        JmpIfAMEM8BitNotEqualsConst(0x68, 1, ["command_0x352552"]),
        ReturnSubroutine(),
        Pause1Frame(identifier="command_0x35255e"),
        SetAMEM8BitToAMEM(amem=0x67, source_amem=0xC7),
        JmpIfAMEM8BitNotEqualsConst(0x67, 1, ["command_0x35255e"]),
        ReturnSubroutine(),
    ])
