# referenced by monster_attacks Backfire, monster_attacks VaVaVoom

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=270,
    script=[
        RunSubroutine(["command_0x353437"], identifier="queuestart_0x355e0f"),
        Db(bytearray(b"\x84\x03\x00")),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SetAMEM16BitToConst(0x60, 34),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x353706),
        RunSubroutine(["command_0x3533df"]),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x353706),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x353706),
        RunSubroutine(["command_0x3533f5"]),
        RunSubroutine(["command_0x353400"]),
        RunSubroutine(["command_0x35340b"]),
        Db(bytearray(b"\x84\x03\x00")),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x355e41",
        ),
        NewEffectObject(effect=EF0049_BROWN_FLASH__4BPP_, playback_off=True),
        Jmp(["command_0x355ec2"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-16,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x355e4f",
        ),
        NewEffectObject(effect=EF0085_POLLEN_NAP__YELLOW_POLLEN_, looping_on=True),
        Jmp(["command_0x355ef2"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x355e5d",
        ),
        DoMaskEffect(CYLINDER_MASK),
        RunSubroutine(["command_0x35336f"]),
        RunSubroutine(["command_0x3533ea"]),
        SetAMEM8BitToConst(0x6A, 0),
        SetAMEM8BitToConst(0x6B, 20),
        SetAMEM8BitToConst(0x6C, 1),
        RunSubroutine(["command_0x353297"]),
        RunSubroutine(["command_0x3533f5"]),
        RunSubroutine(["command_0x3533a7"]),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        ReturnObjectQueue(),
        RunSubroutine(["command_0x353437"], identifier="queuestart_0x355e85"),
        Db(bytearray(b"\x84\x03\x00")),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SetAMEM16BitToConst(0x60, 34),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x353706),
        RunSubroutine(["command_0x3533df"]),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x353706),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x353706),
        RunSubroutine(["command_0x3533f5"]),
        RunSubroutine(["command_0x353400"]),
        RunSubroutine(["command_0x35340b"]),
        Db(bytearray(b"\x84\x03\x00")),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x355eb7",
        ),
        NewEffectObject(effect=EF0048_PURPLE_VIOLET_FLASH__4BPP_, playback_off=True),
        RunSubroutine(["command_0x3533c3"], identifier="command_0x355ec2"),
        RunSubroutine(["command_0x353416"]),
        FadeInEffect(duration=2),
        ScreenFlash(RED, 8),
        Layer3On(property=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        RunSubroutine(["command_0x35337d"]),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=80),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(property=OVERLAP_ALL_EXCEPT_ALLIES, bpp4=True),
        Db(bytearray(b"\x90")),
        RunSubroutine(["command_0x35338b"]),
        Pause2Frames(),
        ClearEffectIndex(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-16,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x355ee7",
        ),
        NewEffectObject(effect=EF0094_S__CROW_DUST__PURPLE_POLLEN_, looping_on=True),
        RunSubroutine(["command_0x3533b5"], identifier="command_0x355ef2"),
        RunSubroutine(["command_0x353421"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=768,
            end_position=768,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        FadeInEffect(duration=2),
        Layer3On(property=OVERLAP_ALL_EXCEPT_ALLIES, bit_0=True, bpp4=True),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        PlaySound(sound=S0189_POLLEN_NAP),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=80),
        FadeOutObject(duration=2),
        PauseScriptUntil(condition=FADE_2BPP_COMPLETE),
        Layer3Off(property=OVERLAP_ALL_EXCEPT_ALLIES, bpp4=True),
        Pause2Frames(),
        ResetObjectMappingMemory(),
        ClearEffectIndex(),
        RunSubroutine(["command_0x353399"]),
        ReturnObjectQueue(),
    ],
)
