# referenced by items MysteryEgg

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=249,
    script=[
        ClearAMEM16Bit(0x60, identifier="queuestart_0x35e76d"),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0274_THE_BIG_BOO,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True,
        ),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35E759),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35E759),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35E759),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35E759),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x35E759),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35E759),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35E759),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x35E759),
        PlaySound(sound=S0175_DEATHSICKLE),
        PauseScriptUntilSpriteSequenceDone(),
        SetAMEM8BitToConst(0x6F, 1),
        Pause1Frame(identifier="command_0x35e7ac"),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 8, ["command_0x35e7ac"]),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b" \xbeC\x00")),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 4, ["command_0x35e7cd"]),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-24,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0571_FEAR_EXCLAMATION_POINT,
            sequence=0,
            store_to_vram=True,
            store_palette=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(identifier="command_0x35e7cd"),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35e7d3"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=24,
            y=-40,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x35e83b"]),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35e7e0"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=24,
            y=8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x35e83b"]),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35e7ed"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-24,
            y=-40,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x35e83b"]),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35e7fa"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-24,
            y=8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x35e83b"]),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35e807"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-44,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x35e83b"]),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35e814"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=12,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x35e83b"]),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35e821"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-28,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x35e83b"]),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35e82e"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=28,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        RunSubroutine(["command_0x35e83b"]),
        ReturnObjectQueue(),
        Db(bytearray(b"\x83\x83"), identifier="command_0x35e83b"),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=320, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        Pause1Frame(identifier="command_0x35e84f"),
        SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6F),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 1, ["command_0x35e84f"]),
        RemoveObject(),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        IncAMEM8Bit(0x6E),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnSubroutine(),
    ],
)
