# pylint: disable=C0301,C0103

"""referenced by monster_attacks PhysicalAttack47, monster_attacks Stench"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=179,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-16,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x354306",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0804_GUNK_BALL_INK_BLAST,
            sequence=7,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        SpriteSequence(sequence=6),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        SpriteSequence(sequence=5),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        SpriteSequence(sequence=4),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        SpriteSequence(sequence=3),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        SpriteSequence(sequence=0, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=10),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 7),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x353706),
        RunSubroutine(["command_0x357fa0"]),
        IncAMEM8BitByConst(0x68, 1),
        PlaySound(sound=S0107_BUBBLE_POP),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x35252f"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=4,
            y=-2,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35435c",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0804_GUNK_BALL_INK_BLAST,
            sequence=1,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        RunSubroutine(["command_0x352546"]),
        RemoveObject(),
        ReturnObjectQueue(),
        ResetTargetMappingMemory(identifier="queuestart_0x354372"),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=7,
            y=-13,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewEffectObject(effect=EF0020_ENDOBUBBLE__BLACK_BALL_ORB_, looping_off=True),
        FadeInEffect(duration=2),
        Layer3On(prop=OVERLAP_ALL, bpp4=True),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        ClearAMEM8Bit(0x68),
        SetAMEM16BitToConst(0x60, 3),
        ObjectQueueAtOffsetAndIndex(index=0, target_address=0x35624B),
        RunSubroutine(["command_0x352552"]),
        Layer3Off(prop=OVERLAP_ALL, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=7,
            y=-13,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewEffectObject(effect=EF0020_ENDOBUBBLE__BLACK_BALL_ORB_, looping_off=True),
        FadeInEffect(duration=1),
        Layer3On(prop=TRANSPARENCY_OFF, bpp4=True),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        FadeOutObject(duration=6),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(prop=TRANSPARENCY_OFF, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        Jmp(["command_0x35252f"]),
    ],
)
