# pylint: disable=C0301,C0103

"""referenced by items SleepyBomb"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=271,
    script=[
        ClearAMEM16Bit(0x60, identifier="queuestart_0x35db5d"),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35DB51),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35DB51),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        ClearAMEM16Bit(0x62, identifier="queuestart_0x35db76"),
        ClearAMEM8Bit(0x6D),
        ResetTargetMappingMemory(identifier="command_0x35db7a"),
        MuteTimingJmp(["command_0x35db95"]),
        SetAMEMToAMEM16Bit(dest_amem=0xC4, amem=0x60),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35DB51),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        IncAMEM16Bit(0x62),
        JmpIfAMEM16BitNotEqualsConst(0x62, 6, ["command_0x35db7a"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=304,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x35db95",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0800_BLUE_GREEN_BUBBLES_CIRCLES,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        SetAMEM8BitToConst(0x6D, 1),
        PlaySound(sound=S0179_SLEEPY_BOMB),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6D, 2),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM16BitToOMEMMain(amem=0x60, omem=0x64, identifier="queuestart_0x35dbbb"),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        Pause1Frame(identifier="command_0x35dbc7"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 1, ["command_0x35dbc7"]),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-12,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Db(bytearray(b"\x83\x83")),
        Pause1Frame(identifier="command_0x35dbdc"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 2, ["command_0x35dbdc"]),
        RemoveObject(),
        ReturnObjectQueue(),
        ClearAMEM16Bit(0x62, identifier="queuestart_0x35dbe9"),
        ClearAMEM16Bit(0x6C),
        SetAMEM8BitToConst(0x66, 4),
        ResetTargetMappingMemory(identifier="command_0x35dbf1"),
        MuteTimingJmp(["command_0x35dc14"]),
        UnknownJmp26(182, ["command_0x35dc0c"]),
        SetAMEMToAMEM16Bit(dest_amem=0xC4, amem=0x60),
        ClearAMEM16Bit(0x60),
        IncAMEM8Bit(0x6C),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35DB51),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        IncAMEM16Bit(0x62, identifier="command_0x35dc0c"),
        JmpIfAMEM16BitNotEqualsConst(0x62, 6, ["command_0x35dbf1"]),
        JmpIfAMEM8BitEqualsConst(
            0x6C, 0, ["command_0x35dc35"], identifier="command_0x35dc14"
        ),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=304,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0801_SLEEP_ZZZ_S,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        SetAMEM8BitToConst(0x6D, 1),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6D, 2),
        SetAMEM8BitToConst(0x6F, 1, identifier="command_0x35dc35"),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM16BitToOMEMMain(amem=0x60, omem=0x64, identifier="queuestart_0x35dc3e"),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        Pause1Frame(identifier="command_0x35dc4a"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 1, ["command_0x35dc4a"]),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-4,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Db(bytearray(b"\x83\x83")),
        Pause1Frame(identifier="command_0x35dc5f"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 2, ["command_0x35dc5f"]),
        RemoveObject(),
        ReturnObjectQueue(),
    ],
)
