# pylint: disable=C0301,C0103

"""referenced by behaviour_33_0x350C5B, behaviour_34_0x350C9E, behaviour_51_0x350F56, behaviour_24_0x350A9C, weapons HandGun, behaviour_8_0x3507A2, behaviour_41_0x350DAF, behaviour_16_0x350928, behaviour_32_0x350C14, behaviour_52_0x350F6B, weapons FingerShot, behaviour_23_0x350A55, behaviour_9_0x3507E9, behaviour_42_0x350DED, behaviour_43_0x350E38"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=434,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35fad7"),
        Db(bytearray(b"\x83\x83")),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=13,
            y=-236,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=256, arch_height=128),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=19,
            y=-232,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=112, arch_height=128),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6F),
        IncAMEM8Bit(0x6F),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35fb13"),
        Db(bytearray(b"\x83\x83")),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=9,
            y=-233,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=288, arch_height=160),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=6,
            y=-231,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=128),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6F),
        IncAMEM8Bit(0x6F),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35fb4f"),
        Db(bytearray(b"\x83\x83")),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=17,
            y=-238,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=288, arch_height=128),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=21,
            y=-239,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=128),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6F),
        IncAMEM8Bit(0x6F),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35fb8b"),
        Db(bytearray(b"\x83\x83")),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
        PauseScriptUntil(condition=0x07),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"!\x9c:\x00")),
        JmpIfAMEM16BitNotEqualsConst(0x6C, 0, ["command_0x35fbc6"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=4,
            y=5,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=80),
        Jmp(["command_0x35fbd4"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=4,
            y=24,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x35fbc6"),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=160, arch_height=40),
        PauseScriptUntil(
            condition=SPRITE_SHIFT_COMPLETE, identifier="command_0x35fbd4"
        ),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        JmpIfAMEM16BitNotEqualsConst(0x6C, 0, ["command_0x35fbec"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=8,
            y=8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        Jmp(["command_0x35fbf4"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=8,
            y=27,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x35fbec"),
        MoveSpriteToCoords(
            shift_type=SHIFT_TYPE_TRANSFER,
            speed=128,
            arch_height=128,
            identifier="command_0x35fbf4"),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6F),
        IncAMEM8Bit(0x6F),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-256,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35fc0a"),
        Db(bytearray(b"\x83\x83")),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
        PauseScriptUntil(condition=0x07),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        Db(bytearray(b"!\x9c:\x00")),
        JmpIfAMEM16BitNotEqualsConst(0x6C, 0, ["command_0x35fc45"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=16,
            y=-1,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=32),
        Jmp(["command_0x35fc53"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=16,
            y=17,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x35fc45"),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=16),
        PauseScriptUntil(
            condition=SPRITE_SHIFT_COMPLETE, identifier="command_0x35fc53"
        ),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        JmpIfAMEM16BitNotEqualsConst(0x6C, 0, ["command_0x35fc6b"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=24,
            y=3,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        Jmp(["command_0x35fc73"]),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=24,
            y=21,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x35fc6b"),
        MoveSpriteToCoords(
            shift_type=SHIFT_TYPE_TRANSFER,
            speed=144,
            arch_height=128,
            identifier="command_0x35fc73"),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6F),
        IncAMEM8Bit(0x6F),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
    ])
