# pylint: disable=C0301,C0103

"""referenced by ally_spells Geno Beam"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=401,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35b46f"),
        Db(bytearray(b" \x8a@\x00")),
        Db(bytearray(b" \x8b\x10\x00")),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6D),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35B43D),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        ClearAMEM8Bit(0x6F),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=6),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35B43D),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=9),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35B43D),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6D),
        Pause1Frame(identifier="command_0x35b4aa"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6E),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 0, ["command_0x35b4aa"]),
        SetAMEM8BitToConst(0x6D, 2),
        ClearAMEM8Bit(0x6C),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35B43D),
        ObjectQueueAtOffsetAndIndex(index=36, target_address=0x35B43D),
        ClearAMEM8Bit(0x6E),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6F),
        Pause1Frame(identifier="command_0x35b4cf"),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6E),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 0, ["command_0x35b4cf"]),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6E),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35b4e3"),
        SetAMEM8BitToOMEMMain(amem=0x6A, omem=0x6A),
        JmpIfAMEM8BitEqualsConst(0x6A, 64, ["command_0x35b502"]),
        NewSpriteAtCoords(
            sprite_id=SPR0029_GENO_FINGER_SHOT,
            sequence=1,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            invert_sprite=True,
            behind_all_sprites=True,
            overlap_all_sprites=True),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x35b50e"]),
        NewSpriteAtCoords(
            sprite_id=SPR0039_RED_SCARECROW,
            sequence=4,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            invert_sprite=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
            identifier="command_0x35b502"),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=5, looping_off=True),
        SetAMEM8BitToOMEMMain(amem=0x6B, omem=0x6B, identifier="command_0x35b50e"),
        JmpIfAMEM8BitGreaterOrEqualThanConst(0x6B, 31, ["command_0x35b51c"]),
        DisplayMessage(BATTLE_MESSAGE, 13),
        PauseScriptUntilDialogClosed(),
        SetAMEM8BitToConst(0x6F, 1, identifier="command_0x35b51c"),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        Pause1Frame(identifier="command_0x35b524"),
        SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 2, ["command_0x35b524"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=18),
        MoveObject(
            speed=1,
            start_position=-193,
            end_position=-193,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=96,
            end_position=96,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=6),
        ResetObjectMappingMemory(),
        Pause1Frame(identifier="command_0x35b548"),
        SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 1, ["command_0x35b548"]),
        MoveObject(
            speed=1,
            start_position=192,
            end_position=192,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=-97,
            end_position=-97,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=7),
        ResetObjectMappingMemory(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        Pause1Frame(identifier="command_0x35b570"),
        SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6E),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 1, ["command_0x35b570"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        RemoveObject(),
        ReturnObjectQueue(),
        ClearAMEM16Bit(0x60, identifier="queuestart_0x35b581"),
        ClearAMEM16Bit(0x6E),
        ObjectQueueAtOffsetAndIndex(index=28, target_address=0x35B43D),
        StartTrackingAllyButtonInputs(),
        PlaySound(sound=S0069_GENO_POWER_UP),
        TimingForChargePress(
            charge_level_1_end=30,
            charge_level_2_end=55,
            charge_level_3_end=80,
            charge_level_4_end=105,
            overcharge_end=130),
        EndTrackingAllyButtonInputs(),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        ClearAMEM16Bit(0x60, identifier="queuestart_0x35b59b"),
        ClearAMEM8Bit(0x6C),
        ClearAMEM8Bit(0x6D),
        SetAMEM8BitToOMEMMain(amem=0x6A, omem=0x6A),
        JmpIfAMEM8BitEqualsConst(0x6A, 64, ["command_0x35b5b6"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=20,
            y=240,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        Jmp(["command_0x35b5be"]),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=14,
            y=243,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="command_0x35b5b6"),
        NewSpriteAtCoords(
            sprite_id=SPR0528_VERY_SMALL_BLACK_DOT,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=8,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
            identifier="command_0x35b5be"),
        ShineEffect(
            colour_count=6, starting_colour_index=1, glow_duration=1, east=True
        ),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=3, identifier="command_0x35b5cb"
        ),
        SetAMEMToRandom(amem=0x60, upper_bound=9),
        ObjectQueueAtOffsetAndIndexAtAMEM60(target_address=0x35B945),
        IncAMEM8Bit(0x6D),
        JmpIfAMEM8BitNotEqualsConst(0x6D, 32, ["command_0x35b5cb"]),
        Pause1Frame(identifier="command_0x35b5de"),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 32, ["command_0x35b5de"]),
        Db(bytearray(b"\x81")),
        RemoveObject(),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
        PlaySound(sound=S0070_GENO_BEAM, identifier="queuestart_0x35b5f0"),
        ScreenEffect(SEF0009_GENO_BEAM),
        Db(bytearray(b"\xa8\x02\x00")),
        SetAMEM8BitToConst(0x6C, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnObjectQueue(),
    ])
