# referenced by ally_spells Mute

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=511,
    script=[
        Db(bytearray(b" \x80\x10\x00"), identifier="queuestart_0x35a77d"),
        JmpIfAMEM8BitGreaterOrEqualThanConst(0x60, 31, ["command_0x35a78b"]),
        DisplayMessage(BATTLE_MESSAGE, 11),
        PauseScriptUntilDialogClosed(),
        ClearAMEM16Bit(0x60, identifier="command_0x35a78b"),
        ClearAMEM8Bit(0x62),
        ClearAMEM8Bit(0x6C),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6F),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-53,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        EnableSpritesOnSubscreen(),
        NewSpriteAtCoords(
            sprite_id=SPR0551_MUTE_BALLOON,
            sequence=0,
            priority=0,
            vram_address=0x6200,
            palette_row=8,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        FadeInSprite(duration=8),
        Db(bytearray(b"\x88")),
        PlaySound(sound=S0187_MUTE_BALLOON_RISES),
        VisibilityOn(),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35A771),
        ResetTargetMappingMemory(identifier="command_0x35a7b3"),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION, x=0, y=-61, z=0, set_y=True
        ),
        MoveObject(
            speed=1,
            start_position=-65,
            end_position=-65,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Pause1Frame(),
        PauseScriptUntil(condition=0x02),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_CURRENT_POSITION, x=0, y=-53, z=0, set_y=True
        ),
        MoveObject(
            speed=1,
            start_position=64,
            end_position=64,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Pause1Frame(),
        PauseScriptUntil(condition=0x02),
        IncAMEM8Bit(0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 3, ["command_0x35a7b3"]),
        ResetObjectMappingMemory(),
        RemoveObject(),
        JmpIfAMEM8BitNotEqualsConst(0x62, 1, ["command_0x35a7f9"]),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35A771),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        Jmp(["command_0x35a863"]),
        NewSpriteAtCoords(
            sprite_id=SPR0551_MUTE_BALLOON,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35a7f9",
        ),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-53,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=416, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM8BitToConst(0x62, 4),
        UnknownJmp26(178, ["command_0x35a83f"]),
        SpriteSequence(sequence=1, looping_on=True),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        SpriteSequence(sequence=2),
        PlaySound(sound=S0107_BUBBLE_POP),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=6),
        SpriteSequence(sequence=3),
        MoveObject(
            speed=1,
            start_position=96,
            end_position=96,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        ResetObjectMappingMemory(),
        Jmp(["command_0x35a863"]),
        PlaySound(sound=S0191_MUTE_BALLOON_FAILS, identifier="command_0x35a83f"),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=5),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-192,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveObject(
            speed=1,
            start_position=-1281,
            end_position=-1281,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=0x02),
        ResetObjectMappingMemory(),
        SetAMEM8BitToConst(0x6F, 1, identifier="command_0x35a863"),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        RemoveObject(),
        ReturnObjectQueue(),
        StartTrackingAllyButtonInputs(identifier="queuestart_0x35a86d"),
        TimingForRotationCount(
            end_accepting_input=120, start_accepting_input=0, max_presses=26
        ),
        SetOMEMMainToAMEM8Bit(omem=0x62, amem=0x62),
        EndTrackingAllyButtonInputs(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35a878",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0551_MUTE_BALLOON,
            sequence=1,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=169,
            y=67,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=416, arch_height=0),
        ClearAMEM8Bit(0x6A),
        ClearAMEM8Bit(0x6B),
        ClearAMEM8Bit(0x6C),
        ClearAMEM8Bit(0x6D),
        ClearAMEM8Bit(0x6E),
        ClearAMEM16Bit(0x62),
        SetAMEM8BitToConst(0x66, 4),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetTargetMappingMemory(identifier="command_0x35a8ad"),
        MuteTimingJmp(["command_0x35a8d0"]),
        UnknownJmp26(182, ["command_0x35a8c8"]),
        IncAMEM8Bit(0x6C),
        SetAMEMToAMEM16Bit(dest_amem=0xC4, amem=0x60),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35A771),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        IncAMEM16Bit(0x62, identifier="command_0x35a8c8"),
        JmpIfAMEM16BitNotEqualsConst(0x62, 6, ["command_0x35a8ad"]),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=18, identifier="command_0x35a8d0"
        ),
        ClearAMEM8Bit(0x62),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35A771),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        RemoveObject(),
        JmpIfAMEM8BitEqualsConst(0x6C, 0, ["command_0x35a918"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=9),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=169,
            y=309,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0551_MUTE_BALLOON,
            sequence=3,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        SetAMEM8BitToConst(0x6E, 1),
        MoveObject(
            speed=1,
            start_position=96,
            end_position=96,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Pause1Frame(identifier="command_0x35a906"),
        JmpIfAMEM8BitNotEqualsAMEM(
            amem=0x6D, source_amem=0xCC, destinations=["command_0x35a906"]
        ),
        PauseScriptUntilSpriteSequenceDone(),
        ResetObjectMappingMemory(),
        SetAMEM8BitToConst(0x6A, 1),
        RemoveObject(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=6),
        PauseScriptUntilAMEMBitsSet(0x6B, [0], identifier="command_0x35a918"),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=152,
            y=32,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35a924",
        ),
        NewEffectObject(effect=EF0009_MUTE__BALLOON_, looping_off=True),
        Layer3On(property=TRANSPARENCY_OFF, bpp4=True),
        PlaySound(sound=S0107_BUBBLE_POP),
        PauseScriptUntil(condition=SEQ_4BPP_COMPLETE),
        Layer3Off(property=TRANSPARENCY_OFF, bpp4=True),
        Pause2Frames(),
        ClearEffectIndex(),
        SetAMEM8BitToConst(0x6B, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6B, amem=0x6B),
        ReturnObjectQueue(),
        ResetTargetMappingMemory(identifier="queuestart_0x35a943"),
        SetAMEM16BitToOMEMMain(amem=0x60, omem=0x64),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        Pause1Frame(identifier="command_0x35a950"),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        JmpIfAMEM8BitNotEqualsConst(0x6E, 1, ["command_0x35a950"]),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=0,
            y=-53,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        Db(bytearray(b"\x83\x83")),
        SetAMEM8BitToOMEMMain(amem=0x6D, omem=0x6D),
        IncAMEM8Bit(0x6D),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        Pause1Frame(identifier="command_0x35a96f"),
        SetAMEM8BitToOMEMMain(amem=0x6A, omem=0x6A),
        JmpIfAMEM8BitNotEqualsConst(0x6A, 1, ["command_0x35a96f"]),
        RemoveObject(),
        ReturnObjectQueue(),
    ],
)
