# pylint: disable=C0301,C0103

"""referenced by monster_attacks Vigorup, monster_attacks Toxicyst, monster_attacks Elegy, monster_attacks PhysicalAttack111, monster_attacks DoomReverb, monster_attacks Quicksilver, monster_attacks Chomp, monster_attacks Echofinder, monster_attacks LastShot, monster_attacks PhysicalAttack21, monster_attacks ViroPlasm, monster_attacks PhysicalAttack116, monster_attacks PhysicalAttack105, monster_attacks PhysicalAttack12, monster_attacks Shaker, monster_attacks 124, behaviour_22_0x350A3E, monster_attacks Terrapunch, monster_attacks PhysicalAttack15, monster_attacks Howl, monster_attacks 123, behaviour_11_0x35086A, behaviour_7_0x350796, behaviour_31_0x350BFD, monster_attacks ScrowBell, behaviour_53_0x350F7A, monster_attacks SpritzBomb, behaviour_10_0x350830, monster_attacks Sporocyst, monster_attacks PhysicalAttack31, monster_attacks PhysicalAttack7, monster_attacks PhysicalAttack0, monster_attacks PhysicalAttack5, monster_attacks SilverBullet, monster_attacks 127, monster_attacks PhysicalAttack89, monster_attacks WildCard, monster_attacks PhysicalAttack27, monster_attacks Jinxed, monster_attacks PhysicalAttack117, monster_attacks PhysicalAttack8, monster_attacks PhysicalAttack108, behaviour_15_0x35091C, monster_attacks PhysicalAttack10, behaviour_40_0x350DA3, monster_attacks LullaBye, behaviour_50_0x350F4A, monster_attacks PhysicalAttack2, monster_attacks PhysicalAttack4, monster_attacks PhysicalAttack118, monster_attacks PhysicalAttack6, monster_attacks PhysicalAttack20"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=179,
    script=[
        SpriteSequence(sequence=3, identifier="command_0x35313b"),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        ReturnSubroutine(),
        SpriteSequence(sequence=3, identifier="command_0x353140"),
        PauseScriptUntilSpriteSequenceDone(),
        RunSubroutine(["command_0x352f2f"]),
        ResetSpriteSequence(),
        ReturnSubroutine(),
        SpriteSequence(sequence=4, identifier="command_0x353148"),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        ReturnSubroutine(),
        SpriteSequence(sequence=4, identifier="command_0x35314d"),
        PauseScriptUntilSpriteSequenceDone(),
        RunSubroutine(["command_0x352f2f"]),
        ResetSpriteSequence(),
        ReturnSubroutine(),
        SpriteSequence(sequence=5, identifier="command_0x353155"),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        ReturnSubroutine(),
        SpriteSequence(sequence=1, identifier="command_0x35315a"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3505d5"]),
        SpriteSequence(sequence=2, identifier="command_0x353160"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3505d5"]),
        SpriteSequence(sequence=3, identifier="command_0x353166"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3505d5"]),
        SpriteSequence(sequence=4, identifier="command_0x35316c"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3505d5"]),
        SpriteSequence(sequence=5, identifier="command_0x353172"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        PlaySound(sound=S0093_BOWYER_ARROW_LOCK_BUTTON),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x3505d5"]),
        SpriteSequence(sequence=4, identifier="command_0x35317e"),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        Jmp(["command_0x350e93"]),
        SpriteSequence(sequence=2, identifier="command_0x353185"),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=6, looping_off=True),
        Jmp(["command_0x3505d5"]),
        SpriteSequence(sequence=5, identifier="command_0x35318d"),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        Jmp(["command_0x350e93"]),
        SpriteSequence(sequence=6, identifier="command_0x353194"),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        Jmp(["command_0x350e93"]),
        SpriteSequence(sequence=7, identifier="command_0x35319b"),
        PauseScriptUntilSpriteSequenceDone(),
        ResetSpriteSequence(),
        Jmp(["command_0x350e93"]),
        SpriteSequence(sequence=1, identifier="command_0x3531a2"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x350e93"]),
        SpriteSequence(sequence=2, identifier="command_0x3531a8"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x350e93"]),
        SpriteSequence(sequence=3, identifier="command_0x3531ae"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x350e93"]),
        SpriteSequence(sequence=4, identifier="command_0x3531b4"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x350e93"]),
        SpriteSequence(sequence=5, identifier="command_0x3531ba"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x350e93"]),
        SpriteSequence(sequence=6, identifier="command_0x3531c0"),
        PauseScriptUntilSpriteSequenceDone(),
        SetAMEM8BitToConst(0x64, 200),
        Set7E5xToAMEM8Bit(0x7E001A, 0x64),
        Jmp(["command_0x350e93"]),
        SpriteSequence(sequence=7, identifier="command_0x3531ce"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x350e93"]),
        SpriteSequence(sequence=8, identifier="command_0x3531d4"),
        PauseScriptUntilSpriteSequenceDone(),
        Jmp(["command_0x350e93"]),
        SpriteSequence(sequence=9, looping_on=True, identifier="command_0x3531da"),
        Jmp(["command_0x350e93"]),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0012_TOADSTOOL_FALLEN_CRYING,
            sequence=1,
            store_to_vram=True,
            store_palette=True,
            identifier="command_0x3531df"),
        PauseScriptUntilSpriteSequenceDone(),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0007_TOADSTOOL_WALKING_DOWN_LEFT,
            sequence=0,
            store_to_vram=True,
            store_palette=True),
        ResetSpriteSequence(),
        ReturnSubroutine(),
    ])
