# pylint: disable=C0301,C0103

"""referenced by battle_events BE0045_ZOMBONE_DIES, battle_events BE0046_CZAR_DRAGON_SUMMONS_HELIOS, battle_events BE0042_BB_BOMBS_EXPLODE, battle_events BE0044_CZAR_DRAGON_DIES"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=659,
    script=[
        RunSubroutine(["command_0x3a77a2"]),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=2),
        PauseScriptUntilSpriteSequenceDone(),
        RunSubroutine(["command_0x3a7614"]),
        RunSubroutine(["command_0x3a77d9"]),
        PlaySound(sound=S0149_ENEMY_JUMPS_HIGH),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-113,
            end_position=-113,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-49,
            end_position=-49,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=33,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        VisibilityOff(),
        RunSubroutine(["command_0x3a765a"]),
        ClearAMEM8Bit(0x60),
        SetAMEM16BitToConst(0x60, 7),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x3A8AC0),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x3A8AC0),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x3A8AC0),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=30, identifier="queuestart_0x3accff"
        ),
        SpriteSequence(sequence=2, looping_on=True),
        RunSubroutine(["command_0x3a7729"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=64,
            end_position=64,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=65,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=30, identifier="queuestart_0x3acd32"
        ),
        SpriteSequence(sequence=2, looping_on=True),
        RunSubroutine(["command_0x3a7729"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-65,
            end_position=-65,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=65,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=30, identifier="queuestart_0x3acd61"
        ),
        SpriteSequence(sequence=2, looping_on=True),
        RunSubroutine(["command_0x3a7729"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=128,
            end_position=128,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=65,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=30, identifier="queuestart_0x3acd90"
        ),
        SpriteSequence(sequence=2, looping_on=True),
        RunSubroutine(["command_0x3a7729"]),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=64,
            end_position=64,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=65,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=60, identifier="queuestart_0x3acdbf"
        ),
        RemoveObject(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=160,
            y=120,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0468_KING_BOMB,
            sequence=0,
            priority=2,
            vram_address=0x7800,
            palette_row=12,
            looping=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=KingBomb, position=0, bit_7=True),
        RunSubroutine(["command_0x3a757a"]),
        ReturnSpriteQueue(),
        RunSubroutine(["command_0x3a7729"], identifier="queuestart_0x3acddd"),
        SpriteSequence(sequence=3, looping_off=True),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=64,
            end_position=64,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=65,
            start_position=-2049,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        SpriteSequence(sequence=0, looping_off=True),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
        Db(bytearray(b"Z"), identifier="queuestart_0x3ace0a"),
        ShakeScreen(amount=5, speed=200),
        PlaySound(sound=S0079_RUMBLE_SINGLE),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=9,
            start_position=0,
            end_position=1024,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        EnableSpritesOnSubscreen(),
        Db(bytearray(b"\x84\x00\x08")),
        Db(bytearray(b"\x9e\x00\x00")),
        FadeOutSprite(duration=2),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        VisibilityOff(),
        DisableSpritesOnSubscreen(),
        RemoveObject(),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a756c"]),
        StopShakingObject(),
        ShakeScreen(amount=3, speed=200),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        StopShakingObject(),
        ShakeScreen(amount=1, speed=200),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=60),
        StopShakingObject(),
        RunSubroutine(["command_0x3a755e"]),
        ReturnSpriteQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=167,
            y=119,
            z=-64,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3ace4f",
        ),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0794_DARK_RED_YELLOW_FIREBALL,
            sequence=0,
            priority=2,
            vram_address=0x7800,
            palette_row=14,
            param_2_and_0x10=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=Helio, position=1, bit_7=True),
        SetAMEM8BitToConst(0x60, 167),
        SetAMEM8BitToConst(0x61, 119),
        SetAMEM8BitToConst(0x62, 64),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        Set7E5xToAMEM8Bit(0x7E003D, 0x62),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=135,
            y=135,
            z=-64,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3ace81",
        ),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0794_DARK_RED_YELLOW_FIREBALL,
            sequence=0,
            priority=2,
            vram_address=0x7A00,
            palette_row=14,
            param_2_and_0x10=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=Helio, position=1, bit_7=True),
        SetAMEM8BitToConst(0x60, 135),
        SetAMEM8BitToConst(0x61, 135),
        SetAMEM8BitToConst(0x62, 64),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        Set7E5xToAMEM8Bit(0x7E003D, 0x62),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=199,
            y=167,
            z=-64,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3aceb3",
        ),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0794_DARK_RED_YELLOW_FIREBALL,
            sequence=0,
            priority=2,
            vram_address=0x7C00,
            palette_row=14,
            param_2_and_0x10=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=Helio, position=1, bit_7=True),
        SetAMEM8BitToConst(0x60, 199),
        SetAMEM8BitToConst(0x61, 167),
        SetAMEM8BitToConst(0x62, 64),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        Set7E5xToAMEM8Bit(0x7E003D, 0x62),
        RunSubroutine(["command_0x3a7544"]),
        ReturnSpriteQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=231,
            y=151,
            z=-64,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x3acee5",
        ),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0794_DARK_RED_YELLOW_FIREBALL,
            sequence=0,
            priority=2,
            vram_address=0x7E00,
            palette_row=14,
            param_2_and_0x10=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        SummonMonster(monster=Helio, position=1, bit_7=True),
        SetAMEM8BitToConst(0x60, 231),
        SetAMEM8BitToConst(0x61, 151),
        SetAMEM8BitToConst(0x62, 64),
        Set7E5xToAMEM8Bit(0x7E003B, 0x60),
        Set7E5xToAMEM8Bit(0x7E003C, 0x61),
        Set7E5xToAMEM8Bit(0x7E003D, 0x62),
        RunSubroutine(["command_0x3a7544"]),
        RunSubroutine(["command_0x3a757a"]),
        ReturnSpriteQueue(),
        ResetTargetMappingMemory(identifier="queuestart_0x3acf1a"),
        MoveObject(
            speed=65,
            start_position=1024,
            end_position=2048,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a8698"]),
        RunSubroutine(["command_0x3a756c"]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=65,
            start_position=-1025,
            end_position=-2049,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetObjectMappingMemory(),
        RunSubroutine(["command_0x3a771e"]),
        ReturnSpriteQueue(),
    ],
)
