# referenced by items GoodieBag

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=119,
    script=[
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=8,
            y=-34,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35dfce",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0195_FLOWER,
            sequence=5,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        MoveObject(
            speed=25,
            start_position=-545,
            end_position=0,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PlaySound(sound=S0061_ITEM_USE),
        Db(bytearray(b"\x12\x81")),
        ResetObjectMappingMemory(),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6E),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35DFC8),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        RemoveObject(),
        NewSpriteAtCoords(
            sprite_id=SPR0518_SMALL_WHITE_CLOUD,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        SetAMEMToRandom(amem=0x6E, upper_bound=5),
        JmpIfAMEM8BitEqualsConst(0x6E, 0, ["command_0x35e012"]),
        AddCoins(1),
        Jmp(["command_0x35e015"]),
        AddCoins(5, identifier="command_0x35e012"),
        SetAMEM8BitToConst(0x6F, 1, identifier="command_0x35e015"),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=0,
            y=-16,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35e01e",
        ),
        MoveObject(
            speed=11,
            start_position=-385,
            end_position=0,
            apply_to_y=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0193_SMALL_COIN,
            sequence=2,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PlaySound(sound=S0013_COIN),
        PauseScriptUntilSpriteSequenceDone(),
        ResetObjectMappingMemory(),
        RemoveObject(),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
    ],
)
