# pylint: disable=C0301,C0103

"""referenced by ally_spells Crusher"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=805,
    script=[
        StartTrackingAllyButtonInputs(identifier="queuestart_0x35b038"),
        ClearAMEM16Bit(0x60),
        ClearAMEM16Bit(0x6A),
        ClearAMEM16Bit(0x6C),
        Pause1Frame(),
        Set7E1xToAMEM8Bit(0x7EE020, 0x6A),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35B01A),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35B01A),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35B01A),
        PauseScriptUntilAMEMBitsSet(0x6A, [0]),
        PauseScriptUntilAMEMBitsSet(0x6B, [0]),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM60ToCurrentTarget(identifier="queuestart_0x35b064"),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION, x=6, y=-88, z=0, set_y=True, set_z=True
        ),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True),
        DoMaskEffect(POLYGON_MASK),
        NewEffectObject(effect=EF0004_CRUSHER, looping_off=True),
        SetMaskCoords((8, -48), (-64, -48), (112, 48), (-64, 48)),
        ScreenFlash(WHITE, 8),
        SetAMEM16BitToAMEM(amem=0x68, source_amem=0x8A),
        Db(bytearray(b"\xc5")),
        Layer3On(prop=TRANSPARENCY_OFF, bit_0=True, bpp4=True),
        ShakeScreen(amount=1, speed=224),
        PlaySound(sound=S0095_BOWSERS_CRUSHER),
        PauseScriptUntil(condition=SEQ_4BPP_COMPLETE),
        TimingForOneTieredButtonPress(
            end_accepting_input=30,
            start_accepting_input=0,
            partial_start=26,
            perfect_start=29,
            perfect_end=30,
            destinations=["command_0x35b0a6"]),
        ScreenFlashWithDuration(WHITE, 1, 16),
        PlaySound(sound=S0078_TIMED_STAT_BOOST),
        EndTrackingAllyButtonInputs(identifier="command_0x35b0a6"),
        FadeOutObject(duration=1),
        ScreenFlash(NO_COLOUR, 8),
        Layer3On(prop=OVERLAP_ALL, bpp4=True, invisible=True),
        PauseScriptUntil(condition=FADE_4BPP_COMPLETE),
        Layer3Off(prop=OVERLAP_ALL, bpp4=True),
        StopShakingObject(),
        Pause2Frames(),
        ClearEffectIndex(),
        SetAMEMToAMEM16Bit(dest_amem=0x8A, amem=0x68),
        Db(bytearray(b"\x90")),
        Db(bytearray(b"\xc4")),
        Db(bytearray(b"\xc5")),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=9, identifier="queuestart_0x35b0c5"
        ),
        SetAMEM16BitToConst(0x60, 0),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION, x=0, y=256, z=0, set_y=True, set_z=True
        ),
        Pause1Frame(),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True),
        NewSpriteAtCoords(
            sprite_id=SPR0792_BLACK_ROCK,
            sequence=3,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        ClearAMEM8Bit(0x6F),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6D),
        ClearAMEM8Bit(0x6C),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x35B01A),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35B01A),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35B01A),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=16, target_address=0x35B01A),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        RemoveObject(),
        SetAMEM8BitToConst(0x6A, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6A, amem=0x6A),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=9, identifier="queuestart_0x35b119"
        ),
        SetAMEM16BitToConst(0x60, 0),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION, x=0, y=256, z=0, set_y=True, set_z=True
        ),
        Pause1Frame(),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True),
        NewSpriteAtCoords(
            sprite_id=SPR0792_BLACK_ROCK,
            sequence=3,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        ClearAMEM8Bit(0x6F),
        ClearAMEM8Bit(0x6E),
        ClearAMEM8Bit(0x6D),
        ClearAMEM8Bit(0x6C),
        ClearAMEM8Bit(0x6B),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=18, target_address=0x35B01A),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=20, target_address=0x35B01A),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=22, target_address=0x35B01A),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=24, target_address=0x35B01A),
        Pause1Frame(),
        ObjectQueueAtOffsetAndIndex(index=26, target_address=0x35B01A),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PauseScriptUntilAMEMBitsSet(0x6E, [0]),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        PauseScriptUntilAMEMBitsSet(0x6B, [0]),
        RemoveObject(),
        SetAMEM8BitToConst(0x6B, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6B, amem=0x6B),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=4, identifier="queuestart_0x35b177"
        ),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION, x=-8, y=16, z=0, set_y=True, set_z=True
        ),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=129,
            start_position=-2305,
            end_position=2304,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=-257,
            end_position=-257,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        RemoveObject(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=4, identifier="queuestart_0x35b1ad"
        ),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION, x=8, y=16, z=0, set_y=True, set_z=True
        ),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=129,
            start_position=-1793,
            end_position=1792,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=384,
            end_position=384,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        RemoveObject(),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=4, identifier="queuestart_0x35b1e3"
        ),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION, x=2, y=20, z=0, set_y=True, set_z=True
        ),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=129,
            start_position=-2113,
            end_position=2112,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=80,
            end_position=80,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        RemoveObject(),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=4, identifier="queuestart_0x35b219"
        ),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION, x=-4, y=18, z=0, set_y=True, set_z=True
        ),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=97,
            start_position=-1537,
            end_position=1536,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=-161,
            end_position=-161,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        RemoveObject(),
        SetAMEM8BitToConst(0x6C, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=4, identifier="queuestart_0x35b24f"
        ),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION, x=-8, y=16, z=0, set_y=True, set_z=True
        ),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=113,
            start_position=-1665,
            end_position=1664,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=-337,
            end_position=-337,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        RemoveObject(),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=4, identifier="queuestart_0x35b285"
        ),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION, x=-4, y=21, z=0, set_y=True, set_z=True
        ),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=81,
            start_position=-1281,
            end_position=1280,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=-49,
            end_position=-49,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        RemoveObject(),
        SetAMEM8BitToConst(0x6E, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6E, amem=0x6E),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=4, identifier="queuestart_0x35b2bb"
        ),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION, x=2, y=19, z=0, set_y=True, set_z=True
        ),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=113,
            start_position=-1601,
            end_position=1600,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=144,
            end_position=144,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        RemoveObject(),
        SetAMEM8BitToConst(0x6D, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6D, amem=0x6D),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=4, identifier="queuestart_0x35b2f1"
        ),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION, x=5, y=16, z=0, set_y=True, set_z=True
        ),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=129,
            start_position=-1921,
            end_position=1920,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=224,
            end_position=224,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        RemoveObject(),
        SetAMEM8BitToConst(0x6C, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnObjectQueue(),
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=4, identifier="queuestart_0x35b327"
        ),
        SetAMEM60ToCurrentTarget(),
        SetAMEM32ToXYZCoords(
            origin=TARGET_CURRENT_POSITION, x=-6, y=20, z=0, set_y=True, set_z=True
        ),
        SetAMEM32ToXYZCoords(origin=ABSOLUTE_POSITION, x=0, y=0, z=0, set_x=True),
        Db(bytearray(b"\x83\x83")),
        MoveObject(
            speed=121,
            start_position=-2305,
            end_position=2304,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True),
        MoveObject(
            speed=1,
            start_position=-49,
            end_position=-49,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        RemoveObject(),
        SetAMEM8BitToConst(0x6B, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6B, amem=0x6B),
        ReturnObjectQueue(),
    ])
