# referenced by weapons StarGun

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=337,
    script=[
        PauseScriptUntil(
            condition=FRAMES_ELAPSED, frames=50, identifier="queuestart_0x35fd9a"
        ),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=20,
            y=240,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0527_YELLOW_MIST_STEAM_FORMS_INTO_SMALL_STAR,
            sequence=3,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        ClearAMEM16Bit(0x60),
        ClearAMEM8Bit(0x6F),
        PlaySound(sound=S0017_STAR_GUN_SHOOT),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35F9A2),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35FD90),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=6),
        ObjectQueueAtOffsetAndIndex(index=14, target_address=0x35F9A2),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35FD90),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=6),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35F9A2),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=2),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35FD90),
        Pause1Frame(identifier="command_0x35fde1"),
        JmpIfAMEM8BitNotEqualsConst(0x6F, 6, ["command_0x35fde1"]),
        RemoveObject(),
        SetAMEM8BitToConst(0x66, 1),
        SetOMEMMainToAMEM8Bit(omem=0x66, amem=0x66),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-6,
            y=-260,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35fdf2",
        ),
        Db(bytearray(b"\x83\x83")),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-4,
            y=-12,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
        PauseScriptUntil(condition=0x07),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-18,
            y=-5,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=48),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-24,
            y=-6,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=128),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6F),
        IncAMEM8Bit(0x6F),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-6,
            y=-260,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35fe45",
        ),
        Db(bytearray(b"\x83\x83")),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-4,
            y=-12,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
        PauseScriptUntil(condition=0x07),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=4,
            y=5,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=80),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=8,
            y=8,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=128),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6F),
        IncAMEM8Bit(0x6F),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=CASTER_CURRENT_POSITION,
            x=-6,
            y=-260,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35fe98",
        ),
        Db(bytearray(b"\x83\x83")),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=-4,
            y=-12,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=1792, arch_height=0),
        PauseScriptUntil(condition=0x07),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=16,
            y=-1,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=128, arch_height=32),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        SetAMEM60ToCurrentTarget(),
        SetAMEM40ToXYZCoords(
            origin=TARGET_CURRENT_POSITION,
            x=24,
            y=3,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_TRANSFER, speed=144, arch_height=128),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        RemoveObject(),
        SetAMEM8BitToOMEMMain(amem=0x6F, omem=0x6F),
        IncAMEM8Bit(0x6F),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
    ],
)
