# pylint: disable=C0301,C0103

"""referenced by items KerokeroCola"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=734,
    script=[
        ClearAMEM16Bit(0x60, identifier="queuestart_0x35d46d"),
        ClearAMEM8Bit(0x6C),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35D45D),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35D45D),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35D45D),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x35D45D),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35D45D),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        ObjectQueueAtOffsetAndIndex(index=12, target_address=0x35D45D),
        Pause1Frame(identifier="command_0x35d4a1"),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 6, ["command_0x35d4a1"]),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=48,
            y=148,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35d4b1"),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        JmpIfAMEM8BitEqualsConst(0x6E, 1, ["command_0x35d4e4"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 2, ["command_0x35d4f0"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 3, ["command_0x35d4fc"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 4, ["command_0x35d508"]),
        NewSpriteAtCoords(
            sprite_id=SPR0523_YELLOW_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        Jmp(["command_0x35d511"]),
        NewSpriteAtCoords(
            sprite_id=SPR0561_BLUE_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d4e4"),
        Jmp(["command_0x35d511"]),
        NewSpriteAtCoords(
            sprite_id=SPR0560_RED_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d4f0"),
        Jmp(["command_0x35d511"]),
        NewSpriteAtCoords(
            sprite_id=SPR0559_GREEN_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d4fc"),
        Jmp(["command_0x35d511"]),
        NewSpriteAtCoords(
            sprite_id=SPR0795_LIGHT_GREEN_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d508"),
        RunSubroutine(["command_0x35d72c"], identifier="command_0x35d511"),
        ReturnObjectQueue(),
        Pause1Frame(identifier="queuestart_0x35d515"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=80,
            y=164,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        JmpIfAMEM8BitEqualsConst(0x6E, 1, ["command_0x35d549"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 2, ["command_0x35d555"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 3, ["command_0x35d561"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 4, ["command_0x35d56d"]),
        NewSpriteAtCoords(
            sprite_id=SPR0523_YELLOW_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True),
        Jmp(["command_0x35d576"]),
        NewSpriteAtCoords(
            sprite_id=SPR0561_BLUE_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True,
            identifier="command_0x35d549"),
        Jmp(["command_0x35d576"]),
        NewSpriteAtCoords(
            sprite_id=SPR0560_RED_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True,
            identifier="command_0x35d555"),
        Jmp(["command_0x35d576"]),
        NewSpriteAtCoords(
            sprite_id=SPR0559_GREEN_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True,
            identifier="command_0x35d561"),
        Jmp(["command_0x35d576"]),
        NewSpriteAtCoords(
            sprite_id=SPR0795_LIGHT_GREEN_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True,
            identifier="command_0x35d56d"),
        RunSubroutine(["command_0x35d72c"], identifier="command_0x35d576"),
        ReturnObjectQueue(),
        Pause1Frame(identifier="queuestart_0x35d57a"),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        JmpIfAMEM8BitLessThanConst(0x6C, 2, ["queuestart_0x35d57a"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=112,
            y=180,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        JmpIfAMEM8BitEqualsConst(0x6E, 1, ["command_0x35d5b8"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 2, ["command_0x35d5c4"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 3, ["command_0x35d5d0"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 4, ["command_0x35d5dc"]),
        NewSpriteAtCoords(
            sprite_id=SPR0523_YELLOW_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        Jmp(["command_0x35d5e5"]),
        NewSpriteAtCoords(
            sprite_id=SPR0561_BLUE_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d5b8"),
        Jmp(["command_0x35d5e5"]),
        NewSpriteAtCoords(
            sprite_id=SPR0560_RED_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d5c4"),
        Jmp(["command_0x35d5e5"]),
        NewSpriteAtCoords(
            sprite_id=SPR0559_GREEN_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d5d0"),
        Jmp(["command_0x35d5e5"]),
        NewSpriteAtCoords(
            sprite_id=SPR0795_LIGHT_GREEN_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d5dc"),
        RunSubroutine(["command_0x35d72c"], identifier="command_0x35d5e5"),
        ReturnObjectQueue(),
        Pause1Frame(identifier="queuestart_0x35d5e9"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=72,
            y=138,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        JmpIfAMEM8BitEqualsConst(0x6E, 1, ["command_0x35d61d"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 2, ["command_0x35d629"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 3, ["command_0x35d635"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 4, ["command_0x35d641"]),
        NewSpriteAtCoords(
            sprite_id=SPR0523_YELLOW_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        Jmp(["command_0x35d64a"]),
        NewSpriteAtCoords(
            sprite_id=SPR0561_BLUE_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d61d"),
        Jmp(["command_0x35d64a"]),
        NewSpriteAtCoords(
            sprite_id=SPR0560_RED_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d629"),
        Jmp(["command_0x35d64a"]),
        NewSpriteAtCoords(
            sprite_id=SPR0559_GREEN_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d635"),
        Jmp(["command_0x35d64a"]),
        NewSpriteAtCoords(
            sprite_id=SPR0795_LIGHT_GREEN_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6400,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d641"),
        RunSubroutine(["command_0x35d72c"], identifier="command_0x35d64a"),
        ReturnObjectQueue(),
        Pause1Frame(identifier="queuestart_0x35d64e"),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        JmpIfAMEM8BitLessThanConst(0x6C, 1, ["queuestart_0x35d64e"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=104,
            y=154,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        JmpIfAMEM8BitEqualsConst(0x6E, 1, ["command_0x35d68c"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 2, ["command_0x35d698"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 3, ["command_0x35d6a4"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 4, ["command_0x35d6b0"]),
        NewSpriteAtCoords(
            sprite_id=SPR0523_YELLOW_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True),
        Jmp(["command_0x35d6b9"]),
        NewSpriteAtCoords(
            sprite_id=SPR0561_BLUE_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True,
            identifier="command_0x35d68c"),
        Jmp(["command_0x35d6b9"]),
        NewSpriteAtCoords(
            sprite_id=SPR0560_RED_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True,
            identifier="command_0x35d698"),
        Jmp(["command_0x35d6b9"]),
        NewSpriteAtCoords(
            sprite_id=SPR0559_GREEN_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True,
            identifier="command_0x35d6a4"),
        Jmp(["command_0x35d6b9"]),
        NewSpriteAtCoords(
            sprite_id=SPR0795_LIGHT_GREEN_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            mirror_sprite=True,
            overlap_all_sprites=True,
            identifier="command_0x35d6b0"),
        RunSubroutine(["command_0x35d72c"], identifier="command_0x35d6b9"),
        ReturnObjectQueue(),
        Pause1Frame(identifier="queuestart_0x35d6bd"),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        JmpIfAMEM8BitLessThanConst(0x6C, 3, ["queuestart_0x35d6bd"]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=136,
            y=170,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True),
        SetAMEM8BitToOMEMMain(amem=0x6E, omem=0x6E),
        JmpIfAMEM8BitEqualsConst(0x6E, 1, ["command_0x35d6fb"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 2, ["command_0x35d707"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 3, ["command_0x35d713"]),
        Pause1Frame(),
        JmpIfAMEM8BitEqualsConst(0x6E, 4, ["command_0x35d71f"]),
        NewSpriteAtCoords(
            sprite_id=SPR0523_YELLOW_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True),
        Jmp(["command_0x35d728"]),
        NewSpriteAtCoords(
            sprite_id=SPR0561_BLUE_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d6fb"),
        Jmp(["command_0x35d728"]),
        NewSpriteAtCoords(
            sprite_id=SPR0560_RED_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d707"),
        Jmp(["command_0x35d728"]),
        NewSpriteAtCoords(
            sprite_id=SPR0559_GREEN_CURE_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d713"),
        Jmp(["command_0x35d728"]),
        NewSpriteAtCoords(
            sprite_id=SPR0795_LIGHT_GREEN_STARS,
            sequence=0,
            priority=3,
            vram_address=0x6600,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
            identifier="command_0x35d71f"),
        RunSubroutine(["command_0x35d72c"], identifier="command_0x35d728"),
        ReturnObjectQueue(),
        JmpIfAMEM8BitEqualsConst(
            0x6E, 4, ["command_0x35d737"], identifier="command_0x35d72c"
        ),
        PlaySound(sound=S0066_RECOVER_HP),
        Jmp(["command_0x35d739"]),
        PlaySound(sound=S0068_RECOVER_DRINK, identifier="command_0x35d737"),
        ShineEffect(
            colour_count=6,
            starting_colour_index=1,
            glow_duration=1,
            east=True,
            identifier="command_0x35d739"),
        PauseScriptUntilSpriteSequenceDone(),
        RemoveObject(),
        Db(bytearray(b"\x81")),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        IncAMEM8Bit(0x6C),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnSubroutine(),
    ])
