# pylint: disable=C0301,C0103

"""referenced by items 80"""

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=411,
    script=[
        ClearAMEM16Bit(0x60, identifier="queuestart_0x35eb07"),
        ClearAMEM16Bit(0x6C),
        ClearAMEM16Bit(0x6E),
        Db(bytearray(b" \x8a\x01\x00")),
        PlaySound(sound=S0071_PSYCHOPATH_DRUM_ROLL),
        ObjectQueueAtOffsetAndIndex(index=2, target_address=0x35EAF9),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=128,
            y=140,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0432_STARSLAP,
            sequence=3,
            priority=3,
            vram_address=0x6200,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        ObjectQueueAtOffsetAndIndex(index=8, target_address=0x35EAF9),
        PlaySound(sound=S0072_PSYCHOPATH_CLOUD_APPEARS),
        PauseScriptUntilSpriteSequenceDone(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        ObjectQueueAtOffsetAndIndex(index=4, target_address=0x35EAF9),
        SpriteSequence(sequence=4),
        PauseScriptUntilSpriteSequenceDone(),
        JmpIfAMEM8BitEqualsConst(0x6A, 1, ["command_0x35eb48"]),
        SpriteSequence(sequence=10),
        Jmp(["command_0x35eb4d"]),
        SpriteSequence(sequence=13, identifier="command_0x35eb48"),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=13),
        PauseScriptUntilSpriteSequenceDone(identifier="command_0x35eb4d"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=15),
        SpriteSequence(sequence=4, looping_off=True),
        MoveObject(
            speed=97,
            start_position=-1025,
            end_position=1024,
            apply_to_z=True,
            should_set_start_position=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        Pause1Frame(),
        PauseScriptUntil(condition=BUTTON_PRESSED),
        ResetObjectMappingMemory(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=45),
        PauseScriptUntilAMEMBitsSet(0x6C, [0]),
        ClearAMEM8Bit(0x6F),
        ObjectQueueAtOffsetAndIndex(index=6, target_address=0x35EAF9),
        PauseScriptUntilAMEMBitsSet(0x6F, [0]),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=30),
        DrawSpriteAtAMEM32Coords(
            sprite_id=SPR0518_SMALL_WHITE_CLOUD,
            sequence=0,
            store_to_vram=True,
            store_palette=True,
        ),
        PlaySound(sound=S0115_TRANSFORM),
        PauseScriptUntilSpriteSequenceDone(),
        SetAMEM8BitToConst(0x6E, 1),
        RemoveObject(),
        PauseScriptUntilAMEMBitsSet(0x6D, [0]),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        ReturnObjectQueue(),
        SetAMEM8BitToOMEMMain(amem=0x6A, omem=0x6A, identifier="queuestart_0x35eb8c"),
        Db(bytearray(b"\xa6")),
        ClearAMEM8Bit(0x6C),
        ClearAMEM16Bit(0x60),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=160,
            y=156,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0434_ZEOSTAR,
            sequence=4,
            priority=3,
            vram_address=0x6400,
            palette_row=8,
            overwrite_vram=True,
            param_2_and_0x10=True,
            overwrite_palette=True,
            behind_all_sprites=True,
            overlap_all_sprites=True,
        ),
        ObjectQueueAtOffsetAndIndex(index=10, target_address=0x35EAF9),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=94),
        SpriteSequence(sequence=11),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=11),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=10),
        PauseScriptUntilSpriteSequenceDone(),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=4),
        JmpIfAMEM8BitEqualsConst(0x6A, 1, ["command_0x35ebc6"]),
        SpriteSequence(sequence=10),
        Jmp(["command_0x35ebcb"]),
        SpriteSequence(sequence=13, identifier="command_0x35ebc6"),
        PauseScriptUntilSpriteSequenceDone(),
        SpriteSequence(sequence=13),
        PauseScriptUntilSpriteSequenceDone(identifier="command_0x35ebcb"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=12),
        SpriteSequence(sequence=12),
        PauseScriptUntilSpriteSequenceDone(),
        SetAMEM8BitToConst(0x6C, 1),
        RemoveObject(),
        Pause1Frame(),
        Db(bytearray(b"\xa5")),
        SetOMEMMainToAMEM8Bit(omem=0x6C, amem=0x6C),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=96,
            y=124,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35ebdf",
        ),
        Db(bytearray(b"\x83\x83")),
        Pause1Frame(identifier="command_0x35ebe9"),
        SetAMEM8BitToOMEMMain(amem=0x6C, omem=0x6C),
        JmpIfAMEM8BitNotEqualsConst(0x6C, 1, ["command_0x35ebe9"]),
        RemoveObject(),
        ReturnObjectQueue(),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=32,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35ebf6",
        ),
        DoMaskEffect(CIRCLE_MASK),
        SetMaskCoords((1, 16), (-117, 17), (1, 2), (1, -113)),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=128,
            y=131,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=352, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        SetMaskCoords((1, 24), (32, 15), (1, 0), (34, 111)),
        NewSpriteAtCoords(
            sprite_id=SPR0622_BOOSTER_S_CHOO_CHOO_TRAIN,
            sequence=0,
            priority=2,
            vram_address=0x010E,
            palette_row=6,
            overwrite_palette=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0113_MARRYMORE_MAN_GREEN,
            sequence=4,
            priority=0,
            vram_address=0x6F22,
            palette_row=5,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            mirror_sprite=True,
            invert_sprite=True,
        ),
        Db(bytearray(b"m")),
        NewSpriteAtCoords(
            sprite_id=SPR0618_TENTACLE_EXTENDING,
            sequence=0,
            priority=0,
            vram_address=0x1410,
            palette_row=4,
            overwrite_vram=True,
            overwrite_palette=True,
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0004_MARIO_ATTACK_UP_RIGHT,
            sequence=12,
            priority=0,
            vram_address=0x25AB,
            palette_row=0,
            overwrite_vram=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=29),
        PlaySound(sound=S0010_MALLOW_PUNCH_1),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=18),
        PlaySound(sound=S0010_MALLOW_PUNCH_1),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=27),
        JmpIfAMEM8BitEqualsConst(0x6A, 1, ["command_0x35ec6c"]),
        PlaySound(sound=S0010_MALLOW_PUNCH_1),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        PlaySound(sound=S0010_MALLOW_PUNCH_1),
        Jmp(["command_0x35ec74"]),
        PlaySound(sound=S0048_MALLOW_PUNCH_2, identifier="command_0x35ec6c"),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=20),
        PlaySound(sound=S0048_MALLOW_PUNCH_2),
        ReturnObjectQueue(identifier="command_0x35ec74"),
        SetAMEM32ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=0,
            y=80,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
            identifier="queuestart_0x35ec75",
        ),
        NewSpriteAtCoords(
            sprite_id=SPR0777_STAR_EGG_LITTLE_BROWN_BIRD,
            sequence=1,
            priority=3,
            vram_address=0x6600,
            palette_row=8,
            overwrite_vram=True,
            looping=True,
            overwrite_palette=True,
            overlap_all_sprites=True,
        ),
        SetAMEM40ToXYZCoords(
            origin=ABSOLUTE_POSITION,
            x=272,
            y=80,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=640, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        SetAMEM8BitToConst(0x6F, 1),
        SetOMEMMainToAMEM8Bit(omem=0x6F, amem=0x6F),
        RemoveObject(),
        ReturnObjectQueue(),
    ],
)
