from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=17,
        y=76,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R043_BOOSTER_TOWER_1F_AREA_01_MAIN_ROOM,
        show_message = False,
        dst_x = 29,
        dst_y = 115,
        dst_z = 5,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=14,
        y=70,
        z=8,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R194_BOOSTER_TOWER_2F_AREA_02_BOOSTERS_RAILWAY_ROOM,
        show_message = False,
        dst_x = 4,
        dst_y = 111,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
]
