from .bambino_bomb_prize import *
from .big_boo_flag_prize import *
from .bright_card_prize import *
from .brooch_prize import *
from .castle_key_1_prize import *
from .castle_key_2_prize import *
from .cookies_prize import *
from .cricket_jam_prize import *
from .cricket_pie_prize import *
from .crown_prize import *
from .crystal_shard_prize import *
from .dry_bones_flag_prize import *
from .elder_key_prize import *
from .extra_shiny_stone_prize import *
from .fertilizer_prize import *
from .gold_paint_prize import *
from .greaper_flag_prize import *
from .mario_doll_prize import *
from .progressive_card_prize import *
from .progressive_fireworks_prize import *
from .rare_frog_coin_prize import *
from .ring_prize import *
from .room_key_prize import *
from .seed_prize import *
from .shed_key_prize import *
from .shoes_prize import *
from .stay_voucher_prize import *
from .temple_key_prize import *
from .wallet_prize import *
