from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E0263_BOUNCE_ON_BED,
        x=6,
        y=11,
        z=1,
        f=EdgeDirection.SOUTHWEST,
        length=4,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0263_BOUNCE_ON_BED,
        x=7,
        y=10,
        z=1,
        f=EdgeDirection.SOUTHWEST,
        length=4,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E3686_MARRYMORE_SHOWER,
        x=10,
        y=13,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E3687_MARRYMORE_SHOWER_DOOR,
        x=10,
        y=14,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
]
