# pylint: disable=C0301

"""E0010_SET_70A7_TO_RANDOM_TIER_2_EQUIP"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        SetVarToRandom(PRIMARY_TEMP_7000, 20),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 0, ["EVENT_10_set_0"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 1, ["EVENT_10_set_1"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 2, ["EVENT_10_set_2"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 3, ["EVENT_10_set_3"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 4, ["EVENT_10_set_4"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 5, ["EVENT_10_set_5"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 6, ["EVENT_10_set_6"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 7, ["EVENT_10_set_7"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 8, ["EVENT_10_set_8"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 9, ["EVENT_10_set_9"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 10, ["EVENT_10_set_10"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 11, ["EVENT_10_set_11"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 12, ["EVENT_10_set_12"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 13, ["EVENT_10_set_13"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 14, ["EVENT_10_set_14"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 15, ["EVENT_10_set_15"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 16, ["EVENT_10_set_16"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 17, ["EVENT_10_set_17"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 18, ["EVENT_10_set_18"]),
        SetVarToConst(ITEM_ID, DoublePunch),
        Return(),
        SetVarToConst(ITEM_ID, SafetyBadge, identifier="EVENT_10_set_0"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, TroopaPin, identifier="EVENT_10_set_1"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, FireDress, identifier="EVENT_10_set_2"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, FirePants, identifier="EVENT_10_set_3"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, FireShirt, identifier="EVENT_10_set_4"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, Parasol, identifier="EVENT_10_set_5"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, RibbitStick, identifier="EVENT_10_set_6"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, TroopaShell, identifier="EVENT_10_set_7"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, GhostMedal, identifier="EVENT_10_set_8"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, HandCannon, identifier="EVENT_10_set_9"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, DrillClaw, identifier="EVENT_10_set_10"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, FuzzyDress, identifier="EVENT_10_set_11"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, FuzzyPants, identifier="EVENT_10_set_12"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, FuzzyShirt, identifier="EVENT_10_set_13"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, StarCape, identifier="EVENT_10_set_14"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, SlapGlove, identifier="EVENT_10_set_15"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, SuperHammer, identifier="EVENT_10_set_16"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, WhompGlove, identifier="EVENT_10_set_17"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, Amulet, identifier="EVENT_10_set_18"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
    ]
)
