# E3072_FLOWER_STAR_FC_OR_MUSHROOM_CHEST

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        DisableObjectTrigger(MEM_70A8),
        PlaySound(sound=SO005_BLOCK_SWITCH, channel=6),
        CopyVarToVar(from_var=ITEM_ID, to_var=PRIMARY_TEMP_7000),
        DisableTriggerOfObjectAt70A8InCurrentLevel(),
        Mem7000AndConst(0x00F0),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=CHEST_COIN_SIZE),
        SetSyncActionScript(MEM_70A8, A0007_HIT_TREASURE_CHEST_CONTENTS_DEPLETED),
        Set70107015ToObjectXYZ(MEM_70A8),
        CopyVarToVar(from_var=Z_COORD_1, to_var=PRIMARY_TEMP_7000),
        AddConstToVar(PRIMARY_TEMP_7000, 608),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=Z_COORD_1),
        JmpIfVarEqualsConst(CHEST_COIN_SIZE, 0, ["EVENT_3072_play_sound_16"]),
        JmpIfVarEqualsConst(CHEST_COIN_SIZE, 16, ["EVENT_3072_enable_controls_23"]),
        JmpIfVarEqualsConst(CHEST_COIN_SIZE, 32, ["EVENT_3072_play_sound_39"]),
        JmpIfVarEqualsConst(CHEST_COIN_SIZE, 48, ["EVENT_3072_play_sound_44"]),
        Jmp(["EVENT_3072_ret_47"]),
        PlaySound(sound=SO014_FLOWER, channel=6, identifier="EVENT_3072_play_sound_16"),
        CreatePacketAt7010(
            packet=P001_FLASHING_POOF_MUSHROOM, destinations=["EVENT_3072_ret_47"]
        ),
        RestoreAllHP(),
        RestoreAllFP(),
        SetVarToConst(TIMER_7020, 8),
        RunBackgroundEventWithPause(event_id=E3075_HEAL_FLASH, timer_var=TIMER_7020),
        Set7000ToCurrentLevel(),
        JmpIfVarEqualsConst(
            PRIMARY_TEMP_7000, 453, ["EVENT_3072_enable_controls_until_return_1"]
        ),
        Jmp(["EVENT_3072_ret_47"]),
        EnableControlsUntilReturn(
            [LEFT, RIGHT, DOWN, UP, X, A, Y, B],
            identifier="EVENT_3072_enable_controls_until_return_1",
        ),
        Pause(8),
        PrioritySet(
            mainscreen=[LAYER_3],
            subscreen=[LAYER_1, LAYER_2, NPC_SPRITES],
            colour_math=[BACKGROUND, HALF_INTENSITY],
        ),
        Jmp(["EVENT_3072_ret_47"]),
        EnableControls(
            [LEFT, RIGHT, DOWN, UP, A, Y, B], identifier="EVENT_3072_enable_controls_23"
        ),
        PlaySound(sound=SO014_FLOWER, channel=6),
        CreatePacketAt7010(packet=P003_BRIEF_STAR, destinations=["EVENT_3072_ret_47"]),
        StopMusicFDA0(),
        SetVarToConst(TIMER_7022, 550),
        RunBackgroundEventWithPause(
            event_id=E3076_EXP_STAR_CHEST_BACKGROUND, timer_var=TIMER_7022
        ),
        SetBit(TEMP_7076_0),
        RunEventAsSubroutine(E0357_EXP_STAR_MUSIC_EXPERIMENT),
        JmpIfBitClear(PROGRESSIVE_STAR_EXP_ENABLED, ["EVENT_3072_check_boss_bit"]),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 0, ["EVENT_3072_set_74"]),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 1, ["EVENT_3072_set_77"]),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 2, ["EVENT_3072_set_80"]),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 3, ["EVENT_3072_set_83"]),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 4, ["EVENT_3072_set_86"]),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 5, ["EVENT_3072_set_89"]),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 6, ["EVENT_3072_set_92"]),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 7, ["EVENT_3072_set_92"]),
        Return(),
        JmpIfBitClear(
            PROGRESSIVE_BOSS_EXP_ENABLED,
            ["EVENT_3072_set_7000_to_70A0_short_mem_95"],
            identifier="EVENT_3072_check_boss_bit",
        ),
        CompareVarToConst(BOSS_VICTORY_COUNTER, 21),
        JmpIfComparisonResultIsGreaterOrEqual(["EVENT_3072_set_92"]),
        CompareVarToConst(BOSS_VICTORY_COUNTER, 15),
        JmpIfComparisonResultIsGreaterOrEqual(["EVENT_3072_set_89"]),
        CompareVarToConst(BOSS_VICTORY_COUNTER, 10),
        JmpIfComparisonResultIsGreaterOrEqual(["EVENT_3072_set_86"]),
        CompareVarToConst(BOSS_VICTORY_COUNTER, 6),
        JmpIfComparisonResultIsGreaterOrEqual(["EVENT_3072_set_83"]),
        CompareVarToConst(BOSS_VICTORY_COUNTER, 3),
        JmpIfComparisonResultIsGreaterOrEqual(["EVENT_3072_set_80"]),
        CompareVarToConst(BOSS_VICTORY_COUNTER, 1),
        JmpIfComparisonResultIsGreaterOrEqual(["EVENT_3072_set_77"]),
        SetVarToConst(ITEM_ID, WhompGlove, identifier="EVENT_3072_set_74"),
        Jmp(["EVENT_3072_set_7000_to_70A0_short_mem_95"]),
        Return(),
        SetVarToConst(ITEM_ID, SlapGlove, identifier="EVENT_3072_set_77"),
        Jmp(["EVENT_3072_set_7000_to_70A0_short_mem_95"]),
        Return(),
        SetVarToConst(ITEM_ID, TroopaShell, identifier="EVENT_3072_set_80"),
        Jmp(["EVENT_3072_set_7000_to_70A0_short_mem_95"]),
        Return(),
        SetVarToConst(ITEM_ID, Parasol, identifier="EVENT_3072_set_83"),
        Jmp(["EVENT_3072_set_7000_to_70A0_short_mem_95"]),
        Return(),
        SetVarToConst(ITEM_ID, HurlyGloves, identifier="EVENT_3072_set_86"),
        Jmp(["EVENT_3072_set_7000_to_70A0_short_mem_95"]),
        Return(),
        SetVarToConst(ITEM_ID, DoublePunch, identifier="EVENT_3072_set_89"),
        Jmp(["EVENT_3072_set_7000_to_70A0_short_mem_95"]),
        Return(),
        SetVarToConst(ITEM_ID, SpikedLink, identifier="EVENT_3072_set_92"),
        Jmp(["EVENT_3072_set_7000_to_70A0_short_mem_95"]),
        Return(),
        CopyVarToVar(
            from_var=ITEM_ID,
            to_var=PRIMARY_TEMP_7000,
            identifier="EVENT_3072_set_7000_to_70A0_short_mem_95",
        ),
        Mem7000AndConst(0x000F),
        SetEXPPacketTo7000(),
        MarioGlows(),
        ClearBit(EXP_STAR_BIT_6),
        ClearBit(UNKNOWN_7064_5),
        ClearBit(EXP_STAR_BIT_5),
        CreatePacketAtObjectCoords(
            packet=P022_RECURSIVE_SPARKLES,
            object=MARIO,
            destinations=["EVENT_3072_jmp_38"],
        ),
        Jmp(["EVENT_3072_ret_47"], identifier="EVENT_3072_jmp_38"),
        PlaySound(sound=SO014_FLOWER, channel=6, identifier="EVENT_3072_play_sound_39"),
        CreatePacketAt7010(
            packet=P000_FLASHING_POOF_FLOWER, destinations=["EVENT_3072_ret_47"]
        ),
        SetVarToConst(PRIMARY_TEMP_7000, 1),
        Add7000ToMaxFP(),
        Jmp(["EVENT_3072_ret_47"]),
        PlaySound(
            sound=SO094_FROG_COIN, channel=6, identifier="EVENT_3072_play_sound_44"
        ),
        CreatePacketAt7010(
            packet=P019_FROG_COIN_BEING_COLLECTED, destinations=["EVENT_3072_ret_47"]
        ),
        AddFrogCoins(1),
        Return(identifier="EVENT_3072_ret_47"),
    ]
)
