# E3885_END_GAME

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        FreezeCamera(),
        Set0158Bit7Offset(True),
        PlayMusicAtCurrentVolume(M23_GOT_A_STAR_PIECE_PART_1),
        Pause(1),
        StopMusicFDA2(),
        ActionQueueSync(
            target=SCREEN_FOCUS,
            subscript=[ASSetWalkingSpeed(FASTEST), ASShiftWestPixels(8)],
        ),
        ActionQueueSync(
            target=LAYER_3,
            subscript=[
                ASSetWalkingSpeed(FASTEST),
                ASShiftEastPixels(22),
                ASShiftNorthSteps(16),
            ],
        ),
        ActionQueueSync(
            target=NPC_7,
            subscript=[
                ASTransferToXYZF(x=6, y=50, z=0, direction=EAST),
                ASSetSpriteSequence(index=1, is_sequence=True, looping=True),
            ],
        ),
        ActionQueueSync(
            target=MARIO,
            subscript=[ASTransferToXYZF(x=3, y=53, z=0, direction=EAST), ASFaceEast()],
        ),
        ActionQueueSync(
            target=NPC_20,
            subscript=[
                ASTransferToXYZF(x=1, y=54, z=0, direction=EAST),
                ASTransferXYZFPixels(x=16, y=0, z=0, direction=EAST),
                ASFaceSoutheast(),
            ],
        ),
        ActionQueueSync(
            target=NPC_21,
            subscript=[
                ASTransferToXYZF(x=2, y=59, z=0, direction=EAST),
                ASFaceNortheast(),
                ASSetSpriteSequence(
                    index=12,
                    sprite_offset=1,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                ),
                ASPause(1),
                ASResetProperties(),
            ],
        ),
        ActionQueueSync(
            target=NPC_19,
            subscript=[
                ASTransferToXYZF(x=3, y=58, z=0, direction=EAST),
                ASTransferXYZFPixels(x=8, y=4, z=0, direction=EAST),
                ASFaceNortheast(),
            ],
        ),
        ActionQueueSync(
            target=NPC_23,
            subscript=[
                ASTransferToXYZF(x=1, y=57, z=0, direction=EAST),
                ASTransferXYZFPixels(x=16, y=0, z=0, direction=EAST),
                ASFaceNortheast(),
            ],
        ),
        RememberLastObject(),
        SetSyncActionScript(NPC_7, A0120_EMBEDDED_ROUTINE),
        FadeInFromColour(duration=90, colour=WHITE),
        PauseScriptUntilEffectDone(),
        Pause(120),
        PauseActionScript(NPC_7),
        ActionQueueSync(
            target=NPC_7,
            subscript=[
                ASShadowOff(),
                ASBPL262728(),
                ASShiftZUpPixels(4),
                ASSetWalkingSpeed(FAST),
                ASShiftZUpPixels(8),
                ASSetWalkingSpeed(VERY_FAST),
                ASShiftZUpPixels(4),
                ASAddZCoord1Step(),
                ASSetWalkingSpeed(FASTEST),
                ASShiftZUpSteps(3),
            ],
        ),
        ActionQueueSync(
            target=NPC_15,
            subscript=[
                ASVisibilityOff(),
                ASPause(11),
                ASTransferToXYZF(x=6, y=50, z=0, direction=EAST),
                ASTransferXYZFPixels(x=252, y=0, z=0, direction=EAST),
                ASVisibilityOn(),
                ASSetWalkingSpeed(FASTEST),
                ASShiftZUpSteps(2),
                ASVisibilityOff(),
            ],
        ),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASSetWalkingSpeed(SLOW),
                ASShiftEastPixels(16),
                ASFaceNortheast(),
                ASSetSpriteSequence(
                    index=23,
                    sprite_offset=2,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                ),
            ],
        ),
        RememberLastObject(),
        SetSyncActionScript(NPC_7, A0120_EMBEDDED_ROUTINE),
        Pause(60),
        Pause(10),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASResetProperties(),
                ASStartLoopNTimes(3),
                ASTurnClockwise45DegreesNTimes(1),
                ASPause(2),
                ASEndLoop(),
            ],
        ),
        ActionQueueSync(
            target=NPC_19,
            subscript=[
                ASSetSpriteSequence(
                    index=18,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                )
            ],
        ),
        ActionQueueSync(
            target=NPC_23,
            subscript=[
                ASSetSpriteSequence(
                    index=19,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                )
            ],
        ),
        ActionQueueSync(
            target=NPC_20,
            subscript=[
                ASSetSpriteSequence(
                    index=17,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                )
            ],
        ),
        RememberLastObject(),
        Pause(10),
        ActionQueueAsync(
            target=NPC_21,
            subscript=[
                ASResetProperties(),
                ASPause(2),
                ASSetSpriteSequence(
                    index=12,
                    sprite_offset=1,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                ),
                ASPause(8),
                ASSetSpriteSequence(
                    index=13,
                    sprite_offset=1,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                ),
                ASPause(4),
                ASSetSpriteSequence(
                    index=14,
                    sprite_offset=1,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                ),
                ASPause(4),
                ASSetSpriteSequence(
                    index=15,
                    sprite_offset=1,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                ),
            ],
        ),
        Pause(10),
        Pause(10),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        Pause(30),
        ActionQueueSync(target=NPC_21, subscript=[ASResetProperties()]),
        ActionQueueSync(target=NPC_20, subscript=[ASResetProperties()]),
        ActionQueueSync(target=NPC_23, subscript=[ASResetProperties()]),
        ActionQueueSync(target=NPC_19, subscript=[ASResetProperties()]),
        RememberLastObject(),
        Pause(10),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASStartLoopNTimes(3),
                ASTurnClockwise45DegreesNTimes(1),
                ASPause(2),
                ASEndLoop(),
            ],
        ),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASPause(8),
                ASSetSpriteSequence(
                    index=23,
                    sprite_offset=2,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                ),
            ],
        ),
        Pause(6),
        PlayMusicAtDefaultVolume(M23_GOT_A_STAR_PIECE_PART_1),
        RememberLastObject(),
        Pause(60),
        PauseActionScript(NPC_7),
        ActionQueueAsync(
            target=NPC_7,
            subscript=[
                ASBPL262728(),
                ASSetWalkingSpeed(VERY_SLOW),
                ASBounceToXYWithHeight(x=6, y=50, height=10),
                ASSetSpriteSequence(index=0, is_sequence=True, looping=True),
            ],
        ),
        Pause(60),
        ActionQueueAsync(
            target=NPC_0,
            subscript=[
                ASTransferToXYZF(x=4, y=54, z=0, direction=EAST),
                ASTransferXYZFPixels(x=8, y=252, z=0, direction=EAST),
            ],
        ),
        SetSyncActionScript(NPC_0, A0248_ENDING_CUTSCENE_EFFECT),
        ActionQueueAsync(
            target=NPC_7,
            subscript=[ASPause(2), ASSetObjectMemoryBits(arg_1=0x0E, bits=[0, 1, 2])],
        ),
        ActionQueueSync(
            target=SCREEN_FOCUS,
            subscript=[
                ASDb(bytearray(b" \x03")),
                ASDb(bytearray(b"$\xf0\xff\xc0\xff")),
                ASPause(64),
                ASBPL262728(),
            ],
        ),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASPause(60),
                ASResetProperties(),
                ASPause(4),
                ASStartLoopNTimes(4),
                ASTurnClockwise45DegreesNTimes(7),
                ASPause(4),
                ASEndLoop(),
            ],
        ),
        ActionQueueSync(
            target=NPC_19,
            subscript=[
                ASSequenceLoopingOn(),
                ASDb(bytearray(b" \x03")),
                ASDb(bytearray(b"$\x80\x00\xe0\xff")),
                ASPause(140),
                ASBPL262728(),
                ASSequenceLoopingOff(),
                ASFaceNorthwest(),
            ],
        ),
        ActionQueueSync(
            target=NPC_20,
            subscript=[
                ASFaceNortheast(),
                ASSetSequenceSpeed(FAST),
                ASFixedFCoordOn(),
                ASSequenceLoopingOn(),
                ASDb(bytearray(b" \x03")),
                ASDb(bytearray(b"$0\x00\x80\xff")),
                ASPause(64),
                ASBPL262728(),
                ASFixedFCoordOff(),
                ASSequenceLoopingOff(),
                ASFaceSoutheast(),
            ],
        ),
        Db(bytearray(b"\xfd\x8e\x16\n\x0b")),
        RememberLastObject(),
        UnsyncActionScript(NPC_0),
        ActionQueueAsync(
            target=NPC_7, subscript=[ASSetObjectMemoryBits(arg_1=0x0E, bits=[])]
        ),
        SetSyncActionScript(NPC_7, A0120_EMBEDDED_ROUTINE),
        Pause(120),
        PauseActionScript(NPC_7),
        StartSyncEmbeddedActionScript(
            target=NPC_7,
            prefix=0xF1,
            subscript=[
                ASBPL262728(),
                ASSetWalkingSpeed(NORMAL),
                ASShiftZUpPixels(7),
                ASSetWalkingSpeed(FAST),
                ASShiftZUpPixels(8),
                ASSetWalkingSpeed(VERY_FAST),
                ASAddZCoord1Step(),
                ASSetWalkingSpeed(FASTEST),
                ASShiftZUpSteps(2),
            ],
        ),
        ActionQueueSync(
            target=NPC_15,
            subscript=[
                ASSequencePlaybackOff(),
                ASPause(12),
                ASSequencePlaybackOn(),
                ASTransferToXYZF(x=4, y=46, z=0, direction=EAST),
                ASTransferXYZFPixels(x=248, y=0, z=0, direction=EAST),
                ASVisibilityOn(),
                ASSetWalkingSpeed(VERY_FAST),
                ASAddZCoord1Step(),
                ASVisibilityOff(),
            ],
        ),
        RememberLastObject(),
        SetSyncActionScript(NPC_7, A0120_EMBEDDED_ROUTINE),
        Pause(120),
        PauseActionScript(NPC_7),
        StartAsyncEmbeddedActionScript(
            target=NPC_7,
            prefix=0xF1,
            subscript=[
                ASBPL262728(),
                ASSetSequenceSpeed(FAST),
                ASPause(30),
                ASSetSequenceSpeed(VERY_FAST),
                ASPause(62),
                ASSetSequenceSpeed(FASTEST),
            ],
        ),
        Pause(60),
        PlayMusicAtDefaultVolume(M24_GOT_A_STAR_PIECE_PART_2),
        Pause(60),
        ActionQueueSync(
            target=NPC_7,
            subscript=[
                ASSetWalkingSpeed(VERY_FAST),
                ASShiftZDownSteps(5),
                ASShiftZDownPixels(4),
                ASSetSpriteSequence(index=2, is_sequence=True, looping=True),
            ],
        ),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASPause(16),
                ASSetSpriteSequence(index=5, is_sequence=True, looping=True),
            ],
        ),
        Pause(200),
        ActionQueueSync(
            target=NPC_7,
            subscript=[
                ASSetWalkingSpeed(SLOW),
                ASShiftZUpSteps(6),
                ASSetWalkingSpeed(VERY_SLOW),
                ASShiftZUpSteps(1),
                ASShiftZUpPixels(6),
            ],
        ),
        ActionQueueSync(
            target=SCREEN_FOCUS,
            subscript=[
                ASPause(34),
                ASSetWalkingSpeed(NORMAL),
                ASShiftZUpSteps(4),
                ASSetWalkingSpeed(SLOW),
                ASAddZCoord1Step(),
            ],
        ),
        Pause(100),
        Db(bytearray(b"\xfd\x8e\x00\n\n")),
        RememberLastObject(),
        SetSyncActionScript(NPC_7, A0120_EMBEDDED_ROUTINE),
        Pause(98),
        PauseActionScript(NPC_7),
        ActionQueueSync(
            target=NPC_7,
            subscript=[ASBPL262728(), ASSetWalkingSpeed(FASTEST), ASShiftZUpSteps(8)],
        ),
        ActionQueueSync(
            target=NPC_15,
            subscript=[
                ASTransferToXYZF(x=4, y=38, z=0, direction=EAST),
                ASTransferXYZFPixels(x=250, y=0, z=0, direction=EAST),
                ASVisibilityOn(),
                ASSetWalkingSpeed(FASTEST),
                ASShiftZUpSteps(4),
            ],
        ),
        RememberLastObject(),
        RunStarPieceSequence(7),
        Db(bytearray(b"\xfd\x8er\x00\x00")),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASResetProperties(),
                ASTransferXYZFPixels(x=0, y=16, z=0, direction=EAST),
            ],
        ),
        SetBit(TEMP_7049_6),
        RunEventAsSubroutine(E0276_REFOCUS_CAMERA_ON_SELF),
        FreezeCamera(),
        ActionQueueSync(
            target=MARIO, subscript=[ASTransferToXYZF(x=4, y=51, z=0, direction=EAST)]
        ),
        ActionQueueAsync(
            target=SCREEN_FOCUS,
            subscript=[
                ASSetWalkingSpeed(FASTEST),
                ASShiftNorthSteps(2),
                ASShiftWestPixels(8),
            ],
        ),
        ActionQueueSync(
            target=NPC_21,
            subscript=[
                ASSetSequenceSpeed(NORMAL),
                ASSequenceLoopingOn(),
                ASDb(bytearray(b" \x03")),
                ASDb(bytearray(b"$\x80\x00\x80\xff")),
                ASPause(88),
                ASBPL262728(),
                ASSequenceLoopingOff(),
            ],
        ),
        Clear0158Bit7Offset(True),
        FadeInFromBlack(sync=True, duration=60),
        PauseScriptUntilEffectDone(),
        RememberLastObject(),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASFaceSouthwest(),
                ASPause(30),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
                ASPause(8),
                ASResetProperties(),
            ],
        ),
        Pause(30),
        ActionQueueAsync(
            target=NPC_21,
            subscript=[
                ASSetSpriteSequence(
                    index=7, is_sequence=True, looping=True, mirror_sprite=True
                ),
                ASPause(8),
                ASResetProperties(),
                ASPause(30),
                ASFaceSoutheast(),
                ASPause(2),
                ASFaceSouthwest(),
            ],
        ),
        Pause(60),
        ActionQueueSync(
            target=NPC_20,
            subscript=[
                ASSetSpriteSequence(
                    index=6, is_sequence=True, looping=True, mirror_sprite=True
                ),
                ASPause(8),
                ASResetProperties(),
            ],
        ),
        ActionQueueSync(
            target=NPC_19,
            subscript=[
                ASSetSpriteSequence(index=7, is_sequence=True, looping=True),
                ASPause(8),
                ASResetProperties(),
            ],
        ),
        ActionQueueSync(
            target=NPC_23,
            subscript=[
                ASSetSpriteSequence(
                    index=7, is_sequence=True, looping=True, mirror_sprite=True
                ),
                ASPause(8),
                ASResetProperties(),
            ],
        ),
        RememberLastObject(),
        Pause(30),
        ActionQueueAsync(
            target=NPC_21,
            subscript=[
                ASSetSequenceSpeed(NORMAL),
                ASSetSpriteSequence(
                    index=10, sprite_offset=1, is_sequence=True, looping=False
                ),
            ],
        ),
        Pause(60),
        PlayMusicAtDefaultVolume(M70_ENDING_PART_1),
        ActionQueueAsync(target=NPC_21, subscript=[ASResetProperties()]),
        Pause(30),
        ActionQueueSync(
            target=NPC_20,
            subscript=[
                ASSetWalkingSpeed(VERY_SLOW),
                ASWalk1StepSoutheast(),
                ASSetSpriteSequence(
                    index=0,
                    sprite_offset=2,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
                ASJumpToHeight(height=64, silent=True),
                ASSetWalkingSpeed(NORMAL),
                ASWalk1StepNorthwest(),
                ASPause(60),
                ASFaceSoutheast(),
                ASResetProperties(),
            ],
        ),
        ActionQueueSync(
            target=NPC_23,
            subscript=[
                ASSetWalkingSpeed(VERY_SLOW),
                ASWalk1StepNortheast(),
                ASSetSpriteSequence(
                    index=8,
                    sprite_offset=1,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                ),
                ASSetWalkingSpeed(NORMAL),
                ASJumpToHeight(height=64, silent=True),
                ASWalk1StepSouthwest(),
                ASPause(60),
                ASFaceNortheast(),
                ASResetProperties(),
            ],
        ),
        ActionQueueSync(
            target=NPC_19,
            subscript=[
                ASSetWalkingSpeed(VERY_SLOW),
                ASWalk1StepNorthwest(),
                ASSetSpriteSequence(
                    index=8,
                    sprite_offset=1,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
                ASSetWalkingSpeed(NORMAL),
                ASJumpToHeight(height=64, silent=True),
                ASWalk1StepSoutheast(),
                ASPause(60),
                ASFaceNorthwest(),
                ASResetProperties(),
            ],
        ),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASPause(60),
                ASSetSpriteSequence(
                    index=0, sprite_offset=3, is_sequence=True, looping=True
                ),
                ASSetWalkingSpeed(NORMAL),
                ASJumpToHeight(height=92, silent=True),
                ASWalk1StepNortheast(),
                ASShiftNortheastPixels(10),
                ASPause(80),
                ASFaceSouthwest(),
                ASResetProperties(),
            ],
        ),
        ActionQueueSync(
            target=NPC_8,
            subscript=[
                ASSequenceLoopingOn(),
                ASPause(20),
                ASTransferToXYZF(x=4, y=49, z=20, direction=EAST),
                ASTransferXYZFPixels(x=246, y=8, z=0, direction=EAST),
                ASFloatingOn(),
            ],
        ),
        ActionQueueSync(
            target=NPC_9,
            subscript=[
                ASSequenceLoopingOn(),
                ASPause(30),
                ASTransferToXYZF(x=4, y=53, z=20, direction=EAST),
                ASTransferXYZFPixels(x=4, y=248, z=0, direction=EAST),
                ASFloatingOn(),
            ],
        ),
        ActionQueueSync(
            target=NPC_10,
            subscript=[
                ASSequenceLoopingOn(),
                ASPause(32),
                ASTransferToXYZF(x=4, y=56, z=20, direction=EAST),
                ASTransferXYZFPixels(x=12, y=246, z=0, direction=EAST),
                ASFloatingOn(),
            ],
        ),
        ActionQueueSync(
            target=NPC_11,
            subscript=[
                ASSequenceLoopingOn(),
                ASPause(24),
                ASTransferToXYZF(x=4, y=56, z=20, direction=EAST),
                ASTransferXYZFPixels(x=244, y=0, z=0, direction=EAST),
                ASFloatingOn(),
            ],
        ),
        ActionQueueSync(
            target=NPC_12,
            subscript=[
                ASSequenceLoopingOn(),
                ASPause(34),
                ASTransferToXYZF(x=3, y=54, z=20, direction=EAST),
                ASTransferXYZFPixels(x=252, y=0, z=0, direction=EAST),
                ASFloatingOn(),
            ],
        ),
        ActionQueueSync(
            target=NPC_13,
            subscript=[
                ASSequenceLoopingOn(),
                ASPause(50),
                ASTransferToXYZF(x=3, y=52, z=20, direction=EAST),
                ASTransferXYZFPixels(x=250, y=252, z=0, direction=EAST),
                ASFloatingOn(),
            ],
        ),
        ActionQueueSync(
            target=NPC_14,
            subscript=[
                ASSequenceLoopingOn(),
                ASPause(40),
                ASTransferToXYZF(x=4, y=50, z=20, direction=EAST),
                ASTransferXYZFPixels(x=238, y=252, z=0, direction=EAST),
                ASFloatingOn(),
            ],
        ),
        RememberLastObject(),
        Db(bytearray(b"^")),
        SetSyncActionScript(NPC_8, A0120_EMBEDDED_ROUTINE),
        SetSyncActionScript(NPC_9, A0120_EMBEDDED_ROUTINE),
        SetSyncActionScript(NPC_10, A0120_EMBEDDED_ROUTINE),
        SetSyncActionScript(NPC_11, A0120_EMBEDDED_ROUTINE),
        SetSyncActionScript(NPC_12, A0120_EMBEDDED_ROUTINE),
        SetSyncActionScript(NPC_13, A0120_EMBEDDED_ROUTINE),
        SetSyncActionScript(NPC_14, A0120_EMBEDDED_ROUTINE),
        Pause(90),
        SetSyncActionScript(NPC_4, A0251_ENDING_CUTSCENE_EFFECT),
        Pause(24),
        SetSyncActionScript(NPC_5, A0252_ENDING_CUTSCENE_EFFECT),
        Pause(24),
        SetSyncActionScript(NPC_6, A0253_ENDING_CUTSCENE_EFFECT),
        Pause(24),
        SetSyncActionScript(NPC_0, A0254_ENDING_CUTSCENE_EFFECT),
        Pause(24),
        SetSyncActionScript(NPC_1, A0255_ENDING_CUTSCENE_EFFECT),
        Pause(24),
        SetSyncActionScript(NPC_2, A0224_ENDING_CUTSCENE_EFFECT),
        Pause(24),
        SetSyncActionScript(NPC_3, A0225_ENDING_CUTSCENE_EFFECT),
        Pause(24),
        PauseActionScript(NPC_12),
        PauseActionScript(NPC_13),
        PauseActionScript(NPC_14),
        PauseActionScript(NPC_8),
        PauseActionScript(NPC_9),
        PauseActionScript(NPC_10),
        PauseActionScript(NPC_11),
        SetSyncActionScript(NPC_12, A0226_ENDING_CUTSCENE_EFFECT),
        SetSyncActionScript(NPC_13, A0226_ENDING_CUTSCENE_EFFECT),
        SetSyncActionScript(NPC_14, A0226_ENDING_CUTSCENE_EFFECT),
        SetSyncActionScript(NPC_8, A0226_ENDING_CUTSCENE_EFFECT),
        SetSyncActionScript(NPC_9, A0226_ENDING_CUTSCENE_EFFECT),
        SetSyncActionScript(NPC_10, A0226_ENDING_CUTSCENE_EFFECT),
        SetSyncActionScript(NPC_11, A0226_ENDING_CUTSCENE_EFFECT),
        Pause(420),
        SetSyncActionScript(NPC_21, A0227_ENDING_CUTSCENE_EFFECT),
        Pause(1, identifier="EVENT_3885_pause_188"),
        JmpIfBitSet(TEMP_7043_0, ["EVENT_3885_action_queue_sync_191"]),
        Jmp(["EVENT_3885_pause_188"]),
        ActionQueueSync(
            target=NPC_15,
            subscript=[
                ASPause(8),
                ASVisibilityOff(),
                ASTransferToXYZF(x=3, y=42, z=0, direction=EAST),
                ASTransferXYZFPixels(x=248, y=248, z=0, direction=EAST),
                ASSetSequenceSpeed(FAST),
                ASVisibilityOn(),
                ASPause(8),
                ASVisibilityOff(),
                ASSetObjectMemoryBits(arg_1=0x0E, bits=[]),
            ],
            identifier="EVENT_3885_action_queue_sync_191",
        ),
        Pause(1, identifier="EVENT_3885_pause_192"),
        JmpIfBitSet(TEMP_7043_1, ["EVENT_3885_action_queue_sync_195"]),
        Jmp(["EVENT_3885_pause_192"]),
        ActionQueueSync(
            target=NPC_16,
            subscript=[
                ASPause(6),
                ASTransferToXYZF(x=4, y=41, z=0, direction=EAST),
                ASTransferXYZFPixels(x=252, y=0, z=0, direction=EAST),
                ASSetSequenceSpeed(FAST),
                ASVisibilityOn(),
                ASPause(10),
                ASVisibilityOff(),
                ASSetObjectMemoryBits(arg_1=0x0E, bits=[]),
            ],
            identifier="EVENT_3885_action_queue_sync_195",
        ),
        Pause(1, identifier="EVENT_3885_pause_196"),
        JmpIfBitSet(TEMP_7043_2, ["EVENT_3885_action_queue_sync_199"]),
        Jmp(["EVENT_3885_pause_196"]),
        ActionQueueSync(
            target=NPC_17,
            subscript=[
                ASVisibilityOff(),
                ASTransferToXYZF(x=4, y=43, z=0, direction=EAST),
                ASTransferXYZFPixels(x=250, y=12, z=0, direction=EAST),
                ASSetSequenceSpeed(FAST),
                ASVisibilityOn(),
                ASDb(bytearray(b" \x03")),
                ASDb(bytearray(b"$\x00\xfa\x00\xfa")),
                ASPause(32),
                ASBPL262728(),
                ASVisibilityOff(),
            ],
            identifier="EVENT_3885_action_queue_sync_199",
        ),
        Pause(1, identifier="EVENT_3885_pause_200"),
        JmpIfBitSet(TEMP_7043_3, ["EVENT_3885_action_queue_sync_203"]),
        Jmp(["EVENT_3885_pause_200"]),
        ActionQueueSync(
            target=NPC_18,
            subscript=[
                ASVisibilityOff(),
                ASTransferToXYZF(x=4, y=46, z=0, direction=EAST),
                ASTransferXYZFPixels(x=6, y=244, z=0, direction=EAST),
                ASSetSequenceSpeed(FAST),
                ASVisibilityOn(),
                ASDb(bytearray(b" \x03")),
                ASDb(bytearray(b"$ \xfc\xe0\xfb")),
                ASPause(32),
                ASBPL262728(),
                ASVisibilityOff(),
            ],
            identifier="EVENT_3885_action_queue_sync_203",
        ),
        Pause(1, identifier="EVENT_3885_pause_204"),
        JmpIfBitSet(TEMP_7043_4, ["EVENT_3885_action_queue_sync_207"]),
        Jmp(["EVENT_3885_pause_204"]),
        ActionQueueSync(
            target=NPC_15,
            subscript=[
                ASPause(4),
                ASTransferToXYZF(x=2, y=45, z=0, direction=EAST),
                ASTransferXYZFPixels(x=4, y=6, z=0, direction=EAST),
                ASSetSequenceSpeed(FAST),
                ASVisibilityOn(),
                ASSetWalkingSpeed(VERY_FAST),
                ASShiftNortheastPixels(8),
                ASDb(bytearray(b" \x03")),
                ASDb(bytearray(b"$\xe0\x05\xe0\xf8")),
                ASPause(32),
                ASBPL262728(),
                ASVisibilityOff(),
            ],
            identifier="EVENT_3885_action_queue_sync_207",
        ),
        Pause(1, identifier="EVENT_3885_pause_208"),
        JmpIfBitSet(TEMP_7043_5, ["EVENT_3885_action_queue_sync_211"]),
        Jmp(["EVENT_3885_pause_208"]),
        ActionQueueSync(
            target=NPC_16,
            subscript=[
                ASTransferToXYZF(x=4, y=49, z=0, direction=EAST),
                ASSetSequenceSpeed(FAST),
                ASVisibilityOn(),
                ASDb(bytearray(b" \x03")),
                ASDb(bytearray(b"$\x00\xfe\x00\xf8")),
                ASPause(32),
                ASBPL262728(),
                ASVisibilityOff(),
            ],
            identifier="EVENT_3885_action_queue_sync_211",
        ),
        Pause(1, identifier="EVENT_3885_pause_212"),
        JmpIfBitSet(TEMP_7043_6, ["EVENT_3885_action_queue_sync_215"]),
        Jmp(["EVENT_3885_pause_212"]),
        ActionQueueSync(
            target=NPC_17,
            subscript=[
                ASTransferToXYZF(x=5, y=45, z=0, direction=EAST),
                ASTransferXYZFPixels(x=232, y=4, z=0, direction=EAST),
                ASSetSequenceSpeed(FAST),
                ASVisibilityOn(),
                ASDb(bytearray(b" \x03")),
                ASDb(bytearray(b"$\x00\xfe\x00\xf8")),
                ASPause(32),
                ASBPL262728(),
                ASVisibilityOff(),
            ],
            identifier="EVENT_3885_action_queue_sync_215",
        ),
        Pause(180),
        ActionQueueAsync(
            target=LAYER_3, subscript=[ASSetWalkingSpeed(FAST), ASShiftSouthSteps(40)]
        ),
        Pause(90),
        FadeOutToColour(duration=120, colour=WHITE),
        PauseScriptUntilEffectDone(),
        Pause(30),
        JmpToEvent(E3950_POST_FINAL_BOSS_INIT),
    ]
)
