# pylint: disable=C0301

"""E1707_BANDITS_WAY_5_LOADER_BACKGROUND"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        PauseActionScript(NPC_5),
        PauseActionScript(NPC_6),
        PauseActionScript(NPC_7),
        PauseActionScript(NPC_8),
        ResetCoords(NPC_5),
        ResetCoords(NPC_6),
        ResetCoords(NPC_7),
        ResetCoords(NPC_8),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[
                ASVisibilityOn(),
                ASSetAllSpeeds(VERY_FAST),
                ASClearSolidityBits(cant_pass_walls=True),
                ASClearSolidityBits(
                    bit_4=True, cant_pass_npcs=True, cant_walk_through=True, bit_7=True
                ),
                ASJmpIfBitClear(TEMP_7043_7, ["EVENT_1707_clear_bit_9"]),
                ASWalk1StepSouth(),
                ASWalk1StepSoutheast(),
                ASWalk1StepEast(),
                ASWalkNortheastSteps(3),
            ]),
        ClearBit(TEMP_7044_6, identifier="EVENT_1707_clear_bit_9"),
        SetVarToRandom(PRIMARY_TEMP_7000, 32768),
        JmpIf7000AllBitsClear(bits=[], destinations=["EVENT_1707_clear_bit_13"]),
        SetBit(TEMP_7044_6),
        ClearBit(TEMP_7044_7, identifier="EVENT_1707_clear_bit_13"),
        CompareVarToConst(PRIMARY_TEMP_7000, 16384),
        JmpIfComparisonResultIsLesser(["EVENT_1707_mem_7000_and_const_17"]),
        SetBit(TEMP_7044_7),
        Mem7000AndConst(0x3FFF, identifier="EVENT_1707_mem_7000_and_const_17"),
        CompareVarToConst(PRIMARY_TEMP_7000, 8192),
        JmpIfComparisonResultIsLesser(["EVENT_1707_jmp_if_bit_set_22"]),
        JmpIfBitSet(TEMP_7044_7, ["EVENT_1707_set_77"]),
        Jmp(["EVENT_1707_set_59"]),
        JmpIfBitSet(
            TEMP_7044_7,
            ["EVENT_1707_set_41"],
            identifier="EVENT_1707_jmp_if_bit_set_22"),
        SetVarToConst(PRIMARY_TEMP_7000, 12288),
        JmpIfBitSet(TEMP_7044_0, ["EVENT_1707_clear_bit_13"]),
        JmpIfBitSet(TEMP_7044_1, ["EVENT_1707_action_queue_async_32"]),
        JmpIfBitSet(TEMP_7044_2, ["EVENT_1707_action_queue_async_30"]),
        JmpIfBitSet(TEMP_7044_3, ["EVENT_1707_action_queue_async_28"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[ASWalkNortheastSteps(8)],
            identifier="EVENT_1707_action_queue_async_28"),
        Jmp(["EVENT_1707_action_queue_async_34"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[
                ASWalk1StepNortheast(),
                ASWalk1StepNorth(),
                ASWalk1StepNorthwest(),
                ASShiftNorthSteps(8),
            ],
            identifier="EVENT_1707_action_queue_async_30"),
        Jmp(["EVENT_1707_action_queue_async_34"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[
                ASWalk1StepNortheast(),
                ASWalk1StepNorth(),
                ASWalkNorthwestSteps(9),
            ],
            identifier="EVENT_1707_action_queue_async_32"),
        Jmp(["EVENT_1707_action_queue_async_34"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[ASBounceToXYWithHeight(x=11, y=95, height=0)],
            identifier="EVENT_1707_action_queue_async_34"),
        SetVarToConst(TEMP_70A9, 25),
        ClearBit(TEMP_7044_1),
        ClearBit(TEMP_7044_2),
        ClearBit(TEMP_7044_3),
        SetBit(TEMP_7044_0),
        Jmp(["EVENT_1707_action_queue_sync_97"]),
        SetVarToConst(PRIMARY_TEMP_7000, 28672, identifier="EVENT_1707_set_41"),
        JmpIfBitSet(TEMP_7044_1, ["EVENT_1707_clear_bit_13"]),
        JmpIfBitSet(TEMP_7044_0, ["EVENT_1707_action_queue_async_50"]),
        JmpIfBitSet(TEMP_7044_2, ["EVENT_1707_action_queue_async_48"]),
        JmpIfBitSet(TEMP_7044_3, ["EVENT_1707_action_queue_async_46"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[
                ASWalkSoutheastSteps(7),
                ASWalkEastSteps(3),
                ASWalkNortheastSteps(3),
            ],
            identifier="EVENT_1707_action_queue_async_46"),
        Jmp(["EVENT_1707_action_queue_async_52"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[ASWalkNortheastSteps(8)],
            identifier="EVENT_1707_action_queue_async_48"),
        Jmp(["EVENT_1707_action_queue_async_52"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[
                ASWalkSoutheastSteps(9),
                ASWalk1StepSouth(),
                ASWalk1StepSouthwest(),
            ],
            identifier="EVENT_1707_action_queue_async_50"),
        Jmp(["EVENT_1707_action_queue_async_52"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[ASBounceToXYWithHeight(x=15, y=107, height=0)],
            identifier="EVENT_1707_action_queue_async_52"),
        SetVarToConst(TEMP_70A9, 25),
        ClearBit(TEMP_7044_0),
        ClearBit(TEMP_7044_2),
        ClearBit(TEMP_7044_3),
        SetBit(TEMP_7044_1),
        Jmp(["EVENT_1707_action_queue_sync_100"]),
        SetVarToConst(PRIMARY_TEMP_7000, 4096, identifier="EVENT_1707_set_59"),
        JmpIfBitSet(TEMP_7044_2, ["EVENT_1707_clear_bit_13"]),
        JmpIfBitSet(TEMP_7044_0, ["EVENT_1707_action_queue_async_68"]),
        JmpIfBitSet(TEMP_7044_1, ["EVENT_1707_action_queue_async_66"]),
        JmpIfBitSet(TEMP_7044_3, ["EVENT_1707_action_queue_async_64"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[
                ASWalkSoutheastSteps(9),
                ASWalk1StepSouth(),
                ASWalk1StepSouthwest(),
            ],
            identifier="EVENT_1707_action_queue_async_64"),
        Jmp(["EVENT_1707_action_queue_async_70"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[ASWalkSouthwestSteps(8)],
            identifier="EVENT_1707_action_queue_async_66"),
        Jmp(["EVENT_1707_action_queue_async_70"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[
                ASShiftSouthSteps(8),
                ASWalk1StepSoutheast(),
                ASWalk1StepSouth(),
                ASWalk1StepSouthwest(),
            ],
            identifier="EVENT_1707_action_queue_async_68"),
        Jmp(["EVENT_1707_action_queue_async_70"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[ASBounceToXYWithHeight(x=11, y=115, height=0)],
            identifier="EVENT_1707_action_queue_async_70"),
        SetVarToConst(TEMP_70A9, 25),
        ClearBit(TEMP_7044_0),
        ClearBit(TEMP_7044_1),
        ClearBit(TEMP_7044_3),
        SetBit(TEMP_7044_2),
        Jmp(["EVENT_1707_action_queue_sync_103"]),
        SetVarToConst(PRIMARY_TEMP_7000, 20480, identifier="EVENT_1707_set_77"),
        JmpIfBitSet(TEMP_7044_3, ["EVENT_1707_clear_bit_13"]),
        JmpIfBitSet(TEMP_7044_0, ["EVENT_1707_action_queue_async_86"]),
        JmpIfBitSet(TEMP_7044_1, ["EVENT_1707_action_queue_async_84"]),
        JmpIfBitSet(TEMP_7044_2, ["EVENT_1707_action_queue_async_82"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[
                ASWalk1StepNortheast(),
                ASWalk1StepNorth(),
                ASWalkNorthwestSteps(9),
            ],
            identifier="EVENT_1707_action_queue_async_82"),
        Jmp(["EVENT_1707_action_queue_async_88"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[
                ASWalkSouthwestSteps(3),
                ASWalkWestSteps(3),
                ASWalkNorthwestSteps(7),
            ],
            identifier="EVENT_1707_action_queue_async_84"),
        Jmp(["EVENT_1707_action_queue_async_88"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[ASWalkSouthwestSteps(8)],
            identifier="EVENT_1707_action_queue_async_86"),
        Jmp(["EVENT_1707_action_queue_async_88"]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[ASBounceToXYWithHeight(x=7, y=103, height=0)],
            identifier="EVENT_1707_action_queue_async_88"),
        SetVarToConst(TEMP_70A9, 25),
        ClearBit(TEMP_7044_0),
        ClearBit(TEMP_7044_1),
        ClearBit(TEMP_7044_2),
        SetBit(TEMP_7044_3),
        ActionQueueSync(
            target=MEM_70A9,
            subscript=[
                ASDb(bytearray(b"\xfd\x12")),
                ASTransferToXYZF(x=10, y=90, z=0, direction=EAST),
            ],
            identifier="EVENT_1707_action_queue_sync_94"),
        Inc(TEMP_70A9),
        JmpIfVarEqualsConst(TEMP_70A9, 28, ["EVENT_1707_clear_bit_107"]),
        ActionQueueSync(
            target=MEM_70A9,
            subscript=[
                ASDb(bytearray(b"\xfd\x12")),
                ASTransferToXYZF(x=14, y=102, z=0, direction=EAST),
            ],
            identifier="EVENT_1707_action_queue_sync_97"),
        Inc(TEMP_70A9),
        JmpIfVarEqualsConst(TEMP_70A9, 28, ["EVENT_1707_clear_bit_107"]),
        ActionQueueSync(
            target=MEM_70A9,
            subscript=[
                ASDb(bytearray(b"\xfd\x12")),
                ASTransferToXYZF(x=10, y=110, z=0, direction=EAST),
            ],
            identifier="EVENT_1707_action_queue_sync_100"),
        Inc(TEMP_70A9),
        JmpIfVarEqualsConst(TEMP_70A9, 28, ["EVENT_1707_clear_bit_107"]),
        ActionQueueSync(
            target=MEM_70A9,
            subscript=[
                ASDb(bytearray(b"\xfd\x12")),
                ASTransferToXYZF(x=6, y=98, z=0, direction=EAST),
            ],
            identifier="EVENT_1707_action_queue_sync_103"),
        Inc(TEMP_70A9),
        JmpIfVarEqualsConst(TEMP_70A9, 28, ["EVENT_1707_clear_bit_107"]),
        Jmp(["EVENT_1707_action_queue_sync_94"]),
        ClearBit(TEMP_7043_7, identifier="EVENT_1707_clear_bit_107"),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[
                ASFaceNortheast(),
                ASJmpIfBitClear(TEMP_7044_6, ["EVENT_1707_set_action_script_sync_109"]),
                ASSetAllSpeeds(FASTEST),
                ASSetBit(TEMP_7043_7),
                ASWalkSouthwestSteps(3),
                ASWalk1StepWest(),
                ASWalk1StepNorthwest(),
                ASWalk1StepNorth(),
                ASFaceNorthwest(),
            ]),
        SetSyncActionScript(
            NPC_5,
            A0472_BANDITS_WAY_5_GOOMBA,
            identifier="EVENT_1707_set_action_script_sync_109"),
        SetSyncActionScript(NPC_6, A0472_BANDITS_WAY_5_GOOMBA),
        SetSyncActionScript(NPC_7, A0472_BANDITS_WAY_5_GOOMBA),
        SetSyncActionScript(NPC_8, A0469_BANDITS_WAY_5_LOADER_BOSS),
        Return(),
    ]
)
