# pylint: disable=C0301

"""E0009_SET_70A7_TO_RANDOM_TIER_1_EQUIP"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        SetVarToRandom(PRIMARY_TEMP_7000, 46),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 0, ["EVENT_9_set_0"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 1, ["EVENT_9_set_1"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 2, ["EVENT_9_set_2"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 3, ["EVENT_9_set_3"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 4, ["EVENT_9_set_4"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 5, ["EVENT_9_set_5"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 6, ["EVENT_9_set_6"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 7, ["EVENT_9_set_7"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 8, ["EVENT_9_set_8"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 9, ["EVENT_9_set_9"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 10, ["EVENT_9_set_10"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 11, ["EVENT_9_set_11"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 12, ["EVENT_9_set_12"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 13, ["EVENT_9_set_13"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 14, ["EVENT_9_set_14"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 15, ["EVENT_9_set_15"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 16, ["EVENT_9_set_16"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 17, ["EVENT_9_set_17"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 18, ["EVENT_9_set_18"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 19, ["EVENT_9_set_19"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 20, ["EVENT_9_set_20"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 21, ["EVENT_9_set_21"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 22, ["EVENT_9_set_22"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 23, ["EVENT_9_set_23"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 24, ["EVENT_9_set_24"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 25, ["EVENT_9_set_25"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 26, ["EVENT_9_set_26"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 27, ["EVENT_9_set_27"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 28, ["EVENT_9_set_28"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 29, ["EVENT_9_set_29"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 30, ["EVENT_9_set_30"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 31, ["EVENT_9_set_31"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 32, ["EVENT_9_set_32"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 33, ["EVENT_9_set_33"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 34, ["EVENT_9_set_34"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 35, ["EVENT_9_set_35"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 36, ["EVENT_9_set_36"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 37, ["EVENT_9_set_37"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 38, ["EVENT_9_set_38"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 39, ["EVENT_9_set_39"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 40, ["EVENT_9_set_40"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 41, ["EVENT_9_set_41"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 42, ["EVENT_9_set_42"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 43, ["EVENT_9_set_43"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 44, ["EVENT_9_set_44"]),
        SetVarToConst(ITEM_ID, Pants),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, FireCape, identifier="EVENT_9_set_0"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, NauticaDress, identifier="EVENT_9_set_1"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, SailorPants, identifier="EVENT_9_set_2"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, SailorShirt, identifier="EVENT_9_set_3"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, WorkPants, identifier="EVENT_9_set_4"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, SpikedLink, identifier="EVENT_9_set_5"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, JumpShoes, identifier="EVENT_9_set_6"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, Cymbals, identifier="EVENT_9_set_7"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, PunchGlove, identifier="EVENT_9_set_8"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, FuzzyCape, identifier="EVENT_9_set_9"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, HappyPants, identifier="EVENT_9_set_10"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, HappyShirt, identifier="EVENT_9_set_11"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, HealShell, identifier="EVENT_9_set_12"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, PolkaDress, identifier="EVENT_9_set_13"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, HandGun, identifier="EVENT_9_set_14"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, HurlyGloves, identifier="EVENT_9_set_15"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, BtubRing, identifier="EVENT_9_set_16"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, RareScarf, identifier="EVENT_9_set_17"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, ScroogeRing, identifier="EVENT_9_set_18"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, MegaShirt, identifier="EVENT_9_set_19"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, TrueformPin, identifier="EVENT_9_set_20"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, FireShell, identifier="EVENT_9_set_21"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, MegaPants, identifier="EVENT_9_set_22"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, SailorCape, identifier="EVENT_9_set_23"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, FroggieStick, identifier="EVENT_9_set_24"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, NokNokShell, identifier="EVENT_9_set_25"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, Chomp, identifier="EVENT_9_set_26"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, CoinTrick, identifier="EVENT_9_set_27"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, FearlessPin, identifier="EVENT_9_set_28"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, Feather, identifier="EVENT_9_set_29"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, FingerShot, identifier="EVENT_9_set_30"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, ThickShirt, identifier="EVENT_9_set_31"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, ChompShell, identifier="EVENT_9_set_32"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, CourageShell, identifier="EVENT_9_set_33"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, HappyCape, identifier="EVENT_9_set_34"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, ThickPants, identifier="EVENT_9_set_35"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, WakeUpPin, identifier="EVENT_9_set_36"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, SignalRing, identifier="EVENT_9_set_37"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, ZoomShoes, identifier="EVENT_9_set_38"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, AntidotePin, identifier="EVENT_9_set_39"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, Hammer, identifier="EVENT_9_set_40"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, Shirt, identifier="EVENT_9_set_41"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, LuckyHammer, identifier="EVENT_9_set_42"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, HappyShell, identifier="EVENT_9_set_43"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
        SetVarToConst(ITEM_ID, MegaCape, identifier="EVENT_9_set_44"),
        JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
    ]
)
