# E3640_STATUE_GAME

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        JmpIfBitSet(UNKNOWN_TOWER_BOSS_2_FIGHT_7092_5, ["EVENT_3640_run_dialog__"]),
        SetBit(UNKNOWN_TOWER_BOSS_2_FIGHT_7092_5),
        FadeOutToBlack(sync=True, duration=60),
        PauseScriptUntilEffectDone(),
        ClearBit(TEMP_704C_0),
        EnterArea(
            room_id=R110_NIMBUS_CASTLE_AREA_18_DODOS_STATUEPOLISHING_ROOM,
            face_direction=NORTHEAST,
            x=6,
            y=68,
            z=1,
        ),
        PaletteSet(palette_set=111, row=1),
        SetSyncActionScript(MARIO, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        ActionQueueAsync(
            target=SCREEN_FOCUS,
            subscript=[
                ASSetWalkingSpeed(VERY_FAST),
                ASWalkToXYCoords(x=1, y=49),
                ASShiftNorthwestSteps(1),
                ASShiftEastPixels(13),
            ],
        ),
        RunEventAsSubroutine(
            E0819_NIMBUS_CASTLE_STATUE_POLISHING_ROOM_SHUFFLED_NPC_ANIMATION_LOADER
        ),
        FadeInFromBlack(sync=False),
        FadeOutMusicToVolume(duration=0, volume=0),
        PlayMusicAtDefaultVolume(M01_DODOS_COMING),
        StopMusicFDA2(),
        Pause(30),
        EnableControlsUntilReturn([]),
        Pause(1),
        Pause(10),
        PlaySound(sound=SO016_OPEN_DOOR, channel=6),
        Pause(60),
        EnableControlsUntilReturn([B]),
        Pause(1),
        PlayMusicAtDefaultVolume(M01_DODOS_COMING),
        Pause(143),
        Pause(235),
        Pause(118),
        RunEventAsSubroutine(
            E0939_STATUE_SUBROUTINE_1, identifier="EVENT_3640_action_queue_async_39"
        ),
        JmpToSubroutine(["EVENT_3640_action_queue_async_288"]),
        Pause(13),
        JmpToSubroutine(["EVENT_3640_action_queue_async_290"]),
        Pause(13),
        JmpToSubroutine(["EVENT_3640_action_queue_async_288"]),
        JmpToSubroutine(["EVENT_3640_action_queue_async_292"]),
        JmpToSubroutine(["EVENT_3640_set_temp_action_script_async_294"]),
        Pause(12),
        JmpToSubroutine(["EVENT_3640_action_queue_async_288"]),
        Pause(13),
        JmpToSubroutine(["EVENT_3640_action_queue_async_290"]),
        Pause(12),
        JmpToSubroutine(["EVENT_3640_action_queue_async_288"]),
        JmpToSubroutine(["EVENT_3640_action_queue_async_292"]),
        JmpToSubroutine(["EVENT_3640_set_temp_action_script_async_305"]),
        Pause(12),
        JmpToSubroutine(["EVENT_3640_action_queue_async_288"]),
        Pause(13),
        JmpToSubroutine(["EVENT_3640_action_queue_async_290"]),
        Pause(12),
        JmpToSubroutine(["EVENT_3640_action_queue_async_288"]),
        RunEventAsSubroutine(E0938_PECK_SUBROUTINE_RIGHT_STATUE),
        SetVarToConst(PRIMARY_TEMP_7000, 0),
        ClearBit(UNKNOWN_708A_7),
        StartLoopNTimes(18),
        Pause(1),
        Set7000ToTappedButton(),
        JmpIf7000AllBitsClear(destinations=["EVENT_3640_end_loop_69"]),
        SetBit(UNKNOWN_708A_7),
        EndLoop(identifier="EVENT_3640_end_loop_69"),
        JmpIfBitSet(UNKNOWN_708A_7, ["EVENT_3640_stop_music_227"]),
        RunEventAsSubroutine(E0937_PECK_SUBROUTINE_MIDDLE_STATUE),
        ClearBit(UNKNOWN_708A_7),
        SetVarToConst(PRIMARY_TEMP_7000, 0),
        StartLoopNTimes(22),
        Pause(1),
        Set7000ToTappedButton(),
        JmpIf7000AllBitsClear(destinations=["EVENT_3640_end_loop_79"]),
        SetBit(UNKNOWN_708A_7),
        EndLoop(identifier="EVENT_3640_end_loop_79"),
        JmpIfBitClear(UNKNOWN_708A_7, ["EVENT_3640_stop_music_316"]),
        SetVarToConst(PRIMARY_TEMP_7000, 0),
        Pause(17),
        JmpToSubroutine(["EVENT_3640_action_queue_async_288"]),
        Pause(13),
        JmpToSubroutine(["EVENT_3640_action_queue_async_290"]),
        Pause(12),
        JmpToSubroutine(["EVENT_3640_action_queue_async_288"]),
        Pause(74),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASSequencePlaybackOn(),
                ASSetWalkingSpeed(FAST),
                ASSetSequenceSpeed(FASTER),
                ASFixedFCoordOn(),
                ASSetSpriteSequence(index=0, looping=False, mirror_sprite=True),
                ASShiftNorthwestSteps(3),
                ASPause(25),
                ASFaceSouthwest(),
                ASSetWalkingSpeed(FASTER),
                ASSetSequenceSpeed(NORMAL),
                ASSetSpriteSequence(index=0, is_mold=True, looping=True),
                ASPause(36),
                ASSequenceLoopingOn(),
                ASStartLoopNTimes(8),
                ASSetSpriteSequence(index=5, looping=False),
                ASPause(2),
                ASSetSpriteSequence(index=0, looping=False),
                ASPause(2),
                ASEndLoop(),
                ASSetSpriteSequence(index=5, is_sequence=True, looping=False),
                ASPause(50),
                ASSetSpriteSequence(index=0, is_mold=True, looping=True),
                ASSequenceLoopingOff(),
            ],
        ),
        Pause(5),
        SetVarToConst(SECONDARY_TEMP_7024, 0),
        SetVarToConst(PRIMARY_TEMP_7000, 0, identifier="EVENT_3640_set_short_92"),
        ClearBit(UNKNOWN_708A_7),
        StartLoopNTimes(17),
        Pause(1),
        Set7000ToTappedButton(),
        JmpIf7000AllBitsClear(destinations=["EVENT_3640_end_loop_99"]),
        SetBit(UNKNOWN_708A_7),
        EndLoop(identifier="EVENT_3640_end_loop_99"),
        JmpIfBitSet(UNKNOWN_708A_7, ["EVENT_3640_stop_music_227"]),
        Inc(SECONDARY_TEMP_7024),
        JmpIfVarNotEqualsConst(SECONDARY_TEMP_7024, 7, ["EVENT_3640_set_short_92"]),
        RunEventAsSubroutine(E0938_PECK_SUBROUTINE_RIGHT_STATUE),
        Pause(18),
        JmpToSubroutine(["EVENT_3640_action_queue_async_288"]),
        Pause(13),
        JmpToSubroutine(["EVENT_3640_action_queue_async_290"]),
        Pause(12),
        JmpToSubroutine(["EVENT_3640_action_queue_async_288"]),
        JmpToSubroutine(["EVENT_3640_action_queue_async_292"]),
        JmpToSubroutine(["EVENT_3640_set_temp_action_script_async_337"]),
        Pause(12),
        JmpToSubroutine(["EVENT_3640_action_queue_async_348"]),
        Pause(13),
        JmpToSubroutine(["EVENT_3640_action_queue_async_350"]),
        Pause(12),
        JmpToSubroutine(["EVENT_3640_action_queue_async_348"]),
        RunEventAsSubroutine(E0938_PECK_SUBROUTINE_RIGHT_STATUE),
        SetVarToConst(PRIMARY_TEMP_7000, 0),
        ClearBit(UNKNOWN_708A_7),
        StartLoopNTimes(18),
        Pause(1),
        Set7000ToTappedButton(),
        JmpIf7000AllBitsClear(destinations=["EVENT_3640_end_loop_126"]),
        SetBit(UNKNOWN_708A_7),
        EndLoop(identifier="EVENT_3640_end_loop_126"),
        JmpIfBitSet(UNKNOWN_708A_7, ["EVENT_3640_stop_music_227"]),
        RunEventAsSubroutine(E0937_PECK_SUBROUTINE_MIDDLE_STATUE),
        ClearBit(UNKNOWN_708A_7),
        SetVarToConst(PRIMARY_TEMP_7000, 0),
        StartLoopNTimes(22),
        Pause(1),
        Set7000ToTappedButton(),
        JmpIf7000AllBitsClear(destinations=["EVENT_3640_end_loop_136"]),
        SetBit(UNKNOWN_708A_7),
        EndLoop(identifier="EVENT_3640_end_loop_136"),
        JmpIfBitClear(UNKNOWN_708A_7, ["EVENT_3640_stop_music_316"]),
        SetVarToConst(PRIMARY_TEMP_7000, 0),
        Pause(18),
        JmpToSubroutine(["EVENT_3640_action_queue_async_350"]),
        Pause(13),
        JmpToSubroutine(["EVENT_3640_action_queue_async_348"]),
        Pause(13),
        JmpToSubroutine(["EVENT_3640_action_queue_async_350"]),
        JmpToSubroutine(["EVENT_3640_action_queue_async_292"]),
        JmpToSubroutine(["EVENT_3640_set_temp_action_script_async_305"]),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASSetSpriteSequence(
                    index=0, is_mold=True, is_sequence=True, looping=True
                ),
                ASPause(23),
                ASSetSpriteSequence(
                    index=0,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
                ASPause(45),
                ASSetSpriteSequence(
                    index=0, is_mold=True, is_sequence=True, looping=True
                ),
                ASPause(45),
                ASSetWalkingSpeed(FAST),
                ASSetSequenceSpeed(VERY_FAST),
                ASSetSpriteSequence(index=0, looping=True, mirror_sprite=True),
                ASShiftSoutheastSteps(3),
                ASReturn(),
            ],
        ),
        RunEventAsSubroutine(E0938_PECK_SUBROUTINE_RIGHT_STATUE),
        SetVarToConst(PRIMARY_TEMP_7000, 0),
        ClearBit(UNKNOWN_708A_7),
        StartLoopNTimes(3),
        Pause(1),
        Set7000ToTappedButton(),
        JmpIf7000AllBitsClear(destinations=["EVENT_3640_end_loop_156"]),
        SetBit(UNKNOWN_708A_7),
        EndLoop(identifier="EVENT_3640_end_loop_156"),
        JmpIfBitSet(UNKNOWN_708A_7, ["EVENT_3640_stop_music_227"]),
        RunEventAsSubroutine(E0937_PECK_SUBROUTINE_MIDDLE_STATUE),
        ClearBit(UNKNOWN_708A_7),
        SetVarToConst(PRIMARY_TEMP_7000, 0),
        StartLoopNTimes(22),
        Pause(1),
        Set7000ToTappedButton(),
        JmpIf7000AllBitsClear(destinations=["EVENT_3640_end_loop_166"]),
        SetBit(UNKNOWN_708A_7),
        EndLoop(identifier="EVENT_3640_end_loop_166"),
        JmpIfBitClear(UNKNOWN_708A_7, ["EVENT_3640_stop_music_316"]),
        SetVarToConst(PRIMARY_TEMP_7000, 0),
        Pause(17),
        JmpToSubroutine(["EVENT_3640_action_queue_async_288"]),
        Pause(13),
        JmpToSubroutine(["EVENT_3640_action_queue_async_290"]),
        Pause(13),
        JmpToSubroutine(["EVENT_3640_action_queue_async_288"]),
        JmpToSubroutine(["EVENT_3640_action_queue_async_292"]),
        JmpToSubroutine(["EVENT_3640_set_temp_action_script_async_337"]),
        Pause(12),
        JmpToSubroutine(["EVENT_3640_action_queue_async_348"]),
        Pause(13),
        JmpToSubroutine(["EVENT_3640_action_queue_async_350"]),
        Pause(12),
        JmpToSubroutine(["EVENT_3640_action_queue_async_348"]),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASSetSpriteSequence(index=0, is_mold=True, looping=True),
                ASSequencePlaybackOn(),
                ASFaceSouthwest(),
                ASPause(16),
                ASSequenceLoopingOn(),
                ASSetSequenceSpeed(NORMAL),
                ASSetSpriteSequence(index=3, is_sequence=True, looping=False),
                ASPause(9),
                ASSequencePlaybackOff(),
                ASPause(8),
                ASSequenceLoopingOff(),
                ASFaceNorthwest(),
                ASSetSpriteSequence(
                    index=4,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
                ASPause(45),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(NORMAL),
                ASSequencePlaybackOn(),
                ASPause(20),
                ASResetProperties(),
                ASFaceNorthwest(),
                ASShiftNorthwestSteps(9),
                ASSetWalkingSpeed(VERY_FAST),
                ASSetSequenceSpeed(VERY_FAST),
                ASShiftNorthwestSteps(3),
                ASVisibilityOff(),
                ASSequenceLoopingOff(),
                ASPause(9),
                ASClearSolidityBits(cant_pass_walls=True),
                ASPause(38),
                ASShiftToXYCoords(x=127, y=66),
                ASVisibilityOn(),
                ASSetSpriteSequence(index=0, looping=True, mirror_sprite=True),
                ASShiftSoutheastSteps(14),
                ASPause(20),
                ASShiftToXYCoords(x=11, y=75),
                ASShiftSouthwestPixels(5),
                ASResetProperties(),
                ASFaceNorthwest(),
                ASVisibilityOn(),
                ASShiftNorthwestSteps(9),
                ASFaceSouthwest(),
                ASSetSpriteSequence(index=0, looping=True),
                ASSequenceLoopingOff(),
            ],
        ),
        Pause(25),
        RunEventAsSubroutine(E0937_PECK_SUBROUTINE_MIDDLE_STATUE),
        ClearBit(UNKNOWN_708A_7),
        SetVarToConst(PRIMARY_TEMP_7000, 0),
        StartLoopNTimes(22),
        Pause(1),
        Set7000ToTappedButton(),
        JmpIf7000AllBitsClear(destinations=["EVENT_3640_end_loop_193"]),
        SetBit(UNKNOWN_708A_7),
        EndLoop(identifier="EVENT_3640_end_loop_193"),
        JmpIfBitClear(UNKNOWN_708A_7, ["EVENT_3640_stop_music_316"]),
        SetVarToConst(PRIMARY_TEMP_7000, 0),
        Pause(30),
        EnableControlsUntilReturn([]),
        ClearBit(TEMP_7043_0),
        ClearBit(TEMP_7043_1),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASSetSequenceSpeed(SLOW),
                ASSetSpriteSequence(index=6, is_sequence=True, looping=False),
                ASPause(90),
                ASSequenceLoopingOff(),
            ],
        ),
        Pause(20),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASFixedFCoordOff(),
                ASResetProperties(),
                ASFaceNorthwest(),
                ASSetAllSpeeds(FAST),
                ASShiftNorthwestSteps(11),
                ASVisibilityOff(),
                ASSequenceLoopingOff(),
                ASStopSound(),
            ],
        ),
        Pause(60),
        PlaySound(sound=SO000_SILENCE, channel=6),
        Pause(30),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASJumpToHeight(96),
                ASShiftNortheastSteps(2),
                ASFaceSouth(),
                ASSetSpriteSequence(
                    index=10, sprite_offset=2, is_sequence=True, looping=False
                ),
                ASPause(60),
            ],
        ),
        SetAsyncActionScript(MARIO, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        RemoveObjectFromSpecificLevel(
            NPC_1, R112_NIMBUS_CASTLE_AREA_17_RIGHT_OF_4WAY_PATH_SAVE_POINT
        ),
        UnfreezeCamera(),
        SetVarToConst(PRIMARY_TEMP_7000, 520),
        RunEventAsSubroutine(E0178_NPC_QUEST_1_CONTAINER),
        JmpIfBitSet(ALTERNATE_STAR_PIECE_WIN_CONDITION, ["EVENT_3640_set_bit_203"]),
        JmpIfBitSet(STATUE_KEEPER_STAR_PIECE, ["EVENT_3640_jmp_sub"]),
        SetBit(STATUE_KEEPER_STAR_PIECE),
        SetVarToConst(PRIMARY_TEMP_7000, 520),
        JmpToEvent(E0167_BOSS_GRANT_STAR_PIECE),
        SetBit(STATUE_KEEPER_FIGHT_PRESENT, identifier="EVENT_3640_set_bit_203"),
        JmpToSubroutine(
            ["EVENT_3400_determine_nimbus_music"], identifier="EVENT_3640_jmp_sub"
        ),
        Return(),
        StopMusic(identifier="EVENT_3640_stop_music_227"),
        RunEventAsSubroutine(E0940_STATUE_SUBROUTINE_2),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASSequenceLoopingOn(),
                ASSequencePlaybackOn(),
                ASSetAllSpeeds(VERY_FAST),
                ASResetProperties(),
                ASFaceNorthwest(),
                ASShiftNorthwestSteps(9),
                ASShiftNorthwestSteps(2),
                ASVisibilityOff(),
                ASSequenceLoopingOff(),
                ASPause(40),
            ],
        ),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASPause(60),
                ASSetSpriteSequence(
                    index=10,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
            ],
        ),
        Pause(60),
        PlaySound(sound=SO016_OPEN_DOOR, channel=6),
        Pause(60),
        JmpIfBitSet(TEMP_7044_2, ["EVENT_3640_action_queue_async_242"]),
        ActionQueueAsync(target=MARIO, subscript=[ASResetProperties()]),
        ClearBit(TEMP_7043_0),
        ClearBit(TEMP_7043_1),
        SetBit(TEMP_7044_2),
        Pause(30),
        Jmp(["EVENT_3640_pause_277"]),
        Return(),
        ActionQueueAsync(
            target=MARIO,
            subscript=[ASResetProperties()],
            identifier="EVENT_3640_action_queue_async_242",
        ),
        EnableControlsUntilReturn([]),
        Pause(60),
        FadeOutMusicToVolume(duration=5, volume=0),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASShiftToXYCoords(x=2, y=56),
                ASShiftSouthwestPixels(5),
                ASShiftSoutheastPixels(16),
                ASSetSpriteSequence(
                    index=0, is_sequence=True, looping=True, mirror_sprite=True
                ),
                ASSetSequenceSpeed(VERY_FAST),
                ASSetWalkingSpeed(FAST),
                ASVisibilityOn(),
                ASShiftSoutheastSteps(9),
                ASSetSpriteSequence(
                    index=0, is_mold=True, is_sequence=True, looping=True
                ),
                ASPause(30),
                ASSetSequenceSpeed(SLOW),
                ASSetSpriteSequence(index=6, is_sequence=True, looping=True),
                ASPause(120),
            ],
        ),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASSetSpriteSequence(
                    index=9, is_mold=True, is_sequence=True, looping=True
                ),
                ASPause(40),
                ASSetSpriteSequence(
                    index=10, is_mold=True, is_sequence=True, looping=True
                ),
                ASPause(40),
                ASSetSpriteSequence(
                    index=11, is_mold=True, is_sequence=True, looping=True
                ),
                ASPause(40),
                ASSetSpriteSequence(
                    index=12, is_mold=True, is_sequence=True, looping=True
                ),
                ASPause(40),
            ],
        ),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASPause(40),
                ASPause(40),
                ASPause(30),
                ASSetSequenceSpeed(VERY_FAST),
                ASSetSpriteSequence(
                    index=9, is_sequence=True, looping=True, mirror_sprite=True
                ),
                ASPause(50),
            ],
        ),
        SetVarToConst(PRIMARY_TEMP_7000, 520),
        RunEventAsSubroutine(E0353_BOSS_BATTLE),
        JmpIfBitClear(GAME_OVER, ["EVENT_3640_unfreeze_camera_252"]),
        ResetAndChooseGame(),
        UnfreezeCamera(identifier="EVENT_3640_unfreeze_camera_252"),
        PaletteSet(palette_set=84, row=1),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASSetSequenceSpeed(FAST),
                ASSetSpriteSequence(index=6, is_sequence=True, looping=True),
            ],
        ),
        ActionQueueAsync(
            target=MARIO, subscript=[ASResetProperties(), ASFaceNortheast()]
        ),
        FadeInFromBlack(sync=False),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASPause(60),
                ASResetProperties(),
                ASFaceNorthwest(),
                ASSetAllSpeeds(VERY_FAST),
                ASShiftNorthwestSteps(11),
                ASVisibilityOff(),
            ],
        ),
        Pause(35),
        PlaySound(sound=SO016_OPEN_DOOR, channel=6),
        Pause(10),
        RemoveObjectFromSpecificLevel(
            NPC_1, R112_NIMBUS_CASTLE_AREA_17_RIGHT_OF_4WAY_PATH_SAVE_POINT
        ),
        SetAsyncActionScript(MARIO, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        EnableControlsUntilReturn([LEFT, RIGHT, DOWN, UP, X, A, Y, B]),
        RestoreAllHP(),
        RestoreAllFP(),
        JmpIfBitSet(
            NIMBUS_LAND_LIBERATED, ["EVENT_3640_play_music_default_volume_273"]
        ),
        PlayMusicAtDefaultVolume(M61_VALENTINA),
        JmpIfBitSet(STATUE_KEEPER_STAR_PIECE, ["EVENT_3640_ret_272"]),
        SetBit(STATUE_KEEPER_STAR_PIECE),
        SetVarToConst(PRIMARY_TEMP_7000, 520),
        JmpToEvent(E0167_BOSS_GRANT_STAR_PIECE),
        Return(identifier="EVENT_3640_ret_272"),
        PlayMusicAtDefaultVolume(
            M50_NIMBUS_LAND, identifier="EVENT_3640_play_music_default_volume_273"
        ),
        JmpIfBitSet(STATUE_KEEPER_STAR_PIECE, ["EVENT_3640_ret_276"]),
        SetBit(STATUE_KEEPER_STAR_PIECE),
        SetVarToConst(PRIMARY_TEMP_7000, 520),
        JmpToEvent(E0167_BOSS_GRANT_STAR_PIECE),
        Return(identifier="EVENT_3640_ret_276"),
        Pause(10, identifier="EVENT_3640_pause_277"),
        PlaySound(sound=SO016_OPEN_DOOR, channel=6),
        Pause(60),
        EnableControlsUntilReturn([B]),
        Pause(1),
        PlayMusicAtDefaultVolume(M01_DODOS_COMING),
        Pause(143),
        Pause(235),
        Pause(131),
        Jmp(["EVENT_3640_action_queue_async_39"]),
        Return(),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASResetProperties(),
                ASFaceSoutheast(),
                ASSequencePlaybackOff(),
                ASSetAllSpeeds(NORMAL),
                ASSetSequenceSpeed(SLOW),
                ASSetSpriteSequence(
                    index=0, is_sequence=True, looping=False, mirror_sprite=True
                ),
                ASPause(12),
                ASSetSpriteSequence(
                    index=8, is_sequence=True, looping=False, mirror_sprite=True
                ),
                ASWalk1StepSoutheast(),
            ],
            identifier="EVENT_3640_action_queue_async_288",
        ),
        Return(),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASResetProperties(),
                ASFaceSoutheast(),
                ASSequencePlaybackOff(),
                ASSetAllSpeeds(NORMAL),
                ASSetSequenceSpeed(SLOW),
                ASSetSpriteSequence(
                    index=0, is_sequence=True, looping=False, mirror_sprite=True
                ),
                ASPause(12),
                ASSetSpriteSequence(
                    index=9, is_sequence=True, looping=False, mirror_sprite=True
                ),
                ASWalk1StepSoutheast(),
            ],
            identifier="EVENT_3640_action_queue_async_290",
        ),
        Return(),
        JmpToEvent(
            E0936_PECK_SUBROUTINE_LEFT_STATUE,
            identifier="EVENT_3640_action_queue_async_292",
        ),
        Return(),
        JmpToEvent(
            E2115_STATUE_1_SHAKE,
            identifier="EVENT_3640_set_temp_action_script_async_294",
        ),
        Return(),
        JmpToEvent(
            E2116_STATUE_2_SHAKE,
            identifier="EVENT_3640_set_temp_action_script_async_305",
        ),
        Return(),
        StopMusic(identifier="EVENT_3640_stop_music_316"),
        EnableControlsUntilReturn([]),
        FreezeCamera(),
        ActionQueueSync(
            target=SCREEN_FOCUS,
            subscript=[
                ASPause(15),
                ASPlaySound(sound=SO022_CLOSE_DOOR, channel=6),
                ASShiftNortheastPixels(4),
                ASShiftSouthwestPixels(4),
                ASShiftNortheastPixels(2),
                ASShiftSouthwestPixels(2),
            ],
        ),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASPause(50),
                ASSetSpriteSequence(
                    index=0, is_mold=True, is_sequence=True, looping=True
                ),
            ],
        ),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASFixedFCoordOn(),
                ASSequencePlaybackOn(),
                ASSequenceLoopingOn(),
                ASSetSequenceSpeed(NORMAL),
                ASSetSpriteSequence(
                    index=7, sprite_offset=2, is_sequence=True, looping=True
                ),
                ASPause(5),
                ASSequencePlaybackOff(),
                ASSetWalkingSpeed(FAST),
                ASSetSpriteSequence(
                    index=3, sprite_offset=2, is_sequence=True, looping=False
                ),
                ASShiftSouthwestSteps(1),
                ASPause(25),
                ASSequencePlaybackOn(),
                ASSetSequenceSpeed(VERY_FAST),
                ASSetSpriteSequence(
                    index=9, is_sequence=True, looping=True, mirror_sprite=True
                ),
                ASPause(20),
                ASResetProperties(),
                ASSequenceLoopingOff(),
                ASSetAllSpeeds(NORMAL),
                ASSetWalkingSpeed(FAST),
                ASJumpToHeight(108),
                ASShiftNortheastSteps(1),
            ],
        ),
        Pause(40),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASSetSequenceSpeed(NORMAL),
                ASSetSpriteSequence(index=7, is_sequence=True, looping=True),
                ASPause(60),
            ],
        ),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASSetAllSpeeds(VERY_FAST),
                ASResetProperties(),
                ASFaceNorthwest(),
                ASShiftNorthwestSteps(11),
                ASVisibilityOff(),
            ],
        ),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASPause(60),
                ASSetSpriteSequence(
                    index=10,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
            ],
        ),
        Pause(60),
        PlaySound(sound=SO016_OPEN_DOOR, channel=6),
        Pause(60),
        JmpIfBitSet(TEMP_7044_2, ["EVENT_3640_action_queue_async_242"]),
        ActionQueueAsync(target=MARIO, subscript=[ASResetProperties()]),
        ClearBit(TEMP_7043_0),
        ClearBit(TEMP_7043_1),
        SetBit(TEMP_7044_2),
        Pause(30),
        Jmp(["EVENT_3640_pause_277"]),
        Return(),
        JmpToEvent(
            E2117_STATUE_4_SHAKE,
            identifier="EVENT_3640_set_temp_action_script_async_337",
        ),
        Return(),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASSequencePlaybackOff(),
                ASSetAllSpeeds(NORMAL),
                ASSetSequenceSpeed(SLOW),
                ASResetProperties(),
                ASFaceNorthwest(),
                ASPause(12),
                ASSetSpriteSequence(
                    index=10, is_sequence=True, looping=False, mirror_sprite=True
                ),
                ASWalk1StepNorthwest(),
            ],
            identifier="EVENT_3640_action_queue_async_348",
        ),
        Return(),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASSequencePlaybackOff(),
                ASSetAllSpeeds(NORMAL),
                ASSetSequenceSpeed(SLOW),
                ASResetProperties(),
                ASFaceNorthwest(),
                ASPause(12),
                ASSetSpriteSequence(
                    index=11, is_sequence=True, looping=False, mirror_sprite=True
                ),
                ASWalk1StepNorthwest(),
            ],
            identifier="EVENT_3640_action_queue_async_350",
        ),
        Return(),
        RunDialog(
            dialog_id=DI3787_DODO_MINIGAME_HINT,
            above_object=NPC_0,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_3640_run_dialog__",
        ),
        Return(),
    ]
)
