# pylint: disable=C0301

"""E3153_OLD_CHEST_GRANTER"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        JmpIfVarEqualsConst(ITEM_ID, 192, ["EVENT_3153_set_197"]),
        JmpIfVarEqualsConst(ITEM_ID, 193, ["EVENT_3153_set_200"]),
        JmpIfVarEqualsConst(ITEM_ID, 194, ["EVENT_3153_set_203"]),
        JmpIfVarEqualsConst(ITEM_ID, 195, ["EVENT_3153_set_206"]),
        JmpIfVarEqualsConst(ITEM_ID, 196, ["EVENT_3153_set_209"]),
        JmpIfVarEqualsConst(ITEM_ID, 197, ["EVENT_3153_set_212"]),
        JmpIfVarEqualsConst(ITEM_ID, 198, ["EVENT_3153_set_215"]),
        JmpIfVarEqualsConst(ITEM_ID, 199, ["EVENT_3153_set_217"]),
        JmpIfVarEqualsConst(ITEM_ID, 200, ["EVENT_3153_set_219"]),
        JmpIfVarEqualsConst(ITEM_ID, 201, ["EVENT_3153_set_221"]),
        JmpIfVarEqualsConst(ITEM_ID, 202, ["EVENT_3153_set_223"]),
        JmpIfVarEqualsConst(ITEM_ID, 203, ["EVENT_3153_set_225"]),
        JmpIfVarEqualsConst(ITEM_ID, 204, ["EVENT_3153_set_227"]),
        JmpIfVarEqualsConst(ITEM_ID, 205, ["EVENT_3153_set_229"]),
        JmpIfVarEqualsConst(ITEM_ID, 206, ["EVENT_3153_set_231"]),
        JmpIfVarEqualsConst(ITEM_ID, 207, ["EVENT_3153_set_233"]),
        JmpIfVarEqualsConst(ITEM_ID, 208, ["EVENT_3153_set_235"]),
        JmpIfVarEqualsConst(ITEM_ID, 209, ["EVENT_3153_set_237"]),
        JmpIfVarEqualsConst(ITEM_ID, 210, ["EVENT_3153_disable_trigger_241"]),
        JmpIfVarEqualsConst(ITEM_ID, SopranoCard, ["EVENT_3153_set_281"]),
        JmpIfVarEqualsConst(ITEM_ID, AltoCard, ["EVENT_3153_set_281"]),
        JmpIfVarEqualsConst(ITEM_ID, TenorCard, ["EVENT_3153_set_281"]),
        SummonObjectToCurrentLevel(
            MEM_70A8, identifier="EVENT_3153_summon_to_current_level_22"
        ),
        RunEventAsSubroutine(E0033_OLD_CHEST_LOADER_POSSIBLY_UNUSED),
        PlaySound(sound=SO014_FLOWER, channel=6),
        RunDialog(
            dialog_id=DI1177_FOUND_A_70A7_AUTO_TERMINATE,
            above_object=MARIO,
            closable=False,
            sync=True,
            multiline=False,
            use_background=False,
            bit_6=True,
        ),
        AddToInventory(ITEM_ID),
        Jmp(["EVENT_3153_ret_33"]),
        StopSound(),
        ActionQueueSync(
            target=SCREEN_FOCUS,
            subscript=[ASSetWalkingSpeed(FAST), ASSetWalkingSpeed(NORMAL)],
        ),
        Inc(HIDDEN_CHEST_COUNTER),
        SetVarToConst(TIMER_701C, 40),
        RunBackgroundEventWithPauseReturnOnExit(
            event_id=E1543_CHEST_CAMERA_SHIFT, timer_var=TIMER_701C
        ),
        Return(identifier="EVENT_3153_ret_33"),
        DisableObjectTrigger(MEM_70A8, identifier="EVENT_3153_disable_trigger_34"),
        PlaySound(sound=SO005_BLOCK_SWITCH, channel=6),
        CopyVarToVar(from_var=ITEM_ID, to_var=PRIMARY_TEMP_7000),
        DisableTriggerOfObjectAt70A8InCurrentLevel(),
        Mem7000AndConst(0x00F0),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=CHEST_COIN_SIZE),
        SetSyncActionScript(MEM_70A8, A0007_HIT_TREASURE_CHEST_CONTENTS_DEPLETED),
        Set70107015ToObjectXYZ(MEM_70A8),
        CopyVarToVar(from_var=Z_COORD_1, to_var=PRIMARY_TEMP_7000),
        AddConstToVar(PRIMARY_TEMP_7000, 608),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=Z_COORD_1),
        JmpIfVarEqualsConst(CHEST_COIN_SIZE, 0, ["EVENT_3153_play_sound_50"]),
        JmpIfVarEqualsConst(CHEST_COIN_SIZE, 16, ["EVENT_3153_enable_controls_57"]),
        JmpIfVarEqualsConst(CHEST_COIN_SIZE, 32, ["EVENT_3153_play_sound_104"]),
        JmpIfVarEqualsConst(CHEST_COIN_SIZE, 48, ["EVENT_3153_play_sound_109"]),
        Jmp(["EVENT_3153_ret_112"]),
        PlaySound(sound=SO014_FLOWER, channel=6, identifier="EVENT_3153_play_sound_50"),
        CreatePacketAt7010(
            packet=P001_FLASHING_POOF_MUSHROOM, destinations=["EVENT_3153_ret_112"]
        ),
        RestoreAllHP(),
        RestoreAllFP(),
        SetVarToConst(TIMER_7020, 8),
        RunBackgroundEventWithPause(event_id=E3075_HEAL_FLASH, timer_var=TIMER_7020),
        Jmp(["EVENT_3153_ret_112"]),
        EnableControls(
            [LEFT, RIGHT, DOWN, UP, A, Y, B], identifier="EVENT_3153_enable_controls_57"
        ),
        PlaySound(sound=SO014_FLOWER, channel=6),
        CreatePacketAt7010(packet=P003_BRIEF_STAR, destinations=["EVENT_3153_ret_112"]),
        StopMusicFDA0(),
        SetVarToConst(TIMER_7022, 550),
        RunBackgroundEventWithPause(
            event_id=E3076_EXP_STAR_CHEST_BACKGROUND, timer_var=TIMER_7022
        ),
        SetBit(TEMP_7076_0),
        JmpIfBitClear(
            PROGRESSIVE_STAR_EXP_ENABLED, ["EVENT_3153_set_7000_to_70A0_short_mem_95"]
        ),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 0, ["EVENT_3153_set_74"]),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 1, ["EVENT_3153_set_77"]),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 2, ["EVENT_3153_set_80"]),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 3, ["EVENT_3153_set_83"]),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 4, ["EVENT_3153_set_86"]),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 5, ["EVENT_3153_set_89"]),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 6, ["EVENT_3153_set_92"]),
        JmpIfVarEqualsConst(EXP_STAR_70D5, 7, ["EVENT_3153_set_92"]),
        Return(),
        SetVarToConst(ITEM_ID, WhompGlove, identifier="EVENT_3153_set_74"),
        Jmp(["EVENT_3153_set_7000_to_70A0_short_mem_95"]),
        Return(),
        SetVarToConst(ITEM_ID, SlapGlove, identifier="EVENT_3153_set_77"),
        Jmp(["EVENT_3153_set_7000_to_70A0_short_mem_95"]),
        Return(),
        SetVarToConst(ITEM_ID, TroopaShell, identifier="EVENT_3153_set_80"),
        Jmp(["EVENT_3153_set_7000_to_70A0_short_mem_95"]),
        Return(),
        SetVarToConst(ITEM_ID, Parasol, identifier="EVENT_3153_set_83"),
        Jmp(["EVENT_3153_set_7000_to_70A0_short_mem_95"]),
        Return(),
        SetVarToConst(ITEM_ID, HurlyGloves, identifier="EVENT_3153_set_86"),
        Jmp(["EVENT_3153_set_7000_to_70A0_short_mem_95"]),
        Return(),
        SetVarToConst(ITEM_ID, DoublePunch, identifier="EVENT_3153_set_89"),
        Jmp(["EVENT_3153_set_7000_to_70A0_short_mem_95"]),
        Return(),
        SetVarToConst(ITEM_ID, SpikedLink, identifier="EVENT_3153_set_92"),
        Jmp(["EVENT_3153_set_7000_to_70A0_short_mem_95"]),
        Return(),
        CopyVarToVar(
            from_var=ITEM_ID,
            to_var=PRIMARY_TEMP_7000,
            identifier="EVENT_3153_set_7000_to_70A0_short_mem_95",
        ),
        Mem7000AndConst(0x000F),
        SetEXPPacketTo7000(),
        MarioGlows(),
        ClearBit(EXP_STAR_BIT_6),
        ClearBit(UNKNOWN_7064_5),
        ClearBit(EXP_STAR_BIT_5),
        CreatePacketAtObjectCoords(
            packet=P022_RECURSIVE_SPARKLES,
            target_npc=MARIO,
            destinations=["EVENT_3153_jmp_103"],
        ),
        Jmp(["EVENT_3153_ret_112"], identifier="EVENT_3153_jmp_103"),
        PlaySound(
            sound=SO014_FLOWER, channel=6, identifier="EVENT_3153_play_sound_104"
        ),
        CreatePacketAt7010(
            packet=P000_FLASHING_POOF_FLOWER, destinations=["EVENT_3153_ret_112"]
        ),
        SetVarToConst(PRIMARY_TEMP_7000, 1),
        Add7000ToMaxFP(),
        Jmp(["EVENT_3153_ret_112"]),
        PlaySound(
            sound=SO094_FROG_COIN, channel=6, identifier="EVENT_3153_play_sound_109"
        ),
        CreatePacketAt7010(
            packet=P019_FROG_COIN_BEING_COLLECTED, destinations=["EVENT_3153_ret_112"]
        ),
        AddFrogCoins(1),
        Return(identifier="EVENT_3153_ret_112"),
        Return(),
        Return(),
        Return(),
        DisableObjectTrigger(MEM_70A8),
        JmpIfVarEqualsConst(ITEM_ID, 240, ["EVENT_3153_play_sound_119"]),
        DisableTriggerOfObjectAt70A8InCurrentLevel(),
        PlaySound(
            sound=SO005_BLOCK_SWITCH, channel=6, identifier="EVENT_3153_play_sound_119"
        ),
        CopyVarToVar(from_var=ACTIVE_NPC, to_var=PRIMARY_TEMP_7000),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=TEMP_70AA),
        Mem7000AndConst(0x0003),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=CHEST_COIN_SIZE),
        AddConstToVar(PRIMARY_TEMP_7000, 288),
        JmpIfMem704XAt7000BitSet(["EVENT_3153_jmp_if_var_equals_const_139"]),
        SetMem704XAt7000Bit(),
        CopyVarToVar(from_var=ITEM_ID, to_var=PRIMARY_TEMP_7000),
        Mem7000AndConst(0x000F),
        JmpIfVarEqualsConst(
            CHEST_COIN_SIZE, 1, ["EVENT_3153_set_70A0_short_mem_to_7000_134"]
        ),
        JmpIfVarEqualsConst(
            CHEST_COIN_SIZE, 2, ["EVENT_3153_set_70A0_short_mem_to_7000_136"]
        ),
        JmpIfVarEqualsConst(
            CHEST_COIN_SIZE, 3, ["EVENT_3153_set_70A0_short_mem_to_7000_138"]
        ),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=COIN_COUNTER_1),
        Jmp(["EVENT_3153_jmp_if_var_equals_const_139"]),
        CopyVarToVar(
            from_var=PRIMARY_TEMP_7000,
            to_var=COIN_COUNTER_2,
            identifier="EVENT_3153_set_70A0_short_mem_to_7000_134",
        ),
        Jmp(["EVENT_3153_jmp_if_var_equals_const_139"]),
        CopyVarToVar(
            from_var=PRIMARY_TEMP_7000,
            to_var=COIN_COUNTER_3,
            identifier="EVENT_3153_set_70A0_short_mem_to_7000_136",
        ),
        Jmp(["EVENT_3153_jmp_if_var_equals_const_139"]),
        CopyVarToVar(
            from_var=PRIMARY_TEMP_7000,
            to_var=COIN_COUNTER_4,
            identifier="EVENT_3153_set_70A0_short_mem_to_7000_138",
        ),
        JmpIfVarEqualsConst(
            CHEST_COIN_SIZE,
            1,
            ["EVENT_3153_jmp_if_var_not_equals_const_144"],
            identifier="EVENT_3153_jmp_if_var_equals_const_139",
        ),
        JmpIfVarEqualsConst(
            CHEST_COIN_SIZE, 2, ["EVENT_3153_jmp_if_var_not_equals_const_146"]
        ),
        JmpIfVarEqualsConst(
            CHEST_COIN_SIZE, 3, ["EVENT_3153_jmp_if_var_not_equals_const_148"]
        ),
        JmpIfVarNotEqualsConst(
            COIN_COUNTER_1, 1, ["EVENT_3153_set_temp_action_script_sync_151"]
        ),
        Jmp(["EVENT_3153_set_action_script_sync_149"]),
        JmpIfVarNotEqualsConst(
            COIN_COUNTER_2,
            1,
            ["EVENT_3153_set_temp_action_script_sync_151"],
            identifier="EVENT_3153_jmp_if_var_not_equals_const_144",
        ),
        Jmp(["EVENT_3153_set_action_script_sync_149"]),
        JmpIfVarNotEqualsConst(
            COIN_COUNTER_3,
            1,
            ["EVENT_3153_set_temp_action_script_sync_151"],
            identifier="EVENT_3153_jmp_if_var_not_equals_const_146",
        ),
        Jmp(["EVENT_3153_set_action_script_sync_149"]),
        JmpIfVarNotEqualsConst(
            COIN_COUNTER_4,
            1,
            ["EVENT_3153_set_temp_action_script_sync_151"],
            identifier="EVENT_3153_jmp_if_var_not_equals_const_148",
        ),
        SetSyncActionScript(
            MEM_70AA,
            A0007_HIT_TREASURE_CHEST_CONTENTS_DEPLETED,
            identifier="EVENT_3153_set_action_script_sync_149",
        ),
        Jmp(["EVENT_3153_set_7010_to_object_xyz_152"]),
        SetTempSyncActionScript(
            MEM_70AA,
            A0008_HIT_TREASURE_CHEST_CONTENTS_REMAINING,
            identifier="EVENT_3153_set_temp_action_script_sync_151",
        ),
        Set70107015ToObjectXYZ(
            MEM_70AA, identifier="EVENT_3153_set_7010_to_object_xyz_152"
        ),
        CopyVarToVar(from_var=Z_COORD_1, to_var=PRIMARY_TEMP_7000),
        AddConstToVar(PRIMARY_TEMP_7000, 608),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=Z_COORD_1),
        CopyVarToVar(from_var=ITEM_ID, to_var=PRIMARY_TEMP_7000),
        Mem7000AndConst(0x00F0),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 240, ["EVENT_3153_play_sound_192"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 160, ["EVENT_3153_play_sound_162"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 128, ["EVENT_3153_play_sound_177"]),
        Jmp(["EVENT_3153_ret_196"]),
        PlaySound(sound=SO013_COIN, channel=6, identifier="EVENT_3153_play_sound_162"),
        CreatePacketAt7010(
            packet=P016_BIG_COIN_BEING_COLLECTED, destinations=["EVENT_3153_ret_196"]
        ),
        SetSyncActionScript(MEM_70A9, A0906_COIN_CHEST),
        AddCoins(10),
        JmpIfVarEqualsConst(CHEST_COIN_SIZE, 1, ["EVENT_3153_dec_171"]),
        JmpIfVarEqualsConst(CHEST_COIN_SIZE, 2, ["EVENT_3153_dec_173"]),
        JmpIfVarEqualsConst(CHEST_COIN_SIZE, 3, ["EVENT_3153_dec_175"]),
        Dec(COIN_COUNTER_1),
        Jmp(["EVENT_3153_ret_196"]),
        Dec(COIN_COUNTER_2, identifier="EVENT_3153_dec_171"),
        Jmp(["EVENT_3153_ret_196"]),
        Dec(COIN_COUNTER_3, identifier="EVENT_3153_dec_173"),
        Jmp(["EVENT_3153_ret_196"]),
        Dec(COIN_COUNTER_4, identifier="EVENT_3153_dec_175"),
        Jmp(["EVENT_3153_ret_196"]),
        PlaySound(sound=SO013_COIN, channel=6, identifier="EVENT_3153_play_sound_177"),
        CreatePacketAt7010(
            packet=P018_SMALL_COIN_BEING_COLLECTED, destinations=["EVENT_3153_ret_196"]
        ),
        SetSyncActionScript(MEM_70A9, A0906_COIN_CHEST),
        AddCoins(1),
        JmpIfVarEqualsConst(CHEST_COIN_SIZE, 1, ["EVENT_3153_dec_186"]),
        JmpIfVarEqualsConst(CHEST_COIN_SIZE, 2, ["EVENT_3153_dec_188"]),
        JmpIfVarEqualsConst(CHEST_COIN_SIZE, 3, ["EVENT_3153_dec_190"]),
        Dec(COIN_COUNTER_1),
        Jmp(["EVENT_3153_ret_196"]),
        Dec(COIN_COUNTER_2, identifier="EVENT_3153_dec_186"),
        Jmp(["EVENT_3153_ret_196"]),
        Dec(COIN_COUNTER_3, identifier="EVENT_3153_dec_188"),
        Jmp(["EVENT_3153_ret_196"]),
        Dec(COIN_COUNTER_4, identifier="EVENT_3153_dec_190"),
        Jmp(["EVENT_3153_ret_196"]),
        PlaySound(sound=SO013_COIN, channel=6, identifier="EVENT_3153_play_sound_192"),
        CreatePacketAt7010(
            packet=P018_SMALL_COIN_BEING_COLLECTED, destinations=["EVENT_3153_ret_196"]
        ),
        SetSyncActionScript(MEM_70A9, A0906_COIN_CHEST),
        AddCoins(1),
        Return(identifier="EVENT_3153_ret_196"),
        SetVarToConst(ITEM_ID, 133, identifier="EVENT_3153_set_197"),
        SetVarToConst(PRIMARY_TEMP_7000, 5),
        Jmp(["EVENT_3153_add_coins_260"]),
        SetVarToConst(ITEM_ID, SheepAttack, identifier="EVENT_3153_set_200"),
        SetVarToConst(PRIMARY_TEMP_7000, 8),
        Jmp(["EVENT_3153_add_coins_260"]),
        SetVarToConst(ITEM_ID, BigBooFlag, identifier="EVENT_3153_set_203"),
        SetVarToConst(PRIMARY_TEMP_7000, 10),
        Jmp(["EVENT_3153_add_coins_260"]),
        SetVarToConst(ITEM_ID, Mushroom2, identifier="EVENT_3153_set_206"),
        SetVarToConst(PRIMARY_TEMP_7000, 150),
        Jmp(["EVENT_3153_add_coins_260"]),
        SetVarToConst(ITEM_ID, 170, identifier="EVENT_3153_set_209"),
        SetVarToConst(PRIMARY_TEMP_7000, 100),
        Jmp(["EVENT_3153_add_coins_260"]),
        SetVarToConst(ITEM_ID, 165, identifier="EVENT_3153_set_212"),
        SetVarToConst(PRIMARY_TEMP_7000, 50),
        Jmp(["EVENT_3153_add_coins_260"]),
        SetVarToConst(ITEM_ID, SonicCymbal, identifier="EVENT_3153_set_215"),
        Jmp(["EVENT_3153_disable_trigger_34"]),
        SetVarToConst(ITEM_ID, 0, identifier="EVENT_3153_set_217"),
        Jmp(["EVENT_3153_disable_trigger_34"]),
        SetVarToConst(ITEM_ID, HappyShell, identifier="EVENT_3153_set_219"),
        Jmp(["EVENT_3153_disable_trigger_34"]),
        SetVarToConst(ITEM_ID, WhompGlove, identifier="EVENT_3153_set_221"),
        Jmp(["EVENT_3153_disable_trigger_34"]),
        SetVarToConst(ITEM_ID, SlapGlove, identifier="EVENT_3153_set_223"),
        Jmp(["EVENT_3153_disable_trigger_34"]),
        SetVarToConst(ITEM_ID, TroopaShell, identifier="EVENT_3153_set_225"),
        Jmp(["EVENT_3153_disable_trigger_34"]),
        SetVarToConst(ITEM_ID, Parasol, identifier="EVENT_3153_set_227"),
        Jmp(["EVENT_3153_disable_trigger_34"]),
        SetVarToConst(ITEM_ID, DoublePunch, identifier="EVENT_3153_set_229"),
        Jmp(["EVENT_3153_disable_trigger_34"]),
        SetVarToConst(ITEM_ID, SpikedLink, identifier="EVENT_3153_set_231"),
        Jmp(["EVENT_3153_disable_trigger_34"]),
        SetVarToConst(ITEM_ID, MegaGlove, identifier="EVENT_3153_set_233"),
        Jmp(["EVENT_3153_disable_trigger_34"]),
        SetVarToConst(ITEM_ID, WarFan, identifier="EVENT_3153_set_235"),
        Jmp(["EVENT_3153_disable_trigger_34"]),
        SetVarToConst(ITEM_ID, DryBonesFlag, identifier="EVENT_3153_set_237"),
        SetVarToConst(PRIMARY_TEMP_7000, 20),
        Jmp(["EVENT_3153_add_coins_260"]),
        Return(),
        DisableObjectTrigger(MEM_70A8, identifier="EVENT_3153_disable_trigger_241"),
        PlaySound(sound=SO005_BLOCK_SWITCH, channel=6),
        DisableTriggerOfObjectAt70A8InCurrentLevel(),
        SetSyncActionScript(MEM_70A8, A0007_HIT_TREASURE_CHEST_CONTENTS_DEPLETED),
        Set70107015ToObjectXYZ(MEM_70A8),
        CopyVarToVar(from_var=Z_COORD_1, to_var=PRIMARY_TEMP_7000),
        AddConstToVar(PRIMARY_TEMP_7000, 608),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=Z_COORD_1),
        JmpIfBitSet(UNKNOWN_704A_3, ["EVENT_3153_clear_bit_251"]),
        PlaySound(sound=SO014_FLOWER, channel=6),
        ClearBit(UNKNOWN_704A_3, identifier="EVENT_3153_clear_bit_251"),
        Inc(HIDDEN_CHEST_COUNTER),
        RunDialog(
            dialog_id=DI3321_YOU_MISSED,
            above_object=Bowser,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        SetSyncActionScript(SCREEN_FOCUS, A0391_CAMERA_SHAKE),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASFaceSouthwest(),
                ASSetSpriteSequence(
                    index=1, sprite_offset=3, is_sequence=True, looping=True
                ),
                ASPlaySound(sound=SO022_CLOSE_DOOR, channel=4),
            ],
        ),
        Pause(40),
        SetAsyncActionScript(MARIO, A0384_PLAYER_LOOK_DOWN_SHAKE_HEAD),
        SetAsyncActionScript(MARIO, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        Return(),
        AddCoins(PRIMARY_TEMP_7000, identifier="EVENT_3153_add_coins_260"),
        SummonObjectToCurrentLevel(MEM_70A8),
        RunDialog(
            dialog_id=DI0515_GOT_X_COINS,
            above_object=MARIO,
            closable=False,
            sync=True,
            multiline=False,
            use_background=False,
            bit_6=True,
        ),
        DisableObjectTrigger(MEM_70A8),
        PlaySound(sound=SO005_BLOCK_SWITCH, channel=6),
        DisableTriggerOfObjectAt70A8InCurrentLevel(),
        SetSyncActionScript(MEM_70A8, A0007_HIT_TREASURE_CHEST_CONTENTS_DEPLETED),
        Set70107015ToObjectXYZ(MEM_70A8),
        CopyVarToVar(from_var=Z_COORD_1, to_var=PRIMARY_TEMP_7000),
        AddConstToVar(PRIMARY_TEMP_7000, 608),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=Z_COORD_1),
        JmpIfBitSet(UNKNOWN_704A_3, ["EVENT_3153_clear_bit_273"]),
        PlaySound(sound=SO013_COIN, channel=6),
        ClearBit(UNKNOWN_704A_3, identifier="EVENT_3153_clear_bit_273"),
        CreatePacketAt7010(
            packet=P016_BIG_COIN_BEING_COLLECTED, destinations=["EVENT_3153_ret_276"]
        ),
        Jmp(["EVENT_3153_ret_277"]),
        Return(identifier="EVENT_3153_ret_276"),
        Return(identifier="EVENT_3153_ret_277"),
        Return(),
        Return(),
        Return(),
        SetVarToConst(ITEM_ID, 0, identifier="EVENT_3153_set_281"),
        SetVarToConst(ITEM_ID, AltoCard),
        StoreItemAt70A7QuantityTo7000(),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 1, ["EVENT_3153_set_298"]),
        SetVarToConst(ITEM_ID, TenorCard),
        StoreItemAt70A7QuantityTo7000(),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 1, ["EVENT_3153_set_294"]),
        SetVarToConst(ITEM_ID, SopranoCard),
        StoreItemAt70A7QuantityTo7000(),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 1, ["EVENT_3153_disable_trigger_241"]),
        SetVarToConst(ITEM_ID, AltoCard),
        Jmp(["EVENT_3153_summon_to_current_level_22"]),
        Return(),
        SetVarToConst(ITEM_ID, SopranoCard, identifier="EVENT_3153_set_294"),
        RemoveOneOfItemFromInventory(TenorCard),
        Jmp(["EVENT_3153_summon_to_current_level_22"]),
        Return(),
        SetVarToConst(ITEM_ID, TenorCard, identifier="EVENT_3153_set_298"),
        RemoveOneOfItemFromInventory(AltoCard),
        Jmp(["EVENT_3153_summon_to_current_level_22"]),
        Return(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        StopSound(),
        Return(),
        Return(),
        Return(),
    ]
)
