# E3806_ENDING_CREDITS_RACE_NPCS

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        FreezeCamera(),
        RunEventAsSubroutine(E1193_ENDING_CREDITS_YOSTER_SHUFFLED_NPC_ANIMATION_LOADER),
        RunBackgroundEvent(
            event_id=E3808_ENDING_CREDITS_RACE_AUDIENCE, return_on_level_exit=True
        ),
        ActionQueueSync(
            target=NPC_7,
            subscript=[
                ASSetWalkingSpeed(VERY_SLOW),
                ASSetSequenceSpeed(FAST),
                ASShiftSouthwestSteps(2),
                ASShiftSouthwestPixels(8),
                ASFaceSoutheast(),
                ASPause(30),
                ASFaceNortheast(),
                ASSetSequenceSpeed(NORMAL),
                ASSetSpriteSequence(
                    index=13,
                    sprite_offset=1,
                    is_sequence=True,
                    looping=False,
                    mirror_sprite=True,
                ),
                ASPause(68),
                ASResetProperties(),
                ASFaceSoutheast(),
                ASPause(2),
                ASFaceSouthwest(),
                ASSetWalkingSpeed(FAST),
                ASSetSequenceSpeed(VERY_FAST),
                ASSequenceLoopingOn(),
                ASPause(60),
                ASShiftSouthwestSteps(5),
                ASShiftSouthwestPixels(12),
                ASSetSequenceSpeed(SLOW),
            ],
        ),
        ActionQueueSync(
            target=NPC_10,
            subscript=[
                ASSetWalkingSpeed(VERY_SLOW),
                ASSetSequenceSpeed(FAST),
                ASWalk1StepSouthwest(),
                ASSetSpriteSequence(index=4, is_sequence=True, looping=True),
                ASPause(61),
                ASResetProperties(),
                ASFaceNorthwest(),
                ASPause(2),
                ASFaceNortheast(),
                ASPause(60),
                ASFaceNorthwest(),
                ASPause(2),
                ASFaceSouthwest(),
                ASSetSequenceSpeed(VERY_FAST),
                ASSequenceLoopingOn(),
                ASSetWalkingSpeed(VERY_SLOW),
                ASShiftZUpPixels(12),
                ASShiftZDownPixels(12),
                ASSetWalkingSpeed(NORMAL),
                ASShiftSouthwestSteps(4),
                ASSequenceLoopingOff(),
                ASSetSequenceSpeed(NORMAL),
            ],
        ),
        ActionQueueSync(
            target=NPC_9,
            subscript=[
                ASPause(159),
                ASSetSpriteSequence(index=12, is_sequence=True, looping=True),
                ASVisibilityOff(),
                ASTransferToObjectXY(NPC_10),
                ASTransferXYZFPixels(x=4, y=254, z=0, direction=EAST),
                ASSetVRAMPriority(MARIO_OVERLAPS_ON_ALL_SIDES),
                ASSetPriority(3),
                ASVisibilityOn(),
                ASFloatingOn(),
                ASSetWalkingSpeed(VERY_FAST),
                ASShiftNorthSteps(4),
                ASSetWalkingSpeed(FAST),
                ASShiftNorthPixels(8),
                ASSetWalkingSpeed(NORMAL),
                ASShiftNorthPixels(4),
                ASSetWalkingSpeed(SLOW),
                ASShiftNorthPixels(2),
                ASShiftSouthPixels(2),
                ASSetWalkingSpeed(NORMAL),
                ASShiftSouthPixels(4),
                ASSetVRAMPriority(NORMAL_PRIORITY),
                ASSetWalkingSpeed(FAST),
                ASWalk1StepSouth(),
                ASSetWalkingSpeed(VERY_FAST),
                ASWalk1StepSouth(),
                ASShiftSouthPixels(2),
                ASWalk1StepSouthwest(),
                ASVisibilityOff(),
            ],
        ),
        ActionQueueSync(target=NPC_5, subscript=[ASPause(300), ASFaceSouthwest()]),
        ActionQueueSync(target=NPC_6, subscript=[ASPause(300), ASFaceSouthwest()]),
        StarMaskExpandFromScreenCenter(),
        RememberLastObject(),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASSetWalkingSpeed(FAST),
                ASSetSequenceSpeed(FAST),
                ASShiftSouthwestSteps(3),
                ASShiftNorthwestSteps(5),
                ASShiftNortheastSteps(1),
                ASShiftNortheastPixels(12),
                ASFaceSoutheast(),
                ASSequenceLoopingOff(),
            ],
        ),
        ActionQueueSync(
            target=NPC_4,
            subscript=[
                ASSetWalkingSpeed(FAST),
                ASSetSequenceSpeed(FAST),
                ASShiftSouthwestSteps(4),
                ASShiftSouthwestPixels(4),
                ASShiftNorthwestSteps(4),
                ASShiftNorthwestPixels(4),
                ASFaceNortheast(),
                ASSequenceLoopingOff(),
            ],
        ),
        ActionQueueSync(
            target=NPC_2,
            subscript=[
                ASSetWalkingSpeed(FAST),
                ASSetSequenceSpeed(FAST),
                ASShiftSouthwestSteps(5),
                ASShiftSouthwestPixels(6),
                ASShiftNorthwestSteps(2),
                ASShiftNorthwestPixels(12),
                ASSequenceLoopingOff(),
            ],
        ),
        SetSyncActionScript(NPC_10, A0239_ENDING_CREDITS_CROCO),
        RememberLastObject(),
        ActionQueueAsync(target=NPC_7, subscript=[ASSequenceLoopingOff()]),
        SetSyncActionScript(NPC_7, A0677_MUSHROOM_DERBY_UNKNOWN),
        SetSyncActionScript(NPC_2, A0677_MUSHROOM_DERBY_UNKNOWN),
        SetSyncActionScript(NPC_3, A0677_MUSHROOM_DERBY_UNKNOWN),
        SetSyncActionScript(NPC_4, A0677_MUSHROOM_DERBY_UNKNOWN),
        ActionQueueSync(
            target=NPC_0,
            subscript=[
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASShiftSoutheastSteps(4),
                ASPause(134),
                ASSetWalkingSpeed(VERY_SLOW),
                ASSetSequenceSpeed(NORMAL),
                ASShiftNortheastSteps(12),
            ],
        ),
        SetSyncActionScript(NPC_5, A0208_RAZ_ENDING),
        SetSyncActionScript(NPC_6, A0209_RAINI_ENDING),
        Pause(425),
        PauseScriptUntilEffectDone(),
        StarMaskShrinkToScreenCenter(),
        PauseScriptUntilEffectDone(),
        JmpToEvent(E3800_ENDING_CREDITS_INDIGO_STAR),
    ]
)
