# pylint: disable=C0301

"""E1178_SEASIDE_GRANT_SHED_ITEM"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        Pause(1, identifier="EVENT_1178_pause_0"),
        ActionQueueSync(
            target=NPC_0,
            subscript=[
                ASFaceSouthwest(),
                ASPause(1),
                ASJumpToHeight(height=96, silent=True),
                ASPause(1),
            ],
        ),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASFaceSouthwest(),
                ASPause(1),
                ASJumpToHeight(height=96, silent=True),
                ASPause(1),
            ],
        ),
        ActionQueueSync(
            target=NPC_2,
            subscript=[
                ASFaceSoutheast(),
                ASPause(1),
                ASJumpToHeight(height=48, silent=True),
                ASPause(1),
            ],
        ),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASFaceSouthwest(),
                ASPause(1),
                ASJumpToHeight(height=80, silent=True),
                ASPause(1),
            ],
        ),
        ActionQueueSync(
            target=NPC_4,
            subscript=[
                ASFaceSoutheast(),
                ASPause(1),
                ASJumpToHeight(height=48, silent=True),
                ASPause(1),
            ],
        ),
        ActionQueueSync(
            target=NPC_5,
            subscript=[
                ASFaceNorthwest(),
                ASPause(1),
                ASJumpToHeight(height=85, silent=True),
                ASPause(1),
            ],
        ),
        ActionQueueAsync(
            target=NPC_6,
            subscript=[
                ASFaceSoutheast(),
                ASPause(1),
                ASJumpToHeight(height=112, silent=True),
                ASPause(1),
            ],
        ),
        ActionQueueAsync(
            target=NPC_5,
            subscript=[
                ASSetAllSpeeds(VERY_FAST),
                ASBounceToXYWithHeight(x=4, y=19, height=0),
                ASFaceSouthwest(),
                ASSetSequenceSpeed(NORMAL),
            ],
        ),
        ActionQueueAsync(
            target=NPC_5,
            subscript=[
                ASSetAllSpeeds(VERY_FAST),
                ASWalkSoutheastSteps(1),
                ASWalkSouthwestSteps(2),
                ASVisibilityOff(),
            ],
        ),
        Pause(1),
        ActionQueueAsync(
            target=NPC_6,
            subscript=[
                ASSetAllSpeeds(VERY_FAST),
                ASBounceToXYWithHeight(x=4, y=19, height=0),
                ASFaceSouthwest(),
                ASSetSequenceSpeed(NORMAL),
            ],
        ),
        ActionQueueAsync(
            target=NPC_6,
            subscript=[
                ASSetAllSpeeds(VERY_FAST),
                ASWalkSoutheastSteps(1),
                ASWalkSouthwestSteps(2),
                ASVisibilityOff(),
            ],
        ),
        Pause(1),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASSetAllSpeeds(VERY_FAST),
                ASBounceToXYWithHeight(x=4, y=19, height=0),
                ASFaceSouthwest(),
                ASSetSequenceSpeed(NORMAL),
            ],
        ),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASSetAllSpeeds(VERY_FAST),
                ASWalkSoutheastSteps(1),
                ASWalkSouthwestSteps(2),
                ASVisibilityOff(),
            ],
        ),
        Pause(1),
        ActionQueueSync(
            target=NPC_0,
            subscript=[
                ASSetAllSpeeds(VERY_FAST),
                ASBounceToXYWithHeight(x=4, y=19, height=0),
                ASFaceSouthwest(),
                ASSetSequenceSpeed(FAST),
            ],
        ),
        ActionQueueAsync(
            target=NPC_1,
            subscript=[
                ASSetAllSpeeds(VERY_FAST),
                ASBounceToXYWithHeight(x=5, y=20, height=0),
                ASFaceSouthwest(),
                ASSetSequenceSpeed(FAST),
            ],
        ),
        ActionQueueSync(
            target=NPC_0,
            subscript=[
                ASSetAllSpeeds(VERY_FAST),
                ASWalkSoutheastSteps(1),
                ASWalkSouthwestSteps(2),
                ASVisibilityOff(),
            ],
        ),
        ActionQueueAsync(
            target=NPC_1,
            subscript=[
                ASSetAllSpeeds(VERY_FAST),
                ASWalkSouthwestSteps(2),
                ASVisibilityOff(),
            ],
        ),
        Pause(5),
        ActionQueueAsync(
            target=NPC_4,
            subscript=[
                ASSetAllSpeeds(NORMAL),
                ASWalkSoutheastSteps(4),
                ASWalkSouthwestSteps(1),
                ASFaceSouthwest(),
            ],
        ),
        ActionQueueAsync(
            target=NPC_4,
            subscript=[
                ASWalkSoutheastSteps(1),
                ASWalkSouthwestSteps(2),
                ASVisibilityOff(),
            ],
        ),
        Pause(1),
        ActionQueueAsync(
            target=NPC_2,
            subscript=[
                ASSetAllSpeeds(NORMAL),
                ASWalkSoutheastSteps(4),
                ASWalkSouthwestSteps(2),
                ASFaceSouthwest(),
            ],
        ),
        RunEventAsSubroutine(E0178_NPC_QUEST_1_CONTAINER),
        ActionQueueAsync(
            target=NPC_2,
            subscript=[
                ASWalkSoutheastSteps(1),
                ASWalkSouthwestSteps(2),
                ASVisibilityOff(),
            ],
        ),
        SetBit(SEASIDE_SHED_EMPTIED),
        Pause(1),
        RemoveObjectFromSpecificLevel(
            NPC_5, R208_SEASIDE_TOWN_DURING_YARIDOVICH_OUTSIDE
        ),
        RemoveOneOfItemFromInventory(ShedKey),
        Return(),
    ]
)
