# pylint: disable=C0301

"""E1775_SKY_TROOPA_PLATFORM"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        CopyVarToVar(from_var=ACTIVE_NPC, to_var=PRIMARY_TEMP_7000),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 23, ["EVENT_1775_jmp_if_bit_set_15"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 24, ["EVENT_1775_jmp_if_bit_set_21"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 25, ["EVENT_1775_jmp_if_bit_set_27"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 26, ["EVENT_1775_jmp_if_bit_set_33"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 27, ["EVENT_1775_jmp_if_bit_set_39"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 28, ["EVENT_1775_jmp_if_bit_set_45"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 29, ["EVENT_1775_jmp_if_bit_set_51"]),
        JmpIfBitSet(
            TEMP_7043_1, ["EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_13"]
        ),
        SetBit(TEMP_7043_1),
        SetBit(TEMP_7044_1),
        JmpToSubroutine(["EVENT_1775_jmp_if_bit_set_57"]),
        ActionQueueSync(
            target=NPC_2,
            subscript=[
                ASSetWalkingSpeed(SLOW),
                ASWalkSoutheastSteps(2),
                ASShiftZUpSteps(2),
                ASPause(60),
                ASSetSequenceSpeed(VERY_FAST),
                ASPause(30),
                ASSetAllSpeeds(NORMAL),
                ASShiftZDownSteps(2),
                ASWalkNorthwestSteps(2),
                ASClearBit(TEMP_7043_1),
            ],
        ),
        ReactivateObject70A8TriggerIfMarioOnTopOfIt(
            identifier="EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_13"
        ),
        Return(),
        JmpIfBitSet(
            TEMP_7043_2,
            ["EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_19"],
            identifier="EVENT_1775_jmp_if_bit_set_15",
        ),
        SetBit(TEMP_7043_2),
        JmpToSubroutine(["EVENT_1775_jmp_if_bit_set_57"]),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASSetWalkingSpeed(SLOW),
                ASWalkSoutheastSteps(5),
                ASAddZCoord1Step(),
                ASPause(60),
                ASSetSequenceSpeed(VERY_FAST),
                ASPause(30),
                ASSetAllSpeeds(NORMAL),
                ASDecZCoord1Step(),
                ASWalkNorthwestSteps(5),
                ASClearBit(TEMP_7043_2),
            ],
        ),
        ReactivateObject70A8TriggerIfMarioOnTopOfIt(
            identifier="EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_19"
        ),
        Return(),
        JmpIfBitSet(
            TEMP_7043_3,
            ["EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_25"],
            identifier="EVENT_1775_jmp_if_bit_set_21",
        ),
        SetBit(TEMP_7043_3),
        JmpToSubroutine(["EVENT_1775_jmp_if_bit_set_57"]),
        ActionQueueSync(
            target=NPC_4,
            subscript=[
                ASSetWalkingSpeed(SLOW),
                ASShiftZUpSteps(2),
                ASWalkNorthwestSteps(2),
                ASPause(60),
                ASSetSequenceSpeed(VERY_FAST),
                ASPause(30),
                ASSetAllSpeeds(NORMAL),
                ASWalkSoutheastSteps(2),
                ASShiftZDownSteps(2),
                ASClearBit(TEMP_7043_3),
            ],
        ),
        ReactivateObject70A8TriggerIfMarioOnTopOfIt(
            identifier="EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_25"
        ),
        Return(),
        JmpIfBitSet(
            TEMP_7043_4,
            ["EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_31"],
            identifier="EVENT_1775_jmp_if_bit_set_27",
        ),
        SetBit(TEMP_7043_4),
        JmpToSubroutine(["EVENT_1775_jmp_if_bit_set_57"]),
        ActionQueueSync(
            target=NPC_5,
            subscript=[
                ASSetWalkingSpeed(SLOW),
                ASWalkNorthwestSteps(4),
                ASPause(60),
                ASSetSequenceSpeed(VERY_FAST),
                ASPause(30),
                ASSetAllSpeeds(NORMAL),
                ASWalkSoutheastSteps(4),
                ASClearBit(TEMP_7043_4),
            ],
        ),
        ReactivateObject70A8TriggerIfMarioOnTopOfIt(
            identifier="EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_31"
        ),
        Return(),
        JmpIfBitSet(
            TEMP_7043_5,
            ["EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_37"],
            identifier="EVENT_1775_jmp_if_bit_set_33",
        ),
        SetBit(TEMP_7043_5),
        JmpToSubroutine(["EVENT_1775_jmp_if_bit_set_57"]),
        ActionQueueSync(
            target=NPC_6,
            subscript=[
                ASSetWalkingSpeed(SLOW),
                ASWalkNorthwestSteps(2),
                ASShiftZUpSteps(2),
                ASPause(60),
                ASSetSequenceSpeed(VERY_FAST),
                ASPause(30),
                ASSetAllSpeeds(NORMAL),
                ASWalkSoutheastSteps(3),
                ASShiftZDownSteps(2),
                ASWalk1StepNorthwest(),
                ASClearBit(TEMP_7043_5),
            ],
        ),
        ReactivateObject70A8TriggerIfMarioOnTopOfIt(
            identifier="EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_37"
        ),
        Return(),
        JmpIfBitSet(
            TEMP_7043_6,
            ["EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_43"],
            identifier="EVENT_1775_jmp_if_bit_set_39",
        ),
        SetBit(TEMP_7043_6),
        JmpToSubroutine(["EVENT_1775_jmp_if_bit_set_57"]),
        ActionQueueSync(
            target=NPC_7,
            subscript=[
                ASSetWalkingSpeed(SLOW),
                ASShiftZUpSteps(4),
                ASWalk1StepSoutheast(),
                ASPause(60),
                ASSetSequenceSpeed(VERY_FAST),
                ASPause(30),
                ASSetAllSpeeds(NORMAL),
                ASWalk1StepNorthwest(),
                ASShiftZDownSteps(4),
                ASClearBit(TEMP_7043_6),
            ],
        ),
        ReactivateObject70A8TriggerIfMarioOnTopOfIt(
            identifier="EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_43"
        ),
        Return(),
        JmpIfBitSet(
            TEMP_7043_7,
            ["EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_49"],
            identifier="EVENT_1775_jmp_if_bit_set_45",
        ),
        SetBit(TEMP_7043_7),
        JmpToSubroutine(["EVENT_1775_jmp_if_bit_set_57"]),
        ActionQueueSync(
            target=NPC_8,
            subscript=[
                ASSetWalkingSpeed(SLOW),
                ASWalkSoutheastSteps(2),
                ASShiftZDownSteps(3),
                ASWalk1StepSoutheast(),
                ASPause(60),
                ASSetSequenceSpeed(VERY_FAST),
                ASPause(30),
                ASSetAllSpeeds(NORMAL),
                ASWalk1StepNorthwest(),
                ASShiftZUpSteps(3),
                ASWalkNorthwestSteps(2),
                ASClearBit(TEMP_7043_7),
            ],
        ),
        ReactivateObject70A8TriggerIfMarioOnTopOfIt(
            identifier="EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_49"
        ),
        Return(),
        JmpIfBitSet(
            TEMP_7044_0,
            ["EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_55"],
            identifier="EVENT_1775_jmp_if_bit_set_51",
        ),
        SetBit(TEMP_7044_0),
        JmpToSubroutine(["EVENT_1775_jmp_if_bit_set_57"]),
        ActionQueueSync(
            target=NPC_9,
            subscript=[
                ASSetWalkingSpeed(SLOW),
                ASWalkSoutheastSteps(3),
                ASShiftZUpSteps(3),
                ASPause(60),
                ASSetSequenceSpeed(VERY_FAST),
                ASPause(60),
                ASSetAllSpeeds(NORMAL),
                ASShiftZDownSteps(3),
                ASWalkNorthwestSteps(3),
                ASClearBit(TEMP_7044_0),
            ],
        ),
        ReactivateObject70A8TriggerIfMarioOnTopOfIt(
            identifier="EVENT_1775_reactivate_trigger_if_mario_on_top_of_object_55"
        ),
        Return(),
        JmpIfBitSet(
            TEMP_707C_0,
            ["EVENT_1775_clear_bit_60"],
            identifier="EVENT_1775_jmp_if_bit_set_57",
        ),
        Db(bytearray(b"\xc7\x90")),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASSet700CToObjectCoord(target_npc=MARIO, coord=COORD_F, pixel=True),
                ASFixedFCoordOn(),
                ASFloatingOff(),
                ASRunAwayShift(),
                ASFloatingOn(),
                ASFixedFCoordOff(),
                ASFaceEast7C(),
            ],
        ),
        ClearBit(TEMP_707C_0, identifier="EVENT_1775_clear_bit_60"),
        Return(),
    ]
)
