# E2601_FACTORY_4TH_ROOM_LOADER

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        ActionQueueSync(
            target=NPC_0,
            subscript=[
                ASSetVRAMPriority(MARIO_OVERLAPS_ON_ALL_SIDES),
                ASSetSpriteSequence(
                    index=0,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
            ],
        ),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASSetVRAMPriority(MARIO_OVERLAPS_ON_ALL_SIDES),
                ASSetSpriteSequence(
                    index=2,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
            ],
        ),
        ActionQueueSync(
            target=NPC_2,
            subscript=[
                ASSetVRAMPriority(MARIO_OVERLAPS_ON_ALL_SIDES),
                ASSetSpriteSequence(
                    index=3,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
            ],
        ),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASSetVRAMPriority(MARIO_OVERLAPS_ON_ALL_SIDES),
                ASSetSpriteSequence(
                    index=1,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
            ],
        ),
        ActionQueueSync(
            target=NPC_4,
            subscript=[
                ASSetVRAMPriority(OBJECT_OVERLAPS_MARIO_ON_ALL_SIDES),
                ASShiftSouthPixels(4),
                ASShiftWestPixels(4),
                ASSetSpriteSequence(
                    index=0,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
            ],
        ),
        ActionQueueSync(
            target=NPC_5,
            subscript=[
                ASSetVRAMPriority(MARIO_OVERLAPS_ON_ALL_SIDES),
                ASShiftEastPixels(12),
                ASSetSpriteSequence(
                    index=4,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
            ],
        ),
        ActionQueueSync(
            target=NPC_6,
            subscript=[
                ASSetVRAMPriority(MARIO_OVERLAPS_ON_ALL_SIDES),
                ASShiftWestPixels(8),
                ASShiftSouthPixels(1),
                ASSetSpriteSequence(
                    index=5,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
            ],
        ),
        JmpIfBitSet(FACTORY_BOSS_DEFEATED, ["EVENT_2601_summon_to_level_37___"]),
        RunEventAsSubroutine(E1969_CHECK_IF_STAR_PIECES_FOR_FACTORY_BOSS_COLLECTED),
        JmpIfComparisonResultIsLesser(["EVENT_2601_fade_in_from_black_async_7_"]),
        SummonObjectToSpecificLevel(
            NPC_14, R470_FACTORY_GROUNDS_AREA_04_GUN_YOLKS_ROOM
        ),
        SummonObjectToCurrentLevel(NPC_14),
        Jmp(["EVENT_2601_sequence_setter_2"]),
        RemoveObjectFromSpecificLevel(
            NPC_14,
            R470_FACTORY_GROUNDS_AREA_04_GUN_YOLKS_ROOM,
            identifier="EVENT_2601_summon_to_level_37___",
        ),
        RemoveObjectFromCurrentLevel(NPC_14),
        RunEventAsSubroutine(
            E0858_INNER_FACTORY_4TH_ROOM_SHUFFLED_NPC_ANIMATION_LOADER,
            identifier="EVENT_2601_sequence_setter_2",
        ),
        FadeInFromBlack(
            sync=False, identifier="EVENT_2601_fade_in_from_black_async_7_"
        ),
        JmpIfBitClear(GAMEBOY_KID_PURCHASE_COMPLETE, ["EVENT_2601_ret_8_"]),
        SetVarToConst(PRIMARY_TEMP_7000, 523),
        JmpToEvent(E0167_BOSS_GRANT_STAR_PIECE),
        Return(identifier="EVENT_2601_ret_8_"),
    ]
)
