# E2416_FOREST_TRAMPOLINE_BUSINESS_LOGIC

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        SetBit(DIRECTIONAL_7047_0, identifier="EVENT_2416_set_bit_0"),
        ActionQueueSync(
            target=MEM_70A8, subscript=[ASSetSpriteSequence(index=0, looping=False)]
        ),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASFixedFCoordOn(),
                ASFloatingOff(),
                ASSequencePlaybackOff(),
                ASShadowOff(),
                ASSetWalkingSpeed(VERY_SLOW),
                ASShiftSouthPixels(8),
            ],
        ),
        SetAsyncActionScript(MARIO, A0408_JUMP_ON_SAVE_BLOCK),
        PlaySound(sound=SO010_TRAMPOLINE, channel=6),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASPause(4),
                ASDb(bytearray(b" \x04")),
                ASDb(bytearray(b"%\x00\x0f\xf0\xff")),
                ASPause(48),
                ASBPL262728(),
            ],
        ),
        Pause(24),
        FadeOutToBlack(sync=False, duration=8),
        StopEmbeddedActionScript(MARIO),
        JmpIfBitSet(DIRECTIONAL_7045_0, ["EVENT_2416_clear_bit_15"]),
        JmpIfBitSet(DIRECTIONAL_7045_1, ["EVENT_2416_clear_bit_18"]),
        JmpIfBitSet(DIRECTIONAL_7045_2, ["EVENT_2416_clear_bit_21"]),
        JmpIfBitSet(DIRECTIONAL_7045_3, ["EVENT_2416_clear_bit_24"]),
        JmpIfBitSet(DIRECTIONAL_7045_4, ["EVENT_2416_clear_bit_27"]),
        JmpIfBitSet(DIRECTIONAL_7045_5, ["EVENT_2416_clear_bit_30"]),
        ClearBit(DIRECTIONAL_7045_0, identifier="EVENT_2416_clear_bit_15"),
        EnterArea(
            room_id=R226_FOREST_MAZE_AREA_02,
            face_direction=SOUTH,
            x=16,
            y=24,
            z=0,
            run_entrance_event=True,
        ),
        Return(),
        ClearBit(DIRECTIONAL_7045_1, identifier="EVENT_2416_clear_bit_18"),
        EnterArea(
            room_id=R228_FOREST_MAZE_AREA_04,
            face_direction=SOUTH,
            x=6,
            y=110,
            z=0,
            run_entrance_event=True,
        ),
        Return(),
        ClearBit(DIRECTIONAL_7045_2, identifier="EVENT_2416_clear_bit_21"),
        EnterArea(
            room_id=R229_FOREST_MAZE_AREA_06,
            face_direction=SOUTH,
            x=20,
            y=108,
            z=0,
            run_entrance_event=True,
        ),
        Return(),
        ClearBit(DIRECTIONAL_7045_2, identifier="EVENT_2416_clear_bit_24"),
        EnterArea(
            room_id=R231_FOREST_MAZE_SECRET_ENTRANCE,
            face_direction=SOUTH,
            x=19,
            y=74,
            z=0,
            run_entrance_event=True,
        ),
        Return(),
        ClearBit(DIRECTIONAL_7045_4, identifier="EVENT_2416_clear_bit_27"),
        EnterArea(
            room_id=R227_FOREST_MAZE_AREA_09_LEADS_TO_4PATH_MAZE,
            face_direction=SOUTH,
            x=6,
            y=40,
            z=0,
            run_entrance_event=True,
        ),
        Return(),
        ClearBit(DIRECTIONAL_7045_5, identifier="EVENT_2416_clear_bit_30"),
        JmpIfVarEqualsConst(TEMP_70AC, 1, ["EVENT_2416_enter_area_39"]),
        JmpIfVarEqualsConst(TEMP_70AC, 2, ["EVENT_2416_enter_area_41"]),
        JmpIfVarEqualsConst(TEMP_70AC, 3, ["EVENT_2416_enter_area_43"]),
        JmpIfVarEqualsConst(TEMP_70AC, 4, ["EVENT_2416_enter_area_45"]),
        JmpIfVarEqualsConst(TEMP_70AC, 5, ["EVENT_2416_enter_area_47"]),
        JmpIfVarEqualsConst(TEMP_70AC, 6, ["EVENT_2416_enter_area_49"]),
        EnterArea(
            room_id=R225_FOREST_MAZE_AREA_05_TREE_TRUNK_AREA,
            face_direction=SOUTH,
            x=4,
            y=74,
            z=0,
            run_entrance_event=True,
        ),
        Return(),
        EnterArea(
            room_id=R225_FOREST_MAZE_AREA_05_TREE_TRUNK_AREA,
            face_direction=SOUTH,
            x=16,
            y=92,
            z=0,
            run_entrance_event=True,
            identifier="EVENT_2416_enter_area_39",
        ),
        Return(),
        EnterArea(
            room_id=R225_FOREST_MAZE_AREA_05_TREE_TRUNK_AREA,
            face_direction=SOUTH,
            x=13,
            y=98,
            z=0,
            run_entrance_event=True,
            identifier="EVENT_2416_enter_area_41",
        ),
        Return(),
        EnterArea(
            room_id=R225_FOREST_MAZE_AREA_05_TREE_TRUNK_AREA,
            face_direction=SOUTH,
            x=12,
            y=86,
            z=0,
            run_entrance_event=True,
            identifier="EVENT_2416_enter_area_43",
        ),
        Return(),
        EnterArea(
            room_id=R225_FOREST_MAZE_AREA_05_TREE_TRUNK_AREA,
            face_direction=SOUTH,
            x=9,
            y=92,
            z=0,
            run_entrance_event=True,
            identifier="EVENT_2416_enter_area_45",
        ),
        Return(),
        EnterArea(
            room_id=R225_FOREST_MAZE_AREA_05_TREE_TRUNK_AREA,
            face_direction=SOUTH,
            x=9,
            y=78,
            z=0,
            run_entrance_event=True,
            identifier="EVENT_2416_enter_area_47",
        ),
        Return(),
        EnterArea(
            room_id=R225_FOREST_MAZE_AREA_05_TREE_TRUNK_AREA,
            face_direction=SOUTH,
            x=6,
            y=84,
            z=0,
            run_entrance_event=True,
            identifier="EVENT_2416_enter_area_49",
        ),
        Return(),
    ]
)
