# E1852_SKY_BRIDGE_ADMIN_SHAMAN

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        CopyVarToVar(from_var=ACTIVE_NPC, to_var=PRIMARY_TEMP_7000),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=TEMP_70AE),
        JmpIfMarioOnAnObjectOrNot(
            [
                "EVENT_1852_set_action_script_sync_31",
                "EVENT_1852_set_action_script_sync_68",
            ]
        ),
        JmpIfBitSet(TEMP_7043_2, ["EVENT_1852_stop_all_background_events_70"]),
        RunDialog(
            dialog_id=DI1300_DUPLICATE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
        ),
        JmpIfDialogOptionBSelected(["EVENT_1852_pause_17"]),
        Jmp(["EVENT_1852_pause_23"]),
        Pause(10, identifier="EVENT_1852_pause_17"),
        SetAsyncActionScript(MARIO, A0671_SHAKE_HEAD_NO),
        ClearBit(TEMP_7044_7),
        SetSyncActionScript(MARIO, A0823_PLAYER_RESET_IN_SKY_BRIDGE_ROOM),
        Return(),
        Pause(10, identifier="EVENT_1852_pause_23"),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        ClearBit(TEMP_7044_7),
        RunDialog(
            dialog_id=DI1305_SKY_BRIDGE_5_COIN_PAY,
            above_object=NPC_17,
            closable=False,
            sync=False,
            multiline=True,
            use_background=True,
        ),
        StoreCoinCountTo7000(),
        CompareVarToConst(PRIMARY_TEMP_7000, 5),
        JmpIfComparisonResultIsGreaterOrEqual(["EVENT_1852_play_sound_33"]),
        RunDialogForDuration(
            dialog_id=DI1306_SKY_BRIDGE_INSUFFICIENT_COINS, duration=1, sync=False
        ),
        SetSyncActionScript(
            MARIO,
            A0823_PLAYER_RESET_IN_SKY_BRIDGE_ROOM,
            identifier="EVENT_1852_set_action_script_sync_31",
        ),
        Return(),
        PlaySound(
            sound=SO055_LOSE_COINS_COIN_FOUNTAIN,
            channel=6,
            identifier="EVENT_1852_play_sound_33",
        ),
        SetVarToConst(PRIMARY_TEMP_7000, 5),
        Dec7000FromCoins(),
        JmpIfBitSet(SKY_BRIDGE_TUTORIAL_BIT, ["EVENT_1852_run_dialog_48"]),
        RunDialog(
            dialog_id=DI1302_SKY_BRIDGE_TUTORIAL_PROMPT,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
        ),
        JmpIfDialogOptionBSelected(["EVENT_1852_pause_45"]),
        Pause(10),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        ClearBit(TEMP_7044_7),
        SetBit(SKY_BRIDGE_TUTORIAL_BIT),
        RunDialog(
            dialog_id=DI1303_SKY_BRIDGE_TUTORIAL,
            above_object=NPC_17,
            closable=False,
            sync=False,
            multiline=True,
            use_background=True,
        ),
        Jmp(["EVENT_1852_run_dialog_48"]),
        Pause(10, identifier="EVENT_1852_pause_45"),
        SetAsyncActionScript(MARIO, A0671_SHAKE_HEAD_NO),
        ClearBit(TEMP_7044_7),
        RunDialog(
            dialog_id=DI1304_SKY_BRIDGE_LEVEL_SELECT,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_1852_run_dialog_48",
        ),
        JmpIfDialogOptionBOrCSelected(
            ["EVENT_1852_set_short_54", "EVENT_1852_set_short_58"]
        ),
        SetVarToConst(TEMP_7026, 5),
        SetBit(SKY_BRIDGE_COURSE_CHOICE),
        SetBit(SKY_BRIDGE_COURSE_1_CHOSEN),
        Jmp(["EVENT_1852_set_short_61"]),
        SetVarToConst(TEMP_7026, 8, identifier="EVENT_1852_set_short_54"),
        SetBit(SKY_BRIDGE_COURSE_CHOICE),
        ClearBit(SKY_BRIDGE_COURSE_1_CHOSEN),
        Jmp(["EVENT_1852_set_short_61"]),
        SetVarToConst(TEMP_7026, 1, identifier="EVENT_1852_set_short_58"),
        ClearBit(SKY_BRIDGE_COURSE_CHOICE),
        ClearBit(SKY_BRIDGE_COURSE_1_CHOSEN),
        SetVarToConst(TEMP_702E, 48, identifier="EVENT_1852_set_short_61"),
        SetVarToConst(TEMP_702C, 100),
        RunDialog(
            dialog_id=DI1314_SKY_BRIDGE_GOOD_LUCK,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
        ),
        SetBit(TEMP_7043_2),
        SetVarToConst(TEMP_7028, 1),
        ActionQueueAsync(
            target=NPC_17,
            subscript=[
                ASClearSolidityBits(
                    bit_4=True, cant_pass_npcs=True, cant_walk_through=True, bit_7=True
                ),
                ASPlaySound(sound=SO161_GHOST, channel=4),
                ASJumpToHeight(128),
                ASStartLoopNTimes(4),
                ASVisibilityOff(),
                ASPause(1),
                ASVisibilityOn(),
                ASPause(2),
                ASEndLoop(),
                ASFloatingOff(),
                ASSetSolidityBits(bit_4=True, cant_walk_through=True),
                ASTransferToXYZF(x=10, y=76, z=19, direction=EAST),
                ASFaceSouthwest(),
            ],
            identifier="EVENT_1852_action_queue_async_66",
        ),
        RunBackgroundEvent(
            event_id=E1732_SKY_BRIDGE_BACKGROUND, return_on_level_exit=True
        ),
        SetSyncActionScript(
            MARIO,
            A0823_PLAYER_RESET_IN_SKY_BRIDGE_ROOM,
            identifier="EVENT_1852_set_action_script_sync_68",
        ),
        Return(),
        StopAllBackgroundEvents(identifier="EVENT_1852_stop_all_background_events_70"),
        ClearBit(TEMP_7043_0),
        ClearBit(TEMP_7044_3),
        JmpIfVarNotEqualsConst(TEMP_7028, 3, ["EVENT_1852_run_dialog_76"]),
        RunDialog(
            dialog_id=DI1308_SKY_BRIDGE_CONGRATS,
            above_object=NPC_17,
            closable=False,
            sync=False,
            multiline=True,
            use_background=True,
        ),
        Jmp(["EVENT_1852_run_dialog_94"]),
        RunDialog(
            dialog_id=DI1307_SKY_BRIDGE_DOUBLE_PROMPT,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_1852_run_dialog_76",
        ),
        JmpIfDialogOptionBSelected(["EVENT_1852_pause_91"]),
        Pause(10),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        ClearBit(TEMP_7044_7),
        Inc(TEMP_7028),
        VarShiftLeft(TEMP_7026, 255),
        AddConstToVar(TEMP_702E, 65520),
        AddConstToVar(TEMP_702C, 65516),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASSetWalkingSpeed(FAST),
                ASClearSolidityBits(cant_pass_walls=True),
                ASJumpToHeight(108),
                ASWalkToXYCoords(x=10, y=76),
                ASPause(
                    1, identifier="EVENT_1852_action_queue_async_85_SUBSCRIPT_pause_4"
                ),
                ASJmpIfMarioInAir(
                    ["EVENT_1852_action_queue_async_85_SUBSCRIPT_pause_4"]
                ),
            ],
        ),
        Pause(1),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASFloatingOff(),
                ASSequencePlaybackOff(),
                ASSetWalkingSpeed(SLOW),
                ASAddZCoord1Step(),
                ASSetWalkingSpeed(VERY_FAST),
                ASWalkToXYCoords(x=20, y=104),
            ],
        ),
        ActionQueueAsync(
            target=NPC_17,
            subscript=[
                ASSetWalkingSpeed(SLOW),
                ASAddZCoord1Step(),
                ASSetWalkingSpeed(VERY_FAST),
                ASWalkToXYCoords(x=20, y=104),
            ],
        ),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASSetAllSpeeds(NORMAL),
                ASFloatingOn(),
                ASSequencePlaybackOn(),
                ASSetSolidityBits(cant_pass_walls=True),
            ],
        ),
        Jmp(["EVENT_1852_action_queue_async_66"]),
        Pause(10, identifier="EVENT_1852_pause_91"),
        SetAsyncActionScript(MARIO, A0671_SHAKE_HEAD_NO),
        ClearBit(TEMP_7044_7),
        RunDialog(
            dialog_id=DI1309_EMPTY,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_1852_run_dialog_94",
        ),
        ActionQueueAsync(
            target=NPC_17,
            subscript=[ASSetSpriteSequence(index=4, looping=False), ASPause(40)],
        ),
        JmpIfBitSet(SKY_BRIDGE_COURSE_CHOICE, ["EVENT_1852_play_sound_102"]),
        PlaySound(sound=SO094_FROG_COIN, channel=6),
        CopyVarToVar(from_var=TEMP_7026, to_var=PRIMARY_TEMP_7000),
        AddFrogCoins(PRIMARY_TEMP_7000),
        RunDialog(
            dialog_id=DI1310_RECEIVED_X_FROG_COINS,
            above_object=TOADSTOOL,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        Jmp(["EVENT_1852_action_queue_sync_106"]),
        PlaySound(sound=SO013_COIN, channel=6, identifier="EVENT_1852_play_sound_102"),
        CopyVarToVar(from_var=TEMP_7026, to_var=PRIMARY_TEMP_7000),
        AddCoins(PRIMARY_TEMP_7000),
        RunDialog(
            dialog_id=DI1311_RECEIVED_X_COINS,
            above_object=TOADSTOOL,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        ActionQueueSync(
            target=NPC_18,
            subscript=[
                ASStartLoopNTimes(3),
                ASTurnClockwise45DegreesNTimes(2),
                ASPause(1),
                ASEndLoop(),
            ],
            identifier="EVENT_1852_action_queue_sync_106",
        ),
        ActionQueueAsync(
            target=NPC_17,
            subscript=[
                ASClearSolidityBits(
                    bit_4=True, cant_pass_npcs=True, cant_walk_through=True, bit_7=True
                ),
                ASPlaySound(sound=SO161_GHOST, channel=4),
                ASJumpToHeight(128),
                ASStartLoopNTimes(4),
                ASVisibilityOff(),
                ASPause(1),
                ASVisibilityOn(),
                ASPause(2),
                ASEndLoop(),
                ASFloatingOff(),
                ASSetSolidityBits(bit_4=True, cant_walk_through=True),
                ASTransferToXYZF(x=20, y=104, z=18, direction=EAST),
                ASFaceSouthwest(),
            ],
        ),
        ClearBit(TEMP_7043_2),
        SetSyncActionScript(MARIO, A0823_PLAYER_RESET_IN_SKY_BRIDGE_ROOM),
        Return(),
    ]
)
