# pylint: disable=C0301

"""E1366_CURTAIN_GAME_BUSINESS_LOGIC_2"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        PauseActionScript(NPC_1, identifier="EVENT_1366_pause_action_script_0"),
        PauseActionScript(NPC_2),
        Pause(10),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASDb(bytearray(b"\xfd\x9ck")),
                ASResetProperties(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASFaceSouthwest(),
                ASPause(25),
                ASFaceNorthwest(),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        ActionQueueAsync(
            target=NPC_2,
            subscript=[
                ASResetProperties(),
                ASFixedFCoordOff(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASWalkNortheastPixels(8),
                ASWalkNorthwestSteps(3),
                ASPause(15),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        Pause(20),
        SetSyncActionScript(NPC_1, A0576_CURTAIN_GAME_OPEN_CURTAIN),
        SetSyncActionScript(NPC_2, A0576_CURTAIN_GAME_OPEN_CURTAIN),
        PlaySound(sound=SO090_CURTAIN, channel=4),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=37),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=45),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=38),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=46),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=39),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=47),
        StartLoopNTimes(79),
        JmpIfBitSet(TEMP_7043_1, ["EVENT_1366_move_script_to_main_thread_243"]),
        JmpIfBitSet(TEMP_7043_3, ["EVENT_1366_move_script_to_main_thread_243"]),
        Pause(1),
        EndLoop(),
        SetSyncActionScript(NPC_1, A0577_CURTAIN_GAME_OPEN_CURTAIN),
        SetSyncActionScript(NPC_2, A0577_CURTAIN_GAME_OPEN_CURTAIN),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=38),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=46),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=37),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=45),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=36),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=44),
        Pause(3),
        PauseActionScript(NPC_1),
        PauseActionScript(NPC_2),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASDb(bytearray(b"\xfd\x9ck")),
                ASResetProperties(),
                ASFixedFCoordOff(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASWalkSouthwestSteps(2),
                ASPause(15),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        ActionQueueAsync(
            target=NPC_2,
            subscript=[
                ASResetProperties(),
                ASFixedFCoordOff(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASWalkSouthwestSteps(2),
                ASPause(15),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        Pause(20),
        SetSyncActionScript(NPC_1, A0576_CURTAIN_GAME_OPEN_CURTAIN),
        SetSyncActionScript(NPC_2, A0576_CURTAIN_GAME_OPEN_CURTAIN),
        PlaySound(sound=SO090_CURTAIN, channel=4),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=33),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=41),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=34),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=42),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=35),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=43),
        StartLoopNTimes(59),
        JmpIfBitSet(TEMP_7043_0, ["EVENT_1366_move_script_to_main_thread_243"]),
        JmpIfBitSet(TEMP_7043_2, ["EVENT_1366_move_script_to_main_thread_243"]),
        Pause(1),
        EndLoop(),
        SetSyncActionScript(NPC_1, A0577_CURTAIN_GAME_OPEN_CURTAIN),
        SetSyncActionScript(NPC_2, A0577_CURTAIN_GAME_OPEN_CURTAIN),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=34),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=42),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=33),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=41),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=32),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=40),
        Pause(3),
        PauseActionScript(NPC_1),
        PauseActionScript(NPC_2),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASDb(bytearray(b"\xfd\x9ck")),
                ASResetProperties(),
                ASFixedFCoordOff(),
                ASSetWalkingSpeed(SLOW),
                ASSetSequenceSpeed(NORMAL),
                ASWalkSouthwestSteps(1),
                ASJumpToHeight(117),
                ASWalkSouthwestSteps(1),
                ASFaceNorthwest(),
                ASPause(20),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        ActionQueueAsync(
            target=NPC_2,
            subscript=[
                ASResetProperties(),
                ASFixedFCoordOff(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASWalkNortheastSteps(4),
                ASFaceNorthwest(),
                ASPause(20),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        Pause(20),
        SetSyncActionScript(NPC_1, A0576_CURTAIN_GAME_OPEN_CURTAIN),
        SetSyncActionScript(NPC_2, A0576_CURTAIN_GAME_OPEN_CURTAIN),
        PlaySound(sound=SO090_CURTAIN, channel=4),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=37),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=41),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=38),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=42),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=39),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=43),
        StartLoopNTimes(39),
        JmpIfBitSet(TEMP_7043_1, ["EVENT_1366_move_script_to_main_thread_243"]),
        JmpIfBitSet(TEMP_7043_2, ["EVENT_1366_move_script_to_main_thread_243"]),
        Pause(1),
        EndLoop(),
        SetSyncActionScript(NPC_1, A0577_CURTAIN_GAME_OPEN_CURTAIN),
        SetSyncActionScript(NPC_2, A0577_CURTAIN_GAME_OPEN_CURTAIN),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=38),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=42),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=37),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=41),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=36),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=40),
        Pause(3),
        PauseActionScript(NPC_1),
        PauseActionScript(NPC_2),
        Pause(15),
        ActionQueueSync(
            target=NPC_2,
            subscript=[
                ASDb(bytearray(b"\xfd\x9ck")),
                ASResetProperties(),
                ASFixedFCoordOff(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASWalkSouthwestPixels(8),
                ASPause(5),
                ASFixedFCoordOn(),
                ASJumpToHeight(64),
                ASWalkNortheastSteps(1),
                ASPause(20),
                ASFixedFCoordOff(),
                ASWalkNortheastSteps(1),
                ASWalkNortheastPixels(8),
                ASFaceNorthwest(),
                ASPause(15),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        ActionQueueAsync(
            target=NPC_1,
            subscript=[
                ASResetProperties(),
                ASFixedFCoordOff(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASWalkNortheastPixels(8),
                ASPause(5),
                ASFixedFCoordOn(),
                ASJumpToHeight(64),
                ASWalkSouthwestSteps(1),
                ASPause(20),
                ASFixedFCoordOff(),
                ASWalkSouthwestSteps(1),
                ASWalkSouthwestPixels(8),
                ASFaceNorthwest(),
                ASPause(15),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        Pause(20),
        PlaySound(sound=SO107_DRUM_ROLL, channel=4),
        ActionQueueAsync(
            target=NPC_1,
            subscript=[
                ASResetProperties(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASWalkNortheastSteps(2),
                ASFaceNorthwest(),
                ASPause(15),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        Pause(20),
        SetSyncActionScript(NPC_1, A0576_CURTAIN_GAME_OPEN_CURTAIN),
        SetSyncActionScript(NPC_2, A0576_CURTAIN_GAME_OPEN_CURTAIN),
        PlaySound(sound=SO090_CURTAIN, channel=4),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=37),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=45),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=38),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=46),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=39),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=47),
        StartLoopNTimes(24),
        JmpIfBitSet(TEMP_7043_1, ["EVENT_1366_move_script_to_main_thread_243"]),
        JmpIfBitSet(TEMP_7043_3, ["EVENT_1366_move_script_to_main_thread_243"]),
        Pause(1),
        EndLoop(),
        SetSyncActionScript(NPC_1, A0577_CURTAIN_GAME_OPEN_CURTAIN),
        SetSyncActionScript(NPC_2, A0577_CURTAIN_GAME_OPEN_CURTAIN),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=38),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=46),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=37),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=45),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=36),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=44),
        Pause(3),
        PauseActionScript(NPC_1),
        PauseActionScript(NPC_2),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASResetProperties(),
                ASFixedFCoordOff(),
                ASPause(5),
                ASFaceNorthwest(),
            ]),
        ActionQueueAsync(
            target=NPC_2,
            subscript=[
                ASResetProperties(),
                ASPause(30),
                ASFixedFCoordOff(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASFaceSouthwest(),
                ASPause(15),
                ASJumpToHeight(53),
                ASPause(15),
                ASJumpToHeight(53),
                ASPause(15),
            ]),
        PlaySound(sound=SO107_DRUM_ROLL, channel=4),
        ActionQueueAsync(
            target=NPC_1,
            subscript=[
                ASPause(10),
                ASResetProperties(),
                ASFixedFCoordOff(),
                ASFaceNortheast(),
                ASPause(20),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASWalkNortheastSteps(2),
                ASPause(30),
                ASFaceNorthwest(),
            ]),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASFaceNorthwest(),
                ASPause(10),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        ActionQueueAsync(
            target=NPC_2,
            subscript=[
                ASFaceNorthwest(),
                ASPause(10),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        Pause(20),
        SetSyncActionScript(NPC_1, A0576_CURTAIN_GAME_OPEN_CURTAIN),
        SetSyncActionScript(NPC_2, A0576_CURTAIN_GAME_OPEN_CURTAIN),
        PlaySound(sound=SO090_CURTAIN, channel=4),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=41),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=45),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=42),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=46),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=43),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=47),
        StartLoopNTimes(14),
        JmpIfBitSet(TEMP_7043_2, ["EVENT_1366_move_script_to_main_thread_243"]),
        JmpIfBitSet(TEMP_7043_3, ["EVENT_1366_move_script_to_main_thread_243"]),
        Pause(1),
        EndLoop(),
        SetSyncActionScript(NPC_1, A0577_CURTAIN_GAME_OPEN_CURTAIN),
        SetSyncActionScript(NPC_2, A0577_CURTAIN_GAME_OPEN_CURTAIN),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=42),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=46),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=41),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=45),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=40),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=44),
        Pause(3),
        PauseActionScript(NPC_1),
        PauseActionScript(NPC_2),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASDb(bytearray(b"\xfd\x9ck")),
                ASResetProperties(),
                ASFixedFCoordOff(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASWalkSouthwestSteps(2),
                ASPause(10),
                ASFaceNorthwest(),
                ASPause(10),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        ActionQueueAsync(
            target=NPC_2,
            subscript=[
                ASResetProperties(),
                ASFixedFCoordOff(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASWalkSouthwestSteps(2),
                ASPause(10),
                ASFaceNorthwest(),
                ASPause(10),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        Pause(20),
        SetSyncActionScript(NPC_1, A0576_CURTAIN_GAME_OPEN_CURTAIN),
        SetSyncActionScript(NPC_2, A0576_CURTAIN_GAME_OPEN_CURTAIN),
        PlaySound(sound=SO090_CURTAIN, channel=4),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=37),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=41),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=38),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=42),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=39),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=43),
        StartLoopNTimes(14),
        JmpIfBitSet(TEMP_7043_1, ["EVENT_1366_move_script_to_main_thread_243"]),
        JmpIfBitSet(TEMP_7043_2, ["EVENT_1366_move_script_to_main_thread_243"]),
        Pause(1),
        EndLoop(),
        SetSyncActionScript(NPC_1, A0577_CURTAIN_GAME_OPEN_CURTAIN),
        SetSyncActionScript(NPC_2, A0577_CURTAIN_GAME_OPEN_CURTAIN),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=38),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=42),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=37),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=41),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=36),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=40),
        Pause(3),
        PauseActionScript(NPC_1),
        PauseActionScript(NPC_2),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASDb(bytearray(b"\xfd\x9ck")),
                ASResetProperties(),
                ASFixedFCoordOff(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASWalkSouthwestSteps(2),
                ASPause(10),
                ASFaceNorthwest(),
                ASPause(10),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        ActionQueueAsync(
            target=NPC_2,
            subscript=[
                ASResetProperties(),
                ASFixedFCoordOff(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASWalkSouthwestSteps(2),
                ASPause(10),
                ASFaceNorthwest(),
                ASPause(10),
                ASSetSpriteSequence(
                    index=6, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        Pause(20),
        SetSyncActionScript(NPC_1, A0576_CURTAIN_GAME_OPEN_CURTAIN),
        SetSyncActionScript(NPC_2, A0576_CURTAIN_GAME_OPEN_CURTAIN),
        PlaySound(sound=SO090_CURTAIN, channel=4),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=33),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=37),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=34),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=38),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=35),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=39),
        StartLoopNTimes(29),
        JmpIfBitSet(TEMP_7043_0, ["EVENT_1366_move_script_to_main_thread_243"]),
        JmpIfBitSet(TEMP_7043_1, ["EVENT_1366_move_script_to_main_thread_243"]),
        Pause(1),
        EndLoop(),
        SetSyncActionScript(NPC_1, A0577_CURTAIN_GAME_OPEN_CURTAIN),
        SetSyncActionScript(NPC_2, A0577_CURTAIN_GAME_OPEN_CURTAIN),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=34),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=38),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=33),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=37),
        Pause(3),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=32),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R192_BOOSTER_TOWER_9F_AREA_02_BOOSTERS_CURTAIN_GAME_ROOM,
            mod_id=36),
        Pause(3),
        PauseActionScript(NPC_1),
        PauseActionScript(NPC_2),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASPause(15),
                ASResetProperties(),
                ASFixedFCoordOff(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASFaceSoutheast(),
            ]),
        ActionQueueAsync(
            target=NPC_2,
            subscript=[
                ASPause(15),
                ASResetProperties(),
                ASFixedFCoordOff(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSequenceSpeed(FAST),
                ASFaceSoutheast(),
            ]),
        Pause(30),
        Jmp(["EVENT_1367_pause_action_script_0"]),
        MoveScriptToMainThread(identifier="EVENT_1366_move_script_to_main_thread_243"),
        EnableControlsUntilReturn([]),
        StopMusicFDA2(),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASPause(1),
                ASSetSpriteSequence(
                    index=0,
                    sprite_offset=3,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
            ]),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASFixedFCoordOn(),
                ASSetWalkingSpeed(VERY_FAST),
                ASWalkSoutheastSteps(2),
            ]),
        ActionQueueAsync(
            target=NPC_2,
            subscript=[
                ASFixedFCoordOn(),
                ASSetWalkingSpeed(VERY_FAST),
                ASWalkSoutheastSteps(2),
            ]),
        Pause(30),
        ActionQueueSync(
            target=NPC_0,
            subscript=[
                ASFixedFCoordOff(),
                ASFaceNorthwest(),
                ASPause(10),
                ASJumpToHeight(50),
            ]),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASFixedFCoordOff(),
                ASFaceNorthwest(),
                ASPause(10),
                ASJumpToHeight(50),
            ]),
        Jmp(["EVENT_1370_play_sound____"]),
    ]
)
