# E3479_MIDAS_RIVER_SCORE_SUBMISSION

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        SetVarToConst(TEMP_70AE, 23),
        JmpIfBitSet(UNKNOWN_MIDAS_RIVER_7079_1, ["EVENT_3479_run_dialog_134"]),
        JmpIfBitClear(TEMP_7043_1, ["EVENT_3479_run_dialog_97"]),
        JmpIfVarNotEqualsConst(
            TEMP_702A, 0, ["EVENT_3479_set_7000_to_7000_short_mem_6"]
        ),
        RunDialog(
            dialog_id=DI1086_MIDAS_EXCHANGE,
            above_object=NPC_12,
            closable=False,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        Jmp(["EVENT_3479_run_dialog_97"]),
        CopyVarToVar(
            from_var=TEMP_702A,
            to_var=PRIMARY_TEMP_7000,
            identifier="EVENT_3479_set_7000_to_7000_short_mem_6",
        ),
        JmpIfVarNotEqualsConst(
            PRIMARY_TEMP_7000, 100, ["EVENT_3479_jmp_if_bit_clear_9"]
        ),
        SetBit(TEMP_7043_3),
        JmpIfBitClear(
            TEMP_7043_2,
            ["EVENT_3479_set_7000_to_70A0_short_mem_13"],
            identifier="EVENT_3479_jmp_if_bit_clear_9",
        ),
        SetVarToConst(MIDAS_RIVER_70CA, 60),
        SetVarToConst(SECONDARY_TEMP_7024, 1),
        Jmp(["EVENT_3479_set_7000_to_70A0_short_mem_32"]),
        CopyVarToVar(
            from_var=MIDAS_RIVER_70B3,
            to_var=PRIMARY_TEMP_7000,
            identifier="EVENT_3479_set_7000_to_70A0_short_mem_13",
        ),
        SetVarToConst(MIDAS_RIVER_70CA, 80),
        SetVarToConst(SECONDARY_TEMP_7024, 1),
        CompareVarToConst(PRIMARY_TEMP_7000, 70),
        JmpIfComparisonResultIsLesser(["EVENT_3479_set_7000_to_70A0_short_mem_32"]),
        SetVarToConst(MIDAS_RIVER_70CA, 75),
        SetVarToConst(SECONDARY_TEMP_7024, 1),
        CompareVarToConst(PRIMARY_TEMP_7000, 80),
        JmpIfComparisonResultIsLesser(["EVENT_3479_set_7000_to_70A0_short_mem_32"]),
        SetVarToConst(MIDAS_RIVER_70CA, 70),
        SetVarToConst(SECONDARY_TEMP_7024, 1),
        CompareVarToConst(PRIMARY_TEMP_7000, 90),
        JmpIfComparisonResultIsLesser(["EVENT_3479_set_7000_to_70A0_short_mem_32"]),
        SetVarToConst(MIDAS_RIVER_70CA, 60),
        SetVarToConst(SECONDARY_TEMP_7024, 1),
        CompareVarToConst(PRIMARY_TEMP_7000, 100),
        JmpIfComparisonResultIsLesser(["EVENT_3479_set_7000_to_70A0_short_mem_32"]),
        SetVarToConst(MIDAS_RIVER_70CA, 50),
        SetVarToConst(SECONDARY_TEMP_7024, 1),
        CopyVarToVar(
            from_var=MIDAS_RIVER_70CA,
            to_var=PRIMARY_TEMP_7000,
            identifier="EVENT_3479_set_7000_to_70A0_short_mem_32",
        ),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=TEMP_7026),
        CopyVarToVar(from_var=TEMP_702A, to_var=PRIMARY_TEMP_7000),
        RunDialog(
            dialog_id=DI1076_MIDAS_EXCHANGE,
            above_object=NPC_12,
            closable=False,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        JmpIfBitSet(TEMP_7043_2, ["EVENT_3479_set_7000_to_7000_short_mem_43"]),
        CopyVarToVar(from_var=MIDAS_RIVER_70B3, to_var=PRIMARY_TEMP_7000),
        Compare7000ToVar(TEMP_702A),
        JmpIfComparisonResultIsGreaterOrEqual(
            ["EVENT_3479_set_7000_to_7000_short_mem_43"]
        ),
        RunDialog(
            dialog_id=DI1087_MIDAS_EXCHANGE,
            above_object=NPC_12,
            closable=False,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        CopyVarToVar(from_var=TEMP_702A, to_var=PRIMARY_TEMP_7000),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=MIDAS_RIVER_70B3),
        CopyVarToVar(
            from_var=TEMP_7026,
            to_var=PRIMARY_TEMP_7000,
            identifier="EVENT_3479_set_7000_to_7000_short_mem_43",
        ),
        JmpIfBitSet(TEMP_7043_2, ["EVENT_3479_run_dialog_duration_47"]),
        RunDialogForDuration(dialog_id=DI1043_MIDAS_EXCHANGE, duration=0, sync=False),
        Jmp(["EVENT_3479_set_7000_to_7000_short_mem_48"]),
        RunDialogForDuration(
            dialog_id=DI1037_DUPLICATE,
            duration=0,
            sync=False,
            identifier="EVENT_3479_run_dialog_duration_47",
        ),
        CopyVarToVar(
            from_var=TEMP_702A,
            to_var=PRIMARY_TEMP_7000,
            identifier="EVENT_3479_set_7000_to_7000_short_mem_48",
        ),
        JmpIfVarEqualsConst(MIDAS_RIVER_70D4, 0, ["EVENT_3479_compare_7000_to_var_53"]),
        RunDialogForDuration(dialog_id=DI1044_MIDAS_EXCHANGE, duration=0, sync=False),
        CopyVarToVar(from_var=MIDAS_RIVER_70D4, to_var=PRIMARY_TEMP_7000),
        AddVarTo7000(TEMP_702A),
        Compare7000ToVar(TEMP_7026, identifier="EVENT_3479_compare_7000_to_var_53"),
        JmpIfComparisonResultIsLesser(["EVENT_3479_set_70A0_short_mem_to_7000_76"]),
        RunDialogForDuration(dialog_id=DI1045_MIDAS_EXCHANGE, duration=0, sync=False),
        SetVarToConst(TEMP_7028, 0),
        Inc(TEMP_7028, identifier="EVENT_3479_inc_short_57"),
        DecVarFrom7000(TEMP_7026),
        Compare7000ToVar(TEMP_7026),
        JmpIfComparisonResultIsGreaterOrEqual(["EVENT_3479_inc_short_57"]),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=MIDAS_RIVER_70D4),
        SetVarToConst(PRIMARY_TEMP_7000, 0),
        SetObjectMemoryToVar(TEMP_7028),
        AddVarTo7000(SECONDARY_TEMP_7024),
        EndLoop(),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=TEMP_7028),
        RunDialogForDuration(dialog_id=DI1046_MIDAS_EXCHANGE, duration=1, sync=False),
        JmpIfBitClear(TEMP_7043_3, ["EVENT_3479_jmp_to_subroutine_72"]),
        RunDialog(
            dialog_id=DI1039_MIDAS_EXCHANGE,
            above_object=NPC_12,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        AddConstToVar(PRIMARY_TEMP_7000, 5),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=TEMP_7028),
        JmpToSubroutine(
            ["EVENT_3479_action_queue_sync_137"],
            identifier="EVENT_3479_jmp_to_subroutine_72",
        ),
        CopyVarToVar(from_var=MIDAS_RIVER_70D4, to_var=PRIMARY_TEMP_7000),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 0, ["EVENT_3479_jmp_if_bit_set_83"]),
        Jmp(["EVENT_3479_jmp_if_bit_set_83"]),
        CopyVarToVar(
            from_var=PRIMARY_TEMP_7000,
            to_var=MIDAS_RIVER_70D4,
            identifier="EVENT_3479_set_70A0_short_mem_to_7000_76",
        ),
        RunDialogForDuration(dialog_id=DI1042_MIDAS_EXCHANGE, duration=1, sync=False),
        PlaySound(sound=SO055_LOSE_COINS_COIN_FOUNTAIN, channel=6),
        JmpIfBitClear(TEMP_7043_3, ["EVENT_3479_jmp_if_bit_set_83"]),
        RunDialog(
            dialog_id=DI1038_MIDAS_EXCHANGE,
            above_object=NPC_12,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        SetVarToConst(TEMP_7028, 5),
        JmpToSubroutine(["EVENT_3479_action_queue_sync_137"]),
        JmpIfBitSet(
            MIDAS_RIVER_FIRST_VISIT_PRIZE_RECEIVED,
            ["EVENT_3479_jmp_if_bit_set_85"],
            identifier="EVENT_3479_jmp_if_bit_set_83",
        ),
        JmpIfVarNotEqualsConst(TEMP_702A, 0, ["EVENT_3479_set_88"]),
        JmpIfBitSet(
            TEMP_7043_1,
            ["EVENT_3479_action_queue_async_94"],
            identifier="EVENT_3479_jmp_if_bit_set_85",
        ),
        Return(),
        Return(),
        RunEventAsSubroutine(
            E0178_NPC_QUEST_1_CONTAINER, identifier="EVENT_3479_set_88"
        ),
        SetBit(MIDAS_RIVER_FIRST_VISIT_PRIZE_RECEIVED),
        JmpIfBitSet(TEMP_7043_1, ["EVENT_3479_action_queue_async_94"]),
        Return(),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASSetAllSpeeds(FAST),
                ASShiftSouthwestSteps(4),
                ASWalk1StepSoutheast(),
                ASSetAllSpeeds(NORMAL),
            ],
            identifier="EVENT_3479_action_queue_async_94",
        ),
        ClearBit(TEMP_7043_1),
        Return(),
        RunDialog(
            dialog_id=DI1077_MIDAS_EXCHANGE,
            above_object=NPC_12,
            closable=False,
            sync=False,
            multiline=True,
            use_background=False,
            identifier="EVENT_3479_run_dialog_97",
        ),
        JmpIfBitSet(TEMP_7043_1, ["EVENT_3479_run_dialog_duration_103"]),
        CopyVarToVar(from_var=MIDAS_RIVER_70D4, to_var=PRIMARY_TEMP_7000),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=SECONDARY_TEMP_7024),
        CopyVarToVar(from_var=MIDAS_RIVER_70B3, to_var=PRIMARY_TEMP_7000),
        RunDialogForDuration(dialog_id=DI1075_MIDAS_EXCHANGE, duration=0, sync=False),
        RunDialogForDuration(
            dialog_id=DI1082_MIDAS_EXCHANGE,
            duration=1,
            sync=False,
            identifier="EVENT_3479_run_dialog_duration_103",
        ),
        JmpIfDialogOptionBSelected(["EVENT_3479_pause_130"]),
        Pause(10),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        StoreCoinCountTo7000(),
        CompareVarToConst(PRIMARY_TEMP_7000, 30),
        JmpIfComparisonResultIsGreaterOrEqual(["EVENT_3479_set_123"]),
        RunDialog(
            dialog_id=DI1081_MIDAS_EXCHANGE,
            above_object=NPC_12,
            closable=False,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        CopyVarToVar(from_var=MIDAS_RIVER_70D4, to_var=PRIMARY_TEMP_7000),
        CompareVarToConst(PRIMARY_TEMP_7000, 30),
        JmpIfComparisonResultIsLesser(["EVENT_3479_run_dialog_duration_121"]),
        RunDialogForDuration(dialog_id=DI1040_MIDAS_EXCHANGE, duration=1, sync=False),
        JmpIfDialogOptionBSelected(["EVENT_3479_pause_130"]),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        CopyVarToVar(from_var=MIDAS_RIVER_70D4, to_var=PRIMARY_TEMP_7000),
        AddConstToVar(PRIMARY_TEMP_7000, 65506),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=MIDAS_RIVER_70D4),
        Jmp(["EVENT_3479_run_dialog_125"]),
        RunDialogForDuration(
            dialog_id=DI1079_MIDAS_EXCHANGE,
            duration=1,
            sync=False,
            identifier="EVENT_3479_run_dialog_duration_121",
        ),
        Jmp(["EVENT_3479_jmp_if_bit_set_83"]),
        SetVarToConst(PRIMARY_TEMP_7000, 30, identifier="EVENT_3479_set_123"),
        Dec7000FromCoins(),
        RunDialog(
            dialog_id=DI1078_MIDAS_EXCHANGE,
            above_object=NPC_12,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
            identifier="EVENT_3479_run_dialog_125",
        ),
        PlaySound(sound=SO055_LOSE_COINS_COIN_FOUNTAIN, channel=6),
        SetBit(TEMP_7043_0),
        SetBit(UNKNOWN_MIDAS_RIVER_7079_1),
        Jmp(["EVENT_3479_jmp_if_bit_set_83"]),
        Pause(10, identifier="EVENT_3479_pause_130"),
        SetAsyncActionScript(MARIO, A0671_SHAKE_HEAD_NO),
        RunDialog(
            dialog_id=DI1079_MIDAS_EXCHANGE,
            above_object=NPC_12,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        Jmp(["EVENT_3479_jmp_if_bit_set_83"]),
        RunDialog(
            dialog_id=DI1080_MIDAS_EXCHANGE,
            above_object=NPC_12,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
            identifier="EVENT_3479_run_dialog_134",
        ),
        SetBit(TEMP_7043_0),
        Return(),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASSetSpriteSequence(
                    index=9, sprite_offset=2, is_sequence=True, looping=True
                )
            ],
            identifier="EVENT_3479_action_queue_sync_137",
        ),
        SetObjectMemoryToVar(TEMP_7028),
        ActionQueueAsync(
            target=NPC_5,
            subscript=[
                ASPlaySound(sound=SO094_FROG_COIN, channel=4),
                ASShadowOff(),
                ASSetVRAMPriority(PRIORITY_3),
                ASSetPriority(3),
                ASSetSpriteSequence(index=1, is_sequence=True, looping=True),
                ASDb(bytearray(b"\x97\x17")),
                ASSetAllSpeeds(FASTEST),
                ASShiftZUpPixels(16),
                ASSetAllSpeeds(NORMAL),
                ASVisibilityOn(),
                ASFloatingOff(),
                ASJumpToHeight(height=80, silent=True),
                ASWalk1StepNortheast(),
                ASVisibilityOff(),
            ],
        ),
        SetVarToConst(PRIMARY_TEMP_7000, 1),
        AddFrogCoins(PRIMARY_TEMP_7000),
        EndLoop(),
        ActionQueueSync(target=MARIO, subscript=[ASResetProperties()]),
        Return(),
    ]
)
