# E0005_SET_70A7_TO_RANDOM_TIER_1_CONSUMABLE

from randomizer.scripts.event.script_imports import *

script = EventScript([
	SetVarToRandom(PRIMARY_TEMP_7000, 12),
	JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 1, ["EVENT_5_set_3"]),
	JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 2, ["EVENT_5_set_4"]),
	JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 3, ["EVENT_5_set_5"]),
	JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 4, ["EVENT_5_set_6"]),
	JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 5, ["EVENT_5_set_7"]),
	JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 6, ["EVENT_5_set_8"]),
	JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 7, ["EVENT_5_set_9"]),
	JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 8, ["EVENT_5_set_10"]),
	JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 9, ["EVENT_5_set_11"]),
	JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 10, ["EVENT_5_set_12"]),
	JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 11, ["EVENT_5_set_13"]),
	SetVarToConst(ITEM_ID, Mushroom),
	JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
	SetVarToConst(ITEM_ID, HoneySyrup, identifier="EVENT_5_set_3"),
	JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
	SetVarToConst(ITEM_ID, PickMeUp, identifier="EVENT_5_set_4"),
	JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
	SetVarToConst(ITEM_ID, AbleJuice, identifier="EVENT_5_set_5"),
	JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
	SetVarToConst(ITEM_ID, YoshiCookie, identifier="EVENT_5_set_6"),
	JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
	SetVarToConst(ITEM_ID, PureWater, identifier="EVENT_5_set_7"),
	JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
	SetVarToConst(ITEM_ID, SleepyBomb, identifier="EVENT_5_set_8"),
	JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
	SetVarToConst(ITEM_ID, FroggieDrink, identifier="EVENT_5_set_9"),
	JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
	SetVarToConst(ITEM_ID, WiltShroom, identifier="EVENT_5_set_10"),
	JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
	SetVarToConst(ITEM_ID, RottenMush, identifier="EVENT_5_set_11"),
	JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
	SetVarToConst(ITEM_ID, MoldyMush, identifier="EVENT_5_set_12"),
	JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM),
	SetVarToConst(ITEM_ID, Mushroom2, identifier="EVENT_5_set_13"),
	JmpToEvent(E0160_NPC_QUEST_GRANT_ITEM)
])
