# pylint: disable=C0301

"""E3228_SHIP_CLONE_CONTROL"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        Pause(1, identifier="EVENT_3228_pause_0"),
        JmpIfMarioInAir(["EVENT_3228_clear_bit_16"]),
        Set7000ToTappedButton(),
        JmpIf7000AllBitsClear(bits=[], destinations=["EVENT_3228_clear_bit_16"]),
        JmpIfBitSet(
            TEMP_7044_0, ["EVENT_3228_start_embedded_action_script_sync_F1_15"]
        ),
        Set7000ToObjectCoord(target_npc=MARIO, coord=COORD_X, pixel=True, bit_7=True),
        JmpIfVarNotEqualsConst(
            PRIMARY_TEMP_7000,
            17,
            ["EVENT_3228_start_embedded_action_script_sync_F1_15"],
        ),
        Set7000ToObjectCoord(target_npc=MARIO, coord=COORD_Y, pixel=True, bit_7=True),
        JmpIfVarNotEqualsConst(
            PRIMARY_TEMP_7000,
            121,
            ["EVENT_3228_start_embedded_action_script_sync_F1_15"],
        ),
        SetBit(TEMP_7044_5),
        SetBit(TEMP_7044_0),
        StartSyncEmbeddedActionScript(
            target=NPC_0,
            prefix=0xF1,
            subscript=[ASJumpToHeight(108)],
            identifier="EVENT_3228_start_embedded_action_script_sync_F1_15",
        ),
        ClearBit(TEMP_7044_7, identifier="EVENT_3228_clear_bit_16"),
        Set7000ToPressedButton(),
        JmpIf7000AllBitsClear(
            bits=[], destinations=["EVENT_3228_set_7000_to_pressed_button_20"]
        ),
        SetBit(TEMP_7044_7),
        Set7000ToPressedButton(identifier="EVENT_3228_set_7000_to_pressed_button_20"),
        JmpIf7000AllBitsClear(bits=[], destinations=["EVENT_3228_pause_0"]),
        StartSyncEmbeddedActionScript(
            target=NPC_0,
            prefix=0xF1,
            subscript=[
                ASSetAllSpeeds(NORMAL),
                ASJmpIfBitClear(
                    TEMP_7044_7,
                    [
                        "EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_set_700C_to_object_coord_3"
                    ],
                ),
                ASSetAllSpeeds(FAST),
                ASSet700CToObjectCoord(
                    target_npc=MARIO,
                    coord=COORD_F,
                    pixel=True,
                    identifier="EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_set_700C_to_object_coord_3",
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    0,
                    [
                        "EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_south_pixels_16"
                    ],
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    1,
                    [
                        "EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_southeast_pixels_14"
                    ],
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    2,
                    [
                        "EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_east_pixels_12"
                    ],
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    3,
                    [
                        "EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_northeast_pixels_26"
                    ],
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    4,
                    [
                        "EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_north_pixels_24"
                    ],
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    5,
                    [
                        "EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_northwest_pixels_22"
                    ],
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    6,
                    [
                        "EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_west_pixels_20"
                    ],
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    7,
                    [
                        "EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_southwest_pixels_18"
                    ],
                ),
                ASWalkEastPixels(
                    5,
                    identifier="EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_east_pixels_12",
                ),
                ASReturn(),
                ASWalkSoutheastPixels(
                    3,
                    identifier="EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_southeast_pixels_14",
                ),
                ASReturn(),
                ASWalkSouthPixels(
                    1,
                    identifier="EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_south_pixels_16",
                ),
                ASReturn(),
                ASWalkSouthwestPixels(
                    3,
                    identifier="EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_southwest_pixels_18",
                ),
                ASReturn(),
                ASWalkWestPixels(
                    5,
                    identifier="EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_west_pixels_20",
                ),
                ASReturn(),
                ASWalkNorthwestPixels(
                    3,
                    identifier="EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_northwest_pixels_22",
                ),
                ASReturn(),
                ASWalkNorthPixels(
                    1,
                    identifier="EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_north_pixels_24",
                ),
                ASReturn(),
                ASWalkNortheastPixels(
                    3,
                    identifier="EVENT_3228_start_embedded_action_script_sync_F1_22_SUBSCRIPT_shift_northeast_pixels_26",
                ),
                ASReturn(),
            ],
        ),
        Jmp(["EVENT_3228_pause_0"]),
    ]
)
