# pylint: disable=C0301

"""E2649_CASINO_GRATE_GUY_RANDOM_PRIZE_GRANTER"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        SetVarToRandom(PRIMARY_TEMP_7000, 255),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 0, ["EVENT_2649_run_dialog_84"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 1, ["EVENT_2649_run_dialog_90"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 2, ["EVENT_2649_run_dialog_90"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 3, ["EVENT_2649_run_dialog_96"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 4, ["EVENT_2649_run_dialog_96"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 5, ["EVENT_2649_run_dialog_96"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 6, ["EVENT_2649_run_dialog_102"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 7, ["EVENT_2649_run_dialog_102"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 8, ["EVENT_2649_run_dialog_102"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 9, ["EVENT_2649_run_dialog_102"]),
        SetVarToRandom(PRIMARY_TEMP_7000, 10),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 0, ["EVENT_2649_run_dialog_108"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 1, ["EVENT_2649_run_dialog_114"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 2, ["EVENT_2649_run_dialog_114"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 3, ["EVENT_2649_run_dialog_114"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 4, ["EVENT_2649_run_dialog_120"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 5, ["EVENT_2649_run_dialog_120"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 6, ["EVENT_2649_run_dialog_120"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 7, ["EVENT_2649_run_dialog_126"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 8, ["EVENT_2649_run_dialog_126"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 9, ["EVENT_2649_run_dialog_126"]),
        Jmp(["EVENT_2649_run_dialog_108"]),
        SetVarToConst(ITEM_ID, RockCandy, identifier="EVENT_2649_run_dialog_84"),
        PlaySound(sound=SO027_FOUND_AN_ITEM, channel=6),
        RunDialog(
            dialog_id=DI0524_GOT_A_70A7_AWAIT_TERMINATE,
            above_object=Bowser,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        AddToInventory(RockCandy),
        Jmp(["EVENT_2649_jmp_131"]),
        SetVarToConst(ITEM_ID, RoyalSyrup, identifier="EVENT_2649_run_dialog_90"),
        PlaySound(sound=SO027_FOUND_AN_ITEM, channel=6),
        RunDialog(
            dialog_id=DI0524_GOT_A_70A7_AWAIT_TERMINATE,
            above_object=Bowser,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        AddToInventory(RoyalSyrup),
        Jmp(["EVENT_2649_jmp_131"]),
        SetVarToConst(ITEM_ID, RedEssence, identifier="EVENT_2649_run_dialog_96"),
        PlaySound(sound=SO027_FOUND_AN_ITEM, channel=6),
        RunDialog(
            dialog_id=DI0524_GOT_A_70A7_AWAIT_TERMINATE,
            above_object=Bowser,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        AddToInventory(RedEssence),
        Jmp(["EVENT_2649_jmp_131"]),
        SetVarToConst(ITEM_ID, KerokeroCola, identifier="EVENT_2649_run_dialog_102"),
        PlaySound(sound=SO027_FOUND_AN_ITEM, channel=6),
        RunDialog(
            dialog_id=DI0524_GOT_A_70A7_AWAIT_TERMINATE,
            above_object=Bowser,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        AddToInventory(KerokeroCola),
        Jmp(["EVENT_2649_jmp_131"]),
        SetVarToConst(ITEM_ID, Mushroom, identifier="EVENT_2649_run_dialog_108"),
        PlaySound(sound=SO027_FOUND_AN_ITEM, channel=6),
        RunDialog(
            dialog_id=DI0524_GOT_A_70A7_AWAIT_TERMINATE,
            above_object=Bowser,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        AddToInventory(Mushroom),
        Jmp(["EVENT_2649_jmp_131"]),
        SetVarToConst(ITEM_ID, WiltShroom, identifier="EVENT_2649_run_dialog_114"),
        PlaySound(sound=SO027_FOUND_AN_ITEM, channel=6),
        RunDialog(
            dialog_id=DI0524_GOT_A_70A7_AWAIT_TERMINATE,
            above_object=Bowser,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        AddToInventory(WiltShroom),
        Jmp(["EVENT_2649_jmp_131"]),
        SetVarToConst(ITEM_ID, RottenMush, identifier="EVENT_2649_run_dialog_120"),
        PlaySound(sound=SO027_FOUND_AN_ITEM, channel=6),
        RunDialog(
            dialog_id=DI0524_GOT_A_70A7_AWAIT_TERMINATE,
            above_object=Bowser,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        AddToInventory(RottenMush),
        Jmp(["EVENT_2649_jmp_131"]),
        SetVarToConst(ITEM_ID, MoldyMush, identifier="EVENT_2649_run_dialog_126"),
        PlaySound(sound=SO027_FOUND_AN_ITEM, channel=6),
        RunDialog(
            dialog_id=DI0524_GOT_A_70A7_AWAIT_TERMINATE,
            above_object=Bowser,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        AddToInventory(MoldyMush),
        Return(identifier="EVENT_2649_jmp_131"),
    ]
)
