# E1107_TADPOLE_BRIDGE_JUMPING

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASObjectMemorySetBit(arg_1=0x0B, bits=[3]),
                ASClearSolidityBits(cant_pass_walls=True),
                ASBounceToXYWithHeight(x=12, y=51, height=0),
                ASPause(1),
                ASFaceNortheast(),
                ASPause(1),
            ],
            identifier="EVENT_1107_action_queue_async_0",
        ),
        Jmp(["EVENT_1107_set_7000_to_object_coord_10"]),
        Set7000ToTappedButton(identifier="EVENT_1107_set_7000_to_tapped_button_2"),
        Pause(1),
        JmpIf7000AnyBitsSet(destinations=["EVENT_1107_set_7000_to_pressed_button_6"]),
        Jmp(["EVENT_1107_set_7000_to_tapped_button_2"]),
        Set7000ToPressedButton(identifier="EVENT_1107_set_7000_to_pressed_button_6"),
        JmpIf7000AnyBitsSet(destinations=["EVENT_1107_set_7000_to_object_coord_10"]),
        JmpIf7000AnyBitsSet(destinations=["EVENT_1107_action_queue_async_14"]),
        Jmp(["EVENT_1107_action_queue_async_18"]),
        Set7000ToObjectCoord(
            object=MARIO,
            coord=COORD_X,
            pixel=True,
            bit_7=True,
            identifier="EVENT_1107_set_7000_to_object_coord_10",
        ),
        JmpIfVarEqualsConst(
            PRIMARY_TEMP_7000, 20, ["EVENT_1107_enable_controls_until_return_20"]
        ),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASShadowOn(),
                ASClearSolidityBits(cant_pass_walls=True),
                ASPause(1),
                ASSetWalkingSpeed(FAST),
                ASJumpToHeight(80),
                ASShiftNortheastSteps(2),
                ASSetSolidityBits(cant_pass_walls=True),
                ASShadowOff(),
                ASPause(1),
                ASFaceNortheast(),
                ASPause(1),
                ASReturn(),
            ],
        ),
        Jmp(["EVENT_1107_set_7000_to_tapped_button_2"]),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASPause(1),
                ASShadowOn(),
                ASSetWalkingSpeed(FAST),
                ASJumpToHeight(80),
                ASShiftSouthwestSteps(2),
                ASSetSolidityBits(cant_pass_walls=True),
                ASPause(1),
                ASFaceSouthwest(),
                ASPause(1),
                ASShadowOff(),
                ASReturn(),
            ],
            identifier="EVENT_1107_action_queue_async_14",
        ),
        Set7000ToObjectCoord(object=MARIO, coord=COORD_X, pixel=True, bit_7=True),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 12, ["EVENT_1105_action_queue_sync_49"]),
        Jmp(["EVENT_1107_set_7000_to_tapped_button_2"]),
        ActionQueueAsync(
            target=MARIO,
            subscript=[ASShadowOn(), ASJumpToHeight(80), ASPause(24), ASShadowOff()],
            identifier="EVENT_1107_action_queue_async_18",
        ),
        Jmp(["EVENT_1107_set_7000_to_tapped_button_2"]),
        EnableControlsUntilReturn(
            [], identifier="EVENT_1107_enable_controls_until_return_20"
        ),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASShadowOn(),
                ASClearSolidityBits(cant_pass_walls=True),
                ASSetWalkingSpeed(FAST),
                ASJumpToHeight(128),
                ASShiftNortheastSteps(3),
                ASSetSolidityBits(cant_pass_walls=True),
                ASPause(1),
                ASFaceNortheast(),
                ASResetProperties(),
                ASSetWalkingSpeed(NORMAL),
                ASReturn(),
            ],
        ),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASShadowOn(),
                ASSetWalkingSpeed(NORMAL),
                ASFaceNortheast(),
                ASShiftNortheastPixels(22),
                ASReturn(),
            ],
        ),
        SetSyncActionScript(NPC_7, A0157_MELODY_BAY_TADPOLES),
        Pause(5),
        SetSyncActionScript(NPC_6, A0157_MELODY_BAY_TADPOLES),
        Pause(5),
        SetSyncActionScript(NPC_5, A0157_MELODY_BAY_TADPOLES),
        Pause(5),
        SetSyncActionScript(NPC_4, A0157_MELODY_BAY_TADPOLES),
        Pause(5),
        SetSyncActionScript(NPC_3, A0157_MELODY_BAY_TADPOLES),
        Pause(5),
        SetSyncActionScript(NPC_2, A0157_MELODY_BAY_TADPOLES),
        Pause(5),
        SetSyncActionScript(NPC_1, A0157_MELODY_BAY_TADPOLES),
        Pause(5),
        SetSyncActionScript(NPC_0, A0157_MELODY_BAY_TADPOLES),
        Pause(5),
        EnableControlsUntilReturn([LEFT, RIGHT, DOWN, UP, X, A, Y, B]),
        SetAsyncActionScript(MARIO, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        ClearBit(TEMP_7043_1),
        Return(),
    ]
)
