# pylint: disable=C0301

"""E3329_JUMPING_FIREBALLS"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        Pause(1, identifier="EVENT_3329_pause_0"),
        Set7000ToObjectCoord(target_npc=MARIO, coord=COORD_Z, pixel=True),
        JmpIfVarNotEqualsConst(PRIMARY_TEMP_7000, 0, ["EVENT_3329_pause_0"]),
        JmpIfBitSet(TEMP_7076_0, ["EVENT_3329_pause_0"]),
        EnableControls([]),
        ClearBit(TEMP_7044_4),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASJmp(["EVENT_3329_non_embedded_action_queue_9"]),
                ASSetSolidityBits(
                    cant_pass_npcs=True,
                    bit_7=True,
                    identifier="EVENT_3329_action_queue_async_6_SUBSCRIPT_set_solidity_bits_1",
                ),
                ASSetBit(TEMP_7044_4),
                ASSetWalkingSpeed(NORMAL),
                ASJumpToHeight(height=96, silent=True),
                ASPause(8),
                ASPause(
                    1, identifier="EVENT_3329_action_queue_async_6_SUBSCRIPT_pause_6"
                ),
                ASJmpIfMarioInAir(
                    ["EVENT_3329_action_queue_async_6_SUBSCRIPT_pause_6"]
                ),
                ASResetProperties(),
                ASSet700CToObjectCoord(target_npc=NPC_0, coord=COORD_F, pixel=True),
                ASFaceEast7C(),
                ASPause(1),
                ASDb(bytearray(b"\xfd\x9c:")),
            ],
        ),
        EnableControls([LEFT, RIGHT, DOWN, UP, X, A, Y, B]),
        Jmp(["EVENT_3329_pause_0"]),
        NonEmbeddedActionQueue(
            subscript=[
                ASFaceSouthwest7D(),
                ASSet700CToObjectCoord(
                    target_npc=DUMMY_0X07, coord=COORD_F, pixel=True
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    7,
                    [
                        "EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_set_sprite_sequence_10"
                    ],
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    0,
                    [
                        "EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_set_sprite_sequence_10"
                    ],
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    1,
                    [
                        "EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_set_sprite_sequence_12"
                    ],
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    2,
                    [
                        "EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_set_sprite_sequence_12"
                    ],
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    3,
                    [
                        "EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_set_sprite_sequence_14"
                    ],
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    4,
                    [
                        "EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_set_sprite_sequence_16"
                    ],
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    5,
                    [
                        "EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_set_sprite_sequence_16"
                    ],
                ),
                ASJmpIfVarEqualsConst(
                    PRIMARY_TEMP_700C,
                    6,
                    [
                        "EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_set_sprite_sequence_16"
                    ],
                ),
                ASSetSpriteSequence(
                    index=9,
                    sprite_offset=3,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                    identifier="EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_set_sprite_sequence_10",
                ),
                ASJmp(["EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_db_17"]),
                ASSetSpriteSequence(
                    index=8,
                    sprite_offset=3,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                    identifier="EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_set_sprite_sequence_12",
                ),
                ASJmp(["EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_db_17"]),
                ASSetSpriteSequence(
                    index=8,
                    sprite_offset=3,
                    is_sequence=True,
                    looping=True,
                    identifier="EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_set_sprite_sequence_14",
                ),
                ASJmp(["EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_db_17"]),
                ASSetSpriteSequence(
                    index=9,
                    sprite_offset=3,
                    is_sequence=True,
                    looping=True,
                    identifier="EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_set_sprite_sequence_16",
                ),
                ASDb(
                    bytearray(b"\xfd\x9ci"),
                    identifier="EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_db_17",
                ),
                ASJmpIfObjectWithinRange(
                    comparing_npc=NPC_0,
                    usually=0,
                    tiles=8,
                    destinations=[
                        "EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_jump_to_height_silent_27"
                    ],
                ),
                ASJmpIfObjectWithinRange(
                    comparing_npc=NPC_0,
                    usually=0,
                    tiles=16,
                    destinations=[
                        "EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_jump_to_height_silent_25"
                    ],
                ),
                ASJmpIfObjectWithinRange(
                    comparing_npc=NPC_0,
                    usually=0,
                    tiles=28,
                    destinations=[
                        "EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_jump_to_height_silent_23"
                    ],
                ),
                ASJumpToHeight(height=384, silent=True),
                ASJmp(
                    [
                        "EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_create_packet_at_npc_coords_28"
                    ]
                ),
                ASJumpToHeight(
                    height=320,
                    silent=True,
                    identifier="EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_jump_to_height_silent_23",
                ),
                ASJmp(
                    [
                        "EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_create_packet_at_npc_coords_28"
                    ]
                ),
                ASJumpToHeight(
                    height=256,
                    silent=True,
                    identifier="EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_jump_to_height_silent_25",
                ),
                ASJmp(
                    [
                        "EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_create_packet_at_npc_coords_28"
                    ]
                ),
                ASJumpToHeight(
                    height=192,
                    silent=True,
                    identifier="EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_jump_to_height_silent_27",
                ),
                ASCreatePacketAtObjectCoords(
                    packet=P047_BLUE_FIRE_TRAIL,
                    target_npc=MARIO,
                    destinations=[
                        "EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_clear_solidity_bits_29"
                    ],
                    identifier="EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_create_packet_at_npc_coords_28",
                ),
                ASClearSolidityBits(
                    cant_pass_npcs=True,
                    bit_7=True,
                    identifier="EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_clear_solidity_bits_29",
                ),
                ASPause(4),
                ASClearSolidityBits(cant_pass_walls=True),
                ASDb(bytearray(b"\xc8\x14")),
                ASDb(bytearray(b"\xfd\xc7")),
                ASSetWalkingSpeed(VERY_FAST),
                ASRunAwayShift(),
                ASSetSolidityBits(cant_pass_walls=True),
                ASPause(
                    1,
                    identifier="EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_pause_37",
                ),
                ASJmpIfMarioInAir(
                    ["EVENT_3329_non_embedded_action_queue_9_SUBSCRIPT_pause_37"]
                ),
                ASJmp(
                    ["EVENT_3329_action_queue_async_6_SUBSCRIPT_set_solidity_bits_1"]
                ),
            ],
            identifier="EVENT_3329_non_embedded_action_queue_9",
        ),
    ]
)
