# E1645_BUCKET_GIRL

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        JmpIfBitSet(BUCKET_PRIZE_GRANT_NO_WARP, ["EVENT_1645_run_dialog_29_"]),
        CopyVarToVar(from_var=ACTIVE_NPC, to_var=PRIMARY_TEMP_7000),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=TEMP_70AE),
        StoreItemAmountTo7000(CarboCookie),
        JmpIfVarNotEqualsConst(PRIMARY_TEMP_7000, 0, ["EVENT_1645_run_dialog_6"]),
        RunDialog(
            dialog_id=DI1146_WISH_I_HAD_CARBO_COOKIE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
        ),
        Return(),
        RunDialog(
            dialog_id=DI1147_CARBO_COOKIE_PROMPT,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_1645_run_dialog_6",
        ),
        JmpIfDialogOptionBSelected(["EVENT_1645_pause_27"]),
        Pause(10),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        RemoveOneOfItemFromInventory(CarboCookie),
        JmpIfBitClear(BUCKET_WARP_ENABLED, ["EVENT_1645_check_trade_type"]),
        JmpIfBitSet(
            FIRST_CARBO_COOKIE_GIVEN,
            ["EVENT_1645_run_dialog_21"],
            identifier="EVENT_1645_jmp_if_bit_set_11",
        ),
        RunDialog(
            dialog_id=DI1149_BUCKET_GIRL_LEAVES,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
        ),
        SetBit(FIRST_CARBO_COOKIE_GIVEN),
        ActionQueueAsync(
            target=MEM_70A8,
            subscript=[
                ASPlaySound(sound=SO004_JUMP, channel=4),
                ASClearSolidityBits(
                    bit_4=True, cant_pass_npcs=True, cant_walk_through=True, bit_7=True
                ),
                ASJumpToHeight(80),
                ASSetAllSpeeds(NORMAL),
                ASFaceSoutheast(),
                ASFixedFCoordOn(),
                ASShiftSouthSteps(2),
                ASJmpIfBitSet(BUCKET_GIRL_DIALOG, ["EVENT_1645_jmp_if_bit_set_15"]),
                ASFixedFCoordOff(),
                ASFaceMario(),
                ASPause(1),
            ],
        ),
        JmpIfBitSet(
            BUCKET_GIRL_DIALOG,
            ["EVENT_1645_action_queue_async_18"],
            identifier="EVENT_1645_jmp_if_bit_set_15",
        ),
        RunDialog(
            dialog_id=DI1232_DONT_TAKE_MY_BUCKET,
            above_object=NPC_12,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        SetBit(BUCKET_GIRL_DIALOG),
        ActionQueueAsync(
            target=MEM_70A8,
            subscript=[
                ASSetAllSpeeds(FAST),
                ASShiftSoutheastSteps(9),
                ASVisibilityOff(),
            ],
            identifier="EVENT_1645_action_queue_async_18",
        ),
        JmpIfBitSet(PROGRESSIVE_FIREWORKS_ENABLED, ["EVENT_1645_remove_bucket_girl"]),
        JmpIfBitSet(SHUFFLE_ONE_FIREWORKS_ENABLED, ["EVENT_1645_remove_bucket_girl"]),
        Return(),
        RemoveObjectFromCurrentLevel(
            MEM_70A8, identifier="EVENT_1645_remove_bucket_girl"
        ),
        RemoveObjectFromSpecificLevel(MEM_70A8, R108_MOLEVILLE_OUTSIDE),
        Return(),
        RunDialog(
            dialog_id=DI1150_BUCKET_GIRL_GRANT,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_1645_run_dialog_21",
        ),
        PlaySound(sound=SO094_FROG_COIN, channel=6),
        AddFrogCoins(1),
        RunDialog(
            dialog_id=DI1176_RECEIVED_A_FROG_COIN,
            above_object=BOWSER,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        ClearBit(FIRST_CARBO_COOKIE_GIVEN),
        Return(),
        Pause(10, identifier="EVENT_1645_pause_27"),
        SetAsyncActionScript(MARIO, A0671_SHAKE_HEAD_NO),
        RunDialog(
            dialog_id=DI1148_CARBO_COOKIE_DECLINE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
        ),
        Return(),
        JmpIfBitSet(
            PROGRESSIVE_FIREWORKS_ENABLED,
            ["EVENT_1645_bucket_grant"],
            identifier="EVENT_1645_check_trade_type",
        ),
        JmpIfBitSet(SHUFFLE_ONE_FIREWORKS_ENABLED, ["EVENT_1645_bucket_grant"]),
        Jmp(["EVENT_1645_jmp_if_bit_set_11"]),
        RunEventAsSubroutine(
            E0178_NPC_QUEST_1_CONTAINER, identifier="EVENT_1645_bucket_grant"
        ),
        SetBit(BUCKET_PRIZE_GRANT_NO_WARP),
        Return(),
        RunDialog(
            dialog_id=DI1151_THANKS_HONORIFIC,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_1645_run_dialog_29_",
        ),
        Return(),
    ]
)
