# E1339_PORTRAIT_GAME_ROOM_LOADER

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        ActionQueueSync(
            target=NPC_15,
            subscript=[
                ASShiftSoutheastPixels(8),
                ASSetSpriteSequence(index=1, is_sequence=True, looping=True),
                ASShadowOff(),
                ASSetVRAMPriority(NORMAL_PRIORITY),
                ASSetPriority(3),
            ],
        ),
        ActionQueueSync(
            target=NPC_14, subscript=[ASShiftNorthwestPixels(8), ASFaceSouthwest()]
        ),
        ActionQueueSync(
            target=NPC_0,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASShadowOff(),
                ASSetPriority(0),
                ASSetVRAMPriority(MARIO_OVERLAPS_ON_ALL_SIDES),
                ASSetSequenceSpeed(FAST),
                ASSequenceLoopingOn(),
            ],
        ),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASShadowOff(),
                ASSetPriority(0),
                ASSetVRAMPriority(MARIO_OVERLAPS_ON_ALL_SIDES),
                ASSetSequenceSpeed(FAST),
                ASSequenceLoopingOn(),
            ],
        ),
        ActionQueueSync(
            target=NPC_2,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASShadowOff(),
                ASSetPriority(0),
                ASSetVRAMPriority(MARIO_OVERLAPS_ON_ALL_SIDES),
                ASSetSequenceSpeed(FAST),
                ASSequenceLoopingOn(),
            ],
        ),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASShadowOff(),
                ASSetPriority(0),
                ASSetVRAMPriority(MARIO_OVERLAPS_ON_ALL_SIDES),
                ASSetSequenceSpeed(FAST),
                ASSequenceLoopingOn(),
            ],
        ),
        ActionQueueSync(
            target=NPC_4,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASShadowOff(),
                ASSetPriority(0),
                ASSetVRAMPriority(MARIO_OVERLAPS_ON_ALL_SIDES),
                ASSetSequenceSpeed(FAST),
                ASSequenceLoopingOn(),
            ],
        ),
        ActionQueueAsync(
            target=NPC_5,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASShadowOff(),
                ASSetPriority(0),
                ASSetVRAMPriority(MARIO_OVERLAPS_ON_ALL_SIDES),
                ASSetSequenceSpeed(FAST),
                ASSequenceLoopingOn(),
            ],
        ),
        RunEventAsSubroutine(
            E0791_TOWER_ANCESTOR_GAME_ROOM_SHUFFLED_NPC_ANIMATION_LOADER
        ),
        JmpIfBitSet(PORTRAIT_GAME_COMPLETED, ["EVENT_1339_set_bit_18"]),
        SetVarToConst(SECONDARY_TEMP_7024, 0),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R195_BOOSTER_TOWER_6F_AREA_02_BOOSTERS_ANCESTOR_GAME_ROOM,
            mod_id=34,
        ),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R195_BOOSTER_TOWER_6F_AREA_02_BOOSTERS_ANCESTOR_GAME_ROOM,
            mod_id=38,
        ),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R195_BOOSTER_TOWER_6F_AREA_02_BOOSTERS_ANCESTOR_GAME_ROOM,
            mod_id=42,
        ),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R195_BOOSTER_TOWER_6F_AREA_02_BOOSTERS_ANCESTOR_GAME_ROOM,
            mod_id=46,
        ),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R195_BOOSTER_TOWER_6F_AREA_02_BOOSTERS_ANCESTOR_GAME_ROOM,
            mod_id=50,
        ),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R195_BOOSTER_TOWER_6F_AREA_02_BOOSTERS_ANCESTOR_GAME_ROOM,
            mod_id=54,
        ),
        FadeInFromBlack(sync=False),
        Return(),
        SetBit(TEMP_7043_0, identifier="EVENT_1339_set_bit_18"),
        SetBit(TEMP_7043_1),
        SetBit(TEMP_7043_2),
        SetBit(TEMP_7043_3),
        SetBit(TEMP_7043_4),
        SetBit(TEMP_7043_5),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R195_BOOSTER_TOWER_6F_AREA_02_BOOSTERS_ANCESTOR_GAME_ROOM,
            mod_id=36,
        ),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R195_BOOSTER_TOWER_6F_AREA_02_BOOSTERS_ANCESTOR_GAME_ROOM,
            mod_id=40,
        ),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R195_BOOSTER_TOWER_6F_AREA_02_BOOSTERS_ANCESTOR_GAME_ROOM,
            mod_id=44,
        ),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R195_BOOSTER_TOWER_6F_AREA_02_BOOSTERS_ANCESTOR_GAME_ROOM,
            mod_id=48,
        ),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R195_BOOSTER_TOWER_6F_AREA_02_BOOSTERS_ANCESTOR_GAME_ROOM,
            mod_id=52,
        ),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R195_BOOSTER_TOWER_6F_AREA_02_BOOSTERS_ANCESTOR_GAME_ROOM,
            mod_id=56,
        ),
        FadeInFromBlack(sync=False),
        Return(),
    ]
)
