# pylint: disable=C0301

"""E3644_NIMBUS_INNKEEPER"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        SetVarToConst(TEMP_70AE, 20),
        SetVarToConst(SECONDARY_TEMP_7024, 30),
        JmpIfBitSet(TEMP_7042_4, ["EVENT_3644_run_dialog_186"]),
        JmpIfBitSet(TEMP_7042_5, ["EVENT_3644_run_dialog_186"]),
        JmpIfBitSet(TEMP_7042_6, ["EVENT_3644_run_dialog_186"]),
        JmpIfBitSet(TEMP_7042_7, ["EVENT_3644_run_dialog_186"]),
        JmpIfBitSet(TEMP_7042_3, ["EVENT_3644_run_dialog_186"]),
        RunDialog(
            dialog_id=DI3729_NIMBUS_INNKEEPER,
            above_object=MEM_70A8,
            closable=False,
            sync=False,
            multiline=True,
            use_background=True),
        JmpIfDialogOptionBSelected(["EVENT_3644_pause_171"]),
        Pause(10),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        RunEventAsSubroutine(E0274_CHECK_IF_HAVE_ENOUGH_COINS),
        JmpIfBitSet(INSUFFICIENT_COINS, ["EVENT_3644_clear_bit_175"]),
        CopyVarToVar(from_var=SECONDARY_TEMP_7024, to_var=PRIMARY_TEMP_7000),
        Dec7000FromCoins(),
        SetBit(NIMBUS_INN),
        RunDialog(
            dialog_id=DI3730_DREAM_CUSHION_PROMPT,
            above_object=MEM_70A8,
            closable=False,
            sync=False,
            multiline=True,
            use_background=True),
        JmpIfDialogOptionBSelected(["EVENT_3644_pause_181"]),
        Pause(10),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        RunEventAsSubroutine(E0274_CHECK_IF_HAVE_ENOUGH_COINS),
        JmpIfBitSet(INSUFFICIENT_COINS, ["EVENT_3644_clear_bit_178"]),
        CopyVarToVar(from_var=SECONDARY_TEMP_7024, to_var=PRIMARY_TEMP_7000),
        Dec7000FromCoins(),
        FadeOutMusicToVolume(duration=2, volume=0),
        CircleMaskShrinkToObject(target=MARIO, width=18, speed=3, static=True),
        Pause(10),
        PlaySound(sound=SO054_GOODNIGHT, channel=6),
        Pause(50),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASSetSpriteSequence(
                    index=30,
                    sprite_offset=2,
                    is_mold=True,
                    is_sequence=True,
                    looping=True)
            ]),
        Pause(60),
        CircleMaskShrinkToObject(target=MARIO, width=0, speed=1, static=True),
        PauseScriptUntilEffectDone(),
        JmpIfBitClear(NIMBUS_INN_PRIZE_GRANTED, ["EVENT_3644_set_bit_55"]),
        SetVarToRandom(PRIMARY_TEMP_7000, 51),
        CompareVarToConst(PRIMARY_TEMP_7000, 45),
        JmpIfComparisonResultIsGreaterOrEqual(["EVENT_3644_jmp_if_bit_set_54"]),
        CompareVarToConst(PRIMARY_TEMP_7000, 41),
        JmpIfComparisonResultIsGreaterOrEqual(["EVENT_3644_set_bit_161"]),
        CompareVarToConst(PRIMARY_TEMP_7000, 34),
        JmpIfComparisonResultIsGreaterOrEqual(["EVENT_3644_set_bit_145"]),
        CompareVarToConst(PRIMARY_TEMP_7000, 17),
        JmpIfComparisonResultIsGreaterOrEqual(
            ["EVENT_3644_set_7000_to_70A0_short_mem_76"]
        ),
        SetBit(TEMP_7042_4),
        EnterArea(
            room_id=R504_NIMBUS_LAND_DREAM_CUSHION_DREAM_TORTES_ARE_SEASONING_MARIO,
            face_direction=SOUTH,
            x=26,
            y=84,
            z=1),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASFloatingOff(),
                ASShadowOff(),
                ASSetSpriteSequence(index=13, is_sequence=True, looping=True),
                ASTransferXYZFPixels(x=0, y=6, z=0, direction=EAST),
            ]),
        ActionQueueSync(target=NPC_5, subscript=[ASSetPriority(3)]),
        ActionQueueSync(target=NPC_3, subscript=[ASSetPriority(3)]),
        FadeInFromBlack(sync=True, duration=120),
        PauseScriptUntilEffectDone(),
        Pause(240),
        FadeOutToBlack(sync=True, duration=90),
        PauseScriptUntilEffectDone(),
        JmpToEvent(E0736_ROSE_TOWN_INN_SLEEP_SUBROUTINE),
        JmpIfBitSet(
            NIMBUS_INN_PRIZE_GRANTED,
            ["EVENT_3644_set_bit_161"],
            identifier="EVENT_3644_jmp_if_bit_set_54"),
        SetBit(TEMP_7042_5, identifier="EVENT_3644_set_bit_55"),
        EnterArea(
            room_id=R502_NIMBUS_LAND_DREAM_CUSHION_DREAM_SMALL_CLOUD_PERSON_CHEERS_ON_MARIOBED_FLOATS,
            face_direction=SOUTH,
            x=23,
            y=20,
            z=0),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASFloatingOff(),
                ASSetSpriteSequence(index=13, is_sequence=True, looping=True),
                ASTransferXYZFPixels(x=8, y=248, z=0, direction=EAST),
            ]),
        ActionQueueAsync(
            target=LAYER_1,
            subscript=[
                ASSetWalkingSpeed(FASTEST),
                ASWalkEastSteps(7),
                ASWalkEastPixels(8),
            ]),
        SummonObjectToCurrentLevel(NPC_4),
        SetSyncActionScript(NPC_4, A0099_LOOPED_JUMPING),
        FadeInFromBlack(sync=True, duration=120),
        PauseScriptUntilEffectDone(),
        Pause(120),
        SetBit(TEMP_7043_1),
        Pause(30),
        ActionQueueSync(
            target=NPC_4,
            subscript=[
                ASStartLoopNTimes(3),
                ASVisibilityOff(),
                ASPause(4),
                ASVisibilityOn(),
                ASPause(4),
                ASEndLoop(),
                ASStartLoopNTimes(3),
                ASVisibilityOff(),
                ASPause(2),
                ASVisibilityOn(),
                ASPause(2),
                ASEndLoop(),
                ASStartLoopNTimes(3),
                ASVisibilityOff(),
                ASPause(1),
                ASVisibilityOn(),
                ASPause(1),
                ASEndLoop(),
                ASVisibilityOff(),
            ]),
        ActionQueueSync(
            target=NPC_5,
            subscript=[
                ASPause(32),
                ASStartLoopNTimes(3),
                ASVisibilityOn(),
                ASPause(1),
                ASVisibilityOff(),
                ASPause(1),
                ASEndLoop(),
                ASEndLoop(),
                ASStartLoopNTimes(3),
                ASVisibilityOn(),
                ASPause(2),
                ASVisibilityOff(),
                ASPause(2),
                ASEndLoop(),
                ASPlaySound(sound=SO044_GHOST_FLOAT, channel=4),
                ASStartLoopNTimes(3),
                ASVisibilityOn(),
                ASPause(4),
                ASVisibilityOff(),
                ASPause(4),
                ASEndLoop(),
                ASVisibilityOn(),
            ]),
        RememberLastObject(),
        FadeOutToBlack(sync=True, duration=90),
        PauseScriptUntilEffectDone(),
        SetBit(TEMP_704C_0),
        JmpToEvent(E0736_ROSE_TOWN_INN_SLEEP_SUBROUTINE),
        CopyVarToVar(
            from_var=NIMBUS_INN_COUNTER,
            to_var=PRIMARY_TEMP_7000,
            identifier="EVENT_3644_set_7000_to_70A0_short_mem_76"),
        CompareVarToConst(PRIMARY_TEMP_7000, 4),
        JmpIfComparisonResultIsGreaterOrEqual(["EVENT_3644_set_bit_161"]),
        SetBit(TEMP_7042_6),
        EnterArea(
            room_id=R502_NIMBUS_LAND_DREAM_CUSHION_DREAM_SMALL_CLOUD_PERSON_CHEERS_ON_MARIOBED_FLOATS,
            face_direction=SOUTH,
            x=23,
            y=20,
            z=0),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASFloatingOff(),
                ASSetSpriteSequence(index=13, is_sequence=True, looping=True),
                ASTransferXYZFPixels(x=8, y=248, z=0, direction=EAST),
            ]),
        ActionQueueAsync(
            target=LAYER_1,
            subscript=[
                ASSetWalkingSpeed(FASTEST),
                ASWalkEastSteps(7),
                ASWalkEastPixels(8),
            ]),
        SetVarToRandom(PRIMARY_TEMP_7000, 4),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 3, ["EVENT_3644_jmp_if_bit_set_101"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 2, ["EVENT_3644_jmp_if_bit_set_114"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 1, ["EVENT_3644_jmp_if_bit_set_128"]),
        JmpIfBitSet(NIMBUS_INN_UNKNOWN_1, ["EVENT_3644_set_7000_to_70A0_short_mem_76"]),
        SetBit(NIMBUS_INN_UNKNOWN_1),
        Inc(NIMBUS_INN_COUNTER),
        SummonObjectToCurrentLevel(NPC_0),
        FadeInFromBlack(sync=True, duration=120),
        PauseScriptUntilEffectDone(),
        Pause(60),
        SetAsyncActionScript(NPC_0, A0636_54_VELOCITY_SINGLE_JUMP),
        Pause(10),
        RunDialog(
            dialog_id=DI3803_DREAM_GAZ,
            above_object=BOWSER,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False),
        Pause(10),
        FadeOutToBlack(sync=True, duration=90),
        PauseScriptUntilEffectDone(),
        JmpToEvent(E0736_ROSE_TOWN_INN_SLEEP_SUBROUTINE),
        JmpIfBitSet(
            NIMBUS_INN_UNKNOWN_2,
            ["EVENT_3644_set_7000_to_70A0_short_mem_76"],
            identifier="EVENT_3644_jmp_if_bit_set_101"),
        SetBit(NIMBUS_INN_UNKNOWN_2),
        Inc(NIMBUS_INN_COUNTER),
        SummonObjectToCurrentLevel(NPC_3),
        FadeInFromBlack(sync=True, duration=120),
        PauseScriptUntilEffectDone(),
        Pause(60),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASSetSpriteSequence(
                    index=20,
                    sprite_offset=2,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
                ASPlaySound(sound=SO063_YOSHI_TALK, channel=4),
                ASPause(10),
                ASResetProperties(),
            ]),
        RunDialog(
            dialog_id=DI3804_DREAM_YOSHI,
            above_object=BOWSER,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False),
        Pause(10),
        FadeOutToBlack(sync=True, duration=90),
        PauseScriptUntilEffectDone(),
        JmpToEvent(E0736_ROSE_TOWN_INN_SLEEP_SUBROUTINE),
        JmpIfBitSet(
            NIMBUS_INN_UNKNOWN_3,
            ["EVENT_3644_set_7000_to_70A0_short_mem_76"],
            identifier="EVENT_3644_jmp_if_bit_set_114"),
        SetBit(NIMBUS_INN_UNKNOWN_3),
        Inc(NIMBUS_INN_COUNTER),
        SummonObjectToCurrentLevel(NPC_1),
        ActionQueueAsync(
            target=NPC_1,
            subscript=[
                ASSetSpriteSequence(
                    index=7,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True)
            ]),
        FadeInFromBlack(sync=True, duration=120),
        PauseScriptUntilEffectDone(),
        Pause(60),
        ActionQueueAsync(
            target=NPC_1,
            subscript=[
                ASResetProperties(),
                ASPause(60),
                ASStartLoopNTimes(1),
                ASSetSpriteSequence(
                    index=6,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
                ASPause(8),
                ASResetProperties(),
                ASPause(8),
                ASEndLoop(),
            ]),
        RunDialog(
            dialog_id=DI3805_DREAM_CHANCELLOR,
            above_object=BOWSER,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False),
        Pause(10),
        FadeOutToBlack(sync=True, duration=90),
        PauseScriptUntilEffectDone(),
        JmpToEvent(E0736_ROSE_TOWN_INN_SLEEP_SUBROUTINE),
        JmpIfBitSet(
            NIMBUS_INN_UNKNOWN_4,
            ["EVENT_3644_set_7000_to_70A0_short_mem_76"],
            identifier="EVENT_3644_jmp_if_bit_set_128"),
        SetBit(NIMBUS_INN_UNKNOWN_4),
        Inc(NIMBUS_INN_COUNTER),
        SummonObjectToCurrentLevel(NPC_2),
        SetSyncActionScript(NPC_2, A0099_LOOPED_JUMPING),
        FadeInFromBlack(sync=True, duration=120),
        PauseScriptUntilEffectDone(),
        Pause(60),
        RunDialog(
            dialog_id=DI3806_DREAM_JUMPING_KID,
            above_object=BOWSER,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False),
        SetBit(TEMP_7043_1),
        Pause(30),
        SetSyncActionScript(NPC_2, A0023_FAST_REPEATED_JUMPING),
        RunDialog(
            dialog_id=DI3807_DREAM,
            above_object=BOWSER,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False),
        Pause(10),
        FadeOutToBlack(sync=True, duration=90),
        PauseScriptUntilEffectDone(),
        JmpToEvent(E0736_ROSE_TOWN_INN_SLEEP_SUBROUTINE),
        SetBit(TEMP_7042_7, identifier="EVENT_3644_set_bit_145"),
        EnterArea(
            room_id=R502_NIMBUS_LAND_DREAM_CUSHION_DREAM_SMALL_CLOUD_PERSON_CHEERS_ON_MARIOBED_FLOATS,
            face_direction=SOUTH,
            x=22,
            y=19,
            z=0),
        FreezeCamera(),
        ActionQueueSync(
            target=SCREEN_FOCUS,
            subscript=[ASSetWalkingSpeed(FASTEST), ASWalkEastPixels(16)]),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASTransferToXYZF(x=30, y=19, z=2, direction=EAST),
                ASSetSpriteSequence(index=13, is_sequence=True, looping=True),
                ASShadowOff(),
            ]),
        RememberLastObject(),
        FadeInFromBlack(sync=True, duration=120),
        PauseScriptUntilEffectDone(),
        ActionQueueSync(
            target=LAYER_1,
            subscript=[
                ASSetWalkingSpeed(SLOW),
                ASDb(bytearray(b" \x04")),
                ASEmbeddedAnimationRoutine(
                    bytearray(
                        b"(\x00\x00\x00\x00\x00\xc0\x00\x03\x00\x01\x00\x00\x00\x08\x80"
                    )
                ),
                ASWalkEastSteps(7),
                ASWalkEastPixels(16),
                ASBPL262728(),
            ]),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASSetWalkingSpeed(SLOW),
                ASFloatingOff(),
                ASClearSolidityBits(cant_pass_walls=True),
                ASSetPriority(3),
                ASDb(bytearray(b" \x04")),
                ASEmbeddedAnimationRoutine(
                    bytearray(
                        b"(\x00\x00\x00\x00\x00@\x00\x03\x00\x01\x00\x00\x00\x08\x80"
                    )
                ),
                ASWalkWestSteps(7),
                ASWalkWestPixels(16),
                ASBPL262728(),
            ]),
        Pause(120),
        ActionQueueSync(
            target=LAYER_1,
            subscript=[
                ASDb(bytearray(b" \x04")),
                ASEmbeddedAnimationRoutine(
                    bytearray(
                        b"(\x00\x00\x00\x00\x00\xc0\x00\x03\x00\x01\x00\x00\x00\x08\x80"
                    )
                ),
                ASWalkEastSteps(6),
                ASBPL262728(),
            ]),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASDb(bytearray(b" \x04")),
                ASEmbeddedAnimationRoutine(
                    bytearray(
                        b"(\x00\x00\x00\x00\x00@\x00\x03\x00\x01\x00\x00\x00\x08\x80"
                    )
                ),
                ASWalkWestSteps(6),
                ASBPL262728(),
            ]),
        FadeOutToBlack(sync=True, duration=90),
        PauseScriptUntilEffectDone(),
        JmpToEvent(E0736_ROSE_TOWN_INN_SLEEP_SUBROUTINE),
        SetBit(TEMP_7042_3, identifier="EVENT_3644_set_bit_161"),
        EnterArea(
            room_id=R503_NIMBUS_LAND_DREAM_CUSHION_DREAM_HEAVY_TROOPA_LAYING_ON_MARIO,
            face_direction=SOUTH,
            x=25,
            y=52,
            z=1),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASFloatingOff(),
                ASShadowOff(),
                ASTransferToXYZF(x=25, y=52, z=2, direction=EAST),
                ASSetSpriteSequence(index=13, is_sequence=True, looping=True),
                ASTransferXYZFPixels(x=4, y=248, z=0, direction=EAST),
                ASSetVRAMPriority(MARIO_OVERLAPS_ON_ALL_SIDES),
            ]),
        ActionQueueSync(
            target=NPC_2,
            subscript=[
                ASTransferXYZFPixels(x=248, y=4, z=0, direction=EAST),
                ASSequenceLoopingOn(),
                ASSetVRAMPriority(OBJECT_OVERLAPS_MARIO_ON_ALL_SIDES),
                ASPause(240),
                ASSetSpriteSequence(
                    index=4, is_sequence=True, looping=True, mirror_sprite=True
                ),
                ASPause(50),
                ASSetSequenceSpeed(NORMAL),
                ASSetSpriteSequence(
                    index=0, is_sequence=True, looping=True, mirror_sprite=True
                ),
            ]),
        FadeInFromBlack(sync=True, duration=120),
        PauseScriptUntilEffectDone(),
        Pause(240),
        FadeOutToBlack(sync=True, duration=90),
        PauseScriptUntilEffectDone(),
        JmpToEvent(E0736_ROSE_TOWN_INN_SLEEP_SUBROUTINE),
        Pause(10, identifier="EVENT_3644_pause_171"),
        SetAsyncActionScript(MARIO, A0671_SHAKE_HEAD_NO),
        Return(),
        ClearBit(INSUFFICIENT_COINS, identifier="EVENT_3644_clear_bit_175"),
        RunDialog(
            dialog_id=DI3731_NIMBUS_INN_INSUFFICIENT_COINS,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        Return(),
        ClearBit(INSUFFICIENT_COINS, identifier="EVENT_3644_clear_bit_178"),
        RunDialog(
            dialog_id=DI3774_NIMBUS_INN_INSUFFICIENT_COINS,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        JmpToEvent(E0280_SLEEP_IN_NIMBUS_INN),
        Pause(10, identifier="EVENT_3644_pause_181"),
        SetAsyncActionScript(MARIO, A0671_SHAKE_HEAD_NO),
        JmpToEvent(E0280_SLEEP_IN_NIMBUS_INN),
        Return(),
        RunDialog(
            dialog_id=DI3767_DUPLICATE,
            above_object=MEM_70A8,
            closable=False,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_3644_run_dialog_186"),
        JmpIfBitSet(TEMP_7042_4, ["EVENT_3644_run_dialog_192"]),
        JmpIfBitSet(TEMP_7042_6, ["EVENT_3644_run_dialog_194"]),
        JmpIfBitSet(TEMP_7042_7, ["EVENT_3644_run_dialog_196"]),
        RunDialog(
            dialog_id=DI3769_NIMBUS_INNKEEPER_AFTER_DREAM_CUSHION,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        Jmp(["EVENT_3644_clear_bit_197"]),
        RunDialog(
            dialog_id=DI3768_NIMBUS_INNKEEPER_AFTER_DREAM_CUSHION,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_3644_run_dialog_192"),
        Jmp(["EVENT_3644_clear_bit_197"]),
        RunDialog(
            dialog_id=DI3770_NIMBUS_INNKEEPER_AFTER_DREAM_CUSHION,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_3644_run_dialog_194"),
        Jmp(["EVENT_3644_clear_bit_197"]),
        RunDialog(
            dialog_id=DI3771_NIMBUS_INNKEEPER_AFTER_DREAM_CUSHION,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_3644_run_dialog_196"),
        ClearBit(TEMP_7042_4, identifier="EVENT_3644_clear_bit_197"),
        ClearBit(TEMP_7042_5),
        ClearBit(TEMP_7042_6),
        ClearBit(TEMP_7042_7),
        ClearBit(TEMP_7042_3),
        Return(),
    ]
)
