# pylint: disable=C0301

"""E2295_ENDING_CREDITS_WEDDING_LOGIC"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        EnterArea(
            room_id=R506_ENDING_CREDITS_MARRYMORE_CHAPEL_BOOSTER_WEDDING_VALENTINA,
            face_direction=NORTHEAST,
            x=22,
            y=74,
            z=0),
        FreezeCamera(),
        ActionQueueSync(
            target=SCREEN_FOCUS,
            subscript=[
                ASSetWalkingSpeed(VERY_FAST),
                ASBounceToXYWithHeight(x=18, y=55, height=0),
                ASWalkNorthwestPixels(8),
            ]),
        ActionQueueSync(target=MARIO, subscript=[ASVisibilityOff()]),
        ActionQueueSync(
            target=NPC_9, subscript=[ASFixedFCoordOn(), ASWalkNorthwestPixels(1)]
        ),
        ActionQueueSync(
            target=NPC_10, subscript=[ASFixedFCoordOn(), ASWalkSoutheastPixels(1)]
        ),
        ActionQueueAsync(
            target=NPC_0,
            subscript=[
                ASWalkSoutheastPixels(4),
                ASFaceSouthwest(),
                ASSequenceLoopingOn(),
            ]),
        RunEventAsSubroutine(E0795_ENDING_CREDITS_CHAPEL_SHUFFLED_NPC_ANIMATION_LOADER),
        StarMaskExpandFromScreenCenter(),
        Pause(95),
        ActionQueueAsync(
            target=NPC_9,
            subscript=[
                ASSetSequenceSpeed(NORMAL),
                ASSetWalkingSpeed(VERY_SLOW),
                ASWalkSoutheastPixels(8),
            ]),
        Pause(20),
        ActionQueueAsync(
            target=NPC_10,
            subscript=[
                ASSetSequenceSpeed(NORMAL),
                ASSetWalkingSpeed(SLOW),
                ASWalkSoutheastPixels(8),
            ]),
        Pause(20),
        ActionQueueAsync(
            target=NPC_9,
            subscript=[
                ASFixedFCoordOff(),
                ASFaceSoutheast(),
                ASPause(30),
                ASFaceNortheast(),
                ASFixedFCoordOn(),
                ASPause(25),
                ASWalkSoutheastPixels(8),
            ]),
        Pause(5),
        ActionQueueSync(
            target=NPC_10,
            subscript=[
                ASSetAllSpeeds(FAST),
                ASFaceNortheast(),
                ASFixedFCoordOn(),
                ASWalkSoutheastPixels(8),
                ASFixedFCoordOff(),
                ASWalkNortheastSteps(3),
                ASWalkNortheastSteps(1),
                ASWalkNorthwestSteps(3),
                ASWalkSouthwestSteps(4),
                ASWalkSoutheastSteps(1),
                ASWalkSoutheastPixels(8),
                ASWalkSouthwestSteps(10),
            ]),
        ActionQueueSync(
            target=NPC_9,
            subscript=[
                ASPause(30),
                ASFixedFCoordOff(),
                ASFaceSoutheast(),
                ASPause(15),
                ASSetAllSpeeds(FAST),
                ASWalkSoutheastSteps(1),
                ASWalkSoutheastPixels(4),
                ASWalkNortheastSteps(2),
                ASWalkNortheastSteps(2),
                ASWalkNorthwestSteps(3),
                ASWalkSouthwestSteps(4),
                ASWalkSoutheastSteps(1),
                ASWalkSoutheastPixels(8),
                ASWalkSouthwestSteps(10),
            ]),
        ActionQueueSync(
            target=NPC_0, subscript=[ASPause(100), ASPause(60), ASSequenceLoopingOff()]
        ),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASPause(85),
                ASSequenceLoopingOn(),
                ASJumpToHeight(height=64, silent=True),
                ASPause(60),
                ASFaceSoutheast(),
                ASPause(65),
                ASSetAllSpeeds(FAST),
                ASWalkSoutheastSteps(4),
                ASWalkSouthwestSteps(7),
            ]),
        ActionQueueSync(
            target=NPC_2,
            subscript=[
                ASPause(85),
                ASSequenceLoopingOn(),
                ASJumpToHeight(height=64, silent=True),
                ASPause(60),
                ASFaceSoutheast(),
                ASPause(65),
                ASSetAllSpeeds(FAST),
                ASWalkSoutheastSteps(2),
                ASWalkSouthwestSteps(7),
            ]),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASPause(85),
                ASSequenceLoopingOn(),
                ASJumpToHeight(height=64, silent=True),
                ASPause(60),
                ASFaceNorthwest(),
                ASPause(65),
                ASSetAllSpeeds(FAST),
                ASWalkNorthwestSteps(2),
                ASWalkSouthwestSteps(7),
            ]),
        ActionQueueSync(
            target=NPC_4,
            subscript=[
                ASPause(85),
                ASSequenceLoopingOn(),
                ASJumpToHeight(height=64, silent=True),
                ASPause(60),
                ASFaceNorthwest(),
                ASPause(65),
                ASSetAllSpeeds(FAST),
                ASWalkNorthwestSteps(4),
                ASWalkSouthwestSteps(7),
            ]),
        ActionQueueSync(
            target=NPC_5,
            subscript=[
                ASVisibilityOff(),
                ASPause(85),
                ASPause(60),
                ASFaceNorthwest(),
                ASPause(65),
                ASPause(60),
                ASVisibilityOn(),
                ASSetAllSpeeds(FAST),
                ASWalkSoutheastSteps(4),
                ASWalkSouthwestSteps(7),
            ]),
        ActionQueueSync(
            target=NPC_6,
            subscript=[
                ASVisibilityOff(),
                ASPause(85),
                ASSequenceLoopingOn(),
                ASPause(60),
                ASFaceNorthwest(),
                ASPause(65),
                ASPause(60),
                ASVisibilityOn(),
                ASSetAllSpeeds(FAST),
                ASWalkSoutheastSteps(2),
                ASWalkSouthwestSteps(7),
            ]),
        ActionQueueSync(
            target=NPC_7,
            subscript=[
                ASPause(85),
                ASSequenceLoopingOn(),
                ASJumpToHeight(height=64, silent=True),
                ASPause(60),
                ASFaceNorthwest(),
                ASPause(65),
                ASPause(60),
                ASSetAllSpeeds(FAST),
                ASWalkNorthwestSteps(2),
                ASWalkSouthwestSteps(7),
            ]),
        ActionQueueAsync(
            target=NPC_8,
            subscript=[
                ASPause(85),
                ASSequenceLoopingOn(),
                ASJumpToHeight(height=64, silent=True),
                ASPause(60),
                ASFaceNorthwest(),
                ASPause(65),
                ASPause(60),
                ASSetAllSpeeds(FAST),
                ASWalkNorthwestSteps(4),
                ASWalkSouthwestSteps(7),
            ]),
        Pause(15),
        ActionQueueSync(
            target=NPC_0,
            subscript=[
                ASSetSpriteSequence(index=1, is_sequence=True, looping=True),
                ASPause(45),
            ]),
        StarMaskShrinkToScreenCenter(),
        Pause(60),
        JmpToEvent(E3802_ENDING_CREDITS_YELLOW_STAR),
        Return(),
    ]
)
