# pylint: disable=C0301

"""E2360_ABYSS_1ST_TRAMPOLINE_CATCHER_LOADER"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        ActionQueueAsync(target=NPC_0, subscript=[ASWalkNortheastPixels(10)]),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASSetVRAMPriority(OBJECT_OVERLAPS_MARIO_ON_ALL_SIDES),
                ASOverwriteSolidity(),
                ASFloatingOff(),
                ASTransferToXYZF(x=14, y=9, z=20, direction=EAST),
                ASWalkNorthPixels(14),
                ASWalkWestPixels(3),
            ],
        ),
        FadeInFromBlack(sync=False),
        PlaySound(sound=SO019_LONG_FALL, channel=6),
        Pause(64),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASSequencePlaybackOff(),
                ASSetSpriteSequence(
                    index=0,
                    sprite_offset=3,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                ),
                ASOverwriteSolidity(
                    cant_pass_walls=True,
                    bit_4=True,
                    cant_pass_npcs=True,
                    cant_walk_through=True,
                    bit_7=True,
                ),
                ASFloatingOn(),
                ASPause(
                    1, identifier="EVENT_2360_action_queue_async_5_SUBSCRIPT_pause_4"
                ),
                ASJmpIfMarioInAir(
                    ["EVENT_2360_action_queue_async_5_SUBSCRIPT_pause_4"]
                ),
                ASPlaySound(sound=SO000_SILENCE, channel=4),
            ],
        ),
        ActionQueueSync(
            target=NPC_0,
            subscript=[ASSetSpriteSequence(index=0, looping=False, mirror_sprite=True)],
        ),
        ActionQueueAsync(
            target=MARIO,
            subscript=[ASSetWalkingSpeed(VERY_SLOW), ASWalkSouthPixels(8)],
        ),
        PlaySound(sound=SO010_TRAMPOLINE, channel=6),
        ActionQueueSync(
            target=SCREEN_FOCUS,
            subscript=[ASSetWalkingSpeed(NORMAL), ASWalkNorthwestSteps(4)],
        ),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASShadowOff(),
                ASDb(bytearray(b" \x07")),
                ASDb(bytearray(b"$\x00\xff\x00\xff")),
                ASDb(bytearray(b"%\x00\x0c\xf0\xff")),
                ASPause(32),
                ASBPL262728(),
            ],
        ),
        Pause(24),
        FadeOutToBlack(sync=False, duration=16),
        StopEmbeddedActionScript(MARIO),
        StopEmbeddedActionScript(SCREEN_FOCUS),
        JmpIfVarEqualsConst(FACTORY_FALL_1, 220, ["EVENT_2360_set_32"]),
        JmpIfVarEqualsConst(FACTORY_FALL_1, 239, ["EVENT_2360_jmp_if_bit_set_38"]),
        SetBit(DIRECTIONAL_7045_7),
        JmpIfBitSet(DIRECTIONAL_7045_0, ["EVENT_2360_enter_area_24"]),
        JmpIfBitSet(DIRECTIONAL_7045_1, ["EVENT_2360_enter_area_26"]),
        JmpIfBitSet(DIRECTIONAL_7045_2, ["EVENT_2360_enter_area_28"]),
        JmpIfBitSet(DIRECTIONAL_7045_4, ["EVENT_2360_enter_area_30"]),
        EnterArea(
            room_id=R222_SMITHY_FACTORY_AREA_03_GLUM_REAPERS,
            face_direction=SOUTH,
            x=14,
            y=99,
            z=10,
            run_entrance_event=True,
        ),
        Jmp(["EVENT_2362_set_118"]),
        EnterArea(
            room_id=R222_SMITHY_FACTORY_AREA_03_GLUM_REAPERS,
            face_direction=SOUTH,
            x=4,
            y=124,
            z=10,
            run_entrance_event=True,
            identifier="EVENT_2360_enter_area_24",
        ),
        Jmp(["EVENT_2362_set_40"]),
        EnterArea(
            room_id=R222_SMITHY_FACTORY_AREA_03_GLUM_REAPERS,
            face_direction=SOUTH,
            x=9,
            y=111,
            z=10,
            run_entrance_event=True,
            identifier="EVENT_2360_enter_area_26",
        ),
        Jmp(["EVENT_2362_set_66"]),
        EnterArea(
            room_id=R222_SMITHY_FACTORY_AREA_03_GLUM_REAPERS,
            face_direction=SOUTH,
            x=14,
            y=121,
            z=10,
            run_entrance_event=True,
            identifier="EVENT_2360_enter_area_28",
        ),
        Jmp(["EVENT_2362_set_92"]),
        EnterArea(
            room_id=R222_SMITHY_FACTORY_AREA_03_GLUM_REAPERS,
            face_direction=SOUTH,
            x=19,
            y=110,
            z=10,
            run_entrance_event=True,
            identifier="EVENT_2360_enter_area_30",
        ),
        Jmp(["EVENT_2362_set_144"]),
        SetVarToConst(FACTORY_FALL_1, 238, identifier="EVENT_2360_set_32"),
        JmpIfBitSet(DIRECTIONAL_7045_1, ["EVENT_2360_enter_area_36"]),
        EnterArea(
            room_id=R220_SMITHY_FACTORY_AREA_02_WSAVE_POINT,
            face_direction=SOUTH,
            x=5,
            y=75,
            z=10,
            run_entrance_event=True,
        ),
        Jmp(["EVENT_2359_set_24"]),
        EnterArea(
            room_id=R220_SMITHY_FACTORY_AREA_02_WSAVE_POINT,
            face_direction=SOUTH,
            x=10,
            y=67,
            z=10,
            run_entrance_event=True,
            identifier="EVENT_2360_enter_area_36",
        ),
        Jmp(["EVENT_2359_set_37"]),
        JmpIfBitSet(
            DIRECTIONAL_7045_0,
            ["EVENT_2360_enter_area_41"],
            identifier="EVENT_2360_jmp_if_bit_set_38",
        ),
        EnterArea(
            room_id=R239_SMITHY_FACTORY_AREA_06_ULTRA_HAMMER,
            face_direction=NORTHEAST,
            x=21,
            y=53,
            z=7,
            run_entrance_event=True,
        ),
        Jmp(["EVENT_2409_jmp_if_bit_clear_57"]),
        EnterArea(
            room_id=R239_SMITHY_FACTORY_AREA_06_ULTRA_HAMMER,
            face_direction=NORTHEAST,
            x=29,
            y=37,
            z=10,
            run_entrance_event=True,
            identifier="EVENT_2360_enter_area_41",
        ),
        Jmp(["EVENT_2409_set_39"]),
    ]
)
