# pylint: disable=C0301

"""E1777_LANDS_END_CLIFF_LOADER"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        SummonObjectToSpecificLevel(NPC_2, R319_LANDS_END_DESERT_AREA_06),
        SummonObjectToSpecificLevel(NPC_6, R402_LANDS_END_DESERT_AREA_03),
        SummonObjectToSpecificLevel(NPC_2, R403_LANDS_END_DESERT_AREA_05),
        SummonObjectToSpecificLevel(NPC_3, R404_LANDS_END_DESERT_AREA_04),
        SummonObjectToSpecificLevel(NPC_6, R318_LANDS_END_DESERT_AREA_02),
        FadeInFromBlack(sync=False),
        JmpIfBitClear(TEMPLE_BOSS_DEFEATED, ["EVENT_1777_ret_32"]),
        PlaySound(sound=SO123_CHAIN_RUMBLING_NOISE, channel=6),
        Pause(1),
        FadeOutSoundToVolume(duration=8, volume=0),
        ActionQueueSync(
            target=SCREEN_FOCUS,
            subscript=[
                ASSetWalkingSpeed(FASTEST),
                ASWalkNortheastSteps(4),
                ASShiftNorthSteps(22),
            ]),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASSetPriority(3),
                ASVisibilityOn(),
                ASSequenceLoopingOn(),
                ASSetAllSpeeds(FASTER),
                ASTransferToXYZF(x=24, y=113, z=24, direction=SOUTHEAST),
                ASBounceToXYWithHeight(x=24, y=113, height=44),
                ASWalkNortheastSteps(2),
                ASFaceSouthwest(),
            ]),
        ActionQueueSync(
            target=NPC_2,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASSetPriority(3),
                ASPause(2),
                ASVisibilityOn(),
                ASSequenceLoopingOn(),
                ASSetAllSpeeds(FAST),
                ASTransferToXYZF(x=21, y=107, z=14, direction=EAST),
                ASBounceToXYWithHeight(x=21, y=107, height=14),
                ASSetSolidityBits(cant_pass_walls=True),
                ASWalkNortheastPixels(8),
                ASFaceSoutheast(),
                ASClearSolidityBits(cant_pass_walls=True),
            ]),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASSetPriority(3),
                ASPause(4),
                ASVisibilityOn(),
                ASSequenceLoopingOn(),
                ASSetAllSpeeds(FAST),
                ASTransferToXYZF(x=23, y=110, z=18, direction=EAST),
                ASBounceToXYWithHeight(x=23, y=110, height=18),
                ASSetSolidityBits(cant_pass_walls=True),
                ASWalkNortheastPixels(8),
                ASFaceSoutheast(),
                ASClearSolidityBits(cant_pass_walls=True),
            ]),
        ActionQueueSync(
            target=NPC_4,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASSetPriority(3),
                ASPause(6),
                ASVisibilityOn(),
                ASSequenceLoopingOn(),
                ASSetAllSpeeds(FAST),
                ASTransferToXYZF(x=26, y=116, z=20, direction=EAST),
                ASBounceToXYWithHeight(x=26, y=116, height=20),
                ASSetSolidityBits(cant_pass_walls=True),
                ASWalkNortheastPixels(8),
                ASFaceSoutheast(),
                ASClearSolidityBits(cant_pass_walls=True),
            ]),
        ActionQueueSync(
            target=NPC_5,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASSetPriority(3),
                ASPause(8),
                ASVisibilityOn(),
                ASSequenceLoopingOn(),
                ASSetAllSpeeds(FAST),
                ASTransferToXYZF(x=24, y=113, z=24, direction=EAST),
                ASBounceToXYWithHeight(x=24, y=113, height=24),
                ASSetSolidityBits(cant_pass_walls=True),
                ASWalkNortheastPixels(8),
                ASFaceSoutheast(),
                ASClearSolidityBits(cant_pass_walls=True),
            ]),
        ActionQueueSync(
            target=NPC_6,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASSetPriority(3),
                ASPause(10),
                ASVisibilityOn(),
                ASSequenceLoopingOn(),
                ASSetAllSpeeds(FAST),
                ASTransferToXYZF(x=22, y=108, z=24, direction=EAST),
                ASBounceToXYWithHeight(x=22, y=108, height=24),
                ASSetSolidityBits(cant_pass_walls=True),
                ASWalkNortheastPixels(8),
                ASFaceSoutheast(),
                ASClearSolidityBits(cant_pass_walls=True),
            ]),
        ActionQueueSync(
            target=NPC_7,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASSetPriority(3),
                ASPause(12),
                ASVisibilityOn(),
                ASSequenceLoopingOn(),
                ASSetAllSpeeds(FAST),
                ASTransferToXYZF(x=20, y=105, z=28, direction=EAST),
                ASBounceToXYWithHeight(x=20, y=105, height=28),
                ASSetSolidityBits(cant_pass_walls=True),
                ASWalkNortheastPixels(8),
                ASFaceSoutheast(),
                ASClearSolidityBits(cant_pass_walls=True),
            ]),
        ActionQueueSync(
            target=NPC_8,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASSetPriority(3),
                ASPause(14),
                ASVisibilityOn(),
                ASSequenceLoopingOn(),
                ASSetAllSpeeds(FAST),
                ASTransferToXYZF(x=21, y=107, z=31, direction=EAST),
                ASBounceToXYWithHeight(x=21, y=107, height=36),
                ASSetSolidityBits(cant_pass_walls=True),
                ASWalkNortheastPixels(8),
                ASFaceSoutheast(),
                ASClearSolidityBits(cant_pass_walls=True),
            ]),
        ActionQueueAsync(
            target=NPC_9,
            subscript=[
                ASClearSolidityBits(cant_pass_walls=True),
                ASSetPriority(3),
                ASPause(14),
                ASVisibilityOn(),
                ASSequenceLoopingOn(),
                ASSetAllSpeeds(FAST),
                ASTransferToXYZF(x=23, y=111, z=30, direction=EAST),
                ASBounceToXYWithHeight(x=23, y=111, height=30),
                ASSetSolidityBits(cant_pass_walls=True),
                ASWalkNortheastPixels(8),
                ASFaceSoutheast(),
                ASClearSolidityBits(cant_pass_walls=True),
            ]),
        SetVarToConst(TEMP_70AB, 21),
        RunEventAsSubroutine(E1739_REFOCUS_CAMERA),
        SetBit(SKY_BRIDGE_PAN),
        SetVarToConst(TEMP_70AB, 29),
        StartLoopNTimes(7),
        RunEventAsSubroutine(E1739_REFOCUS_CAMERA),
        ActionQueueAsync(
            target=MEM_70AB,
            subscript=[
                ASSetVarToConst(TEMP_7034, 65535),
                ASDb(bytearray(b"\xc7\x13")),
                ASAddConstToVar(X_COORD_1, 80),
                ASAddConstToVar(Z_COORD_1, 128),
                ASPause(
                    1, identifier="EVENT_1777_action_queue_async_26_SUBSCRIPT_pause_4"
                ),
                ASCreatePacketAt7010(
                    packet=P032_BLUE_CLOUD,
                    destinations=["EVENT_1777_action_queue_async_26_SUBSCRIPT_pause_4"]),
                ASPlaySound(sound=SO134_SWIPE, channel=4),
                ASPause(1),
                ASSetSpriteSequence(
                    index=5, is_sequence=True, looping=True, mirror_sprite=True
                ),
                ASSetAllSpeeds(NORMAL),
                ASFixedFCoordOn(),
                ASWalkNorthwestPixels(4),
                ASWalkSoutheastPixels(4),
                ASFixedFCoordOff(),
            ]),
        Dec(TEMP_70AB),
        EndLoop(),
        SetVarToConst(TEMP_70AB, 0),
        RunEventAsSubroutine(E1739_REFOCUS_CAMERA),
        ClearBit(SKY_BRIDGE_PAN),
        Return(identifier="EVENT_1777_ret_32"),
    ]
)
