# pylint: disable=C0301

"""E1556_WIGGLER_JUMP"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        SetVarToConst(BATTLE_PACK_ID, 24),
        JmpIfRandom1of2(["EVENT_1556_jmp_if_bit_set_3"]),
        SetVarToConst(BATTLE_PACK_ID, 25),
        JmpIfBitSet(
            TEMP_7043_5, ["EVENT_1556_ret_80"], identifier="EVENT_1556_jmp_if_bit_set_3"
        ),
        JmpIfBitSet(TEMP_7043_6, ["EVENT_1556_ret_80"]),
        EnableControlsUntilReturn([LEFT, RIGHT, DOWN, UP, X, A, Y, B]),
        SetVarToConst(SECONDARY_TEMP_7024, 20),
        CopyVarToVar(from_var=ACTIVE_NPC, to_var=PRIMARY_TEMP_7000),
        DecVarFrom7000(SECONDARY_TEMP_7024),
        JmpIf7000AnyBitsSet(bits=[], destinations=["EVENT_1556_set_bit_13"]),
        SetBit(TEMP_7043_5),
        ClearBit(TEMP_7043_4),
        Jmp(["EVENT_1556_mem_7000_and_const_15"]),
        SetBit(TEMP_7043_6, identifier="EVENT_1556_set_bit_13"),
        SetBit(TEMP_7043_4),
        Mem7000AndConst(0x0004, identifier="EVENT_1556_mem_7000_and_const_15"),
        AddVarTo7000(SECONDARY_TEMP_7024),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=TEMP_702E),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=TEMP_70AA),
        Set7000ToObjectCoord(target_npc=MEM_70AA, coord=COORD_F, pixel=True),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=TEMP_70AE),
        JmpIfBitClear(TEMP_7076_0, ["EVENT_1556_start_loop_n_times_21"]),
        JmpIfMarioOnAnObjectOrNot(
            ["EVENT_1556_start_loop_n_times_21-", "EVENT_1556_ret_80"]
        ),
        StartLoopNTimes(3, identifier="EVENT_1556_start_loop_n_times_21-"),
        PauseActionScript(MEM_70AA),
        Inc(TEMP_70AA),
        EndLoop(),
        Jmp(["EVENT_1556_set_7000_to_70A0_short_mem_45"]),
        StartLoopNTimes(3, identifier="EVENT_1556_start_loop_n_times_21"),
        PauseActionScript(MEM_70AA),
        Inc(TEMP_70AA),
        EndLoop(),
        JmpIfMarioOnAnObjectOrNot(
            [
                "EVENT_1556_set_7000_to_70A0_short_mem_45",
                "EVENT_1556_start_battle_700E_26",
            ]
        ),
        StartBattleWithPackAt700E(identifier="EVENT_1556_start_battle_700E_26"),
        JmpIfBitSet(GAME_OVER, ["EVENT_1556_reset_and_choose_game_43"]),
        SetVarToConst(TEMP_70AF, 0),
        CopyVarToVar(from_var=TEMP_702E, to_var=PRIMARY_TEMP_7000),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=TEMP_70AA),
        StartLoopNTimes(3),
        ResetCoords(MEM_70AA),
        SetSyncActionScript(MEM_70AA, A0652_FOREST_FIRST_WIGGLER_AFTER_RUNNING_AWAY),
        Inc(TEMP_70AA),
        EndLoop(),
        ActionQueueSync(
            target=MARIO, subscript=[ASPause(1), ASJumpToHeight(height=0, silent=True)]
        ),
        FadeInFromBlack(sync=False),
        JmpIfBitSet(TEMP_7043_4, ["EVENT_1556_clear_bit_41"]),
        ClearBit(TEMP_7043_5),
        Return(),
        ClearBit(TEMP_7043_6, identifier="EVENT_1556_clear_bit_41"),
        Return(),
        ResetAndChooseGame(identifier="EVENT_1556_reset_and_choose_game_43"),
        Return(),
        CopyVarToVar(
            from_var=TEMP_70AE,
            to_var=PRIMARY_TEMP_7000,
            identifier="EVENT_1556_set_7000_to_70A0_short_mem_45",
        ),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=PRIMARY_TEMP_700C),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASFaceEast7C(),
                ASClearSolidityBits(
                    bit_4=True, cant_pass_npcs=True, cant_walk_through=True, bit_7=True
                ),
                ASJumpToHeight(144),
                ASWalk1StepFDirection(),
                ASSetSolidityBits(
                    bit_4=True, cant_pass_npcs=True, cant_walk_through=True, bit_7=True
                ),
            ],
        ),
        Inc(TEMP_70AF),
        JmpIfVarNotEqualsConst(TEMP_70AF, 10, ["EVENT_1556_add_coins_57"]),
        Inc(TEMP_70AB),
        SummonObjectToCurrentLevelAtMariosCoords(MEM_70AB),
        StartSyncEmbeddedActionScript(
            target=MEM_70AB,
            prefix=0xF1,
            subscript=[
                ASPlaySound(sound=SO094_FROG_COIN, channel=4),
                ASShadowOff(),
                ASSetVRAMPriority(PRIORITY_3),
                ASSetPriority(3),
                ASSetSpriteSequence(index=1, is_sequence=True, looping=True),
                ASSet700CToObjectCoord(target_npc=MARIO, coord=COORD_F, pixel=True),
                ASAddConstToVar(PRIMARY_TEMP_700C, 2),
                ASMem700CAndConst(0x0004),
                ASMem700CXorConst(0x0004),
                ASFaceEast7C(),
                ASFloatingOff(),
                ASJumpToHeight(160),
                ASWalkFDirectionSteps(2),
                ASVisibilityOff(),
            ],
        ),
        Dec(TEMP_70AB),
        RunDialog(
            dialog_id=DI1049_FOUND_A_FROG_COIN,
            above_object=TOADSTOOL,
            closable=False,
            sync=True,
            multiline=False,
            use_background=False,
            bit_6=True,
        ),
        AddFrogCoins(1),
        Jmp(["EVENT_1556_pause_60"]),
        AddCoins(1, identifier="EVENT_1556_add_coins_57"),
        SummonObjectToCurrentLevelAtMariosCoords(MEM_70AB),
        StartSyncEmbeddedActionScript(
            target=MEM_70AB,
            prefix=0xF1,
            subscript=[
                ASPlaySound(sound=SO013_COIN, channel=4),
                ASShadowOff(),
                ASSetVRAMPriority(PRIORITY_3),
                ASSetPriority(3),
                ASSetSpriteSequence(index=2, is_sequence=True, looping=True),
                ASSet700CToObjectCoord(target_npc=MARIO, coord=COORD_F, pixel=True),
                ASAddConstToVar(PRIMARY_TEMP_700C, 2),
                ASMem700CAndConst(0x0004),
                ASMem700CXorConst(0x0004),
                ASFaceEast7C(),
                ASFloatingOff(),
                ASDb(bytearray(b" \x04")),
                ASDb(bytearray(b"%\x00\x08\xb0\xff")),
                ASWalk1StepFDirection(),
                ASVisibilityOff(),
                ASBPL262728(),
            ],
        ),
        Pause(1, identifier="EVENT_1556_pause_60"),
        CopyVarToVar(from_var=TEMP_702E, to_var=PRIMARY_TEMP_7000),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=TEMP_70AA),
        StartLoopNTimes(3),
        ActionQueueSync(
            target=MEM_70AA,
            subscript=[
                ASSetWalkingSpeed(FAST),
                ASShiftZUpPixels(16),
                ASShiftZDownPixels(16),
            ],
        ),
        Inc(TEMP_70AA),
        Pause(3),
        EndLoop(),
        Dec(TEMP_70AA),
        StopEmbeddedActionScript(MEM_70AA),
        CopyVarToVar(from_var=TEMP_702E, to_var=PRIMARY_TEMP_7000),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=TEMP_70AA),
        StartLoopNTimes(3),
        ResumeActionScript(MEM_70AA),
        Inc(TEMP_70AA),
        EndLoop(),
        JmpIfBitSet(TEMP_7043_4, ["EVENT_1556_clear_bit_79"]),
        ClearBit(TEMP_7043_5),
        Return(),
        ClearBit(TEMP_7043_6, identifier="EVENT_1556_clear_bit_79"),
        Return(identifier="EVENT_1556_ret_80"),
    ]
)
