# E1830_KEEP_HANDLE_ROOM_RELOAD_AFTER_LAVA_FALL

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        EnableControlsUntilReturn([]),
        Pause(1),
        FreezeAllNPCsUntilReturn(),
        Pause(1),
        SetSyncActionScript(MARIO, A0775_PLAYER_FALLS_IN_KEEP_LAVA),
        SetSyncActionScript(NPC_0, A0775_PLAYER_FALLS_IN_KEEP_LAVA),
        Pause(1, identifier="EVENT_1830_pause_6"),
        JmpIfMarioInAir(["EVENT_1830_pause_6"]),
        PauseActionScript(MARIO),
        ResetCoords(MARIO),
        StoreCoinCountTo7000(identifier="EVENT_1830_store_coin_amount_7000_10"),
        JmpIfVarEqualsConst(
            PRIMARY_TEMP_7000, 0, ["EVENT_1830_stop_embedded_action_script_23"]
        ),
        PlaySound(sound=SO055_LOSE_COINS_COIN_FOUNTAIN, channel=6),
        SetVarToConst(PRIMARY_TEMP_700C, 5),
        StartLoopNTimes(7),
        StoreCoinCountTo7000(),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 0, ["EVENT_1830_pause_20"]),
        CreatePacketAtObjectCoords(
            packet=P017_SMALL_MINIGAME_COIN,
            object=MARIO,
            destinations=["EVENT_1830_pause_20"],
        ),
        SetVarToConst(PRIMARY_TEMP_7000, 1),
        Dec7000FromCoins(),
        Pause(1, identifier="EVENT_1830_pause_20"),
        Inc(PRIMARY_TEMP_700C),
        EndLoop(),
        StopEmbeddedActionScript(
            MARIO, identifier="EVENT_1830_stop_embedded_action_script_23"
        ),
        Dec(KEEP_DOOR_LIVES),
        JmpIfVarEqualsConst(KEEP_DOOR_LIVES, 0, ["EVENT_1864_slow_down_music_6"]),
        FadeOutToBlack(sync=False, duration=40),
        Set7000ToCurrentLevel(),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 321, ["EVENT_1830_enter_area_44"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 457, ["EVENT_1830_enter_area_52"]),
        JmpIfVarEqualsConst(
            PRIMARY_TEMP_7000, 455, ["EVENT_1830_set_7000_to_7000_short_mem_35"]
        ),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 322, ["EVENT_1830_enter_area_54"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 458, ["EVENT_1830_enter_area_62"]),
        EnterArea(
            room_id=R456_BOWSERS_KEEP_6DOOR_ACTION_ROOM_1C_GORILLA_THROWING_BARRELS,
            face_direction=NORTHEAST,
            x=22,
            y=123,
            z=0,
        ),
        JmpToEvent(E1836_KEEP_DONKEY_ROOM_LOADER),
        CopyVarToVar(
            from_var=ROSE_WAY_703E,
            to_var=PRIMARY_TEMP_7000,
            identifier="EVENT_1830_set_7000_to_7000_short_mem_35",
        ),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=ACTIVE_NPC),
        Set7000ToObjectCoord(object=MEM_70A8, coord=COORD_X, pixel=True, bit_7=True),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=TEMP_702E),
        Set7000ToObjectCoord(object=MEM_70A8, coord=COORD_Y, pixel=True, bit_7=True),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=TEMP_7030),
        EnterArea(
            room_id=R455_BOWSERS_KEEP_6DOOR_ACTION_ROOM_2C_VERY_SLOW_MOVING_CIRCLING_PLATFORMS,
            face_direction=NORTHEAST,
            x=6,
            y=47,
            z=1,
        ),
        SetBit(TEMP_7044_6),
        JmpToEvent(E1825_KEEP_ROTATING_ROOM_LOADER),
        EnterArea(
            room_id=R321_BOWSERS_KEEP_6DOOR_ACTION_ROOM_2A_SLOW_ELEVATING_PLATFORMS,
            face_direction=NORTHEAST,
            x=4,
            y=62,
            z=7,
            identifier="EVENT_1830_enter_area_44",
        ),
        JmpToSubroutine(["EVENT_1830_pause_70"]),
        SetBit(UNKNOWN_PAN),
        SetVarToConst(TEMP_70AB, 0),
        RunEventAsSubroutine(E1739_REFOCUS_CAMERA),
        ClearBit(UNKNOWN_PAN),
        SetBit(TEMP_7044_6),
        JmpToEvent(E1824_KEEP_SET_PLATFORM_PROPERTIES),
        EnterArea(
            room_id=R457_BOWSERS_KEEP_6DOOR_ACTION_ROOM_2B_CANNONBALL_RIDING,
            face_direction=NORTHEAST,
            x=2,
            y=57,
            z=0,
            identifier="EVENT_1830_enter_area_52",
        ),
        JmpToEvent(E1835_KEEP_CANNONBALL_ROOM_LOADER),
        EnterArea(
            room_id=R322_BOWSERS_KEEP_6DOOR_ACTION_ROOM_1A_JUMPING_TERRAPIN,
            face_direction=NORTHEAST,
            x=8,
            y=115,
            z=2,
            identifier="EVENT_1830_enter_area_54",
        ),
        JmpToSubroutine(["EVENT_1830_pause_70"]),
        SetBit(UNKNOWN_PAN),
        SetVarToConst(TEMP_70AB, 0),
        RunEventAsSubroutine(E1739_REFOCUS_CAMERA),
        ClearBit(UNKNOWN_PAN),
        SetBit(TEMP_7044_6),
        JmpToEvent(E1826_KEEP_INVISIBLE_FLOOR_ROOM_LOADER),
        EnterArea(
            room_id=R458_BOWSERS_KEEP_6DOOR_ACTION_ROOM_1B_MOVING_PLATFORMS,
            face_direction=NORTHEAST,
            x=10,
            y=122,
            z=5,
            identifier="EVENT_1830_enter_area_62",
        ),
        JmpToSubroutine(["EVENT_1830_pause_70"]),
        SetBit(UNKNOWN_PAN),
        SetVarToConst(TEMP_70AB, 0),
        RunEventAsSubroutine(E1739_REFOCUS_CAMERA),
        ClearBit(UNKNOWN_PAN),
        SetBit(TEMP_7044_6),
        JmpToEvent(E1827_KEEP_LINEAR_PLATFORM_ROOM_LOADER),
        Pause(4, identifier="EVENT_1830_pause_70"),
        FreezeAllNPCsUntilReturn(),
        JmpIfBitSet(TEMP_7095_4, ["EVENT_1830_pause_75"]),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASSwapVars(ROSE_WAY_7038, X_COORD_2),
                ASSwapVars(ROSE_WAY_703A, Y_COORD_2),
                ASSwapVars(ROSE_WAY_703C, Z_COORD_2),
                ASDb(bytearray(b"\x99")),
            ],
        ),
        Jmp(["EVENT_1830_ret_81"]),
        Pause(1, identifier="EVENT_1830_pause_75"),
        CopyVarToVar(from_var=ROSE_WAY_703E, to_var=PRIMARY_TEMP_7000),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=ACTIVE_NPC),
        Set7016701BToObjectXYZ(MEM_70A8),
        AddConstToVar(Z_COORD_2, 320),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASDb(bytearray(b"\x99")),
                ASPause(
                    1, identifier="EVENT_1830_action_queue_async_80_SUBSCRIPT_pause_1"
                ),
                ASJmpIfMarioInAir(
                    ["EVENT_1830_action_queue_async_80_SUBSCRIPT_pause_1"]
                ),
            ],
        ),
        Return(identifier="EVENT_1830_ret_81"),
    ]
)
