# pylint: disable=C0301

"""E2392_GARDENER"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        SetVarToConst(TEMP_70AE, 23),
        StoreItemAmountTo7000(Seed),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 1, ["EVENT_2392_jmp_if_bit_set_11"]),
        StoreItemAmountTo7000(Fertilizer),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 1, ["EVENT_2392_jmp_if_bit_set_144"]),
        JmpIfBitSet(GAVE_SEED_AND_FERTILIZER, ["EVENT_2392_run_dialog_9"]),
        SetBit(UNKNOWN_GARDENER_708E_2),
        RunDialog(
            dialog_id=DI3216_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        Return(),
        RunDialog(
            dialog_id=DI3103_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_2392_run_dialog_9"),
        Return(),
        JmpIfBitSet(
            UNKNOWN_GARDENER_708E_2,
            ["EVENT_2392_jmp_if_bit_set_14"],
            identifier="EVENT_2392_jmp_if_bit_set_11"),
        SetBit(UNKNOWN_GARDENER_708E_2),
        RunDialog(
            dialog_id=DI3216_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        JmpIfBitSet(
            UNKNOWN_GARDENER_708E_3,
            ["EVENT_2392_run_dialog_40"],
            identifier="EVENT_2392_jmp_if_bit_set_14"),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASJumpToHeight(108),
                ASPlaySound(sound=SO004_JUMP, channel=6),
                ASPause(22),
                ASSetSequenceSpeed(VERY_FAST),
            ]),
        Pause(22),
        SpeedUpMusicTempoBy(duration=0, change=32),
        Pause(2),
        RunDialog(
            dialog_id=DI3217_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        FreezeCamera(),
        Pause(2),
        SlowDownMusicTempoBy(duration=0, change=0),
        ActionQueueSync(
            target=NPC_3,
            subscript=[ASSetSequenceSpeed(NORMAL), ASPause(16), ASFaceSouthwest()]),
        SetAsyncActionScript(MARIO, A0855_PLAYER_DIZZY_FROM_GARDENER),
        SetSyncActionScript(SCREEN_FOCUS, A0391_CAMERA_SHAKE),
        Pause(32),
        JmpIfBitSet(UNKNOWN_GARDENER_708E_4, ["EVENT_2392_run_dialog_30"]),
        RunDialog(
            dialog_id=DI3214_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        Jmp(["EVENT_2392_pause_31"]),
        RunDialog(
            dialog_id=DI3215_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_2392_run_dialog_30"),
        Pause(16, identifier="EVENT_2392_pause_31"),
        SetAsyncActionScript(MARIO, A0384_PLAYER_LOOK_DOWN_SHAKE_HEAD),
        SetAsyncActionScript(MARIO, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        Pause(16),
        ActionQueueAsync(target=MARIO, subscript=[ASFaceNortheast()]),
        JmpIfBitSet(UNKNOWN_GARDENER_708E_3, ["EVENT_2392_run_dialog_40"]),
        SetBit(UNKNOWN_GARDENER_708E_3),
        RunDialog(
            dialog_id=DI3219_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        Jmp(["EVENT_2392_jmp_if_dialog_option_b_41"]),
        RunDialog(
            dialog_id=DI3221_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_2392_run_dialog_40"),
        JmpIfDialogOptionBSelected(
            ["EVENT_2392_pause_93"], identifier="EVENT_2392_jmp_if_dialog_option_b_41"
        ),
        Pause(10),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        RemoveOneOfItemFromInventory(Seed),
        RunDialog(
            dialog_id=DI3223_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        SetBit(GAVE_SEED),
        JmpIfBitSet(GAVE_FERTILIZER, ["EVENT_2392_freeze_camera_191"]),
        StoreItemAmountTo7000(Fertilizer),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 1, ["EVENT_2392_jmp_if_bit_set_52"]),
        UnfreezeCamera(),
        Return(),
        JmpIfBitSet(
            UNKNOWN_GARDENER_708E_4,
            ["EVENT_2392_run_dialog_85"],
            identifier="EVENT_2392_jmp_if_bit_set_52"),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASJumpToHeight(108),
                ASPlaySound(sound=SO004_JUMP, channel=6),
                ASPause(22),
                ASSetSequenceSpeed(VERY_FAST),
            ]),
        Pause(22),
        SpeedUpMusicTempoBy(duration=0, change=32),
        Pause(2),
        RunDialog(
            dialog_id=DI3218_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        FreezeCamera(),
        Pause(2),
        SlowDownMusicTempoBy(duration=0, change=0),
        ActionQueueSync(
            target=NPC_3,
            subscript=[ASSetSequenceSpeed(NORMAL), ASPause(16), ASFaceSouthwest()]),
        SetAsyncActionScript(MARIO, A0855_PLAYER_DIZZY_FROM_GARDENER),
        SetSyncActionScript(SCREEN_FOCUS, A0391_CAMERA_SHAKE),
        Pause(32),
        RunDialog(
            dialog_id=DI3215_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        Pause(16),
        SetAsyncActionScript(MARIO, A0384_PLAYER_LOOK_DOWN_SHAKE_HEAD),
        SetAsyncActionScript(MARIO, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        Pause(16),
        ActionQueueAsync(target=MARIO, subscript=[ASFaceNortheast()]),
        SetBit(UNKNOWN_GARDENER_708E_4),
        RunDialog(
            dialog_id=DI3220_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        JmpIfDialogOptionBSelected(["EVENT_2392_pause_80"]),
        Pause(10),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        RemoveOneOfItemFromInventory(Fertilizer),
        SetBit(GAVE_FERTILIZER),
        JmpIfBitSet(GAVE_SEED, ["EVENT_2392_freeze_camera_191"]),
        Jmp(["EVENT_2392_freeze_camera_191"]),
        Pause(10, identifier="EVENT_2392_pause_80"),
        SetAsyncActionScript(MARIO, A0671_SHAKE_HEAD_NO),
        RunDialog(
            dialog_id=DI3225_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        UnfreezeCamera(),
        Return(),
        RunDialog(
            dialog_id=DI3224_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_2392_run_dialog_85"),
        JmpIfDialogOptionBSelected(["EVENT_2392_pause_80"]),
        Pause(10),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        RemoveOneOfItemFromInventory(Fertilizer),
        SetBit(GAVE_FERTILIZER),
        JmpIfBitSet(GAVE_SEED, ["EVENT_2392_freeze_camera_191"]),
        Jmp(["EVENT_2392_freeze_camera_191"]),
        Pause(10, identifier="EVENT_2392_pause_93"),
        SetAsyncActionScript(MARIO, A0671_SHAKE_HEAD_NO),
        RunDialog(
            dialog_id=DI3230_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        StoreItemAmountTo7000(Fertilizer),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 1, ["EVENT_2392_jmp_if_bit_set_101"]),
        RunDialog(
            dialog_id=DI3225_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        UnfreezeCamera(),
        Return(),
        JmpIfBitSet(
            UNKNOWN_GARDENER_708E_4,
            ["EVENT_2392_jmp_if_bit_set_131"],
            identifier="EVENT_2392_jmp_if_bit_set_101"),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASJumpToHeight(108),
                ASPlaySound(sound=SO004_JUMP, channel=6),
                ASPause(22),
                ASSetSequenceSpeed(VERY_FAST),
            ]),
        Pause(22),
        SpeedUpMusicTempoBy(duration=0, change=32),
        Pause(2),
        RunDialog(
            dialog_id=DI3218_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        FreezeCamera(),
        Pause(2),
        SlowDownMusicTempoBy(duration=0, change=0),
        ActionQueueSync(
            target=NPC_3,
            subscript=[ASSetSequenceSpeed(NORMAL), ASPause(16), ASFaceSouthwest()]),
        SetAsyncActionScript(MARIO, A0855_PLAYER_DIZZY_FROM_GARDENER),
        SetSyncActionScript(SCREEN_FOCUS, A0391_CAMERA_SHAKE),
        Pause(32),
        RunDialog(
            dialog_id=DI3215_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        Pause(16),
        SetAsyncActionScript(MARIO, A0384_PLAYER_LOOK_DOWN_SHAKE_HEAD),
        SetAsyncActionScript(MARIO, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        Pause(16),
        ActionQueueAsync(target=MARIO, subscript=[ASFaceNortheast()]),
        SetBit(UNKNOWN_GARDENER_708E_4),
        RunDialog(
            dialog_id=DI3220_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        JmpIfDialogOptionBSelected(["EVENT_2392_pause_80"]),
        Pause(10),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        RemoveOneOfItemFromInventory(Fertilizer),
        SetBit(GAVE_FERTILIZER),
        JmpIfBitSet(GAVE_SEED, ["EVENT_2392_freeze_camera_191"]),
        RunDialog(
            dialog_id=DI3227_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        UnfreezeCamera(),
        Return(),
        JmpIfBitSet(
            GAVE_SEED,
            ["EVENT_2392_run_dialog_134"],
            identifier="EVENT_2392_jmp_if_bit_set_131"),
        RunDialog(
            dialog_id=DI3224_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        Jmp(["EVENT_2392_jmp_if_dialog_option_b_135"]),
        RunDialog(
            dialog_id=DI3229_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_2392_run_dialog_134"),
        JmpIfDialogOptionBSelected(
            ["EVENT_2392_pause_80"], identifier="EVENT_2392_jmp_if_dialog_option_b_135"
        ),
        Pause(10),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        RemoveOneOfItemFromInventory(Fertilizer),
        SetBit(GAVE_FERTILIZER),
        JmpIfBitSet(GAVE_SEED, ["EVENT_2392_freeze_camera_191"]),
        RunDialog(
            dialog_id=DI3227_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        UnfreezeCamera(),
        Return(),
        JmpIfBitSet(
            UNKNOWN_GARDENER_708E_4,
            ["EVENT_2392_run_dialog_183"],
            identifier="EVENT_2392_jmp_if_bit_set_144"),
        JmpIfBitSet(UNKNOWN_GARDENER_708E_2, ["EVENT_2392_action_queue_sync_148"]),
        SetBit(UNKNOWN_GARDENER_708E_2),
        RunDialog(
            dialog_id=DI3216_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASJumpToHeight(108),
                ASPlaySound(sound=SO004_JUMP, channel=6),
                ASPause(22),
                ASSetSequenceSpeed(VERY_FAST),
            ],
            identifier="EVENT_2392_action_queue_sync_148"),
        Pause(24),
        SpeedUpMusicTempoBy(duration=0, change=32),
        Pause(2),
        RunDialog(
            dialog_id=DI3218_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        FreezeCamera(),
        Pause(2),
        SlowDownMusicTempoBy(duration=0, change=0),
        ActionQueueSync(
            target=NPC_3,
            subscript=[ASSetSequenceSpeed(NORMAL), ASPause(16), ASFaceSouthwest()]),
        SetAsyncActionScript(MARIO, A0855_PLAYER_DIZZY_FROM_GARDENER),
        SetSyncActionScript(SCREEN_FOCUS, A0391_CAMERA_SHAKE),
        Pause(32),
        JmpIfBitSet(UNKNOWN_GARDENER_708E_3, ["EVENT_2392_run_dialog_163"]),
        RunDialog(
            dialog_id=DI3214_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        Jmp(["EVENT_2392_pause_164"]),
        RunDialog(
            dialog_id=DI3215_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_2392_run_dialog_163"),
        Pause(16, identifier="EVENT_2392_pause_164"),
        SetAsyncActionScript(MARIO, A0384_PLAYER_LOOK_DOWN_SHAKE_HEAD),
        SetAsyncActionScript(MARIO, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        Pause(16),
        ActionQueueAsync(target=MARIO, subscript=[ASFaceNortheast()]),
        JmpIfBitSet(UNKNOWN_GARDENER_708E_4, ["EVENT_2392_run_dialog_173"]),
        SetBit(UNKNOWN_GARDENER_708E_4),
        RunDialog(
            dialog_id=DI3220_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        Jmp(["EVENT_2392_jmp_if_dialog_option_b_174"]),
        RunDialog(
            dialog_id=DI3222_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_2392_run_dialog_173"),
        JmpIfDialogOptionBSelected(
            ["EVENT_2392_pause_80"], identifier="EVENT_2392_jmp_if_dialog_option_b_174"
        ),
        Pause(10),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        RemoveOneOfItemFromInventory(Fertilizer),
        SetBit(GAVE_FERTILIZER),
        JmpIfBitSet(GAVE_SEED, ["EVENT_2392_freeze_camera_191"]),
        RunDialog(
            dialog_id=DI3228_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        UnfreezeCamera(),
        Return(),
        RunDialog(
            dialog_id=DI3222_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_2392_run_dialog_183"),
        JmpIfDialogOptionBSelected(["EVENT_2392_pause_80"]),
        RemoveOneOfItemFromInventory(Fertilizer),
        SetBit(GAVE_FERTILIZER),
        JmpIfBitSet(GAVE_SEED, ["EVENT_2392_freeze_camera_191"]),
        RunDialog(
            dialog_id=DI3228_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        UnfreezeCamera(),
        Return(),
        FreezeCamera(identifier="EVENT_2392_freeze_camera_191"),
        RunDialog(
            dialog_id=DI3226_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        SetBit(GAVE_SEED_AND_FERTILIZER),
        SummonObjectToSpecificLevel(NPC_0, R417_GARDENERS_HOUSE_OUTSIDE),
        SummonObjectToSpecificLevel(NPC_1, R417_GARDENERS_HOUSE_OUTSIDE),
        SummonObjectToSpecificLevel(NPC_0, R418_GARDENERS_HOUSE),
        SummonObjectToSpecificLevel(NPC_1, R418_GARDENERS_HOUSE),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASWalkSoutheastSteps(2),
                ASFaceNortheast(),
                ASPause(16),
                ASSetSpriteSequence(
                    index=1, is_sequence=True, looping=True, mirror_sprite=True
                ),
                ASWalkSouthwestPixels(10),
                ASFaceNortheast(),
                ASResetProperties(),
                ASSequenceLoopingOff(),
                ASPause(32),
                ASSetVRAMPriority(OBJECT_OVERLAPS_MARIO_ON_ALL_SIDES),
                ASOverwriteSolidity(),
                ASSequenceLoopingOn(),
                ASPlaySound(sound=SO004_JUMP, channel=4),
                ASDb(bytearray(b" \x07")),
                ASDb(bytearray(b"$ \x01\xa0\xff")),
                ASDb(bytearray(b"%\xc0\x06\x80\xff")),
                ASPause(25),
                ASBPL262728(),
                ASPause(10),
                ASSequenceLoopingOff(),
                ASPause(48),
                ASPlaySound(sound=SO024_TAPPING_FEET, channel=4),
                ASSetSequenceSpeed(FASTER),
                ASSequenceLoopingOn(),
                ASPause(64),
                ASSequenceLoopingOff(),
                ASSetSequenceSpeed(NORMAL),
                ASPlaySound(sound=SO000_SILENCE, channel=4),
            ]),
        RunDialog(
            dialog_id=DI3075_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASSetWalkingSpeed(NORMAL),
                ASWalkToXYCoords(x=25, y=14),
                ASFaceSoutheast(),
            ]),
        Pause(16),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASPlaySound(sound=SO024_TAPPING_FEET, channel=4),
                ASSetSequenceSpeed(FASTER),
                ASSequenceLoopingOn(),
                ASPause(64),
                ASSequenceLoopingOff(),
                ASSetSequenceSpeed(NORMAL),
                ASPlaySound(sound=SO000_SILENCE, channel=4),
            ]),
        RunDialog(
            dialog_id=DI3076_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        Pause(16),
        ActionQueueAsync(
            target=SCREEN_FOCUS,
            subscript=[ASSetWalkingSpeed(SLOW), ASWalkToXYCoords(x=22, y=0)]),
        Pause(96),
        RunDialog(
            dialog_id=DI3085_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        Pause(32),
        PlaySound(sound=SO127_LIGHT_RATTLE, channel=6),
        ActionQueueAsync(
            target=NPC_0,
            subscript=[
                ASSetSpriteSequence(
                    index=0, is_mold=True, is_sequence=True, looping=True
                ),
                ASVisibilityOn(),
            ]),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASSetSpriteSequence(
                    index=0,
                    sprite_offset=3,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True)
            ]),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASDb(bytearray(b" \x07")),
                ASDb(bytearray(b"$\xe0\xfe`\x00")),
                ASDb(bytearray(b"%\xc0\x06\x80\xff")),
                ASPause(32),
                ASBPL262728(),
            ]),
        SetAsyncActionScript(NPC_3, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        Pause(24),
        SetAsyncActionScript(MARIO, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        Pause(32),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASSetSpriteSequence(
                    index=0,
                    sprite_offset=3,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True)
            ]),
        PlaySound(sound=SO128_FLOATING_HOVERING, channel=6),
        ActionQueueSync(
            target=NPC_0,
            subscript=[
                ASSetSequenceSpeed(NORMAL),
                ASSetSpriteSequence(index=0, looping=False),
                ASPause(64),
                ASSetSpriteSequence(
                    index=14, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        Pause(40),
        SummonObjectToCurrentLevel(NPC_1),
        ActionQueueAsync(
            target=NPC_1,
            subscript=[
                ASSetSequenceSpeed(NORMAL),
                ASSetSpriteSequence(index=0, looping=False),
                ASPause(64),
                ASSetSpriteSequence(
                    index=14, is_mold=True, is_sequence=True, looping=True
                ),
            ]),
        PlaySound(sound=SO000_SILENCE, channel=6),
        Pause(48),
        RunDialog(
            dialog_id=DI3098_GARDENER_CUTSCENE,
            above_object=NPC_14,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False),
        Pause(16),
        SetAsyncActionScript(MARIO, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        ActionQueueSync(
            target=NPC_3,
            subscript=[ASPlaySound(sound=SO004_JUMP, channel=4), ASJumpToHeight(160)]),
        RunDialog(
            dialog_id=DI3099_GARDENER_CUTSCENE,
            above_object=NPC_14,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False),
        Pause(24),
        SetSyncActionScript(NPC_3, A0856_GARDENER_RUNS_IN_CIRCLES),
        SpeedUpMusicTempoBy(duration=0, change=32),
        Pause(2),
        RunDialog(
            dialog_id=DI3100_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        SetBit(TEMP_7043_0),
        Pause(1, identifier="EVENT_2392_pause_236"),
        JmpIfBitSet(TEMP_7043_1, ["EVENT_2392_pause_239"]),
        Jmp(["EVENT_2392_pause_236"]),
        Pause(4, identifier="EVENT_2392_pause_239"),
        SlowDownMusicTempoBy(duration=0, change=0),
        Pause(32),
        RunDialog(
            dialog_id=DI3101_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASSetSpriteSequence(
                    index=1,
                    sprite_offset=3,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
                ASPlaySound(sound=SO022_CLOSE_DOOR, channel=4),
            ]),
        SetSyncActionScript(SCREEN_FOCUS, A0391_CAMERA_SHAKE),
        Pause(8),
        RunDialog(
            dialog_id=DI3102_GARDENER_CUTSCENE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        Pause(8),
        SetAsyncActionScript(MARIO, A0857_PLAYER_DENIES_GARDENER),
        SetAsyncActionScript(MARIO, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        UnfreezeCamera(),
        Return(),
    ]
)
