# pylint: disable=C0301

"""E0942_KEEP_FIRST_BOSS_SUMMON_CHEST"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        ActionQueueAsync(
            target=NPC_1,
            subscript=[
                ASFaceSoutheast(),
                ASPause(60),
                ASSetSpriteSequence(
                    index=6,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
                ASPause(4),
                ASSetSpriteSequence(
                    index=7,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
                ASPause(4),
                ASSetSpriteSequence(
                    index=8,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
                ASPause(4),
                ASSetSpriteSequence(
                    index=9,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
                ASPause(4),
                ASSetSpriteSequence(
                    index=10,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
                ASPause(4),
                ASSetSpriteSequence(
                    index=11,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
                ASPause(4),
                ASSetSpriteSequence(
                    index=12,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
                ASPause(15),
            ]),
        ActionQueueAsync(
            target=NPC_1,
            subscript=[
                ASPause(10),
                ASSetSpriteSequence(
                    index=13,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
                ASPause(4),
                ASSetSpriteSequence(
                    index=14,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
                ASPause(4),
                ASStartLoopNTimes(4),
                ASSetSpriteSequence(
                    index=15,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
                ASPause(4),
                ASSetSpriteSequence(
                    index=16,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
                ASPause(4),
                ASSetSpriteSequence(
                    index=17,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True),
                ASPause(4),
                ASEndLoop(),
            ]),
        Return(),
    ]
)
