# E2342_TOWER_SEESAW_CHEST_CONTD

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        JmpIfBitClear(TEMP_7043_1, ["EVENT_2342_set_action_script_sync_49"]),
        JmpIfBitSet(
            TOWER_SEESAW_CHEST_OPENED, ["EVENT_2342_set_action_script_sync_49"]
        ),
        EnableControls([]),
        FreezeCamera(),
        SetSyncActionScript(NPC_4, A0738_TOWER_CHEST_SEESAW_WHEN_ACTIVATED),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASPlaySound(sound=SO033_JUMPING_BOUNCING_FISH, channel=4),
                ASDb(bytearray(b" \x04")),
                ASDb(bytearray(b"%\x00\x0f\xe1\xff")),
                ASPause(56),
                ASPlaySound(sound=SO019_LONG_FALL, channel=4),
                ASPause(199),
                ASBPL262728(),
                ASPlaySound(sound=SO022_CLOSE_DOOR, channel=6),
                ASShiftZUpPixels(12),
            ],
        ),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASSetPriority(3),
                ASSetVRAMPriority(OBJECT_OVERLAPS_MARIO_ON_ALL_SIDES),
                ASSetSpriteSequence(
                    index=7,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
                ASPause(16),
                ASSetSpriteSequence(
                    index=3,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
                ASPause(32),
                ASSetSpriteSequence(
                    index=23,
                    sprite_offset=2,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                ),
                ASPause(48),
                ASSetSpriteSequence(
                    index=24,
                    sprite_offset=2,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                ),
                ASPause(127),
                ASSetSpriteSequence(
                    index=23,
                    sprite_offset=2,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                ),
                ASPause(16),
                ASSetSpriteSequence(
                    index=3,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
                ASPause(8),
                ASSetSpriteSequence(
                    index=7,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
                ASPause(16),
                ASSetSpriteSequence(
                    index=4,
                    sprite_offset=1,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
                ASPlaySound(sound=SO004_JUMP, channel=4),
                ASDb(bytearray(b" \x04")),
                ASDb(bytearray(b"%P\x0f\x80\xff")),
                ASPause(74),
                ASBPL262728(),
                ASShiftToXYCoords(x=18, y=121),
                ASSetSpriteSequence(
                    index=3,
                    is_mold=True,
                    is_sequence=True,
                    looping=True,
                    mirror_sprite=True,
                ),
            ],
        ),
        ActionQueueSync(
            target=SCREEN_FOCUS,
            subscript=[
                ASPause(248),
                ASSetWalkingSpeed(FASTEST),
                ASShiftNorthSteps(15),
                ASPause(32),
                ASShiftSouthSteps(19),
            ],
        ),
        Pause(255),
        SetSyncActionScript(NPC_3, A0739_TOWER_SEESAW_CHEST_ITEM),
        Pause(32),
        SetSyncActionScript(NPC_0, A0007_HIT_TREASURE_CHEST_CONTENTS_DEPLETED),
        Pause(8),
        ActionQueueSync(target=NPC_0, subscript=[ASSetVRAMPriority(NORMAL_PRIORITY)]),
        Set7016701BToObjectXYZ(NPC_0),
        AddConstToVar(Z_COORD_2, 304),
        ActionQueueSync(
            target=NPC_3,
            subscript=[
                ASTransferTo70167018701A(),
                ASShadowOff(),
                ASVisibilityOn(),
                ASSetVRAMPriority(OBJECT_OVERLAPS_MARIO_ON_ALL_SIDES),
                ASSetWalkingSpeed(NORMAL),
            ],
        ),
        PlaySound(sound=SO014_FLOWER, channel=6),
        Pause(16),
        SetSyncActionScript(NPC_4, A0738_TOWER_CHEST_SEESAW_WHEN_ACTIVATED),
        ActionQueueAsync(target=NPC_1, subscript=[ASJumpToHeight(108), ASPause(28)]),
        ActionQueueSync(target=NPC_1, subscript=[ASShiftZUpPixels(12)]),
        Pause(1),
        SetAsyncActionScript(MARIO, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        SetSyncActionScript(NPC_4, A0739_TOWER_SEESAW_CHEST_ITEM),
        ActionQueueAsync(
            target=MARIO, subscript=[ASJumpToHeight(108), ASWalk1StepSouth()]
        ),
        Pause(8),
        PlaySound(sound=SO085_FLOWER, channel=6),
        SetSyncActionScript(MARIO, A0385_LOOK_UP_AT_TOWER_SEESAW_CHEST),
        RunEventAsSubroutine(E0178_NPC_QUEST_1_CONTAINER),
        SetAsyncActionScript(MARIO, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        SetBit(TOWER_SEESAW_CHEST_OPENED),
        ClearBit(TEMP_7043_0),
        DisableObjectTriggerInSpecificLevel(
            NPC_0, R197_BOOSTER_TOWER_1F_AREA_02_HIGH_MASHER_ROOM_WTEETERTOTTER
        ),
        RemoveObjectFromCurrentLevel(NPC_3),
        EnableControls([LEFT, RIGHT, DOWN, UP, X, A, Y, B]),
        UnfreezeCamera(),
        Return(),
        SetSyncActionScript(
            NPC_4,
            A0738_TOWER_CHEST_SEESAW_WHEN_ACTIVATED,
            identifier="EVENT_2342_set_action_script_sync_49",
        ),
        ActionQueueAsync(
            target=NPC_1,
            subscript=[
                ASPlaySound(sound=SO033_JUMPING_BOUNCING_FISH, channel=4),
                ASJumpToHeight(108),
                ASPause(28),
            ],
        ),
        ActionQueueSync(target=NPC_1, subscript=[ASShiftZUpPixels(12)]),
        Pause(1),
        SetAsyncActionScript(NPC_4, A0739_TOWER_SEESAW_CHEST_ITEM),
        Set7000ToObjectCoord(object=MARIO, coord=COORD_Z, pixel=True, bit_7=True),
        JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 1, ["EVENT_2342_freeze_camera_58"]),
        ClearBit(TEMP_7043_0),
        Return(),
        FreezeCamera(identifier="EVENT_2342_freeze_camera_58"),
        ActionQueueAsync(target=MARIO, subscript=[ASJumpToHeight(108)]),
        UnfreezeCamera(),
        ClearBit(TEMP_7043_0),
        Return(),
    ]
)
