# E3352_DR_TOPPER_QUIZ

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        ClearBit(TEMP_7044_7),
        SetSyncActionScript(
            NPC_0, A0059_SEWER_STAIR_UPPER_RIGHT_RAT_PACING_AND_BOWSERS_KEEP_GAME_MOLDS
        ),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASSetPriority(3),
                ASWalkToXYCoords(x=5, y=102),
                ASFaceNortheast(),
            ],
        ),
        ActionQueueSync(target=SCREEN_FOCUS, subscript=[ASWalkToXYCoords(x=1, y=75)]),
        SetBit(TEMP_7044_7),
        FadeOutMusicToVolume(duration=4, volume=0),
        Pause(8),
        PlayMusicAtDefaultVolume(M36_EXPLANATION),
        SetVarToConst(ROSE_WAY_7038, 0),
        SetVarToConst(ROSE_WAY_703A, 0),
        SetVarToConst(ROSE_WAY_703C, 0),
        SetVarToConst(SECONDARY_TEMP_7024, 12),
        Jmp(["EVENT_3352_clear_bit_32"], identifier="EVENT_3352_jmp_15"),
        Set7000ToObjectCoord(
            object=MARIO,
            coord=COORD_Z,
            pixel=True,
            identifier="EVENT_3352_set_7000_to_object_coord_16",
        ),
        CompareVarToConst(PRIMARY_TEMP_7000, 1024),
        JmpIfLoadedMemoryIsBelow0(["EVENT_3352_clear_bit_111"]),
        Dec(SECONDARY_TEMP_7024),
        JmpIfLoadedMemoryIsNot0(["EVENT_3352_jmp_15"]),
        ClearBit(TEMP_7044_7),
        SetSyncActionScript(
            NPC_0, A0059_SEWER_STAIR_UPPER_RIGHT_RAT_PACING_AND_BOWSERS_KEEP_GAME_MOLDS
        ),
        PlayMusicAtDefaultVolume(M66_BOWSERS_CASTLE_2ND_TIME),
        SlowDownMusic(),
        RunDialog(
            dialog_id=DI1887_QUIZ_FAILED,
            above_object=NPC_12,
            closable=True,
            sync=True,
            multiline=True,
            use_background=False,
        ),
        SetBit(TEMP_7044_7),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASSetObjectMemoryBits(arg_1=0x0B, bits=[0, 1]),
                ASShiftZDownSteps(4),
            ],
        ),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASSetSpriteSequence(
                    index=12, sprite_offset=2, is_sequence=True, looping=True
                ),
                ASPause(2),
            ],
        ),
        Pause(180),
        FadeOutToBlack(sync=False),
        JmpToEvent(E3356_KEEP_RESPAWN_IN_LOBBY_UPON_FAILURE),
        ClearBit(TEMP_7044_5, identifier="EVENT_3352_clear_bit_32"),
        JmpIfRandom2of3(["EVENT_3352_set_short_43", "EVENT_3352_set_short_52"]),
        SetVarToConst(TEMP_7034, 1842),
        CopyVarToVar(from_var=ROSE_WAY_7038, to_var=UNKNOWN_7036),
        SetVarToConst(TEMP_7032, 16),
        JmpToSubroutine(["EVENT_3352_set_short_61"]),
        JmpIfBitSet(TEMP_7044_5, ["EVENT_3352_clear_bit_32"]),
        CopyVarToVar(from_var=UNKNOWN_7036, to_var=ROSE_WAY_7038),
        JmpIfBitSet(TEMP_7044_6, ["EVENT_3352_pause_107"]),
        JmpIfDialogOptionBOrCSelected(["EVENT_3352_pause_103", "EVENT_3352_pause_103"]),
        Jmp(["EVENT_3352_pause_99"]),
        SetVarToConst(TEMP_7034, 1858, identifier="EVENT_3352_set_short_43"),
        CopyVarToVar(from_var=ROSE_WAY_703A, to_var=UNKNOWN_7036),
        SetVarToConst(TEMP_7032, 16),
        JmpToSubroutine(["EVENT_3352_set_short_61"]),
        JmpIfBitSet(TEMP_7044_5, ["EVENT_3352_clear_bit_32"]),
        CopyVarToVar(from_var=UNKNOWN_7036, to_var=ROSE_WAY_703A),
        JmpIfBitSet(TEMP_7044_6, ["EVENT_3352_pause_107"]),
        JmpIfDialogOptionBOrCSelected(["EVENT_3352_pause_99", "EVENT_3352_pause_103"]),
        Jmp(["EVENT_3352_pause_103"]),
        SetVarToConst(TEMP_7034, 1874, identifier="EVENT_3352_set_short_52"),
        CopyVarToVar(from_var=ROSE_WAY_703C, to_var=UNKNOWN_7036),
        SetVarToConst(TEMP_7032, 8),
        JmpToSubroutine(["EVENT_3352_set_short_61"]),
        JmpIfBitSet(TEMP_7044_5, ["EVENT_3352_clear_bit_32"]),
        CopyVarToVar(from_var=UNKNOWN_7036, to_var=ROSE_WAY_703C),
        JmpIfBitSet(TEMP_7044_6, ["EVENT_3352_pause_107"]),
        JmpIfDialogOptionBOrCSelected(["EVENT_3352_pause_103", "EVENT_3352_pause_99"]),
        Jmp(["EVENT_3352_pause_103"]),
        SetVarToConst(TEMP_7026, 1, identifier="EVENT_3352_set_short_61"),
        GenerateRandomNumFromRangeVar(TEMP_7032),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=ROSE_WAY_703E),
        JmpIfVarEqualsConst(
            PRIMARY_TEMP_7000, 0, ["EVENT_3352_set_7000_to_7000_short_mem_68"]
        ),
        SetObjectMemoryToVar(PRIMARY_TEMP_7000),
        VarShiftLeft(TEMP_7026, 255),
        EndLoop(),
        CopyVarToVar(
            from_var=UNKNOWN_7036,
            to_var=PRIMARY_TEMP_7000,
            identifier="EVENT_3352_set_7000_to_7000_short_mem_68",
        ),
        Mem7000AndVar(TEMP_7026),
        CompareVarToConst(PRIMARY_TEMP_7000, 0),
        JmpIfLoadedMemoryIsNot0(["EVENT_3352_set_bit_97"]),
        CopyVarToVar(from_var=UNKNOWN_7036, to_var=PRIMARY_TEMP_7000),
        Mem7000OrVar(TEMP_7026),
        CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=UNKNOWN_7036),
        CopyVarToVar(from_var=ROSE_WAY_703E, to_var=PRIMARY_TEMP_7000),
        AddVarTo7000(TEMP_7034),
        ClearBit(TEMP_7044_7),
        SetSyncActionScript(
            NPC_0, A0059_SEWER_STAIR_UPPER_RIGHT_RAT_PACING_AND_BOWSERS_KEEP_GAME_MOLDS
        ),
        RunDialog(
            dialog_id=PRIMARY_TEMP_7000,
            above_object=NPC_12,
            closable=False,
            sync=True,
            multiline=True,
            use_background=False,
        ),
        ClearBit(TEMP_7044_6),
        PauseScriptResumeOnNextDialogPageB(),
        SetBit(TEMP_7044_7),
        SetVarToConst(TEMP_7028, 30),
        StartLoopNFrames(299),
        Pause(1),
        SetVarToRandom(PRIMARY_TEMP_7000, 256),
        Inc(TEMP_7028),
        JmpIfVarNotEqualsConst(
            TEMP_7028, 60, ["EVENT_3352_if_0210_bits_012_clear_do_not_jump_91"]
        ),
        PlaySound(sound=SO144_CLICK, channel=4),
        SetVarToConst(TEMP_7028, 0),
        If0210Bits012ClearDoNotJump(
            ["EVENT_3352_end_loop_93"],
            identifier="EVENT_3352_if_0210_bits_012_clear_do_not_jump_91",
        ),
        Jmp(["EVENT_3352_close_dialog_95"]),
        EndLoop(identifier="EVENT_3352_end_loop_93"),
        SetBit(TEMP_7044_6),
        CloseDialog(identifier="EVENT_3352_close_dialog_95"),
        Return(),
        SetBit(TEMP_7044_5, identifier="EVENT_3352_set_bit_97"),
        Return(),
        Pause(4, identifier="EVENT_3352_pause_99"),
        PlaySound(sound=SO087_CORRECT_SIGNAL, channel=6),
        ActionQueueAsync(target=NPC_1, subscript=[ASShiftZUpPixels(7)]),
        Jmp(["EVENT_3352_set_7000_to_object_coord_16"]),
        Pause(4, identifier="EVENT_3352_pause_103"),
        PlaySound(sound=SO088_WRONG_SIGNAL, channel=6),
        ActionQueueAsync(target=NPC_1, subscript=[ASShiftZDownPixels(14)]),
        Jmp(["EVENT_3352_set_7000_to_object_coord_16"]),
        Pause(4, identifier="EVENT_3352_pause_107"),
        PlaySound(sound=SO088_WRONG_SIGNAL, channel=6),
        ActionQueueAsync(target=NPC_1, subscript=[ASShiftZDownPixels(7)]),
        Jmp(["EVENT_3352_set_7000_to_object_coord_16"]),
        ClearBit(TEMP_7044_7, identifier="EVENT_3352_clear_bit_111"),
        SetSyncActionScript(
            NPC_0, A0059_SEWER_STAIR_UPPER_RIGHT_RAT_PACING_AND_BOWSERS_KEEP_GAME_MOLDS
        ),
        Pause(8),
        PlayMusicAtDefaultVolume(M09_VICTORY),
        RunDialog(
            dialog_id=DI1886_DUPLICATE,
            above_object=NPC_12,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False,
        ),
        SetBit(TEMP_7044_7),
        Pause(32),
        ActionQueueSync(
            target=NPC_0, subscript=[ASSetSpriteSequence(index=3, looping=False)]
        ),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASPause(38),
                ASSetWalkingSpeed(VERY_FAST),
                ASAddZCoord1Step(),
                ASStartLoopNTimes(7),
                ASShiftZDownPixels(4),
                ASShiftZUpPixels(4),
                ASEndLoop(),
            ],
        ),
        ActionQueueSync(
            target=MARIO,
            subscript=[
                ASPause(38),
                ASJumpToHeight(256),
                ASShiftNortheastSteps(4),
                ASPause(
                    1, identifier="EVENT_3352_action_queue_sync_120_SUBSCRIPT_pause_3"
                ),
                ASJmpIfMarioInAir(
                    ["EVENT_3352_action_queue_sync_120_SUBSCRIPT_pause_3"]
                ),
                ASPlaySound(sound=SO058_INSERT, channel=4),
                ASObjectMemoryModifyBits(arg_1=0x09, set_flags=[5], clear_bits=[4, 6]),
                ASSetBit(TEMP_7044_6),
                ASPause(8),
                ASShiftNortheastSteps(2),
                ASSetBit(TEMP_7044_5),
            ],
        ),
        Pause(1, identifier="EVENT_3352_pause_121"),
        JmpIfBitClear(TEMP_7044_6, ["EVENT_3352_pause_121"]),
        PlaySound(sound=SO016_OPEN_DOOR, channel=4),
        ApplyTileModToLevel(
            use_alternate=True,
            room_id=R464_BOWSERS_KEEP_6DOOR_PUZZLE_ROOM_1A_QUIZ,
            mod_id=0,
        ),
        Pause(1, identifier="EVENT_3352_pause_125"),
        JmpIfBitClear(TEMP_7044_5, ["EVENT_3352_pause_125"]),
        JmpToEvent(E1953_KEEP_QUIZ_ROOM_EXIT_CONTAINER),
        Return(),
    ]
)
