# E1872_FIREWORKS_HOUSE_BUY_ITEM

from randomizer.scripts.event.script_imports import *

script = EventScript([
	CopyVarToVar(from_var=ACTIVE_NPC, to_var=PRIMARY_TEMP_7000),
	CopyVarToVar(from_var=PRIMARY_TEMP_7000, to_var=TEMP_70AE),
	JmpIfBitSet(FIREWORKS_HOUSE_ITEM_SOLD, ["EVENT_1872_run_dialog_8__"]),
	JmpIfBitSet(PROGRESSIVE_FIREWORKS_ENABLED, ["EVENT_1872_run_dialog_8_"]),
	JmpIfBitSet(SHUFFLE_ONE_FIREWORKS_ENABLED, ["EVENT_1872_run_dialog_8_"]),
	StoreItemAmountTo7000(Fireworks),
	JmpIfVarEqualsConst(PRIMARY_TEMP_7000, 0, ["EVENT_1872_jmp_if_bit_set_6"]),
	RunDialog(dialog_id=DI1297_CANT_SELL_MORE_THAN_ONE_FIREWORKS, above_object=MEM_70A8, closable=True, sync=False, multiline=True, use_background=True),
	Return(),
	JmpIfBitSet(FIRST_CARBO_COOKIE_GIVEN, ["EVENT_1872_run_dialog_8"], identifier="EVENT_1872_jmp_if_bit_set_6"),
	RunDialog(dialog_id=DI1289_FIREWORKS_GUY_FIREWORKS, above_object=MEM_70A8, closable=True, sync=False, multiline=True, use_background=True, identifier="EVENT_1872_run_dialog_8"),
	JmpIfDialogOptionBSelected(["EVENT_1872_pause_38"]),
	Pause(10),
	SetAsyncActionScript(MARIO, A0670_NOD_YES),
	StoreCoinCountTo7000(),
	CompareVarToConst(PRIMARY_TEMP_7000, 500),
	JmpIfComparisonResultIsGreaterOrEqual(["EVENT_1872_play_sound_17"]),
	RunDialog(dialog_id=DI1293_FIREWORKS_GUY_INSUFFICIENT_COINS, above_object=MEM_70A8, closable=True, sync=False, multiline=True, use_background=True, identifier="EVENT_1872_run_dialog_15"),
	Return(),
	PlaySound(sound=SO055_LOSE_COINS_COIN_FOUNTAIN, channel=6, identifier="EVENT_1872_play_sound_17"),
	SetVarToConst(PRIMARY_TEMP_7000, 500),
	Dec7000FromCoins(),
	JmpIfVarEqualsConst(FIREWORKS_COUNTER, 5, ["EVENT_1872_play_sound_34"]),
	Inc(FIREWORKS_COUNTER),
	PlaySound(sound=SO085_FLOWER, channel=6, identifier="EVENT_1872_play_sound_34"),
	RunDialog(dialog_id=DI1294_GOT_FIREWORKS, above_object=BOWSER, closable=True, sync=False, multiline=True, use_background=False),
	AddToInventory(Fireworks),
	Return(),
	Pause(10, identifier="EVENT_1872_pause_38"),
	SetAsyncActionScript(MARIO, A0671_SHAKE_HEAD_NO),
	Return(),
	RunDialog(dialog_id=DI1288_FIREWORKS_GUY_MYSTERY_ITEM, above_object=MEM_70A8, closable=True, sync=False, multiline=True, use_background=True, identifier="EVENT_1872_run_dialog_8_"),
	JmpIfDialogOptionBSelected(["EVENT_1872_pause_38"]),
	Pause(10),
	SetAsyncActionScript(MARIO, A0670_NOD_YES),
	StoreCoinCountTo7000(),
	CompareVarToConst(PRIMARY_TEMP_7000, 500),
	JmpIfComparisonResultIsGreaterOrEqual(["EVENT_1872_set_18_"]),
	Jmp(["EVENT_1872_run_dialog_15"]),
	SetVarToConst(PRIMARY_TEMP_7000, 500, identifier="EVENT_1872_set_18_"),
	Dec7000FromCoins(),
	SetBit(FIREWORKS_HOUSE_ITEM_SOLD),
	RunEventAsSubroutine(E0178_NPC_QUEST_1_CONTAINER),
	Return(),
	RunDialog(dialog_id=DI1287_DUPLICATE, above_object=MEM_70A8, closable=True, sync=False, multiline=True, use_background=True, identifier="EVENT_1872_run_dialog_8__"),
	Return()
])
