# pylint: disable=C0301

"""E0604_MARRYMORE_INN_BRIGHT_CARD_ENTHUSIAST"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        StoreItemAmountTo7000(BrightCard),
        JmpIfVarNotEqualsConst(PRIMARY_TEMP_7000, 0, ["EVENT_604_run_dialog_5"]),
        JmpIfBitSet(BRIGHT_CARD_SOLD, ["EVENT_604_run_dialog_39"]),
        RunDialog(
            dialog_id=DI2057_BRIGHT_CARD_SALE_HINT,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        Return(),
        RunDialog(
            dialog_id=DI2054_PROMPT_TO_SELL_BRIGHT_CARD,
            above_object=MEM_70A8,
            closable=False,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_604_run_dialog_5"),
        JmpIfDialogOptionBSelected(["EVENT_604_set_action_script_async_17"]),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        Pause(10),
        PlaySound(sound=SO013_COIN, channel=6),
        AddCoins(100),
        RemoveOneOfItemFromInventory(
            BrightCard, identifier="EVENT_604_remove_one_from_inventory_11"
        ),
        SetBit(BRIGHT_CARD_SOLD),
        RunDialog(
            dialog_id=DI2077_BRIGHT_CARD_BUYER,
            above_object=NPC_12,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False),
        RunDialog(
            dialog_id=DI2468_BRIGHT_CARD_BUYER,
            above_object=MARIO,
            closable=True,
            sync=False,
            multiline=False,
            use_background=False),
        RunDialog(
            dialog_id=DI2469_BRIGHT_CARD_BUYER,
            above_object=NPC_12,
            closable=True,
            sync=False,
            multiline=True,
            use_background=False),
        Return(),
        SetAsyncActionScript(
            MARIO,
            A0671_SHAKE_HEAD_NO,
            identifier="EVENT_604_set_action_script_async_17"),
        Pause(10),
        RunDialog(
            dialog_id=DI2108_BRIGHT_CARD_HAGGLE,
            above_object=MEM_70A8,
            closable=False,
            sync=False,
            multiline=True,
            use_background=True),
        JmpIfDialogOptionBSelected(["EVENT_604_set_action_script_async_26"]),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        Pause(10),
        PlaySound(sound=SO094_FROG_COIN, channel=6),
        AddFrogCoins(5),
        Jmp(["EVENT_604_remove_one_from_inventory_11"]),
        SetAsyncActionScript(
            MARIO,
            A0671_SHAKE_HEAD_NO,
            identifier="EVENT_604_set_action_script_async_26"),
        Pause(10),
        RunDialog(
            dialog_id=DI2307_BRIGHT_CARD_HAGGLE,
            above_object=MEM_70A8,
            closable=False,
            sync=False,
            multiline=True,
            use_background=True),
        JmpIfDialogOptionBSelected(["EVENT_604_set_action_script_async_35"]),
        SetAsyncActionScript(MARIO, A0670_NOD_YES),
        Pause(10),
        PlaySound(sound=SO094_FROG_COIN, channel=6),
        AddFrogCoins(10),
        Jmp(["EVENT_604_remove_one_from_inventory_11"]),
        SetAsyncActionScript(
            MARIO,
            A0671_SHAKE_HEAD_NO,
            identifier="EVENT_604_set_action_script_async_35"),
        Pause(10),
        RunDialog(
            dialog_id=DI2308_BRIGHT_CARD_HAGGLE,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        Return(),
        RunDialog(
            dialog_id=DI2329_BRIGHT_CARD_BUY_BACK_PROMPT,
            above_object=MEM_70A8,
            closable=False,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_604_run_dialog_39"),
        JmpIfDialogOptionBSelected(["EVENT_604_run_dialog_53"]),
        StoreFrogCoinCountTo7000(),
        CompareVarToConst(PRIMARY_TEMP_7000, 15),
        JmpIfComparisonResultIsLesser(["EVENT_604_run_dialog_51"]),
        RunDialog(
            dialog_id=DI2334_BRIGHT_CARD_BUY_BACK,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True),
        SetVarToConst(PRIMARY_TEMP_7000, 15),
        PlaySound(sound=SO094_FROG_COIN, channel=6),
        Dec7000FromFrogCoins(),
        AddToInventory(BrightCard),
        ClearBit(BRIGHT_CARD_SOLD),
        Return(),
        RunDialog(
            dialog_id=DI2380_LITTLE_SHORT,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_604_run_dialog_51"),
        Return(),
        RunDialog(
            dialog_id=DI2335_BRIGHT_CARD_DECLINE_BUY_BACK,
            above_object=MEM_70A8,
            closable=True,
            sync=False,
            multiline=True,
            use_background=True,
            identifier="EVENT_604_run_dialog_53"),
        Return(),
    ]
)
