# pylint: disable=C0301

"""E1147_SEASIDE_INITIATE_BOSS_FIGHT_ANIMATION"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        ActionQueueSync(target=NPC_6, subscript=[ASSetSequenceSpeed(FAST)]),
        ActionQueueSync(
            target=NPC_0,
            subscript=[
                ASSetWalkingSpeed(NORMAL),
                ASFaceSouthwest(),
                ASFixedFCoordOn(),
                ASWalkSoutheastSteps(2),
                ASFixedFCoordOff(),
                ASFaceSoutheast(),
                ASFixedFCoordOn(),
                ASWalkNortheastSteps(2),
                ASSetWalkingSpeed(FAST),
                ASFixedFCoordOff(),
                ASFaceNortheast(),
                ASFixedFCoordOn(),
                ASWalkNorthwestSteps(2),
                ASFixedFCoordOff(),
                ASFaceNorthwest(),
                ASFixedFCoordOn(),
                ASWalkSouthwestSteps(2),
                ASSetWalkingSpeed(VERY_FAST),
                ASStartLoopNTimes(2),
                ASFaceSouthwest(),
                ASFixedFCoordOn(),
                ASWalkSoutheastSteps(2),
                ASFixedFCoordOff(),
                ASFaceSoutheast(),
                ASFixedFCoordOn(),
                ASWalkNortheastSteps(2),
                ASFixedFCoordOff(),
                ASFaceNortheast(),
                ASFixedFCoordOn(),
                ASWalkNorthwestSteps(2),
                ASFixedFCoordOff(),
                ASFaceNorthwest(),
                ASFixedFCoordOn(),
                ASWalkSouthwestSteps(2),
                ASEndLoop(),
                ASSetWalkingSpeed(FAST),
                ASBounceToXYWithHeight(x=6, y=26, height=0),
                ASVisibilityOff(),
            ]),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASSetWalkingSpeed(NORMAL),
                ASFaceSoutheast(),
                ASFixedFCoordOn(),
                ASWalkNortheastSteps(2),
                ASFixedFCoordOff(),
                ASFaceNortheast(),
                ASFixedFCoordOn(),
                ASWalkNorthwestSteps(2),
                ASSetWalkingSpeed(FAST),
                ASFixedFCoordOff(),
                ASFaceNorthwest(),
                ASFixedFCoordOn(),
                ASWalkSouthwestSteps(2),
                ASFixedFCoordOff(),
                ASFaceSouthwest(),
                ASFixedFCoordOn(),
                ASWalkSoutheastSteps(2),
                ASSetWalkingSpeed(VERY_FAST),
                ASStartLoopNTimes(2),
                ASFaceSoutheast(),
                ASFixedFCoordOn(),
                ASWalkNortheastSteps(2),
                ASFixedFCoordOff(),
                ASFaceNortheast(),
                ASFixedFCoordOn(),
                ASWalkNorthwestSteps(2),
                ASFixedFCoordOff(),
                ASFaceNorthwest(),
                ASFixedFCoordOn(),
                ASWalkSouthwestSteps(2),
                ASFixedFCoordOff(),
                ASFaceSouthwest(),
                ASFixedFCoordOn(),
                ASWalkSoutheastSteps(2),
                ASEndLoop(),
                ASSetWalkingSpeed(FAST),
                ASBounceToXYWithHeight(x=6, y=26, height=0),
                ASVisibilityOff(),
            ]),
        ActionQueueSync(
            target=NPC_2,
            subscript=[
                ASSetWalkingSpeed(NORMAL),
                ASFaceNorthwest(),
                ASFixedFCoordOn(),
                ASWalkSouthwestSteps(2),
                ASFixedFCoordOff(),
                ASFaceSouthwest(),
                ASFixedFCoordOn(),
                ASWalkSoutheastSteps(2),
                ASSetWalkingSpeed(FAST),
                ASFixedFCoordOff(),
                ASFaceSoutheast(),
                ASFixedFCoordOn(),
                ASWalkNortheastSteps(2),
                ASFixedFCoordOff(),
                ASFaceNortheast(),
                ASFixedFCoordOn(),
                ASWalkNorthwestSteps(2),
                ASSetWalkingSpeed(VERY_FAST),
                ASStartLoopNTimes(2),
                ASFaceNorthwest(),
                ASFixedFCoordOn(),
                ASWalkSouthwestSteps(2),
                ASFixedFCoordOff(),
                ASFaceSouthwest(),
                ASFixedFCoordOn(),
                ASWalkSoutheastSteps(2),
                ASFixedFCoordOff(),
                ASFaceSoutheast(),
                ASFixedFCoordOn(),
                ASWalkNortheastSteps(2),
                ASFixedFCoordOff(),
                ASFaceNortheast(),
                ASFixedFCoordOn(),
                ASWalkNorthwestSteps(2),
                ASEndLoop(),
                ASSetWalkingSpeed(FAST),
                ASBounceToXYWithHeight(x=6, y=26, height=0),
                ASVisibilityOff(),
            ]),
        ActionQueueAsync(
            target=NPC_3,
            subscript=[
                ASSetWalkingSpeed(NORMAL),
                ASFaceNortheast(),
                ASFixedFCoordOn(),
                ASWalkNorthwestSteps(2),
                ASFixedFCoordOff(),
                ASFaceNorthwest(),
                ASFixedFCoordOn(),
                ASWalkSouthwestSteps(2),
                ASSetWalkingSpeed(FAST),
                ASFixedFCoordOff(),
                ASFaceSouthwest(),
                ASFixedFCoordOn(),
                ASWalkSoutheastSteps(2),
                ASFixedFCoordOff(),
                ASFaceSoutheast(),
                ASFixedFCoordOn(),
                ASWalkNortheastSteps(2),
                ASPlaySound(sound=SO089_LIT_FUSE, channel=6),
                ASSetWalkingSpeed(VERY_FAST),
                ASStartLoopNTimes(2),
                ASFaceNortheast(),
                ASFixedFCoordOn(),
                ASWalkNorthwestSteps(2),
                ASFixedFCoordOff(),
                ASFaceNorthwest(),
                ASFixedFCoordOn(),
                ASWalkSouthwestSteps(2),
                ASFixedFCoordOff(),
                ASFaceSouthwest(),
                ASFixedFCoordOn(),
                ASWalkSoutheastSteps(2),
                ASFixedFCoordOff(),
                ASFaceSoutheast(),
                ASFixedFCoordOn(),
                ASWalkNortheastSteps(2),
                ASEndLoop(),
                ASSetWalkingSpeed(FAST),
                ASBounceToXYWithHeight(x=6, y=26, height=0),
                ASVisibilityOff(),
            ]),
        PlaySound(sound=SO148_SURGING_ELECTRICITY, channel=6),
        FadeOutMusicToVolume(duration=8, volume=0),
        PaletteSetMorphs(palette_type=NOTHING, palette_set=2, duration=214, row=11),
        Pause(60),
        ScreenFlashesWithColour(WHITE),
        Pause(20),
        ScreenFlashesWithColour(WHITE),
        Pause(10),
        ScreenFlashesWithColour(WHITE),
        Pause(10),
        ScreenFlashesWithColour(WHITE),
        Pause(10),
        ScreenFlashesWithColour(WHITE),
        ActionQueueAsync(
            target=NPC_7,
            subscript=[
                ASTransferToXYZF(x=6, y=26, z=0, direction=EAST),
                ASFaceSoutheast(),
                ASVisibilityOn(),
            ]),
        SetSyncActionScript(NPC_7, A0527_SEASIDE_BOSS_TRANSFORM),
        Pause(7),
        ScreenFlashesWithColour(WHITE),
        Pause(7),
        ScreenFlashesWithColour(WHITE),
        SetSyncActionScript(NPC_6, A0527_SEASIDE_BOSS_TRANSFORM),
        Pause(10),
        StartLoopNTimes(6),
        ScreenFlashesWithColour(WHITE),
        Pause(5),
        EndLoop(),
        RemoveObjectFromCurrentLevel(NPC_6),
        PauseActionScript(NPC_7),
        ActionQueueAsync(
            target=NPC_7,
            subscript=[
                ASVisibilityOn(),
                ASSetSequenceSpeed(NORMAL),
                ASSetSpriteSequence(
                    index=0, is_sequence=True, looping=False, mirror_sprite=True
                ),
            ]),
        PlaySound(sound=SO091_TUMBLING_BOULDERS, channel=6),
        Pause(8),
        ScreenFlashesWithColour(WHITE),
        Pause(10),
        ScreenFlashesWithColour(WHITE),
        Pause(45),
        RunEventAsSubroutine(E0354_BOSS_BATTLE_CONTAINER),
        JmpIfBitClear(GAME_OVER, ["EVENT_1147_play_music_default_volume_42"]),
        ResetAndChooseGame(),
        PlayMusicAtDefaultVolume(
            M05_SEASIDE_TOWN, identifier="EVENT_1147_play_music_default_volume_42"
        ),
        EnterArea(
            room_id=R316_SEASIDE_TOWN_BEACH, face_direction=NORTHWEST, x=8, y=30, z=0
        ),
        SetBit(SEASIDE_LIBERATED),
        RemoveObjectFromSpecificLevel(
            NPC_0, R213_SEASIDE_TOWN_DURING_YARIDOVICH_BEETLES_ARE_USBOMB_SHOP
        ),
        RemoveObjectFromSpecificLevel(
            NPC_1, R213_SEASIDE_TOWN_DURING_YARIDOVICH_BEETLES_ARE_USBOMB_SHOP
        ),
        ActionQueueSync(
            target=SCREEN_FOCUS,
            subscript=[ASSetWalkingSpeed(FASTEST), ASWalkToXYCoords(x=0, y=8)]),
        ActionQueueSync(target=MARIO, subscript=[ASShiftToXYCoords(x=4, y=22)]),
        RunEventAsSubroutine(E1163_SEASIDE_LIBERATED_BEACH),
        PauseScriptUntilEffectDone(),
        SetSyncActionScript(MARIO, A0395_PLAYER_RESET_PROPERTIES_AND_SOLIDITY),
        RestoreAllHP(),
        RestoreAllFP(),
        JmpToEvent(E0168_BOSS_GRANT_STAR_PIECE_CONTAINER),
        Return(),
    ]
)
