# pylint: disable=C0301

"""E3480_MIDAS_RIVER_WATERFALL_LOADER"""

from randomizer.scripts.event.script_imports import *

script = EventScript(
    [
        EnableControls([]),
        FadeOutMusicToVolume(duration=0, volume=8),
        FadeOutSoundToVolume(duration=0, volume=0),
        PlaySound(sound=SO035_RUNNING_WATER, channel=4),
        FadeOutSoundToVolume(duration=2, volume=127),
        SetVarToConst(TEMP_70A9, 32),
        SetVarToConst(X_COORD_2, 4480),
        SetVarToConst(Y_COORD_2, 256),
        SetVarToConst(Z_COORD_2, 0),
        StartLoopNTimes(2),
        ActionQueueAsync(target=MEM_70A9, subscript=[ASDb(bytearray(b"\x99"))]),
        AddConstToVar(X_COORD_2, 128),
        AddConstToVar(Y_COORD_2, 64),
        Inc(TEMP_70A9),
        EndLoop(),
        SetVarToConst(X_COORD_2, 4608),
        SetVarToConst(Y_COORD_2, 512),
        ActionQueueAsync(target=MEM_70A9, subscript=[ASDb(bytearray(b"\x99"))]),
        FadeInFromBlack(sync=True, duration=80),
        JmpIfBitClear(SIGNAL_RING_DIRECTIONAL_BIT, ["EVENT_3480_jmp_if_bit_set_19"]),
        RunEventAsSubroutine(E3588_SIGNAL_RING_ACTIVATOR),
        JmpIfBitClear(SIGNAL_RING_BIT, ["EVENT_3480_jmp_if_bit_set_19"]),
        RunEventAsSubroutine(E3892_MIDAS_RIVER_STAR_PIECE_SIGNAL),
        JmpIfBitSet(
            BUCKET_WARP_BIT,
            ["EVENT_3480_action_queue_async_22"],
            identifier="EVENT_3480_jmp_if_bit_set_19"),
        JmpIfBitSet(UNKNOWN_MIDAS_RIVER_704D_6, ["EVENT_3480_action_queue_async_22"]),
        ActionQueueSync(
            target=NPC_1,
            subscript=[
                ASPause(148),
                ASShiftToXYCoords(x=6, y=73),
                ASVisibilityOn(),
                ASSequenceLoopingOn(),
                ASSetWalkingSpeed(FASTEST),
                ASShiftNorthSteps(27),
                ASVisibilityOff(),
            ]),
        ActionQueueAsync(
            target=MARIO,
            subscript=[
                ASVisibilityOff(),
                ASClearSolidityBits(cant_pass_walls=True),
                ASSetWalkingSpeed(SLOW),
                ASWalk1StepNorth(),
                ASSetWalkingSpeed(NORMAL),
                ASWalk1StepNorth(),
                ASSetWalkingSpeed(FAST),
                ASShiftNorthSteps(2),
                ASSetWalkingSpeed(FASTER),
                ASShiftNorthSteps(3),
                ASSetWalkingSpeed(VERY_FAST),
                ASShiftNorthSteps(34),
                ASSetWalkingSpeed(FASTER),
                ASShiftNorthSteps(3),
                ASSetWalkingSpeed(FAST),
                ASShiftNorthSteps(2),
                ASSetWalkingSpeed(NORMAL),
                ASWalk1StepNorth(),
                ASSetWalkingSpeed(SLOW),
                ASWalk1StepNorth(),
                ASSetWalkingSpeed(NORMAL),
                ASSetSolidityBits(cant_pass_walls=True),
            ],
            identifier="EVENT_3480_action_queue_async_22"),
        FadeOutMusicToVolume(duration=1, volume=56),
        JmpIfBitSet(BUCKET_WARP_BIT, ["EVENT_3480_action_queue_async_30"]),
        JmpIfBitSet(UNKNOWN_MIDAS_RIVER_704D_6, ["EVENT_3480_action_queue_async_28"]),
        ActionQueueAsync(
            target=NPC_1,
            subscript=[
                ASShiftToXYCoords(x=9, y=2),
                ASFixedFCoordOn(),
                ASSequenceLoopingOn(),
                ASWalkNorthPixels(5),
                ASSetWalkingSpeed(NORMAL),
                ASStartLoopNTimes(4),
                ASVisibilityOff(),
                ASPause(2),
                ASVisibilityOn(),
                ASPause(2),
                ASWalkSouthPixels(1),
                ASEndLoop(),
                ASShiftSouthSteps(5),
                ASFixedFCoordOff(),
            ]),
        Jmp(["EVENT_3480_action_queue_sync_31"]),
        ActionQueueAsync(
            target=NPC_1,
            subscript=[
                ASTransferToXYZF(x=10, y=4, z=0, direction=EAST),
                ASFixedFCoordOn(),
                ASSequenceLoopingOn(),
                ASFloatingOn(),
                ASSetWalkingSpeed(SLOW),
                ASStartLoopNTimes(4),
                ASVisibilityOff(),
                ASPause(2),
                ASVisibilityOn(),
                ASPause(2),
                ASEndLoop(),
                ASDb(bytearray(b" \x04")),
                ASDb(bytearray(b"%\x00\x02\xf0\xff")),
                ASPlaySound(sound=SO033_JUMPING_BOUNCING_FISH, channel=4),
                ASWalkSouthwestSteps(2),
                ASSetWalkingSpeed(NORMAL),
                ASShiftSouthSteps(3),
                ASBPL262728(),
                ASFixedFCoordOff(),
            ],
            identifier="EVENT_3480_action_queue_async_28"),
        Jmp(["EVENT_3480_set_action_script_sync_69"]),
        ActionQueueAsync(
            target=NPC_1,
            subscript=[
                ASShiftToXYCoords(x=6, y=8),
                ASFaceNortheast(),
                ASFloatingOn(),
                ASStartLoopNTimes(4),
                ASVisibilityOff(),
                ASPause(2),
                ASVisibilityOn(),
                ASPause(2),
                ASEndLoop(),
                ASSetWalkingSpeed(NORMAL),
                ASShiftSouthSteps(6),
                ASDb(bytearray(b" \x04")),
                ASDb(bytearray(b"%p\x02\xf5\xff")),
                ASPlaySound(sound=SO010_TRAMPOLINE, channel=4),
                ASWalkNortheastSteps(6),
                ASWalk1StepNorth(),
                ASBPL262728(),
            ],
            identifier="EVENT_3480_action_queue_async_30"),
        ActionQueueSync(
            target=NPC_16,
            subscript=[
                ASTransferToObjectXY(NPC_1),
                ASSetSequenceSpeed(VERY_SLOW),
                ASSetVRAMPriority(PRIORITY_3),
                ASSetSpriteSequence(index=0, looping=False),
                ASPause(60),
                ASVisibilityOff(),
            ],
            identifier="EVENT_3480_action_queue_sync_31"),
        SetSyncActionScript(
            MARIO,
            A0466_MIDAS_RIVER_TUNNEL_LEAVE,
            identifier="EVENT_3480_set_action_script_sync_69"),
        JmpToSubroutine(["EVENT_3480_action_queue_async_73"]),
        RunEventAtReturn(E3489_MIDAS_RIVER_WATERFALL_LISTEN_FOR_BUTTON_INPUTS),
        Return(),
        ActionQueueAsync(
            target=NPC_1,
            subscript=[
                ASDb(bytearray(b"\x97\x00")),
                ASVisibilityOn(),
                ASSequenceLoopingOn(),
                ASShadowOff(),
                ASSetObjectMemoryBits(arg_1=0x0E, bits=[2, 3]),
            ],
            identifier="EVENT_3480_action_queue_async_73"),
        Return(),
    ]
)
