# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectsequencedisassembler --rom ROM > openmode_sequence_debug.txt
from randomizer.data.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data.eventtables import RadialDirections, AreaObjects, NPCPackets, Sounds, Coords, CoordUnits, Rooms
script = [
    {
        "identifier": 'ACTION_791_turn_random_direction_0',
        "command": 'turn_random_direction'
    },
    {
        "identifier": 'ACTION_791_pause_1',
        "command": 'pause',
        "args": [12]
    },
    {
        "identifier": 'ACTION_791_turn_random_direction_2',
        "command": 'turn_random_direction'
    },
    {
        "identifier": 'ACTION_791_pause_3',
        "command": 'pause',
        "args": [8]
    },
    {
        "identifier": 'ACTION_791_turn_random_direction_4',
        "command": 'turn_random_direction'
    },
    {
        "identifier": 'ACTION_791_pause_5',
        "command": 'pause',
        "args": [16]
    },
    {
        "identifier": 'ACTION_791_face_northwest_6',
        "command": 'face_northwest'
    },
    {
        "identifier": 'ACTION_791_ret_7',
        "command": 'ret'
    }
]
