# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectsequencedisassembler --rom ROM > openmode_sequence_debug.txt
from randomizer.data.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data.eventtables import RadialDirections, AreaObjects, NPCPackets, Sounds, Coords, CoordUnits, Rooms
script = [
    {
        "identifier": 'ACTION_1007_jump_to_height_0',
        "command": 'jump_to_height',
        "args": [80]
    },
    {
        "identifier": 'ACTION_1007_pause_1',
        "command": 'pause',
        "args": [25]
    },
    {
        "identifier": 'ACTION_1007_jmp_2',
        "command": 'jmp',
        "args": ['ACTION_1007_jump_to_height_0']
    }
]
