# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectsequencedisassembler --rom ROM > openmode_sequence_debug.txt
from randomizer.helpers.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.helpers.eventtables import RadialDirections, AreaObjects, NPCPackets, Sounds, Coords, CoordUnits, Rooms
script = [
    {
        "identifier": 'ACTION_687_shadow_off_0',
        "command": 'shadow_off'
    },
    {
        "identifier": 'ACTION_687_floating_off_1',
        "command": 'floating_off'
    },
    {
        "identifier": 'ACTION_687_set_vram_priority_2',
        "command": 'set_vram_priority',
        "args": [VramPriority.PRIORITY_3]
    },
    {
        "identifier": 'ACTION_687_set_sprite_sequence_3',
        "command": 'set_sprite_sequence',
        "args": [7, 0, [_0x08Flags.READ_AS_SEQUENCE]]
    },
    {
        "identifier": 'ACTION_687_visibility_off_4',
        "command": 'visibility_off'
    },
    {
        "identifier": 'ACTION_687_sequence_looping_on_5',
        "command": 'sequence_looping_on'
    },
    {
        "identifier": 'ACTION_687_pause_6',
        "command": 'pause',
        "args": [6]
    },
    {
        "identifier": 'ACTION_687_visibility_on_7',
        "command": 'visibility_on'
    },
    {
        "identifier": 'ACTION_687_pause_8',
        "command": 'pause',
        "args": [26]
    },
    {
        "identifier": 'ACTION_687_set_sprite_sequence_9',
        "command": 'set_sprite_sequence',
        "args": [6, 0, [_0x08Flags.READ_AS_SEQUENCE]]
    },
    {
        "identifier": 'ACTION_687_pause_10',
        "command": 'pause',
        "args": [24]
    },
    {
        "identifier": 'ACTION_687_visibility_off_11',
        "command": 'visibility_off'
    },
    {
        "identifier": 'ACTION_687_ret_12',
        "command": 'ret'
    }
]
