# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.data.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.data.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": 'EVENT_3499_action_queue_async_0',
        "command": 'action_queue_async',
        "args": [AreaObjects.MARIO],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_0_SUBSCRIPT_object_memory_set_bit_0',
                "command": 'object_memory_set_bit',
                "args": [0x0b, [3]]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_set_short_1',
        "command": 'set_short',
        "args": [0x7024, 0x0000]
    },
    {
        "identifier": 'EVENT_3499_set_short_2',
        "command": 'set_short',
        "args": [0x7034, 0x0010]
    },
    {
        "identifier": 'EVENT_3499_set_short_3',
        "command": 'set_short',
        "args": [0x7026, 0x0001]
    },
    {
        "identifier": 'EVENT_3499_set_4',
        "command": 'set',
        "args": [0x70b1, 0]
    },
    {
        "identifier": 'EVENT_3499_freeze_camera_5',
        "command": 'freeze_camera'
    },
    {
        "identifier": 'EVENT_3499_action_queue_sync_6',
        "command": 'action_queue_sync',
        "args": [AreaObjects.MARIO],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_sync_6_SUBSCRIPT_transfer_to_xyzf_0',
                "command": 'transfer_to_xyzf',
                "args": [11, 67, 0, RadialDirections.EAST]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_action_queue_sync_7',
        "command": 'action_queue_sync',
        "args": [AreaObjects.LAYER_3],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_sync_7_SUBSCRIPT_set_animation_speed_0',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_7_SUBSCRIPT_shift_northwest_steps_1',
                "command": 'shift_northwest_steps',
                "args": [18]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_fade_in_from_black_async_8',
        "command": 'fade_in_from_black_async'
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_9',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_8],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_9_SUBSCRIPT_db_0',
                "command": 'db',
                "args": [0x20, 0x04]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_9_SUBSCRIPT_embedded_animation_routine_1',
                "command": 'embedded_animation_routine',
                "args": [0x28, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x20, 0x80]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_9_SUBSCRIPT_fixed_f_coord_on_2',
                "command": 'fixed_f_coord_on'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_9_SUBSCRIPT_sequence_looping_on_3',
                "command": 'sequence_looping_on'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_9_SUBSCRIPT_set_animation_speed_4',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_9_SUBSCRIPT_set_animation_speed_5',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_9_SUBSCRIPT_set_sprite_sequence_6',
                "command": 'set_sprite_sequence',
                "args": [3, 2, [_0x08Flags.READ_AS_SEQUENCE, _0x08Flags.MIRROR_SPRITE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_9_SUBSCRIPT_shift_z_up_pixels_7',
                "command": 'shift_z_up_pixels',
                "args": [9]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_9_SUBSCRIPT_shift_southeast_pixels_8',
                "command": 'shift_southeast_pixels',
                "args": [8]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_action_queue_sync_10',
        "command": 'action_queue_sync',
        "args": [AreaObjects.NPC_8],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_sync_10_SUBSCRIPT_shift_northwest_steps_0',
                "command": 'shift_northwest_steps',
                "args": [11]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_11',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_7],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_11_SUBSCRIPT_set_animation_speed_0',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.WALKING, _0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_11_SUBSCRIPT_shift_northwest_steps_1',
                "command": 'shift_northwest_steps',
                "args": [11]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_11_SUBSCRIPT_set_animation_speed_2',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.SEQUENCE]]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_set_action_script_sync_12',
        "command": 'set_action_script_sync',
        "args": [AreaObjects.NPC_8, 715]
    },
    {
        "identifier": 'EVENT_3499_run_dialog_13',
        "command": 'run_dialog',
        "args": [1178, AreaObjects.NPC_12, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE]]
    },
    {
        "identifier": 'EVENT_3499_jmp_to_subroutine_14',
        "command": 'jmp_to_subroutine',
        "args": ['EVENT_3499_action_queue_sync_96']
    },
    {
        "identifier": 'EVENT_3499_run_dialog_15',
        "command": 'run_dialog',
        "args": [1179, AreaObjects.NPC_14, [_0x60Flags.ASYNC, _0x60Flags.MULTILINE]]
    },
    {
        "identifier": 'EVENT_3499_jmp_to_subroutine_16',
        "command": 'jmp_to_subroutine',
        "args": ['EVENT_3499_action_queue_sync_99']
    },
    {
        "identifier": 'EVENT_3499_pause_17',
        "command": 'pause',
        "args": [20]
    },
    {
        "identifier": 'EVENT_3499_jmp_to_subroutine_18',
        "command": 'jmp_to_subroutine',
        "args": ['EVENT_3499_action_queue_sync_96']
    },
    {
        "identifier": 'EVENT_3499_run_dialog_duration_19',
        "command": 'run_dialog_duration',
        "args": [1180, DialogDurations.SHORT, []]
    },
    {
        "identifier": 'EVENT_3499_pause_script_resume_on_next_dialog_page_a_FD61_20',
        "command": 'pause_script_resume_on_next_dialog_page_a_FD61'
    },
    {
        "identifier": 'EVENT_3499_jmp_to_subroutine_21',
        "command": 'jmp_to_subroutine',
        "args": ['EVENT_3499_action_queue_sync_99']
    },
    {
        "identifier": 'EVENT_3499_pause_script_resume_on_next_dialog_page_a_FD61_22',
        "command": 'pause_script_resume_on_next_dialog_page_a_FD61'
    },
    {
        "identifier": 'EVENT_3499_jmp_to_subroutine_23',
        "command": 'jmp_to_subroutine',
        "args": ['EVENT_3499_action_queue_sync_96']
    },
    {
        "identifier": 'EVENT_3499_pause_script_resume_on_next_dialog_page_a_FD61_24',
        "command": 'pause_script_resume_on_next_dialog_page_a_FD61'
    },
    {
        "identifier": 'EVENT_3499_jmp_to_subroutine_25',
        "command": 'jmp_to_subroutine',
        "args": ['EVENT_3499_action_queue_sync_99']
    },
    {
        "identifier": 'EVENT_3499_unsync_dialog_26',
        "command": 'unsync_dialog'
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_27',
        "command": 'action_queue_async',
        "args": [AreaObjects.MARIO],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_27_SUBSCRIPT_set_animation_speed_0',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.WALKING, _0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_27_SUBSCRIPT_shift_northwest_steps_1',
                "command": 'shift_northwest_steps',
                "args": [8]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_27_SUBSCRIPT_fixed_f_coord_on_2',
                "command": 'fixed_f_coord_on'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_27_SUBSCRIPT_set_animation_speed_3',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.WALKING]]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_run_dialog_28',
        "command": 'run_dialog',
        "args": [1181, AreaObjects.NPC_12, [_0x60Flags.CLOSABLE, _0x60Flags.MULTILINE]]
    },
    {
        "identifier": 'EVENT_3499_pause_script_resume_on_next_dialog_page_a_FD61_29',
        "command": 'pause_script_resume_on_next_dialog_page_a_FD61'
    },
    {
        "identifier": 'EVENT_3499_jmp_to_subroutine_30',
        "command": 'jmp_to_subroutine',
        "args": ['EVENT_3499_action_queue_sync_96']
    },
    {
        "identifier": 'EVENT_3499_unsync_dialog_31',
        "command": 'unsync_dialog'
    },
    {
        "identifier": 'EVENT_3499_jmp_to_subroutine_32',
        "command": 'jmp_to_subroutine',
        "args": ['EVENT_3499_action_queue_sync_99']
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_33',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_7],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_33_SUBSCRIPT_set_animation_speed_0',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.VERY_FAST, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_33_SUBSCRIPT_sequence_looping_on_1',
                "command": 'sequence_looping_on'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_33_SUBSCRIPT_pause_2',
                "command": 'pause',
                "args": [40]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_33_SUBSCRIPT_set_animation_speed_3',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.SEQUENCE]]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_jmp_to_subroutine_34',
        "command": 'jmp_to_subroutine',
        "args": ['EVENT_3499_action_queue_sync_96']
    },
    {
        "identifier": 'EVENT_3499_run_dialog_35',
        "command": 'run_dialog',
        "args": [1182, AreaObjects.NPC_14, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE]]
    },
    {
        "identifier": 'EVENT_3499_action_queue_sync_36',
        "command": 'action_queue_sync',
        "args": [AreaObjects.NPC_7],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_sync_36_SUBSCRIPT_set_animation_speed_0',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_36_SUBSCRIPT_sequence_looping_on_1',
                "command": 'sequence_looping_on'
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_37',
        "command": 'action_queue_async',
        "args": [AreaObjects.MARIO],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_37_SUBSCRIPT_sequence_looping_on_0',
                "command": 'sequence_looping_on'
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_set_38',
        "command": 'set',
        "args": [0x70ae, 3]
    },
    {
        "identifier": 'EVENT_3499_jmp_to_subroutine_39',
        "command": 'jmp_to_subroutine',
        "args": ['EVENT_3499_action_queue_sync_99']
    },
    {
        "identifier": 'EVENT_3499_set_action_script_sync_40',
        "command": 'set_action_script_sync',
        "args": [AreaObjects.NPC_3, 707]
    },
    {
        "identifier": 'EVENT_3499_set_action_script_sync_41',
        "command": 'set_action_script_sync',
        "args": [AreaObjects.NPC_4, 707]
    },
    {
        "identifier": 'EVENT_3499_set_action_script_sync_42',
        "command": 'set_action_script_sync',
        "args": [AreaObjects.NPC_5, 707]
    },
    {
        "identifier": 'EVENT_3499_pause_43',
        "command": 'pause',
        "args": [60]
    },
    {
        "identifier": 'EVENT_3499_freeze_all_npcs_until_return_44',
        "command": 'freeze_all_npcs_until_return'
    },
    {
        "identifier": 'EVENT_3499_palette_set_morphs_45',
        "command": 'palette_set_morphs',
        "args": [PaletteSetTypes.FADE_TO, 10, 26, 1]
    },
    {
        "identifier": 'EVENT_3499_palette_set_morphs_46',
        "command": 'palette_set_morphs',
        "args": [PaletteSetTypes.FADE_TO, 10, 26, 2]
    },
    {
        "identifier": 'EVENT_3499_palette_set_morphs_47',
        "command": 'palette_set_morphs',
        "args": [PaletteSetTypes.FADE_TO, 10, 26, 3]
    },
    {
        "identifier": 'EVENT_3499_palette_set_morphs_48',
        "command": 'palette_set_morphs',
        "args": [PaletteSetTypes.FADE_TO, 10, 26, 4]
    },
    {
        "identifier": 'EVENT_3499_palette_set_morphs_49',
        "command": 'palette_set_morphs',
        "args": [PaletteSetTypes.FADE_TO, 10, 26, 5]
    },
    {
        "identifier": 'EVENT_3499_palette_set_morphs_50',
        "command": 'palette_set_morphs',
        "args": [PaletteSetTypes.FADE_TO, 10, 26, 6]
    },
    {
        "identifier": 'EVENT_3499_palette_set_morphs_51',
        "command": 'palette_set_morphs',
        "args": [PaletteSetTypes.FADE_TO, 10, 26, 7]
    },
    {
        "identifier": 'EVENT_3499_pause_52',
        "command": 'pause',
        "args": [16]
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_53',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_6],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_53_SUBSCRIPT_transfer_to_xyzf_0',
                "command": 'transfer_to_xyzf',
                "args": [11, 65, 0, RadialDirections.EAST]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_53_SUBSCRIPT_set_priority_1',
                "command": 'set_priority',
                "args": [3]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_53_SUBSCRIPT_visibility_on_2',
                "command": 'visibility_on'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_53_SUBSCRIPT_set_animation_speed_3',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.WALKING, _0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_53_SUBSCRIPT_shift_northwest_steps_4',
                "command": 'shift_northwest_steps',
                "args": [6]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_53_SUBSCRIPT_set_sprite_sequence_5',
                "command": 'set_sprite_sequence',
                "args": [10, 0, [_0x08Flags.READ_AS_SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_53_SUBSCRIPT_jump_to_height_6',
                "command": 'jump_to_height',
                "args": [64]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_play_sound_54',
        "command": 'play_sound',
        "args": [Sounds._087_CORRECT_SIGNAL, 6]
    },
    {
        "identifier": 'EVENT_3499_run_dialog_55',
        "command": 'run_dialog',
        "args": [1188, AreaObjects.NPC_12, [_0x60Flags.ASYNC, _0x60Flags.MULTILINE]]
    },
    {
        "identifier": 'EVENT_3499_jmp_if_dialog_option_b_56',
        "command": 'jmp_if_dialog_option_b',
        "args": ['EVENT_3499_run_dialog_duration_75']
    },
    {
        "identifier": 'EVENT_3499_run_dialog_57',
        "command": 'run_dialog',
        "args": [1183, AreaObjects.NPC_12, [_0x60Flags.ASYNC, _0x60Flags.MULTILINE]]
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_58',
        "command": 'action_queue_async',
        "args": [AreaObjects.MARIO],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_clear_solidity_bits_0',
                "command": 'clear_solidity_bits',
                "args": [[_0x0AFlags.BIT_4, _0x0AFlags.CANT_PASS_NPCS, _0x0AFlags.CANT_WALK_THROUGH, _0x0AFlags.BIT_7]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_set_animation_speed_1',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_set_animation_speed_2',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_start_loop_n_times_3',
                "command": 'start_loop_n_times',
                "args": [3]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_play_sound_4',
                "command": 'play_sound',
                "args": [Sounds._003_MENU_SCROLL, 6]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_shift_northeast_pixels_5',
                "command": 'shift_northeast_pixels',
                "args": [8]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_end_loop_6',
                "command": 'end_loop'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_jump_to_height_7',
                "command": 'jump_to_height',
                "args": [107]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_pause_8',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_start_loop_n_times_9',
                "command": 'start_loop_n_times',
                "args": [7]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_play_sound_10',
                "command": 'play_sound',
                "args": [Sounds._003_MENU_SCROLL, 6]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_shift_southwest_pixels_11',
                "command": 'shift_southwest_pixels',
                "args": [8]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_end_loop_12',
                "command": 'end_loop'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_start_loop_n_times_13',
                "command": 'start_loop_n_times',
                "args": [1]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_jump_to_height_14',
                "command": 'jump_to_height',
                "args": [107]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_pause_15',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_58_SUBSCRIPT_end_loop_16',
                "command": 'end_loop'
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_run_dialog_duration_59',
        "command": 'run_dialog_duration',
        "args": [1184, DialogDurations.FOREVER, [_0x60Flags.ASYNC]]
    },
    {
        "identifier": 'EVENT_3499_jmp_to_subroutine_60',
        "command": 'jmp_to_subroutine',
        "args": ['EVENT_3499_action_queue_sync_102']
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_61',
        "command": 'action_queue_async',
        "args": [AreaObjects.MARIO],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_pause_0',
                "command": 'pause',
                "args": [36]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_play_sound_1',
                "command": 'play_sound',
                "args": [Sounds._049_BIG_SHELL_HIT, 4]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_set_animation_speed_2',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_set_animation_speed_3',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_jump_to_height_silent_4',
                "command": 'jump_to_height_silent',
                "args": [112]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_set_sprite_sequence_5',
                "command": 'set_sprite_sequence',
                "args": [7, 3, [_0x08Flags.READ_AS_SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_start_loop_n_times_6',
                "command": 'start_loop_n_times',
                "args": [15]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_visibility_off_7',
                "command": 'visibility_off'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_pause_8',
                "command": 'pause',
                "args": [1]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_visibility_on_9',
                "command": 'visibility_on'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_shift_southeast_pixels_10',
                "command": 'shift_southeast_pixels',
                "args": [1]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_end_loop_11',
                "command": 'end_loop'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_reset_properties_12',
                "command": 'reset_properties'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_pause_13',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_set_animation_speed_14',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.SLOW, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_61_SUBSCRIPT_shift_northwest_pixels_15',
                "command": 'shift_northwest_pixels',
                "args": [16]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_action_queue_sync_62',
        "command": 'action_queue_sync',
        "args": [AreaObjects.NPC_3],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_sync_62_SUBSCRIPT_set_animation_speed_0',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.WALKING, _0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_62_SUBSCRIPT_play_sound_1',
                "command": 'play_sound',
                "args": [Sounds._050_WATER_DROPLET, 4]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_62_SUBSCRIPT_jump_to_height_2',
                "command": 'jump_to_height',
                "args": [56]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_62_SUBSCRIPT_set_sprite_sequence_3',
                "command": 'set_sprite_sequence',
                "args": [2, 0, [_0x08Flags.LOOPING_OFF, _0x08Flags.READ_AS_SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_62_SUBSCRIPT_pause_4',
                "command": 'pause',
                "args": [32]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_62_SUBSCRIPT_reset_properties_5',
                "command": 'reset_properties'
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_62_SUBSCRIPT_set_animation_speed_6',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_62_SUBSCRIPT_shift_northwest_steps_7',
                "command": 'shift_northwest_steps',
                "args": [6]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_63',
        "command": 'action_queue_async',
        "args": [AreaObjects.MARIO],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_63_SUBSCRIPT_pause_0',
                "command": 'pause',
                "args": [84]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_63_SUBSCRIPT_play_sound_1',
                "command": 'play_sound',
                "args": [Sounds._049_BIG_SHELL_HIT, 4]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_63_SUBSCRIPT_jump_to_height_silent_2',
                "command": 'jump_to_height_silent',
                "args": [112]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_63_SUBSCRIPT_set_sprite_sequence_3',
                "command": 'set_sprite_sequence',
                "args": [7, 3, [_0x08Flags.READ_AS_SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_63_SUBSCRIPT_set_animation_speed_4',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_63_SUBSCRIPT_start_loop_n_times_5',
                "command": 'start_loop_n_times',
                "args": [23]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_63_SUBSCRIPT_visibility_off_6',
                "command": 'visibility_off'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_63_SUBSCRIPT_shift_southeast_pixels_7',
                "command": 'shift_southeast_pixels',
                "args": [2]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_63_SUBSCRIPT_visibility_on_8',
                "command": 'visibility_on'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_63_SUBSCRIPT_shift_southeast_pixels_9',
                "command": 'shift_southeast_pixels',
                "args": [2]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_63_SUBSCRIPT_end_loop_10',
                "command": 'end_loop'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_63_SUBSCRIPT_reset_properties_11',
                "command": 'reset_properties'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_63_SUBSCRIPT_pause_12',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_63_SUBSCRIPT_transfer_to_xyzf_13',
                "command": 'transfer_to_xyzf',
                "args": [7, 59, 0, RadialDirections.EAST]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_64',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_3],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_64_SUBSCRIPT_set_sprite_sequence_0',
                "command": 'set_sprite_sequence',
                "args": [0, 0, [_0x08Flags.READ_AS_SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_64_SUBSCRIPT_shift_xy_steps_1',
                "command": 'shift_xy_steps',
                "args": [3, 6]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_run_dialog_duration_65',
        "command": 'run_dialog_duration',
        "args": [1185, DialogDurations.FOREVER, [_0x60Flags.ASYNC]]
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_66',
        "command": 'action_queue_async',
        "args": [AreaObjects.MARIO],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_66_SUBSCRIPT_set_animation_speed_0',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_66_SUBSCRIPT_set_animation_speed_1',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_66_SUBSCRIPT_shift_southwest_steps_2',
                "command": 'shift_southwest_steps',
                "args": [2]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_jmp_to_subroutine_67',
        "command": 'jmp_to_subroutine',
        "args": ['EVENT_3499_action_queue_sync_102']
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_68',
        "command": 'action_queue_async',
        "args": [AreaObjects.MARIO],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_68_SUBSCRIPT_pause_0',
                "command": 'pause',
                "args": [17]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_68_SUBSCRIPT_jump_to_height_1',
                "command": 'jump_to_height',
                "args": [108]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_68_SUBSCRIPT_pause_2',
                "command": 'pause',
                "args": [23]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_68_SUBSCRIPT_set_animation_speed_3',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_68_SUBSCRIPT_play_sound_4',
                "command": 'play_sound',
                "args": [Sounds._010_TRAMPOLINE, 4]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_68_SUBSCRIPT_floating_off_5',
                "command": 'floating_off'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_68_SUBSCRIPT_jump_to_height_silent_6',
                "command": 'jump_to_height_silent',
                "args": [108]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_68_SUBSCRIPT_shift_northwest_pixels_7',
                "command": 'shift_northwest_pixels',
                "args": [32]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_68_SUBSCRIPT_pause_8',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_68_SUBSCRIPT_transfer_to_xyzf_9',
                "command": 'transfer_to_xyzf',
                "args": [7, 59, 0, RadialDirections.EAST]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_run_dialog_duration_69',
        "command": 'run_dialog_duration',
        "args": [1186, DialogDurations.FOREVER, [_0x60Flags.ASYNC]]
    },
    {
        "identifier": 'EVENT_3499_action_queue_sync_70',
        "command": 'action_queue_sync',
        "args": [AreaObjects.NPC_4],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_sync_70_SUBSCRIPT_set_animation_speed_0',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.WALKING, _0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_70_SUBSCRIPT_play_sound_1',
                "command": 'play_sound',
                "args": [Sounds._050_WATER_DROPLET, 4]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_70_SUBSCRIPT_jump_to_height_2',
                "command": 'jump_to_height',
                "args": [56]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_70_SUBSCRIPT_set_sprite_sequence_3',
                "command": 'set_sprite_sequence',
                "args": [2, 0, [_0x08Flags.LOOPING_OFF, _0x08Flags.READ_AS_SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_70_SUBSCRIPT_pause_4',
                "command": 'pause',
                "args": [32]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_70_SUBSCRIPT_reset_properties_5',
                "command": 'reset_properties'
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_70_SUBSCRIPT_set_animation_speed_6',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_70_SUBSCRIPT_shift_northwest_steps_7',
                "command": 'shift_northwest_steps',
                "args": [4]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_70_SUBSCRIPT_set_animation_speed_8',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.VERY_FAST, [_0x10Flags.WALKING, _0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_70_SUBSCRIPT_set_sprite_sequence_9',
                "command": 'set_sprite_sequence',
                "args": [0, 0, [_0x08Flags.READ_AS_SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_70_SUBSCRIPT_shift_southeast_steps_10',
                "command": 'shift_southeast_steps',
                "args": [8]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_71',
        "command": 'action_queue_async',
        "args": [AreaObjects.MARIO],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_71_SUBSCRIPT_pause_0',
                "command": 'pause',
                "args": [72]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_71_SUBSCRIPT_jump_to_height_1',
                "command": 'jump_to_height',
                "args": [108]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_71_SUBSCRIPT_pause_2',
                "command": 'pause',
                "args": [23]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_71_SUBSCRIPT_set_animation_speed_3',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_71_SUBSCRIPT_play_sound_4',
                "command": 'play_sound',
                "args": [Sounds._010_TRAMPOLINE, 4]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_71_SUBSCRIPT_floating_off_5',
                "command": 'floating_off'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_71_SUBSCRIPT_jump_to_height_silent_6',
                "command": 'jump_to_height_silent',
                "args": [108]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_71_SUBSCRIPT_shift_northwest_pixels_7',
                "command": 'shift_northwest_pixels',
                "args": [32]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_set_action_script_async_72',
        "command": 'set_action_script_async',
        "args": [AreaObjects.NPC_9, 716]
    },
    {
        "identifier": 'EVENT_3499_action_queue_sync_73',
        "command": 'action_queue_sync',
        "args": [AreaObjects.NPC_4],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_sync_73_SUBSCRIPT_pause_0',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_73_SUBSCRIPT_shift_xy_steps_1',
                "command": 'shift_xy_steps',
                "args": [254, 252]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_74',
        "command": 'action_queue_async',
        "args": [AreaObjects.MARIO],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_74_SUBSCRIPT_pause_0',
                "command": 'pause',
                "args": [30]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_74_SUBSCRIPT_transfer_to_xyzf_1',
                "command": 'transfer_to_xyzf',
                "args": [7, 59, 0, RadialDirections.EAST]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_74_SUBSCRIPT_set_solidity_bits_2',
                "command": 'set_solidity_bits',
                "args": [[_0x0AFlags.BIT_4, _0x0AFlags.CANT_PASS_NPCS, _0x0AFlags.CANT_WALK_THROUGH, _0x0AFlags.BIT_7]]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_run_dialog_duration_75',
        "command": 'run_dialog_duration',
        "args": [1187, DialogDurations.SHORT, [_0x60Flags.ASYNC]]
    },
    {
        "identifier": 'EVENT_3499_play_sound_76',
        "command": 'play_sound',
        "args": [Sounds._087_CORRECT_SIGNAL, 6]
    },
    {
        "identifier": 'EVENT_3499_fade_out_music_to_volume_77',
        "command": 'fade_out_music_to_volume',
        "args": [2, 0]
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_78',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_6],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_78_SUBSCRIPT_reset_properties_0',
                "command": 'reset_properties'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_78_SUBSCRIPT_shift_southeast_steps_1',
                "command": 'shift_southeast_steps',
                "args": [6]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_78_SUBSCRIPT_visibility_off_2',
                "command": 'visibility_off'
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_palette_set_morphs_79',
        "command": 'palette_set_morphs',
        "args": [PaletteSetTypes.FADE_TO, 10, 97, 1]
    },
    {
        "identifier": 'EVENT_3499_palette_set_morphs_80',
        "command": 'palette_set_morphs',
        "args": [PaletteSetTypes.FADE_TO, 10, 98, 2]
    },
    {
        "identifier": 'EVENT_3499_palette_set_morphs_81',
        "command": 'palette_set_morphs',
        "args": [PaletteSetTypes.FADE_TO, 10, 99, 3]
    },
    {
        "identifier": 'EVENT_3499_palette_set_morphs_82',
        "command": 'palette_set_morphs',
        "args": [PaletteSetTypes.FADE_TO, 10, 100, 4]
    },
    {
        "identifier": 'EVENT_3499_palette_set_morphs_83',
        "command": 'palette_set_morphs',
        "args": [PaletteSetTypes.FADE_TO, 10, 101, 5]
    },
    {
        "identifier": 'EVENT_3499_palette_set_morphs_84',
        "command": 'palette_set_morphs',
        "args": [PaletteSetTypes.FADE_TO, 10, 102, 6]
    },
    {
        "identifier": 'EVENT_3499_palette_set_morphs_85',
        "command": 'palette_set_morphs',
        "args": [PaletteSetTypes.FADE_TO, 10, 103, 7]
    },
    {
        "identifier": 'EVENT_3499_pause_86',
        "command": 'pause',
        "args": [32]
    },
    {
        "identifier": 'EVENT_3499_unfreeze_all_npcs_87',
        "command": 'unfreeze_all_npcs'
    },
    {
        "identifier": 'EVENT_3499_run_background_event_88',
        "command": 'run_background_event',
        "args": [3500, [_0x40Flags.RETURN_ON_LEVEL_EXIT]]
    },
    {
        "identifier": 'EVENT_3499_run_background_event_89',
        "command": 'run_background_event',
        "args": [3503, [_0x40Flags.RETURN_ON_LEVEL_EXIT, _0x40Flags.BIT_6]]
    },
    {
        "identifier": 'EVENT_3499_set_action_script_sync_90',
        "command": 'set_action_script_sync',
        "args": [AreaObjects.LAYER_1, 704]
    },
    {
        "identifier": 'EVENT_3499_set_action_script_sync_91',
        "command": 'set_action_script_sync',
        "args": [AreaObjects.LAYER_2, 655]
    },
    {
        "identifier": 'EVENT_3499_set_action_script_sync_92',
        "command": 'set_action_script_sync',
        "args": [AreaObjects.LAYER_3, 705]
    },
    {
        "identifier": 'EVENT_3499_play_music_default_volume_93',
        "command": 'play_music_default_volume',
        "args": [Music._38_BOOSTER_HILL]
    },
    {
        "identifier": 'EVENT_3499_run_event_at_return_94',
        "command": 'run_event_at_return',
        "args": [3502]
    },
    {
        "identifier": 'EVENT_3499_ret_95',
        "command": 'ret'
    },
    {
        "identifier": 'EVENT_3499_action_queue_sync_96',
        "command": 'action_queue_sync',
        "args": [AreaObjects.NPC_8],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_sync_96_SUBSCRIPT_shift_north_pixels_0',
                "command": 'shift_north_pixels',
                "args": [4]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_96_SUBSCRIPT_set_sprite_sequence_1',
                "command": 'set_sprite_sequence',
                "args": [4, 2, [_0x08Flags.READ_AS_SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_96_SUBSCRIPT_shift_north_pixels_2',
                "command": 'shift_north_pixels',
                "args": [4]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_96_SUBSCRIPT_shift_west_pixels_3',
                "command": 'shift_west_pixels',
                "args": [8]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_96_SUBSCRIPT_set_sprite_sequence_4',
                "command": 'set_sprite_sequence',
                "args": [4, 2, [_0x08Flags.READ_AS_SEQUENCE, _0x08Flags.MIRROR_SPRITE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_96_SUBSCRIPT_shift_west_pixels_5',
                "command": 'shift_west_pixels',
                "args": [8]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_96_SUBSCRIPT_set_object_memory_bits_6',
                "command": 'set_object_memory_bits',
                "args": [0x0e, [0]]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_97',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_7],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_97_SUBSCRIPT_pause_0',
                "command": 'pause',
                "args": [4]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_97_SUBSCRIPT_face_southwest_1',
                "command": 'face_southwest'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_97_SUBSCRIPT_pause_2',
                "command": 'pause',
                "args": [4]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_97_SUBSCRIPT_face_southeast_3',
                "command": 'face_southeast'
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_ret_98',
        "command": 'ret'
    },
    {
        "identifier": 'EVENT_3499_action_queue_sync_99',
        "command": 'action_queue_sync',
        "args": [AreaObjects.NPC_8],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_sync_99_SUBSCRIPT_shift_east_pixels_0',
                "command": 'shift_east_pixels',
                "args": [8]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_99_SUBSCRIPT_set_sprite_sequence_1',
                "command": 'set_sprite_sequence',
                "args": [4, 2, [_0x08Flags.READ_AS_SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_99_SUBSCRIPT_shift_east_pixels_2',
                "command": 'shift_east_pixels',
                "args": [8]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_99_SUBSCRIPT_set_sprite_sequence_3',
                "command": 'set_sprite_sequence',
                "args": [3, 2, [_0x08Flags.READ_AS_SEQUENCE, _0x08Flags.MIRROR_SPRITE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_99_SUBSCRIPT_shift_south_pixels_4',
                "command": 'shift_south_pixels',
                "args": [8]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_99_SUBSCRIPT_set_object_memory_bits_5',
                "command": 'set_object_memory_bits',
                "args": [0x0e, [0]]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_action_queue_async_100',
        "command": 'action_queue_async',
        "args": [AreaObjects.NPC_7],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_async_100_SUBSCRIPT_pause_0',
                "command": 'pause',
                "args": [4]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_100_SUBSCRIPT_face_southwest_1',
                "command": 'face_southwest'
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_100_SUBSCRIPT_pause_2',
                "command": 'pause',
                "args": [4]
            },
            {
                "identifier": 'EVENT_3499_action_queue_async_100_SUBSCRIPT_face_northwest_3',
                "command": 'face_northwest'
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_ret_101',
        "command": 'ret'
    },
    {
        "identifier": 'EVENT_3499_action_queue_sync_102',
        "command": 'action_queue_sync',
        "args": [AreaObjects.NPC_0],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_sync_102_SUBSCRIPT_visibility_off_0',
                "command": 'visibility_off'
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_102_SUBSCRIPT_transfer_to_xyzf_1',
                "command": 'transfer_to_xyzf',
                "args": [5, 54, 0, RadialDirections.EAST]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_102_SUBSCRIPT_set_priority_2',
                "command": 'set_priority',
                "args": [2]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_102_SUBSCRIPT_face_southwest_3',
                "command": 'face_southwest'
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_102_SUBSCRIPT_fixed_f_coord_on_4',
                "command": 'fixed_f_coord_on'
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_102_SUBSCRIPT_set_animation_speed_5',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FASTER, [_0x10Flags.WALKING, _0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_102_SUBSCRIPT_shift_southwest_pixels_6',
                "command": 'shift_southwest_pixels',
                "args": [36]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_102_SUBSCRIPT_play_sound_7',
                "command": 'play_sound',
                "args": [Sounds._049_BIG_SHELL_HIT, 4]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_102_SUBSCRIPT_visibility_on_8',
                "command": 'visibility_on'
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_102_SUBSCRIPT_jump_to_height_9',
                "command": 'jump_to_height',
                "args": [24]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_102_SUBSCRIPT_walk_1_step_southeast_10',
                "command": 'walk_1_step_southeast'
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_102_SUBSCRIPT_set_700C_to_object_coord_11',
                "command": 'set_700C_to_object_coord',
                "args": [AreaObjects.DUMMY_0X07, Coords.X, [], CoordUnits.PIXEL]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_102_SUBSCRIPT_mem_compare_val_12',
                "command": 'mem_compare_val',
                "args": [5888]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_102_SUBSCRIPT_jmp_if_comparison_result_is_lesser_13',
                "command": 'jmp_if_comparison_result_is_lesser',
                "args": ['EVENT_3499_action_queue_sync_102_SUBSCRIPT_jump_to_height_9']
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_action_queue_sync_103',
        "command": 'action_queue_sync',
        "args": [AreaObjects.NPC_3],
        "subscript": [
            {
                "identifier": 'EVENT_3499_action_queue_sync_103_SUBSCRIPT_pause_0',
                "command": 'pause',
                "args": [50]
            },
            {
                "identifier": 'EVENT_3499_action_queue_sync_103_SUBSCRIPT_jump_to_height_1',
                "command": 'jump_to_height',
                "args": [112]
            }
        ]
    },
    {
        "identifier": 'EVENT_3499_ret_104',
        "command": 'ret'
    }
]
