from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=9,
        y=79,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R415_NIMBUS_LAND_SMALL_PLATFORM_AFTER_NIMBUS_CASTLE_THRONE_PATHS,
        show_message = False,
        dst_x = 28,
        dst_y = 121,
        dst_z = 4,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=1,
        y=96,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R121_NIMBUS_CASTLE_PATH_AFTER_THRONE_ROOM_2ND,
        show_message = False,
        dst_x = 8,
        dst_y = 81,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
]
