"""NPC list import"""

from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    ChestNPC(
        occupant=TreasureChest,
        initiator=EventInitiator.HIT_FROM_BELOW,
        event_script=E3517_CHEST_DIFFERENTIATOR_NPC_1_2_3_OR_OTHER,
        action_script=A0014_FLOATING_CHEST,
        lower_70a7=0,
        upper_70a7=0,
        speed=0,
        visible=True,
        x=23,
        y=14,
        z=3,
        z_half=True,
        direction=SOUTHWEST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=False,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=False,
        cant_move_if_in_air=True,
        byte7_upper2=True,
        priority_0=True,
        priority_1=True,
        priority_2=False,
        cannot_clone=False,
    ),
    # NPC_1
    ChestClone(
        occupant=TreasureChest,
        lower_70a7=0,
        upper_70a7=0,
        visible=True,
        x=23,
        y=19,
        z=3,
        z_half=True,
        direction=SOUTHWEST,
        priority_0=True,
        priority_1=True,
        priority_2=False,
        cannot_clone=False,
    ),
    # NPC_2
    ChestClone(
        occupant=TreasureChest,
        lower_70a7=2,
        upper_70a7=0,
        visible=True,
        x=21,
        y=18,
        z=3,
        z_half=True,
        direction=SOUTHWEST,
        priority_0=True,
        priority_1=True,
        priority_2=False,
        cannot_clone=False,
    ),
    # NPC_3
    ChestClone(
        occupant=TreasureChest,
        lower_70a7=2,
        upper_70a7=0,
        visible=True,
        x=21,
        y=15,
        z=3,
        z_half=True,
        direction=SOUTHWEST,
        priority_0=True,
        priority_1=True,
        priority_2=False,
        cannot_clone=False,
    ),
]
