from .coins_100_prize import *
from .coins_10_prize import *
from .coins_150_prize import *
from .coins_1_prize import *
from .coins_20_prize import *
from .coins_50_prize import *
from .coins_5_prize import *
from .coins_8_prize import *
from .frog_coin_10_prize import *
from .frog_coin_1_prize import *
from .frog_coin_20_prize import *
from .frog_coin_2_prize import *
from .frog_coin_3_prize import *
