"""NPC list import"""

from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    RegularNPC(
        occupant=BlueToad,
        initiator=EventInitiator.PRESS_A_FROM_ANY_SIDE,
        event_script=E0745_MUSHROOM_KINGDOM_INN_SLEEPING_GUY,
        action_script=A0223_BIG_TOAD_SLEEPING,
        speed=0,
        visible=True,
        x=8,
        y=122,
        z=3,
        z_half=False,
        direction=NORTHWEST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=False,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=True,
        byte3_bit7=True,
        slidable_along_walls=True,
        cant_move_if_in_air=False,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        show_shadow=False,
        acute_axis=5,
        obtuse_axis=5,
        height=2,
        cannot_clone=True,
        byte5_bit7=False,
    ),
]
