"""NPC list import"""

from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    BattlePackNPC(
        occupant=AlleyRat,
        initiator=EventInitiator.ANYTHING_EXCEPT_PRESS_A,
        after_battle=PostBattleBehaviour.REMOVE_PERMANENTLY,
        battle_pack=PACK0074_ALLEYRAT_PACK_1,
        action_script=A0342_SHIP_2ND_STAIRWAY_RATS,
        speed=0,
        visible=True,
        x=15,
        y=86,
        z=6,
        z_half=False,
        direction=SOUTHWEST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=True,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=True,
        cant_jump_through=False,
        cant_pass_npcs=True,
        byte3_bit5=False,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=True,
        cant_move_if_in_air=True,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False,
    ),
    # NPC_1
    BattlePackClone(
        occupant=AlleyRat,
        battle_pack=PACK0074_ALLEYRAT_PACK_1,
        action_script=A0342_SHIP_2ND_STAIRWAY_RATS,
        visible=True,
        x=11,
        y=93,
        z=0,
        z_half=False,
        direction=SOUTHWEST,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False,
    ),
    # NPC_2
    BattlePackClone(
        occupant=AlleyRat,
        battle_pack=PACK0074_ALLEYRAT_PACK_1,
        action_script=A0342_SHIP_2ND_STAIRWAY_RATS,
        visible=True,
        x=12,
        y=94,
        z=0,
        z_half=False,
        direction=NORTHEAST,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False,
    ),
    # NPC_3
    BattlePackClone(
        occupant=AlleyRat,
        battle_pack=PACK0074_ALLEYRAT_PACK_1,
        action_script=A0342_SHIP_2ND_STAIRWAY_RATS,
        visible=True,
        x=15,
        y=87,
        z=6,
        z_half=False,
        direction=NORTHEAST,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False,
    ),
]
