# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.helpers.eventtables import (
    ControllerDirections,
    RadialDirections,
    Rooms,
    Sounds,
    AreaObjects,
    NPCPackets,
    Locations,
    Shops,
    EventSequences,
    MenuTutorials,
    OverworldSequences,
    PlayableCharacters,
    EquipSlots,
    DialogDurations,
    IntroTitles,
    Colours,
    PaletteSetTypes,
    Music,
    MusicDirections,
    MusicPitch,
    Coords,
    CoordUnits,
    Tutorials,
    _0x40Flags,
    _0x60Flags,
    _0x62Flags,
    _0x63Flags,
    _0x68Flags,
    _0x6AFlags,
    _0x6BFlags,
    _0x81Flags,
    _0x84Flags)
from randomizer.helpers.objectsequencetables import (
    SequenceSpeeds,
    VramPriority,
    _0x08Flags,
    _0x0AFlags,
    _0x10Flags)
from randomizer.data import items

script = [
    {
        "identifier": "EVENT_3946_run_event_as_subroutine_23",
        "command": "run_event_as_subroutine",
        "args": [33],
    },
    {
        "identifier": "EVENT_3946_",
        "command": "create_packet_at_7010",
        "args": [103, "EVENT_3946_ret_259"],
    },
    {
        "identifier": "EVENT_3946_play_sound_24",
        "command": "play_sound",
        "args": [Sounds._014_FLOWER, 6],
    },
    {
        "identifier": "EVENT_3946_run_dialog_25",
        "command": "run_dialog",
        "args": [2098, AreaObjects.MARIO, [_0x60Flags.BIT_6]],
    },
    {"identifier": "EVENT_3946_inc_7", "command": "inc", "args": [0x70B2]},
    {
        "identifier": "EVENT_3946_put_inventory_22",
        "command": "put_inventory",
        "args": [233],
    },
    {"identifier": "EVENT_3946_ret_259", "command": "ret"},
]
