
from randomizer.helpers.eventtables import (
    ControllerDirections,
    RadialDirections,
    Rooms,
    Sounds,
    AreaObjects,
    NPCPackets,
    Locations,
    Shops,
    EventSequences,
    MenuTutorials,
    OverworldSequences,
    PlayableCharacters,
    EquipSlots,
    DialogDurations,
    IntroTitles,
    Colours,
    PaletteSetTypes,
    Music,
    MusicDirections,
    MusicPitch,
    Coords,
    CoordUnits,
    Tutorials,
    _0x40Flags,
    _0x60Flags,
    _0x62Flags,
    _0x63Flags,
    _0x68Flags,
    _0x6AFlags,
    _0x6BFlags,
    _0x81Flags,
    _0x84Flags)
from randomizer.helpers.objectsequencetables import (
    SequenceSpeeds,
    VramPriority,
    _0x08Flags,
    _0x0AFlags,
    _0x10Flags)
from randomizer.data import items

script = [
    {"identifier": "EVENT_2226_pause_5_", "command": "pause", "args": [10]},
    {
        "identifier": "EVENT_2226_start_battle_19",
        "command": "set_var_to_const",
        "args": [0x7000, 522],
    },
    {
        "identifier": "EVENT_2226_fight_",
        "command": "run_event_as_subroutine",
        "args": [353],
    },
    {
        "identifier": "EVENT_2226_jmp_if_bit_clear_20",
        "command": "jmp_if_bit_clear",
        "args": [0x7040, 0, "EVENT_2226_restore_all_hp_22"],
    },
    {"identifier": "EVENT_2226___jmp_to_event_9", "command": "reset_and_choose_game"},
    {"identifier": "EVENT_2226_restore_all_hp_22", "command": "restore_all_hp"},
    {"identifier": "EVENT_2226_restore_all_fp_14_", "command": "restore_all_fp"},
    {"identifier": "EVENT_2226_set_bit_23", "command": "set_bit", "args": [0x7093, 7]},
    {"identifier": "EVENT_2226_set_bit_23_", "command": "set_bit", "args": [0x7092, 4]},
    {"identifier": "EVENT_2226_set_short_28", "command": "set_var_to_const", "args": [0x7000, 522]},
    {
        "identifier": "EVENT_2226_jmp_to_event_29",
        "command": "jmp_to_event",
        "args": [167],
    },
    {"identifier": "EVENT_2226_stop_sound_30", "command": "stop_sound"},
    {"identifier": "EVENT_2226_j", "command": "jmp_to_event", "args": [2149]},
    {"identifier": "EVENT_2226_ret_31", "command": "ret"},
]
