# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.helpers.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.helpers.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": 'EVENT_44_set_var_to_random_1',
        "command": 'set_var_to_random',
        "args": [0x7000, 2]
    },
    {
        "identifier": "EVENT_44_jmp_if_7000_equals_short_0",
        "command": "jmp_if_var_equals_const",
        "args": [0x7000, 0, "EVENT_44__2"]
    },
    {
        "identifier": "EVENT_44_2",
        "command": 'jmp_to_event',
        "args": [26]
    },
    {
        "identifier": "EVENT_44__2",
        "command": 'jmp_to_event',
        "args": [27]
    }
]
