from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E1857_MOLEVILLE_SHOP_EXIT_TO_EXTERIOR,
        x=11,
        y=18,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0263_BOUNCE_ON_BED,
        x=16,
        y=14,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0263_BOUNCE_ON_BED,
        x=16,
        y=15,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
]
