from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E0418_PIPE_VAULT_PIPES_ROOM_ENTRANCE_PIPE,
        x=5,
        y=54,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E3605_PIPE_VAULT_PIPE_TO_TRIPLE_CHEST_ROOM,
        x=7,
        y=50,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0421_PIPE_VAULT_PIPES_ROOM_EXIT_PIPE,
        x=15,
        y=34,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0431_PIPE_VAULT_GOOMBA_THUMPIN_ENTRANCE_PIPE,
        x=13,
        y=38,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0492_PIPE_VAULT_PIRANHA_TIMER_1,
        x=6,
        y=51,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0494_PIPE_VAULT_PIRANHA_TIMER_2,
        x=8,
        y=47,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0495_PIPE_VAULT_PIRANHA_TIMER_3,
        x=10,
        y=43,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0496_PIPE_VAULT_PIRANHA_TIMER_4,
        x=12,
        y=39,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0497_PIPE_VAULT_PIRANHA_TIMER_5,
        x=14,
        y=35,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
]
