from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=10,
        y=30,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R273_MOLEVILLE_MINES_AREA_04_WTRAMPOLINE,
        show_message = False,
        dst_x = 10,
        dst_y = 49,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=2,
        y=17,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R279_MOLEVILLE_MINES_AREA_08_CROCOS_BOMBED_ROOM,
        show_message = False,
        dst_x = 18,
        dst_y = 121,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
]
