name: Star Hill wish submission
description: The dialogs that display if you talk to the smiley stars on Star Hill
title: "[Submission - Star Hill Wish]: "
labels: [submission]

body:
  - type: markdown
    attributes:
      value: |
        Submit a wish to be added to the Star Hill wish star pool.  

        Supported characters:  
        `A-Z`, `a-z`, `0-9`, and any of `♥♪•~©:;#×+%↑→←*&()-/?!.,`

        (Note: unlike ship passwords and Melody Bay tunes, Star Hill wishes are not credited.)

  - type: textarea
    id: wish
    attributes:
      label: Wish text
      description: | 
        These are generally very short, brief statements and not extended dialogs.  
        It is recommended to use the [Lazy Shell editor](https://github.com/Yakibomb/LAZYSHELL-UPDATED/releases) to preview your text for run-on sentences. There should be a good spot to await the user to press A within every 3 lines or less to prevent forced scrolling. 
    validations:
      required: true
