name: Sunken Ship password submission
description: The "Randomize Sunken Ship password" flag will pull one password at random from a pool of user-submitted options.
title: "[Submission - Sunken Ship]: "
labels: [submission]

body:
  - type: markdown
    attributes:
      value: |
        Submit a password to be added to the Sunken Ship password pool.

        Supported characters for all password letters and hint text:  
        `A-Z`, `a-z`, `0-9`, and any of `♥♪•~©:;#×+%↑→←*&()-/?!.,`

  - type: input
    id: submission
    attributes:
      label: Your word
      description: |
        Must be exactly six characters.  
        The five choices per letter box will be randomized to suit your submission.  
        References do not necessarily have to be related to the Mario series. Other games and franchises are welcome.
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Your name or handle
      description: |
        If your password is randomly selected for the seed, this is the name that will appear in the game's ending sequence.  
        Only capital letters A-Z, periods, spaces, and underscores are supported (no numbers or other characters).  
        Leave this blank if you prefer to be anonymous.

  - type: markdown
    attributes:
      value: |
        Contributors must write their own hint text for each of the 6 sunken ship puzzle rooms. Players must have something to go off of so that they are not hard required to bruteforce it.
        
        This is required, developers will not come up with hint text for you.

        You can write these however you like, whether hinting at certain letters or the subject matter. Keep them brief and direct.  
        The first line of each hint will be "Memo left by ___" with a random person's name from the randomizer's credits.  
        It is recommended to use the [Lazy Shell editor](https://github.com/Yakibomb/LAZYSHELL-UPDATED/releases) to preview your text for run-on sentences. Your hint should ideally fit in two lines or less, but if you want to extend it, make sure there is a good place to await the user to press A (i.e. usually the end of a sentence) within the first two lines.  
        You don't *have* to do this, but if you don't, your submission might sit in the queue indefinitely since it would require someone else to take the time to format it for you. It's best to just do it yourself.

  - type: textarea
    id: hint1
    attributes:
      label: Trampoline Room Hint
      description: |
        Original text: " It is found on the bed of the ocean."
    validations:
      required: true

  - type: textarea
    id: hint2
    attributes:
      label: Paratroopa Room Hint
      description: |
        Original text: " There is an 's' in the word."
    validations:
      required: true

  - type: textarea
    id: hint3
    attributes:
      label: 3D Maze Room Hint
      description: |
        Original text: " It has two vowels."
    validations:
      required: true

  - type: textarea
    id: hint4
    attributes:
      label: Coin Snake Room Hint
      description: |
        Original text: " It has four consonants."
    validations:
      required: true

  - type: textarea
    id: hint5
    attributes:
      label: Cannonball Room Hint
      description: |
        Original text: " At least... two consonants are side by side."
    validations:
      required: true

  - type: textarea
    id: hint6
    attributes:
      label: Rolling Barrel Room Hint
      description: |
        Original text: " The 'r' comes before the 'l'."
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: |
        There are 5 extra dialogs we can use for hint text. They are the notes placed around the areas of the ship before the puzzle rooms and the dialog said by the sleeping Dry Bones.  
        These are not required for your submission but you can include them if you're feeling creative.

  - type: textarea
    id: hint7
    attributes:
      label: Optional hint 1

  - type: textarea
    id: hint8
    attributes:
      label: Optional hint 2

  - type: textarea
    id: hint9
    attributes:
      label: Optional hint 3
      
  - type: textarea
    id: hint10
    attributes:
      label: Optional hint 4

  - type: textarea
    id: hint11
    attributes:
      label: Optional hint 5