name: Invisible flag submission
description: Submit invisible flag location
title: "[Submission - Invisible Flag]: "
labels: [submission]

body:
  - type: markdown
    attributes:
      value: |
        If you have a great idea for a place that one of the three invisible items can be randomly placed with the ""Move invisible flag checks" setting, submit it here.  
        Use https://fantasyanime.com/squaresoft/mariorpg/mariorpg_maps.htm for reference.  
        Note: unlike ship passwords and tadpole pond songs, invisible flag locations are not credited.

  - type: textarea
    id: location
    attributes:
      label: Describe the location
      description: |
        Give as much detail as possible.  Your location should ideally be unique and not confusable with any other location in the world (i.e. "blue curtain" is not specific enough).
        If you can, use the Lazy Shell editor (https://github.com/Yakibomb/LAZYSHELL-UPDATED/releases) to find the room number and xyz coordinates and include them here, it saves the devs a lot of time.
    validations:
      required: true

  - type: textarea
    id: hint
    attributes:
      label: Hint text
      description: |
        This will be what one of the Three Musty Fears says to give the player a hint about where the item is.  
        Yes, this is required, no, the developers will not do this for you.  
        Keep your hint brief and vague but helpful. i.e. "behind a wooden bat" = good, "in Monstro Town behind the welcome sign" = bad (too obvious).
    validations:
      required: true