name: Sunken Ship password submission
description: Submit Sunken Ship password for review
title: "[Submission - Sunken Ship]: "
labels: [submission]

body:
  - type: markdown
    attributes:
      value: |
        Submit a password to be added to the Sunken Ship password pool.  
        Supported characters for all text fields:  
        A-Z, a-z, 0-9, and any of `♥♪•~©:;#×+%↑→←*&()-/?!.,`

  - type: input
    id: submission
    attributes:
      label: Your password
      description: |
        Must be exactly six characters.<br>
        The five choices per letter box will be randomized to suit your submission.<br>
        References do not necessarily have to be related to the Mario series. Other games and franchises are welcome.
    validations:
      required: true

  - type: input
    id: passwordname
    attributes:
      label: Name of your submission
      description: |
        This is only used for developer purposes.
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Your name or handle
      description: |
        If your password is randomly selected for the seed, this is the name that will appear in the game's ending sequence.<br>
        Only capital letters A-Z, periods, spaces, and underscores are supported (no numbers or other characters).<br>
        Leave this blank if you prefer to be anonymous.

  - type: markdown
    attributes:
      value: |
        Contributors must write their own hint text for each of the 6 sunken ship puzzle rooms.<br>
        Players must have something to go off of so that they do not need to entirely bruteforce guess, so you must provide hint text for your own submission. This is required, developers will not come up with hint text for you.<br>
        You can write these however you like (ie they don't need to start with "Memo left by ___", unless you want them to), but they should be brief.<br><br>
        It is recommended to use the [Lazy Shell editor](https://github.com/Yakibomb/LAZYSHELL-UPDATED/releases) to preview your text for run-on sentences. There should be a good spot to await the user to press A within every 3 lines or less to prevent forced scrolling.

  - type: textarea
    id: hint1
    attributes:
      label: Trampoline Puzzle Memo
      description: |
        Original text: "Memo left by Magellean: It is found on the bed of the ocean."
    validations:
      required: true

  - type: textarea
    id: hint2
    attributes:
      label: Troopa Puzzle Memo
      description: |
        Original text: "Memo left by Magellean: There is an 's' in the word."
    validations:
      required: true

  - type: textarea
    id: hint3
    attributes:
      label: 3D Maze Memo
      description: |
        Original text: "Memo left by DeGama: It has two vowels."
    validations:
      required: true

  - type: textarea
    id: hint4
    attributes:
      label: Coin Snake Memo
      description: |
        Original text: "Memo left by DeGama: It has four consonants."
    validations:
      required: true

  - type: textarea
    id: hint5
    attributes:
      label: Cannonball Memo
      description: |
        Original text: "Memo left by Van Doren: At least... two consonants are side by side."
    validations:
      required: true

  - type: textarea
    id: hint6
    attributes:
      label: Rolling Barrel Memo
      description: |
        Original text: "Memo left by Van Doren: The 'r' comes before the 'l'."
    validations:
      required: true

  - type: textarea
    id: optional_hints
    attributes:
      label: Optional extra hints
      description: |
        There are 5 extra dialogs we can use for hint text (the notes placed around the ship before the puzzle rooms).<br>
        These are not required but you can include them if you're feeling creative.<br>
        List up to 5 extra hints in this text box, separated by line breaks.
