"""NPC list import"""

from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    RegularNPC(
        occupant=Key,
        initiator=EventInitiator.PRESS_A_OR_TOUCH_ANY_SIDE,
        event_script=E0241_FREESTANDING_1_GRANT,
        action_script=A0000_DO_NOTHING,
        speed=0,
        visible=True,
        x=10,
        y=28,
        z=0,
        z_half=True,
        direction=SOUTHWEST,
        face_on_trigger=True,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=False,
        cant_walk_up_stairs=True,
        cant_walk_under=True,
        cant_pass_walls=False,
        cant_jump_through=True,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=True,
        cant_move_if_in_air=True,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        show_shadow=True,
        height=3,
        cannot_clone=True),
    # NPC_1
    RegularNPC(
        occupant=Letter,
        initiator=EventInitiator.PRESS_A_FROM_FRONT,
        event_script=E1165_SEASIDE_LIBERATED_BEACH_LETTER,
        action_script=A0015_DO_NOTHING,
        speed=0,
        visible=True,
        x=11,
        y=20,
        z=0,
        z_half=True,
        direction=SOUTHWEST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=True,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=True,
        cant_move_if_in_air=True,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=True),
]
