"""Prize definitions, split one class per file.

The star-import header below is load-bearing: downstream modules do
from randomizer.logic.progression.prizes import * and rely on names that leak
through it (dialog/variable/sfx name constants), not just the prize classes.
"""

from __future__ import (annotations)
from enum import (StrEnum)
from re import (M)
from typing import (TYPE_CHECKING)
from smrpgpatchbuilder.datatypes.overworld_scripts.arguments import (NPC_0, NPC_1)
from randomizer.data.overworld_scripts.event.scripts.script_3645 import (NPC_2)
from randomizer.data.variables.dialog_names import *
from smrpgpatchbuilder.datatypes.overworld_scripts.event_scripts.classes import (EventScript, UsableEventScriptCommand)
from smrpgpatchbuilder.datatypes.overworld_scripts.event_scripts.commands import (JmpIfBitClear, Return, SetVarToConst, JmpToEvent, Inc, SetBit, CharacterJoinsParty, ClearBit, RunDialog, ApplySolidityModToLevel, ApplyTileModToLevel, RemoveObjectFromSpecificLevel)
from smrpgpatchbuilder.datatypes.overworld_scripts.arguments.area_objects import (NPC_3)
from randomizer.data.variables.variable_names import *
from randomizer.data.variables.overworld_sfx_names import *
from smrpgpatchbuilder.datatypes.overworld_scripts.arguments.area_objects import (MARIO, MALLOW, GENO, BOWSER, TOADSTOOL)
from smrpgpatchbuilder.datatypes.battles.formations_packs.types.classes import (FormationMember)
from randomizer.data.packs.pack_collection import (
    FORM0055_ONE_BELOMEENEMY3_ONE_MARIOCLONES_ONE_TOADSTOOL3,
    FORM0096_ONE_CULEX3D_ONE_FIRECRYS3D_ONE_WATERCRYS3D_ONE_EARTHCRYS3D_ONE_WINDCRYS3D,
    FORM0123_ONE_BOOSTERENEMY2_THREE_SNIFIT2_ONE_BOOSTERDUMMY,
    FORM0124_ONE_PUNCHINELLO2_ONE_STRONGBOBOMB3_ONE_STRONGBOBOMB1_ONE_STRONGBOBOMB4_ONE_STRONGBOBOMB2,
    FORM0137_ONE_BUNDT2_ONE_RASPBERRY2_TWO_TORTE2_ONE_CANDLE,
    FORM0216_ONE_JOHNNYENEMY2,
    FORM0217_ONE_JINXENEMY4_ONE_TEAMGAUGE,
    FORM0251_ONE_PUNCHINELLO_FOUR_MICROBOMB,
    FORM0258_ONE_CLERK_TWO_MADMALLETENEMYHENCHMAN,
    FORM0259_ONE_MANAGER_THREE_POUNDERENEMYHENCHMAN,
    FORM0260_ONE_DIRECTOR_FOUR_POUNDETTEENEMYHENCHMAN,
    FORM0261_ONE_GUNYOLK_ONE_FACTORYCHIEF,
    FORM0266_ONE_PANDORITE,
    FORM0267_ONE_HIDON_FOUR_GOOMBETTE,
    FORM0268_ONE_BOXBOY_ONE_FAUTSO,
    FORM0269_ONE_CHESTER_ONE_BAHAMUTTENEMY2,
    FORM0271_ONE_BOOSTER_THREE_SNIFITENEMYHENCHMAN,
    FORM0273_ONE_CROCO1,
    FORM0274_ONE_CROCO2,
    FORM0276_ONE_JOHNNY_FOUR_BANDANABLUE_TWO_WATERCRYSTAL,
    FORM0277_ONE_KINGCALAMARI_TWO_TENTACLESENEMY2_THREE_TENTACLES,
    FORM0278_ONE_BELOME1,
    FORM0279_ONE_BELOME2_ONE_MARIOCLONE_ONE_TOADSTOOL2,
    FORM0281_ONE_VALENTINA_ONE_DODO,
    FORM0282_ONE_CZARDRAGON_ONE_ZOMBONE_FOUR_HELIO,
    FORM0283_FIVE_SMILAX_ONE_MEGASMILAX,
    FORM0284_ONE_COUNTDOWN_TWO_DINGALING,
    FORM0285_ONE_BIRDETTA_ONE_SHELLY_FOUR_EGGBERT,
    FORM0286_ONE_BUNDT_ONE_RASPBERRY_TWO_TORTE,
    FORM0287_ONE_KNIFEGUY_ONE_GRATEGUY,
    FORM0288_ONE_JINX1,
    FORM0289_ONE_MACK_FOUR_BODYGUARD,
    FORM0290_ONE_YARIDOVICH_ONE_YARIDOVICHMIRAGE,
    FORM0291_ONE_BOWYER,
    FORM0292_ONE_AXEMRANGERS_ONE_AXEMRED_ONE_AXEMBLACK_ONE_AXEMPINK_ONE_AXEMGREEN_ONE_AXEMYELLOW,
    FORM0293_TWO_HAMMERBRO,
    FORM0294_ONE_CLOAKER_ONE_DOMINO_ONE_MADADDER,
    FORM0295_ONE_SMITHY1_ONE_SMELTER_TWO_MACHINEMADEBODYGUARD,
    FORM0296_ONE_EXOR_ONE_NEOSQUID_ONE_RIGHTEYE_ONE_LEFTEYE,
    FORM0297_ONE_JINX2,
    FORM0298_ONE_JINX3,
    FORM0299_ONE_JAGGER,
    FORM0314_ONE_FORMLESS_ONE_MOKURA,
    FORM0315_ONE_DODOENEMYSOLO,
    FORM0316_ONE_KAMEK_ONE_TERRAPIN,
    FORM0317_ONE_BOOMER_TWO_HANGINSHY,
    FORM0322_ONE_CULEX_ONE_FIRECRYSTAL_ONE_WATERCRYSTAL_ONE_EARTHCRYSTAL_ONE_WINDCRYSTAL,
)
from randomizer.data.items.items import (
    CrystalShardItem,
    ExtraShinyStoneItem,
    HammerItem,
    FroggieStickItem,
    NokNokShellItem,
    PunchGloveItem,
    FingerShotItem,
    CymbalsItem,
    ChompItem,
    MasherItem,
    ChompShellItem,
    StayVoucherItem,
    SuperHammerItem,
    HandGunItem,
    WhompGloveItem,
    SlapGloveItem,
    TroopaShellItem,
    ParasolItem,
    HurlyGlovesItem,
    DoublePunchItem,
    RibbitStickItem,
    SpikedLinkItem,
    MegaGloveItem,
    WarFanItem,
    HandCannonItem,
    StickyGloveItem,
    UltraHammerItem,
    SuperSlapItem,
    DrillClawItem,
    StarGunItem,
    SonicCymbalItem,
    LazyShellItem,
    FryingPanItem,
    LuckyHammerItem,
    ShirtItem,
    PantsItem,
    ThickShirtItem,
    ThickPantsItem,
    MegaShirtItem,
    MegaPantsItem,
    WorkPantsItem,
    MegaCapeItem,
    HappyShirtItem,
    HappyPantsItem,
    HappyCapeItem,
    HappyShellItem,
    PolkaDressItem,
    SailorShirtItem,
    SailorPantsItem,
    SailorCapeItem,
    NauticaDressItem,
    CourageShellItem,
    FuzzyShirtItem,
    FuzzyPantsItem,
    FuzzyCapeItem,
    FuzzyDressItem,
    FireShirtItem,
    FirePantsItem,
    FireCapeItem,
    FireShellItem,
    FireDressItem,
    HeroShirtItem,
    PrincePantsItem,
    StarCapeItem,
    HealShellItem,
    RoyalDressItem,
    SuperSuitItem,
    ZoomShoesItem,
    SafetyBadgeItem,
    JumpShoesItem,
    SafetyRingItem,
    AmuletItem,
    ScroogeRingItem,
    ExpBoosterItem,
    AttackScarfItem,
    RareScarfItem,
    BtubRingItem,
    AntidotePinItem,
    WakeUpPinItem,
    FearlessPinItem,
    TrueformPinItem,
    CoinTrickItem,
    GhostMedalItem,
    JinxBeltItem,
    FeatherItem,
    TroopaPinItem,
    SignalRingItem,
    QuartzCharmItem,
    MushroomItem,
    MidMushroomItem,
    MaxMushroomItem,
    HoneySyrupItem,
    MapleSyrupItem,
    RoyalSyrupItem,
    PickMeUpItem,
    AbleJuiceItem,
    BracerItem,
    EnergizerItem,
    YoshiAdeItem,
    RedEssenceItem,
    KerokeroColaItem,
    YoshiCookieItem,
    PureWaterItem,
    SleepyBombItem,
    BadMushroomItem,
    FireBombItem,
    IceBombItem,
    FlowerTabItem,
    FlowerJarItem,
    FlowerBoxItem,
    YoshiCandyItem,
    FroggieDrinkItem,
    MukuCookieItem,
    ElixirItem,
    MegalixirItem,
    SeeYaItem,
    TempleKeyItem,
    GoodieBagItem,
    EarlierTimesItem,
    FreshenUpItem,
    RareFrogCoinItem,
    WalletItem,
    CricketPieItem,
    RockCandyItem,
    CastleKey1Item,
    CastleKey2Item,
    BambinoBombItem,
    RoomKeyItem,
    ElderKeyItem,
    ShedKeyItem,
    FrightBombItem,
    BeetleBoxItem,
    LuckyJewelItem,
    CrystallineItem,
    PowerBlastItem,
    WiltShroomItem,
    RottenMushItem,
    MoldyMushItem,
    SeedItem,
    FertilizerItem,
    BigBooFlagItem,
    DryBonesFlagItem,
    GreaperFlagItem,
    CricketJamItem,
    FireworksItem,
    BrightCardItem,
    StarEggItem,
    ShoesItem,
    BroochItem,
    RingItem,
    CrownItem,
    LazyShellItem2,
    MushroomItem2,
    WonderChompItem,
    Stella023Item,
    SageStickItem,
    TeamworkBandItem,
    EnduringBroochItem,
)
from randomizer.data.variables.variable_names import *
from randomizer.data.variables.room_names import *
from randomizer.data.variables.event_script_names import *
from randomizer.data.variables.battlefield_names import *
from randomizer.data.enemies.enemies import *
from randomizer.data.variables.battle_event_names import *
from randomizer.data.physical_objects.bosses import *
from randomizer.data.physical_objects.henchmen import *
from randomizer.data.physical_objects.characters import (MarioCharacterNPC, MallowCharacterNPC, GenoCharacterNPC, BowserCharacterNPC, ToadstoolCharacterNPC)
from randomizer.data.allies.allies import (MARIO_Ally, MALLOW_Ally, GENO_Ally, BOWSER_Ally, TOADSTOOL_Ally)
from randomizer.types.prize import (
    BossFightHenchman,
    CharacterName,
    FrogCoinQuantityPrize,
    EXPStarPrize,
    StandardPrize,
    CoinQuantityPrize,
    SlotsPrize,
    BossFightPrize,
    CharacterPrize,
    StarPiecePrize,
    ItemPrize,
    SpellPrize,
    MimicFightInitiatorPrize,
    TreasureHunterNickname,
    ProgressiveItemPrize,
    WeddingGearPrize,
    SpecialItemPrizeType,
    KeyPrize,
    FortuneEnum,
)
from randomizer.data.spells.spells import (
    JumpSpell,
    FireOrbSpell,
    SuperJumpSpell,
    SuperFlameSpell,
    UltraJumpSpell,
    UltraFlameSpell,
    ThunderboltSpell,
    HPRainSpell,
    PsychopathSpell,
    ShockerSpell,
    SnowySpell,
    PsychBombSpell,
    GenoBeamSpell,
    GenoBoostSpell,
    GenoWhirlSpell,
    GenoBlastSpell,
    GenoFlashSpell,
    TerrorizeSpell,
    PoisonGasSpell,
    CrusherSpell,
    BowserCrushSpell,
    TherapySpell,
    GroupHugSpell,
    MuteSpell,
    SleepyTimeSpell,
    ComeBackSpell,
    StarRainSpell,
)
from randomizer.data.variables.overworld_sfx_names import *
from randomizer.data.physical_objects.items import *
from randomizer.types.flags import (
    BanditsWayGating,
    BanditsWayGate,
    KeroSewersGate,
    KeroSewersGating,
    BoosterTowerGate,
    BoosterTowerGating,
    PipeVaultGate,
    PipeVaultGating,
    Moleville1Gate,
    Moleville1Gating,
    ForestMazeGate,
    ForestMazeGating,
    BoosterHillGate,
    BoosterHillGating,
    MarrymoreGate,
    MarrymoreGating,
    YaridovichGate,
    YaridovichGating,
    SeaGate,
    SeaGating,
    LandsEndGate,
    LandsEndGating,
    BelomeTempleGate,
    BelomeTempleGating,
    MonstroTownGate,
    MonstroTownGating,
    NimbusGate,
    NimbusGating,
    BarrelVolcanoGate,
    BarrelVolcanoGating,
    BowsersKeepGate,
    BowsersKeepGating,
    FactoryGate,
    FactoryGating,
    WinCondition,
    WinConditions,
)
from smrpgpatchbuilder.datatypes.overworld_scripts.arguments.area_objects import (NPC_0, NPC_6, NPC_9, NPC_10)
from randomizer.data.rooms.npcs import (MAGIKOOPA_NPC_2, MAGIKOOPA_NPC_3)
from randomizer.data.variables.room_names import (R432_ENDING_CREDITS_JOHNNY_LOOKING_OUT_AT_SUNSET_ON_BEACH_SHORE, R435_ENDING_CREDITS_BOWSERS_KEEP_BOWSER_TROOPS_REPAIR, R505_ENDING_CREDITS_YOSTER_ISLE_CROCO_RACING_YOSHI, R506_ENDING_CREDITS_MARRYMORE_CHAPEL_BOOSTER_WEDDING_VALENTINA)

if TYPE_CHECKING:
    from randomizer.types.gameworld import (GameWorld)
    from randomizer.types.prizelocation import (BossFightLocation, BossFightLocationNPC)
    from randomizer.types.physical_objects import (BossNPC, NPC as NPCPhysical)
    from smrpgpatchbuilder.datatypes.levels.classes import (NPC as NPCBase)


from .boss_fight_prizes import *
from .character_prizes import *
from .coin_prizes import *
from .exp_star_prizes import *
from .item_prizes import *
from .key_prizes import *
from .mimic_prizes import *
from .misc_prizes import *
from .slot_prizes import *
from .spell_prizes import *
from .star_piece_prizes import *


ALL_BOSS_FIGHTS: list[type[BossFightPrize]] = [
    HammerBrosFight,
    Croco1BossFight,
    MackBossFight,
    PandoriteBossFight,
    Belome1BossFight,
    BowyerBossFight,
    Croco2BossFight,
    PunchinelloBossFight,
    BoosterBossFight,
    KnifeGuyGrateGuyBossFight,
    BundtBossFight,
    KingCalamariBossFight,
    HidonBossFight,
    JohnnyBossFight,
    YaridovichBossFight,
    MokuraBossFight,
    Belome2BossFight,
    JaggerBossFight,
    Jinx1BossFight,
    Jinx2BossFight,
    Jinx3BossFight,
    CulexBossFight,
    BoxBoyBossFight,
    MegasmilaxBossFight,
    DodoBossFight,
    BirdettaBossFight,
    ValentinaBossFight,
    CzarDragonBossFight,
    AxemRangersBossFight,
    ChesterBossFight,
    KamekBossFight,
    BoomerBossFight,
    ExorBossFight,
    CountdownBossFight,
    CloakerDominoBossFight,
    ClerkBossFight,
    ManagerBossFight,
    DirectorBossFight,
    GunyolkBossFight,
    SmithyBossFight,
    Punchinello2BossFight,
    Booster2BossFight,
    Bundt2BossFight,
    Johnny2Fight,
    Belome3Fight,
    Jinx4BossFight,
    Culex3DBossFight,
]
