"""NPC list import"""

from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    BattlePackNPC(
        occupant=PipePiranhaPlant,
        initiator=EventInitiator.ANYTHING_EXCEPT_PRESS_A,
        after_battle=PostBattleBehaviour.REMOVE_PERMANENTLY,
        battle_pack=PACK0034_PIRANHA_WITH_SHYRANGER,
        action_script=A0665_PIPE_VAULT_PIRANHA,
        speed=0,
        visible=True,
        x=7,
        y=50,
        z=0,
        z_half=False,
        direction=SOUTHWEST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=True,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=False,
        cant_pass_npcs=True,
        byte3_bit5=True,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=False,
        cant_move_if_in_air=True,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=False,
        cannot_clone=False),
    # NPC_1
    BattlePackClone(
        occupant=PipePiranhaPlant,
        battle_pack=PACK0035_MULTIPLE_PIRANHA_WITH_SHYRANGER,
        action_script=A0666_PIPE_VAULT_PIRANHA,
        visible=True,
        x=9,
        y=46,
        z=0,
        z_half=False,
        direction=SOUTHWEST,
        priority_0=False,
        priority_1=False,
        priority_2=False,
        cannot_clone=False),
    # NPC_2
    BattlePackClone(
        occupant=PipePiranhaPlant,
        battle_pack=PACK0034_PIRANHA_WITH_SHYRANGER,
        action_script=A0667_PIPE_VAULT_PIRANHA,
        visible=True,
        x=11,
        y=42,
        z=0,
        z_half=False,
        direction=SOUTHWEST,
        priority_0=False,
        priority_1=False,
        priority_2=False,
        cannot_clone=False),
    # NPC_3
    BattlePackClone(
        occupant=PipePiranhaPlant,
        battle_pack=PACK0035_MULTIPLE_PIRANHA_WITH_SHYRANGER,
        action_script=A0668_PIPE_VAULT_PIRANHA,
        visible=True,
        x=13,
        y=38,
        z=0,
        z_half=False,
        direction=SOUTHWEST,
        priority_0=False,
        priority_1=False,
        priority_2=False,
        cannot_clone=False),
]
