from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=16,
        y=40,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R137_LANDS_END_AREA_01,
        show_message = False,
        dst_x = 11,
        dst_y = 18,
        dst_z = 6,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=30,
        y=19,
        z=4,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R139_LANDS_END_AREA_03_GECKITS_PLAYING_CANNONBALL,
        show_message = False,
        dst_x = 3,
        dst_y = 117,
        dst_z = 4,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
