"""NPC list import"""

from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    RegularNPC(
        occupant=Shyster,
        initiator=EventInitiator.NONE,
        event_script=E0256_RETURN,
        action_script=A0103_MK_THRONE_HENCHMAN_BOUNCE_BOSS_FIGHT_START,
        speed=0,
        visible=True,
        x=12,
        y=94,
        z=2,
        z_half=False,
        direction=SOUTHWEST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=False,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=False,
        byte3_bit7=False,
        slidable_along_walls=False,
        cant_move_if_in_air=False,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False),
    # NPC_1
    RegularClone(
        occupant=Shyster,
        event_script=E0256_RETURN,
        action_script=A0103_MK_THRONE_HENCHMAN_BOUNCE_BOSS_FIGHT_START,
        visible=True,
        x=13,
        y=97,
        z=2,
        z_half=False,
        direction=SOUTHWEST,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False),
    # NPC_2
    RegularNPC(
        occupant=RedSmallToad,
        initiator=EventInitiator.PRESS_A_FROM_ANY_SIDE,
        event_script=E0385_MUSHROOM_KINGDOM_OCCUPIED_TOADSTOOLS_ROOM_ANTECHAMBER_TOAD,
        action_script=A0119_SLOW_SEQUENCE_LOOP,
        speed=0,
        visible=True,
        x=4,
        y=95,
        z=0,
        z_half=False,
        direction=SOUTHEAST,
        face_on_trigger=True,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=False,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=True,
        cant_move_if_in_air=False,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False),
]
