"""Types, tables, and enums for progress location development."""

from .classes import (
    Inventory,
    ProgressLocation,
    BossFightLocation,
    BossStarPiecePrize,
    ItemLocation,
    FrogDiscipleShopItem,
    ChestLocation,
    EarlygameChestLocation,
    MidgameChestLocation,
    ChestLocationAllowCoins,
    ChestLocationAllowSlots,
    MimicReloadRewardChest,
    GrantLocation,
    InvisibleItemCandidate,
    TreasureShopItem,
    StartingItemGrant,
    FreestandingLocation,
    MidasRiverTunnelItem,
    PacketItem,
    CharacterSpottedLocation,
    CharacterReplacementFill,
    CharacterRecruitLocation,
    CharacterSpellSlot,
    LaterSpellSlot,
    MarioSpellSlot,
    MallowSpellSlot,
    GenoSpellSlot,
    ToadstoolSpellSlot,
    BowserSpellSlot,
    ProgressLocationT)
from .enums import LocationWorldArea, PacketType
from .table import ROOMS_BATTLEFIELD_DICT
