from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=22,
        y=100,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R275_MOLEVILLE_MINES_AREA_06_SMALL_ROOM_LEADING_TO_AREA_06,
        show_message = False,
        dst_x = 3,
        dst_y = 117,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=27,
        y=85,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R279_MOLEVILLE_MINES_AREA_08_CROCOS_BOMBED_ROOM,
        show_message = False,
        dst_x = 11,
        dst_y = 119,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=22,
        y=87,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R282_MOLEVILLE_MINES_AREA_10_SMALL_ROOM_WMINECART_TRACKS,
        show_message = False,
        dst_x = 27,
        dst_y = 123,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
]
