# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectsequencedisassembler --rom ROM > openmode_sequence_debug.txt
from randomizer.helpers.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.helpers.eventtables import RadialDirections, AreaObjects, NPCPackets, Sounds, Coords, CoordUnits, Rooms
script = [
    {
        "identifier": 'ACTION_925_set_priority_0',
        "command": 'set_priority',
        "args": [2]
    },
    {
        "identifier": 'ACTION_925_set_700C_to_current_level_1',
        "command": 'set_700C_to_current_level'
    },
    {
        "identifier": 'ACTION_925_jmp_if_700C_equals_short_2',
        "command": "jmp_if_var_equals_const",
        "args": [0x700C, 79, 'ACTION_925_set_priority_4']
    },
    {
        "identifier": 'ACTION_925_set_animation_speed_3',
        "command": 'set_animation_speed',
        "args": [SequenceSpeeds.SLOW, [_0x10Flags.SEQUENCE]]
    },
    {
        "identifier": 'ACTION_925_set_priority_4',
        "command": 'set_priority',
        "args": [3]
    },
    {
        "identifier": 'ACTION_925_shift_south_pixels_5',
        "command": 'shift_south_pixels',
        "args": [3]
    },
    {
        "identifier": 'ACTION_925_set_sprite_sequence_6',
        "command": 'set_sprite_sequence',
        "args": [1, 0, [_0x08Flags.READ_AS_SEQUENCE]]
    },
    {
        "identifier": 'ACTION_925_pause_8',
        "command": 'pause',
        "args": [1]
    },
    {
        "identifier": 'ACTION_925_jmp_9',
        "command": 'jmp',
        "args": ['ACTION_925_pause_8']
    }
]
