"""NPC list import"""

from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    RegularNPC(
        occupant=WhirlpoolBubble,
        initiator=EventInitiator.NONE,
        event_script=E0256_RETURN,
        action_script=A0926_SEA_ESCAPE_BUBBLE,
        speed=0,
        visible=True,
        x=25,
        y=120,
        z=0,
        z_half=False,
        direction=SOUTHWEST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=False,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=False,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=False,
        byte3_bit7=False,
        slidable_along_walls=True,
        cant_move_if_in_air=True,
        byte7_upper2=True,
        priority_0=False,
        priority_1=True,
        priority_2=False,
        cannot_clone=False,
    ),
    # NPC_1
    RegularClone(
        occupant=WhirlpoolBubble,
        event_script=E0256_RETURN,
        action_script=A0927_SEA_ESCAPE_BUBBLE,
        visible=True,
        x=24,
        y=119,
        z=0,
        z_half=False,
        direction=SOUTHWEST,
        priority_0=False,
        priority_1=True,
        priority_2=False,
        cannot_clone=False,
    ),
]
