# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.helpers.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.helpers.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": 'EVENT_647_apply_tile_mod_0',
        "command": 'apply_tile_mod',
        "args": [Rooms._154_MARRYMORE_CHAPEL_SANCTUARY_DURING_BOOSTER, 0, [_0x6AFlags.USE_ALTERNATE]]
    },
    {
        "identifier": 'EVENT_647_play_sound_1',
        "command": 'play_sound',
        "args": [Sounds._084_SMOKED, 6]
    },
    {
        "identifier": 'EVENT_647_dec_2',
        "command": 'dec',
        'args': [0x70ae, 1],
    },
    {
        "identifier": 'EVENT_647_set_short_3',
        "command": "set_var_to_const",
        "args": [0x701e, 0x012c]
    },
    {
        "identifier": 'EVENT_647_run_background_event_with_pause_return_on_exit_4',
        "command": 'run_background_event_with_pause_return_on_exit',
        "args": [648, 0x701e, []]
    },
    {
        "identifier": 'EVENT_647_ret_5',
        "command": 'ret'
    }
]
