# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.helpers.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.helpers.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": "EVENT_253_room_7_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 7, 'EVENT_253_room_7_set']
    },
    {
        "identifier": "EVENT_253_room_20_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 20, 'EVENT_253_room_20_328_set']
    },
    {
        "identifier": "EVENT_253_room_34_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 34, 'EVENT_253_room_34_set']
    },
    {
        "identifier": "EVENT_253_room_35_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 35, 'EVENT_253_room_35_logic']
    },
    {
        "identifier": "EVENT_253_room_39_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 39, 'EVENT_253_room_39_set']
    },
    {
        "identifier": "EVENT_253_room_67_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 67, 'EVENT_253_room_67_set']
    },
    {
        "identifier": "EVENT_253_room_74_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 74, 'EVENT_253_room_74_logic']
    },
    {
        "identifier": "EVENT_253_room_75_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 75, 'EVENT_253_room_75_logic']
    },
    {
        "identifier": "EVENT_253_room_83_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 83, 'EVENT_253_room_83_84_logic']
    },
    {
        "identifier": "EVENT_253_room_84_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 84, 'EVENT_253_room_83_84_logic']
    },
    {
        "identifier": "EVENT_253_room_86_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 86, 'EVENT_253_room_86_logic']
    },
    {
        "identifier": "EVENT_253_room_92_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 92, 'EVENT_253_room_92_logic']
    },
    {
        "identifier": "EVENT_253_room_93_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 93, 'EVENT_253_room_93_94_logic']
    },
    {
        "identifier": "EVENT_253_room_94_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 94, 'EVENT_253_room_93_94_logic']
    },
    {
        "identifier": "EVENT_253_room_95_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 95, 'EVENT_253_room_95_96_logic']
    },
    {
        "identifier": "EVENT_253_room_96_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 96, 'EVENT_253_room_95_96_logic']
    },
    {
        "identifier": "EVENT_253_room_100_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 100, 'EVENT_253_room_100_logic']
    },
    {
        "identifier": "EVENT_253_room_108_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 108, 'EVENT_253_room_108_logic']
    },
    {
        "identifier": "EVENT_253_room_110_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 110, 'EVENT_253_room_110_logic']
    },
    {
        "identifier": "EVENT_253_room_143_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 143, 'EVENT_253_room_143_logic']
    },
    {
        "identifier": "EVENT_253_room_154_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 154, 'EVENT_253_room_154_logic']
    },
    {
        "identifier": "EVENT_253_room_171_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 171, 'EVENT_253_room_171_logic']
    },
    {
        "identifier": "EVENT_253_room_189_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 189, 'EVENT_253_room_189_logic']
    },
    {
        "identifier": "EVENT_253_room_190_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 190, 'EVENT_253_room_190_logic']
    },
    {
        "identifier": "EVENT_253_room_192_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 192, 'EVENT_253_room_192_logic']
    },
    {
        "identifier": "EVENT_253_room_194_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 194, 'EVENT_253_room_194_logic']
    },
    {
        "identifier": "EVENT_253_room_197_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 197, "EVENT_253_room_197_logic"]
    },
    {
        "identifier": "EVENT_253_room_203_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 203, 'EVENT_253_room_203_logic']
    },
    {
        "identifier": "EVENT_253_room_204_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 204, 'EVENT_253_room_204_logic']
    },
    {
        "identifier": "EVENT_253_room_205_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 205, 'EVENT_253_room_205_logic']
    },
    {
        "identifier": "EVENT_253_room_206_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 206, 'EVENT_253_room_206_logic']
    },
    {
        "identifier": "EVENT_253_room_254_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 254, 'EVENT_253_room_254_logic']
    },
    {
        "identifier": "EVENT_253_room_255_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 255, 'EVENT_253_room_255_logic']
    },
    {
        "identifier": "EVENT_253_room_273_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 273, 'EVENT_253_room_273_logic']
    },
    {
        "identifier": "EVENT_253_room_277_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 277, 'EVENT_253_room_277_logic']
    },
    {
        "identifier": "EVENT_253_room_283_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 283, 'EVENT_253_room_283_logic']
    },
    {
        "identifier": "EVENT_253_room_314_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 314, "EVENT_253_room_314_logic"]
    },
    {
        "identifier": "EVENT_253_room_328_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 328, 'EVENT_253_room_20_328_set']
    },
    {
        "identifier": "EVENT_253_room_330_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 330, 'EVENT_253_room_330_set']
    },
    {
        "identifier": "EVENT_253_room_335_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 335, 'EVENT_253_room_335_logic']
    },
    {
        "identifier": "EVENT_253_room_336_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 336, 'EVENT_253_room_336_logic']
    },
    {
        "identifier": "EVENT_253_room_339_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 339, "EVENT_253_room_339_logic"]
    },
    {
        "identifier": "EVENT_253_room_346_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 346, "EVENT_253_room_346_logic"]
    },
    {
        "identifier": "EVENT_253_room_351_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 351, "EVENT_253_room_351_logic"]
    },
    {
        "identifier": "EVENT_253_room_397_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 397, "EVENT_253_room_397_logic"]
    },
    {
        "identifier": "EVENT_253_room_399_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 399, "EVENT_253_room_399_logic"]
    },
    {
        "identifier": "EVENT_253_room_406_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 406, "EVENT_253_room_406_logic"]
    },
    {
        "identifier": "EVENT_253_room_407_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 407, "EVENT_253_room_407_logic"]
    },
    {
        "identifier": "EVENT_253_room_409_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 409, "EVENT_253_room_409_logic"]
    },
    {
        "identifier": "EVENT_253_room_413_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 413, "EVENT_253_room_413_logic"]
    },
    {
        "identifier": "EVENT_253_room_414_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 414, "EVENT_253_room_414_logic"]
    },
    {
        "identifier": "EVENT_253_room_438_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 438, "EVENT_253_room_438_logic"]
    },
    {
        "identifier": "EVENT_253_room_480_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 480, "EVENT_253_room_480_481_logic"]
    },
    {
        "identifier": "EVENT_253_room_481_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 481, "EVENT_253_room_480_481_logic"]
    },
    {
        "identifier": "EVENT_253_room_483_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 483, 'EVENT_253_room_491_483_logic']
    },
    {
        "identifier": "EVENT_253_room_491_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 491, 'EVENT_253_room_491_483_logic']
    },
    {
        "identifier": "EVENT_253_room_493_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 493, "EVENT_253_room_493_logic"]
    },
    {
        "identifier": "EVENT_253_pandorite_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 512, 'EVENT_253_pandorite_set']
    },
    {
        "identifier": "EVENT_253_hidon_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 513, 'EVENT_253_hidon_set']
    },
    {
        "identifier": "EVENT_253_croco_2_jump",
        "command": 'jmp_if_var_equals_const',
        'args': [0x7000, 518, 'EVENT_253_croco_2_set']
    },
    {
        "identifier": "EVENT_253_cancel",
        "command": 'ret'
    },
    {
        "identifier": 'EVENT_253_room_7_set',
        "command": "set_var_to_const",
        "args": [0x70a7, 115]
    },
    {
        "identifier": "EVENT_253_room_7_logic",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_20_328_set',
        "command": "set_var_to_const",
        "args": [0x70a7, 96]
    },
    {
        "identifier": "EVENT_253_room_20_328_logic",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_34_set',
        "command": "set_var_to_const",
        "args": [0x70a7, 109]
    },
    {
        "identifier": "EVENT_253_room_34_logic",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": "EVENT_253_room_35_logic",
        "command": 'jmp_to_event',
        "args": [157]
    },
    {
        "identifier": 'EVENT_253_room_39_set',
        "command": "set_var_to_const",
        "args": [0x70a7, 174]
    },
    {
        "identifier": "EVENT_253_room_39_logic",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_67_set',
        "command": "set_var_to_const",
        "args": [0x70a7, 7]
    },
    {
        "identifier": "EVENT_253_room_67_logic",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": "EVENT_253_room_74_logic",
        "command": 'jmp_to_event',
        "args": [3097]
    },
    {
        "identifier": 'EVENT_253_room_75_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 6]
    },
    {
        "identifier": "EVENT_253_room_75_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_83_84_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 163]
    },
    {
        "identifier": "EVENT_253_room_83_84_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_86_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 9]
    },
    {
        "identifier": "EVENT_253_room_86_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_92_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 176]
    },
    {
        "identifier": "EVENT_253_room_92_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": "EVENT_253_room_93_94_logic",
        "command": 'jmp_to_event',
        "args": [157]
    },
    {
        "identifier": 'EVENT_253_room_95_96_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 115]
    },
    {
        "identifier": "EVENT_253_room_95_96_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": "EVENT_253_room_100_logic",
        "command": 'jmp_to_event',
        "args": [157]
    },
    {
        "identifier": "EVENT_253_room_108_logic",
        "command": 'jmp_to_event',
        "args": [157]
    },
    {
        "identifier": 'EVENT_253_room_110_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 91]
    },
    {
        "identifier": "EVENT_253_room_110_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_143_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 115]
    },
    {
        "identifier": "EVENT_253_room_143_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": "EVENT_253_room_154_logic",
        "command": 'jmp_to_event',
        "args": [3932]
    },
    {
        "identifier": 'EVENT_253_room_171_logic',
        "command": "set_var_to_const",
        "args": [0x7000, 150]
    },
    {
        "identifier": "EVENT_253_room_171_jmp",
        "command": 'jmp_to_event',
        "args": [159]
    },
    {
        "identifier": 'EVENT_253_room_189_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 162]
    },
    {
        "identifier": "EVENT_253_room_189_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_190_logic',
        "command": "set_var_to_const",
        "args": [0x7000, 10]
    },
    {
        "identifier": "EVENT_253_room_190_jmp",
        "command": 'jmp_to_event',
        "args": [159]
    },
    {
        "identifier": 'EVENT_253_room_192_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 78]
    },
    {
        "identifier": "EVENT_253_room_192_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_194_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 115]
    },
    {
        "identifier": "EVENT_253_room_194_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_197_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 12]
    },
    {
        "identifier": 'EVENT_253_room_197_jmp',
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_203_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 99]
    },
    {
        "identifier": 'EVENT_253_room_203_jmp',
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_204_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 115]
    },
    {
        "identifier": 'EVENT_253_room_204_jmp',
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_205_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 5]
    },
    {
        "identifier": "EVENT_253_room_205_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_206_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 128]
    },
    {
        "identifier": "EVENT_253_room_206_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_254_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 158]
    },
    {
        "identifier": "EVENT_253_room_254_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_255_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 90]
    },
    {
        "identifier": "EVENT_253_room_255_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_273_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 115]
    },
    {
        "identifier": "EVENT_253_room_273_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_277_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 115]
    },
    {
        "identifier": "EVENT_253_room_277_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_283_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 115]
    },
    {
        "identifier": "EVENT_253_room_283_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_314_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 117]
    },
    {
        "identifier": "EVENT_253_room_314_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_330_set',
        "command": "set_var_to_const",
        "args": [0x70a7, 85]
    },
    {
        "identifier": "EVENT_253_room_330_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": "EVENT_253_room_335_logic",
        "command": 'jmp_to_event',
        "args": [157]
    },
    {
        "identifier": 'EVENT_253_room_336_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 148]
    },
    {
        "identifier": "EVENT_253_room_336_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": "EVENT_253_room_339_logic",
        "command": 'jmp_to_event',
        "args": [184]
    },
    {
        "identifier": 'EVENT_253_room_346_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 107]
    },
    {
        "identifier": "EVENT_253_room_346_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_351_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 94]
    },
    {
        "identifier": "EVENT_253_room_351_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_397_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 81]
    },
    {
        "identifier": "EVENT_253_room_397_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_399_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 89]
    },
    {
        "identifier": "EVENT_253_room_399_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_406_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 131]
    },
    {
        "identifier": "EVENT_253_room_406_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_407_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 92]
    },
    {
        "identifier": "EVENT_253_room_407_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_409_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 134]
    },
    {
        "identifier": "EVENT_253_room_409_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_413_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 116]
    },
    {
        "identifier": "EVENT_253_room_413_logic_2",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_414_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 116]
    },
    {
        "identifier": "EVENT_253_room_414_logic_2",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_438_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 159]
    },
    {
        "identifier": "EVENT_253_room_438_logic_2",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_480_481_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 115]
    },
    {
        "identifier": "EVENT_253_room_480_481_logic_2",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_room_491_483_logic',
        "command": "set_var_to_const",
        "args": [0x70a7, 102]
    },
    {
        "identifier": "EVENT_253_room_491_483_jmp",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": "EVENT_253_room_493_logic",
        "command": 'jmp_to_event',
        "args": [161]
    },
    {
        "identifier": 'EVENT_253_pandorite_set',
        "command": "set_var_to_const",
        "args": [0x70a7, 87]
    },
    {
        "identifier": "EVENT_253_pandorite_logic",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_hidon_set',
        "command": "set_var_to_const",
        "args": [0x70a7, 75]
    },
    {
        "identifier": "EVENT_253_hidon_logic",
        "command": 'jmp_to_event',
        "args": [160]
    },
    {
        "identifier": 'EVENT_253_croco_2_set',
        "command": "set_var_to_const",
        "args": [0x70a7, 135]
    },
    {
        "identifier": "EVENT_253_croco_2_logic",
        "command": 'jmp_to_event',
        "args": [160]
    },
]
