# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.helpers.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.helpers.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    {
        "identifier": 'EVENT_1113_jmp_if_bit_set_3',
        "command": 'jmp_if_bit_set',
        "args": [0x7054, 6, 'EVENT_1113_run_dialog_33']
    },
    {
        "identifier": 'EVENT_1113_jmp_if_bit_set_4',
        "command": 'jmp_if_bit_set',
        "args": [0x7054, 5, 'EVENT_1113_jmp_if_bit_clear_13']
    },
    {
        "identifier": 'EVENT_1113_jmp_if_bit_set_5',
        "command": 'jmp_if_bit_set',
        "args": [0x7051, 4, 'EVENT_1113_jmp_if_bit_clear_9']
    },
    {
        "identifier": 'EVENT_1113_run_dialog_7',
        "command": 'run_dialog',
        "args": [2664, AreaObjects.MEM_70A8, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE, _0x60Flags.USE_BACKGROUND]]
    },
    {
        "identifier": 'EVENT_1113_ret_8',
        "command": 'ret'
    },
    {
        "identifier": 'EVENT_1113_jmp_if_bit_clear_9',
        "command": 'jmp_if_bit_clear',
        "args": [0x7057, 4, 'EVENT_1113_run_dialog_31']
    },
    {
        "identifier": 'EVENT_1113_run_dialog_11',
        "command": 'run_dialog',
        "args": [2665, AreaObjects.MEM_70A8, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE, _0x60Flags.USE_BACKGROUND]]
    },
    {
        "identifier": 'EVENT_1113_ret_12',
        "command": 'ret'
    },
    {
        "identifier": 'EVENT_1113_jmp_if_bit_clear_13',
        "command": 'jmp_if_bit_clear',
        "args": [0x7089, 0, 'EVENT_1113_run_dialog_insert']
    },
    {
        "identifier": 'EVENT_1113_run_dialog_14',
        "command": 'run_dialog',
        "args": [2663, AreaObjects.MEM_70A8, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE, _0x60Flags.USE_BACKGROUND]]
    },
    {
        "identifier": 'EVENT_1113_run_dialog_15',
        "command": 'run_dialog',
        "args": [2668, AreaObjects.MEM_70A8, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE, _0x60Flags.USE_BACKGROUND]]
    },
    {
        "identifier": 'EVENT_1113_fade_out_music_to_volume_16',
        "command": 'fade_out_music_to_volume',
        "args": [1, 0]
    },
    {
        "identifier": 'EVENT_1113_pause_17',
        "command": 'pause',
        "args": [30]
    },
    {
        "identifier": "EVENT_1113_3rd_song_hint",
        "command": "run_event_as_subroutine",
        "args": [1088]
    },
    {
        "identifier": 'EVENT_1113_run_dialog_28',
        "command": 'run_dialog',
        "args": [2673, AreaObjects.MEM_70A8, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE, _0x60Flags.USE_BACKGROUND]]
    },
    {
        "identifier": 'EVENT_1113_fade_out_music_to_volume_29',
        "command": 'fade_out_music_to_volume',
        "args": [3, 100]
    },
    {
        "identifier": 'EVENT_1113_ret_32',
        "command": 'ret'
    },
    {
        "identifier": 'EVENT_1113_run_dialog_31',
        "command": 'run_dialog',
        "args": [2660, AreaObjects.MEM_70A8, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE, _0x60Flags.USE_BACKGROUND]]
    },
    {
        "identifier": 'EVENT_1113_ret_32_',
        "command": 'ret'
    },
    {
        "identifier": 'EVENT_1113_run_dialog_insert',
        "command": 'run_dialog',
        "args": [2662, AreaObjects.MEM_70A8, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE, _0x60Flags.USE_BACKGROUND]]
    },
    {
        "identifier": 'EVENT_1113_ret_insert',
        "command": 'ret'
    },
    {
        "identifier": 'EVENT_1113_run_dialog_33',
        "command": 'run_dialog',
        "args": [2674, AreaObjects.MEM_70A8, [_0x60Flags.CLOSABLE, _0x60Flags.ASYNC, _0x60Flags.MULTILINE, _0x60Flags.USE_BACKGROUND]]
    },
    {
        "identifier": 'EVENT_1113_ret_34',
        "command": 'ret'
    }
]
