# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.helpers.eventtables import (
    ControllerDirections,
    RadialDirections,
    Rooms,
    Sounds,
    AreaObjects,
    NPCPackets,
    Locations,
    Shops,
    EventSequences,
    MenuTutorials,
    OverworldSequences,
    PlayableCharacters,
    EquipSlots,
    DialogDurations,
    IntroTitles,
    Colours,
    PaletteSetTypes,
    Music,
    MusicDirections,
    MusicPitch,
    Coords,
    CoordUnits,
    Tutorials,
    _0x40Flags,
    _0x60Flags,
    _0x62Flags,
    _0x63Flags,
    _0x68Flags,
    _0x6AFlags,
    _0x6BFlags,
    _0x81Flags,
    _0x84Flags,
)
from randomizer.helpers.objectsequencetables import (
    SequenceSpeeds,
    VramPriority,
    _0x08Flags,
    _0x0AFlags,
    _0x10Flags,
)
from randomizer.data import items

script = [
    {
        "identifier": "EVENT_1926_jmp_if_bit_set_0",
        "command": "jmp_if_bit_set",
        "args": [0x708B, 5, "EVENT_1926_jmp_if_bit_clear_73"],
    },
    # kggg fight
    {
        "identifier": "EVENT_1926_start_battle_46",
        "command": "run_event_as_subroutine",
        "args": [354],
    },
    {
        "identifier": "EVENT_1926_jmp_if_bit_clear_47",
        "command": "jmp_if_bit_clear",
        "args": [0x7040, 0, "EVENT_1926_fade_out_music_to_volume_49"],
    },
    {
        "identifier": "EVENT_1926_reset_and_choose_game_48",
        "command": "reset_and_choose_game",
    },
    {
        "identifier": "EVENT_1926_fade_out_music_to_volume_49",
        "command": "fade_out_music_to_volume",
        "args": [0, 0],
    },
    {
        "identifier": "EVENT_1926_summon_to_level_160",
        "command": "summon_to_level",
        "args": [
            AreaObjects.NPC_0,
            Rooms._039_BOOSTER_TOWER_5F_KNIFE_GUYS_JUGGLING_ROOM,
        ],
    },
    {
        "identifier": "EVENT_1926_summon_to_level_161",
        "command": "summon_to_level",
        "args": [
            AreaObjects.NPC_1,
            Rooms._039_BOOSTER_TOWER_5F_KNIFE_GUYS_JUGGLING_ROOM,
        ],
    },
    {
        "identifier": "EVENT_1926_summon_to_level_162",
        "command": "summon_to_level",
        "args": [
            AreaObjects.NPC_2,
            Rooms._039_BOOSTER_TOWER_5F_KNIFE_GUYS_JUGGLING_ROOM,
        ],
    },
    {
        "identifier": "EVENT_1926_remove_from_level_163",
        "command": "remove_from_level",
        "args": [
            AreaObjects.NPC_3,
            Rooms._039_BOOSTER_TOWER_5F_KNIFE_GUYS_JUGGLING_ROOM,
        ],
    },
    {
        "identifier": "EVENT_1926_remove_from_level_164",
        "command": "remove_from_level",
        "args": [
            AreaObjects.NPC_4,
            Rooms._039_BOOSTER_TOWER_5F_KNIFE_GUYS_JUGGLING_ROOM,
        ],
    },
    {
        "identifier": "EVENT_1926_remove_from_level_165",
        "command": "remove_from_level",
        "args": [
            AreaObjects.NPC_5,
            Rooms._039_BOOSTER_TOWER_5F_KNIFE_GUYS_JUGGLING_ROOM,
        ],
    },
    {
        "identifier": "EVENT_1926_remove_from_level_166",
        "command": "remove_from_level",
        "args": [
            AreaObjects.NPC_6,
            Rooms._039_BOOSTER_TOWER_5F_KNIFE_GUYS_JUGGLING_ROOM,
        ],
    },
    {"identifier": "EVENT_1926_set_bit_51", "command": "set_bit", "args": [0x7048, 6]},
    {"identifier": "EVENT_1926_set_bit_53", "command": "set_bit", "args": [0x7089, 2]},
    {
        "identifier": "EVENT_1926_enter_area_54",
        "command": "enter_area",
        "args": [
            Rooms._202_BOOSTER_TOWER_ENTRANCE,
            RadialDirections.SOUTHWEST,
            5,
            114,
            15,
            [],
        ],
    },
    {"identifier": "EVENT_1926_restore_all_hp_58", "command": "restore_all_hp"},
    {"identifier": "EVENT_1926_restore_all_fp_59", "command": "restore_all_fp"},
    {"identifier": "EVENT_1926_set_bit_4", "command": "set_bit", "args": [0x708B, 5]},
    {
        "identifier": "EVENT_1926_run_event_as_subroutine_57_",
        "command": "run_event_as_subroutine",
        "args": [205],
    },
    {"identifier": "EVENT_1926_set_bit_40_", "command": "set_bit", "args": [0x7077, 5]},
    {
        "identifier": "EVENT_1926_fade_out_to_black_async_44_",
        "command": "jmp_to_event",
        "args": [1328],
    },
    {"identifier": "EVENT_1926_ret_61", "command": "ret"},
    # shortcut
    {
        "identifier": "EVENT_1926_jmp_if_bit_clear_73",
        "command": "jmp_if_bit_clear",
        "args": [0x704C, 6, "EVENT_1926_balcony_empty"],
    },
    {"identifier": "EVENT_1926_jmp_74", "command": "jmp_to_event", "args": [1282]},
    {
        "identifier": "EVENT_1926_balcony_empty",
        "command": "jmp_to_event",
        "args": [1283],
    },
]
