from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=27,
        y=30,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R017_MUSHROOM_KINGDOM_CASTLE_MAIN_HALL,
        show_message = False,
        dst_x = 4,
        dst_y = 23,
        dst_z = 2,
        dst_z_half = False,
    dst_f = SOUTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=26,
        y=19,
        z=3,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=2,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R032_MUSHROOM_KINGDOM_CASTLE_ENTRANCE_TO_TOADSTOOLS_ROOM,
        show_message = False,
        dst_x = 11,
        dst_y = 98,
        dst_z = 1,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
