from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    BattlePackNPC(
        occupant=Shyster,
        initiator=EventInitiator.ANYTHING_EXCEPT_PRESS_A,
        after_battle=PostBattleBehaviour.REMOVE_PERMANENTLY,
        battle_pack=PACK0010_REGULAR_SHYSTERS_BIASED_2,
        action_script=A0115_MK_THRONE_ANTECHAMBER_HENCHMAN,
        speed=0,
        visible=True,
        x=27,
        y=94,
        z=0,
        z_half=False,
        direction=SOUTHWEST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=True,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=False,
        byte3_bit7=False,
        slidable_along_walls=False,
        cant_move_if_in_air=False,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False,
    ),
    # NPC_1
    BattlePackClone(
        occupant=Shyster,
        battle_pack=PACK0011_REGULAR_SHYSTERS_BIASED_3,
        action_script=A0116_MK_THRONE_ANTECHAMBER_HENCHMAN,
        visible=True,
        x=28,
        y=97,
        z=0,
        z_half=False,
        direction=SOUTHWEST,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False,
    ),
]
