from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=27,
        y=34,
        z=5,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R131_SEA_AREA_04_BUNCH_OF_ZEOSTARS,
        show_message = False,
        dst_x = 2,
        dst_y = 66,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=25,
        y=36,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R136_SEA_AREA_07_SMALL_UNDERWATER_ROOM,
        show_message = False,
        dst_x = 26,
        dst_y = 123,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=17,
        y=50,
        z=5,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R174_SEA_AREA_08_SHORE_WITH_SUNKEN_SHIP,
        show_message = False,
        dst_x = 12,
        dst_y = 29,
        dst_z = 6,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
]
