from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E3618_NIMBUS_EXTERIOR_OPEN_INN_DOOR,
        x=4,
        y=47,
        z=2,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E3619_NIMBUS_EXTERIOR_OPEN_SHOP_DOOR,
        x=11,
        y=47,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E3622_NIMBUS_EXTERIOR_OPEN_NORTHEAST_HOUSE_DOOR,
        x=12,
        y=27,
        z=2,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E3621_NIMBUS_EXTERIOR_OPEN_SOUTH_HOUSE_DOOR,
        x=15,
        y=65,
        z=2,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E3620_NIMBUS_EXTERIOR_OPEN_GARROS_DOOR,
        x=25,
        y=49,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E3645_NIMBUS_EXTERIOR_EXIT_TO_VINES,
        x=12,
        y=58,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=3,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E3645_NIMBUS_EXTERIOR_EXIT_TO_VINES,
        x=11,
        y=59,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=3,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0740_NIMBUS_LAND_OCCUPIED_CASTLE_FRONT_ENTRANCE,
        x=20,
        y=36,
        z=2,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
]
