from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=7,
        y=25,
        z=3,
        f=EdgeDirection.SOUTHEAST,
        length=4,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R368_NIMBUS_LAND_ROYAL_BUS_STATION,
        show_message = False,
        dst_x = 4,
        dst_y = 43,
        dst_z = 1,
        dst_z_half = False,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=13,
        y=26,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R341_NIMBUS_LAND_GARROS_HOUSE,
        show_message = True,
        dst_x = 2,
        dst_y = 24,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=16,
        y=64,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R342_NIMBUS_LAND_LOWER_HOUSE,
        show_message = False,
        dst_x = 2,
        dst_y = 56,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=5,
        y=46,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R343_NIMBUS_LAND_INN,
        show_message = False,
        dst_x = 2,
        dst_y = 92,
        dst_z = 2,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=11,
        y=46,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R344_NIMBUS_LAND_ITEM_SHOP,
        show_message = False,
        dst_x = 17,
        dst_y = 24,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=25,
        y=48,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R345_NIMBUS_LAND_TOPRIGHT_HOUSE_CROCO_DROPS_SIGNAL_RING,
        show_message = False,
        dst_x = 17,
        dst_y = 56,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
]
