from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E1797_LANDS_END_SKY_BRIDGE_ROOM_EXIT_TO_DESERT,
        x=10,
        y=75,
        z=9,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1869_SKY_BRIDGE_LOADER,
        x=20,
        y=103,
        z=9,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1869_SKY_BRIDGE_LOADER,
        x=8,
        y=78,
        z=9,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1869_SKY_BRIDGE_LOADER,
        x=10,
        y=82,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = True,
    ),
]
