# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py graphicsdisassembler --rom ROM
from randomizer.data.palettes import CompleteSprite, AnimationPack, AnimationPackProperties, AnimationSequence, AnimationSequenceFrame, Mold, Tile, Clone
sprite = CompleteSprite(
    animation=AnimationPack(64, length=224, unknown=0x0002,
        properties=AnimationPackProperties(vram_size=2048,
            molds=[
                Mold(0, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(1, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(2, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(3, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(4, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(5, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(6, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(7, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(8, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(9, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(10, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(11, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(12, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(13, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(14, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(15, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(16, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(17, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(18, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(19, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(20, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(21, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(22, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(23, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(24, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(25, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(26, gridplane=False,
                    tiles=[
                    ]
                ),
                Mold(27, gridplane=False,
                    tiles=[
                    ]
                ),
            ],
            sequences=[
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=0),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=1),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=2),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=3),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=4),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=5),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=6),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=7),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=8),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=9),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=10),
                        AnimationSequenceFrame(duration=8, mold_id=11),
                        AnimationSequenceFrame(duration=8, mold_id=10),
                        AnimationSequenceFrame(duration=8, mold_id=12),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=13),
                        AnimationSequenceFrame(duration=8, mold_id=14),
                        AnimationSequenceFrame(duration=8, mold_id=13),
                        AnimationSequenceFrame(duration=8, mold_id=15),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=16),
                        AnimationSequenceFrame(duration=8, mold_id=17),
                        AnimationSequenceFrame(duration=8, mold_id=16),
                        AnimationSequenceFrame(duration=8, mold_id=18),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=19),
                        AnimationSequenceFrame(duration=8, mold_id=20),
                        AnimationSequenceFrame(duration=8, mold_id=19),
                        AnimationSequenceFrame(duration=8, mold_id=21),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=22),
                        AnimationSequenceFrame(duration=8, mold_id=23),
                        AnimationSequenceFrame(duration=8, mold_id=22),
                        AnimationSequenceFrame(duration=8, mold_id=24),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=2, mold_id=1),
                        AnimationSequenceFrame(duration=2, mold_id=9),
                        AnimationSequenceFrame(duration=2, mold_id=7),
                        AnimationSequenceFrame(duration=2, mold_id=8),
                        AnimationSequenceFrame(duration=2, mold_id=5),
                        AnimationSequenceFrame(duration=2, mold_id=26),
                        AnimationSequenceFrame(duration=2, mold_id=25),
                        AnimationSequenceFrame(duration=2, mold_id=27),
                    ]
                ),
            ]
        )
    ),
    palette_id=664,
    palette_offset=0,
    unknown_num=0
)
