# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py graphicsdisassembler --rom ROM
from randomizer.data.palettes import CompleteSprite, AnimationPack, AnimationPackProperties, AnimationSequence, AnimationSequenceFrame, Mold, Tile, Clone
sprite = CompleteSprite(
    animation=AnimationPack(370, length=31, unknown=0x0000,
        properties=AnimationPackProperties(vram_size=2048,
            molds=[
                Mold(0, gridplane=False,
                    tiles=[
                        Tile(mirror=False, invert=False, format=0, length=7, subtile_bytes=[
                            bytearray(b'\xfe\xfa\x02\x12\xf5\xee\xfa\x02\x12\xf9\xe8\xfa\x02\x12\xf9\xe5\xfa\x02\x12\x08\xee\xfa\x02\x12\x0c\xe8\xfa\x02\x12\x08\xe1\xfa'),
                            bytearray(b'J"@]\x00\x12\xfb\xf6\xfa\x02\x12\xf8\xfc}\x01"\xfb\x00\x1b\n"\xf8\xfe\x8d\x01"\xfa\xfc(\x01\x12\xf8'),
                            bytearray(b'\x00\x01\xfa\x02\x12\x02\xdc\xfa\x02\x12\xf5\x02\xfa\x02\x12\xf3\xe2\xfa\x02\x12\xfc\xdd\xfa\x02\x12\x00\xf2\xfa\x02\xf0\xf7\xea'),
                            bytearray(b'\x02\x12\t\xe7\xfa\x02\x12\x07\xe0\xfa\x02\x12\x13\xea\xfa\x02\x12\x04\xf7\xfa\x02\x12\x06\xfe\xfa\x02\x12\x11\xf6\xfa\x02\x12'),
                        ], is_16bit=False, y_plus=0, y_minus=0, x=120, y=120),
                    ]
                ),
            ],
            sequences=[
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=16, mold_id=0),
                    ]
                ),
            ]
        )
    ),
    palette_id=364,
    palette_offset=0,
    unknown_num=0
)
