# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py graphicsdisassembler --rom ROM
from randomizer.data.palettes import CompleteSprite, AnimationPack, AnimationPackProperties, AnimationSequence, AnimationSequenceFrame, Mold, Tile, Clone
sprite = CompleteSprite(
    animation=AnimationPack(249, length=184, unknown=0x0000,
        properties=AnimationPackProperties(vram_size=2048,
            molds=[
                Mold(0, gridplane=True,
                    tiles=[
                        Tile(mirror=False, invert=False, format=1, length=13, subtile_bytes=[
                            bytearray(b'\x00\x00\x00\x00\x01\x00\x03\x02\x07\x05\x05\x07\x05\x06\x167\x00\x00\x00\x00\x01\x01\x00\x00\x02\x07\n\x07\x1b\x07I7'),
                            bytearray(b'\x00\x00 \x00\xf0\x08\xfa\x0e\xe9\xff9\xcf\xd0\x1f\xe0\xbf\x00\x00  \x10\x18\x10\x16\x18\xf70\xff\xe0\xef\xc0_'),
                            bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x00\x00\x80'),
                            bytearray(b'\x08\x0b\x1e\x0f\x14\x07\x1a\x03\x19\x01\x04\x00\x00\x00\x04\x044\x0b\x10\x0f\x18\x07<\x03>\x01?\x00\x7f\x00{\x04'),
                            bytearray(b'\xc0\xff\x00\xff\x01\xff\x03\xff\x07\xff\xff\xffx\x7f@\x7f\x00\xe7\x00\xc3\x00\x83\x00\x8f\x00\xff\x00\xff\x80\x7f\x80\x7f'),
                            bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x80\x80\x80\x80\xc0\xc0\xc0\xc0\x80\x00\x00\x00\x80\x00\x80\x00\x00\x80\x00\x80@\x80@\xa0'),
                            bytearray(b'\x03\x03C\x03C\x03c\x031\x01\x1d\x01\x0e\x00\x0f\x00|\x03|\x03|\x03|\x03>\x01\x1e\x01\x0f\x00\x0f\x00'),
                            bytearray(b'\xc0\xff\x80\xff\x80\xff\x80\xff\xe0\xff\xf8\xff\x7f\x7f\x86\x06\x00\xf0\x00\xe0\x00\xe0\x00\xe0\x00\xf1\x00\xff\x80\x7f\xf9\x06'),
                            bytearray(b'@\xc0@\xc0\x00\xc0 \xc0p\xc0\xf8\xc0\xb8\x808`@\xa0@\xa0\x00\xc0 \xe00\xf0\x08\xc8h\xa8\xf8\x18'),
                            bytearray(b'\x0f\x00\x0f\x07\x0f\x07\x0f\x0c\x0f\x08\x07\x04\x03\x03\x00\x00\x0f\x00\x0f\x07\x0f\x07\x0f\x0c\x0f\x08\x07\x04\x03\x03\x00\x00'),
                            bytearray(b'\xe0\x00\xfe\xc0\xf3\xc3\xe7\x07\x97\x07\x17\x07\x97\x87\x7f\x7f\xff\x00\xfe\xc1\xf3\xcc\xe7\x18\x97h\x17\xe8\x97\xe8\x7f\x7f'),
                            bytearray(b'\x80\xe0\x10\xf0\xf0\xf0``hh\x90\x10\xe0\xe0\x00\x00\xe0\x18\xf0\x08\xf0\x08`\x98h\x98\x90p\xe0\xe0\x00\x00'),
                        ], is_16bit=False, y_plus=0, y_minus=0, x=0, y=0),
                    ]
                ),
            ],
            sequences=[
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=3),
                        AnimationSequenceFrame(duration=8, mold_id=4),
                        AnimationSequenceFrame(duration=8, mold_id=3),
                        AnimationSequenceFrame(duration=8, mold_id=5),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=0),
                        AnimationSequenceFrame(duration=8, mold_id=1),
                        AnimationSequenceFrame(duration=8, mold_id=0),
                        AnimationSequenceFrame(duration=8, mold_id=2),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=6),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=2, mold_id=7),
                        AnimationSequenceFrame(duration=2, mold_id=8),
                        AnimationSequenceFrame(duration=6, mold_id=9),
                        AnimationSequenceFrame(duration=2, mold_id=8),
                        AnimationSequenceFrame(duration=2, mold_id=7),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=15),
                        AnimationSequenceFrame(duration=4, mold_id=14),
                        AnimationSequenceFrame(duration=4, mold_id=11),
                        AnimationSequenceFrame(duration=8, mold_id=12),
                        AnimationSequenceFrame(duration=4, mold_id=11),
                        AnimationSequenceFrame(duration=4, mold_id=10),
                        AnimationSequenceFrame(duration=4, mold_id=13),
                        AnimationSequenceFrame(duration=8, mold_id=14),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=2, mold_id=15),
                        AnimationSequenceFrame(duration=2, mold_id=16),
                        AnimationSequenceFrame(duration=6, mold_id=17),
                        AnimationSequenceFrame(duration=2, mold_id=16),
                        AnimationSequenceFrame(duration=2, mold_id=15),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=18),
                        AnimationSequenceFrame(duration=16, mold_id=19),
                        AnimationSequenceFrame(duration=16, mold_id=20),
                        AnimationSequenceFrame(duration=16, mold_id=19),
                        AnimationSequenceFrame(duration=16, mold_id=20),
                        AnimationSequenceFrame(duration=16, mold_id=19),
                        AnimationSequenceFrame(duration=16, mold_id=20),
                        AnimationSequenceFrame(duration=10, mold_id=21),
                        AnimationSequenceFrame(duration=32, mold_id=3),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=6, mold_id=22),
                        AnimationSequenceFrame(duration=8, mold_id=23),
                        AnimationSequenceFrame(duration=6, mold_id=22),
                        AnimationSequenceFrame(duration=6, mold_id=3),
                        AnimationSequenceFrame(duration=6, mold_id=18),
                        AnimationSequenceFrame(duration=8, mold_id=21),
                        AnimationSequenceFrame(duration=6, mold_id=18),
                        AnimationSequenceFrame(duration=6, mold_id=3),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=8, mold_id=24),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=2, mold_id=25),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=4, mold_id=6),
                        AnimationSequenceFrame(duration=4, mold_id=30),
                        AnimationSequenceFrame(duration=4, mold_id=3),
                        AnimationSequenceFrame(duration=4, mold_id=29),
                        AnimationSequenceFrame(duration=4, mold_id=0),
                        AnimationSequenceFrame(duration=4, mold_id=26),
                        AnimationSequenceFrame(duration=4, mold_id=27),
                        AnimationSequenceFrame(duration=8, mold_id=28),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=6, mold_id=18),
                        AnimationSequenceFrame(duration=6, mold_id=21),
                    ]
                ),
                AnimationSequence(
                    frames=[
                        AnimationSequenceFrame(duration=2, mold_id=31),
                    ]
                ),
            ]
        )
    ),
    palette_id=654,
    palette_offset=0,
    unknown_num=0
)
