
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
objects = [
    {
        "id": 0,
        "type": ObjectType.OBJECT,
        "initiator": Initiator.PRESS_A_FROM_ANY_SIDE,
        "model": 492,
        "event_script": 256,
        "action_script": 400,
        "speed": 0,
        "npc_id_offset": 0,
        "event_offset": 0,
        "action_offset": 0,
        "visible": True,
        "x": 6,
        "y": 18,
        "z": 0,
        "z_half": False,
        "direction": RadialDirection.SOUTHWEST,
        "face_on_trigger": True,
        "cant_enter_doors": False,
        "byte2_bit5": False,
        "set_sequence_playback": True,
        "cant_float": False,
        "cant_walk_up_stairs": False,
        "cant_walk_under": False,
        "cant_pass_walls": False,
        "cant_jump_through": False,
        "cant_pass_npcs": False,
        "byte3_bit5": False,
        "cant_walk_through": False,
        "byte3_bit7": False,
        "slidable_along_walls": False,
        "cant_move_if_in_air": False,
        "byte7_upper2": 0x03,
        "clones": []
    },
]
