from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=2,
        y=31,
        z=5,
        f=EdgeDirection.SOUTHEAST,
        length=3,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R472_FACTORY_GROUNDS_AREA_03,
        show_message = False,
        dst_x = 15,
        dst_y = 118,
        dst_z = 5,
        dst_z_half = False,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=15,
        y=57,
        z=5,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R406_FACTORY_GROUNDS_AREA_01_WITH_TOAD,
        show_message = False,
        dst_x = 4,
        dst_y = 32,
        dst_z = 5,
        dst_z_half = False,
    dst_f = SOUTHEAST,
        x_bit_7 = False,
    ),
]
