"""NPC list import"""

from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    RegularNPC(
        occupant=JumpTrampoline,
        initiator=EventInitiator.JUMP_ON,
        event_script=E3749_NIMBUS_MEZZANINE_TRAMPOLINE_TO_TOWN_SQUARE,
        action_script=A0015_DO_NOTHING,
        speed=0,
        visible=True,
        x=24,
        y=18,
        z=2,
        z_half=False,
        direction=SOUTHWEST,
        face_on_trigger=False,
        cant_enter_doors=True,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=True,
        cant_walk_up_stairs=False,
        cant_walk_under=True,
        cant_pass_walls=True,
        cant_jump_through=False,
        cant_pass_npcs=True,
        byte3_bit5=True,
        cant_walk_through=True,
        byte3_bit7=True,
        slidable_along_walls=False,
        cant_move_if_in_air=False,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=True,
    ),
    # NPC_1
    RegularNPC(
        occupant=WarpTrampoline,
        initiator=EventInitiator.JUMP_ON,
        event_script=E3760_NIMBUS_MEZZANINE_TRAMPOLINE_TO_WORLD_MAP,
        action_script=A0015_DO_NOTHING,
        speed=0,
        visible=True,
        x=28,
        y=27,
        z=2,
        z_half=False,
        direction=SOUTHWEST,
        face_on_trigger=False,
        cant_enter_doors=True,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=True,
        cant_walk_up_stairs=False,
        cant_walk_under=True,
        cant_pass_walls=True,
        cant_jump_through=False,
        cant_pass_npcs=True,
        byte3_bit5=True,
        cant_walk_through=True,
        byte3_bit7=True,
        slidable_along_walls=False,
        cant_move_if_in_air=False,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=True,
    ),
]
