from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E1360_CURTAIN_1,
        x=1,
        y=20,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1361_CURTAIN_2,
        x=2,
        y=18,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1362_CURTAIN_3,
        x=3,
        y=16,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1363_CURTAIN_4,
        x=4,
        y=14,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1364_CURTAIN_ROOM_EXIT_TO_BALCONY,
        x=2,
        y=26,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
]
