from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=22,
        y=26,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R263_LANDS_END_UNDERGROUND_AREA_01,
        show_message = False,
        dst_x = 10,
        dst_y = 92,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=30,
        y=10,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R265_LANDS_END_UNDERGROUND_AREA_03,
        show_message = False,
        dst_x = 15,
        dst_y = 109,
        dst_z = 4,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
