from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=1,
        y=46,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R139_LANDS_END_AREA_03_GECKITS_PLAYING_CANNONBALL,
        show_message = False,
        dst_x = 18,
        dst_y = 88,
        dst_z = 6,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=17,
        y=37,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R142_LANDS_END_AREA_05_SKY_BRIDGE,
        show_message = False,
        dst_x = 21,
        dst_y = 115,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=14,
        y=23,
        z=9,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R142_LANDS_END_AREA_05_SKY_BRIDGE,
        show_message = False,
        dst_x = 19,
        dst_y = 105,
        dst_z = 12,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
