# behaviour_27_0x350B2D

from randomizer.scripts.animation.script_imports import *

script = SubroutineOrBanklessScript(
    expected_size=83,
    script=[
        ResetTargetMappingMemory(),
        ResetObjectMappingMemory(),
        Db(bytearray(b"T")),
        Db(bytearray(b">")),
        ResetTargetMappingMemory(),
        MoveObject(
            speed=1,
            start_position=256,
            end_position=256,
            apply_to_x=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        MoveObject(
            speed=1,
            start_position=-129,
            end_position=-129,
            apply_to_y=True,
            should_set_end_position=True,
            should_set_speed=True,
        ),
        PauseScriptUntil(condition=FRAMES_ELAPSED, frames=8),
        ResetObjectMappingMemory(),
        ResetTargetMappingMemory(),
        SetAMEM40ToXYZCoords(
            origin=CASTER_INITIAL_POSITION,
            x=0,
            y=0,
            z=0,
            set_x=True,
            set_y=True,
            set_z=True,
        ),
        MoveSpriteToCoords(shift_type=SHIFT_TYPE_SHIFT, speed=256, arch_height=0),
        PauseScriptUntil(condition=SPRITE_SHIFT_COMPLETE),
        ResetObjectMappingMemory(),
        Db(bytearray(b"W")),
        Db(bytearray(b";")),
        Db(bytearray(b"U")),
        Db(bytearray(b";")),
        Db(bytearray(b"V")),
        JmpIfTargetEnabled(["command_0x350b75"]),
        PlaySound(sound=S0089_COMMON_MONSTER_EXPLOSION),
        Db(bytearray(b"\xa4")),
        SetAMEM8BitTo7E5x(0x60, 0x7E002C),
        ClearAMEM8Bit(0x61),
        ObjectQueueAtOffsetAndIndexAtAMEM60(target_address=0x350B80),
        RemoveObject(),
        SetAMEMToAMEM16Bit(dest_amem=0x6E, amem=0x62),
        Db(bytearray(b"\x98")),
        Db(bytearray(b"F"), identifier="command_0x350b75"),
        Db(bytearray(b"\x15")),
        Pause1Frame(),
        Db(bytearray(b"R\x80\x08v\x0b")),
        Jmp(["command_0x350b06"]),
    ],
)
