from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=24,
        y=16,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R413_NIMBUS_CASTLE_KINGS_LOCKED_CELLAR,
        show_message = False,
        dst_x = 29,
        dst_y = 55,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=30,
        y=11,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R122_NIMBUS_CASTLE_AREA_12_ENTRANCE_TO_THRONE_ROOM,
        show_message = False,
        dst_x = 1,
        dst_y = 125,
        dst_z = 1,
        dst_z_half = True,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
