# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectsequencedisassembler --rom ROM > openmode_sequence_debug.txt
from randomizer.data.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data.eventtables import RadialDirections, AreaObjects, NPCPackets, Sounds, Coords, CoordUnits, Rooms
script = [
    {
        "identifier": 'ACTION_159_reset_properties_0',
        "command": 'reset_properties'
    },
    {
        "identifier": 'ACTION_159_sequence_looping_off_1',
        "command": 'sequence_looping_off'
    },
    {
        "identifier": 'ACTION_159_sequence_playback_off_2',
        "command": 'sequence_playback_off'
    },
    {
        "identifier": 'ACTION_159_ret_3',
        "command": 'ret'
    }
]
