from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    ChestNPC(
        occupant=TreasureChest,
        initiator=EventInitiator.HIT_FROM_BELOW,
        event_script=E0172_CHEST_1_CONTAINER,
        action_script=A0014_FLOATING_CHEST,
        lower_70A7=4,
        upper_70A7=10,
        speed=0,
        visible=True,
        x=29,
        y=67,
        z=3,
        z_half=False,
        direction=SOUTHWEST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=False,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=True,
        cant_move_if_in_air=False,
        byte7_upper2=True,
        priority_0=True,
        priority_1=True,
        priority_2=False,
        show_shadow=False,
        cannot_clone=False,
    ),
]
