from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E2432_FOREST_MAZE_TRANSITION,
        x=9,
        y=44,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=3,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2433_FOREST_MAZE_TRANSITION,
        x=3,
        y=46,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=3,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2434_FOREST_MAZE_TRANSITION,
        x=9,
        y=64,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=3,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2435_FOREST_MAZE_TRANSITION,
        x=3,
        y=62,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=3,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
]
