from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E2349_TOWER_SPOOKUM_JUMPS_OUT,
        x=14,
        y=39,
        z=5,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2349_TOWER_SPOOKUM_JUMPS_OUT,
        x=11,
        y=45,
        z=8,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2352_TOWER_START_BULLET_BILLS,
        x=10,
        y=44,
        z=10,
        f=EdgeDirection.SOUTHEAST,
        length=6,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2352_TOWER_START_BULLET_BILLS,
        x=10,
        y=45,
        z=10,
        f=EdgeDirection.SOUTHEAST,
        length=6,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2352_TOWER_START_BULLET_BILLS,
        x=11,
        y=45,
        z=8,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2352_TOWER_START_BULLET_BILLS,
        x=15,
        y=42,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
]
