"""NPC list import"""

from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    RegularNPC(
        occupant=Empty,
        initiator=EventInitiator.NONE,
        event_script=E0256_RETURN,
        action_script=A0015_DO_NOTHING,
        speed=0,
        visible=False,
        x=0,
        y=0,
        z=0,
        z_half=False,
        direction=SOUTHWEST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=False,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=False,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=False,
        byte3_bit7=False,
        slidable_along_walls=True,
        cant_move_if_in_air=True,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=False,
        cannot_clone=False),
    # NPC_1
    BattlePackNPC(
        occupant=Magmus,
        initiator=EventInitiator.ANYTHING_EXCEPT_PRESS_A,
        after_battle=PostBattleBehaviour.REMOVE_PERMANENTLY,
        battle_pack=PACK0102_MAGMUS_WITH_ARMOREDANT_OERLIKON,
        action_script=A0727_MAGMITES,
        speed=0,
        visible=True,
        x=24,
        y=33,
        z=1,
        z_half=False,
        direction=NORTHEAST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=True,
        cant_walk_up_stairs=False,
        cant_walk_under=True,
        cant_pass_walls=True,
        cant_jump_through=False,
        cant_pass_npcs=True,
        byte3_bit5=True,
        cant_walk_through=True,
        byte3_bit7=True,
        slidable_along_walls=True,
        cant_move_if_in_air=True,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False),
    # NPC_2
    BattlePackClone(
        occupant=Magmus,
        battle_pack=PACK0102_MAGMUS_WITH_ARMOREDANT_OERLIKON,
        action_script=A0727_MAGMITES,
        visible=True,
        x=26,
        y=29,
        z=5,
        z_half=False,
        direction=SOUTHWEST,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False),
]
