# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py eventdisassembler --rom ROM > openmode_debug.txt
from randomizer.data.eventtables import ControllerDirections, RadialDirections, Rooms, Sounds, AreaObjects, NPCPackets, Locations, Shops, EventSequences, MenuTutorials, OverworldSequences, PlayableCharacters, EquipSlots, DialogDurations, IntroTitles, Colours, PaletteSetTypes, Music, MusicDirections, MusicPitch, Coords, CoordUnits, Tutorials, _0x40Flags, _0x60Flags, _0x62Flags, _0x63Flags, _0x68Flags, _0x6AFlags, _0x6BFlags, _0x81Flags, _0x84Flags
from randomizer.data.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.data import items
script = [
    # tower's already been opened
    {
        "identifier": 'EVENT_1331_jmp_if_bit_set_0',
        "command": 'jmp_if_bit_set',
        "args": [0x7053, 6, 'EVENT_1331_ret']
    },

    # don't have the right character yet
    {
        "identifier": 'EVENT_1331_jmp_if_bit_set_0_',
        "command": 'jmp_if_bit_clear',
        "args": [0x7053, 7, 'EVENT_1331_ret']
    },

    # do have the right character
    {
        "identifier": 'EVENT_1331_remove_from_current_level_3_',
        "command": 'remove_from_current_level',
        "args": [AreaObjects.NPC_1]
    },

    {
        "identifier": 'EVENT_1331_action_queue_async_11',
        "command": 'action_queue_async',
        "args": [AreaObjects.MARIO],
        "subscript": [
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_set_animation_speed_0',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_10_SUBSCRIPT_walk_to_xy_coords_6__',
                "command": 'walk_to_xy_coords',
                "args": [5, 115]
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_set_animation_speed_1',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.VERY_FAST, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_pause_3',
                "command": 'pause',
                "args": [15]
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_face_southwest_4',
                "command": 'face_southwest'
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_pause_5',
                "command": 'pause',
                "args": [15]
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_set_animation_speed_6_',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.SLOW, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_sequence_looping_on_7',
                "command": 'sequence_looping_on'
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_pause_8',
                "command": 'pause',
                "args": [15]
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_set_animation_speed_9',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_pause_10',
                "command": 'pause',
                "args": [15]
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_set_animation_speed_11',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.FAST, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_pause_12',
                "command": 'pause',
                "args": [15]
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_set_animation_speed_13',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.VERY_FAST, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_pause_14',
                "command": 'pause',
                "args": [45]
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_set_animation_speed_15',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.VERY_FAST, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_fixed_f_coord_on_16',
                "command": 'fixed_f_coord_on'
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_11_SUBSCRIPT_shift_northeast_steps_17',
                "command": 'shift_northeast_steps',
                "args": [2]
            }
        ]
    },
    {
        "identifier": 'EVENT_1331_action_queue_sync_12',
        "command": 'action_queue_sync',
        "args": [AreaObjects.MARIO],
        "subscript": [
            {
                "identifier": 'EVENT_1331_action_queue_sync_12_SUBSCRIPT_sequence_looping_off_0_',
                "command": 'sequence_looping_off'
            },
            {
                "identifier": 'EVENT_1331_action_queue_sync_12_SUBSCRIPT_sequence_playback_off_1_',
                "command": 'sequence_playback_off'
            },
            {
                "identifier": 'EVENT_1331_action_queue_sync_12_SUBSCRIPT_set_animation_speed_2',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.VERY_FAST, [_0x10Flags.WALKING]]
            },
            {
                "identifier": 'EVENT_1331_action_queue_sync_12_SUBSCRIPT_shift_northeast_pixels_3',
                "command": 'shift_northeast_pixels',
                "args": [18]
            },
            {
                "identifier": 'EVENT_1331_action_queue_sync_12_SUBSCRIPT_shift_southwest_pixels_4',
                "command": 'shift_southwest_pixels',
                "args": [12]
            },
            {
                "identifier": 'EVENT_1331_action_queue_sync_12_SUBSCRIPT_shift_northeast_pixels_5',
                "command": 'shift_northeast_pixels',
                "args": [8]
            },
            {
                "identifier": 'EVENT_1331_action_queue_sync_12_SUBSCRIPT_shift_southwest_pixels_6',
                "command": 'shift_southwest_pixels',
                "args": [6]
            },
            {
                "identifier": 'EVENT_1331_action_queue_sync_12_SUBSCRIPT_shift_northeast_pixels_7',
                "command": 'shift_northeast_pixels',
                "args": [4]
            },
            {
                "identifier": 'EVENT_1331_action_queue_sync_12_SUBSCRIPT_shift_southwest_pixels_8',
                "command": 'shift_southwest_pixels',
                "args": [4]
            },
        ]
    },
    {
        "identifier": 'EVENT_1331_pause_13',
        "command": 'pause',
        "args": [5]
    },
    {
        "identifier": 'EVENT_1331_apply_solidity_mod_14',
        "command": 'apply_solidity_mod',
        "args": [Rooms._202_BOOSTER_TOWER_ENTRANCE, 0, [_0x6BFlags.PERMANENT]]
    },
    {
        "identifier": 'EVENT_1331_apply_tile_mod_15',
        "command": 'apply_tile_mod',
        "args": [Rooms._202_BOOSTER_TOWER_ENTRANCE, 32, [_0x6AFlags.USE_ALTERNATE]]
    },
    {
        "identifier": 'EVENT_1331_play_sound_16',
        "command": 'play_sound',
        "args": [Sounds._021_RUMBLING, 6]
    },
    {
        "identifier": 'EVENT_1331_remove_from_current_level_17',
        "command": 'remove_from_current_level',
        "args": [AreaObjects.NPC_2]
    },
    {
        "identifier": 'EVENT_1331_remove_from_level_18',
        "command": 'remove_from_level',
        "args": [AreaObjects.NPC_2, Rooms._202_BOOSTER_TOWER_ENTRANCE]
    },
    {
        "identifier": 'EVENT_1331_pause_something',
        "command": 'pause',
        "args": [60]
    },


    {
        "identifier": 'EVENT_1331_action_queue_async_133',
        "command": 'action_queue_async',
        "args": [AreaObjects.MARIO],
        "subscript": [
            {
                "identifier": 'EVENT_3797_action_queue_async_133_SUBSCRIPT_set_animation_speed_0',
                "command": 'set_animation_speed',
                "args": [SequenceSpeeds.NORMAL, [_0x10Flags.SEQUENCE]]
            },
            {
                "identifier": 'EVENT_3797_action_queue_async_133_SUBSCRIPT_set_sprite_sequence_1',
                "command": 'set_sprite_sequence',
                "args": [10, 2, [_0x08Flags.LOOPING_OFF, _0x08Flags.READ_AS_SEQUENCE]]
            },
            {
                "identifier": 'pause_132',
                "command": 'pause',
                "args": [60]
            },
            {
                "identifier": 'EVENT_2496_____action_queue_async_250_SUBSCRIPT_reset_properties_0',
                "command": 'reset_properties'
            },
            {
                "identifier": 'EVENT_1331_action_queue_async_10_SUBSCRIPT_walk_to_xy_coords_6___',
                "command": 'face_northeast',
            },
        ]
    },

    {
        "identifier": 'EVENT_1331_set_bit',
        "command": 'set_bit',
        "args": [0x7053, 6]
    },
    {
        "identifier": 'EVENT_1331_ret',
        "command": 'ret'
    }
]
