from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E2449_FOREST_TRUNK_ROOM_RIGHTMOST_TRUNK,
        x=16,
        y=92,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2450_FOREST_TRUNK_ROOM_LOWEST_TRUNK,
        x=13,
        y=98,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2451_FOREST_TRUNK_ROOM_MIDDLE_RIGHT_TRUNK,
        x=12,
        y=86,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2452_FOREST_TRUNK_ROOM_MIDDLE_LEFT_TRUNK,
        x=9,
        y=92,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2453_FOREST_TRUNK_ROOM_UPPER_LEFT_TRUNK,
        x=9,
        y=78,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2454_FOREST_TRUNK_ROOM_UPPER_RIGHT_TRUNK,
        x=6,
        y=84,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2455_FOREST_TRUNK_ROOM_WIGGLER_TRUNK,
        x=4,
        y=74,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
]
