# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectdisassembler --rom ROM
from randomizer.helpers.roomobjecttables import (
    ObjectType,
    Initiator,
    PostBattle,
    RadialDirection,
    Music,
    Edge,
    ExitType,
    Locations,
    Rooms,
    PartitionBufferTypes,
    PartitionMainSpace)
from randomizer.data.rooms.room import (
    Buffer,
    Partition,
    DestinationProps,
    RoomExit,
    MapExit,
    Event,
    BattlePackNPC,
    RegularNPC,
    ChestNPC,
    BattlePackClone,
    RegularClone,
    ChestClone,
    Room)
from randomizer.data.npcs import npcs
from randomizer.helpers.npcmodeltables import SpriteName, VramStore, ShadowSize
from randomizer.helpers.misc_helpers import ExtraSpriteActions

room = Room(
    partition=Partition(
        ally_sprite_buffer_size=1,
        allow_extra_sprite_buffer=True,
        extra_sprite_buffer_size=1,
        buffers=[
            Buffer(
                buffer_type=PartitionBufferTypes.TREASURE_CHEST,
                main_buffer_space=PartitionMainSpace._0_BYTES,
                index_in_main_buffer=True),
            Buffer(
                buffer_type=PartitionBufferTypes.EMPTY_3,
                main_buffer_space=PartitionMainSpace._0_BYTES,
                index_in_main_buffer=True),
            Buffer(
                buffer_type=PartitionBufferTypes.EMPTY_3,
                main_buffer_space=PartitionMainSpace._0_BYTES,
                index_in_main_buffer=True),
        ],
        full_palette_buffer=True),
    music=Music._66_BOWSERS_CASTLE_2ND_TIME,
    entrance_event=15,
    event_tiles=[
        Event(
            event=3361,
            x=21,
            y=79,
            z=0,
            f=Edge.SOUTHEAST,
            height=6,
            length=2,
            nw_se_edge_active=True,
            ne_sw_edge_active=False,
            byte_8_bit_4=False),
    ],
    objects=[
        ChestNPC(  # 0
            occupant=npcs.TreasureChest,
            initiator=Initiator.HIT_FROM_BELOW,
            event_script=3348,
            action_script=14,
            lower_70a7=0,
            upper_70a7=0,
            visible=True,
            x=18,
            y=76,
            z=3,
            z_half=True,
            direction=RadialDirection.SOUTHWEST,
            face_on_trigger=False,
            cant_enter_doors=False,
            byte2_bit5=False,
            set_sequence_playback=True,
            cant_float=False,
            cant_walk_up_stairs=False,
            cant_walk_under=False,
            cant_pass_walls=False,
            cant_jump_through=False,
            cant_pass_npcs=True,
            byte3_bit5=False,
            cant_walk_through=True,
            byte3_bit7=False,
            slidable_along_walls=False,
            cant_move_if_in_air=True,
            byte7_upper2=3,
            priority_0=True,
            priority_1=True,
            priority_2=False,
            cannot_clone=False),
    ])
