
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
from randomizer.data.rooms.room import Buffer, Partition, DestinationProps, RoomExit, MapExit, Event, BattlePackNPC, RegularNPC, ChestNPC, BattlePackClone, RegularClone, ChestClone, Room
from randomizer.data.npcs import npcs
from randomizer.helpers.npcmodeltables import SpriteName, VramStore, ShadowSize
from randomizer.helpers.misc_helpers import ExtraSpriteActions
room = Room(
    partition=Partition(
        ally_sprite_buffer_size=1,
        allow_extra_sprite_buffer=False,
        extra_sprite_buffer_size=0,
        buffers = [
            Buffer(
                buffer_type=PartitionBufferTypes._3_SPRITES_PER_ROW,
                main_buffer_space=PartitionMainSpace._0_BYTES,
                index_in_main_buffer=True
            ),
            Buffer(
                buffer_type=PartitionBufferTypes._3_SPRITES_PER_ROW,
                main_buffer_space=PartitionMainSpace._0_BYTES,
                index_in_main_buffer=True
            ),
            Buffer(
                buffer_type=PartitionBufferTypes._3_SPRITES_PER_ROW,
                main_buffer_space=PartitionMainSpace._0_BYTES,
                index_in_main_buffer=True
            )
        ],
        full_palette_buffer=True
    ),
    music=Music._41_SUNKEN_SHIP,
    entrance_event=3921,
    exit_fields=[
        RoomExit(
            x=9,
            y=19,
            z=0,
            f=Edge.SOUTHWEST,
            length=2,
            height=0,
            nw_se_edge_active=True,
            ne_sw_edge_active=False,
            byte_2_bit_2=False,
            destination=Rooms._160_SUNKEN_SHIP_AREA_01,
            show_message=False,
            dst_x=6,
            dst_y=15,
            dst_z=0,
            dst_z_half=0,
            dst_f=RadialDirection.SOUTHWEST,
            x_bit_7=False),
    ],
    objects=[
        RegularNPC( # 0
            occupant=npcs.SavePoint,
            initiator=Initiator.JUMP_ON,
            event_script=80,
            action_script=120,
            visible=True,
            x=13,
            y=13,
            z=0,
            z_half=True,
            direction=RadialDirection.SOUTHWEST,
            face_on_trigger=False,
            cant_enter_doors=False,
            byte2_bit5=False,
            set_sequence_playback=True,
            cant_float=False,
            cant_walk_up_stairs=False,
            cant_walk_under=False,
            cant_pass_walls=False,
            cant_jump_through=False,
            cant_pass_npcs=True,
            byte3_bit5=True,
            cant_walk_through=True,
            byte3_bit7=True,
            slidable_along_walls=False,
            cant_move_if_in_air=True,
            byte7_upper2=3,
            priority_0=True,
            priority_1=True,
            priority_2=False,
            show_shadow=False,
            cannot_clone=False),
        RegularNPC( # 1
            occupant=npcs.Letter,
            initiator=Initiator.PRESS_A_FROM_FRONT,
            event_script=3303,
            action_script=919,
            visible=True,
            x=12,
            y=10,
            z=1,
            z_half=False,
            direction=RadialDirection.SOUTHEAST,
            face_on_trigger=False,
            cant_enter_doors=False,
            byte2_bit5=False,
            set_sequence_playback=False,
            cant_float=False,
            cant_walk_up_stairs=False,
            cant_walk_under=False,
            cant_pass_walls=False,
            cant_jump_through=False,
            cant_pass_npcs=True,
            byte3_bit5=False,
            cant_walk_through=True,
            byte3_bit7=False,
            slidable_along_walls=True,
            cant_move_if_in_air=True,
            byte7_upper2=3,
            priority_0=False,
            priority_1=False,
            priority_2=True,
            cannot_clone=True),
    ]
)
