
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
from randomizer.data.rooms.room import Buffer, Partition, DestinationProps, RoomExit, MapExit, Event, BattlePackNPC, RegularNPC, ChestNPC, BattlePackClone, RegularClone, ChestClone, Room
from randomizer.data.npcs import npcs
from randomizer.helpers.npcmodeltables import SpriteName, VramStore, ShadowSize
from randomizer.helpers.misc_helpers import ExtraSpriteActions
room = Room(
    partition=Partition(
        ally_sprite_buffer_size=1,
        allow_extra_sprite_buffer=False,
        extra_sprite_buffer_size=0,
        buffers = [
            Buffer(
                buffer_type=PartitionBufferTypes._4_SPRITES_PER_ROW,
                main_buffer_space=PartitionMainSpace._0_BYTES,
                index_in_main_buffer=True
            ),
            Buffer(
                buffer_type=PartitionBufferTypes.EMPTY_3,
                main_buffer_space=PartitionMainSpace._0_BYTES,
                index_in_main_buffer=True
            ),
            Buffer(
                buffer_type=PartitionBufferTypes.EMPTY_3,
                main_buffer_space=PartitionMainSpace._0_BYTES,
                index_in_main_buffer=True
            )
        ],
        full_palette_buffer=True
    ),
    music=Music._02_MUSHROOM_KINGDOM,
    entrance_event=257,
    event_tiles=[
        Event(
            event=349,
            x=29,
            y=91,
            z=0,
            f=Edge.SOUTHWEST,
            height=0,
            length=2,
            nw_se_edge_active=True,
            ne_sw_edge_active=False,
            byte_8_bit_4=False),
    ],
    exit_fields=[
        RoomExit(
            x=26,
            y=98,
            z=0,
            f=Edge.SOUTHWEST,
            length=2,
            height=0,
            nw_se_edge_active=True,
            ne_sw_edge_active=False,
            byte_2_bit_2=False,
            destination=Rooms._017_MUSHROOM_KINGDOM_CASTLE_MAIN_HALL,
            show_message=False,
            dst_x=9,
            dst_y=19,
            dst_z=2,
            dst_z_half=0,
            dst_f=RadialDirection.SOUTHWEST,
            x_bit_7=False),
    ],
    objects=[
        RegularNPC( # 0
            occupant=npcs.RedSmallToad,
            initiator=Initiator.PRESS_A_FROM_ANY_SIDE,
            event_script=326,
            action_script=15,
            visible=True,
            x=28,
            y=92,
            z=0,
            z_half=False,
            direction=RadialDirection.SOUTHWEST,
            face_on_trigger=True,
            cant_enter_doors=True,
            byte2_bit5=False,
            set_sequence_playback=True,
            cant_float=True,
            cant_walk_up_stairs=False,
            cant_walk_under=False,
            cant_pass_walls=True,
            cant_jump_through=False,
            cant_pass_npcs=False,
            byte3_bit5=False,
            cant_walk_through=True,
            byte3_bit7=False,
            slidable_along_walls=False,
            cant_move_if_in_air=False,
            byte7_upper2=3,
            priority_0=False,
            priority_1=False,
            priority_2=True,
            cannot_clone=False),
        RegularClone( # 1
            occupant=npcs.RedSmallToad,
            event_script=326,
            action_script=15,
            visible=True,
            x=29,
            y=95,
            z=0,
            z_half=False,
            direction=RadialDirection.SOUTHWEST,
            priority_0=False,
            priority_1=False,
            priority_2=True,
            cannot_clone=False),
    ]
)
