"""NPC list import"""

from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    RegularNPC(
        occupant=Chancellor,
        initiator=EventInitiator.PRESS_A_FROM_ANY_SIDE,
        event_script=E0330_CHANCELLOR,
        action_script=A0138_CHANCELLOR,
        speed=0,
        visible=True,
        x=17,
        y=27,
        z=3,
        z_half=False,
        direction=SOUTHWEST,
        face_on_trigger=True,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=True,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=True,
        cant_jump_through=False,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=False,
        cant_move_if_in_air=False,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False,
    ),
    # NPC_1
    RegularNPC(
        occupant=RedSmallToad,
        initiator=EventInitiator.PRESS_A_FROM_ANY_SIDE,
        event_script=E0327_MUSHROOM_KINGDOM_CASTLE_THRONE_ROOM_TOAD,
        action_script=A0128_WALK_RANDOM_DIRECTIONS,
        speed=0,
        visible=True,
        x=15,
        y=29,
        z=2,
        z_half=False,
        direction=SOUTHEAST,
        face_on_trigger=True,
        cant_enter_doors=True,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=True,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=True,
        cant_jump_through=False,
        cant_pass_npcs=True,
        byte3_bit5=True,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=True,
        cant_move_if_in_air=True,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False,
    ),
]
