from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=16,
        y=118,
        z=4,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R262_LANDS_END_UNDERGROUND_AREA_04_BUY_SUPER_STARS,
        show_message = False,
        dst_x = 15,
        dst_y = 18,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=27,
        y=111,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R420_BELOME_TEMPLE_AREA_02_FORTUNE_ROOM,
        show_message = False,
        dst_x = 1,
        dst_y = 47,
        dst_z = 1,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
