#A0481_FACTORY_SWITCH_ROOM_AMEBOID

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	ShadowOff(),
	VisibilityOff(),
	Pause(128),
	VisibilityOn(),
	SetWalkingSpeed(SLOW),
	SequenceLoopingOn(),
	ShiftSouthwestSteps(6),
	ShiftSouthwestPixels(10),
	SetSpriteSequence(index=9, is_sequence=True, looping=True),
	FloatingOn(),
	JumpToHeight(0),
	ShadowOn(),
	Pause(24),
	SetWalkingSpeed(NORMAL),
	SetSpriteSequence(index=9, is_sequence=True, looping=True, mirror_sprite=True),
	Db(bytearray(b' \x07')),
	StartLoopNTimes(2),
	Db(bytearray(b'$\xc0\x00\xa0\x00')),
	Db(bytearray(b'%\xc0\x06\x80\xff')),
	Pause(30),
	EndLoop(),
	StartLoopNTimes(1, identifier="ACTION_481_start_loop_n_times_21"),
	Db(bytearray(b'$\xa0\xff@\x00')),
	Db(bytearray(b'%\xc0\x06\x80\xff')),
	Pause(30),
	EndLoop(),
	StartLoopNTimes(1),
	Db(bytearray(b'$\xa0\xff\xc0\xff')),
	Db(bytearray(b'%\xc0\x06\x80\xff')),
	Pause(30),
	EndLoop(),
	StartLoopNTimes(1),
	Db(bytearray(b'$`\x00\xc0\xff')),
	Db(bytearray(b'%\xc0\x06\x80\xff')),
	Pause(30),
	EndLoop(),
	StartLoopNTimes(1),
	Db(bytearray(b'$`\x00@\x00')),
	Db(bytearray(b'%\xc0\x06\x80\xff')),
	Pause(30),
	EndLoop(),
	Jmp(["ACTION_481_start_loop_n_times_21"])
])
