#A0822_KEEP_JUMPING_TERRAPIN_INIT

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	SetPriority(3),
	ClearSolidityBits(cant_pass_walls=True),
	SetAllSpeeds(NORMAL),
	Set700CToPressedButton(),
	JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 21, ["ACTION_822_pause_119"]),
	JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 22, ["ACTION_822_pause_63"]),
	SetSolidityBits(cant_pass_walls=True),
	FixedFCoordOn(),
	PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
	JumpToHeight(96),
	Walk1StepSoutheast(),
	Pause(8),
	FixedFCoordOff(),
	FaceSouthwest(),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	SetBit(TEMP_7043_1),
	Pause(24),
	Pause(24),
	SetAllSpeeds(FAST),
	PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
	JumpToHeight(105),
	SetSolidityBits(cant_pass_walls=True),
	ShiftSoutheastSteps(3),
	Pause(1, identifier="ACTION_822_pause_23"),
	JmpIfObjectInAir(NPC_3, ["ACTION_822_pause_23"]),
	SetBit(TEMP_7043_1),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	ClearSolidityBits(cant_pass_walls=True),
	SetAllSpeeds(NORMAL),
	Walk1StepSoutheast(),
	ShiftNortheastSteps(16),
	ShiftNortheastSteps(3),
	SetAllSpeeds(FAST),
	PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
	JumpToHeight(105),
	SetSolidityBits(cant_pass_walls=True),
	ShiftNortheastSteps(3),
	Pause(1, identifier="ACTION_822_pause_37"),
	JmpIfObjectInAir(NPC_3, ["ACTION_822_pause_37"]),
	SetBit(TEMP_7043_1),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	ClearSolidityBits(cant_pass_walls=True),
	SetAllSpeeds(NORMAL),
	ShiftNorthwestSteps(4),
	ShiftNorthwestSteps(2),
	ShiftNortheastSteps(2),
	ShiftNorthwestSteps(3),
	ShiftNortheastSteps(5),
	ShiftSoutheastSteps(4),
	SetAllSpeeds(FAST),
	PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
	JumpToHeight(105),
	ShiftSoutheastSteps(3),
	SetSolidityBits(cant_pass_walls=True),
	Pause(1, identifier="ACTION_822_pause_54"),
	JmpIfObjectInAir(NPC_3, ["ACTION_822_pause_54"]),
	SetBit(TEMP_7043_1),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	ClearSolidityBits(cant_pass_walls=True),
	SetAllSpeeds(NORMAL),
	ShiftNortheastSteps(2),
	VisibilityOff(),
	Return(),
	Pause(24, identifier="ACTION_822_pause_63"),
	SetSolidityBits(cant_pass_walls=True),
	FixedFCoordOn(),
	SetAllSpeeds(FAST),
	PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
	JumpToHeight(96),
	ShiftNorthwestSteps(2),
	Pause(8),
	FixedFCoordOff(),
	FaceSouthwest(),
	SetAllSpeeds(NORMAL),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	Pause(24),
	ShiftNorthwestSteps(2),
	SetAllSpeeds(FAST),
	PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
	JumpToHeight(105),
	ShiftNortheastSteps(3),
	SetSolidityBits(cant_pass_walls=True),
	Pause(1, identifier="ACTION_822_pause_82"),
	JmpIfObjectInAir(NPC_2, ["ACTION_822_pause_82"]),
	SetBit(TEMP_7043_1),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	ClearSolidityBits(cant_pass_walls=True),
	SetAllSpeeds(NORMAL),
	ShiftNortheastSteps(10),
	SetAllSpeeds(FAST),
	PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
	JumpToHeight(105),
	ShiftNortheastSteps(3),
	SetSolidityBits(cant_pass_walls=True),
	Pause(1, identifier="ACTION_822_pause_94"),
	JmpIfObjectInAir(NPC_2, ["ACTION_822_pause_94"]),
	SetBit(TEMP_7043_1),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	ClearSolidityBits(cant_pass_walls=True),
	SetAllSpeeds(NORMAL),
	ShiftNortheastSteps(2),
	ShiftNortheastSteps(7),
	ShiftSoutheastSteps(3),
	Walk1StepSoutheast(),
	ShiftSouthwestSteps(2),
	SetAllSpeeds(FAST),
	PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
	JumpToHeight(105),
	ShiftSoutheastSteps(3),
	SetSolidityBits(cant_pass_walls=True),
	Pause(1, identifier="ACTION_822_pause_110"),
	JmpIfObjectInAir(NPC_2, ["ACTION_822_pause_110"]),
	SetBit(TEMP_7043_1),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	ClearSolidityBits(cant_pass_walls=True),
	SetAllSpeeds(NORMAL),
	ShiftNortheastSteps(8),
	VisibilityOff(),
	Return(),
	Pause(24, identifier="ACTION_822_pause_119"),
	Pause(24),
	SetSolidityBits(cant_pass_walls=True),
	FixedFCoordOn(),
	PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
	JumpToHeight(96),
	Walk1StepNortheast(),
	Pause(8),
	FixedFCoordOff(),
	FaceSouthwest(),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	ShiftNortheastSteps(10),
	SetAllSpeeds(FAST),
	PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
	JumpToHeight(105),
	ShiftSoutheastSteps(3),
	SetSolidityBits(cant_pass_walls=True),
	Pause(1, identifier="ACTION_822_pause_136"),
	JmpIfObjectInAir(NPC_1, ["ACTION_822_pause_136"]),
	SetBit(TEMP_7043_1),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	ClearSolidityBits(cant_pass_walls=True),
	SetAllSpeeds(NORMAL),
	Walk1StepSoutheast(),
	ShiftNortheastSteps(5),
	Walk1StepNorthwest(),
	ShiftNorthwestSteps(2),
	ShiftNortheastSteps(3),
	SetAllSpeeds(FAST),
	PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
	JumpToHeight(105),
	ShiftNortheastSteps(3),
	SetSolidityBits(cant_pass_walls=True),
	Pause(1, identifier="ACTION_822_pause_152"),
	JmpIfObjectInAir(NPC_1, ["ACTION_822_pause_152"]),
	SetBit(TEMP_7043_1),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	ClearSolidityBits(cant_pass_walls=True),
	SetAllSpeeds(NORMAL),
	Walk1StepNortheast(),
	Walk1StepSoutheast(),
	ShiftSoutheastSteps(2),
	ShiftNortheastSteps(2),
	SetAllSpeeds(FAST),
	PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
	JumpToHeight(105),
	ShiftNortheastSteps(3),
	SetSolidityBits(cant_pass_walls=True),
	Pause(1, identifier="ACTION_822_pause_167"),
	JmpIfObjectInAir(NPC_1, ["ACTION_822_pause_167"]),
	SetBit(TEMP_7043_1),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	ClearSolidityBits(cant_pass_walls=True),
	SetAllSpeeds(NORMAL),
	ShiftNortheastSteps(2),
	VisibilityOff(),
	Return()
])
