"""A0646_MIDAS_2ND_TUNNELS_CROOK"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        FaceSouthwest(),
        SetPriority(3),
        SequenceLoopingOn(),
        StartLoopNTimes(1),
        SetSpriteSequence(index=3, looping=False),
        Pause(24),
        SetSpriteSequence(index=2, looping=False),
        Pause(24),
        EndLoop(),
        SetAllSpeeds(FAST),
        WalkNortheastSteps(2),
        ObjectMemoryModifyBits(arg_1=0x09, set_bits=[5], clear_bits=[4, 6]),
        Walk1StepEast(),
        Pause(60),
        WalkEastSteps(3),
        SetPriority(3),
        Walk1StepEast(),
        StartLoopNTimes(1),
        FaceSouthwest(),
        Pause(20),
        FaceSoutheast(),
        Pause(20),
        EndLoop(),
        FixedFCoordOn(),
        WalkSouthSteps(3),
        FixedFCoordOff(),
        Walk1StepSoutheast(),
        FaceNortheast(),
        Pause(8),
        SetAllSpeeds(FASTEST),
        ShiftZUpSteps(2),
        SetAllSpeeds(NORMAL),
        Walk1StepNortheast(),
        Pause(24),
        FaceSoutheast(),
        Pause(96),
        SetAllSpeeds(VERY_FAST),
        FaceNortheast(),
        AddZCoord1Step(),
        SetAllSpeeds(NORMAL),
        WalkNortheastSteps(3),
        FaceSoutheast(),
        SetSpriteSequence(index=3, looping=False, mirror_sprite=True),
        Pause(24),
        StartLoopNTimes(1),
        FaceSouthwest(),
        Pause(24),
        FaceSoutheast(),
        Pause(24),
        EndLoop(),
        Pause(17),
        SetAllSpeeds(FAST),
        SetBit(TEMP_7043_2),
        JumpToHeight(96),
        WalkSoutheastSteps(3),
        ObjectMemoryModifyBits(arg_1=0x09, set_bits=[5], clear_bits=[4, 6]),
        Walk1StepEast(),
        WalkSoutheastSteps(4),
        SetSequenceSpeed(NORMAL),
        JumpToHeight(64),
        SetSpriteSequence(index=2, looping=False, mirror_sprite=True),
        ClearBit(TEMP_7043_2),
        Pause(32),
        SetAllSpeeds(NORMAL),
        Walk1StepSouthwest(),
        Walk1StepSoutheast(),
        SetPriority(3),
        WalkNortheastSteps(2),
        Pause(14),
        SetSpriteSequence(index=4, looping=False, mirror_sprite=True),
        Pause(60),
        SetAllSpeeds(FAST),
        JumpToHeight(104),
        WalkNortheastSteps(3),
        SetAllSpeeds(NORMAL),
        WalkSoutheastSteps(2),
        WalkNortheastSteps(4),
        WalkSoutheastSteps(2),
        SetBit(TEMP_7043_2),
        ClearBit(TEMP_7043_1),
        Pause(18),
        SetAllSpeeds(VERY_FAST),
        StartLoopNTimes(1),
        ShiftZUpPixels(8),
        ShiftZDownPixels(8),
        EndLoop(),
        SetAllSpeeds(FAST),
        JumpToHeight(96),
        WalkSoutheastSteps(3),
        FixedFCoordOn(),
        Walk1StepEast(),
        FixedFCoordOff(),
        FaceSouthwest(),
        Pause(72),
        SetAllSpeeds(SLOW),
        JumpToHeight(54),
        SetSpriteSequence(index=2, looping=False, mirror_sprite=True),
        Pause(36),
        FaceSoutheast(),
        Pause(8),
        SetAllSpeeds(FAST),
        JumpToHeight(96),
        WalkSoutheastSteps(3),
        Walk1StepEast(),
        SetBit(TEMP_7043_2),
        ClearBit(TEMP_7043_1),
        JumpToHeight(96),
        Pause(32),
        FaceSoutheast(),
        SetAllSpeeds(VERY_FAST),
        StartLoopNTimes(1),
        ShiftZUpPixels(8),
        ShiftZDownPixels(8),
        EndLoop(),
        SetAllSpeeds(FAST),
        JumpToHeight(96),
        WalkSoutheastSteps(4),
        FaceSouthwest(),
        SetAllSpeeds(NORMAL),
        SetSpriteSequence(index=3, is_sequence=True, looping=True),
        Pause(1, identifier="ACTION_646_pause_120"),
        JmpIfBitClear(TEMP_7043_1, ["ACTION_646_pause_120"]),
        ResetProperties(),
        Pause(13),
        SetSpriteSequence(index=2, looping=False),
        Pause(40),
        SetSequenceSpeed(FASTEST),
        JmpIfBitSet(MIDAS_RIVER_TUNNEL_2_BIT_1, ["ACTION_646_face_southwest_130"]),
        FaceSoutheast(),
        Return(),
        FaceSouthwest(identifier="ACTION_646_face_southwest_130"),
        Return(),
    ]
)
