"""A0407_STAR_HILL_3RD_ROOM_MUKU"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        Pause(21, identifier="ACTION_407_pause_0"),
        ClearSolidityBits(bit_4=True, cant_walk_through=True),
        SetSpriteSequence(index=10, is_mold=True, is_sequence=True, looping=True),
        Pause(1),
        ShiftToXYCoords(x=28, y=113),
        SetSpriteSequence(index=8, looping=False),
        Pause(160),
        SetSolidityBits(bit_4=True, cant_walk_through=True),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        Pause(60),
        SetSpriteSequence(index=9, looping=False),
        Pause(292),
        ClearSolidityBits(bit_4=True, cant_walk_through=True),
        VisibilityOff(),
        Pause(48),
        ClearSolidityBits(bit_4=True, cant_walk_through=True),
        SetSpriteSequence(index=10, is_mold=True, is_sequence=True, looping=True),
        Pause(1),
        ShiftToXYCoords(x=30, y=85),
        SetSpriteSequence(index=8, looping=False),
        Pause(160),
        SetSolidityBits(bit_4=True, cant_walk_through=True),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        Pause(60),
        SetSpriteSequence(index=9, looping=False),
        Pause(292),
        ClearSolidityBits(bit_4=True, cant_walk_through=True),
        ShiftToXYCoords(x=0, y=0),
        ObjectMemorySetBit(arg_1=0x30, bits=[4]),
        Pause(48),
        SetSpriteSequence(index=10, is_mold=True, is_sequence=True, looping=True),
        Pause(1),
        ShiftToXYCoords(x=24, y=97),
        VisibilityOn(),
        SetSpriteSequence(index=8, looping=False),
        Pause(160),
        SetSolidityBits(bit_4=True, cant_walk_through=True),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        Pause(60),
        SetSpriteSequence(index=9, looping=False),
        Pause(292),
        ClearSolidityBits(bit_4=True, cant_walk_through=True),
        VisibilityOff(),
        Pause(48),
        SetSpriteSequence(
            index=10, is_mold=True, is_sequence=True, looping=True, mirror_sprite=True
        ),
        Pause(1),
        ShiftToXYCoords(x=22, y=85),
        VisibilityOn(),
        SetSpriteSequence(index=8, looping=False, mirror_sprite=True),
        Pause(160),
        SetSolidityBits(bit_4=True, cant_walk_through=True),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        Pause(60),
        SetSpriteSequence(index=9, looping=False, mirror_sprite=True),
        Pause(292),
        ClearSolidityBits(bit_4=True, cant_walk_through=True),
        VisibilityOff(),
        Pause(48),
        SetSpriteSequence(index=10, is_mold=True, is_sequence=True, looping=True),
        Pause(1),
        ShiftToXYCoords(x=28, y=121),
        VisibilityOn(),
        SetSpriteSequence(index=8, looping=False),
        Pause(160),
        SetSolidityBits(bit_4=True, cant_walk_through=True),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        Pause(60),
        SetSpriteSequence(index=9, looping=False),
        Pause(292),
        ClearSolidityBits(bit_4=True, cant_walk_through=True),
        VisibilityOff(),
        Pause(21),
        Jmp(["ACTION_407_pause_0"]),
    ]
)
