"""A0035_INNER_FORST_WIGGLER_NORTHEAST"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        JmpIfBitSet(TEMP_7044_5, ["ACTION_35_jmp_if_bit_set_3"]),
        JmpIfBitSet(TEMP_7044_6, ["ACTION_35_face_southwest_31"]),
        Jmp(["ACTION_35_face_southwest_21"]),
        JmpIfBitSet(
            TEMP_7044_6,
            ["ACTION_35_face_southwest_11"],
            identifier="ACTION_35_jmp_if_bit_set_3"),
        FaceNortheast(),
        JmpToSubroutine(["ACTION_34_clear_solidity_bits_48"]),
        SetPriority(2),
        WalkNortheastSteps(2),
        SetPriority(3),
        WalkNortheastSteps(2),
        Jmp(["ACTION_32_shift_z_up_steps_20"]),
        FaceSouthwest(identifier="ACTION_35_face_southwest_11"),
        JmpToSubroutine(["ACTION_34_clear_solidity_bits_48"]),
        SetPriority(3),
        Walk1StepSouthwest(),
        Walk1StepSoutheast(),
        WalkNortheastSteps(10),
        SetPriority(2),
        Walk1StepNorthwest(),
        Walk1StepSouthwest(),
        Jmp(["ACTION_32_shift_z_up_steps_20"]),
        FaceSouthwest(identifier="ACTION_35_face_southwest_21"),
        JmpToSubroutine(["ACTION_34_clear_solidity_bits_48"]),
        SetPriority(3),
        Walk1StepSouthwest(),
        Walk1StepNorthwest(),
        SetPriority(2),
        WalkNortheastSteps(10),
        Walk1StepSoutheast(),
        Walk1StepSouthwest(),
        Jmp(["ACTION_32_shift_z_up_steps_20"]),
        FaceSouthwest(identifier="ACTION_35_face_southwest_31"),
        JmpToSubroutine(["ACTION_34_clear_solidity_bits_48"]),
        SetPriority(3),
        Walk1StepSouthwest(),
        Walk1StepSoutheast(),
        WalkNortheastSteps(10),
        Walk1StepSoutheast(),
        WalkSouthwestSteps(5),
        SetPriority(2),
        StartLoopNTimes(2),
        Walk1StepNorthwest(),
        Walk1StepSouthwest(),
        EndLoop(),
        WalkSouthwestSteps(2),
        SetPriority(3),
        Walk1StepSoutheast(),
        Walk1StepNortheast(),
        Jmp(["ACTION_32_shift_z_up_steps_20"]),
    ]
)
