"""A1015_END_CREDITS_FROGFUCIUS_RAISES"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        SetSpriteSequence(index=0, is_mold=True, looping=True),
        SetObjectMemoryBits(arg_1=0x0E, bits=[0]),
        Pause(110),
        Pause(60),
        SetSpriteSequence(index=6, is_mold=True, looping=True),
        Pause(80),
        SetSpriteSequence(index=0, is_mold=True, looping=True),
        Pause(20),
        SetSpriteSequence(
            index=6,
            is_mold=True,
            looping=True,
            identifier="ACTION_1015_set_sprite_sequence_8"),
        Pause(5),
        SetSpriteSequence(index=0, is_mold=True, looping=True),
        Pause(10),
        SetSpriteSequence(index=6, is_mold=True, looping=True),
        Pause(20),
        SetSpriteSequence(index=0, is_mold=True, looping=True),
        Pause(5),
        SetSpriteSequence(index=6, is_mold=True, looping=True),
        Pause(10),
        SetSpriteSequence(index=0, is_mold=True, looping=True),
        Pause(3),
        SetSpriteSequence(index=6, is_mold=True, looping=True),
        Pause(5),
        SetSpriteSequence(index=0, is_mold=True, looping=True),
        Pause(5),
        SetSpriteSequence(index=6, is_mold=True, looping=True),
        Pause(15),
        SetSpriteSequence(index=0, is_mold=True, looping=True),
        Pause(10),
        SetSpriteSequence(index=6, is_mold=True, looping=True),
        Pause(15),
        SetSpriteSequence(index=0, is_mold=True, looping=True),
        Pause(15),
        SetSpriteSequence(index=6, is_mold=True, looping=True),
        Pause(7),
        SetSpriteSequence(index=0, is_mold=True, looping=True),
        Pause(7),
        SetSpriteSequence(index=6, is_mold=True, looping=True),
        Pause(40),
        SetSpriteSequence(index=0, is_mold=True, looping=True),
        Jmp(["ACTION_1015_set_sprite_sequence_8"]),
        Return(),
    ]
)
