#A0821_KEEP_VERTICAL_PLATFORMS_IN_LAVA_ROOM

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	SetSolidityBits(bit_4=True),
	SetWalkingSpeed(SLOW),
	FixedFCoordOn(),
	Set700CToPressedButton(),
	JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 27, ["ACTION_821_set_animation_speed_28"]),
	JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 21, ["ACTION_821_shift_southwest_steps_19"]),
	SetPriority(3),
	AddConstToVar(PRIMARY_TEMP_700C, 65515),
	Inc(PRIMARY_TEMP_700C),
	LoadMemory(PRIMARY_TEMP_700C),
	Pause(9),
	EndLoop(),
	Set700CToPressedButton(),
	Mem700CAndConst(0x0001),
	JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 0, ["ACTION_821_shift_z_up_steps_16"]),
	Pause(96),
	ShiftZUpSteps(3, identifier="ACTION_821_shift_z_up_steps_16"),
	ShiftZDownSteps(3),
	Jmp(["ACTION_821_shift_z_up_steps_16"]),
	ShiftSouthwestSteps(2, identifier="ACTION_821_shift_southwest_steps_19"),
	ShiftZUpSteps(5),
	Walk1StepSouthwest(),
	Pause(32),
	Walk1StepNortheast(),
	ShiftZDownSteps(5),
	ShiftNortheastSteps(2),
	Pause(32),
	Jmp(["ACTION_821_shift_southwest_steps_19"]),
	SetWalkingSpeed(SLOW, identifier="ACTION_821_set_animation_speed_28"),
	ShiftZUpSteps(3),
	SetWalkingSpeed(NORMAL),
	ShiftZUpSteps(4),
	SetWalkingSpeed(FAST),
	ShiftZUpSteps(3),
	StartLoopNTimes(7),
	ShiftZDownPixels(4),
	ShiftZUpPixels(4),
	EndLoop(),
	SetWalkingSpeed(FASTEST),
	ShiftZDownSteps(10),
	Jmp(["ACTION_821_set_animation_speed_28"])
])
