"""A0057_SEWER_FISH"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        ClearSolidityBits(cant_pass_npcs=True, bit_7=True),
        Set700CToPressedButton(),
        Mem700CAndConst(0x0003),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 1, ["ACTION_57_pause_8"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 2, ["ACTION_57_pause_9"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 3, ["ACTION_57_pause_10"]),
        Pause(3),
        Inc(TEMP_702C),
        Pause(3, identifier="ACTION_57_pause_8"),
        Pause(3, identifier="ACTION_57_pause_9"),
        Pause(3, identifier="ACTION_57_pause_10"),
        Inc(TEMP_702C),
        JmpIfBitSet(SEWER_WATER_LEVEL, ["ACTION_57_object_memory_modify_bits_64"]),
        Set700CToCurrentLevel(),
        JmpIfVarEqualsConst(
            PRIMARY_TEMP_700C, 57, ["ACTION_57_set_animation_speed_83"]
        ),
        JmpIfVarEqualsConst(
            PRIMARY_TEMP_700C, 58, ["ACTION_57_set_animation_speed_83"]
        ),
        Set700CToPressedButton(),
        SetWalkingSpeed(SLOW),
        SetSequenceSpeed(NORMAL),
        JmpIfVarEqualsConst(
            PRIMARY_TEMP_700C, 20, ["ACTION_57_set_animation_speed_83"]
        ),
        WalkFDirectionSteps(12),
        TurnClockwise45DegreesNTimes(4),
        BPL262728(identifier="ACTION_57_bpl_26_27_28_22"),
        ClearSolidityBits(cant_pass_walls=True),
        SetWalkingSpeed(SLOW),
        SetSequenceSpeed(NORMAL),
        WalkFDirectionSteps(10),
        JmpIfObjectWithinRange(
            comparing_npc=MARIO,
            usually=0,
            tiles=8,
            destinations=["ACTION_57_set_solidity_bits_33"],
        ),
        WalkFDirectionSteps(2),
        TurnClockwise45DegreesNTimes(4),
        WalkFDirectionSteps(12),
        TurnClockwise45DegreesNTimes(4),
        Jmp(["ACTION_57_bpl_26_27_28_22"]),
        SetSolidityBits(
            cant_pass_walls=True, identifier="ACTION_57_set_solidity_bits_33"
        ),
        SetWalkingSpeed(NORMAL),
        SetSequenceSpeed(FAST),
        WalkFDirectionSteps(2),
        Db(bytearray(b"\xc7\x87")),
        Set700CToObjectCoord(target_npc=DUMMY_0X07, coord=COORD_F, pixel=True),
        AddConstToVar(PRIMARY_TEMP_700C, 4),
        Mem700CAndConst(0x0007),
        CopyVarToVar(from_var=PRIMARY_TEMP_700C, to_var=TEMP_702E),
        SetWalkingSpeed(FAST),
        JumpToHeight(height=160, silent=True),
        Walk1StepFDirection(),
        SetPriority(3),
        WalkFDirectionSteps(4),
        JumpToHeight(height=64, silent=True),
        TurnClockwise45DegreesNTimes(4),
        WalkFDirectionSteps(2),
        JumpToHeight(height=32, silent=True),
        WalkFDirectionSteps(2),
        ObjectMemoryModifyBits(arg_1=0x09, set_bits=[5], clear_bits=[4, 6]),
        Move70107015To7016701B(),
        WalkTo70167018701A(),
        CopyVarToVar(from_var=TEMP_702E, to_var=PRIMARY_TEMP_700C),
        FaceEast7C(),
        BPL262728(),
        ClearSolidityBits(cant_pass_walls=True),
        SetWalkingSpeed(SLOW),
        SetSequenceSpeed(NORMAL),
        WalkFDirectionSteps(12),
        TurnClockwise45DegreesNTimes(4),
        Jmp(["ACTION_57_bpl_26_27_28_22"]),
        ObjectMemoryModifyBits(
            arg_1=0x09,
            set_bits=[5],
            clear_bits=[4, 6],
            identifier="ACTION_57_object_memory_modify_bits_64",
        ),
        ClearSolidityBits(cant_pass_npcs=True, bit_7=True),
        SetWalkingSpeed(NORMAL),
        FixedFCoordOn(),
        FloatingOn(),
        JmpIfRandom1of2(["ACTION_57_set_sprite_sequence_72"]),
        SetSpriteSequence(index=8, is_sequence=True, looping=False),
        Jmp(["ACTION_57_turn_random_direction_73"]),
        SetSpriteSequence(
            index=8,
            is_sequence=True,
            looping=False,
            mirror_sprite=True,
            identifier="ACTION_57_set_sprite_sequence_72",
        ),
        TurnRandomDirection(identifier="ACTION_57_turn_random_direction_73"),
        JmpIfRandom2of3(["ACTION_57_jump_to_height_79", "ACTION_57_jump_to_height_79"]),
        JumpToHeight(112),
        Walk1StepFDirection(),
        ResetProperties(),
        Jmp(["ACTION_57_walk_1_step_f_direction_80"]),
        JumpToHeight(64, identifier="ACTION_57_jump_to_height_79"),
        Walk1StepFDirection(identifier="ACTION_57_walk_1_step_f_direction_80"),
        ResetProperties(),
        Jmp(["ACTION_57_object_memory_modify_bits_64"]),
        SetWalkingSpeed(SLOW, identifier="ACTION_57_set_animation_speed_83"),
        Inc(TEMP_702C),
        CopyVarToVar(from_var=TEMP_702C, to_var=PRIMARY_TEMP_700C),
        Mem700CAndConst(0x0003),
        JmpIfVarEqualsConst(
            PRIMARY_TEMP_700C, 0, ["ACTION_57_shift_f_direction_steps_89"]
        ),
        SetWalkingSpeed(NORMAL),
        WalkFDirectionSteps(2, identifier="ACTION_57_shift_f_direction_steps_89"),
        Inc(TEMP_702C),
        CopyVarToVar(from_var=TEMP_702C, to_var=PRIMARY_TEMP_700C),
        Mem700CAndConst(0x0003),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 0, ["ACTION_57_face_mario_96"]),
        TurnRandomDirection(),
        Jmp(["ACTION_57_set_animation_speed_83"]),
        FaceMario(identifier="ACTION_57_face_mario_96"),
        Jmp(["ACTION_57_set_animation_speed_83"]),
    ]
)
