"""A0758_STAR_HILL_2ND_ROOM_WEST_GECKO"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        SequenceLoopingOn(identifier="ACTION_758_sequence_looping_on_0"),
        ShadowOff(),
        SetWalkingSpeed(VERY_SLOW),
        WalkSoutheastSteps(4),
        Pause(16),
        FaceNortheast(),
        Pause(16),
        WalkNortheastSteps(4),
        Pause(16),
        FaceSoutheast(),
        Pause(16),
        WalkSoutheastSteps(4),
        Pause(16),
        FaceNortheast(),
        Pause(16),
        WalkNortheastSteps(4),
        Pause(16),
        FaceSouthwest(),
        SetSpriteSequence(index=0, is_sequence=True, looping=True),
        Pause(16),
        WalkSouthSteps(4),
        FaceSouthwest(),
        ResetProperties(),
        Pause(16),
        WalkSouthwestSteps(4),
        Pause(16),
        FaceNorthwest(),
        Pause(16),
        WalkNorthwestSteps(4),
        Pause(16),
        FaceSouthwest(),
        SetPriority(3),
        Pause(16),
        WalkSouthwestSteps(4),
        Pause(16),
        FaceNorthwest(),
        Pause(16),
        WalkNorthwestSteps(8),
        Pause(16),
        FaceNortheast(),
        Pause(16),
        WalkNortheastSteps(4),
        SetPriority(2),
        Pause(16),
        FaceSoutheast(),
        Pause(16),
        Jmp(["ACTION_758_sequence_looping_on_0"]),
    ]
)
