#A0405_FOREST_MAZE_AREA_FREEMOVING_AMANITA

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	SequenceLoopingOn(identifier="ACTION_405_sequence_looping_on_0"),
	SetSequenceSpeed(NORMAL),
	JmpIfRandom1of2(["ACTION_405_walk_1_step_southeast_20"]),
	ShiftNortheastSteps(2),
	Pause(8),
	Walk1StepSoutheast(),
	Pause(8),
	Walk1StepSouthwest(),
	Pause(8),
	Walk1StepSoutheast(),
	Pause(8),
	Walk1StepNortheast(),
	Pause(8),
	Walk1StepNorthwest(),
	Pause(8),
	ShiftSouthwestSteps(2),
	Pause(8),
	Walk1StepNorthwest(),
	Pause(8),
	Jmp(["ACTION_405_sequence_looping_on_0"]),
	Walk1StepSoutheast(identifier="ACTION_405_walk_1_step_southeast_20"),
	Pause(8),
	Walk1StepNortheast(),
	Pause(8),
	Walk1StepNorthwest(),
	Pause(8),
	ShiftSoutheastSteps(2),
	Pause(8),
	Walk1StepNortheast(),
	Pause(8),
	ShiftNorthwestSteps(2),
	Pause(8),
	ShiftSouthwestSteps(2),
	Pause(8),
	Jmp(["ACTION_405_sequence_looping_on_0"])
])
