"""A0782_LANDS_END_CANNON_WHILE_PLAYER_OCCUPIED"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        SetBit(TEMP_7043_0),
        SetBit(TEMP_7044_6),
        SetSpriteSequence(
            index=0,
            is_sequence=True,
            looping=True,
            identifier="ACTION_782_set_sprite_sequence_2",
        ),
        JmpIfBitClear(TEMP_7043_0, ["ACTION_783_clear_bit_61"]),
        SetVarToConst(TEMP_7032, 0),
        SetVarToConst(SECONDARY_TEMP_7024, 1792),
        Pause(6),
        SetVarToConst(SECONDARY_TEMP_7024, 1793),
        Pause(6),
        JmpIfBitClear(TEMP_7043_0, ["ACTION_783_clear_bit_61"]),
        SetVarToConst(SECONDARY_TEMP_7024, 1794),
        Pause(6),
        SetVarToConst(SECONDARY_TEMP_7024, 1795),
        Pause(6),
        JmpIfBitClear(TEMP_7043_0, ["ACTION_782_clear_bit_55"]),
        JmpIfBitClear(TEMP_7044_4, ["ACTION_782_set_sprite_sequence_17"]),
        PlaySound(sound=SO143_METRONOME_UPBEAT_DING, channel=4),
        SetSpriteSequence(
            index=2,
            is_sequence=True,
            looping=True,
            identifier="ACTION_782_set_sprite_sequence_17",
        ),
        SetVarToConst(TEMP_7032, 7),
        Pause(6),
        SetVarToConst(SECONDARY_TEMP_7024, 1794),
        Pause(6),
        SetVarToConst(SECONDARY_TEMP_7024, 1793),
        Pause(6),
        SetVarToConst(SECONDARY_TEMP_7024, 1792),
        Pause(6),
        JmpIfBitClear(TEMP_7044_4, ["ACTION_782_set_sprite_sequence_28"]),
        PlaySound(sound=SO144_CLICK, channel=4),
        SetSpriteSequence(
            index=0,
            is_sequence=True,
            looping=True,
            identifier="ACTION_782_set_sprite_sequence_28",
        ),
        JmpIfBitClear(TEMP_7043_0, ["ACTION_783_clear_bit_61"]),
        SetVarToConst(TEMP_7032, 0),
        SetVarToConst(SECONDARY_TEMP_7024, 768),
        Pause(6),
        SetVarToConst(SECONDARY_TEMP_7024, 769),
        Pause(6),
        JmpIfBitClear(TEMP_7043_0, ["ACTION_783_clear_bit_61"]),
        SetVarToConst(SECONDARY_TEMP_7024, 770),
        Pause(6),
        SetVarToConst(SECONDARY_TEMP_7024, 771),
        Pause(6),
        JmpIfBitClear(TEMP_7043_0, ["ACTION_782_clear_bit_55"]),
        JmpIfBitClear(TEMP_7044_4, ["ACTION_782_set_sprite_sequence_43"]),
        PlaySound(sound=SO144_CLICK, channel=4),
        SetSpriteSequence(
            index=1,
            is_sequence=True,
            looping=True,
            identifier="ACTION_782_set_sprite_sequence_43",
        ),
        SetVarToConst(TEMP_7032, 3),
        Pause(6),
        SetVarToConst(SECONDARY_TEMP_7024, 770),
        Pause(6),
        SetVarToConst(SECONDARY_TEMP_7024, 769),
        Pause(6),
        SetVarToConst(SECONDARY_TEMP_7024, 768),
        Pause(6),
        JmpIfBitClear(TEMP_7044_4, ["ACTION_782_set_sprite_sequence_2"]),
        PlaySound(sound=SO144_CLICK, channel=4),
        Jmp(["ACTION_782_set_sprite_sequence_2"]),
        ClearBit(TEMP_7044_6, identifier="ACTION_782_clear_bit_55"),
        ResetProperties(),
        Return(),
    ]
)
