"""A0299_MINES_FINAL_BOSS_ROOM_TINY_HENCHMAN_EXPLODE"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        VisibilityOff(),
        TransferToXYZF(x=7, y=18, z=6, direction=EAST),
        TransferXYZFPixels(x=4, y=2, z=0, direction=EAST),
        SetPriority(3),
        SetSpriteSequence(index=0, is_sequence=True, looping=True),
        VisibilityOn(),
        FaceMario(),
        JmpIfBitSet(TEMP_7043_1, ["ACTION_299_set_var_to_random_66"]),
        SetBit(TEMP_7043_1),
        Set700CToObjectCoord(target_npc=DUMMY_0X07, coord=COORD_F, pixel=True),
        JmpIfVarEqualsConst(
            PRIMARY_TEMP_700C,
            0,
            ["ACTION_299_jmp_if_bit_set_23"],
            identifier="ACTION_299_jmp_if_700C_equals_short_10"),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 1, ["ACTION_299_jmp_if_bit_set_23"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 2, ["ACTION_299_jmp_if_bit_set_35"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 4, ["ACTION_299_jmp_if_bit_set_29"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 5, ["ACTION_299_jmp_if_bit_set_41"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 6, ["ACTION_299_jmp_if_bit_set_41"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 7, ["ACTION_299_jmp_if_bit_set_23"]),
        JmpIfBitSet(
            TEMP_7043_1,
            ["ACTION_299_clear_bit_47"],
            identifier="ACTION_299_jmp_if_bit_set_17"),
        SetBit(TEMP_7043_1),
        SetWalkingSpeed(FAST),
        JumpToHeight(height=64, silent=True),
        WalkSouthwestPixels(48),
        Jmp(["ACTION_299_set_priority_62"]),
        JmpIfBitSet(
            TEMP_7043_2,
            ["ACTION_299_clear_bit_50"],
            identifier="ACTION_299_jmp_if_bit_set_23"),
        SetBit(TEMP_7043_2),
        SetWalkingSpeed(FAST),
        JumpToHeight(height=64, silent=True),
        WalkSoutheastPixels(48),
        Jmp(["ACTION_299_set_priority_62"]),
        JmpIfBitSet(
            TEMP_7043_3,
            ["ACTION_299_clear_bit_53"],
            identifier="ACTION_299_jmp_if_bit_set_29"),
        SetBit(TEMP_7043_3),
        SetWalkingSpeed(FASTER),
        JumpToHeight(height=64, silent=True),
        WalkWestPixels(72),
        Jmp(["ACTION_299_set_priority_62"]),
        JmpIfBitSet(
            TEMP_7043_4,
            ["ACTION_299_clear_bit_56"],
            identifier="ACTION_299_jmp_if_bit_set_35"),
        SetBit(TEMP_7043_4),
        JumpToHeight(height=80, silent=True),
        SetWalkingSpeed(FAST),
        WalkSouthPixels(36),
        Jmp(["ACTION_299_set_priority_62"]),
        JmpIfBitSet(
            TEMP_7043_5,
            ["ACTION_299_clear_bit_59"],
            identifier="ACTION_299_jmp_if_bit_set_41"),
        SetBit(TEMP_7043_5),
        SetWalkingSpeed(FAST),
        JumpToHeight(height=64, silent=True),
        WalkNorthwestPixels(48),
        Jmp(["ACTION_299_set_priority_62"]),
        ClearBit(TEMP_7043_1, identifier="ACTION_299_clear_bit_47"),
        JmpIfRandom1of2(["ACTION_299_jmp_if_bit_set_35"]),
        Jmp(["ACTION_299_jmp_if_bit_set_29"]),
        ClearBit(TEMP_7043_2, identifier="ACTION_299_clear_bit_50"),
        JmpIfRandom1of2(["ACTION_299_jmp_if_bit_set_17"]),
        Jmp(["ACTION_299_jmp_if_bit_set_35"]),
        ClearBit(TEMP_7043_3, identifier="ACTION_299_clear_bit_53"),
        JmpIfRandom1of2(["ACTION_299_jmp_if_bit_set_41"]),
        Jmp(["ACTION_299_jmp_if_bit_set_17"]),
        ClearBit(TEMP_7043_4, identifier="ACTION_299_clear_bit_56"),
        JmpIfRandom1of2(["ACTION_299_jmp_if_bit_set_17"]),
        Jmp(["ACTION_299_jmp_if_bit_set_23"]),
        ClearBit(TEMP_7043_5, identifier="ACTION_299_clear_bit_59"),
        JmpIfRandom1of2(["ACTION_299_jmp_if_bit_set_29"]),
        Jmp(["ACTION_299_jmp_if_bit_set_17"]),
        SetPriority(2, identifier="ACTION_299_set_priority_62"),
        Pause(1, identifier="ACTION_299_pause_63"),
        JmpIfObjectInAir(DUMMY_0X07, ["ACTION_299_pause_63"]),
        Jmp(["ACTION_302_pause_0"]),
        SetVarToRandom(
            PRIMARY_TEMP_700C, 8, identifier="ACTION_299_set_var_to_random_66"
        ),
        Jmp(["ACTION_299_jmp_if_700C_equals_short_10"]),
    ]
)
