"""A0037_MIDAS_RIVER_3RD_TUNNEL_ON_LEFT_GOOMBETTE"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        SetPriority(3),
        SequenceLoopingOn(),
        Pause(40),
        WalkSoutheastSteps(2),
        SetAllSpeeds(FAST),
        JumpToHeight(96),
        WalkSoutheastSteps(3),
        SetAllSpeeds(NORMAL),
        FixedFCoordOn(),
        Walk1StepEast(),
        FixedFCoordOff(),
        Walk1StepNortheast(),
        SetAllSpeeds(FAST),
        StartLoopNTimes(1),
        ShiftZUpPixels(8),
        ShiftZDownPixels(8),
        EndLoop(),
        SetBit(TEMP_7043_2),
        SetVRAMPriority(PRIORITY_3),
        SetAllSpeeds(FAST),
        Walk1StepWest(),
        JumpToHeight(96),
        WalkNorthwestSteps(3),
        SetAllSpeeds(NORMAL),
        WalkNorthwestSteps(4),
        PlaySound(sound=SO065_THWOMP_STOMP, channel=4),
        SetSequenceSpeed(SLOW),
        SetSpriteSequence(index=2, looping=False),
        Pause(40),
        SetSequenceSpeed(NORMAL),
        WalkWestSteps(3),
        WalkNorthwestSteps(2),
        SetAllSpeeds(FAST),
        JumpToHeight(96),
        WalkNorthwestSteps(3),
        SetAllSpeeds(NORMAL),
        WalkNorthwestSteps(2),
        ObjectMemoryModifyBits(arg_1=0x09, set_bits=[5], clear_bits=[4, 6]),
        WalkNorthwestSteps(2),
        SetPriority(3),
        Walk1StepNorthwest(),
        SetBit(TEMP_7043_3),
        Return(),
    ]
)
