#A0509_PIPE_VAULT_FIREBALL

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	ClearSolidityBits(bit_4=True, cant_pass_npcs=True, cant_walk_through=True, bit_7=True, identifier="ACTION_509_clear_solidity_bits_0"),
	SetPriority(3),
	VisibilityOn(),
	SetSpriteSequence(index=0, is_sequence=True, looping=True),
	Pause(5),
	SetWalkingSpeed(FASTEST),
	SetSpriteSequence(index=1, is_sequence=True, looping=True),
	PlaySound(sound=SO084_SMOKED, channel=6),
	AddZCoord1Step(),
	SetSolidityBits(bit_4=True, cant_pass_npcs=True, cant_walk_through=True, bit_7=True),
	AddZCoord1Step(),
	SetWalkingSpeed(VERY_FAST),
	AddZCoord1Step(),
	SetWalkingSpeed(FASTER),
	ShiftZUpPixels(8),
	SetWalkingSpeed(FAST),
	ShiftZUpPixels(4),
	SetWalkingSpeed(NORMAL),
	ShiftZUpPixels(4),
	StartLoopNTimes(3),
	SetSpriteSequence(index=2, is_sequence=True, looping=True),
	Pause(4),
	SetSpriteSequence(index=3, is_sequence=True, looping=True),
	Pause(4),
	SetSpriteSequence(index=4, is_sequence=True, looping=True),
	Pause(4),
	EndLoop(),
	SetSpriteSequence(index=4, is_sequence=True, looping=True),
	ShiftZDownPixels(4),
	SetWalkingSpeed(FAST),
	ShiftZDownPixels(4),
	SetWalkingSpeed(FASTER),
	ShiftZDownPixels(8),
	SetWalkingSpeed(VERY_FAST),
	DecZCoord1Step(),
	SetWalkingSpeed(FASTEST),
	SetSpriteSequence(index=2, is_sequence=True, looping=True),
	DecZCoord1Step(),
	ClearSolidityBits(bit_4=True, cant_pass_npcs=True, cant_walk_through=True, bit_7=True),
	DecZCoord1Step(),
	SetSpriteSequence(index=0, is_sequence=True, looping=True),
	Pause(5),
	VisibilityOff(),
	Pause(90),
	Jmp(["ACTION_509_clear_solidity_bits_0"])
])
