"""A0890_NIMBUS_DIZZY_SHY_GUY"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        Set700CToCurrentLevel(),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 117, ["ACTION_890_pause_23"]),
        Pause(1, identifier="ACTION_890_pause_2"),
        JmpIfBitSet(TEMP_7043_2, ["ACTION_890_pause_5"]),
        Jmp(["ACTION_890_pause_2"]),
        Pause(90, identifier="ACTION_890_pause_5"),
        FaceSouthwest(),
        SetSpriteSequence(index=5, is_sequence=True, looping=True),
        JmpIfRandom1of2(
            ["ACTION_890_set_animation_speed_11"],
            identifier="ACTION_890_jmp_if_random_above_128_8",
        ),
        SetWalkingSpeed(NORMAL),
        Jmp(["ACTION_890_walk_1_step_south_12"]),
        SetWalkingSpeed(SLOW, identifier="ACTION_890_set_animation_speed_11"),
        Walk1StepSouth(identifier="ACTION_890_walk_1_step_south_12"),
        SetWalkingSpeed(VERY_SLOW),
        WalkSouthwestPixels(8),
        JmpIfRandom1of2(["ACTION_890_set_animation_speed_18"]),
        SetWalkingSpeed(NORMAL),
        Jmp(["ACTION_890_walk_1_step_west_19"]),
        SetWalkingSpeed(SLOW, identifier="ACTION_890_set_animation_speed_18"),
        Walk1StepWest(identifier="ACTION_890_walk_1_step_west_19"),
        SetWalkingSpeed(VERY_SLOW),
        WalkSouthwestPixels(8),
        Jmp(["ACTION_890_jmp_if_random_above_128_8"]),
        Pause(1, identifier="ACTION_890_pause_23"),
        JmpIfBitSet(TEMP_7043_2, ["ACTION_890_pause_26"]),
        Jmp(["ACTION_890_pause_23"]),
        Pause(90, identifier="ACTION_890_pause_26"),
        FaceSouthwest(),
        SetSpriteSequence(index=5, is_sequence=True, looping=True),
        JmpIfRandom1of2(
            ["ACTION_890_set_animation_speed_32"],
            identifier="ACTION_890_jmp_if_random_above_128_29",
        ),
        SetWalkingSpeed(NORMAL),
        Jmp(["ACTION_890_walk_1_step_south_33"]),
        SetWalkingSpeed(SLOW, identifier="ACTION_890_set_animation_speed_32"),
        Walk1StepSouth(identifier="ACTION_890_walk_1_step_south_33"),
        SetWalkingSpeed(VERY_SLOW),
        WalkSouthwestPixels(8),
        JmpIfRandom1of2(["ACTION_890_set_animation_speed_39"]),
        SetWalkingSpeed(NORMAL),
        Jmp(["ACTION_890_walk_1_step_west_40"]),
        SetWalkingSpeed(SLOW, identifier="ACTION_890_set_animation_speed_39"),
        Walk1StepWest(identifier="ACTION_890_walk_1_step_west_40"),
        SetWalkingSpeed(VERY_SLOW),
        WalkSouthwestPixels(8),
        Jmp(["ACTION_890_jmp_if_random_above_128_29"]),
    ]
)
