"""A0726_MINES_FIREBALLS"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        VisibilityOff(identifier="ACTION_726_visibility_off_0"),
        ObjectMemorySetBit(arg_1=0x30, bits=[4]),
        ClearSolidityBits(
            bit_4=True, cant_pass_npcs=True, cant_walk_through=True, bit_7=True
        ),
        Pause(23),
        JmpIfRandom1of2(["ACTION_726_visibility_off_0"]),
        Pause(13),
        JmpIfRandom1of2(["ACTION_726_visibility_off_0"]),
        JmpIfBitSet(TEMP_7043_0, ["ACTION_726_visibility_off_0"]),
        Jmp(["ACTION_726_visibility_on_26"]),
        VisibilityOff(identifier="ACTION_726_visibility_off_9"),
        ObjectMemorySetBit(arg_1=0x30, bits=[4]),
        ClearSolidityBits(
            bit_4=True, cant_pass_npcs=True, cant_walk_through=True, bit_7=True
        ),
        TurnRandomDirection(identifier="ACTION_726_turn_random_direction_12"),
        Walk1StepFDirection(),
        Set700CToPressedButton(),
        Mem700CAndConst(0x0003),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 1, ["ACTION_726_pause_21"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 2, ["ACTION_726_pause_22"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 3, ["ACTION_726_pause_23"]),
        TurnRandomDirection(),
        Pause(7),
        Pause(5, identifier="ACTION_726_pause_21"),
        Pause(11, identifier="ACTION_726_pause_22"),
        Pause(13, identifier="ACTION_726_pause_23"),
        JmpIfRandom1of2(["ACTION_726_turn_random_direction_12"]),
        JmpIfBitSet(TEMP_7043_0, ["ACTION_726_visibility_off_9"]),
        VisibilityOn(identifier="ACTION_726_visibility_on_26"),
        PlaySound(sound=SO084_SMOKED, channel=4),
        SetSpriteSequence(index=6, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=2, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=6, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=0, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        StartLoopNTimes(1),
        SetSpriteSequence(index=7, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=8, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=9, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        EndLoop(),
        StartLoopNTimes(1),
        SetSpriteSequence(index=10, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=11, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=12, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        EndLoop(),
        SetSpriteSequence(index=13, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=14, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=15, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        ResetProperties(),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        SetSolidityBits(bit_4=True, cant_walk_through=True),
        SequenceLoopingOn(),
        SequencePlaybackOn(),
        Db(bytearray(b" \x07")),
        Db(bytearray(b")\x00")),
        BPL2627(),
        SetWalkingSpeed(NORMAL),
        VisibilityOn(),
        VisibilityOff(),
        Db(bytearray(b"+\x08 \x80\x00")),
        EmbeddedAnimationRoutine(
            bytearray(b"(\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01\x00\x00\x00\x02\x80")
        ),
        JmpIfBitSet(
            TEMP_7043_0,
            ["ACTION_726_object_memory_set_bit_84"],
            identifier="ACTION_726_jmp_if_bit_set_71"),
        FaceMario(),
        Pause(16),
        Set700CToObjectCoord(
            target_npc=DUMMY_0X07, coord=COORD_Z, pixel=True, bit_7=True
        ),
        CompareVarToConst(PRIMARY_TEMP_700C, 10),
        JmpIfComparisonResultIsGreaterOrEqual(["ACTION_726_object_memory_set_bit_84"]),
        JmpIfRandom1of2(["ACTION_726_jmp_if_bit_set_71"]),
        Pause(16),
        Set700CToObjectCoord(
            target_npc=DUMMY_0X07, coord=COORD_Z, pixel=True, bit_7=True
        ),
        CompareVarToConst(PRIMARY_TEMP_700C, 10),
        JmpIfComparisonResultIsGreaterOrEqual(["ACTION_726_object_memory_set_bit_84"]),
        JmpIfRandom1of2(["ACTION_726_jmp_if_bit_set_71"]),
        BPL262728(),
        ObjectMemorySetBit(
            arg_1=0x30, bits=[4], identifier="ACTION_726_object_memory_set_bit_84"
        ),
        ClearSolidityBits(bit_4=True, cant_walk_through=True),
        SetSpriteSequence(index=13, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=14, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=15, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        StartLoopNTimes(1),
        SetSpriteSequence(index=10, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=11, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=12, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        EndLoop(),
        StartLoopNTimes(1),
        SetSpriteSequence(index=7, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=8, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=9, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        EndLoop(),
        SetSpriteSequence(index=0, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=6, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=2, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        SetSpriteSequence(index=6, is_mold=True, is_sequence=True, looping=True),
        Pause(2),
        Jmp(["ACTION_726_visibility_off_9"]),
    ]
)
