"""A0599_MIDAS_RIVER_MID_LEFT_TUNNEL_PLAYER_OUTER"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        ClearSolidityBits(cant_pass_walls=True),
        ClearBit(TEMP_7043_0),
        SetVarToConst(X_COORD_2, 512),
        SetVarToConst(Y_COORD_2, 6656),
        SetVarToConst(Z_COORD_2, 0),
        TransferTo70167018701A(),
        SetAllSpeeds(NORMAL),
        VisibilityOn(),
        WalkNortheastSteps(4),
        Walk1StepEast(),
        WalkSoutheastSteps(2),
        WalkSouthSteps(2),
        WalkSouthwestSteps(3),
        WalkSouthSteps(2),
        WalkSoutheastSteps(4),
        Walk1StepEast(),
        WalkNortheastSteps(5),
        Walk1StepNorth(),
        WalkNorthwestSteps(4),
        WalkNorthSteps(2),
        WalkNortheastSteps(3),
        WalkSoutheastSteps(5),
        WalkSouthSteps(2),
        Walk1StepSoutheast(),
        Walk1StepEast(),
        WalkNortheastSteps(7),
        WalkSoutheastSteps(8),
        Walk1StepEast(),
        WalkNortheastSteps(2),
        WalkSoutheastSteps(4),
        WalkSouthSteps(3),
        WalkSoutheastSteps(2),
        Walk1StepEast(),
        WalkNortheastSteps(6),
        WalkSoutheastSteps(5),
        WalkSouthSteps(2),
        WalkSouthwestSteps(3),
        Walk1StepSouth(),
        SetBit(TEMP_7043_0),
        Walk1StepSouthwest(),
        Return(),
    ]
)
