"""A0844_VALLEY_5_PIPE_SHY_AWAY"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        SequenceLoopingOn(),
        SetPriority(3),
        ShadowOff(),
        SetWalkingSpeed(SLOW),
        WalkSoutheastSteps(4),
        WalkSoutheastPixels(8),
        ShadowOn(),
        JmpIfObjectNotInSpecificLevel(
            NPC_3,
            R251_BEAN_VALLEY_PIRANHA_PIPE_AREA,
            ["ACTION_844_jmp_if_object_in_level___2"]),
        WalkToXYCoords(x=9, y=29),
        WalkEastPixels(10),
        Pause(32),
        SetSpriteSequence(index=5, is_sequence=True, looping=True, mirror_sprite=True),
        Pause(112),
        SetBit(TEMP_7043_4),
        Pause(32),
        ResetProperties(),
        JmpIfObjectNotInSpecificLevel(
            NPC_4,
            R251_BEAN_VALLEY_PIRANHA_PIPE_AREA,
            ["ACTION_844_jmp_if_object_in_level___3"],
            identifier="ACTION_844_jmp_if_object_in_level___2"),
        WalkToXYCoords(x=8, y=25),
        Pause(32),
        SetSpriteSequence(index=5, is_sequence=True, looping=True),
        Pause(112),
        SetBit(TEMP_7043_0),
        Pause(32),
        ResetProperties(),
        JmpIfObjectNotInSpecificLevel(
            NPC_5,
            R251_BEAN_VALLEY_PIRANHA_PIPE_AREA,
            ["ACTION_844_jmp_if_object_in_level___4"],
            identifier="ACTION_844_jmp_if_object_in_level___3"),
        WalkToXYCoords(x=6, y=29),
        Pause(32),
        SetSpriteSequence(index=5, is_sequence=True, looping=True),
        Pause(112),
        SetBit(TEMP_7043_1),
        Pause(32),
        ResetProperties(),
        JmpIfObjectNotInSpecificLevel(
            NPC_0,
            R251_BEAN_VALLEY_PIRANHA_PIPE_AREA,
            ["ACTION_844_jmp_if_object_in_level___5"],
            identifier="ACTION_844_jmp_if_object_in_level___4"),
        WalkToXYCoords(x=8, y=34),
        Pause(32),
        SetSpriteSequence(index=5, is_sequence=True, looping=True),
        Pause(112),
        SetBit(TEMP_7043_3),
        Pause(32),
        ResetProperties(),
        JmpIfObjectNotInSpecificLevel(
            NPC_1,
            R251_BEAN_VALLEY_PIRANHA_PIPE_AREA,
            ["ACTION_844_walk_to_xy_coords_13"],
            identifier="ACTION_844_jmp_if_object_in_level___5"),
        WalkToXYCoords(x=10, y=35),
        Pause(32),
        SetSpriteSequence(index=5, is_sequence=True, looping=True),
        Pause(112),
        SetBit(TEMP_7043_5),
        Pause(32),
        ResetProperties(),
        WalkToXYCoords(x=7, y=28, identifier="ACTION_844_walk_to_xy_coords_13"),
        WalkSouthwestSteps(4),
        WalkSouthwestPixels(12),
        ShadowOff(),
        WalkSouthwestSteps(14),
        VisibilityOff(),
        Return(),
    ]
)
