"""A0752_STAR_HILL_2ND_ROOM_MUKUMUKU"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        ClearSolidityBits(
            bit_4=True,
            cant_walk_through=True,
            identifier="ACTION_752_clear_solidity_bits_0"),
        SetSpriteSequence(
            index=10, is_mold=True, is_sequence=True, looping=True, mirror_sprite=True
        ),
        Pause(1),
        ShiftToXYCoords(x=13, y=7),
        SetSpriteSequence(index=8, looping=False, mirror_sprite=True),
        Pause(160),
        SetSolidityBits(bit_4=True, cant_walk_through=True),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        Pause(60),
        SetSpriteSequence(index=9, looping=False, mirror_sprite=True),
        Pause(292),
        ShiftToXYCoords(x=0, y=0),
        ObjectMemorySetBit(arg_1=0x30, bits=[4]),
        Pause(48),
        ClearSolidityBits(bit_4=True, cant_walk_through=True),
        SetSpriteSequence(index=10, is_mold=True, is_sequence=True, looping=True),
        Pause(1),
        ShiftToXYCoords(x=23, y=11),
        SetSpriteSequence(index=8, looping=False),
        Pause(160),
        SetSolidityBits(bit_4=True, cant_walk_through=True),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        Pause(60),
        SetSpriteSequence(index=9, looping=False),
        Pause(292),
        ClearSolidityBits(bit_4=True, cant_walk_through=True),
        VisibilityOff(),
        Pause(48),
        SetSpriteSequence(index=10, is_mold=True, is_sequence=True, looping=True),
        Pause(1),
        ShiftToXYCoords(x=9, y=47),
        VisibilityOn(),
        SetSpriteSequence(index=8, looping=False),
        Pause(160),
        SetSolidityBits(bit_4=True, cant_walk_through=True),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        Pause(60),
        SetSpriteSequence(index=9, looping=False),
        Pause(292),
        ClearSolidityBits(bit_4=True, cant_walk_through=True),
        VisibilityOff(),
        Pause(48),
        SetSpriteSequence(
            index=10, is_mold=True, is_sequence=True, looping=True, mirror_sprite=True
        ),
        Pause(1),
        ShiftToXYCoords(x=21, y=31),
        VisibilityOn(),
        SetSpriteSequence(index=8, looping=False, mirror_sprite=True),
        Pause(160),
        SetSolidityBits(bit_4=True, cant_walk_through=True),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        Pause(60),
        SetSpriteSequence(index=9, looping=False, mirror_sprite=True),
        Pause(292),
        ClearSolidityBits(bit_4=True, cant_walk_through=True),
        VisibilityOff(),
        Pause(48),
        SetSpriteSequence(
            index=10, is_mold=True, is_sequence=True, looping=True, mirror_sprite=True
        ),
        Pause(1),
        ShiftToXYCoords(x=9, y=31),
        VisibilityOn(),
        SetSpriteSequence(index=8, looping=False, mirror_sprite=True),
        Pause(160),
        SetSolidityBits(bit_4=True, cant_walk_through=True),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        Pause(60),
        SetSpriteSequence(index=9, looping=False, mirror_sprite=True),
        Pause(292),
        ClearSolidityBits(bit_4=True, cant_walk_through=True),
        VisibilityOff(),
        Pause(48),
        Jmp(["ACTION_752_clear_solidity_bits_0"]),
    ]
)
