"""A0461_FACTORY_SWITCH_ROOM_AMEBOID"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        SetWalkingSpeed(SLOW),
        ShadowOff(),
        SequenceLoopingOn(),
        WalkSouthwestSteps(6),
        WalkSouthwestPixels(10),
        SetSpriteSequence(index=9, is_sequence=True, looping=True),
        FloatingOn(),
        JumpToHeight(0),
        ShadowOn(),
        Pause(24),
        SetWalkingSpeed(NORMAL),
        ResetProperties(),
        WalkToXYCoords(x=22, y=85, identifier="ACTION_461_walk_to_xy_coords_12"),
        SetSpriteSequence(index=9, is_sequence=True, looping=True, mirror_sprite=True),
        Db(bytearray(b" \x07")),
        Db(bytearray(b"$\x00\xfe\x00\x02")),
        Db(bytearray(b"%\xc0\x06\x80\xff")),
        Pause(30),
        BPL262728(),
        ResetProperties(),
        WalkToXYCoords(x=20, y=95),
        SetSpriteSequence(index=9, is_sequence=True, looping=True),
        Db(bytearray(b" \x07")),
        Db(bytearray(b"$\x00\x02 \x00")),
        Db(bytearray(b"%\xc0\x06\x80\xff")),
        Pause(30),
        Db(bytearray(b"$\x00\x02\x80\xfe")),
        Db(bytearray(b"%\xc0\x06\x80\xff")),
        Pause(30),
        BPL262728(),
        ResetProperties(),
        WalkToXYCoords(x=22, y=89),
        SetSpriteSequence(index=9, is_sequence=True, looping=True),
        Db(bytearray(b" \x07")),
        Db(bytearray(b"$\x00\xfe\x00\x00")),
        Db(bytearray(b"%\xc0\x06\x80\xff")),
        Pause(30),
        Db(bytearray(b"$\x00\xfe\x00\x00")),
        Db(bytearray(b"%\xc0\x06\x80\xff")),
        Pause(30),
        Db(bytearray(b"$\x80\xff\x80\x01")),
        Db(bytearray(b"%\xc0\x06\x80\xff")),
        Pause(30),
        BPL262728(),
        ResetProperties(),
        WalkToXYCoords(x=20, y=98),
        SetSpriteSequence(index=9, is_sequence=True, looping=True, mirror_sprite=True),
        Db(bytearray(b" \x07")),
        Db(bytearray(b"$\x00\x02\x00\xff")),
        Db(bytearray(b"%\xc0\x06\x80\xff")),
        Pause(30),
        Db(bytearray(b"$\x00\x02\x00\xff")),
        Db(bytearray(b"%\xc0\x06\x80\xff")),
        Pause(30),
        Db(bytearray(b"$\x90\xff\x00\x01")),
        Db(bytearray(b"%\xc0\x06\x80\xff")),
        Pause(30),
        Db(bytearray(b"$\x00\x00\x00\xfe")),
        Db(bytearray(b"%\xc0\x06\x80\xff")),
        Pause(30),
        BPL262728(),
        ResetProperties(),
        Jmp(["ACTION_461_walk_to_xy_coords_12"]),
    ]
)
