"""A0374_SANCTUARY_HENCHMAN"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        SetWalkingSpeed(FAST),
        SetSequenceSpeed(VERY_FAST),
        SetVarToConst(TEMP_702A, 5),
        FixedFCoordOff(),
        SetBit(TEMP_7044_1),
        JmpIfBitSet(
            TEMP_7044_1,
            ["ACTION_374_jmp_if_random_above_66_13"],
            identifier="ACTION_374_jmp_if_bit_set_5"),
        JmpIfBitSet(TEMP_7044_2, ["ACTION_374_jmp_if_random_above_66_13"]),
        CopyVarToVar(from_var=FACTORY_FALL_3, to_var=PRIMARY_TEMP_700C),
        CompareVarToConst(PRIMARY_TEMP_700C, 5),
        JmpIfComparisonResultIsGreaterOrEqual(["ACTION_374_jmp_to_subroutine_18"]),
        JmpIfRandom1of2(["ACTION_374_jmp_to_subroutine_16"]),
        JmpToSubroutine(["ACTION_374_jmp_if_random_above_128_67"]),
        Jmp(["ACTION_374_jmp_if_bit_set_5"]),
        JmpIfRandom2of3(
            ["ACTION_374_jmp_to_subroutine_16", "ACTION_374_jmp_to_subroutine_18"],
            identifier="ACTION_374_jmp_if_random_above_66_13"),
        JmpToSubroutine(["ACTION_374_jmp_if_bit_set_98"]),
        Jmp(["ACTION_374_jmp_if_bit_set_5"]),
        JmpToSubroutine(
            ["ACTION_374_jmp_if_var_equals_const_20"],
            identifier="ACTION_374_jmp_to_subroutine_16"),
        Jmp(["ACTION_374_jmp_if_bit_set_5"]),
        JmpToSubroutine(
            ["ACTION_374_jmp_if_random_above_128_67"],
            identifier="ACTION_374_jmp_to_subroutine_18"),
        Jmp(["ACTION_374_jmp_if_bit_set_5"]),
        JmpIfVarEqualsConst(
            TEMP_702A,
            4,
            ["ACTION_374_jmp_if_var_equals_const_44"],
            identifier="ACTION_374_jmp_if_var_equals_const_20"),
        JmpIfRandom1of2(["ACTION_374_jmp_if_var_equals_const_44"]),
        JmpIfBitSet(TEMP_7044_2, ["ACTION_374_shift_northeast_steps_35"]),
        JmpIfBitSet(TEMP_7044_1, ["ACTION_374_shift_northeast_steps_35"]),
        JmpIfRandom1of2(["ACTION_374_clear_solidity_bits_29"]),
        TurnRandomDirection(),
        Pause(10),
        TurnRandomDirection(),
        Pause(10),
        ClearSolidityBits(
            cant_walk_through=True, identifier="ACTION_374_clear_solidity_bits_29"
        ),
        ClearSolidityBits(bit_4=True),
        SetObjectMemoryBits(arg_1=0x0B, bits=[0, 1]),
        SetBit(TEMP_7044_7),
        JumpToHeight(height=96, silent=True),
        Inc(FACTORY_FALL_3),
        WalkNortheastSteps(3, identifier="ACTION_374_shift_northeast_steps_35"),
        Dec(TEMP_702A),
        Pause(1, identifier="ACTION_374_pause_37"),
        JmpIfObjectInAir(DUMMY_0X07, ["ACTION_374_pause_37"]),
        ClearBit(TEMP_7044_7),
        SetObjectMemoryBits(arg_1=0x0B, bits=[]),
        SetSolidityBits(cant_walk_through=True),
        SetSolidityBits(bit_4=True),
        Return(),
        JmpIfVarEqualsConst(
            TEMP_702A,
            7,
            ["ACTION_374_jmp_if_var_equals_const_20"],
            identifier="ACTION_374_jmp_if_var_equals_const_44"),
        JmpIfBitSet(TEMP_7044_2, ["ACTION_374_shift_southwest_steps_58"]),
        JmpIfBitSet(TEMP_7044_1, ["ACTION_374_shift_southwest_steps_58"]),
        JmpIfRandom1of2(["ACTION_374_clear_solidity_bits_52"]),
        TurnRandomDirection(),
        Pause(10),
        TurnRandomDirection(),
        Pause(10),
        ClearSolidityBits(
            cant_walk_through=True, identifier="ACTION_374_clear_solidity_bits_52"
        ),
        ClearSolidityBits(bit_4=True),
        SetObjectMemoryBits(arg_1=0x0B, bits=[0, 1]),
        SetBit(TEMP_7044_7),
        JumpToHeight(height=96, silent=True),
        Inc(FACTORY_FALL_3),
        WalkSouthwestSteps(3, identifier="ACTION_374_shift_southwest_steps_58"),
        Inc(TEMP_702A),
        Pause(1, identifier="ACTION_374_pause_60"),
        JmpIfObjectInAir(DUMMY_0X07, ["ACTION_374_pause_60"]),
        ClearBit(TEMP_7044_7),
        SetObjectMemoryBits(arg_1=0x0B, bits=[]),
        SetSolidityBits(cant_walk_through=True),
        SetSolidityBits(bit_4=True),
        Return(),
        JmpIfRandom1of2(
            ["ACTION_374_jmp_if_bit_set_83"],
            identifier="ACTION_374_jmp_if_random_above_128_67"),
        JmpIfBitSet(TEMP_7044_2, ["ACTION_374_clear_bit_76"]),
        JmpIfBitSet(TEMP_7044_4, ["ACTION_374_ret_82"]),
        JmpIfBitSet(TEMP_7044_1, ["ACTION_374_jmp_if_bit_set_98"]),
        SetBit(TEMP_7044_1),
        ClearBit(TEMP_7044_2),
        ClearBit(TEMP_7044_3),
        ClearBit(TEMP_7044_4),
        Jmp(["ACTION_374_shift_southeast_steps_80"]),
        ClearBit(TEMP_7044_1, identifier="ACTION_374_clear_bit_76"),
        ClearBit(TEMP_7044_2),
        ClearBit(TEMP_7044_3),
        SetBit(TEMP_7044_4),
        WalkSoutheastSteps(4, identifier="ACTION_374_shift_southeast_steps_80"),
        SetVarToConst(FACTORY_FALL_3, 0),
        Return(identifier="ACTION_374_ret_82"),
        JmpIfBitSet(
            TEMP_7044_4,
            ["ACTION_374_clear_bit_91"],
            identifier="ACTION_374_jmp_if_bit_set_83"),
        JmpIfBitSet(TEMP_7044_3, ["ACTION_374_ret_97"]),
        JmpIfBitSet(TEMP_7044_2, ["ACTION_374_jmp_if_bit_set_98"]),
        ClearBit(TEMP_7044_1),
        ClearBit(TEMP_7044_2),
        SetBit(TEMP_7044_3),
        ClearBit(TEMP_7044_4),
        Jmp(["ACTION_374_shift_northwest_steps_95"]),
        ClearBit(TEMP_7044_1, identifier="ACTION_374_clear_bit_91"),
        SetBit(TEMP_7044_2),
        ClearBit(TEMP_7044_3),
        ClearBit(TEMP_7044_4),
        WalkNorthwestSteps(4, identifier="ACTION_374_shift_northwest_steps_95"),
        SetVarToConst(FACTORY_FALL_3, 0),
        Return(identifier="ACTION_374_ret_97"),
        JmpIfBitSet(
            TEMP_7044_2,
            ["ACTION_374_set_bit_105"],
            identifier="ACTION_374_jmp_if_bit_set_98"),
        ClearBit(TEMP_7044_1),
        SetBit(TEMP_7044_2),
        ClearBit(TEMP_7044_3),
        ClearBit(TEMP_7044_4),
        Walk1StepSoutheast(),
        Return(),
        SetBit(TEMP_7044_1, identifier="ACTION_374_set_bit_105"),
        ClearBit(TEMP_7044_2),
        ClearBit(TEMP_7044_3),
        ClearBit(TEMP_7044_4),
        Walk1StepNorthwest(),
        Return(),
    ]
)
