#A0317_COIN_SNAKE_HEAD_BASE

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	SetSolidityBits(bit_0=True, cant_pass_walls=True, identifier="ACTION_317_set_solidity_bits_0"),
	SetVarToConst(TEMP_70AE, 21),
	Walk1StepNorthwest(),
	AddZCoord1Step(),
	ShiftNorthwestSteps(2),
	Inc(TEMP_70AE),
	Walk1StepSouthwest(),
	DecZCoord1Step(),
	Walk1StepSouthwest(),
	Inc(TEMP_70AE),
	Walk1StepSouthwest(),
	DecZCoord1Step(),
	Walk1StepSouthwest(),
	Inc(TEMP_70AE),
	ShiftSouthwestSteps(2),
	ShiftNorthwestSteps(2),
	ShiftZUpSteps(3),
	ShiftNorthwestSteps(2),
	Inc(TEMP_70AE),
	ShiftSouthwestSteps(4),
	Inc(TEMP_70AE),
	ShiftSouthwestSteps(2),
	ShiftZDownSteps(2),
	Inc(TEMP_70AE),
	ShiftSouthwestSteps(2),
	AddZCoord1Step(),
	Walk1StepSouthwest(),
	Inc(TEMP_70AE),
	Walk1StepSoutheast(),
	DecZCoord1Step(),
	ShiftSoutheastSteps(2),
	Inc(TEMP_70AE),
	ShiftSoutheastSteps(2),
	DecZCoord1Step(),
	Walk1StepSoutheast(),
	Inc(TEMP_70AE),
	Walk1StepSoutheast(),
	AddZCoord1Step(),
	ShiftNortheastSteps(2),
	Inc(TEMP_70AE),
	ShiftNortheastSteps(2),
	ShiftZUpSteps(2),
	Walk1StepNortheast(),
	Inc(TEMP_70AE),
	ShiftNortheastSteps(2),
	Inc(TEMP_70AE),
	Walk1StepNortheast(),
	Walk1StepSoutheast(),
	DecZCoord1Step(),
	Inc(TEMP_70AE),
	ShiftSoutheastSteps(2),
	AddZCoord1Step(),
	Walk1StepSoutheast(),
	Inc(TEMP_70AE),
	Walk1StepNortheast(),
	ShiftZDownSteps(2),
	ShiftNortheastSteps(2),
	Inc(TEMP_70AE),
	VisibilityOff(),
	ObjectMemorySetBit(arg_1=0x30, bits=[4]),
	Return()
])
