#A0825_MACHINE_YARID

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	Set700CToCurrentLevel(),
	JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 474, ["ACTION_825_set_700C_to_pressed_button_30"]),
	SetSequenceSpeed(FAST, identifier="ACTION_825_set_animation_speed_2"),
	VisibilityOff(),
	FloatingOff(),
	TransferToXYZF(x=22, y=54, z=18, direction=EAST),
	SequencePlaybackOff(),
	Pause(40),
	JumpToHeight(96),
	Pause(20),
	SetSolidityBits(cant_pass_walls=True),
	VisibilityOn(),
	FloatingOn(),
	ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
	Pause(1, identifier="ACTION_825_pause_14"),
	JmpIfObjectInAir(NPC_0, ["ACTION_825_pause_14"]),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	SequencePlaybackOn(),
	SetSpriteSequence(index=0, is_sequence=True, looping=False, mirror_sprite=True),
	Pause(8),
	JumpToHeight(160),
	SetWalkingSpeed(FAST),
	ShiftSoutheastSteps(5),
	Pause(1, identifier="ACTION_825_pause_23"),
	JmpIfObjectInAir(NPC_0, ["ACTION_825_pause_23"]),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	JumpToHeight(96),
	ClearSolidityBits(cant_pass_walls=True),
	ShiftSoutheastSteps(3),
	Jmp(["ACTION_825_set_animation_speed_2"]),
	Set700CToPressedButton(identifier="ACTION_825_set_700C_to_pressed_button_30"),
	JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 24, ["ACTION_825_visibility_off_69"]),
	CompareVarToConst(PRIMARY_TEMP_700C, 21),
	JmpIfComparisonResultIsGreaterOrEqual(["ACTION_825_set_700C_to_pressed_button_53"]),
	Pause(1, identifier="ACTION_825_pause_34"),
	JmpIfBitClear(TEMP_7043_0, ["ACTION_825_pause_34"]),
	Pause(1, identifier="ACTION_825_pause_36"),
	JmpIfObjectInAir(NPC_4, ["ACTION_825_pause_36"]),
	SetWalkingSpeed(SLOW),
	ShiftZDownPixels(3),
	SetWalkingSpeed(NORMAL),
	ShiftZDownPixels(1),
	SetWalkingSpeed(SLOW),
	ShiftZDownPixels(4),
	SetWalkingSpeed(VERY_SLOW),
	ShiftZDownPixels(2),
	Pause(2),
	SetWalkingSpeed(SLOW),
	ShiftZDownPixels(1),
	Pause(35),
	SetWalkingSpeed(FASTEST),
	ShiftZUpPixels(11),
	Jmp(["ACTION_825_pause_34"]),
	Set700CToPressedButton(identifier="ACTION_825_set_700C_to_pressed_button_53"),
	AddConstToVar(PRIMARY_TEMP_700C, 65517),
	LoadMemory(PRIMARY_TEMP_700C),
	Pause(4),
	EndLoop(),
	SetPriority(3),
	SetAllSpeeds(SLOW),
	TurnClockwise45Degrees(identifier="ACTION_825_turn_clockwise_45_degrees_60"),
	ShiftFDirectionSteps(2),
	StartLoopNTimes(3),
	TurnClockwise45DegreesNTimes(2),
	Pause(15),
	EndLoop(),
	TurnRandomDirection(),
	Walk1StepFDirection(),
	Jmp(["ACTION_825_turn_clockwise_45_degrees_60"]),
	VisibilityOff(identifier="ACTION_825_visibility_off_69"),
	FloatingOff(),
	TransferToXYZF(x=20, y=31, z=2, direction=SOUTHEAST),
	SetSpriteSequence(index=0, is_sequence=True, looping=False, mirror_sprite=True),
	SequencePlaybackOff(),
	SetSolidityBits(cant_pass_walls=True),
	SetSolidityBits(cant_pass_npcs=True, bit_7=True),
	JmpIfBitClear(UNKNOWN_DIRECTIONAL_BIT_2, ["ACTION_825_jump_to_height_78"]),
	Pause(130),
	JumpToHeight(96, identifier="ACTION_825_jump_to_height_78"),
	Pause(20),
	VisibilityOn(),
	FloatingOn(),
	ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
	SetBit(TEMP_7043_0),
	Pause(1, identifier="ACTION_825_pause_84"),
	JmpIfObjectInAir(NPC_4, ["ACTION_825_pause_84"]),
	ClearBit(TEMP_7043_0),
	JmpIfBitSet(UNKNOWN_DIRECTIONAL_BIT_2, ["ACTION_825_visibility_off_69"]),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	SequencePlaybackOn(),
	SetSpriteSequence(index=0, is_sequence=True, looping=False, mirror_sprite=True),
	Pause(60),
	ObjectMemorySetBit(arg_1=0x30, bits=[4]),
	PlaySound(sound=SO010_TRAMPOLINE, channel=4),
	JumpToHeight(160),
	ClearSolidityBits(cant_pass_npcs=True, bit_7=True),
	SetWalkingSpeed(FAST),
	ShiftSoutheastSteps(5),
	Pause(1, identifier="ACTION_825_pause_98"),
	JmpIfObjectInAir(NPC_4, ["ACTION_825_pause_98"]),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	JumpToHeight(96),
	ClearSolidityBits(cant_pass_walls=True),
	ShiftSoutheastSteps(3),
	Jmp(["ACTION_825_visibility_off_69"])
])
