#A0457_FACTORY_SWITCH_ROOM_AMEBOID

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	SetWalkingSpeed(SLOW),
	ShadowOff(),
	SequenceLoopingOn(),
	ShiftSouthwestSteps(2),
	ShiftSouthwestPixels(10),
	SetSpriteSequence(index=9, is_sequence=True, looping=True),
	FloatingOn(),
	JumpToHeight(0),
	ShadowOn(),
	Pause(24),
	SetWalkingSpeed(NORMAL),
	Db(bytearray(b' \x07')),
	Db(bytearray(b'$\x00\x00\x80\x01')),
	Db(bytearray(b'%\xc0\x06\x80\xff')),
	Pause(30),
	Db(bytearray(b'$\x80\xfe\x00\x00'), identifier="ACTION_457_db_15"),
	Db(bytearray(b'%\xc0\x06\x80\xff')),
	Pause(30),
	Db(bytearray(b'$\x00\xff\x00\x01')),
	Db(bytearray(b'%\xc0\x06\x80\xff')),
	Pause(30),
	BPL262728(),
	Pause(16),
	ResetProperties(),
	Pause(16),
	WalkToXYCoords(x=20, y=95),
	SetSpriteSequence(index=9, is_sequence=True, looping=True, mirror_sprite=True),
	Db(bytearray(b' \x07')),
	Db(bytearray(b'$0\x01\x00\x00')),
	Db(bytearray(b'%\xc0\x06\x80\xff')),
	Pause(30),
	Db(bytearray(b'$\x00\x01\x00\xff')),
	Db(bytearray(b'%\xc0\x06\x80\xff')),
	Pause(30),
	BPL262728(),
	Pause(16),
	ResetProperties(),
	Pause(16),
	WalkToXYCoords(x=21, y=88),
	SetSpriteSequence(index=9, is_sequence=True, looping=True),
	Db(bytearray(b' \x07')),
	Jmp(["ACTION_457_db_15"])
])
