#A0133_MK_OCCUPIED_EXTERIOR_REPEATING_HENCHMEN

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	BPL262728(),
	TransferToXYZF(x=13, y=81, z=18, direction=EAST),
	Walk1StepSouthwest(),
	VisibilityOn(),
	ShiftSouthwestPixels(12),
	SetSolidityBits(bit_4=True),
	SetSolidityBits(cant_walk_through=True),
	SetSolidityBits(cant_pass_walls=True),
	StartLoopNTimes(5),
	Db(bytearray(b' \x04')),
	Db(bytearray(b'%\xc0\x06\x80\xff')),
	Walk1StepSouthwest(),
	ShiftSouthwestPixels(14),
	Pause(2),
	BPL262728(),
	EndLoop(),
	ClearSolidityBits(cant_pass_walls=True),
	JmpToSubroutine(["ACTION_105_set_animation_speed_0"]),
	JmpToSubroutine(["ACTION_104_set_animation_speed_0"]),
	JmpToSubroutine(["ACTION_104_set_animation_speed_0"]),
	SetSolidityBits(cant_pass_walls=True),
	StartLoopNTimes(1),
	Db(bytearray(b' \x04')),
	Db(bytearray(b'%\xc0\x06\x80\xff')),
	Walk1StepSouthwest(),
	ShiftSouthwestPixels(14),
	Pause(2),
	BPL262728(),
	EndLoop(),
	ClearSolidityBits(cant_pass_walls=True),
	JmpToSubroutine(["ACTION_104_set_animation_speed_0"]),
	JmpToSubroutine(["ACTION_104_set_animation_speed_0"]),
	Pause(20),
	VisibilityOff(),
	ClearSolidityBits(bit_4=True),
	ClearSolidityBits(cant_walk_through=True),
	Return()
])
