#A0257_NIMBUS_PINWHEEL_LEFT

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	SequenceLoopingOn(),
	SetSequenceSpeed(SLOW),
	Set700CToCurrentLevel(),
	JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 117, ["ACTION_257_set_bit_55"]),
	Jmp(["ACTION_257_set_bit_8"]),
	Pause(1, identifier="ACTION_257_pause_5"),
	JmpIfBitClear(TEMP_7043_1, ["ACTION_257_set_bit_8"]),
	Jmp(["ACTION_257_pause_5"]),
	SetBit(TEMP_7043_2, identifier="ACTION_257_set_bit_8"),
	Pause(180),
	SetWalkingSpeed(SLOW),
	AddZCoord1Step(),
	SetSequenceSpeed(NORMAL),
	SetSpriteSequence(index=4, is_sequence=True, looping=True),
	Pause(14),
	SetSpriteSequence(index=5, is_sequence=True, looping=True),
	SetWalkingSpeed(SLOW),
	ShiftSouthwestPixels(8, identifier="ACTION_257_shift_southwest_pixels_17"),
	SetWalkingSpeed(NORMAL),
	Walk1StepSouthwest(),
	SetWalkingSpeed(FAST),
	ShiftSouthwestSteps(1),
	SetWalkingSpeed(VERY_FAST),
	ShiftSouthwestSteps(5),
	SetWalkingSpeed(FAST),
	ShiftSouthwestSteps(1),
	SetWalkingSpeed(NORMAL),
	Walk1StepSouthwest(),
	SetWalkingSpeed(SLOW),
	ShiftSouthwestPixels(8),
	ShiftNortheastPixels(8),
	SetWalkingSpeed(NORMAL),
	Walk1StepNortheast(),
	SetWalkingSpeed(FAST),
	ShiftNortheastSteps(1),
	SetWalkingSpeed(VERY_FAST),
	ShiftNortheastSteps(5),
	SetWalkingSpeed(FAST),
	ShiftNortheastSteps(1),
	SetWalkingSpeed(NORMAL),
	Walk1StepNortheast(),
	SetWalkingSpeed(SLOW),
	ShiftNortheastPixels(8),
	JmpIfBitSet(TEMP_7043_1, ["ACTION_257_set_sprite_sequence_45"]),
	Jmp(["ACTION_257_shift_southwest_pixels_17"]),
	SetSpriteSequence(index=14, is_mold=True, is_sequence=True, looping=True, identifier="ACTION_257_set_sprite_sequence_45"),
	Pause(6),
	SetSpriteSequence(index=0, is_sequence=True, looping=True),
	SetSequenceSpeed(SLOW),
	DecZCoord1Step(),
	SetBit(TEMP_7043_3),
	Jmp(["ACTION_257_pause_5"]),
	Pause(1, identifier="ACTION_257_pause_52"),
	JmpIfBitClear(TEMP_7043_1, ["ACTION_257_set_bit_55"]),
	Jmp(["ACTION_257_pause_52"]),
	SetBit(TEMP_7043_2, identifier="ACTION_257_set_bit_55"),
	Pause(180),
	SetWalkingSpeed(SLOW),
	ShiftZUpPixels(8),
	SetSequenceSpeed(NORMAL),
	SetSpriteSequence(index=4, is_sequence=True, looping=True),
	Pause(14),
	SetSpriteSequence(index=5, is_sequence=True, looping=True),
	SetWalkingSpeed(SLOW),
	ShiftSouthPixels(8),
	SetWalkingSpeed(NORMAL),
	ShiftSouthPixels(8),
	SetWalkingSpeed(FAST),
	ShiftSouthwestPixels(8),
	SetWalkingSpeed(VERY_FAST),
	ShiftSouthwestSteps(3),
	SetWalkingSpeed(FAST),
	ShiftSouthwestPixels(8),
	SetWalkingSpeed(NORMAL),
	ShiftSouthwestPixels(4),
	SetWalkingSpeed(SLOW),
	ShiftSouthwestPixels(2),
	ShiftNortheastPixels(2, identifier="ACTION_257_shift_northeast_pixels_77"),
	SetWalkingSpeed(NORMAL),
	ShiftNortheastPixels(4),
	SetWalkingSpeed(FAST),
	ShiftNortheastPixels(8),
	SetWalkingSpeed(VERY_FAST),
	ShiftNortheastSteps(2),
	SetWalkingSpeed(FAST),
	ShiftNortheastPixels(8),
	SetWalkingSpeed(NORMAL),
	ShiftNortheastPixels(4),
	SetWalkingSpeed(SLOW),
	ShiftNortheastPixels(2),
	JmpIfBitSet(TEMP_7043_1, ["ACTION_257_shift_northeast_pixels_105"]),
	ShiftSouthwestPixels(2),
	SetWalkingSpeed(NORMAL),
	ShiftSouthwestPixels(4),
	SetWalkingSpeed(FAST),
	ShiftSouthwestPixels(8),
	SetWalkingSpeed(VERY_FAST),
	ShiftSouthwestSteps(2),
	SetWalkingSpeed(FAST),
	ShiftSouthwestPixels(8),
	SetWalkingSpeed(NORMAL),
	ShiftSouthwestPixels(4),
	SetWalkingSpeed(SLOW),
	ShiftSouthwestPixels(2),
	Jmp(["ACTION_257_shift_northeast_pixels_77"]),
	ShiftNortheastPixels(10, identifier="ACTION_257_shift_northeast_pixels_105"),
	Walk1StepNorth(),
	SetSpriteSequence(index=14, is_mold=True, is_sequence=True, looping=True),
	Pause(6),
	SetSpriteSequence(index=0, is_sequence=True, looping=True),
	SetSequenceSpeed(SLOW),
	ShiftZDownPixels(8),
	SetBit(TEMP_7043_3),
	Jmp(["ACTION_257_pause_52"])
])
