#A0672_ROSE_TOWN_LIBERATED_WATER_KID

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	JmpToSubroutine(["ACTION_672_visibility_off_10"]),
	ShiftSouthwestSteps(1),
	ShiftNorthwestSteps(1),
	FaceSoutheast(),
	SequenceLoopingOff(),
	Pause(160),
	ShiftSoutheastSteps(1),
	ShiftNortheastSteps(1),
	JmpToSubroutine(["ACTION_672_shift_northeast_steps_26"]),
	Return(),
	VisibilityOff(identifier="ACTION_672_visibility_off_10"),
	TransferToXYZF(x=15, y=55, z=2, direction=EAST),
	FaceSoutheast(),
	SetWalkingSpeed(SLOW),
	SetSequenceSpeed(FAST),
	VisibilityOn(),
	Walk1StepSoutheast(),
	SetSolidityBits(cant_walk_through=True),
	ShiftSoutheastSteps(4),
	SetSolidityBits(cant_pass_walls=True),
	FloatingOn(),
	ShiftSouthwestSteps(2),
	ClearSolidityBits(cant_pass_walls=True),
	FloatingOff(),
	ShiftSouthwestSteps(2),
	Return(),
	ShiftNortheastSteps(2, identifier="ACTION_672_shift_northeast_steps_26"),
	ShiftNortheastPixels(8),
	SetSolidityBits(cant_pass_walls=True),
	FloatingOn(),
	ShiftNortheastSteps(1),
	ClearSolidityBits(cant_pass_walls=True),
	FloatingOff(),
	ShiftNortheastPixels(8),
	ShiftNorthwestSteps(4),
	ClearSolidityBits(bit_4=True, cant_pass_npcs=True, cant_walk_through=True, bit_7=True),
	Walk1StepNorthwest(),
	VisibilityOff(),
	TransferToXYZF(x=16, y=85, z=0, direction=EAST),
	Return()
])
