#A0109_MK_HALL_REPEATING_HENCHMEN_STARTING

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	SetPriority(3),
	ClearSolidityBits(bit_4=True, cant_pass_npcs=True, cant_walk_through=True, bit_7=True),
	SetWalkingSpeed(FASTEST),
	ShiftZUpPixels(20),
	SetWalkingSpeed(VERY_FAST),
	ShiftZUpPixels(10),
	SetWalkingSpeed(FAST),
	ShiftZUpPixels(4),
	SetWalkingSpeed(NORMAL),
	ShiftZUpPixels(2),
	SetWalkingSpeed(SLOW),
	ShiftZUpPixels(1),
	SetWalkingSpeed(VERY_SLOW),
	ShiftZUpPixels(1),
	SetWalkingSpeed(VERY_SLOW),
	ShiftZDownPixels(1),
	SetWalkingSpeed(SLOW),
	ShiftZDownPixels(1),
	SetWalkingSpeed(NORMAL),
	ShiftZDownPixels(2),
	SetWalkingSpeed(FAST),
	ShiftZDownPixels(4),
	SetWalkingSpeed(VERY_FAST),
	ShiftZDownPixels(10),
	SetWalkingSpeed(FASTEST),
	ShiftZDownPixels(20),
	Pause(2),
	SetSolidityBits(bit_4=True, cant_pass_npcs=True, cant_walk_through=True, bit_7=True),
	SetWalkingSpeed(FASTEST, identifier="ACTION_109_set_animation_speed_28"),
	ShiftZUpPixels(20),
	SetWalkingSpeed(VERY_FAST),
	ShiftZUpPixels(10),
	SetWalkingSpeed(FAST),
	ShiftZUpPixels(4),
	SetWalkingSpeed(NORMAL),
	ShiftZUpPixels(2),
	SetWalkingSpeed(SLOW),
	ShiftZUpPixels(1),
	SetWalkingSpeed(VERY_SLOW),
	ShiftZUpPixels(1),
	SetWalkingSpeed(VERY_SLOW),
	ShiftZDownPixels(1),
	SetWalkingSpeed(SLOW),
	ShiftZDownPixels(1),
	SetWalkingSpeed(NORMAL),
	ShiftZDownPixels(2),
	SetWalkingSpeed(FAST),
	ShiftZDownPixels(4),
	SetWalkingSpeed(VERY_FAST),
	ShiftZDownPixels(10),
	SetWalkingSpeed(FASTEST),
	ShiftZDownPixels(20),
	Pause(2),
	Jmp(["ACTION_109_set_animation_speed_28"])
])
