"""A0372_SANCTUARY_HENCHMAN"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        SetSequenceSpeed(VERY_FAST),
        SetWalkingSpeed(FAST),
        SetVarToConst(TEMP_7026, 3),
        SetBit(TEMP_7043_1),
        JmpIfBitSet(
            TEMP_7043_1,
            ["ACTION_372_jmp_if_random_above_66_12"],
            identifier="ACTION_372_jmp_if_bit_set_4",
        ),
        JmpIfBitSet(TEMP_7043_2, ["ACTION_372_jmp_if_random_above_66_12"]),
        CopyVarToVar(from_var=FACTORY_FALL_1, to_var=PRIMARY_TEMP_700C),
        CompareVarToConst(PRIMARY_TEMP_700C, 5),
        JmpIfComparisonResultIsGreaterOrEqual(["ACTION_372_jmp_to_subroutine_17"]),
        JmpIfRandom1of2(["ACTION_372_jmp_to_subroutine_15"]),
        JmpToSubroutine(["ACTION_372_jmp_if_random_above_128_66"]),
        Jmp(["ACTION_372_jmp_if_bit_set_4"]),
        JmpIfRandom2of3(
            ["ACTION_372_jmp_to_subroutine_15", "ACTION_372_jmp_to_subroutine_17"],
            identifier="ACTION_372_jmp_if_random_above_66_12",
        ),
        JmpToSubroutine(["ACTION_372_jmp_if_bit_set_97"]),
        Jmp(["ACTION_372_jmp_if_bit_set_4"]),
        JmpToSubroutine(
            ["ACTION_372_jmp_if_var_equals_const_19"],
            identifier="ACTION_372_jmp_to_subroutine_15",
        ),
        Jmp(["ACTION_372_jmp_if_bit_set_4"]),
        JmpToSubroutine(
            ["ACTION_372_jmp_if_random_above_128_66"],
            identifier="ACTION_372_jmp_to_subroutine_17",
        ),
        Jmp(["ACTION_372_jmp_if_bit_set_4"]),
        JmpIfVarEqualsConst(
            TEMP_7026,
            2,
            ["ACTION_372_jmp_if_var_equals_const_43"],
            identifier="ACTION_372_jmp_if_var_equals_const_19",
        ),
        JmpIfRandom1of2(["ACTION_372_jmp_if_var_equals_const_43"]),
        JmpIfBitSet(TEMP_7043_2, ["ACTION_372_shift_northeast_steps_34"]),
        JmpIfBitSet(TEMP_7043_1, ["ACTION_372_shift_northeast_steps_34"]),
        JmpIfRandom1of2(["ACTION_372_clear_solidity_bits_28"]),
        TurnRandomDirection(),
        Pause(10),
        TurnRandomDirection(),
        Pause(10),
        ClearSolidityBits(
            cant_walk_through=True, identifier="ACTION_372_clear_solidity_bits_28"
        ),
        ClearSolidityBits(bit_4=True),
        SetObjectMemoryBits(arg_1=0x0B, bits=[0, 1]),
        SetBit(TEMP_7044_5),
        JumpToHeight(height=96, silent=True),
        Inc(FACTORY_FALL_1),
        WalkNortheastSteps(3, identifier="ACTION_372_shift_northeast_steps_34"),
        Dec(TEMP_7026),
        Pause(1, identifier="ACTION_372_pause_36"),
        JmpIfObjectInAir(DUMMY_0X07, ["ACTION_372_pause_36"]),
        ClearBit(TEMP_7044_5),
        SetObjectMemoryBits(arg_1=0x0B, bits=[]),
        SetSolidityBits(cant_walk_through=True),
        SetSolidityBits(bit_4=True),
        Return(),
        JmpIfVarEqualsConst(
            TEMP_7026,
            5,
            ["ACTION_372_jmp_if_var_equals_const_19"],
            identifier="ACTION_372_jmp_if_var_equals_const_43",
        ),
        JmpIfBitSet(TEMP_7043_2, ["ACTION_372_shift_southwest_steps_57"]),
        JmpIfBitSet(TEMP_7043_1, ["ACTION_372_shift_southwest_steps_57"]),
        JmpIfRandom1of2(["ACTION_372_clear_solidity_bits_51"]),
        TurnRandomDirection(),
        Pause(10),
        TurnRandomDirection(),
        Pause(10),
        ClearSolidityBits(
            cant_walk_through=True, identifier="ACTION_372_clear_solidity_bits_51"
        ),
        ClearSolidityBits(bit_4=True),
        SetObjectMemoryBits(arg_1=0x0B, bits=[0, 1]),
        SetBit(TEMP_7044_5),
        JumpToHeight(height=96, silent=True),
        Inc(FACTORY_FALL_1),
        WalkSouthwestSteps(3, identifier="ACTION_372_shift_southwest_steps_57"),
        Inc(TEMP_7026),
        Pause(1, identifier="ACTION_372_pause_59"),
        JmpIfObjectInAir(DUMMY_0X07, ["ACTION_372_pause_59"]),
        ClearBit(TEMP_7044_5),
        SetObjectMemoryBits(arg_1=0x0B, bits=[]),
        SetSolidityBits(cant_walk_through=True),
        SetSolidityBits(bit_4=True),
        Return(),
        JmpIfRandom1of2(
            ["ACTION_372_jmp_if_bit_set_82"],
            identifier="ACTION_372_jmp_if_random_above_128_66",
        ),
        JmpIfBitSet(TEMP_7043_2, ["ACTION_372_clear_bit_75"]),
        JmpIfBitSet(TEMP_7043_4, ["ACTION_372_ret_81"]),
        JmpIfBitSet(TEMP_7043_1, ["ACTION_372_jmp_if_bit_set_97"]),
        SetBit(TEMP_7043_1),
        ClearBit(TEMP_7043_2),
        ClearBit(TEMP_7043_3),
        ClearBit(TEMP_7043_4),
        Jmp(["ACTION_372_shift_southeast_steps_79"]),
        ClearBit(TEMP_7043_1, identifier="ACTION_372_clear_bit_75"),
        ClearBit(TEMP_7043_2),
        ClearBit(TEMP_7043_3),
        SetBit(TEMP_7043_4),
        WalkSoutheastSteps(4, identifier="ACTION_372_shift_southeast_steps_79"),
        SetVarToConst(FACTORY_FALL_1, 0),
        Return(identifier="ACTION_372_ret_81"),
        JmpIfBitSet(
            TEMP_7043_4,
            ["ACTION_372_clear_bit_90"],
            identifier="ACTION_372_jmp_if_bit_set_82",
        ),
        JmpIfBitSet(TEMP_7043_3, ["ACTION_372_ret_96"]),
        JmpIfBitSet(TEMP_7043_2, ["ACTION_372_jmp_if_bit_set_97"]),
        ClearBit(TEMP_7043_1),
        ClearBit(TEMP_7043_2),
        SetBit(TEMP_7043_3),
        ClearBit(TEMP_7043_4),
        Jmp(["ACTION_372_shift_northwest_steps_94"]),
        ClearBit(TEMP_7043_1, identifier="ACTION_372_clear_bit_90"),
        SetBit(TEMP_7043_2),
        ClearBit(TEMP_7043_3),
        ClearBit(TEMP_7043_4),
        WalkNorthwestSteps(4, identifier="ACTION_372_shift_northwest_steps_94"),
        SetVarToConst(FACTORY_FALL_1, 0),
        Return(identifier="ACTION_372_ret_96"),
        JmpIfBitSet(
            TEMP_7043_2,
            ["ACTION_372_set_bit_104"],
            identifier="ACTION_372_jmp_if_bit_set_97",
        ),
        ClearBit(TEMP_7043_1),
        SetBit(TEMP_7043_2),
        ClearBit(TEMP_7043_3),
        ClearBit(TEMP_7043_4),
        Walk1StepSoutheast(),
        Return(),
        SetBit(TEMP_7043_1, identifier="ACTION_372_set_bit_104"),
        ClearBit(TEMP_7043_2),
        ClearBit(TEMP_7043_3),
        ClearBit(TEMP_7043_4),
        Walk1StepNorthwest(),
        Return(),
    ]
)
