"""A0827_ENEMY_ON_SIDEWAYS_CONVEYOR"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        VisibilityOff(),
        SetPriority(3),
        FixedFCoordOn(),
        Set700CToCurrentLevel(),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 473, ["ACTION_827_floating_off_72"]),
        Set700CToPressedButton(),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 29, ["ACTION_827_shadow_off_53"]),
        CompareVarToConst(PRIMARY_TEMP_700C, 24),
        JmpIfComparisonResultIsGreaterOrEqual(
            ["ACTION_827_set_700C_to_pressed_button_33"]
        ),
        Set700CToPressedButton(),
        AddConstToVar(PRIMARY_TEMP_700C, 65517),
        LoadMemory(PRIMARY_TEMP_700C),
        Pause(49),
        EndLoop(),
        Db(bytearray(b"\xfd\x12"), identifier="ACTION_827_db_14"),
        TransferToXYZF(x=1, y=71, z=4, direction=EAST),
        SetWalkingSpeed(NORMAL),
        VisibilityOn(),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        WalkSoutheastSteps(7),
        SetWalkingSpeed(VERY_FAST),
        DecZCoord1Step(),
        SetWalkingSpeed(NORMAL),
        Walk1StepSoutheast(),
        SetWalkingSpeed(VERY_FAST),
        DecZCoord1Step(),
        SetWalkingSpeed(NORMAL),
        WalkSoutheastSteps(2),
        ObjectMemorySetBit(arg_1=0x30, bits=[4]),
        Pause(1),
        VisibilityOff(),
        Pause(49),
        Jmp(["ACTION_827_db_14"]),
        Set700CToPressedButton(identifier="ACTION_827_set_700C_to_pressed_button_33"),
        AddConstToVar(PRIMARY_TEMP_700C, 65513),
        LoadMemory(PRIMARY_TEMP_700C),
        Pause(50),
        EndLoop(),
        Db(bytearray(b"\xfd\x12"), identifier="ACTION_827_db_38"),
        TransferToXYZF(x=7, y=70, z=4, direction=EAST),
        SetWalkingSpeed(NORMAL),
        VisibilityOn(),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        WalkSoutheastSteps(7),
        SetWalkingSpeed(VERY_FAST),
        DecZCoord1Step(),
        SetWalkingSpeed(NORMAL),
        WalkSoutheastSteps(4),
        ObjectMemorySetBit(arg_1=0x30, bits=[4]),
        Pause(1),
        VisibilityOff(),
        Pause(50),
        Jmp(["ACTION_827_db_38"]),
        ShadowOff(identifier="ACTION_827_shadow_off_53"),
        TransferToXYZF(x=11, y=58, z=6, direction=EAST),
        SetWalkingSpeed(NORMAL),
        VisibilityOn(),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        WalkSoutheastSteps(5),
        ShadowOn(),
        WalkSoutheastSteps(2),
        SetWalkingSpeed(VERY_FAST),
        DecZCoord1Step(),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        SetWalkingSpeed(NORMAL),
        ShadowOff(),
        WalkSoutheastSteps(3),
        ObjectMemorySetBit(arg_1=0x30, bits=[4]),
        Pause(1),
        VisibilityOff(),
        Pause(10),
        Jmp(["ACTION_827_shadow_off_53"]),
        FloatingOff(identifier="ACTION_827_floating_off_72"),
        ClearSolidityBits(cant_pass_walls=True),
        JmpIfBitSet(
            TEMP_7044_0,
            ["ACTION_827_jmp_if_bit_clear_100"],
            identifier="ACTION_827_jmp_if_bit_set_74"),
        TransferToXYZF(x=7, y=101, z=28, direction=EAST),
        Pause(50),
        JumpToHeight(96),
        ShadowOn(),
        WalkSoutheastPixels(8),
        Pause(12),
        VisibilityOn(),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        SetSolidityBits(cant_pass_walls=True),
        FloatingOn(),
        Pause(1, identifier="ACTION_827_pause_85"),
        JmpIfObjectInAir(NPC_6, ["ACTION_827_pause_85"]),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        Pause(218),
        JmpIfBitSet(UNKNOWN_704D_0, ["ACTION_827_clear_bit_91"]),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        ClearBit(UNKNOWN_704D_0, identifier="ACTION_827_clear_bit_91"),
        ShadowOff(),
        FloatingOff(),
        ClearSolidityBits(cant_pass_walls=True),
        WalkNorthwestSteps(2),
        ObjectMemorySetBit(arg_1=0x30, bits=[4]),
        Pause(1),
        VisibilityOff(),
        Jmp(["ACTION_827_jmp_if_bit_set_74"]),
        JmpIfBitClear(
            TEMP_7044_0,
            ["ACTION_827_jmp_if_bit_set_74"],
            identifier="ACTION_827_jmp_if_bit_clear_100"),
        TransferToXYZF(x=8, y=58, z=12, direction=SOUTHEAST),
        Pause(30),
        JumpToHeight(96),
        ShadowOn(),
        WalkSoutheastPixels(8),
        Pause(12),
        VisibilityOn(),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        SetSolidityBits(cant_pass_walls=True),
        FloatingOn(),
        Pause(1, identifier="ACTION_827_pause_111"),
        JmpIfObjectInAir(NPC_6, ["ACTION_827_pause_111"]),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        Pause(258),
        JmpIfBitSet(UNKNOWN_704D_0, ["ACTION_827_clear_bit_117"]),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        ClearBit(UNKNOWN_704D_0, identifier="ACTION_827_clear_bit_117"),
        ShadowOff(),
        FloatingOff(),
        ClearSolidityBits(cant_pass_walls=True),
        WalkNorthwestSteps(2),
        ObjectMemorySetBit(arg_1=0x30, bits=[4]),
        Pause(1),
        VisibilityOff(),
        Jmp(["ACTION_827_jmp_if_bit_clear_100"]),
    ]
)
