"""A0050_SEWERS_3RD_WATER_ROOM_RATS"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        ObjectMemorySetBit(arg_1=0x0B, bits=[3]),
        ClearSolidityBits(cant_pass_walls=True, cant_pass_npcs=True, bit_7=True),
        Set700CToPressedButton(),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 21, ["ACTION_50_pause_26"]),
        Pause(4, identifier="ACTION_50_pause_4"),
        Walk1StepNorthwest(),
        Pause(1),
        Walk1StepSouthwest(),
        Pause(1),
        WalkSoutheastSteps(2),
        Pause(1),
        Walk1StepNortheast(),
        Pause(1),
        Inc(TEMP_702C),
        Walk1StepNorthwest(),
        Pause(1),
        WalkSouthwestSteps(2),
        Pause(1),
        Walk1StepNorthwest(),
        Pause(1),
        WalkNortheastSteps(3),
        Pause(1),
        Walk1StepSoutheast(),
        Pause(1),
        Walk1StepSouthwest(),
        Jmp(["ACTION_50_pause_4"]),
        Pause(3, identifier="ACTION_50_pause_26"),
        Walk1StepNorthwest(),
        Pause(1),
        WalkNortheastSteps(2),
        Pause(2),
        Walk1StepSoutheast(),
        WalkSouthwestSteps(3),
        Walk1StepSoutheast(),
        Walk1StepNortheast(),
        Walk1StepNorthwest(),
        JmpIfRandom1of2(["ACTION_50_pause_26"]),
        WalkNortheastSteps(2),
        Walk1StepSoutheast(),
        Pause(3),
        WalkNorthwestSteps(2),
        WalkSouthwestSteps(3),
        Walk1StepSoutheast(),
        Walk1StepNortheast(),
        Jmp(["ACTION_50_pause_26"]),
    ]
)
