#A0750_STAR_HILL_1ST_ROOM_MUKUMUKU

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	Pause(21, identifier="ACTION_750_pause_0"),
	ClearSolidityBits(bit_4=True, cant_walk_through=True),
	SetSpriteSequence(index=10, is_mold=True, is_sequence=True, looping=True),
	Pause(1),
	ShiftToXYCoords(x=12, y=87),
	SetSpriteSequence(index=8, looping=False),
	Pause(160),
	SetSolidityBits(bit_4=True, cant_walk_through=True),
	ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
	Pause(60),
	SetSpriteSequence(index=9, looping=False),
	Pause(292),
	ClearSolidityBits(bit_4=True, cant_walk_through=True),
	ShiftToXYCoords(x=0, y=0),
	ObjectMemorySetBit(arg_1=0x30, bits=[4]),
	Pause(48),
	SetSpriteSequence(index=10, is_mold=True, is_sequence=True, looping=True, mirror_sprite=True),
	Pause(1),
	ShiftToXYCoords(x=8, y=111),
	SetSpriteSequence(index=8, looping=False, mirror_sprite=True),
	Pause(160),
	SetSolidityBits(bit_4=True, cant_walk_through=True),
	ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
	Pause(60),
	SetSpriteSequence(index=9, looping=False, mirror_sprite=True),
	Pause(292),
	ClearSolidityBits(bit_4=True, cant_walk_through=True),
	VisibilityOff(),
	Pause(48),
	SetSpriteSequence(index=10, is_mold=True, is_sequence=True, looping=True, mirror_sprite=True),
	Pause(1),
	ShiftToXYCoords(x=6, y=83),
	VisibilityOn(),
	SetSpriteSequence(index=8, looping=False, mirror_sprite=True),
	Pause(160),
	SetSolidityBits(bit_4=True, cant_walk_through=True),
	ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
	Pause(60),
	SetSpriteSequence(index=9, looping=False, mirror_sprite=True),
	Pause(292),
	ClearSolidityBits(bit_4=True, cant_walk_through=True),
	VisibilityOff(),
	Pause(48),
	SetSpriteSequence(index=10, is_mold=True, is_sequence=True, looping=True),
	Pause(1),
	ShiftToXYCoords(x=12, y=103),
	VisibilityOn(),
	SetSpriteSequence(index=8, looping=False),
	Pause(160),
	SetSolidityBits(bit_4=True, cant_walk_through=True),
	ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
	Pause(60),
	SetSpriteSequence(index=9, looping=False),
	Pause(292),
	ClearSolidityBits(bit_4=True, cant_walk_through=True),
	VisibilityOff(),
	Pause(48),
	SetSpriteSequence(index=10, is_mold=True, is_sequence=True, looping=True),
	Pause(1),
	ShiftToXYCoords(x=2, y=107),
	VisibilityOn(),
	SetSpriteSequence(index=8, looping=False),
	Pause(160),
	SetSolidityBits(bit_4=True, cant_walk_through=True),
	ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
	Pause(60),
	SetSpriteSequence(index=9, looping=False),
	Pause(292),
	ClearSolidityBits(bit_4=True, cant_walk_through=True),
	VisibilityOff(),
	Pause(21),
	Jmp(["ACTION_750_pause_0"])
])
