"""A0169_BANDITS_WAY_GOOMBA"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        SequenceLoopingOn(),
        Set700CToPressedButton(),
        AddConstToVar(PRIMARY_TEMP_700C, 65517),
        LoadMemory(PRIMARY_TEMP_700C),
        Pause(2),
        EndLoop(),
        SetWalkingSpeed(SLOW, identifier="ACTION_169_set_animation_speed_6"),
        SetSequenceSpeed(NORMAL),
        SetSpriteSequence(index=3, is_sequence=True, looping=True),
        Walk1StepSouthwest(),
        Pause(9),
        ResetProperties(),
        Pause(9),
        JmpIfObjectWithinRangeSameZ(
            comparing_npc=MARIO,
            usually=0,
            tiles=6,
            destinations=["ACTION_169_set_animation_speed_39"]),
        StartLoopNTimes(2),
        TurnClockwise45DegreesNTimes(6),
        Walk1StepFDirection(),
        JmpIfObjectWithinRangeSameZ(
            comparing_npc=MARIO,
            usually=0,
            tiles=6,
            destinations=["ACTION_169_set_animation_speed_39"]),
        EndLoop(),
        Pause(15),
        FaceSoutheast(),
        Pause(15),
        JmpIfObjectWithinRangeSameZ(
            comparing_npc=MARIO,
            usually=0,
            tiles=6,
            destinations=["ACTION_169_set_animation_speed_39"]),
        SetSpriteSequence(index=3, is_sequence=True, looping=True, mirror_sprite=True),
        Walk1StepSoutheast(),
        Pause(9),
        ResetProperties(),
        Pause(9),
        JmpIfObjectWithinRangeSameZ(
            comparing_npc=MARIO,
            usually=0,
            tiles=6,
            destinations=["ACTION_169_set_animation_speed_39"]),
        StartLoopNTimes(2),
        TurnClockwise45DegreesNTimes(2),
        Walk1StepFDirection(),
        JmpIfObjectWithinRangeSameZ(
            comparing_npc=MARIO,
            usually=0,
            tiles=6,
            destinations=["ACTION_169_set_animation_speed_39"]),
        EndLoop(),
        Pause(15),
        FaceSouthwest(),
        Pause(15),
        JmpIfObjectWithinRangeSameZ(
            comparing_npc=MARIO,
            usually=0,
            tiles=6,
            destinations=["ACTION_169_set_animation_speed_39"]),
        Jmp(["ACTION_169_set_animation_speed_6"]),
        SetWalkingSpeed(FAST, identifier="ACTION_169_set_animation_speed_39"),
        SetSequenceSpeed(VERY_FAST),
        StartLoopNTimes(1),
        FaceMario(),
        WalkFDirectionSteps(2),
        EndLoop(),
        Jmp(["ACTION_169_set_animation_speed_6"]),
    ]
)
