#A0482_FOREST_PLAYER_FALLS_TO_UNDERGROUND

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	ClearBit(DIRECTIONAL_7047_0),
	Pause(32),
	OverwriteSolidity(),
	SetPriority(3),
	ShadowOff(),
	FaceSouth(),
	JmpIfBitSet(UNKNOWN_7047_4, ["ACTION_482_clear_bit_18"]),
	SetSpriteSequence(index=0, sprite_offset=1, is_mold=True, is_sequence=True, looping=True),
	VisibilityOn(),
	Db(bytearray(b' \x07')),
	Db(bytearray(b'$\x00\x00\xb0\x00')),
	Db(bytearray(b'%\x80\t\x80\xff')),
	Pause(16),
	ShadowOn(),
	Pause(24),
	BPL262728(),
	Db(bytearray(b'\xfd\x9c:')),
	Return(),
	ClearBit(UNKNOWN_7047_4, identifier="ACTION_482_clear_bit_18"),
	FaceSouthwest(),
	SetSpriteSequence(index=0, sprite_offset=3, is_mold=True, is_sequence=True, looping=True),
	VisibilityOn(),
	Db(bytearray(b' \x07')),
	Db(bytearray(b'$\x00\x00\xb0\x00')),
	Db(bytearray(b'%\x80\t\x80\xff')),
	Pause(16),
	ShadowOn(),
	Pause(24),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	Db(bytearray(b'$\x00\x00\x00\x00')),
	Db(bytearray(b'%\xc0\x06\x80\xff')),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	Pause(30),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	Db(bytearray(b'%\x80\x04\x80\xff')),
	Pause(20),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	Db(bytearray(b'%@\x02\x80\xff')),
	Pause(10),
	PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
	BPL262728(),
	Pause(16),
	Jmp(["ACTION_384_sequence_looping_on_0"])
])
