"""A0048_SEWERS_1ST_WATER_ROOM_RAT"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        ObjectMemorySetBit(
            arg_1=0x0B, bits=[3], identifier="ACTION_48_object_memory_set_bit_0"
        ),
        SetAllSpeeds(FAST),
        WalkNortheastSteps(3),
        Pause(8),
        FaceNorthwest(),
        Pause(8),
        FaceSoutheast(),
        Pause(8),
        JmpIfRandom1of2(["ACTION_48_shift_southwest_steps_27"]),
        JumpToHeight(height=108, silent=True),
        WalkNortheastSteps(3),
        Pause(8),
        WalkNortheastSteps(4),
        WalkSoutheastSteps(2),
        WalkSouthwestSteps(2),
        Pause(8),
        Walk1StepNorthwest(),
        WalkSouthwestSteps(4),
        Pause(8),
        JumpToHeight(height=108, silent=True),
        Pause(8),
        WalkSouthwestSteps(4),
        JumpToHeight(height=108, silent=True),
        Pause(12),
        Walk1StepNorthwest(),
        Pause(8),
        Jmp(["ACTION_48_object_memory_set_bit_0"]),
        WalkSouthwestSteps(5, identifier="ACTION_48_shift_southwest_steps_27"),
        Walk1StepSoutheast(),
        Pause(8),
        FaceSouthwest(),
        JumpToHeight(height=108, silent=True),
        Pause(12),
        Walk1StepSouthwest(),
        Pause(8),
        WalkSouthwestSteps(5),
        FaceNorthwest(),
        JumpToHeight(height=108, silent=True),
        Pause(16),
        JmpIfRandom1of2(["ACTION_48_pause_52"]),
        WalkNortheastSteps(3),
        FaceNorthwest(),
        JumpToHeight(height=72, silent=True),
        Pause(8),
        Walk1StepNorthwest(),
        WalkNortheastSteps(4),
        Pause(8),
        JumpToHeight(height=72, silent=True),
        Pause(8),
        Walk1StepNortheast(),
        Pause(8),
        Jmp(["ACTION_48_object_memory_set_bit_0"]),
        Pause(8, identifier="ACTION_48_pause_52"),
        JumpToHeight(height=108, silent=True),
        Pause(16),
        Walk1StepSoutheast(),
        Walk1StepSouthwest(),
        Walk1StepNorthwest(),
        WalkNortheastSteps(2),
        WalkNorthwestSteps(2),
        FaceNortheast(),
        JumpToHeight(height=72, silent=True),
        Pause(8),
        Walk1StepNortheast(),
        Pause(4),
        Walk1StepSoutheast(),
        WalkNortheastSteps(4),
        Pause(8),
        JumpToHeight(height=88, silent=True),
        WalkNortheastSteps(2),
        Pause(8),
        Jmp(["ACTION_48_object_memory_set_bit_0"]),
    ]
)
