"""A0126_CANNON_GECKIT"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        ObjectMemorySetBit(arg_1=0x30, bits=[4]),
        ObjectMemorySetBit(arg_1=0x0B, bits=[3]),
        SequenceLoopingOn(),
        SetPriority(3),
        Pause(1, identifier="ACTION_126_pause_4"),
        Set700CToPressedButton(),
        AddConstToVar(PRIMARY_TEMP_700C, 65511),
        AddConstToVar(PRIMARY_TEMP_700C, 25),
        JmpIfMem704XAt700CBitClear(["ACTION_126_pause_4"]),
        AddConstToVar(PRIMARY_TEMP_700C, 65511),
        Mem700CAndConst(0x0003),
        AddConstToVar(PRIMARY_TEMP_700C, 21),
        CopyVarToVar(from_var=PRIMARY_TEMP_700C, to_var=TEMP_70AA),
        Db(bytearray(b"\x97\x12")),
        JmpIfBitSet(TEMP_7044_1, ["ACTION_126_pause_4"]),
        SetBit(TEMP_7044_1),
        SetAllSpeeds(FASTER),
        PlaySound(sound=SO033_JUMPING_BOUNCING_FISH, channel=4),
        SetVarToConst(TEMP_7034, 61166),
        CreatePacketAtObjectCoords(
            packet=P032_BLUE_CLOUD,
            target_npc=DUMMY_0X07,
            destinations=["ACTION_126_jump_to_height_20"]),
        JumpToHeight(188, identifier="ACTION_126_jump_to_height_20"),
        Pause(1),
        VisibilityOn(),
        ClearBit(TEMP_7044_1),
        WalkNorthwestSteps(6),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        SetSolidityBits(cant_pass_walls=True),
        Pause(1, identifier="ACTION_126_pause_27"),
        JmpIfObjectInAir(DUMMY_0X07, ["ACTION_126_pause_27"]),
        SetAllSpeeds(NORMAL),
        FloatingOff(),
        ClearSolidityBits(cant_pass_walls=True),
        Pause(20),
        StartLoopNTimes(7),
        Walk1StepFDirection(),
        TurnClockwise45DegreesNTimes(2),
        EndLoop(),
        Walk1StepSouthwest(),
        WalkSouthwestPixels(2),
        FloatingOn(),
        SetSolidityBits(cant_pass_walls=True),
        Pause(1, identifier="ACTION_126_pause_41"),
        JmpIfObjectInAir(DUMMY_0X07, ["ACTION_126_pause_41"]),
        FloatingOff(),
        ClearSolidityBits(cant_pass_walls=True),
        Walk1StepSoutheast(),
        FloatingOn(),
        Pause(1, identifier="ACTION_126_pause_47"),
        JmpIfObjectInAir(DUMMY_0X07, ["ACTION_126_pause_47"]),
        WalkSoutheastSteps(4),
        Walk1StepNortheast(),
        WalkNorthwestSteps(3),
        Walk1StepSouthwest(),
        WalkSoutheastSteps(3),
        WalkNortheastPixels(2),
        FixedFCoordOn(),
        Pause(10),
        SetWalkingSpeed(FAST),
        JumpToHeight(108),
        Walk1StepEast(),
        Pause(6),
        SetVRAMPriority(OBJECT_OVERLAPS_MARIO_ON_ALL_SIDES),
        Pause(2),
        SetVRAMPriority(NORMAL_PRIORITY),
        FixedFCoordOff(),
        VisibilityOff(),
        Pause(1, identifier="ACTION_126_pause_66"),
        JmpIfObjectInAir(DUMMY_0X07, ["ACTION_126_pause_66"]),
        Pause(6),
        Jmp(["ACTION_126_pause_4"]),
    ]
)
