"""A0597_MIDAS_FISH"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        SetSpriteSequence(index=0, is_sequence=True, looping=True, mirror_sprite=True),
        ShadowOn(),
        SetVRAMPriority(PRIORITY_3),
        SetPriority(3),
        Db(bytearray(b"\xc8\x00")),
        AddConstToVar(X_COORD_2, 62976),
        AddConstToVar(Y_COORD_2, 1280),
        SetVarToConst(Z_COORD_2, 0),
        TransferTo70167018701A(),
        VisibilityOn(),
        SetWalkingSpeed(FAST),
        SetSequenceSpeed(NORMAL),
        SetSpriteSequence(index=1, is_sequence=True, looping=True),
        WalkNortheastSteps(4),
        PlaySound(sound=SO050_WATER_DROPLET, channel=4),
        Pause(1),
        ResetProperties(),
        FixedFCoordOn(),
        SetWalkingSpeed(FASTEST),
        SetSequenceSpeed(FAST),
        AddZCoord1Step(),
        SetWalkingSpeed(VERY_FAST),
        ShiftZUpPixels(8),
        SetWalkingSpeed(FAST),
        ShiftZUpPixels(4),
        SetWalkingSpeed(NORMAL),
        ShiftZUpPixels(2),
        StartLoopNTimes(1),
        ShiftZDownPixels(2),
        ShiftZUpPixels(2),
        EndLoop(),
        SetWalkingSpeed(FASTEST),
        WalkNortheastPixels(4),
        ShiftZDownPixels(12),
        DecZCoord1Step(),
        VisibilityOff(),
        Return(),
    ]
)
