#A0845_ACTIVATE_PIRANHA_PLANT_IN_PIPE

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	SetSpriteSequence(index=4, is_mold=True, is_sequence=True, looping=True),
	VisibilityOn(),
	Pause(32),
	JmpIfRandom1of2(["ACTION_845_set_sprite_sequence_6"]),
	SetSpriteSequence(index=0, is_mold=True, is_sequence=True, looping=True),
	Jmp(["ACTION_845_pause_7"]),
	Pause(1, identifier="ACTION_845_set_sprite_sequence_6"),
	SetSpriteSequence(index=0, is_mold=True, is_sequence=True, looping=True, mirror_sprite=True),
	Pause(48, identifier="ACTION_845_pause_7"),
	JmpIfRandom1of2(["ACTION_845_start_loop_n_times_22"], identifier="ACTION_845_jmp_if_random_above_128_8"),
	StartLoopNTimes(2),
	SetSpriteSequence(index=0, is_mold=True, is_sequence=True, looping=True),
	Pause(2),
	SetSpriteSequence(index=1, is_mold=True, is_sequence=True, looping=True),
	Pause(4),
	SetSpriteSequence(index=2, is_mold=True, is_sequence=True, looping=True),
	Pause(8),
	SetSpriteSequence(index=1, is_mold=True, is_sequence=True, looping=True),
	Pause(2),
	SetSpriteSequence(index=0, is_mold=True, is_sequence=True, looping=True),
	Pause(4),
	EndLoop(),
	Jmp(["ACTION_845_jmp_if_random_above_128_8"]),
	StartLoopNTimes(2, identifier="ACTION_845_start_loop_n_times_22"),
	SetSpriteSequence(index=0, is_mold=True, is_sequence=True, looping=True, mirror_sprite=True),
	Pause(2),
	SetSpriteSequence(index=1, is_mold=True, is_sequence=True, looping=True, mirror_sprite=True),
	Pause(4),
	SetSpriteSequence(index=2, is_mold=True, is_sequence=True, looping=True, mirror_sprite=True),
	Pause(8),
	SetSpriteSequence(index=1, is_mold=True, is_sequence=True, looping=True, mirror_sprite=True),
	Pause(2),
	SetSpriteSequence(index=0, is_mold=True, is_sequence=True, looping=True, mirror_sprite=True),
	Pause(4),
	EndLoop(),
	Jmp(["ACTION_845_jmp_if_random_above_128_8"])
])
