#A0599_MIDAS_RIVER_MID_LEFT_TUNNEL_PLAYER_OUTER

from randomizer.scripts.action.script_imports import *

script = ActionScript([
	ClearSolidityBits(cant_pass_walls=True),
	ClearBit(TEMP_7043_0),
	SetVarToConst(X_COORD_2, 512),
	SetVarToConst(Y_COORD_2, 6656),
	SetVarToConst(Z_COORD_2, 0),
	TransferTo70167018701A(),
	SetAllSpeeds(NORMAL),
	VisibilityOn(),
	ShiftNortheastSteps(4),
	Walk1StepEast(),
	ShiftSoutheastSteps(2),
	ShiftSouthSteps(2),
	ShiftSouthwestSteps(3),
	ShiftSouthSteps(2),
	ShiftSoutheastSteps(4),
	Walk1StepEast(),
	ShiftNortheastSteps(5),
	Walk1StepNorth(),
	ShiftNorthwestSteps(4),
	ShiftNorthSteps(2),
	ShiftNortheastSteps(3),
	ShiftSoutheastSteps(5),
	ShiftSouthSteps(2),
	Walk1StepSoutheast(),
	Walk1StepEast(),
	ShiftNortheastSteps(7),
	ShiftSoutheastSteps(8),
	Walk1StepEast(),
	ShiftNortheastSteps(2),
	ShiftSoutheastSteps(4),
	ShiftSouthSteps(3),
	ShiftSoutheastSteps(2),
	Walk1StepEast(),
	ShiftNortheastSteps(6),
	ShiftSoutheastSteps(5),
	ShiftSouthSteps(2),
	ShiftSouthwestSteps(3),
	Walk1StepSouth(),
	SetBit(TEMP_7043_0),
	Walk1StepSouthwest(),
	Return()
])
