"""A0162_BOSS_IN_BANDITS_WAY_3"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        JmpIfBitSet(UNKNOWN_7078_1, ["ACTION_162_set_animation_speed_57"]),
        JmpIfBitSet(UNKNOWN_7078_0, ["ACTION_162_set_animation_speed_38"]),
        JmpIfBitSet(UNKNOWN_7077_7, ["ACTION_162_set_animation_speed_18"]),
        VisibilityOn(),
        SetBit(UNKNOWN_7077_7),
        SequenceLoopingOn(),
        SetAllSpeeds(FASTER),
        PlaySound(sound=SO033_JUMPING_BOUNCING_FISH, channel=4),
        JumpToHeight(128),
        WalkToXYCoords(x=20, y=108),
        WalkNorthSteps(7),
        StartLoopNTimes(1),
        WalkNortheastSteps(3),
        SetAllSpeeds(FAST),
        WalkNortheastSteps(2),
        SetAllSpeeds(FASTER),
        EndLoop(),
        WalkNorthwestSteps(2),
        SetAllSpeeds(FASTER, identifier="ACTION_162_set_animation_speed_18"),
        TransferToXYZF(x=24, y=82, z=0, direction=EAST),
        VisibilityOn(),
        FaceSouthwest(),
        Pause(1, identifier="ACTION_162_pause_22"),
        JmpIfObjectWithinRange(
            comparing_npc=MARIO,
            usually=0,
            tiles=4,
            destinations=["ACTION_162_set_bit_25"],
        ),
        Jmp(["ACTION_162_pause_22"]),
        SetBit(UNKNOWN_7078_0, identifier="ACTION_162_set_bit_25"),
        PlaySound(sound=SO033_JUMPING_BOUNCING_FISH, channel=4),
        JumpToHeight(128),
        SetPriority(3),
        WalkToXYCoords(x=29, y=72),
        ObjectMemoryModifyBits(arg_1=0x09, set_bits=[5], clear_bits=[4, 6]),
        SetAllSpeeds(VERY_FAST),
        WalkNorthwestSteps(9),
        SetAllSpeeds(FASTER),
        WalkNorthSteps(5),
        WalkNorthwestSteps(2),
        WalkNorthSteps(3),
        WalkNortheastSteps(2),
        SetAllSpeeds(FAST, identifier="ACTION_162_set_animation_speed_38"),
        TransferToXYZF(x=24, y=43, z=0, direction=EAST),
        VisibilityOn(),
        FaceSouthwest(),
        Pause(1, identifier="ACTION_162_pause_42"),
        JmpIfObjectWithinRange(
            comparing_npc=MARIO,
            usually=0,
            tiles=3,
            destinations=["ACTION_162_set_bit_45"],
        ),
        Jmp(["ACTION_162_pause_42"]),
        SetBit(UNKNOWN_7078_1, identifier="ACTION_162_set_bit_45"),
        PlaySound(sound=SO033_JUMPING_BOUNCING_FISH, channel=4),
        JumpToHeight(128),
        WalkToXYCoords(x=25, y=36),
        SetAllSpeeds(FASTER),
        WalkNorthwestSteps(4),
        SetAllSpeeds(FAST),
        WalkNorthwestSteps(4),
        SetAllSpeeds(FASTER),
        WalkNorthSteps(5),
        SetAllSpeeds(FAST),
        WalkNorthwestSteps(2),
        SetAllSpeeds(FAST, identifier="ACTION_162_set_animation_speed_57"),
        TransferToXYZF(x=20, y=16, z=0, direction=EAST),
        VisibilityOn(),
        FaceSoutheast(),
        Pause(1, identifier="ACTION_162_pause_61"),
        JmpIfObjectWithinRange(
            comparing_npc=MARIO,
            usually=0,
            tiles=4,
            destinations=["ACTION_162_set_bit_64"],
        ),
        Jmp(["ACTION_162_pause_61"]),
        SetBit(BANDITS_WAY_CUTSCENE_3_VIEWED, identifier="ACTION_162_set_bit_64"),
        PlaySound(sound=SO033_JUMPING_BOUNCING_FISH, channel=4),
        JumpToHeight(144),
        WalkNortheastSteps(5),
        VisibilityOff(),
        Return(),
    ]
)
