"""A0664_ROSE_TOWN_OCCUPIED_WATER_GUY"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        TransferToXYZF(x=15, y=55, z=2, direction=EAST),
        SetWalkingSpeed(SLOW),
        SetSequenceSpeed(FAST),
        VisibilityOn(),
        ClearSolidityBits(cant_pass_walls=True),
        ClearSolidityBits(
            bit_4=True, cant_pass_npcs=True, cant_walk_through=True, bit_7=True
        ),
        SetBit(ROSE_TOWN_WATER_PUMPERS_POSITION),
        Walk1StepSoutheast(),
        FaceNorthwest(),
        Pause(60),
        SetSolidityBits(cant_walk_through=True),
        WalkSoutheastSteps(4),
        SetSolidityBits(cant_pass_walls=True),
        FloatingOn(),
        WalkSouthwestSteps(2),
        ClearSolidityBits(cant_pass_walls=True),
        FloatingOff(),
        WalkSouthwestSteps(3),
        FaceNorthwest(),
        Pause(60),
        Walk1StepNortheast(),
        FaceNorthwest(),
        FixedFCoordOn(),
        StartLoopNTimes(2),
        SetWalkingSpeed(FAST),
        ShiftZUpPixels(6),
        SetWalkingSpeed(VERY_SLOW),
        ShiftZDownPixels(6),
        Pause(30),
        EndLoop(),
        FixedFCoordOff(),
        SetWalkingSpeed(SLOW),
        Walk1StepSouthwest(),
        FaceNorthwest(),
        Pause(60),
        SetWalkingSpeed(VERY_SLOW),
        WalkNortheastSteps(3),
        SetSolidityBits(cant_pass_walls=True),
        FloatingOn(),
        WalkNortheastSteps(2),
        ClearSolidityBits(cant_pass_walls=True),
        FloatingOff(),
        WalkNorthwestSteps(4),
        Pause(30),
        ClearBit(ROSE_TOWN_WATER_PUMPERS_POSITION),
        ClearSolidityBits(cant_walk_through=True),
        Walk1StepNorthwest(),
        VisibilityOff(),
        TransferToXYZF(x=22, y=77, z=0, direction=EAST),
        Return(),
    ]
)
