"""A0822_KEEP_JUMPING_TERRAPIN_INIT"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        SetPriority(3),
        ClearSolidityBits(cant_pass_walls=True),
        SetAllSpeeds(NORMAL),
        Set700CToPressedButton(),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 21, ["ACTION_822_pause_119"]),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 22, ["ACTION_822_pause_63"]),
        SetSolidityBits(cant_pass_walls=True),
        FixedFCoordOn(),
        PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
        JumpToHeight(96),
        Walk1StepSoutheast(),
        Pause(8),
        FixedFCoordOff(),
        FaceSouthwest(),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        SetBit(TEMP_7043_1),
        Pause(24),
        Pause(24),
        SetAllSpeeds(FAST),
        PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
        JumpToHeight(105),
        SetSolidityBits(cant_pass_walls=True),
        WalkSoutheastSteps(3),
        Pause(1, identifier="ACTION_822_pause_23"),
        JmpIfObjectInAir(NPC_3, ["ACTION_822_pause_23"]),
        SetBit(TEMP_7043_1),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        ClearSolidityBits(cant_pass_walls=True),
        SetAllSpeeds(NORMAL),
        Walk1StepSoutheast(),
        WalkNortheastSteps(16),
        WalkNortheastSteps(3),
        SetAllSpeeds(FAST),
        PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
        JumpToHeight(105),
        SetSolidityBits(cant_pass_walls=True),
        WalkNortheastSteps(3),
        Pause(1, identifier="ACTION_822_pause_37"),
        JmpIfObjectInAir(NPC_3, ["ACTION_822_pause_37"]),
        SetBit(TEMP_7043_1),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        ClearSolidityBits(cant_pass_walls=True),
        SetAllSpeeds(NORMAL),
        WalkNorthwestSteps(4),
        WalkNorthwestSteps(2),
        WalkNortheastSteps(2),
        WalkNorthwestSteps(3),
        WalkNortheastSteps(5),
        WalkSoutheastSteps(4),
        SetAllSpeeds(FAST),
        PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
        JumpToHeight(105),
        WalkSoutheastSteps(3),
        SetSolidityBits(cant_pass_walls=True),
        Pause(1, identifier="ACTION_822_pause_54"),
        JmpIfObjectInAir(NPC_3, ["ACTION_822_pause_54"]),
        SetBit(TEMP_7043_1),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        ClearSolidityBits(cant_pass_walls=True),
        SetAllSpeeds(NORMAL),
        WalkNortheastSteps(2),
        VisibilityOff(),
        Return(),
        Pause(24, identifier="ACTION_822_pause_63"),
        SetSolidityBits(cant_pass_walls=True),
        FixedFCoordOn(),
        SetAllSpeeds(FAST),
        PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
        JumpToHeight(96),
        WalkNorthwestSteps(2),
        Pause(8),
        FixedFCoordOff(),
        FaceSouthwest(),
        SetAllSpeeds(NORMAL),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        Pause(24),
        WalkNorthwestSteps(2),
        SetAllSpeeds(FAST),
        PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
        JumpToHeight(105),
        WalkNortheastSteps(3),
        SetSolidityBits(cant_pass_walls=True),
        Pause(1, identifier="ACTION_822_pause_82"),
        JmpIfObjectInAir(NPC_2, ["ACTION_822_pause_82"]),
        SetBit(TEMP_7043_1),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        ClearSolidityBits(cant_pass_walls=True),
        SetAllSpeeds(NORMAL),
        WalkNortheastSteps(10),
        SetAllSpeeds(FAST),
        PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
        JumpToHeight(105),
        WalkNortheastSteps(3),
        SetSolidityBits(cant_pass_walls=True),
        Pause(1, identifier="ACTION_822_pause_94"),
        JmpIfObjectInAir(NPC_2, ["ACTION_822_pause_94"]),
        SetBit(TEMP_7043_1),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        ClearSolidityBits(cant_pass_walls=True),
        SetAllSpeeds(NORMAL),
        WalkNortheastSteps(2),
        WalkNortheastSteps(7),
        WalkSoutheastSteps(3),
        Walk1StepSoutheast(),
        WalkSouthwestSteps(2),
        SetAllSpeeds(FAST),
        PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
        JumpToHeight(105),
        WalkSoutheastSteps(3),
        SetSolidityBits(cant_pass_walls=True),
        Pause(1, identifier="ACTION_822_pause_110"),
        JmpIfObjectInAir(NPC_2, ["ACTION_822_pause_110"]),
        SetBit(TEMP_7043_1),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        ClearSolidityBits(cant_pass_walls=True),
        SetAllSpeeds(NORMAL),
        WalkNortheastSteps(8),
        VisibilityOff(),
        Return(),
        Pause(24, identifier="ACTION_822_pause_119"),
        Pause(24),
        SetSolidityBits(cant_pass_walls=True),
        FixedFCoordOn(),
        PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
        JumpToHeight(96),
        Walk1StepNortheast(),
        Pause(8),
        FixedFCoordOff(),
        FaceSouthwest(),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        WalkNortheastSteps(10),
        SetAllSpeeds(FAST),
        PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
        JumpToHeight(105),
        WalkSoutheastSteps(3),
        SetSolidityBits(cant_pass_walls=True),
        Pause(1, identifier="ACTION_822_pause_136"),
        JmpIfObjectInAir(NPC_1, ["ACTION_822_pause_136"]),
        SetBit(TEMP_7043_1),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        ClearSolidityBits(cant_pass_walls=True),
        SetAllSpeeds(NORMAL),
        Walk1StepSoutheast(),
        WalkNortheastSteps(5),
        Walk1StepNorthwest(),
        WalkNorthwestSteps(2),
        WalkNortheastSteps(3),
        SetAllSpeeds(FAST),
        PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
        JumpToHeight(105),
        WalkNortheastSteps(3),
        SetSolidityBits(cant_pass_walls=True),
        Pause(1, identifier="ACTION_822_pause_152"),
        JmpIfObjectInAir(NPC_1, ["ACTION_822_pause_152"]),
        SetBit(TEMP_7043_1),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        ClearSolidityBits(cant_pass_walls=True),
        SetAllSpeeds(NORMAL),
        Walk1StepNortheast(),
        Walk1StepSoutheast(),
        WalkSoutheastSteps(2),
        WalkNortheastSteps(2),
        SetAllSpeeds(FAST),
        PlaySound(sound=SO030_SURPRISED_MONSTER, channel=4),
        JumpToHeight(105),
        WalkNortheastSteps(3),
        SetSolidityBits(cant_pass_walls=True),
        Pause(1, identifier="ACTION_822_pause_167"),
        JmpIfObjectInAir(NPC_1, ["ACTION_822_pause_167"]),
        SetBit(TEMP_7043_1),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        ClearSolidityBits(cant_pass_walls=True),
        SetAllSpeeds(NORMAL),
        WalkNortheastSteps(2),
        VisibilityOff(),
        Return(),
    ]
)
