"""A0826_ENEMY_FALL_ONTO_CONVEYOR"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        SetPriority(3),
        Set700CToCurrentLevel(),
        JmpIfVarEqualsConst(
            PRIMARY_TEMP_700C, 473, ["ACTION_826_set_solidity_bits_61"]
        ),
        Set700CToPressedButton(),
        CompareVarToConst(PRIMARY_TEMP_700C, 24),
        JmpIfComparisonResultIsGreaterOrEqual(
            ["ACTION_826_shift_f_direction_steps_55"]
        ),
        JmpIfVarEqualsConst(PRIMARY_TEMP_700C, 22, ["ACTION_826_shadow_on_34"]),
        ShadowOn(identifier="ACTION_826_shadow_on_7"),
        VisibilityOff(),
        FloatingOff(),
        SetSolidityBits(cant_pass_walls=True),
        Pause(20),
        TransferToXYZF(x=7, y=38, z=2, direction=SOUTHEAST),
        FaceSouthwest(),
        JumpToHeight(96),
        Pause(20),
        FloatingOn(),
        VisibilityOn(),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        Pause(24),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        Pause(30),
        JumpToHeight(64),
        Walk1StepSouthwest(),
        Pause(5),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        Pause(58),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        JumpToHeight(96),
        ClearSolidityBits(cant_pass_walls=True),
        Walk1StepSoutheast(),
        ShadowOff(),
        Walk1StepSoutheast(),
        Jmp(["ACTION_826_shadow_on_7"]),
        ShadowOn(identifier="ACTION_826_shadow_on_34"),
        VisibilityOff(),
        FloatingOff(),
        SetSolidityBits(cant_pass_walls=True),
        Pause(20),
        TransferToXYZF(x=14, y=24, z=0, direction=SOUTHEAST),
        JumpToHeight(96),
        Pause(20),
        FloatingOn(),
        VisibilityOn(),
        ObjectMemoryClearBit(arg_1=0x30, bits=[4]),
        Pause(24),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        Pause(42),
        PlaySound(sound=SO022_CLOSE_DOOR, channel=4),
        Pause(2),
        JumpToHeight(96),
        ClearSolidityBits(cant_pass_walls=True),
        ShadowOff(),
        WalkSouthwestSteps(2),
        Jmp(["ACTION_826_shadow_on_34"]),
        WalkFDirectionSteps(4, identifier="ACTION_826_shift_f_direction_steps_55"),
        Pause(8),
        TurnClockwise45DegreesNTimes(2),
        Pause(8),
        TurnClockwise45DegreesNTimes(2),
        Jmp(["ACTION_826_shift_f_direction_steps_55"]),
        SetSolidityBits(
            cant_pass_walls=True, identifier="ACTION_826_set_solidity_bits_61"
        ),
        Set700CToPressedButton(),
        AddConstToVar(PRIMARY_TEMP_700C, 65517),
        LoadMemory(PRIMARY_TEMP_700C),
        Pause(2),
        EndLoop(),
        SetWalkingSpeed(NORMAL),
        FixedFCoordOn(),
        StartLoopNTimes(2, identifier="ACTION_826_start_loop_n_times_69"),
        Walk1StepSoutheast(),
        Pause(30),
        EndLoop(),
        StartLoopNTimes(2),
        Walk1StepNorthwest(),
        Pause(30),
        EndLoop(),
        Jmp(["ACTION_826_start_loop_n_times_69"]),
    ]
)
