"""A0641_MIDAS_2ND_TUNNELS_PIRANHA"""

from randomizer.scripts.action.script_imports import *

script = ActionScript(
    [
        SetPriority(3),
        SetVRAMPriority(NORMAL_PRIORITY),
        SequenceLoopingOn(),
        FixedFCoordOn(),
        Pause(8),
        StartLoopNTimes(5),
        SetAllSpeeds(NORMAL),
        Walk1StepSouthwest(),
        SetSequenceSpeed(FAST),
        WalkSouthwestPixels(8),
        WalkNortheastPixels(8),
        WalkSouthwestPixels(8),
        WalkNortheastPixels(8),
        SetSequenceSpeed(NORMAL),
        Walk1StepNortheast(),
        EndLoop(),
        SetAllSpeeds(FAST),
        Walk1StepSouthwest(),
        Pause(1, identifier="ACTION_641_pause_18"),
        JmpIfBitClear(TEMP_7043_1, ["ACTION_641_pause_18"]),
        SetAllSpeeds(VERY_FAST),
        Walk1StepNortheast(),
        StartLoopNTimes(7),
        ShiftZUpPixels(8),
        ShiftZDownPixels(8),
        EndLoop(),
        SetWalkingSpeed(NORMAL),
        SetSequenceSpeed(VERY_FAST),
        Pause(16),
        StartLoopNTimes(5),
        JumpToHeight(56),
        Walk1StepSoutheast(),
        JumpToHeight(56),
        Walk1StepNorthwest(),
        EndLoop(),
        WalkEastSteps(2),
        Return(),
    ]
)
