from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E3765_BEAN_VALLEY_UPPER_CHEST_ROOM_FALL_TO_LOWER_CHEST_ROOM,
        x=19,
        y=96,
        z=6,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = True,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E3765_BEAN_VALLEY_UPPER_CHEST_ROOM_FALL_TO_LOWER_CHEST_ROOM,
        x=19,
        y=97,
        z=6,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = True,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E3782_BEAN_VALLEY_UPPER_CHEST_ROOM_FALL_TO_WEST_VINE_ROOM,
        x=17,
        y=104,
        z=6,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = True,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E3782_BEAN_VALLEY_UPPER_CHEST_ROOM_FALL_TO_WEST_VINE_ROOM,
        x=17,
        y=105,
        z=6,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = True,
        byte_8_bit_4 = False,
    ),
]
