from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=1,
        y=19,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R084_ROSE_TOWN_OUTSIDE,
        show_message = True,
        dst_x = 4,
        dst_y = 38,
        dst_z = 1,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=6,
        y=13,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=2,
        nw_se_edge_active = True,
        ne_sw_edge_active = True,
        byte_2_bit_2 = False,
        destination = R096_ROSE_TOWN_INN_2F,
        show_message = False,
        dst_x = 8,
        dst_y = 47,
        dst_z = 1,
        dst_z_half = True,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
]
