from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=15,
        y=74,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R208_SEASIDE_TOWN_DURING_YARIDOVICH_OUTSIDE,
        show_message = False,
        dst_x = 15,
        dst_y = 42,
        dst_z = 1,
        dst_z_half = False,
    dst_f = SOUTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=18,
        y=68,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R208_SEASIDE_TOWN_DURING_YARIDOVICH_OUTSIDE,
        show_message = False,
        dst_x = 17,
        dst_y = 38,
        dst_z = 1,
        dst_z_half = False,
    dst_f = SOUTHEAST,
        x_bit_7 = False,
    ),
]
