from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E2161_KEEP_TERRA_COTTA_BATTLE_ROOM_SUMMON_1ST_BATTLE,
        x=5,
        y=57,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=3,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2162_KEEP_TERRA_COTTA_BATTLE_ROOM_SUMMON_2ND_BATTLE,
        x=9,
        y=49,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=3,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2163_KEEP_TERRA_COTTA_BATTLE_ROOM_SUMMON_3RD_BATTLE,
        x=13,
        y=41,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=3,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2164_KEEP_TERRA_COTTA_BATTLE_ROOM_SUMMON_4TH_BATTLE,
        x=17,
        y=33,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=3,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1948_KEEP_TERRA_CORRA_BATTLE_ROOM_EXIT,
        x=22,
        y=25,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
]
