from randomizer.entities.rooms.exit_imports import *

exits = [
    MapExit(
        x=4,
        y=68,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = OW16_TADPOLE_POND,
        show_message = False,
        byte_2_bit_1 = False,
        byte_2_bit_0 = False,
    ),
    RoomExit(
        x=27,
        y=73,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R074_TADPOLE_POND_AREA_02,
        show_message = True,
        dst_x = 2,
        dst_y = 52,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHEAST,
        x_bit_7 = False,
    ),
]
