from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    RegularNPC(
        occupant=FakeToad,
        initiator=EventInitiator.PRESS_A_FROM_ANY_SIDE,
        event_script=E1140_SEASIDE_OCCUPIED_BOMB_SHOP,
        action_script=A0585_SEASIDE_OCCUPIED_SHOPKEEPER,
        speed=0,
        visible=True,
        x=14,
        y=40,
        z=0,
        z_half=False,
        direction=SOUTHEAST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=True,
        cant_walk_up_stairs=True,
        cant_walk_under=True,
        cant_pass_walls=False,
        cant_jump_through=False,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=True,
        cant_move_if_in_air=True,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False,
    ),
    # NPC_1
    RegularClone(
        occupant=FakeToad,
        event_script=E1141_SEASIDE_OCCUPIED_BOMB_SHOP_CUSTOMER,
        action_script=A0586_SEASIDE_OCCUPIED_CUSTOMER,
        visible=True,
        x=14,
        y=43,
        z=0,
        z_half=False,
        direction=NORTHWEST,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False,
    ),
]
