from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E0547_ROSE_TOWN_OCCUPIED_ARROW_CONTROL_1,
        x=11,
        y=42,
        z=1,
        f=EdgeDirection.SOUTHWEST,
        length=4,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0549_ROSE_TOWN_OCCUPIED_ARROW_CONTROL_2,
        x=11,
        y=55,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0549_ROSE_TOWN_OCCUPIED_ARROW_CONTROL_2,
        x=7,
        y=45,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0549_ROSE_TOWN_OCCUPIED_ARROW_CONTROL_2,
        x=15,
        y=43,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0549_ROSE_TOWN_OCCUPIED_ARROW_CONTROL_2,
        x=13,
        y=30,
        z=1,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0553_ROSE_TOWN_OCCUPIED_ARROW_CONTROL_4,
        x=16,
        y=47,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=4,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0550_ROSE_TOWN_OCCUPIED_ARROW_CONTROL_3,
        x=9,
        y=55,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=3,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0550_ROSE_TOWN_OCCUPIED_ARROW_CONTROL_3,
        x=10,
        y=56,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=6,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E3590_ROSE_TOWN_CHIMNEY,
        x=23,
        y=47,
        z=6,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
]
