from randomizer.entities.rooms.exit_imports import *

exits = [
    MapExit(
        x=7,
        y=54,
        z=1,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = True,
        destination = OW18_ROSE_TOWN,
        show_message = False,
        byte_2_bit_1 = True,
        byte_2_bit_0 = True,
    ),
    RoomExit(
        x=5,
        y=36,
        z=1,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R085_ROSE_TOWN_DURING_BOWYER_INN_1F,
        show_message = True,
        dst_x = 2,
        dst_y = 18,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=21,
        y=45,
        z=1,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R087_ROSE_TOWN_ITEM_SHOP,
        show_message = True,
        dst_x = 2,
        dst_y = 69,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=14,
        y=55,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R089_ROSE_TOWN_DURING_BOWYER_THREE_GRANDKIDS_HOUSE,
        show_message = False,
        dst_x = 16,
        dst_y = 16,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=16,
        y=34,
        z=1,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R091_ROSE_TOWN_COUPLES_HOUSE,
        show_message = False,
        dst_x = 13,
        dst_y = 40,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=12,
        y=24,
        z=4,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R093_ROSE_TOWN_DURING_BOWYER_TREASURE_HOUSE_1F,
        show_message = False,
        dst_x = 16,
        dst_y = 65,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
]
