from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E1296_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=20,
        y=23,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1296_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=20,
        y=24,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1298_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=22,
        y=23,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1298_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=22,
        y=24,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1299_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=25,
        y=17,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1299_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=25,
        y=18,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1300_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=24,
        y=23,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1300_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=24,
        y=24,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1302_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=27,
        y=17,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1302_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=27,
        y=18,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1303_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=24,
        y=27,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1303_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=24,
        y=28,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1305_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=27,
        y=25,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1305_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=27,
        y=26,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1306_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=29,
        y=21,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1306_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=29,
        y=22,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1307_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=25,
        y=33,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1307_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=25,
        y=34,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1308_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=27,
        y=29,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1308_TOWER_CHECKERBOARD_ROOM_FIREBALL_LAUNCHER,
        x=27,
        y=30,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
]
