from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=15,
        y=34,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R102_MOLEVILLE_OUTSIDE_AT_EXIT_FROM_MINES,
        show_message = False,
        dst_x = 17,
        dst_y = 44,
        dst_z = 4,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=21,
        y=23,
        z=4,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R278_MOLEVILLE_MINES_AREA_03_LEADS_BACK_TO_AREA_1,
        show_message = False,
        dst_x = 11,
        dst_y = 89,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=20,
        y=25,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R274_MOLEVILLE_MINES_AREA_02,
        show_message = False,
        dst_x = 3,
        dst_y = 97,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
