"""NPC list import"""

from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    RegularNPC(
        occupant=OldBlueToad,
        initiator=EventInitiator.PRESS_A_FROM_ANY_SIDE,
        event_script=E0352_MUSHROOM_KINGDOM_OCCUPIED_SHOPKEEPER,
        action_script=A0119_SLOW_SEQUENCE_LOOP,
        speed=0,
        visible=True,
        x=15,
        y=18,
        z=2,
        z_half=True,
        direction=SOUTHWEST,
        face_on_trigger=True,
        cant_enter_doors=True,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=False,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=False,
        cant_move_if_in_air=False,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False),
    # NPC_1
    RegularNPC(
        occupant=Letter,
        initiator=EventInitiator.PRESS_A_FROM_FRONT,
        event_script=E0290_MUSHROOM_KINGDOM_SHOP_LOGIC,
        action_script=A0977_NOTE_WITHOUT_KNIFE,
        speed=0,
        visible=True,
        x=14,
        y=19,
        z=2,
        z_half=False,
        direction=SOUTHWEST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=False,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=True,
        cant_move_if_in_air=False,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=True),
]
