from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=23,
        y=106,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=3,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R448_BOWSERS_KEEP_AREA_09_TALL_ROOM_WSAVE_POINT,
        show_message = False,
        dst_x = 4,
        dst_y = 42,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=28,
        y=97,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R449_BOWSERS_KEEP_AREA_11_THWOMPBULLET_ROOM_AFTER_MAGIKOOPAS_ROOM,
        show_message = False,
        dst_x = 4,
        dst_y = 77,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=26,
        y=93,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R450_BOWSERS_KEEP_AREA_12_CROCOS_SHOP_2_AFTER_MAGIKOOPAS_ROOM,
        show_message = False,
        dst_x = 4,
        dst_y = 29,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
