from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=3,
        y=66,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R357_VOLCANO_POSTCD_AREA_01,
        show_message = False,
        dst_x = 19,
        dst_y = 83,
        dst_z = 12,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=3,
        y=50,
        z=3,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R365_VOLCANO_POSTCD_AREA_03,
        show_message = False,
        dst_x = 15,
        dst_y = 39,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
]
