from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=11,
        y=120,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R281_MOLEVILLE_MINES_AREA_07_FROM_CROCOS_BOMBED_ROOM,
        show_message = False,
        dst_x = 26,
        dst_y = 87,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=18,
        y=123,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R283_MOLEVILLE_MINES_AREA_09_LEADS_LEFT_TO_CROCOS_BOMBED_ROOM,
        show_message = False,
        dst_x = 3,
        dst_y = 19,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHEAST,
        x_bit_7 = False,
    ),
]
