# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectdisassembler --rom ROM
from randomizer.helpers.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
from randomizer.data.rooms.room import Buffer, Partition, DestinationProps, RoomExit, MapExit, Event, BattlePackNPC, RegularNPC, ChestNPC, BattlePackClone, RegularClone, ChestClone, Room
from randomizer.data import npcs
from randomizer.helpers.npcmodeltables import SpriteName, VramStore, ShadowSize
room = Room(
    partition=Partition(
        ally_sprite_buffer_size=1,
        allow_extra_sprite_buffer=False,
        extra_sprite_buffer_size=0,
        buffers = [
            Buffer(
                buffer_type=PartitionBufferTypes.EMPTY_3,
                main_buffer_space=PartitionMainSpace._0_BYTES,
                index_in_main_buffer=True
            ),
            Buffer(
                buffer_type=PartitionBufferTypes.EMPTY_3,
                main_buffer_space=PartitionMainSpace._0_BYTES,
                index_in_main_buffer=True
            ),
            Buffer(
                buffer_type=PartitionBufferTypes.EMPTY_3,
                main_buffer_space=PartitionMainSpace._0_BYTES,
                index_in_main_buffer=True
            )
        ],
        full_palette_buffer=True
    ),
    music=Music._02_MUSHROOM_KINGDOM,
    entrance_event=15,
    exit_fields=[
        RoomExit(
            x=27,
            y=30,
            z=0,
            f=Edge.SOUTHEAST,
            length=2,
            height=0,
            nw_se_edge_active=True,
            ne_sw_edge_active=False,
            byte_2_bit_2=False,
            destination=Rooms._017_MUSHROOM_KINGDOM_CASTLE_MAIN_HALL,
            show_message=False,
            dst_x=4,
            dst_y=23,
            dst_z=2,
            dst_z_half=0,
            dst_f=RadialDirection.SOUTHEAST,
            x_bit_7=False,
        ),
        RoomExit(
            x=26,
            y=19,
            z=3,
            f=Edge.SOUTHWEST,
            length=2,
            height=2,
            nw_se_edge_active=True,
            ne_sw_edge_active=False,
            byte_2_bit_2=False,
            destination=Rooms._032_MUSHROOM_KINGDOM_CASTLE_ENTRANCE_TO_TOADSTOOLS_ROOM,
            show_message=False,
            dst_x=11,
            dst_y=98,
            dst_z=1,
            dst_z_half=0,
            dst_f=RadialDirection.NORTHEAST,
            x_bit_7=False,
        ),
    ],
)
