"""NPC list import"""

from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    RegularNPC(
        occupant=BlueToad,
        initiator=EventInitiator.PRESS_A_FROM_ANY_SIDE,
        event_script=E0302_MUSHROOM_KINGDOM_DAD,
        action_script=A0119_SLOW_SEQUENCE_LOOP,
        speed=0,
        visible=True,
        x=7,
        y=22,
        z=2,
        z_half=False,
        direction=NORTHWEST,
        face_on_trigger=True,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=False,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=False,
        cant_move_if_in_air=False,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False),
    # NPC_1
    RegularClone(
        occupant=PinkToad,
        event_script=E0301_MUSHROOM_KINGDOM_MOM,
        action_script=A0119_SLOW_SEQUENCE_LOOP,
        visible=True,
        x=7,
        y=16,
        z=2,
        z_half=False,
        direction=NORTHEAST,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False),
    # NPC_2
    RegularNPC(
        occupant=PinkSmallToad,
        initiator=EventInitiator.PRESS_A_FROM_ANY_SIDE,
        event_script=E0306_MUSHROOM_KINGDOM_BROTHER,
        action_script=A0128_WALK_RANDOM_DIRECTIONS,
        speed=0,
        visible=True,
        x=5,
        y=18,
        z=2,
        z_half=False,
        direction=SOUTHWEST,
        face_on_trigger=True,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=True,
        cant_pass_walls=True,
        cant_jump_through=False,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=True,
        cant_move_if_in_air=False,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False),
]
