from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E1913_ABYSS_MACHINE_ARROW_ANIMATE,
        x=4,
        y=79,
        z=1,
        f=EdgeDirection.SOUTHWEST,
        length=3,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1913_ABYSS_MACHINE_ARROW_ANIMATE,
        x=5,
        y=78,
        z=1,
        f=EdgeDirection.SOUTHWEST,
        length=3,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1913_ABYSS_MACHINE_ARROW_ANIMATE,
        x=10,
        y=78,
        z=1,
        f=EdgeDirection.SOUTHWEST,
        length=4,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1913_ABYSS_MACHINE_ARROW_ANIMATE,
        x=10,
        y=77,
        z=1,
        f=EdgeDirection.SOUTHWEST,
        length=4,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1913_ABYSS_MACHINE_ARROW_ANIMATE,
        x=14,
        y=66,
        z=2,
        f=EdgeDirection.SOUTHWEST,
        length=3,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E1913_ABYSS_MACHINE_ARROW_ANIMATE,
        x=14,
        y=65,
        z=2,
        f=EdgeDirection.SOUTHWEST,
        length=3,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
]
