"""NPC list import"""

from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    BattlePackNPC(
        occupant=Greaper,
        initiator=EventInitiator.ANYTHING_EXCEPT_PRESS_A,
        after_battle=PostBattleBehaviour.REMOVE_PERMANENTLY,
        battle_pack=PACK0076_GREAPER_WITH_REACHER_STRAWHEAD,
        action_script=A0344_SHIP_PUZZLE_AREA_GREAPERS,
        speed=0,
        visible=True,
        x=20,
        y=70,
        z=6,
        z_half=True,
        direction=SOUTHEAST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=False,
        cant_pass_npcs=True,
        byte3_bit5=False,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=True,
        cant_move_if_in_air=True,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False),
    # NPC_1
    BattlePackClone(
        occupant=Greaper,
        battle_pack=PACK0076_GREAPER_WITH_REACHER_STRAWHEAD,
        action_script=A0344_SHIP_PUZZLE_AREA_GREAPERS,
        visible=True,
        x=17,
        y=76,
        z=6,
        z_half=True,
        direction=SOUTHEAST,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False),
    # NPC_2
    BattlePackClone(
        occupant=Greaper,
        battle_pack=PACK0076_GREAPER_WITH_REACHER_STRAWHEAD,
        action_script=A0344_SHIP_PUZZLE_AREA_GREAPERS,
        visible=True,
        x=14,
        y=82,
        z=6,
        z_half=True,
        direction=SOUTHEAST,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False),
    # NPC_3
    BattlePackClone(
        occupant=Greaper,
        battle_pack=PACK0076_GREAPER_WITH_REACHER_STRAWHEAD,
        action_script=A0344_SHIP_PUZZLE_AREA_GREAPERS,
        visible=True,
        x=17,
        y=84,
        z=1,
        z_half=True,
        direction=SOUTHEAST,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False),
    # NPC_4
    BattlePackClone(
        occupant=Greaper,
        battle_pack=PACK0076_GREAPER_WITH_REACHER_STRAWHEAD,
        action_script=A0344_SHIP_PUZZLE_AREA_GREAPERS,
        visible=True,
        x=21,
        y=76,
        z=1,
        z_half=True,
        direction=SOUTHEAST,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False),
    # NPC_5
    BattlePackClone(
        occupant=Greaper,
        battle_pack=PACK0076_GREAPER_WITH_REACHER_STRAWHEAD,
        action_script=A0344_SHIP_PUZZLE_AREA_GREAPERS,
        visible=True,
        x=24,
        y=71,
        z=1,
        z_half=True,
        direction=SOUTHWEST,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=False),
]
