from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=4,
        y=120,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R079_ROSE_WAY_MAIN_AREA,
        show_message = False,
        dst_x = 19,
        dst_y = 12,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=14,
        y=122,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R079_ROSE_WAY_MAIN_AREA,
        show_message = False,
        dst_x = 27,
        dst_y = 15,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
]
