from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E2461_STAR_HILL_2ND_ROOM_SUMMON_NORTH_SACKIT,
        x=21,
        y=23,
        z=2,
        f=EdgeDirection.SOUTHWEST,
        length=12,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2462_STAR_HILL_2ND_ROOM_SUMMON_EAST_SACKIT,
        x=23,
        y=43,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=8,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2463_STAR_HILL_2ND_ROOM_SUMMON_WEST_SACKIT,
        x=7,
        y=44,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=8,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2464_STAR_HILL_2ND_ROOM_SUMMON_CENTRAL_SACKIT,
        x=14,
        y=43,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=12,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E2525_STAR_HILL_2ND_ROOM_USE_DOOR,
        x=13,
        y=23,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=7,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
]
