from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=14,
        y=94,
        z=4,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R119_NIMBUS_CASTLE_AREA_06_LEFTMOST_FRONT_DOOR_FROM_AREA_05,
        show_message = False,
        dst_x = 6,
        dst_y = 13,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=21,
        y=101,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R414_NIMBUS_CASTLE_AREA_08_FROM_AREA_07_GET_ROOM_KEY_1_HERE,
        show_message = False,
        dst_x = 27,
        dst_y = 77,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHEAST,
        x_bit_7 = False,
    ),
]
