# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectdisassembler --rom ROM
from randomizer.data.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms
room = {
  "partition": 83,
  "music": Music._27_DUNGEON_IS_FULL_OF_MONSTERS,
  "entrance_event": 1791,
  "event_tiles": [],
  "exit_fields": [
    {
      "x": 22,
      "y": 26,
      "z": 0,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "destination": Rooms._263_LANDS_END_UNDERGROUND_AREA_01,
      "show_message": False,
      "destination_props": {
        "x": 10,
        "y": 92,
        "z": 0,
        "z_half": False,
        "f": RadialDirection.SOUTHWEST,
        "x_bit_7": False
      }
    },
    {
      "x": 30,
      "y": 10,
      "z": 0,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "destination": Rooms._265_LANDS_END_UNDERGROUND_AREA_03,
      "show_message": True,
      "destination_props": {
        "x": 15,
        "y": 109,
        "z": 4,
        "z_half": False,
        "f": RadialDirection.NORTHEAST,
        "x_bit_7": False
      }
    }
  ],
  "objects": [
    {
      "id": 0,
      "type": ObjectType.BATTLE,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 350,
      "battle_pack": 82,
      "after_battle": 0,
      "action_script": 768,
      "speed": 0,
      "action_offset": 0,
      "pack_offset": 9,
      "visible": True,
      "x": 24,
      "y": 23,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.NORTHWEST,
      "face_on_trigger": True,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": True,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": True,
      "cant_walk_through": True,
      "byte3_bit7": True,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 1,
          "action_offset": 0,
          "pack_offset": 9,
          "visible": True,
          "x": 26,
          "y": 21,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "id": 2,
          "action_offset": 0,
          "pack_offset": 9,
          "visible": True,
          "x": 29,
          "y": 18,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHEAST
        }
      ]
    },
    {
      "id": 3,
      "type": ObjectType.BATTLE,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 336,
      "battle_pack": 82,
      "after_battle": 0,
      "action_script": 160,
      "speed": 0,
      "action_offset": 0,
      "pack_offset": 1,
      "visible": True,
      "x": 28,
      "y": 13,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.NORTHEAST,
      "face_on_trigger": True,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": True,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": True,
      "cant_walk_through": True,
      "byte3_bit7": True,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 4,
          "action_offset": 0,
          "pack_offset": 1,
          "visible": True,
          "x": 29,
          "y": 14,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.NORTHEAST
        },
        {
          "id": 5,
          "action_offset": 0,
          "pack_offset": 1,
          "visible": True,
          "x": 28,
          "y": 13,
          "z": 2,
          "z_half": False,
          "direction": RadialDirection.NORTHEAST
        },
        {
          "id": 6,
          "action_offset": 0,
          "pack_offset": 1,
          "visible": True,
          "x": 29,
          "y": 14,
          "z": 2,
          "z_half": False,
          "direction": RadialDirection.NORTHEAST
        }
      ]
    }
  ]
}
