# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectdisassembler --rom ROM
from randomizer.data.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms
room = {
  "partition": 70,
  "music": Music._62_BARREL_VOLCANO,
  "entrance_event": 15,
  "event_tiles": [],
  "exit_fields": [
    {
      "x": 12,
      "y": 67,
      "z": 0,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._386_VOLCANO_AREA_12_ERUPTING_STUMPET,
      "show_message": False,
      "destination_props": {
        "x": 19,
        "y": 123,
        "z": 0,
        "z_half": False,
        "f": RadialDirection.NORTHEAST,
        "x_bit_7": False
      }
    },
    {
      "x": 15,
      "y": 71,
      "z": 5,
      "f": Edge.SOUTHEAST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._386_VOLCANO_AREA_12_ERUPTING_STUMPET,
      "show_message": False,
      "destination_props": {
        "x": 20,
        "y": 110,
        "z": 4,
        "z_half": False,
        "f": RadialDirection.SOUTHEAST,
        "x_bit_7": False
      }
    }
  ],
  "objects": [
    {
      "id": 0,
      "type": ObjectType.CHEST,
      "initiator": Initiator.HIT_FROM_BELOW,
      "model": 503,
      "event_script": 3153,
      "action_script": 435,
      "speed": 0,
      "star_offset": 6,
      "item_offset": 12,
      "visible": True,
      "x": 10,
      "y": 67,
      "z": 4,
      "z_half": True,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": False,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "id": 1,
          "star_offset": 8,
          "item_offset": 12,
          "visible": True,
          "x": 11,
          "y": 61,
          "z": 8,
          "z_half": True,
          "direction": RadialDirection.SOUTHWEST
        }
      ]
    },
    {
      "id": 2,
      "type": ObjectType.OBJECT,
      "initiator": Initiator.JUMP_ON,
      "model": 509,
      "event_script": 80,
      "action_script": 120,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 13,
      "y": 65,
      "z": 5,
      "z_half": True,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": True,
      "cant_walk_through": True,
      "byte3_bit7": True,
      "slidable_along_walls": False,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": []
    }
  ]
}
