# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectdisassembler --rom ROM
from randomizer.data.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection
room = {
  "partition": 11,
  "objects": [
    {
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 253,
      "event_script": 540,
      "action_script": 15,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 1,
      "action_offset": 0,
      "visible": True,
      "x": 17,
      "y": 20,
      "z": 4,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": False,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": True,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": False,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "npc_id_offset": 0,
          "event_offset": 1,
          "action_offset": 0,
          "visible": True,
          "x": 17,
          "y": 20,
          "z": 4,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "npc_id_offset": 0,
          "event_offset": 1,
          "action_offset": 0,
          "visible": True,
          "x": 17,
          "y": 20,
          "z": 4,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "npc_id_offset": 0,
          "event_offset": 1,
          "action_offset": 0,
          "visible": True,
          "x": 17,
          "y": 20,
          "z": 4,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "npc_id_offset": 0,
          "event_offset": 1,
          "action_offset": 0,
          "visible": True,
          "x": 17,
          "y": 20,
          "z": 4,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "npc_id_offset": 0,
          "event_offset": 1,
          "action_offset": 0,
          "visible": True,
          "x": 17,
          "y": 20,
          "z": 4,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "npc_id_offset": 0,
          "event_offset": 1,
          "action_offset": 0,
          "visible": True,
          "x": 17,
          "y": 20,
          "z": 4,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "npc_id_offset": 0,
          "event_offset": 1,
          "action_offset": 0,
          "visible": True,
          "x": 17,
          "y": 20,
          "z": 4,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        }
      ]
    }
  ]
}
