# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectdisassembler --rom ROM
from randomizer.data.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection
room = {
  "partition": 18,
  "objects": [
    {
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 63,
      "event_script": 470,
      "action_script": 15,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 25,
      "y": 25,
      "z": 1,
      "z_half": False,
      "direction": RadialDirection.NORTHWEST,
      "face_on_trigger": True,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": False,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 29,
          "y": 18,
          "z": 1,
          "z_half": False,
          "direction": RadialDirection.NORTHWEST
        }
      ]
    },
    {
      "type": ObjectType.OBJECT,
      "initiator": Initiator.NONE,
      "model": 495,
      "event_script": 3728,
      "action_script": 979,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 2,
      "visible": True,
      "x": 27,
      "y": 14,
      "z": 2,
      "z_half": False,
      "direction": RadialDirection.SOUTHEAST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": False,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "npc_id_offset": 0,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 22,
          "y": 23,
          "z": 2,
          "z_half": False,
          "direction": RadialDirection.SOUTHEAST
        }
      ]
    }
  ]
}
