# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectdisassembler --rom ROM
from randomizer.data.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection
room = {
  "partition": 73,
  "objects": [
    {
      "type": ObjectType.OBJECT,
      "initiator": Initiator.JUMP_ON,
      "model": 99,
      "event_script": 3296,
      "action_script": 15,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 18,
      "y": 120,
      "z": 0,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": []
    }
  ]
}
