# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectdisassembler --rom ROM
from randomizer.data.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms
room = {
  "partition": None,
  "music": Music._11_BOWSERS_CASTLE_1ST_TIME,
  "entrance_event": 2498,
  "event_tiles": [],
  "exit_fields": [
    {
      "x": 17,
      "y": 67,
      "z": 0,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 0,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "destination_type": ExitType.ROOM,
      "byte_2_bit_2": False,
      "destination": Rooms._261_BOWSERS_KEEP_1ST_TIME_AREA_03_LAVA_ROOM_WBRIDGE,
      "show_message": False,
      "destination_props": {
        "x": 4,
        "y": 66,
        "z": 5,
        "z_half": False,
        "f": RadialDirection.NORTHEAST,
        "x_bit_7": False
      }
    }
  ],
  "objects": []
}
