# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectdisassembler --rom ROM
from randomizer.data.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection
room = {
  "partition": 12,
  "objects": [
    {
      "type": ObjectType.OBJECT,
      "initiator": Initiator.PRESS_A_FROM_ANY_SIDE,
      "model": 65,
      "event_script": 301,
      "action_script": 119,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 1,
      "action_offset": 0,
      "visible": True,
      "x": 7,
      "y": 22,
      "z": 2,
      "z_half": False,
      "direction": RadialDirection.NORTHWEST,
      "face_on_trigger": True,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": False,
      "cant_jump_through": False,
      "cant_pass_npcs": False,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": True,
      "slidable_along_walls": False,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "npc_id_offset": 1,
          "event_offset": 0,
          "action_offset": 0,
          "visible": True,
          "x": 7,
          "y": 16,
          "z": 2,
          "z_half": False,
          "direction": RadialDirection.NORTHEAST
        }
      ]
    },
    {
      "type": ObjectType.OBJECT,
      "initiator": Initiator.PRESS_A_FROM_ANY_SIDE,
      "model": 116,
      "event_script": 306,
      "action_script": 128,
      "speed": 0,
      "npc_id_offset": 0,
      "event_offset": 0,
      "action_offset": 0,
      "visible": True,
      "x": 5,
      "y": 18,
      "z": 2,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": True,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": False,
      "cant_walk_up_stairs": False,
      "cant_walk_under": True,
      "cant_pass_walls": True,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": True,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": False,
      "byte7_upper2": 0x03,
      "clones": []
    }
  ]
}
