# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectdisassembler --rom ROM
from randomizer.data.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms
room = {
  "partition": None,
  "music": Music._32_AND_MY_NAMES_BOOSTER,
  "entrance_event": 2354,
  "event_tiles": [
    {
      "event": 2420,
      "x": 10,
      "y": 80,
      "z": 0,
      "f": Edge.SOUTHEAST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    },
    {
      "event": 2421,
      "x": 13,
      "y": 90,
      "z": 0,
      "f": Edge.SOUTHWEST,
      "length": 2,
      "height": 7,
      "nw_se_edge_active": True,
      "ne_sw_edge_active": False,
      "byte_8_bit_4": False,
    }
  ],
  "exit_fields": [],
  "objects": []
}
