# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectdisassembler --rom ROM
from randomizer.data.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection
room = {
  "partition": 94,
  "objects": [
    {
      "type": ObjectType.BATTLE,
      "initiator": Initiator.ANYTHING_EXCEPT_PRESS_A,
      "model": 335,
      "battle_pack": 74,
      "after_battle": 0,
      "action_script": 342,
      "speed": 0,
      "action_offset": 0,
      "pack_offset": 0,
      "visible": True,
      "x": 15,
      "y": 86,
      "z": 6,
      "z_half": False,
      "direction": RadialDirection.SOUTHWEST,
      "face_on_trigger": False,
      "cant_enter_doors": False,
      "byte2_bit5": False,
      "set_sequence_playback": True,
      "cant_float": True,
      "cant_walk_up_stairs": False,
      "cant_walk_under": False,
      "cant_pass_walls": True,
      "cant_jump_through": False,
      "cant_pass_npcs": True,
      "byte3_bit5": False,
      "cant_walk_through": True,
      "byte3_bit7": False,
      "slidable_along_walls": True,
      "cant_move_if_in_air": True,
      "byte7_upper2": 0x03,
      "clones": [
        {
          "action_offset": 0,
          "pack_offset": 0,
          "visible": True,
          "x": 11,
          "y": 93,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.SOUTHWEST
        },
        {
          "action_offset": 0,
          "pack_offset": 0,
          "visible": True,
          "x": 12,
          "y": 94,
          "z": 0,
          "z_half": False,
          "direction": RadialDirection.NORTHEAST
        },
        {
          "action_offset": 0,
          "pack_offset": 0,
          "visible": True,
          "x": 15,
          "y": 87,
          "z": 6,
          "z_half": False,
          "direction": RadialDirection.NORTHEAST
        }
      ]
    }
  ]
}
