# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectdisassembler --rom ROM
from randomizer.data.roomobjecttables import ObjectType, Initiator, PostBattle, RadialDirection, Music, Edge, ExitType, Locations, Rooms, PartitionBufferTypes, PartitionMainSpace
room = {
  "partition": None,
  "music": Music._54_HAPPY_ADVENTURE_DELIGHFUL_ADVENTURE,
  "entrance_event": 15,
  "event_tiles": [],
  "exit_fields": [],
  "objects": []
}
