# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py objectsequencedisassembler --rom ROM > openmode_sequence_debug.txt
from randomizer.helpers.objectsequencetables import SequenceSpeeds, VramPriority, _0x08Flags, _0x0AFlags, _0x10Flags
from randomizer.helpers.eventtables import RadialDirections, AreaObjects, NPCPackets, Sounds, Coords, CoordUnits, Rooms
script = [
    {
        "identifier": 'ACTION_518_fixed_f_coord_on_0',
        "command": 'fixed_f_coord_on'
    },
    {
        "identifier": 'ACTION_518_set_animation_speed_1',
        "command": 'set_animation_speed',
        "args": [SequenceSpeeds.FAST, [_0x10Flags.WALKING]]
    },
    {
        "identifier": 'ACTION_518_shift_northeast_pixels_2',
        "command": 'shift_northeast_pixels',
        "args": [4]
    },
    {
        "identifier": 'ACTION_518_fixed_f_coord_off_3',
        "command": 'fixed_f_coord_off'
    },
    {
        "identifier": 'ACTION_518_face_northeast_4',
        "command": 'face_northeast'
    },
    {
        "identifier": 'ACTION_518_shift_northeast_pixels_5',
        "command": 'shift_northeast_pixels',
        "args": [6]
    },
    {
        "identifier": 'ACTION_518_visibility_off_6',
        "command": 'visibility_off'
    },
    {
        "identifier": 'ACTION_518_ret_7',
        "command": 'ret'
    }
]
