# Debug mode config
# house_exit:
#   room: 400
#   x: 2
#   y: 66
#   z: 0
#   direction: NORTHEAST
# bosses:
# shift: 0
# override:
# Valentina: CountdownBoss
# Mack: BowyerBoss
# HammerBros: SmithyBoss
# Mack: CountdownBoss
# Booster: DirectorBoss
items:
  start:
    - CastleKey1
    - CastleKey2
    - BambinoBomb
    - ShinyStone
    - BrightCard
    - SignalRing
    - ShedKey
    - SeeYa
  override:
    MushroomWay1: BanditsWayStar
    MushroomWay2: BanditsWayStar
    MushroomWay3: BanditsWayStar
    BanditsWayStarChest: BanditsWayStar
    BanditsWayDogJump: BanditsWayStar
    KeroSewersStarChest: BanditsWayStar
    RoseWayFiveChests1: BanditsWayStar
    RoseWayFiveChests2: BanditsWayStar
    RoseWayFiveChests3: BanditsWayStar
    RoseWayFiveChests4: BanditsWayStar
    RoseWayFiveChests5: BanditsWayStar
    ForestMazeUnderground2: BanditsWayStar
    ForestMazeUnderground3: BanditsWayStar
    ForestMazeRedEssence: BanditsWayStar
    ForestMazeSecret1: BanditsWayStar
    ForestMazeSecret2: BanditsWayStar
    ForestMazeSecret3: BanditsWayStar
    ForestMazeSecret4: BanditsWayStar
    ForestMazeSecret5: BanditsWayStar
    MolevilleMinesStarChest: BanditsWayStar
    MolevilleMinesCoins: BanditsWayStar
    BOOSTER_TOWER_SPOOKUM: BanditsWayStar
    SEA_STAR_CHEST: BanditsWayStar
    SUNKEN_SHIP_RAT_STAIRS: BanditsWayStar
    SUNKEN_SHIP_COINS_1: BanditsWayStar
    SUNKEN_SHIP_COINS_2: BanditsWayStar
    SUNKEN_SHIP_CLONE_ROOM: BanditsWayStar
    SUNKEN_SHIP_FROG_COIN_ROOM: BanditsWayStar
    SUNKEN_SHIP_HIDON_MUSHROOM: BanditsWayStar
    LandsEndChowPit1: BanditsWayStar
    LandsEndChowPit2: BanditsWayStar
    LandsEndBeeRoom: BanditsWayStar
    LandsEndSecret1: BanditsWayStar
    LandsEndStarChest1: BanditsWayStar
    LandsEndStarChest2: BanditsWayStar
    LandsEndStarChest3: BanditsWayStar
    NIMBUS_LAND_BEFORE_BIRDETTA_1: BanditsWayStar
    NIMBUS_LAND_BEFORE_BIRDETTA_2: BanditsWayStar
    NimbusCastleSingleGoldBird: BanditsWayStar
    NimbusCastleAfterEgg2: BanditsWayStar
    NimbusCastleStarChest: BanditsWayStar
    BarrelVolcanoStarRoom: BanditsWayStar
    BarrelVolcanoSaveRoom2: BanditsWayStar
