from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=14,
        y=122,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = True,
        byte_2_bit_2 = False,
        destination = R024_SUNKEN_SHIP_POSTKC_AREA_15_BANDANA_RED_ROOM_WLONG_STAIRWELL,
        show_message = False,
        dst_x = 10,
        dst_y = 112,
        dst_z = 6,
        dst_z_half = True,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=17,
        y=115,
        z=2,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R028_SUNKEN_SHIP_POSTKC_AREA_17_JOHNNYS_ROOM,
        show_message = False,
        dst_x = 24,
        dst_y = 120,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
