"""NPC list import"""

from randomizer.entities.rooms.object_imports import *

objects = [
    # NPC_0
    RegularNPC(
        occupant=SavePoint,
        initiator=EventInitiator.JUMP_ON,
        event_script=E0080_SAVE_BLOCK_SUBROUTINE,
        action_script=A0120_EMBEDDED_ROUTINE,
        speed=0,
        visible=True,
        x=18,
        y=13,
        z=0,
        z_half=True,
        direction=SOUTHWEST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=True,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=False,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=True,
        byte3_bit7=False,
        slidable_along_walls=False,
        cant_move_if_in_air=True,
        byte7_upper2=True,
        priority_0=True,
        priority_1=True,
        priority_2=False,
        show_shadow=False,
        cannot_clone=True,
    ),
    # NPC_1
    RegularNPC(
        occupant=BlockShadow,
        initiator=EventInitiator.NONE,
        event_script=E0256_RETURN,
        action_script=A0015_DO_NOTHING,
        speed=0,
        visible=True,
        x=18,
        y=13,
        z=0,
        z_half=False,
        direction=SOUTHWEST,
        face_on_trigger=False,
        cant_enter_doors=False,
        byte2_bit5=False,
        set_sequence_playback=False,
        cant_float=False,
        cant_walk_up_stairs=False,
        cant_walk_under=False,
        cant_pass_walls=False,
        cant_jump_through=False,
        cant_pass_npcs=False,
        byte3_bit5=False,
        cant_walk_through=False,
        byte3_bit7=False,
        slidable_along_walls=False,
        cant_move_if_in_air=True,
        byte7_upper2=True,
        priority_0=False,
        priority_1=False,
        priority_2=True,
        cannot_clone=True,
    ),
]
