from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=12,
        y=62,
        z=2,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R017_MUSHROOM_KINGDOM_CASTLE_MAIN_HALL,
        show_message = False,
        dst_x = 8,
        dst_y = 30,
        dst_z = 2,
        dst_z_half = False,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=17,
        y=61,
        z=3,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R022_MUSHROOM_KINGDOM_CASTLE_GUEST_ROOM,
        show_message = False,
        dst_x = 22,
        dst_y = 52,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=13,
        y=70,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=2,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R031_MUSHROOM_KINGDOM_CASTLE_VAULT,
        show_message = False,
        dst_x = 6,
        dst_y = 90,
        dst_z = 2,
        dst_z_half = True,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
]
