from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=4,
        y=13,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=1,
        nw_se_edge_active = True,
        ne_sw_edge_active = True,
        byte_2_bit_2 = False,
        destination = R152_MARRYMORE_CHAPEL_MAIN_HALL,
        show_message = False,
        dst_x = 10,
        dst_y = 41,
        dst_z = 1,
        dst_z_half = True,
    dst_f = NORTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=9,
        y=15,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=1,
        nw_se_edge_active = True,
        ne_sw_edge_active = True,
        byte_2_bit_2 = False,
        destination = R156_MARRYMORE_CHAPEL_KITCHEN_NO_SPRITESEXITS_UNUSED,
        show_message = False,
        dst_x = 2,
        dst_y = 91,
        dst_z = 1,
        dst_z_half = True,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
