from randomizer.entities.rooms.event_imports import *

events = [
    Event(
        event=E1859_FIREWORKS_HOUSE_EXIT_TO_EXTERIOR,
        x=11,
        y=44,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0263_BOUNCE_ON_BED,
        x=13,
        y=34,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0263_BOUNCE_ON_BED,
        x=13,
        y=35,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0263_BOUNCE_ON_BED,
        x=14,
        y=37,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
    Event(
        event=E0263_BOUNCE_ON_BED,
        x=15,
        y=38,
        z=1,
        f=EdgeDirection.SOUTHEAST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_8_bit_4 = False,
    ),
]
