from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=19,
        y=32,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R272_MOLEVILLE_MINES_AREA_11_BOMBED_ROOM_WSINGING_MOLES,
        show_message = False,
        dst_x = 9,
        dst_y = 14,
        dst_z = 0,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=21,
        y=23,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R285_MOLEVILLE_MINES_AREA_13_LONG_MINECART_TRACKS_ROOM,
        show_message = False,
        dst_x = 2,
        dst_y = 123,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=20,
        y=21,
        z=4,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R285_MOLEVILLE_MINES_AREA_13_LONG_MINECART_TRACKS_ROOM,
        show_message = False,
        dst_x = 1,
        dst_y = 121,
        dst_z = 4,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
]
