from randomizer.entities.rooms.exit_imports import *

exits = [
    RoomExit(
        x=14,
        y=61,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R134_SEA_AREA_03_SUPER_STAR_ROOM,
        show_message = False,
        dst_x = 18,
        dst_y = 97,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=4,
        y=57,
        z=0,
        f=EdgeDirection.SOUTHEAST,
        length=1,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R132_SEA_AREA_05_FROM_AREA_02_WSAVE_POINT,
        show_message = False,
        dst_x = 1,
        dst_y = 120,
        dst_z = 0,
        dst_z_half = False,
    dst_f = NORTHEAST,
        x_bit_7 = False,
    ),
    RoomExit(
        x=1,
        y=67,
        z=0,
        f=EdgeDirection.SOUTHWEST,
        length=2,
        height=0,
        nw_se_edge_active = True,
        ne_sw_edge_active = False,
        byte_2_bit_2 = False,
        destination = R133_SEA_AREA_06_WATER_ROOM_WWHIRLPOOLS,
        show_message = False,
        dst_x = 26,
        dst_y = 36,
        dst_z = 5,
        dst_z_half = False,
    dst_f = SOUTHWEST,
        x_bit_7 = False,
    ),
]
